### ISSUE TITLE
Provide scaler for Datadog metrics

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda#1002]
Provide scaler for Datadog metrics.

https://docs.datadoghq.com/metrics/

**Comment by erickhun** [comment]
One of the use case would be to use keda to grab altogether AWS cloudwatch metrics and  custom metrics in Datadog (such as APM). 

Datadog provides their own [autoscaling solution](https://www.datadoghq.com/blog/autoscale-kubernetes-datadog/), but some metrics from your [cloud provider (AWS cloudwatch, GCP, Azure, etc...) are delayed up to 15 minutes](AWS, Azure, GCP) what isn't great when you need to auto-scale without delay.

**Comment by tomkerkhove** [comment]
Great to hear, are you willing to contribute this? I think this would be a great addition!

**Comment by tomkerkhove** [comment]
@arapulido is working on this

**Comment by JacobHenner** [comment]
I believe this can be closed (implemented in https://github.com/kedacore/keda/pull/2354)
