### ISSUE TITLE
Provide scaler for Elastic Metricbeat metrics

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda#1003]
Provide scaler for Elastic Metricbeat metrics.

https://www.elastic.co/beats/metricbeat

**Comment by melisatanrverdi** [comment]
Hi, I am interested this issue, could you please give more details about it?

**Comment by tomkerkhove** [comment]
It looks like I've misread and it's just a way to use agents to get metrics into a variety of output systems such as [Elasticsearch and more](https://www.elastic.co/guide/en/beats/metricbeat/current/configuring-output.html) so I will close this issue, sorry.

I'm opening https://github.com/kedacore/keda/issues/1756 for Elasticsearch instead.
