### ISSUE TITLE
Add information to NOTES.txt in helm chart

### ISSUE THREAD

**Issue by lee0c** [kedacore/keda#102]
Add installation notes, next steps, methods to see output, etc to NOTES.txt - some general information that would be useful to someone who has just installed the chart.

Most likely: note about config-ing scaledobjects, note about seeing which External Metrics are in use via apis/external.metrics... link, how to see current hpas, etc

**Comment by tomkerkhove** [comment]
@jeffhollan I would consider this as required for v1.0

**Comment by tomkerkhove** [comment]
Feel free to assign this to me, but we'll need to lock down what we want to list

**Comment by tomkerkhove** [comment]
Let's start with just providing a command to show how to get the installed ScaledObject & HPAs.

I will pick that up.

**Comment by ahmelsayed** [comment]
Closed in #315
