### ISSUE TITLE
keda-operator memory pressure

### ISSUE THREAD

**Issue by hila3000** [kedacore/keda#1033]
Hi,

I opened it initially as a discussion but I think it might be a bug.

We're using keda in Production.
I've noticed keda-operator pods are being evicted due to memory pressure.
When checking the graphs, it just seems like a memory leak that keeps up until it reaches 10GB, then the pod gets evicted.

My question is-
Is it reasonable for keda-operator to reach 10GB of memory consumption?
Anything in configuration I should set to avoid that if it's not a valid consumption (like requests and limit resources settings in the keda-deployment)? or change the `pollingInterval: 5` to less frequent?

## Expected Behavior
steady memory usage of X memory, I should expect up to 1GB, but steady nevertheless.

## Actual Behavior
Increasing memory usage up to 10GB, then the pods gets evicted. Seems like a memory leak.

## Steps to Reproduce the Problem
I don't know if it happens on all keda implementations or just production ones in which we currently have 56 scaledobjects. 

## Specifications

  - **KEDA Version:** 1.5.0
  - **Platform & Version:** GCP GKE, not sure what you mean by version.
  - **Kubernetes Version:** gke master version: 1.14.10-gke.42
  - **Scaler(s):** ScaledObjects based on a Pub/Sub subscription, cooldownPeriod: 300, pollingInterval: 5

Thanks,
Hila

**Comment by hila3000** [comment]
Update - I've changed the pollingInterval from 5 to 60, the usage is now moderated but still in an increasing trend.

**Comment by balchua** [comment]
@hila3000 this is related to the gcp scaler issue you had right?  Is it a good time to close this one?

**Comment by hila3000** [comment]
Indeed. Thank you!

**Comment by o0oRiCHQRD** [comment]
@hila3000 surely some forwarding information would be helpful to add to this??? my team finally found a thread describing the same issue as we are experiencing and then it just dies with a reference to an unlinked problem.

Please update the post with some follow on context and a link?

thanks.

**Comment by hila3000** [comment]
@o0oRiCHQRD The issue got resolved by using the new images @zroubalik provided-
KEDA Operator: docker.io/zroubalik/keda:gcpclose
KEDA Metrics Adapter: docker.io/zroubalik/keda-metrics-adapter:gcpclose
+ setting min and max limits on the deployment.

I've asked in the relevant issue corresponding (https://github.com/kedacore/keda/issues/1062) if the fixes from the above images exist in keda 2.0.0 and forward?

**Comment by zroubalik** [comment]
please note that those images are not official, I produced them just for testing purposes. I deifinitely recommend an update  to KEDA v2

**Comment by hila3000** [comment]
Yeah, I just mentioned it here to make sure the fixes are in the official v2.
Once you confirmed it, definitely should use v2 and not the ones I mentioned.
