### ISSUE TITLE
High vulnerabilities in keda 1.5 docker image

### ISSUE THREAD

**Issue by ansonauhk** [kedacore/keda#1039]
Our Sysdig enterprise image scan is picking up 36 vulnerabilities. Is it possible to scan and fix them before releasing an image? This can help enterprise adoption of KEDA

Some highlight 
RHSA-2020:2637
RHSA-2020:0271
RHSA-2020:0273
RHSA-2020:0575
RHSA-2020:2755

- KEDA Version:1.5.0

**Comment by tomkerkhove** [comment]
I'll take this up, sorry about that.

See #1040, #1041 & https://github.com/kedacore/charts/issues/64

**Comment by tomkerkhove** [comment]
@zroubalik @ahmelsayed We should include this in 2.0 and maybe ship 1.5.1 for this.

**Comment by zroubalik** [comment]
agree 2.0 should include this for sure

**Comment by tomkerkhove** [comment]
These should be mitigated in v2.0, can you have a look please?

**Comment by tomkerkhove** [comment]
Closing due to no response
