### ISSUE TITLE
Setup container scanning on-push

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda#1040]
Setup container scanning on-push with Snyk

**Comment by tomkerkhove** [comment]
GitHub Actions that I'll use:
- https://github.com/snyk/actions/tree/master/docker
- https://github.com/snyk/actions/tree/master/golang

**Comment by tomkerkhove** [comment]
This will be incorporated in master/nightly build.

**Comment by tomkerkhove** [comment]
This is setup to scan Dockerfile during PRs:
![image](https://user-images.githubusercontent.com/4345663/96877198-a4001800-1479-11eb-8934-3f19c95cbac4.png)

Maintainers can view the report in Snyk, unfortunately we cannot make it public.

**Comment by zroubalik** [comment]
@tomkerkhove I think this is alread done, am I right?

**Comment by tomkerkhove** [comment]
Yes, through their integration but checking with CNCF to get more insights and apparently GH Actions is the best way to go!

**Comment by idvoretskyi** [comment]
@tomkerkhove what is the issue with the Snyk app/integration?

**Comment by tomkerkhove** [comment]
Nothing, but I thought you wanted to use GitHub Actions instead of it because of our open Snyk Pro ticket?
