### ISSUE TITLE
Azure monitor scaler should use new azure-sdk-go version because of an bugfix inside the MetricValue struct

### ISSUE THREAD

**Issue by christle** [kedacore/keda#1049]
We want to use the azure monitor scaler for scaling our http-trigger azure functions with keda. but the scaler gets the following error for the aggregationtype "Count"

```
Error occurred unmarshalling JSON - Error = 'json: cannot unmarshal number "6.0" into Go struct field MetricValue.value.timeseries.data.count of type int64'
```

The current version from the azure monitor scaler use this package reference:
https://github.com/kedacore/keda/blob/57ffd4ee384db38f1169453cb16b31f00eacffa5/pkg/scalers/azure/azure_monitor.go#L11

The problem above is fixed in a newer version of the azure sdk for go:
https://github.com/Azure/azure-sdk-for-go/blob/ff2ed3f45ee513326efc7d6d5e845ddc6ee9adf8/services/preview/monitor/mgmt/2019-06-01/insights/models.go#L3976

i think we should reference the new one. 

### Steps to Reproduce the Problem

 Use an Azure Monitor scaler with for this metric:
 ```
metricName: requests/count
resourceURI: Microsoft.Insights/components/appinsightsname
metricAggregationType: Count
````
### Specifications

  - **KEDA Version:** 1.5
  - **Scaler(s):** Azure Monitor

**Comment by tomkerkhove** [comment]
Thanks for the tip, are you willing to contribute this to our v2 branch?

**Comment by christle** [comment]
sure, i will do it the next couple of days

**Comment by zroubalik** [comment]
@christle awesome, as Tom mentioned, please contribute this to v2 branch: https://github.com/kedacore/keda/tree/v2

**Comment by christle** [comment]
Today, i finally found the time to fix this issue on the v2 branch. But i realized that the issue is fixed with the change on v2: https://github.com/kedacore/keda/commit/4abddb39b30189c1af067bf93bead1ab67c77f1d

I think on v2 exists a dependency update for "github.com/Azure/go-autorest/autorest/azure/auth" and the commit above change the type for count from int to float.

So it is fixed on v2

**Comment by tomkerkhove** [comment]
Great to hear, ok if I close it?

**Comment by christle** [comment]
yes
