### ISSUE TITLE
Make api/v1alpha1 revive compatible

### ISSUE THREAD

**Issue by turbaszek** [kedacore/keda#1054]
KEDA uses [golint](https://github.com/golang/lint) to ensure code quality. However, some files still need adjusting:

- [ ] api/v1alpha1/condition_types.go
- [ ] api/v1alpha1/groupversion_info.go
- [ ] api/v1alpha1/gvkr_types.go
- [ ] api/v1alpha1/scaledjob_types.go
- [ ] api/v1alpha1/scaledobject_types.go
- [ ] api/v1alpha1/triggerauthentication_types.go

### How 

1. Create a new branch from `v2`branch
2. Remove the files from list in [Makefile](https://github.com/kedacore/keda/blob/5fe6c52ad38a44726b74e1339e7197e193d1c26c/Makefile#L212-L242)
3. Run `make revive`
4. Commit your changes and open a PR to `v2`

### Reference
https://github.com/kedacore/keda/pull/1025#discussion_r475134492

**Comment by aman-bansal** [comment]
Hi @turbaszek and @tomkerkhove, I picked this issue. Have raised the PR. Please review.
