### ISSUE TITLE
Make pkg/scaling revive compatible

### ISSUE THREAD

**Issue by turbaszek** [kedacore/keda#1057]
KEDA uses [golint](https://github.com/golang/lint) to ensure code quality. However, some files still need adjusting:

- [ ] pkg/scaling/executor/scale_executor.go
- [ ] pkg/scaling/resolver/hashicorpvault_handler.go
- [ ] pkg/scaling/resolver/scale_resolvers.go
- [ ] pkg/scaling/resolver/scale_resolvers_test.go

### How 

1. Create a new branch from `v2`branch
2. Remove the files from list in [Makefile](https://github.com/kedacore/keda/blob/5fe6c52ad38a44726b74e1339e7197e193d1c26c/Makefile#L212-L242)
3. Run `make revive`
4. Commit your changes and open a PR to `v2`

### Reference
https://github.com/kedacore/keda/pull/1025#discussion_r475134492

**Comment by rahulrai-in** [comment]
Can I take this issue to get familiar with the code? Thanks.

**Comment by zroubalik** [comment]
@rahulrai-in great, go ahead!

**Comment by rahulrai-in** [comment]
> @rahulrai-in great, go ahead!

@zroubalik Thanks. Can you assign it to me?

**Comment by aman-bansal** [comment]
I think we can close this issue. There are no more revive issues. Solved and merged here #1128 .
cc. @turbaszek @zroubalik
