### ISSUE TITLE
Allow zero target queueLength for rabbitmq

### ISSUE THREAD

**Issue by spacem** [kedacore/keda#1064]
### Use-Case
Not sure if this is a bug or feature request.. or maybe I am doing it wrong?

* We have a user queue up a long running job then we see scale up from zero ie. a pod is created for that job - great!
* Now a 2nd user queues up a job.. we would like a 2nd pod be created for this new job

I am using rabbitmq with AKS and kubernetes 1.17.7.

### Specification

In my mind to achieve this we would just set a target queue length to zero but when I try this I get no scale happen and see this error in the keda operator:
```
"error":"HorizontalPodAutoscaler.autoscaling \"keda-hpa-exporter\" is invalid: spec.metrics[0].external.target.averageValue:
Invalid value: resource.Quantity{i:resource.int64Amount{value:0, scale:0}, d:resource.infDecAmount{Dec:(*inf.Dec)(nil)}, s:\"0\", Format:\"DecimalSI\"}: must be positive"
```

If I set the target queue length to one ("1") the 2nd job sits in the queue. A 2nd pod is only created when the 3rd job is queued (ie. when the queue length gets to 2).

Edit: I see something similar can be done by scaling "jobs" instead of "deployments". Implementing would mean changes to our consumers pods to terminate after processing but when I test this with high maxReplicaCount it seems to only create one pod. If I set high parallel setting it seems to create that many even if there is just two needed.

**Comment by mboutet** [comment]
@spacem, did you say that you had the same problem even by using the ScaledJob instead of ScaledObject?

**Comment by obean** [comment]
Bump

**Comment by theomessin** [comment]
Bump

**Comment by JorTurFer** [comment]
Hi @obean and @theomessin 
Do you have the same issue? Could you open a new issue with the info to track it?
This issue has more than a year
