### ISSUE TITLE
Redis List scaler/e2e tests are broken

### ISSUE THREAD

**Issue by zroubalik** [kedacore/keda#1066]
Redis list e2e tests are failing on v2 branch in the code brought by this PR: https://github.com/kedacore/keda/pull/1013

KEDA Operator logs:
```
2020-09-01T07:13:00.886Z	ERROR	redis_scaler	error	{"error": "list must be of type:list,set,hash,zset but was none"}
github.com/go-logr/zapr.(*zapLogger).Error
	/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128
github.com/kedacore/keda/pkg/scalers.(*redisScaler).IsActive
	/workspace/pkg/scalers/redis_scaler.go:148
github.com/kedacore/keda/pkg/scaling.(*scaleHandler).checkScaledObjectScalers
	/workspace/pkg/scaling/scale_handler.go:203
github.com/kedacore/keda/pkg/scaling.(*scaleHandler).checkScalers
	/workspace/pkg/scaling/scale_handler.go:192
github.com/kedacore/keda/pkg/scaling.(*scaleHandler).startScaleLoop
	/workspace/pkg/scaling/scale_handler.go:134
```

In the e2e tests Redis returns `none` [type](https://redis.io/commands/type).

https://github.com/kedacore/keda/blob/f5064f69ebba673b5757afb5ca9bacf9368dba4b/pkg/scalers/redis_scaler.go#L216-L227

Should we default to `list` type in case the returned type is `none`, that was AFAIK the original solution, before this part was changed in the PR?

Or are the e2e tests wrong?

## Specifications

  - **KEDA Version:** v2
  - **Scaler(s):** Redis List

**Comment by zroubalik** [comment]
@ilyamor ^

**Comment by balchua** [comment]
@zroubalik looking at v1, keda only supported `list` type.  I suppose that should be the default if its empty.
My 2 cents.
