### ISSUE TITLE
Decouple go fmt and vet from building docker image

### ISSUE THREAD

**Issue by turbaszek** [kedacore/keda#1070]
### Use-Case

Currently when users build the image we run `go fmt` and `go vet` as a step:
```
Step 14/19 : RUN make manager
 ---> Running in b436cbd21bce
...
go fmt ./...
go vet ./...
```

It takes some time and seems not necessary for the successful build of the image. 

Additionally, on `v2` we have code quality checks on CI.  What I would suggest is:
1. Keep `gofmt` and `govet` in Makefile so people can use them
1. Don't run them when building anything
1. Add `go vet` to pre-commits so we can easily run them in code quality check (fmt is already there)

I'm happy to open a PR if we think it's reasonable.

**Comment by arschles** [comment]
I'm happy to take this on
