### ISSUE TITLE
Support basic authentication for Metrics API scaler

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda#1082]
### Use-Case

Support basic authentication for Metrics API scaler

### Reference 
https://github.com/kedacore/keda/issues/929

**Comment by aman-bansal** [comment]
Hi @tomkerkhove, I would like to pick this issue. Based on this thread, I believe no one is doing any development on this. Just wanted to check if I can start.

**Comment by tomkerkhove** [comment]
Nope, that is correct. Thanks for picking this up!

**Comment by aman-bansal** [comment]
Great! I'm starting with this. Thanks!

**Comment by aman-bansal** [comment]
@tomkerkhove this is done. can we please close this issue.

**Comment by tomkerkhove** [comment]
Thanks!
