### ISSUE TITLE
Support API Key authentication for Metrics API scaler

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda#1083]
### Use-Case

Support API Key authentication for Metrics API scaler

### Specification

- [x] Support for API key in HTTP URL
- [ ] Support for API key in HTTP request header

### Reference 
https://github.com/kedacore/keda/issues/929

**Comment by aman-bansal** [comment]
Hi @tomkerkhove, I would like to pick this issue. Based on this thread, I believe no one is doing any development on this. Just wanted to check if I can start.

**Comment by tomkerkhove** [comment]
Nope, that is correct. Thanks for picking this up!

**Comment by aman-bansal** [comment]
Perfect. So what I get from the description is that we wanted to integrate API Key (which will be available in the metadata) to be appended to the http URL like this `http://myapp/metric/endpoint?api_key=<metadata.APIKEY>`. I believe this is the standard implementation practice or do we need customization in defining the query param name?

**Comment by tomkerkhove** [comment]
Today, they have to provide the full URL to call - https://keda.sh/docs/2.0/scalers/metrics-api/

In theory they can add the API key in there already but I'd prefer not to. What we want to achieve here is:
- API key support through request header
- API key support through query parameter

For both I would provide a standard header/query parameter name, but with the option to define their own in case they deviate from the mainstream. Make sense?

**Comment by aman-bansal** [comment]
Got it. All clear now. I am starting with this. Thanks!

**Comment by aman-bansal** [comment]
@tomkerkhove this is done. can we close this issue :)

**Comment by tomkerkhove** [comment]
Thanks!
