### ISSUE TITLE
Support client certificate authentication for Metrics API scaler

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda#1084]
### Use-Case

Support client certificate authentication for Metrics API scaler

### Reference 
https://github.com/kedacore/keda/issues/929

**Comment by ddmendes** [comment]
Hello! I'd like to work on this issue

**Comment by tomkerkhove** [comment]
Thanks! But we already have a PR in the works, sorry..

**Comment by ddmendes** [comment]
Oh, sorry, didn't notice, just checked there was no one assigned

**Comment by girishramnani** [comment]
Seems like the related PR #1137 was merged, can this issue be closed?

**Comment by tomkerkhove** [comment]
Jup, sorry about that!
