### ISSUE TITLE
Consider renaming "master" to "main"

### ISSUE THREAD

**Issue by turbaszek** [kedacore/keda#1092]
> Many communities, both on GitHub and in the wider Git community, are considering renaming the default branch name of their repository from `master`. GitHub is gradually renaming the default branch of our own repositories from `master` to `main`.

source: https://github.com/github/renaming

I would like to propose considering similar change in KEDA project. The current moment seems to be a good one as there is no PR opened to `mater` (this is a big problem in other OSS projects). 

Happy to hear the opinion of maintainers @zroubalik @tomkerkhove @ahmelsayed @jeffhollan

**Comment by jeffhollan** [comment]
Supportive of this and also had same thought the other day when opening PRs

**Comment by tomkerkhove** [comment]
Fine by me, as long as all repos are aligned.

**Comment by turbaszek** [comment]
> all repos are aligned

By this we mean all repos in kedacore?

**Comment by zroubalik** [comment]
Yeah

**Comment by tomkerkhove** [comment]
If we sit back and wait, GitHub will do it for us; and probably break our automation 🤓

**Comment by zroubalik** [comment]
done
