### ISSUE TITLE
Consideration for Maintainership for Tomek Urbaszek

### ISSUE THREAD

**Issue by turbaszek** [kedacore/keda#1093]
Hello everyone!

As described in [GOVERNANCE.md](https://github.com/kedacore/keda/blob/v2/GOVERNANCE.md) I am raising this issue to let you know that I'm happy to volunteer as a maintainer of KEDA. I'd love to share some of my open-source experience with this community and learn even much more from you.

**Comment by tomkerkhove** [comment]
We've had a chat with Tomek offline and are happy to have him part of our community but our maintainer board is full at the moment so we cannot have him as a new maintainer.

That does not mean we do not appreciate his work and if our maintainer board changes, we will definitely consider him to become a maintainer!

Keep on doing what you do @turbaszek, we highly appreciate your work!
