### ISSUE TITLE
Can the docker image name be changed from keda-metrics-adapter to keda-metrics-apiserver?

### ISSUE THREAD

**Issue by ckuduvalli** [kedacore/keda#1105]
Currently we are using the name keda-metrics-apiserver for POD_NAME, SERVICE_NAME and so on. Only the docker image is called keda-metrics-adapter. Can we please change the docker image name also to keda-metrics-apiserver when v2 is released?

@zroubalik @tomkerkhove 
Kindly suggest

**Comment by tomkerkhove** [comment]
I'll leave this up to @zroubalik but for me this sounds ok.

**Comment by zroubalik** [comment]
Sounds good to me. @ckuduvalli are you willing to contribute this?

**Comment by ckuduvalli** [comment]
yes i will change it and send a pr

**Comment by tomkerkhove** [comment]
Awesome, thanks! Would you mind updating our Helm charts as well?

**Comment by ckuduvalli** [comment]
@tomkerkhove @zroubalik 
For this change, I am not sure what to add and where to add documentation in keda-docs. Also, not sure about tests and changelog. Kindly help.

@tomkerkhove 
could you please let me know how to update helm charts for this change?

**Comment by zroubalik** [comment]
Reopening for helm charts

**Comment by zroubalik** [comment]
@ckuduvalli tests are not needed imho, and for changelog. I'll include this note to my already opened PR for changelog:https://github.com/kedacore/keda/pull/1086

**Comment by ckuduvalli** [comment]
Thank you @zroubalik

**Comment by ckuduvalli** [comment]
@zroubalik @tomkerkhove 
Have made the helm charts change
https://github.com/kedacore/charts/pull/66

**Comment by tomkerkhove** [comment]
Should we add this to https://github.com/kedacore/keda-docs/blob/master/content/docs/2.0/migration.md @zroubalik ?

**Comment by zroubalik** [comment]
@tomkerkhove IMHO it is not needed, it is covered in Changelog and this change is not something that is directly affecting users.

**Comment by flyingfang** [comment]
Hey, there is a a bug in the pr...The image key "metricsAdapter" in values.yaml has not been changed.

**Comment by tomkerkhove** [comment]
This you mean? https://github.com/kedacore/charts/pull/66/files#diff-c7bc2dee6b0e6a8755bd9c0383b7a103R7

**Comment by flyingfang** [comment]
> This you mean? https://github.com/kedacore/charts/pull/66/files#diff-c7bc2dee6b0e6a8755bd9c0383b7a103R7

should be  "metricsApiServer: docker.io/kedacore/keda-metrics-apiserver:1.5.0"

**Comment by tomkerkhove** [comment]
Woops, thanks for letting us know! Fixing it now.
