### ISSUE TITLE
Adjust revive configuration

### ISSUE THREAD

**Issue by turbaszek** [kedacore/keda#1107]
In #1104 we abandoned golint because it was abandoned by the community that was maintaining it. Instead, we decided to use [revive](https://github.com/mgechev/revive) which provides more configuration options.

Currently our `revive.toml` which is a configuration file fo revive uses setup from tidb:
https://github.com/pingcap/tidb/blob/master/tools/check/revive.toml

We may consider adjusting used rules to our needs. List of available rules is here:
https://github.com/mgechev/revive#available-rules

**Comment by silenceper** [comment]
already use golangci #1155

/close
