### ISSUE TITLE
Authentication and Authz of API server

### ISSUE THREAD

**Issue by Aarthisk** [kedacore/keda#111]
1. The API server should not use self signed certs ina  true production environment
2 The HPA should have access to the API server for scaling without running as cluster-admin.

**Comment by jeffhollan** [comment]
What's the status of this? Is it in your "current" set of work items or should we punt?

**Comment by iyacontrol** [comment]
hi @Aarthisk Do you mean too much permissions for keda-operator?

**Comment by zroubalik** [comment]
`cluster-admin` permissions were removed as part of the recent refactoring.

**Comment by jeffhollan** [comment]
Thanks @zroubalik  - I assume that means we can close this?

**Comment by zroubalik** [comment]
@jeffhollan The API server is still using self signed certs, so the point 1. is still unresolved

**Comment by tomkerkhove** [comment]
Moving to v1.2
