### ISSUE TITLE
Custom Resources (CRD) file is not showing on AKS cluster after installing Keda

### ISSUE THREAD

**Issue by sanprasingh** [kedacore/keda#1110]
Hi Team,
Below Custom Resources (CRD) file is not showing on AKS cluster after installing Keda.
scaledobjects.keda.k8s.io
triggerauthentications.keda.k8s.io

is it required for scaling ?

Thanks.

**Comment by tomkerkhove** [comment]
Yes it is, how did you install KEDA?
