### ISSUE TITLE
Update .devcontainer config to comply with the latest changes

### ISSUE THREAD

**Issue by zroubalik** [kedacore/keda#1114]
We have introduced changes in the project layout etc. with the update to Operator SDK v1.0.0 #1007 

It is needed update `.devcontainer` config, Dockerfile: https://github.com/kedacore/keda/tree/v2/.devcontainer

**Comment by zroubalik** [comment]
@kashifsoofi expressed an interest in covering this issue, thx

**Comment by girishramnani** [comment]
@zroubalik is this issue taken? if not, I would like to work on this.

**Comment by zroubalik** [comment]
@girishramnani a couple months ago @kashifsoofi mentioned, that he would like to contribute this, but haven't heard from him since then. Would be great if you can take this :)

**Comment by girishramnani** [comment]
understood, moving forward on this.

**Comment by kashifsoofi** [comment]
thanks @girishramnani all yours, apologies guys i should have left comment on issue earlier, i did 1 pr to update, not sure if it covered everything required

**Comment by zroubalik** [comment]
Ouch, sorry for the confusion guys! @kashifsoofi I can see your PR now, I forgot about it completely, sorry.

Is everything solved then and we can close this issue?

PR for reference: https://github.com/kedacore/keda/pull/1140

**Comment by kashifsoofi** [comment]
Let @girishramnani have a look, there might be something missing.

**Comment by girishramnani** [comment]
Sure, I will play around with it quickly and get back with my findings.

**Comment by girishramnani** [comment]
noticed a small nit that the devcontainer.json was using `ms-vscode.go` for the plugin extension id instead of `google.go` so updated that as part of the https://github.com/kedacore/keda/pull/1334
