### ISSUE TITLE
Azure Log Analyitcs e2e test is failing

### ISSUE THREAD

**Issue by zroubalik** [kedacore/keda#1150]
Nightly job is failing on this test:

https://github.com/kedacore/keda/runs/1109700318?check_suite_focus=true

```
 >>> scalers/azure-log-analytics.test.ts.log <<<

  ✖ before hook A required parameters LA scaler was not resolved
  ✖ 3 tests remaining in scalers/azure-log-analytics.test.ts

  1 hook failed

  before hook

  /__w/keda/keda/tests/scalers/azure-log-analytics.test.ts:14

   13:   if (!la_workspace_id || !sp_id || !sp_key || !sp_tenant) {  
   14:     t.fail('A required parameters LA scaler was not resolved')
   15:   }                                                           

  A required parameters LA scaler was not resolved
```

**Comment by zroubalik** [comment]
@spoplavskiy @ahmelsayed PTAL^

**Comment by spoplavskiy** [comment]
@zroubalik , @ahmelsayed 
Looks like not all parameters resolved from env. variables:

const la_workspace_id = process.env['TEST_LOG_ANALYTICS_WORKSPACE_ID']
const sp_id = process.env['AZURE_SP_ID']
const sp_key = process.env['AZURE_SP_KEY']
const sp_tenant = process.env['AZURE_SP_TENANT']

@ahmelsayed , can you double check those parameters exposed as env. variables on build machine? If they are named differently, let me know, I will change in test.

**Comment by spoplavskiy** [comment]
I think we can close this issue, as the last nightly e2e test has been executed successfully: https://github.com/kedacore/keda/actions/runs/258467884

@zroubalik , what do you think?

**Comment by zroubalik** [comment]
Yes, thanks for the fix!
