### ISSUE TITLE
Want to be the maintainer of the project

### ISSUE THREAD

**Issue by silenceper** [kedacore/keda#1161]
Hello KEDA community!

I want to join the project and become the maintainer of the project.

I have relatively rich experience in go projects, and I am very interested in improving the code quality of the project(such as #1155), maintaining new features, and fixing bugs.

At present, my work mainly revolves around Kubernetes to build a PaaS platform, and I often need to use the flexible scalability of kubernetes to expand applications.

I am currently working in China, and I can also help promote the project in China.

Thank you for your consideration!

**Comment by zroubalik** [comment]
Hi @silenceper,

I am very sorry for the delay with a response. 

Thanks a lot for your interested, we definitely welcome a help on improving the project. And thanks for your recent contributions too!
Unfortunately our maintainer board is full at the moment, so we cannot have you as a new maintainer. But as the maintainer board changes, we will definitely consider you to become a maintainer!

Pleae keep on  what you do, we highly appreciate your work!

**Comment by silenceper** [comment]
@zroubalik 
Thank you for your attention to my request and reply.
I also look forward to the day when I become a maintainer. 😄

**Comment by zroubalik** [comment]
Btw joining our community call is a good starting point 🙂
