### ISSUE TITLE
Support for pod identity for Azure Log Analytics scaler

### ISSUE THREAD

**Issue by carlwoodhouse** [kedacore/keda#1165]
Other azure scalers such as azure monitor support the ability to use azure pod identity for authentication; currently the azure log analyics scaler only supports service principle; it would be great if we could make it use podidentity :)

**Comment by tomkerkhove** [comment]
Definitely agree, are you willing to contribute this or just open the request?

**Comment by spoplavskiy** [comment]
@carlwoodhouse , @tomkerkhove 
Thanks for a feedback. This is something I'm working on right now.
I expect to introduce this feature till end of week.

**Comment by tomkerkhove** [comment]
Awesome, thanks @spoplavskiy!

**Comment by carlwoodhouse** [comment]
Excellent ! Thanks @spoplavskiy

**Comment by zroubalik** [comment]
Fixed in #1173
