### ISSUE TITLE
Issue "Not the leader" 

### ISSUE THREAD

**Issue by Sam8301-arch** [kedacore/keda#1166]
I had tried to restore KEDA but its operator failing with below messages and thus not starting up. Anyone face this issue?

{"level":"info","ts":1600307747.1605864,"logger":"cmd","msg":"KEDA Version: 1.5.0"}
{"level":"info","ts":1600307747.1606233,"logger":"cmd","msg":"Go Version: go1.14.4"}
{"level":"info","ts":1600307747.1606328,"logger":"cmd","msg":"Go OS/Arch: linux"}
{"level":"info","ts":1600307747.160639,"logger":"cmd","msg":"Version of operator-sdk: v0.11.0"}
{"level":"info","ts":1600307747.1608016,"logger":"leader","msg":"Trying to become the leader."}
{"level":"info","ts":1600307747.5870316,"logger":"leader","msg":"Not the leader. Waiting."}
{"level":"info","ts":1600307748.7144656,"logger":"leader","msg":"Not the leader. Waiting."}
{"level":"info","ts":1600307751.0974603,"logger":"leader","msg":"Not the leader. Waiting."}
{"level":"info","ts":1600307755.6356907,"logger":"leader","msg":"Not the leader. Waiting."}
{"level":"info","ts":1600307764.34399,"logger":"leader","msg":"Not the leader. Waitin

**Comment by silenceper** [comment]
From the log, it seems that the leader election failed. Have you started multiple of keda pod?

**Comment by zroubalik** [comment]
Yeah, please check that there isnt any other KEDA operator pod running.

**Comment by Sam8301-arch** [comment]
Hi Guys,

Log is keep popping up this leader election information and doing nothing, please see below information which you asked above.

kubectl get services,deployments,pods -n keda
NAME                                                              TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)             AGE
service/keda-operator-metrics                    ClusterIP   1xx.xx.xx.x6   <none>        8383/TCP,8686/TCP   xh
service/keda-operator-metrics-apiserver   ClusterIP   1xx.xx.xx.xx7   <none>        443/TCP,80/TCP      xh

NAME                                                    READY   UP-TO-DATE   AVAILABLE   AGE
deployment.extensions/keda-operator                     1/1     1            1           xh
deployment.extensions/keda-operator-metrics-apiserver   1/1     1            1           xh

NAME                                                   READY   STATUS    RESTARTS   AGE
pod/keda-operator-xxx                     1/1     Running   0          xh
pod/keda-operator-metrics-apiserver-xxxl   1/1     Running   0          xh

kubectl logs service/keda-operator-metrics-apiserver -n keda
I0917 01:55:49.621249       1 main.go:77] keda_metrics_adapter "msg"="KEDA Version: 1.5.0"  
I0917 01:55:49.621312       1 main.go:78] keda_metrics_adapter "msg"="KEDA Commit: 374adbe873aec8a8d351e818d3fb2108106ebeb6"  
I0917 01:55:49.621321       1 main.go:79] keda_metrics_adapter "msg"="Go Version: go1.14.4"  
I0917 01:55:49.621329       1 main.go:80] keda_metrics_adapter "msg"="Go OS/Arch: linux/xxx"  
I0917 01:55:50.025233       1 provider.go:47] keda_metrics_adapter/provider "msg"="starting"  
I0917 01:55:50.025261       1 main.go:96] keda_metrics_adapter "msg"="starting adapter..."  
I0917 01:55:50.711435       1 serving.go:312] Generated self-signed cert (apiserver.local.config/certificates/apiserver.crt, apiserver.local.config/certificates/apiserver.key)
I0917 01:55:50.968467       1 secure_serving.go:116] Serving securely on [::]:6443

kubectl logs keda-operator-xxx -n keda
{"level":"info","ts":1600380504.648097,"logger":"cmd","msg":"KEDA Version: 1.5.0"}
{"level":"info","ts":1600380504.648128,"logger":"cmd","msg":"Go Version: go1.14.4"}
{"level":"info","ts":1600380504.6481357,"logger":"cmd","msg":"Go OS/Arch: linux-xxx"}
{"level":"info","ts":1600380504.648143,"logger":"cmd","msg":"Version of operator-sdk: v0.11.0"}
{"level":"info","ts":1600380504.6483057,"logger":"leader","msg":"Trying to become the leader."}
{"level":"info","ts":1600380505.077344,"logger":"leader","msg":"Not the leader. Waiting."}
{"level":"info","ts":1600380506.210069,"logger":"leader","msg":"Not the leader. Waiting."}
{"level":"info","ts":1600380508.5996609,"logger":"leader","msg":"Not the leader. Waiting."}
{"level":"info","ts":1600380513.1394327,"logger":"leader","msg":"Not the leader. Waiting."}
{"level":"info","ts":1600380521.8489273,"logger":"leader","msg":"Not the leader. Waiting."}

Just wanted to check with you guys how to proceed from here, is this a know issue or may be some locked thing not printing on the logs?

**Comment by Sam8301-arch** [comment]
Hi again,  just want to follow up on this if you think what else is missing here. Thanks!

**Comment by Sam8301-arch** [comment]
@zroubalik @silenceper

**Comment by zroubalik** [comment]
@Sam8301-arch have you tried to completely uninstall KEDA?

**Comment by Sam8301-arch** [comment]
yes I have uninstalled KEDA and it worked when i did velero(backup/restore) of KEDA its stuck see both logs

**UNINSTALL LOG FILE:**
kubectl logs pod/keda-operator-xxx -n keda
{"level":"info","ts":1600305090.2607338,"logger":"cmd","msg":"KEDA Version: 1.5.0"}
{"level":"info","ts":1600305090.2607734,"logger":"cmd","msg":"Go Version: go1.14.4"}
{"level":"info","ts":1600305090.2607784,"logger":"cmd","msg":"Go OS/Arch: linux/amd64"}
{"level":"info","ts":1600305090.2607815,"logger":"cmd","msg":"Version of operator-sdk: v0.11.0"}
{"level":"info","ts":1600305090.2609844,"logger":"leader","msg":"Trying to become the leader."}
{"level":"info","ts":1600305092.6807027,"logger":"leader","msg":"No pre-existing lock was found."}
{"level":"info","ts":1600305092.6883569,"logger":"leader","msg":"Became the leader."}
{"level":"info","ts":1600305095.0938156,"logger":"controller-runtime.metrics","msg":"metrics server is starting to listen","addr":"0.0.0.0:8383"}
{"level":"info","ts":1600305095.0941236,"logger":"cmd","msg":"Registering Components."}
{"level":"info","ts":1600305095.0944548,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"scaledobject-controller","source":"kind source: /, Kind="}
{"level":"info","ts":1600305095.0945892,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"scaledobject-controller","source":"kind source: /, Kind="}
{"level":"info","ts":1600305098.45227,"logger":"metrics","msg":"Metrics Service object created","Service.Name":"keda-operator-metrics","Service.Namespace":"keda"}
{"level":"info","ts":1600305098.904427,"logger":"cmd","msg":"Could not create ServiceMonitor object","error":"no ServiceMonitor registered with the API"}
{"level":"info","ts":1600305098.9047391,"logger":"cmd","msg":"Install prometheus-operator in your cluster to create ServiceMonitor objects","error":"no ServiceMonitor registered with the API"}
{"level":"info","ts":1600305098.9048412,"logger":"cmd","msg":"Starting the Cmd."}
{"level":"info","ts":1600305098.907098,"logger":"controller-runtime.manager","msg":"starting metrics server","path":"/metrics"}
{"level":"info","ts":1600305099.0058148,"logger":"controller-runtime.controller","msg":"Starting Controller","controller":"scaledobject-controller"}
{"level":"info","ts":1600305099.1060016,"logger":"controller-runtime.controller","msg":"Starting workers","controller":"scaledobject-controller","worker count":1}

**ISSUE LOG:**
kubectl logs keda-operator-XXX -n keda
{"level":"info","ts":1600307747.1605864,"logger":"cmd","msg":"KEDA Version: 1.5.0"}
{"level":"info","ts":1600307747.1606233,"logger":"cmd","msg":"Go Version: go1.14.4"}
{"level":"info","ts":1600307747.1606328,"logger":"cmd","msg":"Go OS/Arch: linux/amd64"}
{"level":"info","ts":1600307747.160639,"logger":"cmd","msg":"Version of operator-sdk: v0.11.0"}
{"level":"info","ts":1600307747.1608016,"logger":"leader","msg":"Trying to become the leader."}
{"level":"info","ts":1600307747.5870316,"logger":"leader","msg":"Not the leader. Waiting."}
{"level":"info","ts":1600307748.7144656,"logger":"leader","msg":"Not the leader. Waiting."}
{"level":"info","ts":1600307751.0974603,"logger":"leader","msg":"Not the leader. Waiting."}
{"level":"info","ts":1600307755.6356907,"logger":"leader","msg":"Not the leader. Waiting."}
{"level":"info","ts":1600307764.34399,"logger":"leader","msg":"Not the leader. Waiting."}

Looks like its get locked somehow and not printing that lock information when I am restoring KEDA from velero? Any clue why its not printing that lock information?

**Comment by zroubalik** [comment]
OK, I am not familiar with velero, but that is the root of the problem. It probably doesn't release the lock when you did backup and restore. 

This is the leaderId used for the election:
https://github.com/kedacore/keda/blob/7a1fd919f5aea5af94939a84c371239c0fe2b364/main.go#L73

**Comment by Sam8301-arch** [comment]
is it possible we can release the lock or check lock status?

**Comment by zroubalik** [comment]
@Sam8301-arch you can try to delete configmap `operator.keda.sh` in the `keda` namespace, if there's any.
