### ISSUE TITLE
Not encoding data in the secret AWS SQS

### ISSUE THREAD

**Issue by therahulbhati** [kedacore/keda#1171]
In the documentation, in https://keda.sh/docs/2.0/scalers/aws-sqs/ its mentioned to store AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY directly without encoding, this works with KEDA. But if I want to use the same secret say with a POD by injecting the secret data and use as env variable as mentioned [here](https://kubernetes.io/docs/tasks/inject-data-application/distribute-credentials-secure/#configure-all-key-value-pairs-in-a-secret-as-container-environment-variables), due to default behavior it tries to decode the secret data. This causes inconsistency since we are not encoding the key and secret.

## Expected Behavior
To be consistent with Kubernetes practices

## Actual Behavior
Not consistent with Kubernetes practices

**Comment by tomkerkhove** [comment]
I'm updating the docs as this should not be the case: https://github.com/kedacore/keda-docs/pull/263

Can you share what you are seeing at runtime or is this purely when reading the docs?

**Comment by therahulbhati** [comment]
@tomkerkhove its working for us. The problem was from our side earlier we creating secrets using YAML, when created secret from file it worked. Thanks for the quick support!!
