### ISSUE TITLE
Uninstall instructions on the documentation is outdated

### ISSUE THREAD

**Issue by tecoholic** [kedacore/keda#1184]
The deployment section on the website has Uninstall instructions which refer to missing YAML files.

```
kubectl delete -f https://raw.githubusercontent.com/kedacore/keda/master/deploy/crds/keda.sh_scaledobjects_crd.yaml
kubectl delete -f https://raw.githubusercontent.com/kedacore/keda/master/deploy/crds/keda.sh_scaledjobs_crd.yaml
kubectl delete -f https://raw.githubusercontent.com/kedacore/keda/master/deploy/crds/keda.sh_triggerauthentications_crd.yaml
```

## Expected Behavior

The instructions should be updated for a working solution

## Actual Behavior

The uninstall instructions aren't in working state

## Steps to Reproduce the Problem

  1. Follow uninstall instructions from [deploy](https://keda.sh/docs/2.0/deploy/) page
  2.
  3.

## Specifications

  - **KEDA Version:** v1.5
  - **Platform & Version:** Ubuntu 16.04.7 LTS
  - **Kubernetes Version:** v1.17.9
  - **Scaler(s):** Doesn't matter

**Comment by zroubalik** [comment]
You are using KEDA v 1.5 but following uninstall instruction for version 2.0.

If you check 1.5 documentation, you will see that it is referring to the correct files:
https://keda.sh/docs/1.5/deploy/

**Comment by tecoholic** [comment]
Oh! I am sorry for the noise. That was stupid. :disappointed:

**Comment by zroubalik** [comment]
@tecoholic no worries at all 😃
