### ISSUE TITLE
Problem deploying scaledJob

### ISSUE THREAD

**Issue by karthikeyanVK** [kedacore/keda#1189]
## Expected Behavior
Scaled Job to be deployed.

## Actual Behavior

Getting error `error: unable to recognize "deployjob.yaml": no matches for kind "ScaledJob" in version "keda.sh/v1alpha1"`

## Steps to Reproduce the Problem

  1. Copied the sample into yaml file from https://keda.sh/docs/2.0/concepts/scaling-jobs/#details
  2. Save the file named deploy.yaml
  3. Ran kubectl apply -f  deployjob.yaml
  4. It gave the below error. `error: unable to recognize "deployjob.yaml": no matches for kind "ScaledJob" in version "keda.sh/v1alpha1"`
 5. My AKS works fine for Scaledobject, so keda installation is all fine. When i want to move to ScaledJob for long running execution am getting this error. 

## Specifications

  - **KEDA Version:** *2.0*
  - **Platform & Version:** *AKS*
  - **Kubernetes Version:** *1.17.9*
  - **Scaler(s):** *ScalerJob*

**Comment by zroubalik** [comment]
@karthikeyanVK could you please confirm the KEDA version, in the description you mentioned KEDA 1.0.

But ScaledJob is present only for 2.0.0 (2.0.0-beta) to be specific.

You should chech that ScaledJob CRD is installed in the cluster

`kubectl get crd | grep keda`

**Comment by zroubalik** [comment]
this might be related: https://github.com/kedacore/keda/issues/1193

**Comment by karthikeyanVK** [comment]
This one worked. I uninstalled and reinstalled the Beta version of KEDA using the below command. 

`kubectl apply -f https://github.com/kedacore/keda/releases/download/v2.0.0-beta/keda-2.0.0-beta.yaml`

**Comment by BlaneG** [comment]
I was receiving a similar error when trying to deploy to kubernetes with `func kubernetes deploy`

```
Error running kubectl apply  -f -.
.....
error: resource mapping not found for name: "<XXXX>" namespace: "" from "STDIN": no matches for kind "ScaledObject" in version "keda.sh/v1alpha1"
ensure CRDs are installed first
```

I reinstalled the most recent version of keda from yaml described here: https://keda.sh/docs/2.7/deploy/#yaml
