### ISSUE TITLE
KafkaScaler - Use Configmap for setting topics / bootstrapServers / consumerGroup

### ISSUE THREAD

**Issue by QuintinBecker** [kedacore/keda#1190]
We are using configmaps to configure the deployments for our Keda-Scaled service and would like to use same Configmap for the ScaledObject as well. 

### Use-Case

By using configmaps to configure ScaledObject and Deployment at the same time, chenges only need to be done in configmaps.
As we use different brnaches for DEV/PROD we currently need to adopt the ScaledObject for each branch.

### Specification

Currently only string-type is supported:
topic: 'literal_topicname'

Add ConfigMap reference:
```
topic:
 valueFrom:
  configMapKeyRef:
   name: topics-cfg
   key: topicname
...
```
or like in RedisScaler
```
topicFromEnv: topicname-env-var-in-deployment
bootstrapServersEnv: bootstrapServers-env-var-in-deployment
consumerGroupFromEnv: consumerGroup-env-var-in-deployment
```

Wer are running on OKD 4.5 and user KEDA 2.0

**Comment by QuintinBecker** [comment]
@grassiale 
Do you think such a feature can be added to the ScaledObject definition ? 
This would be a real benefit for everyone using seperate GIT branches for DEV/QUAL/PROD and would make updates/changes so much easier.

**Comment by medkbadri** [comment]
@QuintinBecker  are the changes impacted?
when I use bootstrapServersFromEnv parameter, I'm getting this error:
ERROR   controller      Reconciler error        {"reconcilerGroup": "keda.sh", "reconcilerKind": "ScaledObject", "controller": "scaledobject", "name": "kafka-scaledobject", "namespace": "default", "error": "error getting scaler for trigger #0: error parsing kafka metadata: no bootstrapServers given"}

**Comment by jlewi** [comment]
I tried it using the latest Keda and it seems to be working. 

One issue I ran into is that my deployment had multiple containers and it looks like it was checking the first container from the environment variable.

**Comment by lallinger-arbeit** [comment]
as #1329 is merged this could be closed @QuintinBecker could you close the issue?

**Comment by whyevenquestion1t** [comment]
@QuintinBecker were you able to resolve the issue? Having the functionality to fetch env variables from the configmap would be very useful
