### ISSUE TITLE
watch all sub folders in azure blob storage scaler?

### ISSUE THREAD

**Issue by nithinkd-geon** [kedacore/keda#1210]
is it possible to watch all subfolders in azure blob storage scaler
like can i provide blobPrefix as "RawData/Processing/{containername}" where {containername} is dynamic and need to listen files in and scale accrodingly

**Comment by tomkerkhove** [comment]
Adding @jeffhollan @ahmelsayed @anirudhgarg

**Comment by tomkerkhove** [comment]
Duplicate of #1789
