### ISSUE TITLE
Error while using keda 2.0.0-rc Azure servicebus scaler on AKS

### ISSUE THREAD

**Issue by prashantmait** [kedacore/keda#1226]
While using the helm install for the 2.0-rc on AKS getting this warning 

```
 helm : manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
 At line:1 char:1
 + helm install keda kedacore/keda --version 2.0.0-rc --namespace keda
 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     + CategoryInfo          : NotSpecified: (manifest_sorter...: "crd-install":String) [], RemoteException
     + FullyQualifiedErrorId : NativeCommandError
  
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"

```

Thereafter creating a Servicebus topic based scaler is not getting created properly , it remains in Ready=False state
Doesnt create any corresponding HPA either, so no scaling on events on the service bus topic either.

Tried this on newly created cluster on Azure, based on kubernetes version 1.18.8 and 1.17.9 both

Result of running "kubectl describe scaledobjects -n asis"
![image](https://user-images.githubusercontent.com/55595256/95202733-5770d780-07ff-11eb-9541-eab00e6dc41d.png)

**Comment by zroubalik** [comment]
@tbickford @tomkerkhove any idea what could be wrong with helm in this case?

**Comment by tomkerkhove** [comment]
Can you share the following please :
- Your raw ScaledObject YAML
- Logs from the KEDA operator

@zroubalik This is still the same issue. I would just remove support for Helm 2 since it's dead end and we can't manage to work around it so I would rather focus on some other features over fixing this one.

**Comment by zroubalik** [comment]
@tomkerkhove I don't have a problem with dropping Helm 2 support. It's up to you guys @tomkerkhove @tbickford
