### ISSUE TITLE
Cloudwatch scaler - Support cloudwatch metrics with multiple dimensions

### ISSUE THREAD

**Issue by jmhoeft** [kedacore/keda#1230]
Support cloudwatch metrics with multiple dimensions

### Use-Case

Right now the cloudwatch scaler only lets you specify a single dimension name and value.  This means you can't scale on any metrics with multiple dimensions.  

### Specification

It would be great to be able to specify a list of dimensions in the ScaleTrigger:

```triggers:
- type: aws-cloudwatch
  metadata:
    # Required: namespace
    namespace: MyCustomNamespace
    # Required: At least one dimension name
    dimensions:
    - Name: QueueName
      Value: keda
    - Name: env
      Value: dev
    metricName: AGE
    targetMetricValue: "2"
    minMetricValue: "0"
    ...

**Comment by jmhoeft** [comment]
The cloudwatch GetMetricData call definitely supports multiple dimensions on the metric, the limiting factor here is the ScaleTriggers Metadata being `map[string]string`. I already did some work to prove this out but wanted to hear if you folks had any thoughts on how to implement this.

**Comment by JonasMatos0** [comment]
Got confirmation that this is a good feature to be implemented. 
https://github.com/kedacore/keda/discussions/1321


I'm taking a look on the needed changes. If you want to collaborate yourself, please let me know what you have so far, @jmhoeft  .

**Comment by jmhoeft** [comment]
Hey! Somehow just saw this.  Let me remember what I was doing and get it pushed soon. Basically, what I was unsure about was that [this call](https://github.com/kedacore/keda/blob/main/pkg/scalers/aws_cloudwatch_scaler.go#L251) works just fine with multiple dimensions, but I wasn't sure the best way to get the inputs. It will probably require changes to CRDs.

**Comment by JonasMatos0** [comment]
@jmhoeft solution merged on
https://github.com/kedacore/keda/pull/1517
https://github.com/kedacore/keda-docs/pull/352
