### ISSUE TITLE
Add Argo Rollouts e2e test

### ISSUE THREAD

**Issue by zroubalik** [kedacore/keda#1234]
KEDA v2 can scale CustomResource, we should add scenario to cover [Argo Rollouts](https://github.com/argoproj/argo-rollouts).

We can reuse existing Scalers e2e tests, just add the target deployment as a Argo Rollout

E2E test: https://github.com/kedacore/keda/tree/v2/tests

**Comment by anggao** [comment]
@zroubalik I can do this, if no one take it :)

**Comment by zroubalik** [comment]
@anggao great, go ahead!
