### ISSUE TITLE
InfluxDB metrics Scaler

### ISSUE THREAD

**Issue by gordonbondon** [kedacore/keda#1239]
Provide a scaler based on a query to InfluxDB (similar to Prometheus or CloudWatch)

  - **Scaler Source:** [InfluxDB](https://github.com/influxdata/influxdb) is a popular timeseries DB. 
  - **How do you want to scale:** Scale on target value from [Flux](https://docs.influxdata.com/influxdb/v2.0/query-data/get-started/) query. Similar to zalando metrics adapter [here](https://github.com/zalando-incubator/kube-metrics-adapter#example-external-metric-1)
  - **Authentication:** InfluxDB client require address and token for authentication ([ref](https://pkg.go.dev/github.com/influxdata/influxdb-client-go/v2#NewClient))

Would you consider a PR which will add this or it's better suited as external scaler?

**Comment by zroubalik** [comment]
@gordonbondon PR would be great!

**Comment by yquansah** [comment]
@gordonbondon Hello, are you taking a crack at adding this scaler? I was also thinking about submitting a PR.

**Comment by gordonbondon** [comment]
@yquansah I've been working on it, but it's a bit far from being ready right now

**Comment by gordonbondon** [comment]
I believe this is now released in https://github.com/kedacore/keda/releases/tag/v2.1.0

**Comment by JasonRD** [comment]
is it supported influxdb 1.x?
