### ISSUE TITLE
Switch default namespace from `keda` to `keda-system`

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda#1240]
I'm seeing more and more project using `{project}-system` as a naming convention for the Kubernetes namespace.

What are your thoughts on following that? It feels more explicit in what the goal is with `keda-system` rather than `keda` but it might just be me.

**Comment by zroubalik** [comment]
I personally don't see a push to change this, but leave it up to others.

(my 2 cents: I don't see a particular benefit from this change and it could potentially break existing installations, if user does update)

**Comment by tomkerkhove** [comment]
Yeah, fair point! Closing.
