### ISSUE TITLE
Keda keeps managing deleted ScaledJobs

### ISSUE THREAD

**Issue by OrenLederman** [kedacore/keda#1247]
The Keda operator logs still show that it's querying the queues after the ScaledJob is deleted. I believe it also tries to instantiate Jobs (and fails) if there are work items in the queue. I used it with a GCP PubSub scaler

Workaround - restart the operator

## Expected Behavior
Keda should identify deleted ScaledJobs and stop querying their queue

## Actual Behavior
Keda keeps querying delete jobs' queues.

## Steps to Reproduce the Problem
  1. Create a ScaledJob (with a GCP PubSub trigger)
  2. Verify that Keda identified the job and it querying the eueue
  3. Delete ScaledJob
  4. Check the Keda operator log

## Specifications
  - **KEDA Version: 2.0.0-RC
  - **Platform & Version: Ubuntu 18 and GCP's Container Optimized OS
  - **Kubernetes Version: v1.16.13-gke.401
  - **Scaler(s): gcp-pubsub

**Comment by zroubalik** [comment]
@TsuyoshiUshio PTAL

**Comment by Lefthander** [comment]
Just want to confirm the similar bug under AWS EKS platform:

KEDA Version: 2.0.0-RC
EKS Version: 1.17-eks.3
AMI release version: AMI 1.17.11-20201007
AMI type: AL2_x86_64
Scaler:  aws-sqs

**Comment by TsuyoshiUshio** [comment]
Thank you guys. 
It seems an issue of the ScaledJob finalizer. I'll try to repro it. 
I'm pretty busy for a couple of days, however, after that, I'll do it.

**Comment by zroubalik** [comment]
@TsuyoshiUshio I can take a look on this one.

**Comment by zroubalik** [comment]
@OrenLederman good catch, thanks for the reporting!

**Comment by OrenLederman** [comment]
Happy to help. Thank you for working on this tool - it's just what I need for my long-running jobs.
