### ISSUE TITLE
IBM MQ Scaler 

### ISSUE THREAD

**Issue by jessm12** [kedacore/keda#1253]
Hi team KEDA! We have been working on an IBM MQ Scaler that we would like to contribute. We have had a chat with @zroubalik and we are ready to open Pull Requests for the scaler code, docs and sample to be linked that we have put together that we would love feedback on 🙂 We plan to attend Thursday's community meeting. You can take a look at our code at: 

- https://github.com/ibm-messaging/mq-keda/tree/IBM-MQ-Scaler-v2
- https://github.com/ibm-messaging/mq-keda-docs/blob/ibm-docs/content/docs/2.0/scalers/ibm-mq.md
- https://github.com/ibm-messaging/mq-dev-patterns/tree/master/Go-K8s

Scaler details:
- **Scaler Source:** A scaler to support the scaling of applications consuming IBM MQ Queue messages.
- **How do you want to scale:** Scale on the depth of an IBM MQ Queue.
- **Authentication:** Requirement to authenticate with the IBM MQ Admin endpoint.

**Comment by zroubalik** [comment]
Great job!
