### ISSUE TITLE
TLS client is build with InsecureSkipVerify

### ISSUE THREAD

**Issue by aman-bansal** [kedacore/keda#1263]
`InsecureSkipVerify` while defined TLS client is not recommended in production systems. This is susceptible to man in the middle attack. Only for internal testing, this should be enabled.

## Expected Behavior
One of the hidden features of TLS is hostname verification. While defining client, `ServerName` verification is needed to detect if there is any routing via man in the middle attack. For this to work, the client should know which server he is expecting the results. It works automatically if the hostname is matched to the server name provided in the certificate. Otherwise, we need to specify it separately.

## Actual Behavior
InsecureSkipVerify is being used and thus hostname verification is skipped.

## Specifications
Present in all versions

## Solution / Suggestion
I believe for every scaler using TLS server name should be added as an additional trigger parameter. If not provided, we will use InsecureSkipVerify.

Let's discuss how best we can achieve this. And I would love to pick this up too.
cc. @ahmelsayed @zroubalik @tomkerkhove @turbaszek

**Comment by arschles** [comment]
https://github.com/kedacore/keda/pull/1251/files makes some progress towards this. creation of HTTP requests is limited to 1-2 points in the code

**Comment by tomkerkhove** [comment]
Is this just for RabbitMQ @aman-bansal?

**Comment by aman-bansal** [comment]
No it's something that has been present at every place where we work with TLS. RabbitMQ, Kafka, Metric api everywhere.

**Comment by marchmallow** [comment]
We could help support it for Redis TLS too

**Comment by arschles** [comment]
https://github.com/kedacore/keda/pull/1251#issuecomment-719905088 for related discussion on this
