### ISSUE TITLE
Provide trigger authentication support for GCP scalers

### ISSUE THREAD

**Issue by harshthakur9030** [kedacore/keda#1273]
GCP should support TriggerAuthentication like other scalers

### Use-Case
This is more secure

Would be happy to take this issue up with little guidance. 
I see that gcp scaler is reading auth creds from config.TriggerMetadata . So if I change it to read from config.Auth , will it just work or are there any other changes that I would need to do?

**Comment by tomkerkhove** [comment]
We are certainly open for contributions @harshthakur9030, thanks for the suggestion!

Adding @zroubalik for guidance

**Comment by zroubalik** [comment]
> I see that gcp scaler is reading auth creds from config.TriggerMetadata . So if I change it to read from config.Auth , will it just work or are there any other changes that I would need to do?

I think this should do the job :)
