### ISSUE TITLE
mysql-scaledobject no error no pod scale

### ISSUE THREAD

**Issue by kenotsolutions** [kedacore/keda#1277]
## Expected Behavior
check MySQL query and scale pointed deployment

## Actual Behavior

I see the scaledobject is ready and there is no error on the kade-operator pod's log 

## Steps to Reproduce the Problem

  1.  MySQL created and prepared for the query
  2.  php-apache deployment created 
  3. scale object created 

## Specifications

  - **KEDA Version:** *2.0.0.c
  - **Platform & Version:** *bare metal*
  - **Kubernetes Version:** *v1.18.2*
  - **Scaler(s):** *mysql

[php-apace-deployment.yaml.gz](https://github.com/kedacore/keda/files/5411993/php-apace-deployment.yaml.gz)
[mysql.yml.gz](https://github.com/kedacore/keda/files/5411994/mysql.yml.gz)
[mysql-pvc.yml.gz](https://github.com/kedacore/keda/files/5411995/mysql-pvc.yml.gz)
[keda-hpa-mysql.yml.gz](https://github.com/kedacore/keda/files/5411996/keda-hpa-mysql.yml.gz)

```
2020-10-20T22:11:08.200Z	INFO	controllers.ScaledObject	Updated HPA according to ScaledObject	{"ScaledObject.Namespace": "keda-hpa-test", "ScaledObject.Name": "mysql-scaledobject", "HPA.Namespace": "keda-hpa-test", "HPA.Name": "keda-hpa-mysql-scaledobject"}
2020-10-20T22:11:08.200Z	INFO	controllers.ScaledObject	Initializing Scaling logic according to ScaledObject Specification	{"ScaledObject.Namespace": "keda-hpa-test", "ScaledObject.Name": "mysql-scaledobject"}
2020-10-20T22:11:08.208Z	INFO	controllers.ScaledObject	Reconciling ScaledObject	{"ScaledObject.Namespace": "keda-hpa-test", "ScaledObject.Name": "mysql-scaledobject"}

```

```
 kubectl get scaledobjects.keda.sh
NAME                 SCALETARGETKIND      SCALETARGETNAME   TRIGGERS   AUTHENTICATION                   READY   ACTIVE   AGE
mysql-scaledobject   apps/v1.Deployment   php-apache        mysql      keda-trigger-auth-mysql-secret   True    True     6m35s
```

We should see php-apache auto-scale up to  maxReplicaCount =10 pod here 
```
kubectl get pods
NAME                          READY   STATUS    RESTARTS   AGE
mysql-5456cbb767-mn24j        1/1     Running   0          106m
php-apache-5c4f475bf5-qzkmx   1/1     Running   0          40m
```

MYSQL
```
create database scale;
use scale;
create table queue (name varchar(10),number int);
insert into queue (name,number) values ('test',16);

use mysql
GRANT ALL PRIVILEGES ON *.* TO 'user'@'%'
````

I could not find how to set MySQL user and password into connectionString. I think you should put better example while the old example could not use it. for example https://github.com/turbaszek/keda-example/blob/master/keda/mysql-hpa.yaml this example no longer supported

**Comment by kenotsolutions** [comment]
with the new relase (rc-2) the problem fixed

**Comment by prathap-pft** [comment]
@kenotsolutions.
Can you please provide an example on how to configure username,password and host with the below connection string from your documentation.

mysql_conn_str: user@tcp(mysql:3306)/stats_db

**Comment by prathap-pft** [comment]
> @kenotsolutions.
> Can you please provide an example on how to configure username,password and host with the below connection string from your documentation.
> 
> mysql_conn_str: user@tcp(mysql:3306)/stats_db

OK, I figured out how to configure it finally.
Since the scaler is written in go, you will have to configure as below. 
username:password@tcp(hostName:3306)/databasename.
Request you guys to update the document also.
