### ISSUE TITLE
Support "Value" metric type for RabbitMQ scaler

### ISSUE THREAD

**Issue by knepe** [kedacore/keda#1314]
Would like to be able to use "Value" metric type for the RabbitMQ scaler, instead of "AverageValue" as it is now.

### Use-Case

Want to have min replicas set to 0, so it will have 0 replicas when queue is empty, but as soon as the queue for ex contains 1 to 300 messages it should scale to 1 replica, and between 300-600 it should scale to 2 replicas and so on. There is another issue requesting this feature here: https://github.com/kedacore/keda/issues/692

I built a local image to test it out and it works as expected if we use `v2beta2.ValueMetricType` instead of `AverageValueMetricType`, but it should be configurable and default to `AverageValueMetricType` I guess.

### Specification

- [ ] Make MetricTarget Type configurable

**Comment by knepe** [comment]
Please discuss this if/how you want to solve this in a more generic way :) 
I have a working image I'm using in my cluster here: https://github.com/kedacore/keda/compare/main...knepe:main

**Comment by knepe** [comment]
Hey guys, have you had time to discuss this? @zroubalik

**Comment by jeffhollan** [comment]
Discussed in our standup today - this seems like a good feature worth looking into. Adding to roadmap

**Comment by zroubalik** [comment]
My only small remark is, how do we handle multiple scalers per ScaledObject? Do we want to allow mixed scenario, I am curious what is the behavior then, whether it won't be confusing for users.

Maybe not 🐱

**Comment by msf** [comment]
I have a similar need. Immediate scale from zero if any message is present in the queue, and then some HPA behaviour based on the queue length size.

**Comment by knepe** [comment]
Hey, any updates on this? :)

**Comment by avivgold098** [comment]
Hey, this very useful also for the `Prometheus` Scaler as well

**Comment by tomkerkhove** [comment]
Can you create a dedicated issue for Promehtues please?

**Comment by zroubalik** [comment]
I'd prefer some umbrella issue where we can track this effort, because imho it should be done for all scalers.
