### ISSUE TITLE
New OpenStack Swift scaler

### ISSUE THREAD

**Issue by domminiks** [kedacore/keda#1342]
My team ([@sidilabs](https://github.com/sidilabs)) and I want to contribute to KEDA by proposing and also implementing a RedHat/[OpenStack Swift](https://docs.openstack.org/swift/latest/) scaler.

More info about our proposal:

  - **Scaler Source:** Swift is the default object-store for OpenStack. It works much like AWS S3 or Azure Blob Storage. 
	  > The OpenStack Object Store project, known as Swift, offers cloud storage software so that you can store and retrieve lots of data with a simple API. It's built for scale and optimized for durability, availability, and concurrency across the entire data set.
	  
  - **How do you want to scale:** The idea is to scale based on the object count in a certain container. As the object count (number of files, folders, ...) changes, KEDA scales up or down accordingly.

  - **Authentication:** for authentication we must use Keystone (another OpenStack project). With Keystone, one can get an access token to be used for authentication/authorization. We've investigated two auth methods for getting a token and then querying the Swift API:
	-  Simple username/password
	-  Using [Application Credentials](https://docs.openstack.org/api-ref/identity/v3/index.html?expanded=#application-credentials)

We understand that both auth methods should be implemented by the scaler.

**Comment by zroubalik** [comment]
Looking good! That would be a great contribution.

Just a minor nit, implementing e2e tests with the scaler would be really great: https://github.com/kedacore/keda/tree/main/tests

**Comment by domminiks** [comment]
Ok, I took a note about it, thanks! 

Letting the community know about our progress soon :smile:

**Comment by tomkerkhove** [comment]
This was implemented, closing
