### ISSUE TITLE
[Scaler] AWS SQS

### ISSUE THREAD

**Issue by jeffhollan** [kedacore/keda#138]
A scaler that could activate / deactivate and provide metrics for SQS

**Comment by jeffhollan** [comment]
Sounds like @zach-dunton-sf is working on this.  If so happy to assign.  Thanks @zach-dunton-sf!

**Comment by zach-dunton-sf** [comment]
In progress PR is here https://github.com/kedacore/keda/pull/191

**Comment by jeffhollan** [comment]
Merged in and fixed up.
