### ISSUE TITLE
New Openstack Metric scaler (Old AODH)

### ISSUE THREAD

**Issue by Rodolfodc** [kedacore/keda#1382]
Me and my team ([@sidilabs](https://github.com/sidilabs)) are aiming to contribute with Keda by building a new Keda scaler for [Openstack](https://docs.openstack.org/) project, based on [AODH](https://docs.openstack.org/aodh/latest/) service.

  - **Scaler Source:** AODH is the Openstack alarming system, similar to AWS CloudWatch.
> The Alarming service (aodh) project provides a service that enables the ability to trigger actions based on defined rules against metric or event data collecteted
  - **How do you want to scale:** The scaling will be based on how many alarms are activated, the user will be able to allow filtering alarms by name, severity or just let Keda consider all activated alarms
  - **Authentication:** for authentication we must use Keystone (another OpenStack project). With Keystone, one can get an access token to be used for authentication/authorization. We've investigated two auth methods for getting a token and then querying the Swift API:
    - Simple username/password
    - Using Application Credentials

We understand that both auth methods should be implemented by the scaler.

**Comment by tomkerkhove** [comment]
Sounds great! Happy to have you contribute this!

**Comment by Rodolfodc** [comment]
Hi, I recently finished this scaler, but I found out that this scaler makes more sense as being an Openstack metrics scaler instead of being only Openstack AODH Scaler, cause Openstack alarm API (AODH) doens't provide metrics, as it is in AWS CloudWhatch API. 
Here it is: https://github.com/kedacore/keda/pull/1689

**Comment by Rodolfodc** [comment]
Here is the PR for this new scaler: https://github.com/kedacore/keda/pull/1692

**Comment by zroubalik** [comment]
Done in #1692
