### ISSUE TITLE
Add ability to disable scaling without removing object.

### ISSUE THREAD

**Issue by bkruger99** [kedacore/keda#1392]
Discussion: https://github.com/kedacore/keda/discussions/1331

With HPA, you can set your deployment (for example) to zero and the HPA won't spin up new pods - disabling the HPA in the process.

What I do like with Keda that I don't want to see go that HPA doesn't allow is exactly the scale to 0 ability for a deployment for example.  

### Use-Case

We have cases where I work where we backfill some historical data.  Currently with regular hpa's, we can leave backfill deployments hanging around and scaled to zero when not in use.   When we need to backfill, we can simply scale down our regular workers to zero and scale up our backfill workers.  When we're done, we scale backfill back down to zero and then scale up to at least one worker and let hpa handle the rest.

### Specification
I really don't have anything to offer here other than this would be something that can be done via least privilege.  Add/remove an annotation to scaled object and the metrics server just always returns zero?   The hpa object just disappears temporarily?  I would like to have an easy toggle for it though.   Can an enable/disable value be passed in to the scaled object it itself kinda like replicas?   I will defer to expertise in here and I'm curious on the best method for my own future learning.

**Comment by tomkerkhove** [comment]
Feels like there is a lot of overlap with https://github.com/kedacore/keda/issues/944 or do you have different needs?

**Comment by bkruger99** [comment]
So long as I can disable keda and make changes w/o having to mess with manifest, then yeah, that works.   I'll close this one as #944 seems to be the same.

**Comment by dmeytin** [comment]
+1
We need this feature to support automated DR

**Comment by harzallah** [comment]
+1 also for automating DR

**Comment by tomkerkhove** [comment]
This is available today in KEDA v2.7: https://keda.sh/docs/2.7/concepts/scaling-deployments/#pause-autoscaling

See https://github.com/kedacore/keda/issues/944
