### ISSUE TITLE
[Scaler] Azure Event Hubs

### ISSUE THREAD

**Issue by jeffhollan** [kedacore/keda#14]

**Comment by jeffhollan** [comment]
For the `type` would be good to have both `azure-eventhub` or `azure-iothub` as alias as people may be approaching this from either #214

**Comment by tomkerkhove** [comment]
That means that we should also have an alias for `metadata.eventHubName` to avoid confusion.

Happy to review configurations in case there is a need.

**Comment by jeffhollan** [comment]
Starting work on Monday, doing some validation around the capabilies of the Azure Go SDK

**Comment by asavaritayal** [comment]
Working on validation/bug fixes.

**Comment by Aarthisk** [comment]
Closed via PR: https://github.com/kedacore/keda/pull/276
