### ISSUE TITLE
[Scaler] Google Pub/Sub

### ISSUE THREAD

**Issue by jeffhollan** [kedacore/keda#141]

**Comment by patnaikshekhar** [comment]
@jeffhollan it looks like the length of a topic / subscription is not available through an API yet. The only way to get the number of messages in a subscription is to call the stackdriver API and fetch the external metric pubsub.googleapis.com/subscription/num_undelivered_messages.

**Comment by tomkerkhove** [comment]
Maybe that's a good workaround until they support it in the Google Pub/Sub API?

**Comment by patnaikshekhar** [comment]
@jeffhollan I'm happy to pick this one up next

**Comment by patnaikshekhar** [comment]
@jeffhollan @tomkerkhove @yaron2 I've submitted a pull request for this now

**Comment by ahmelsayed** [comment]
Merged
