### ISSUE TITLE
Show min/max replica count when using kubectl get scaledobject

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda#1410]
Show minimum replica count when using kubectl get scaledobject.

### Use-Case

This allows operators to easily learn what the replica counts are for scaled objects.

**Comment by Ritikaa96** [comment]
Hi @tomkerkhove are we adding the min/max? is this going forward?

**Comment by Ritikaa96** [comment]
I had tweaked with the code to get these before so if it is going forward I can raise the pr. Also as they are fixed can we do something like 
`kubectl get so`

`NAME       ......          **REPLICACOUNTRANGE**       READY      ACTIVE       AGE`
`scaledObjectName     .......   **1-30**                              TRUE          TRUE            ..... `

If this is what I think it is.

**Comment by tomkerkhove** [comment]
We are certainly open for a PR if you want to contribute this @Ritikaa96 - Thanks!

**Comment by Ritikaa96** [comment]
Sure, thanks @tomkerkhove ! so to be certain we have to add minReplicaCount and maxReplicaCount both right? Like:

`kubectl get so`

`NAME       ......                      **MINREPLICACOUNT**      **MAXREPLICACOUNT**           READY      ACTIVE       AGE`
`scaledObjectName     .......             **1**                                        **30**                                    TRUE          TRUE            ..... `

**Comment by tomkerkhove** [comment]
I'd go for `MIN REPLICAS | MAX REPLICAS` - OK for you @zroubalik ?

**Comment by zroubalik** [comment]
> I'd go for `MIN REPLICAS | MAX REPLICAS` - OK for you @zroubalik ?

@tomkerkhove yeah, I like this

**Comment by Ritikaa96** [comment]
@tomkerkhove  @zroubalik Great then, I'll change the column-names to MIN REPLICAS  &  MAX REPLICAS and raise the PR.

**Comment by Ritikaa96** [comment]
@tomkerkhove @zroubalik adding MIN | MAX for both scaledObject and scaledJob cases in [#1534](https://github.com/kedacore/keda/pull/1534) FYI.
