### ISSUE TITLE
Why is there code in here attributed to/copyrighted by the Kubernetes Authors?

### ISSUE THREAD

**Issue by technosophos** [kedacore/keda#143]
https://github.com/kedacore/keda/blob/master/pkg/apis/keda/v1alpha1/zz_generated.deepcopy.go

**Comment by ahmelsayed** [comment]
It's an auto-generated file using kubernetes' [client generator](https://github.com/kubernetes/code-generator). It probably make sense to keep their license notice like with other open source dependencies, but IANAL

**Comment by jchesterpivotal** [comment]
The license header is configurable by design: https://github.com/kubernetes/code-generator/blob/master/hack/boilerplate.go.txt

**Comment by ahmelsayed** [comment]
Thank you @jchesterpivotal  and @technosophos. I didn't know that. I opened a PR with a fix. I just copied our license file there. I hope that's correct...
