### ISSUE TITLE
Provide resource requests/limits for KEDA deployment

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda#1450]
Provide resource requests/limits for KEDA deployment so that we guide our users and not flood a cluster.

**Comment by zroubalik** [comment]
Don't we already have these? https://github.com/kedacore/keda/blob/2a2987ab0f6020cffa9e75e18005469ca3aaf426/config/manager/manager.yaml#L37-L42

**Comment by tomkerkhove** [comment]
Closing as we only need them in Helm then, thanks for pointing out!

Should we document them on https://keda.sh/docs/2.0/operate/ as well?

**Comment by zroubalik** [comment]
> Should we document them on https://keda.sh/docs/2.0/operate/ as well?

Yeah, that make a sense.
