### ISSUE TITLE
Add mongoDB scaler

### ISSUE THREAD

**Issue by NUCsimple** [kedacore/keda#1465]
Provide a scaler based on a query to mongoDB:

  - **Scaler Source:** *Mongo DB is a database with a large number of users.*
  - **How do you want to scale:** *Scale on target value from mongo query. Similar to mysql.*
  - **Authentication:** *MongoDB client require address and password for authentication*

**Comment by tomkerkhove** [comment]
Thanks for the contribution @NUCsimple, we'll review it asap!

**Comment by taxilian** [comment]
very cool -- wish I knew Go well enough to add support for tls connections. It's certainly possible to specify tls in the connection string, but the most secure way to do mongodb uses tls authentication as well, meaning that you need to not only tell it "use TLS", you need to give it a CA certificate and a client key / certificate to use.

Seems like this could be done either by having the key, cert, and ca in the same secret or by allowing you to provide a tls secret as well.

I may have to try to learn enough go to do a PR for this as it would be *really* useful for me

**Comment by zroubalik** [comment]
@taxilian just give it a try, it is not that hard to contribute in Go :) 
You can check other scalers how they handle certs referencing, for example Kafka, Metrics API scaler or other ones.

**Comment by JorTurFer** [comment]
Maybe can this issue be closed?
