### ISSUE TITLE
Unable to remove ScaledObject

### ISSUE THREAD

**Issue by wiseelf** [kedacore/keda#1470]
ScaledObject is not being deleted, namespace stuck in Terminating state.

## Expected Behavior
ScaledObject is deleted and namespace is removed.

## Actual Behavior
ScaledObject is not being deleted, namespace stuck in Terminating state.

## Steps to Reproduce the Problem

  1. Deploy ScaledObject into namespace test
  2. kubectl delete ns test
  3. namespace stuck in termination state.

## Logs from KEDA operator

```
021-01-04T12:10:41.272Z	ERROR	scalehandler	Target resource doesn't exist	{"resource": "apps/v1.Deployment", "name": "test-lead-cli", "error": "deployments.apps \"test-lead-cli\" not found"}
github.com/go-logr/zapr.(*zapLogger).Error
	/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128
github.com/kedacore/keda/pkg/scaling.(*scaleHandler).getPods
	/workspace/pkg/scaling/scale_handler.go:373
github.com/kedacore/keda/pkg/scaling.(*scaleHandler).GetScalers
	/workspace/pkg/scaling/scale_handler.go:63
github.com/kedacore/keda/pkg/scaling.(*scaleHandler).checkScalers
	/workspace/pkg/scaling/scale_handler.go:182
github.com/kedacore/keda/pkg/scaling.(*scaleHandler).startScaleLoop
	/workspace/pkg/scaling/scale_handler.go:135
2021-01-04T12:10:41.272Z	ERROR	scalehandler	Error getting scalers	{"object": {"apiVersion": "keda.sh/v1alpha1", "kind": "ScaledObject", "namespace": "test", "name": "test-lead"}, "error": "deployments.apps \"test-lead-cli\" not found"}
github.com/go-logr/zapr.(*zapLogger).Error
	/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128
github.com/kedacore/keda/pkg/scaling.(*scaleHandler).checkScalers
	/workspace/pkg/scaling/scale_handler.go:184
github.com/kedacore/keda/pkg/scaling.(*scaleHandler).startScaleLoop
	/workspace/pkg/scaling/scale_handler.go:135
```

## Specifications

  - **KEDA Version:** *2.0.0*
  - **Platform & Version:** *EKS 1.17*
  - **Kubernetes Version:** *1.17*
  - **Scaler(s):** *prometheus*

**Comment by zroubalik** [comment]
You should delete the ScaledObject before removing the namespace, there are finalizers waiting to be handled in that namespace. You can refer to this blog about this problem: https://www.openshift.com/blog/the-hidden-dangers-of-terminating-namespaces
(if TLDR jump to the `Removing a Terminating Namespace` section)
