### ISSUE TITLE
Provide scaler for Azure Data Explorer

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda#1488]
A clear and concise description of what scaler you'd like to use and how you'd want to use it:

  - **Scaler Source:** *Azure Data Explorer*
  - **How do you want to scale:** *Scale based on a Kusto query*
  - **Authentication:** TBD
- **SDK**: https://docs.microsoft.com/en-us/azure/data-explorer/kusto/api/golang/kusto-golang-client-library

**Comment by yasiboni-max** [comment]
Hi, would like to take this one :)

**Comment by yasiboni-max** [comment]
It's a really good improvement. I'd like to work on this one.

**Comment by tomkerkhove** [comment]
Awesome, thanks a ton @yasiboni-max!

**Comment by RamCohen** [comment]
Hi. Was there any progress made ?
Would like to take this on.

**Comment by tomkerkhove** [comment]
I haven't heard from @yasiboni-max so if you'd like to work on it - Be my guest!

Ok for you @yasiboni-max ?

**Comment by yasiboni-max** [comment]
I actually finished the implementation, but then I saw that you asked to use the SDK so I started to do so.
Currently I have an [issue](https://github.com/Azure/azure-kusto-go/issues/33#) with passing a predefined query to kusto client.

**Comment by RamCohen** [comment]
Try this:

// GetADXSingleRowFromQuery returns the only row from an ADX query result.
If there are more rows, an error is returned.
func GetADXSingleRowFromQuery(ctx context.Context, query string, client
querier) (*table.Row, error) {
    // Execute the query.
    iter, err := client.Query(ctx, "database", kusto.NewStmt("", kusto.
UnsafeStmt(unsafe.Stmt { true, false})).UnsafeAdd(query))
    if err != nil {
        return nil, fmt.Errorf("failed to execute query %s: %v", query, err)
    }
    defer iter.Stop()

    // Get the first (and only result) that should have only a single
numerical column.
    row, err := iter.Next()

    if err != nil {
        return nil, fmt.Errorf("failed to get query %s result: %v", query,
err)
    }

    _, err = iter.Next()

    if (err != io.EOF) {
        return nil, fmt.Errorf("Query %s result had more than a single
result row", query)
    }

    return row, nil
}

**Comment by yasiboni-max** [comment]
Hi @tomkerkhove,  my e2e test requires some setup:  

- Kusto cluster
- Kusto database
- Assign the necessary role to the AAD app & MSI that being used by pod identity
- Expose few values as environment variables.

Can you please elaborate with the right procedure to do so? I didn't find (or missed) the guidelines in the contribution guide for that.

**Comment by tomkerkhove** [comment]
We don't allow contributors to do this for now but if you can provide some more information then I'm happy to do everything that is required.

**Comment by yasiboni-max** [comment]
Sure, no problem. Few requirements for e2e:
- Provision Data Explorer Cluster.
- Create Database inside that cluster.
- Assign "Database viewer" role to  AAD app & MSI that pod identity use ([link](https://docs.microsoft.com/en-us/cli/azure/kusto/database?view=azure-cli-latest#az-kusto-database-add-principal)).
- Expose database name as env var "TEST_DATA_EXPLORER_DB" in e2e environment.
- Expose cluster endpoint uri as env var "TEST_DATA_EXPLORER_ENDPOINT" in e2e environment.

kedacore pr: https://github.com/kedacore/keda/pull/2627
kedadocs pr: https://github.com/kedacore/keda-docs/pull/658

**Comment by tomkerkhove** [comment]
Thank you for the contribution @yasiboni 🎉
