### ISSUE TITLE
Provide scaler for custom metrics in Azure Monitor

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda#1489]
A clear and concise description of what scaler you'd like to use and how you'd want to use it:

  - **Scaler Source:** *custom metrics in Azure Monitor which include Azure Application Insights metrics*
  - **How do you want to scale:** *Based on the value*
  - **Authentication:** *Managed Identity or service principle* (see [docs](https://docs.microsoft.com/en-us/azure/azure-monitor/platform/metrics-custom-overview#authentication))

**Comment by kibnelbachyr** [comment]
We have the same need here. can you advice please?

**Comment by tomkerkhove** [comment]
There is no scaler for it yet, but you might be able to use our Azure Log Analytics scaler to run a query to fetch them.
