### ISSUE TITLE
Support for Azure function CosmosDBTrigger

### ISSUE THREAD

**Issue by petro2050** [kedacore/keda#1494]
I want to migrate my existing codebase to an AKS cluster, but I've noticed you don't have support for `CosmosDBTrigger` according to https://docs.microsoft.com/en-us/azure/azure-functions/functions-kubernetes-keda. If possible, please add support for this trigger.

### Use-Case

By using a `CosmosDBTrigger`, I can listen to messages in `Change Feed` and create an event-driven architecture that leverages `Cosmos DB`. An ideal implementation would create as many leases as there are active instances running. Leases should be load-balanced as active instance count changes.

**Comment by tomkerkhove** [comment]
Definitely a good use-case, we are already tracking it on https://github.com/kedacore/keda/issues/232.

Thanks for suggesting!
