### ISSUE TITLE
Rate limiting of v1beta1.external.metrics.k8s.io

### ISSUE THREAD

**Issue by bpinske** [kedacore/keda#1503]
I have keda deployed in all of my environments and I notice that I am getting spammed in all of them with rate limiting notices. Including environments which are not actually using Keda at all yet. Is there anything that I should be doing to address this, or is this a known issue of some sort? I don't see any documentation around this situation. I haven't seen any ill effect on keda's performance where I am actually using it.

```
kube-apiserver-ip-10-28-11-137.us-west-1.compute.internal kube-apiserver E0112 17:07:58.690813       1 controller.go:114] loading OpenAPI spec for "v1beta1.external.metrics.k8s.io" failed with: OpenAPI spec does not exist
kube-apiserver-ip-10-28-11-137.us-west-1.compute.internal kube-apiserver I0112 17:07:58.690830       1 controller.go:127] OpenAPI AggregationController: action for item v1beta1.external.metrics.k8s.io: Rate Limited Requeue.
```

Keda version: 2.0.0 
Kubernetes Version: 1.18.6

**Comment by surki** [comment]
Thanks @bpinske . I am seeing those errors as well (in AWS EKS 1.18)

**Comment by surki** [comment]
Looks like we should do something like this?: https://github.com/DirectXMan12/k8s-prometheus-adapter/pull/335

**Comment by zroubalik** [comment]
Yeah, update of the https://github.com/kubernetes-sigs/custom-metrics-apiserver deps and related code should help. Though it may not be that easy step, as there might be dependency conflicts between mainly (k8s) deps used by KEDA and the updated version of custom-metrics-adapter :(

**Comment by surki** [comment]
@zroubalik I will make those changes and send a PR "soon" (have done similar changes for other customer metrics servers, so familiar with the details)

**Comment by zroubalik** [comment]
@surki that's great, thanks for doing that!
