### ISSUE TITLE
Create e2e tests 

### ISSUE THREAD

**Issue by szuecs** [kedacore/keda#151]
A major enhancement of complex tools need e2e tests to make updates of the component, dependencies  and depending workloads not error prone. 
I remember for example we had an issue that a wrong metrics object let controller-manager panic. I would like to see an error before we update for example Kubernetes. :)

**Comment by ahmelsayed** [comment]
Are there any particular testing tools or frameworks used in general for k8s controllers or operators? I have some basic test setup I'm putting together here (https://github.com/kedacore/keda/tree/master/tests) just using shell scripts. But I'm curious if there's a more conventional way for kubernetes projects in general.

**Comment by szuecs** [comment]
@ahmelsayed We have some of our tooling tested in https://github.com/zalando-incubator/kubernetes-on-aws/tree/dev/test/e2e. I think it would be quite nice to have more projects adapt the kubernetes e2e tests, such that users can have test infra that actually tests all the tools they use.

**Comment by ahmelsayed** [comment]
Thanks @szuecs. After looking at few options I decided to go with Typescript for tests and using the node client for kubernetes or shelljs+kubectl. I added a readme here https://github.com/kedacore/keda/tree/master/tests and an E2E test for azure-queues scalers. Will slowly add tests for the rest of the event sources next.
