### ISSUE TITLE
Support Azure k8s Metrics Adapter for integration with HPA

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda#152]
_Disclaimer: I haven't checked the code so this might already be the case_

Why does Keda use MSFTs own metrics adapter instead of adopting the [Azure k8s Metrics Adapter](https://github.com/Azure/azure-k8s-metrics-adapter) to integrate with the HPA?

Is it because it's based on other metrics than Azure Monitor or a different reason?
Based on the docs it's not really clear to me where it's getting the metrics from.

**Comment by yaron2** [comment]
KEDA is a cloud agnostic, vendor neutral project and thus cannot use an Azure only software component.

Even for Azure services, the reliance on Azure Monitor is problematic for a multitude of reasons.

**Comment by tomkerkhove** [comment]
That makes sense, I think my question is more why doesn't Keda integrate with existing metric servers which we can plug in.

For example Ive just opened #156 for Prometheus support, which has a metrics server already, and #155 which improves Monitor support while we could plug in the one mentioned above.

/cc @jeffhollan

**Comment by yaron2** [comment]
Was just talking about Prometheus yesterday :)

Thats indeed a very powerful feature.

**Comment by yaron2** [comment]
Closing this as we have #155 and #156 to track

**Comment by tomkerkhove** [comment]
Fair enough, thanks for following-up!
