### ISSUE TITLE
Changing wiki ScaleObject-spec.md

### ISSUE THREAD

**Issue by pushthat** [kedacore/keda#153]
Thanks for the work ! I tried keda with virtual node on aks and I worked very well ! This impressive event driver tool powered by virtual node scaling capacity open new doors !

I changed some link references as well as anchor to make the wiki more accessible.

I followed this instruction https://gist.github.com/larrybotha/10650410 to fork the wiki, there's also documentation for the merging part.

https://github.com/pushthat/keda/wiki/ScaledObject-spec
Regard,

**Comment by ahmelsayed** [comment]
Thank you very much @pushthat for your contributions. I merged your Wiki changes https://github.com/kedacore/keda/wiki/ScaledObject-spec/_history
