### ISSUE TITLE
Remove MIN field from kubectl get scaledjob.

### ISSUE THREAD

**Issue by Shubham82** [kedacore/keda#1552]
In latest release of KEDA(2.1.0), we added the functionality to show minimum and maximum replicacount for scaledobject and scaledjob when we run `kubectl get scaledobject` and `kubectl get scaledjob` but There is no minRelicaCount kind of thing for scaledjob or not define such thing  when we creating scaledjob object, only maxRelicacount is there for scaledjob, see the scaledjob spec [here](https://keda.sh/docs/2.1/concepts/scaling-jobs/#scaledjob-spec). and scaledjob_types.go code [here](https://github.com/kedacore/keda/blob/main/api/v1alpha1/scaledjob_types.go#L30). so when we run `kubectl get scaledjob ` it would show blank for MIN field

## Expected Behavior
     Should not show MIN field when we  run `kubectl get scaledjob`

## Actual Behavior
     Always show MIN field blank(nothing) when we run `kubectl get scaledjob`

## Specifications
  - **KEDA Version:** *2.1.0*

**Comment by Shubham82** [comment]
Could you let me know if it is ok to remove the MIN field from kubectl get scaledjob. If this is valid i would like to work on this.
Thanks

/assign

**Comment by zroubalik** [comment]
@Shubham82 good catch. Yes, would be great to fix this!

**Comment by Shubham82** [comment]
Sure thanks! @zroubalik  Will soon create a PR for it.

**Comment by Shubham82** [comment]
@zroubalik i have  Created a PR for it in #1553

**Comment by Shubham82** [comment]
Hi @tomkerkhove @zroubalik should we also update our Helm chart?
