### ISSUE TITLE
Add support for authentication (Bearer, Basic Auth and TLS) to the Prometheus scaler

### ISSUE THREAD

**Issue by marpio** [kedacore/keda#1559]
Add support for authentication (Bearer, Basic Auth and TLS) to the Prometheus scaler.
### Use-Case
I would like to use KEDA in a OpenShift 4 cluster and scale workloads using the Prometheus scaler. OpenShift's monitoring stack includes Prometheus which is accessible via Thanos Querier, which in turn has a oauth-proxy in front of it.
This means that the scaler would need to be able to pass OAuth Token in order to execute a query.

Tell us more what you'd like to achieve
Additionally the recent releases of Prometheus support Basic and TLS auth so this would be a nice addition too.
### Specification

- [ ] Support OAuth token based authentication
- [ ] Support Basic Auth
- [ ] Support TLS authentication

**Comment by zroubalik** [comment]
Seems like a valid usecase, are you willing to contribute this?

**Comment by surki** [comment]
This is (auth) something we are looking for us well, came here to create an issue, found this.
We are looking for something simper though, like basic auth. If there is a consensus, I could add that.

**Comment by marpio** [comment]
@zroubalik yes, I can add that. @surki Are planning to add token auth as well or just basic auth?

**Comment by zroubalik** [comment]
@marpio @surki cool, I'll leave it up to you! Thanks!

**Comment by zroubalik** [comment]
Just please try to follow other scalers and how are they dealing with authentication. So we have consistent user experience. Thx!

**Comment by zroubalik** [comment]
@marpio OT, I'd be interested to know more about your usage of KEDA on OpenShift? Could you please contact me on [kubernetes slack](https://kubernetes.slack.com/) or on [email](zroubali@redhat.com)? Thanks!

**Comment by surki** [comment]
@marpio I am looking at just basic auth. If you are planning to add both, I could wait. thanks.

**Comment by marpio** [comment]
@surki yes, I'm planning to do both. I need this feature soon and will start implementing it tomorrow so it shouldn't take long.

**Comment by adrianchifor** [comment]
@zroubalik This was merged/closed almost 2 months ago, are you guys planning on doing a release? Really need this on Openshift to use the Prometheus scaler, would be much appreciated!

**Comment by zroubalik** [comment]
@adrianchifor we are going to do the 2.3 release next week at the latest :) if you have any further questions, feel free to ping me on slack.
