### ISSUE TITLE
Cloud Events/Event Grid Webhooks

### ISSUE THREAD

**Issue by cwoolum** [kedacore/keda#159]
The documentation says that this works with Cloud Events/ Event Grid webhooks. Is there an example of this somewhere?

**Comment by yaron2** [comment]
We dont yet support Event Grid.

Where in Keda docs have you seen this?

**Comment by cwoolum** [comment]
Aaah, I guess it was only on the Azure functions blog. It says that it's supported now.

"Today KEDA and supporting tooling works with Kafka, Azure Queues, Azure Service Bus, RabbitMQ, HTTP, and Azure Event Grid / Cloud Events"

https://cloudblogs.microsoft.com/opensource/2019/05/06/announcing-keda-kubernetes-event-driven-autoscaling-containers/

**Comment by yaron2** [comment]
Yeah that shouldnt have been mentioned in the blog post..

**Comment by anirudhgarg** [comment]
Event Grid just needs a Http Webhook to be registered for the Consumer. So since we support Http through Osiris - theoretically it can work as a Consumer of Event Grid events

**Comment by yaron2** [comment]
True, but that'd only take you from/to zero without 1:n.

**Comment by jeffhollan** [comment]
It works (1:n with traditional autoscaling rules) - but I should document (e.g. I tested this with osiris and the Azure Functions tooling).  That's why I was conscious in wording "and supporting tooling."

@cwoolum were you looking to use the Azure Functions HTTP / Event Grid trigger or just a generic trigger? For generic I'd recommend Osiris.  For Azure Functions tooling I can send you my sample in the meantime.

**Comment by yaron2** [comment]
To get "full" EventGrid support, the users needs to use Osiris for to/from zero and then manually enable an HPA for cpu/memory 1:N.

Since KEDA is not in play for this scenario and does not support EventGrid, I suggest we close this issue.

We could open another issue to track whether or not there are metrics available for pending events in an EventGrid subscription topic. If so, we could easily create a KEDA scaler for that.

**Comment by yaron2** [comment]
Relating to #155 , there [seem to be metrics](https://docs.microsoft.com/en-us/azure/azure-monitor/platform/metrics-supported#microsofteventgridtopics) we could work with for an Event Grid KEDA scaler.

**Comment by jeffhollan** [comment]
> To get "full" EventGrid support, the users needs to use Osiris for to/from zero and then manually enable an HPA for cpu/memory 1:N.
> 
> Since KEDA is not in play for this scenario and does not support EventGrid, I suggest we close this issue.
> 
> We could open another issue to track whether or not there are metrics available for pending events in an EventGrid subscription / topic. If so, we could easily create a KEDA scaler for that.

Agree. @cwoolum still happy to chat though on this item specifically and help out even though the work to improve the scenario may land on the core tools or Osiris repos. Let me know what you were hoping to achieve and I can help route and assist.

**Comment by cwoolum** [comment]
@jeffhollan , I was specifically looking to us this with EventGrid and the CloudEvents schema. We currently have a pod deployed as a AspNet Core web service but I really would like the scale to 0 functionality that Keda provides.

**Comment by steeling** [comment]
Any update on this? OSIRIS hasn’t had a commit in quite a while, and the readme has a warning on its stability.

**Comment by steeling** [comment]
@yaron2 is this issue worth reopening? Looks like Osiris is unstable.. "Osiris, as a concept, is highly experimental and currently remains under heavy development.", although "heavy development" seems outdated, with the last commit to master that touched actual code (not just documentation or install scripts), being in Nov 2019.

EventGrid would be really nice to have since it provides a single api for many different event sources

**Comment by cwoolum** [comment]
I got this working fine with just Osiris. Based on the docs, it seems unstable but I didn't run into any issues.

It wouldn't really make sense to use Keda for this because EventGrid is not true Pub/Sub when using webhooks. When EventGrid receives messages and has a webhook subscriber, it's just begin sending messages to the endpoint without confirmation of actually having anyone listening. This is different from all of the other scaler types where the subscriber only connects when it is ready to receive messages. Because of this, it makes more sense use Osiris in combination with a regular HPA to scale your subscribers accordingly.

**Comment by steeling** [comment]
Can you expand on that? Looks like it does have built-in retry/dead lettering and waits for a 200 response from the eventhandler

https://docs.microsoft.com/en-us/azure/event-grid/delivery-and-retry#retry-schedule-and-duration

**Comment by cwoolum** [comment]
EventGrid waits for a 200 to determine if the message was received successfully, but it doesn't wait to send the messages like something like RabbitMQ, Azure Service Bus, or EventHub would do. As soon as the messages are received, EventGrid will attempt to send them to a webhook subscriber. 

The reason Osiris works well with this is that it will hold the request open until a pod spins up and is able to process the message.  With Keda, even if you could build a scaler to work with EventGrid, all of the messages sent by EventGrid until the pod spun up would fail and exponential retry would begin to occur. This could lead to a delayed processing of your messages depending on how many times the messages fail before the pod comes up.

**Comment by steeling** [comment]
Gotcha that makes sense, thanks for clarifying that!

One last question: with what looks like osiris falling out of maintenance, and with this feature seeming to be highly desirable does it make sense to pull in this functionality into Keda itself? That would open up leveraging CloudEvents, Azure EventGrid, and many other push-based event queues. Just a thought, thanks again for all your help!

**Comment by cwoolum** [comment]
You are welcome! @zroubalik and @yaron2 might be able to give feedback on bringing Osiris into Keda.

**Comment by yaron2** [comment]
> You are welcome! @zroubalik and @yaron2 might be able to give feedback on bringing Osiris into Keda.

Personally, I'd like to see Osiris functionality being pulled into KEDA. As a de-facto autoscaler for Kubernetes, KEDA needs to support both models of communications, being event driven (asynchronous) and request/response (synchronous) based.

**Comment by zroubalik** [comment]
I don't think we are going to add Osiris or it's subcomponents directly in the KEDA. But External push scaler could be a way how to plug things together. https://keda.sh/docs/2.0/scalers/external-push/
