### ISSUE TITLE
Azure Functions Socket Error

### ISSUE THREAD

**Issue by Fillo22** [kedacore/keda#1590]
Hi everyone, 
I'm trying to deploy an Azure Function (Event Hub Triggered), but after starting the pod crashes with the following error:
`
System.Net.Sockets.SocketException (13): Permission denied
`

Event Hub is connected via Private Endpoint and all ports are open.
Keda operator is the latest.
Has anyone ever had the same problem?

_Originally posted by @Fillo22 in https://github.com/kedacore/keda/discussions/1589_

**Comment by tomkerkhove** [comment]
This looks more like an issue for Azure Functions team than for KEDA since we just spin up the instances, but don't handle what's inside of it. Makes sense?

**Comment by Fillo22** [comment]
It seems to be related with container's permissions. I'm investigating on the cause.

**Comment by Fillo22** [comment]
Even if an http trigger is not used, the dotnet core runtime tries to expose a reserved port (1 - 1024), however it does not have the permissions to do this, so it fails. To work around the problem I added an environment variable 
`
ENV ASPNETCORE_URLS=http://*:8080
`

and exposed a non-root port.
