### ISSUE TITLE
Release ARM container image to support Edge deployments

### ISSUE THREAD

**Issue by yaron2** [kedacore/keda#160]
KEDA can run on edge ARM devices.
All we need to do is publish an armv7 container image.

The image can then be set via Helm.

**Comment by jeffhollan** [comment]
Do you plan to tackle this in the next week or too or should we punt to the "Triaged" milestone as a P1/P2?

**Comment by yaron2** [comment]
In the next week.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by jeffhollan** [comment]
Yaron planning to release by end of week

**Comment by asavaritayal** [comment]
Looking at mid-next week for next update.

**Comment by asavaritayal** [comment]
Will need experience in the func Core Tools to specify which image.
