### ISSUE TITLE
Please add Expression field to AWS CloudWatch scaler

### ISSUE THREAD

**Issue by jeffjen** [kedacore/keda#1619]
**Proposal**

We'd like to add simple math aggregation to our metric data.

As it stands, we need to write a Lambda Function to poll and compute new metric data from a set of metrics, and then publish them back to cloudwatch.

Would be nice to be able to perform this kind of operation without need to provision Lambda

**Use-Case**

According to https://forums.aws.amazon.com/thread.jspa?threadID=309159

We can get a rough estimate on how many active connections are there by performing math expression.

**Comment by tomkerkhove** [comment]
Interesting request as this could be interesting for multiple scalers. What would the expression look like?

**Comment by coderanger** [comment]
I would imagine they mean a CloudWatch expression. We hardwire things to MetricStat here https://github.com/kedacore/keda/blob/main/pkg/scalers/aws_cloudwatch_scaler.go#L278 but CloudWatch allows asking for either a single metric or an expression https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_MetricDataQuery.html

**Comment by tomkerkhove** [comment]
Makes sense to have this as a field indeed! Are you willing to contribute this @jeffjen ?

**Comment by jeffjen** [comment]
> Makes sense to have this as a field indeed! Are you willing to contribute this @jeffjen ?

I can work on this

My proposed change will be to not mess with multiple metrics in a query since it will change the struct to include an array of dimensions / namespace

The first step will be to just provide a way to add Math Expression for a single metric on designated dimension and namespace.

**Comment by tomkerkhove** [comment]
Thanks!

I don't know how the SDK works but I'd just add a new optional `expression` field which just passes through to AWS CloudWatch and let it handle everything?

**Comment by dekelev** [comment]
I've opened this [PR](https://github.com/kedacore/keda/pull/2911) to add alternative expression field and also changed the scaler to use int64 instead of float64.

**Comment by JorTurFer** [comment]
I'd say that this is done by https://github.com/kedacore/keda-docs/pull/755. Feel free to reopen the issue if it's not done
