### ISSUE TITLE
Support metadata annotations in ScaledJob template

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda#1627]
**Proposal**

Support metadata annotations in ScaledJob template to control its behavior

**Use-Case**

https://github.com/kedacore/keda/pull/1322#issuecomment-781691004

**Comment by fjmacagno** [comment]
Are there any plans for this to be implemented?

**Comment by sringel** [comment]
With this [patch](https://github.com/kedacore/keda/issues/1311#issuecomment-801477202) applied to the ScaledJob CRD annotations defined the jobTargetRef template metadata are applied to the pod successfully. So if you are running into this issue check the ScaledJob CRD and ensure it has `x-kubernetes-preserve-unknown-fields: true`.

**Comment by tomkerkhove** [comment]
Closing as it's already fixed.
