### ISSUE TITLE
graphite 支持

### ISSUE THREAD

**Issue by shuoliu1** [kedacore/keda#1628]
**Proposal**

是否考虑支持 graphite 用作triggers 

**Scaler Source**

graphite

**Scaling Mechanics**

水平伸缩

**Authentication Source**

api_key

是否考虑支持 graphite 用作triggers

**Comment by tomkerkhove** [comment]
Would definately be interesting, are you able to contribute this?

**Comment by shuoliu1** [comment]
Consider implementing scalers in combination with Graphite render api

**Comment by shuoliu1** [comment]
https://github.com/kedacore/keda/pull/1749
