### ISSUE TITLE
Validate scenarios work as expected on minikube and update README

### ISSUE THREAD

**Issue by jeffhollan** [kedacore/keda#164]

**Comment by jeffhollan** [comment]
@bbrowning has done some testing here, @Aarthisk done some too. I'm cool to close this but if @Aarthisk you want to do one last validation pass?

Sounds like idea is to track a quick 5 min README for any notes with minikube we can just use this issue to do

**Comment by Aarthisk** [comment]
https://github.com/kedacore/keda/pull/245

**Comment by Aarthisk** [comment]
There was not much with regards to minikube that I added except that you can deploy using the yaml if Helm is not an option.
