### ISSUE TITLE
Re-tag and push our existing images in Docker Hub to GitHub Container Registry (GHCR)

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda#1651]
Re-tag and push our existing images in Docker Hub to GHCR so that all our images are available in GitHub Container Registry as well.

Relates to https://github.com/kedacore/governance/issues/16

**Comment by zroubalik** [comment]
Do we really want to retag the old images? What is the benefit? (In order to consume them, we would need to change the old (already released) manifests.

**Comment by tomkerkhove** [comment]
As discussed offline, this was mainly to have all our artifacts in the new place; not perse to regenerate old artifacts/manifests.

https://github.com/orgs/kedacore/packages?type=source
