### ISSUE TITLE
Convenience CLI

### ISSUE THREAD

**Issue by arschles** [kedacore/keda#1661]
### Proposal

It would be helpful for some users -- as well as folks getting started -- to have a CLI tool that provides commands to submit a `ScaledObject` / `ScaledJob` and other KEDA-specific resources. It would not be complex, but it would provide an imperative interface for KEDA's functionality.

A few more notes:

- This tool would be roughly analogous to the `kubectl create ...` commands, which provides a simplified imperative interface into base Kubernetes functionality (e.g. `Deployment`, `Service`, and more).
- This idea initially came up discussing the [http add on](https://github.com/kedacore/http-add-on), but it was suggested that we could provide functionality for KEDA core as well, so I'm starting the discussion here
- _I'll volunteer to build this CLI if there's support_
    - I've built a [similar CLI](https://github.com/kubernetes-sigs/service-catalog/tree/master/cmd/svcat) and several users of that project adopted it as their primary method of interacting with the system

### Use-Case

Generally, there are some people who prefer to interact with a system imperatively. This would help me personally when trying to start scaling an _already running `Deployment`_, especially one for which I don't necessarily have the YAML for on disk. One example is if I'm running someone else's application or have installed their Helm chart from their remote repo.

Beyond that:

- it would be helpful to provide an alternative way to get started with KEDA using the CLI (similar to how the [interactive tutorials](https://kubernetes.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive/) use `kubectl create`).
- I assume there are workloads that use scripts to do deployments, rather than 100% YAML/declarative. These use cases may benefit from a CLI command rather than submitting YAML

**Comment by tomkerkhove** [comment]
Duplicate of https://github.com/kedacore/keda/issues/173 I think?

**Comment by arschles** [comment]
Ah, thanks @tomkerkhove. I'll close this and move my comment over to there.
