### ISSUE TITLE
KEDA Dashboard

### ISSUE THREAD

**Issue by jeffhollan** [kedacore/keda#167]
The option to expose a dashboard that would surface details on the cluster and what KEDA sees / how it is behaving.  Potentially also could show Azure Functions and info on the triggers and health

**Comment by yaron2** [comment]
+1 on the dashboard, but a KEDA dashboard probably shouldn't have an Azure Functions specific functionality.

It may be interesting to create an Azure Functions Dashboard for Kubernetes that has much more metadata than things related to the scope of KEDA.

**Comment by Aarthisk** [comment]
Maybe a KEDA dashboard that can be extended then? I think of the Keda dashboard as showing the scaled objects, triggers, + last scale times, current metrics . HPA description for each scaled object and the scale controller logs and especially errors. The functions part of it can include function logs and runtime logs.

**Comment by tomkerkhove** [comment]
> +1 on the dashboard, but a KEDA dashboard probably shouldn't have an Azure Functions specific functionality.

Agreed!

**Comment by asavaritayal** [comment]
[Dashboard Mocks Part 1.pdf](https://github.com/kedacore/keda/files/3383245/Dashboard.Mocks.Part.1.pdf)

**Comment by tomkerkhove** [comment]
Dashboard is available here: https://github.com/kedacore/dashboard

**Comment by jeffhollan** [comment]
I'll take the action to at least document how to use the dashboard from the keda-docs repo

**Comment by tomkerkhove** [comment]
Already working on it!

**Comment by tomkerkhove** [comment]
Done via https://github.com/kedacore/keda-docs/pull/18 & https://github.com/kedacore/keda-docs/pull/16
