### ISSUE TITLE
Scale deployments by pre-determined number

### ISSUE THREAD

**Issue by hasansalimkanmaz** [kedacore/keda#1670]
### Proposal

Is it possible to define a scale parameter for scaling deployments by some number? Currently, it is only possible scale deployments by 1. Pods are going from 0 to maxReplicaCount by 1.

### Use-Case

I would like to scale my deployments by 5. For ex. 5-10-15-20. Currently, I can only do it by 1 as 1-2-3-4-5... 

I need this for the following. I am using kafka for streaming and I am scaling my pods. If I scale down/up, Kafka rebalances and waits for some time. This results in overhead. If I can scale by 5, this rebalancing issue will not affect me too much.

**Comment by tomkerkhove** [comment]
That's a reasonable ask I think, WDYT @zroubalik?

**Comment by coderanger** [comment]
This would be a request for an hpa feature I think? Once supported in core then we could add a pass through but keda doesn’t own the pod count calculation.

**Comment by zroubalik** [comment]
Yes, we would need HPA to implement this.

For your scenario, you could try to tweak scaling behaviour: https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#support-for-configurable-scaling-behavior

**Comment by hasansalimkanmaz** [comment]
Thank you very much for your kind and fast replies. I will adapt my code accordingly.
