### ISSUE TITLE
[Docs] Keda is more than running Functions

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda#168]
As discussed in the community standup Keda is more than running Functions.

However, the Keda overview here only shows Function pods, maybe we should add just "Pods" next to it?

![Keda Overview](https://raw.githubusercontent.com/kedacore/keda/6157e65eedc1d0319fe44173a468974903c229d0/images/keda-arch.png)

**Comment by yaron2** [comment]
I agree, Function pods should just be pods.

@jeffhollan

**Comment by jeffhollan** [comment]
Not sure if that is *enough* to close this issue but linked PR

**Comment by thdotnet** [comment]
you can leave the image as it is, just include a disclaimer in the overview.

**Comment by tomkerkhove** [comment]
That's good enough for me @jeffhollan but if you'd like to add a separate icon with Function Pods that's fine for me as well - Up to you.

From my side, it's ok to close - Thanks!

> you can leave the image as it is, just includes a disclaimer in the overview.

Having this in the overview would be good as well but it should be in the image as well. Personally, I'd rather look at a visual overview to get a quick glance rather than reading the full into, but that might just be me.

**Comment by yaron2** [comment]
The KEDA description says: ``` KEDA is a Kubernetes-based Event Driven Autoscaling component. It provides event driven scale for any container running in Kubernetes ```.

We replaced the image to show only pods, and we say KEDA can be used with any type of container under the ```Azure Functions Integration```.

Is this good enough to close this issue?

**Comment by tomkerkhove** [comment]
Certainly, thank you very much!
