### ISSUE TITLE
[KafkaScaler] Scale beyond the number of partitions

### ISSUE THREAD

**Issue by lionelvillard** [kedacore/keda#1683]
### Proposal

Add an option to disable the check that prevent KafkaScaler to scale beyond the number of partitions

### Use-Case

When KEDA is used to scale CRDs, the number of replicas does not necessarily match the number of Kafka consumers. For instance, KEDA can we used to increase/decrease the throughput (msgs/sec). In this usecase it makes sense to have more replicas than partitions.

**Comment by zroubalik** [comment]
Fine by me!
@tomkerkhove wdyt?

**Comment by tomkerkhove** [comment]
Fine by me.

- Tom Kerkhove

________________________________
