### ISSUE TITLE
Should remove app.kubernetes.io/version label from label selectors

### ISSUE THREAD

**Issue by anggao** [kedacore/keda#1694]
### Report

When upgrade from KEDA v2.0.0 to v2.2.0, we encountered the following issue

Deployment.apps "keda-operator" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app":"keda-operator", "app.kubernetes.io/part-of":"keda-operator", "app.kubernetes.io/version":"2.2.0"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable

### Expected Behavior

We should be able to upgrade KEDA without any issue

### Actual Behavior

Deployment.apps "keda-operator" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app":"keda-operator", "app.kubernetes.io/part-of":"keda-operator", "app.kubernetes.io/version":"2.2.0"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable

### Steps to Reproduce the Problem

1. Install KEDA by https://github.com/kedacore/keda/releases/download/v2.0.0/keda-2.0.0.yaml
2. upgrade KEDA with https://github.com/kedacore/keda/releases/download/v2.2.0/keda-2.2.0.yaml
3.

### Logs from KEDA operator

```
example
```

### KEDA Version

2.1.0

### Kubernetes Version

1.18

### Platform

Any

**Comment by zroubalik** [comment]
Relevant kustomize issue: https://github.com/kubernetes-sigs/kustomize/issues/1009
