### ISSUE TITLE
[Docs] Create an FAQ

### ISSUE THREAD

**Issue by jeffhollan** [kedacore/keda#170]
I think the best place is a wiki page.  We could potentially link to it from the README.  A few questions:

- Does this only work with Azure Functions containers?
- How does this compare to Knative?
- How can I get involved?

Some other questions I've gotten but I'm not sure if we should include or not:

- How much does KEDA cost (mostly people coming at it from the Azure side I think)
- Do all the function triggers and bindings work in KEDA?

**Comment by tomkerkhove** [comment]
Maybe another one would be in terms of support.

It's still in experimental phase so good to mention that *and* what support to expect, presumably best-effort on GH?

**Comment by anirudhgarg** [comment]
Finally closing this out - have added a FAQ here:  https://github.com/kedacore/keda/wiki/FAQ
