### ISSUE TITLE
[Sample] Azure Monitor -> Prometheus -> KEDA

### ISSUE THREAD

**Issue by jeffhollan** [kedacore/keda#171]
Will assign @tomkerkhove once he accepts the invite to the org :)

Depends on https://github.com/kedacore/keda/issues/156

**Comment by tomkerkhove** [comment]
Done, feel free to assign me!

**Comment by tomkerkhove** [comment]
Given most of it works via KEDA by default I'm not sure if this sample even makes sense anymore, or does it?

This is based on #252 /cc @yaron2

**Comment by yaron2** [comment]
Can you please provide a brief description of this sample?

**Comment by tomkerkhove** [comment]
Pull Azure Monitor metrics in Prometheus and autoscale on that metric

**Comment by yaron2** [comment]
IMO you are right, this is redundant now. There can be a sample for Prometheus that demonstrates multiple metrics examples, Azure Monitor can be one of them.

**Comment by tomkerkhove** [comment]
Then I would close this issue.

If we add the sample that pulls in metrics from Azure Monitor to Prometheus we can refer to Promitor to achieve this.

**Comment by asavaritayal** [comment]
Closing issue in favor of adding a sample - https://github.com/kedacore/keda/issues/253
