### ISSUE TITLE
Support for mutual TLS for Redis connections

### ISSUE THREAD

**Issue by faun** [kedacore/keda#1722]
### Proposal

It appears that there is not currently support for mutual TLS when connecting to a Redis database. We use mTLS to connect to our Redis databases. Without this, the connection to the Redis database is rejected. Without the ability to connect to the Redis databases over mTLS means we cannot use the any of the Redis-based functionality in KEDA.

### Use-Case

In order to support connecting to a Redis database that utilizes mutual TLS, we would need to be able to pass a certificate authority certificate, a client certificate, and a private key:

```console
REDIS_URL="rediss://..."
REDIS_KEYS_DIR="$PWD"
CACERT_PATH="$REDIS_KEYS_DIR/server_ca.pem"
CERT_PATH="$REDIS_KEYS_DIR/user.crt"
KEY_PATH="$REDIS_KEYS_DIR/user_private.key"

redis-cli -u "$REDIS_URL" --tls --cacert "$CACERT_PATH" --cert "$CERT_PATH" --key "$KEY_PATH"
```

**Comment by zroubalik** [comment]
Makes sense to me, there are other scalers (eg. Kafka) that support TLS.
Is this something you'd like to contribute?

**Comment by faun** [comment]
I think so. I'd need some guidance, but yes.

**Comment by zroubalik** [comment]
@faun great. As I said, you can check how other scalers implemented this.

**Comment by faun** [comment]
I think we've decided to use the Metrics API scaler instead to simplify things a bit for the first iteration. Thanks for the guidance, @zroubalik!

**Comment by mhemken-vts** [comment]
Was this ever implemented?
