### ISSUE TITLE
Kubernetes Workload Autoscaler

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda#1735]
### Proposal

When workloads on Kubernetes depend on each other, they typically need to scale accordingly.

This helps to avoid flooding downstream services because of scaling out other components.

For example - Workload A processes a queue and interacts with workload B. Workload A can autoscale based on queue depth and workload B on CPU. But in some scenarios, you want to add 1 instance for workload B for every 4 instances of workload A

### Scaler Source

Number of instances of another workload that depends on the current workload

### Scaling Mechanics

Add 1 instance for your workload, for every `n` instances of another workload.

### Authentication Source

Kubernetes service account

**Comment by JorTurFer** [comment]
Any news about this? We have one use case where this option could help. In our case, we have one "RabbitMQ" hub which scale depending on the queues, but that hub does calls to other services. Now we are scaling them in base of the CPU this could improve our scaling rules taking in consideration the CPU and the amount of instances in the hub.
If you still think that this is useful, I can try to implement it during the summer :)
WDYT?

**Comment by tomkerkhove** [comment]
My use-case is similar indeed and we are open for contributions so that would be great, thank you @JorTurFer!

**Comment by JorTurFer** [comment]
Hi @tomkerkhove 
I will try to do it, it's a good task to improve my Golang :)

**Comment by JorTurFer** [comment]
I'm starting this and I have some doubts about it.
What could be better, use match selectors and count the pods directly or use the controller (deployment or statefulset) to get the child pods?
I don't have a strong opinion, but I guess that is more powerful to use selectors instead of the controller.
WDTY?

**Comment by tomkerkhove** [comment]
I would personally rely on the controller. What about you @zroubalik ?

**Comment by zroubalik** [comment]
Selectors on the other hand could be more generic - we can match mutliple Deployments 🤷‍♂️

**Comment by JorTurFer** [comment]
> Selectors on the other hand could be more generic - we can match mutliple Deployments 🤷‍♂️

We can match multiple Deployments or workloads in general, not only Deployments, that is the reason why I'm doubting...

**Comment by zroubalik** [comment]
> > Selectors on the other hand could be more generic - we can match mutliple Deployments 🤷‍♂️
> 
> We can match multiple Deployments or workloads in general, not only Deployments, that is the reason why I'm doubting...

Yeah, that's what I thought.

**Comment by JorTurFer** [comment]
Okey, 
If there isn't a strong opinion about it, I think that I will take the approach of match selectors. They can bring exactly the same capabilities as using controller, but also can another capabilities if you need them.
How do you feel with this approach @tomkerkhove ?

**Comment by tomkerkhove** [comment]
Sounds good to me!
