### ISSUE TITLE
Explicitly setting minReplicas to 0 results in an error

### ISSUE THREAD

**Issue by jeffhollan** [kedacore/keda#176]
The default for minReplicas on a ScaledObject is 0.  If you explicitly set it to 0 it throws an exception that it needs to be >= 1.  If you leave nil it does set it to 0.  

[This appears to be the offending conditional block](https://github.com/kedacore/keda/blob/eefb318a67240df1779f1a6c9c92776bc8249fcc/pkg/handler/scale_handler.go#L131-L136)

**Comment by tomkerkhove** [comment]
I have not written Go before, but this might be a good opportunity to dive into it

**Comment by yaron2** [comment]
@tomkerkhove I have time to close this today, but I'll leave it to you if you explicitly state you're on it :)

**Comment by tomkerkhove** [comment]
No no, feel free to fix it @yaron2 I will be too slow anyway!

**Comment by yaron2** [comment]
@jeffhollan can you please paste the exception log?
