### ISSUE TITLE
azure_pipelines_scaler PAT base64 parsing

### ISSUE THREAD

**Issue by hieumoscow** [kedacore/keda#1765]
https://github.com/kedacore/keda/blob/89da00b24fa961b0c2d58687b031d25cf26e3ce3/pkg/scalers/azure_pipelines_scaler.go#L125

@troydn thanks for this scaler, I am implementing this for one of my customer in Asia. 
BTW, When referencing the PAT token, there seems to be an extra "\n" token at the end of the decode PAT value that I had to include a trim method to get rid of it.
[Changes](https://github.com/kedacore/keda/compare/main...hieumoscow:main#diff-f2e89ab024d43f3779d3c08dd6ada9c899967cd9ccc21c764bcd8980a39d600cL125)

Not sure how this came about and whether there is a base64 decode issue here?
Hieu

**Comment by troydn** [comment]
@hieumoscow the base64 encoding/decoding should be fine. I'm guessing you are using a secret with TriggerAuthentication?
How did you base64 encode your PAT? If you do this manually you should use `echo -n "PAT" | base64`. The -n option does not output a trailing newline.

**Comment by hieumoscow** [comment]
Thanks @troydn, that helped. I tried with both TriggerAuthentication & just pure secret / personalAccessTokenFromEnv like you test.
Works nicely now.

One question is during scaling in, it seems that we are not able to control which pod/runner it's going to terminate. Thus some running pipeline might break because of this. Is there a way to handle this (this is a general KEDA issue I believe)? 

My thinking is that there are two options:
1. Turn into ScaledJob to ensure the job finish it's execution. 
1. K8s 1.21 has a beta feature called [Pod Cost](https://github.com/kubernetes/enhancements/tree/master/keps/sig-apps/2255-pod-cost) that will help to influence the order of terminations among pods. 

Thanks @troydn

**Comment by zroubalik** [comment]
Unfortunately there's no way how to control which pod will be scaled down (as KEDA relies on HPA for the scaling). The Pod Cost feature could help with this, but because KEDA is not controlling the applications or data itself, it is very hard for KEDA to actually set the priorities on the scaled pods. We will have to come up with some mechanism.

**Comment by tomkerkhove** [comment]
There is also a blog post in the works that talks about this - https://github.com/kedacore/keda-docs/pull/431

Bottom line; use Jobs, not Deployments

**Comment by hieumoscow** [comment]
This is very useful, thanks @tomkerkhove @zroubalik. I have been testing with --once in the agents.
Just running tests to ensure that we can scale out and in without impacting the jobs as well as putting affinity to upgrade k8s gracefully in production.
