### ISSUE TITLE
Cron: no validation for range input in start an end field in metadata

### ISSUE THREAD

**Issue by Ritikaa96** [kedacore/keda#1809]
### Report

Cron standard include range as an input too. When i tried : 

> End:              18 * * * *
> Start:             11-13 * * * *

SO created with no error. Scaling happened with start at 13 and end at 18 minutes.
or 

> when start: -32 * * * * 

It started containers with terminating state and deployment available number become 0.  No error in operator or scaledObject log.
There should be validation for range value input too. May I ask , are we taking different  start and end inputs rather than range intentionally? How about a different field for eg. Range? 

### Expected Behavior

There should be validation and set error for no support for range in SO events or there should be provision for using range inputs

### Actual Behavior

Cron syntax with range as an input too. When i tried : 

> End:              18 * * * *
> Start:             11-13 * * * *

SO created with no error. Scaling happened with start at 13 and end at 18 minutes.
or 

> when start: -32 * * * * 

It started containers with terminating state and deployment available number become 0. No error in scaledobject events or operator logs

### Steps to Reproduce the Problem

1. use start  Start:    11-13 * * * * & end : 18 * * * * for first case & for second case- use start: -13 * * * * in cron scaledObject trigger metadata
2. apply SO and check the logs in `kubectl describe so`
3. Check output log from `kubectl logs -n keda keda-operator-xxxx-xxxx`

### Logs from KEDA operator

No error occurred/mentioned though desired replicacount not achieved. the scaling is acc. to min replicacount

### KEDA Version

2.2.0

### Kubernetes Version

1.20

### Platform

Other

### Scaler Details

Cron

**Comment by tomkerkhove** [comment]
I'm not sure I'm getting your questions/report, can you elaborate on it please?

**Comment by Ritikaa96** [comment]
Hi @tomkerkhove , What i want to know is 

1. are we open for another metadata field for simple 'range' type input as cron syntax allow ranges too . For eg. schedule: 30-35 * * * * it will simply merge start and end. Here the trigger would be from 30th minute to 35th minute of every hour.
2. If we are not open for Range input, then a validation is needed for input values to start and end because i tried : **start**: 30-35 * * * * and **end**: 40 * * * * , and the scaling wasn't happening as expected.

**Comment by Ritikaa96** [comment]
@tomkerkhove also giving values like **start**: -30 * * * * will result in pods initiated with a **state: terminating** . I understand there is rare case for such inputs but we have to add some tests  and validation for these too.

**Comment by zroubalik** [comment]
Hi @Ritikaa96 as per the validation for values like `start: -30 * * * *`, we should definitely check that!

For the range, I don't have a strong opinion, it might bring additional complexity, because there will be more options how to specify the scaler, so I wonder if there's a real benefit. But if there's a demand for this, I am definitely open to that.

**Comment by Ritikaa96** [comment]
@zroubalik , Hi! I Don't think specific demand for range field is there. But we have to add validation for input with hyphens **(-)**, in case user try to add range or try some negative scenario because there is no validation for this in the code yet.

**Comment by zroubalik** [comment]
Yeah agree on that

**Comment by Ritikaa96** [comment]
Hi @zroubalik . added the validation in [this](https://github.com/kedacore/keda/pull/1836) PR. PTAL.
