### ISSUE TITLE
ScaledObject - Implicit maintenance-mode deactivation

### ISSUE THREAD

**Issue by houstonj1** [kedacore/keda#1818]
### Proposal

Similar to a native HPA for Kubernetes, it would be nice if the ScaledObject supported [implicit maintenance-mode deactivation](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#implicit-maintenance-mode-deactivation).

If the target of the ScaledObject is set to a number of replicas below the current minReplicaCount, autoscaling would be paused. 

### Use-Case

This would be incredibly helpful for maintenance scenarios where the metric source is still active. For example, if I need to do maintenance on a system that depends on RabbitMQ, I should be able to scale those applications down, without removing the ScaledObject or preventing other systems from reading from RabbitMQ.

### Anything else?

I couldn't seem to find any issues related to this, but I am happy to close this if there is already an open discussion. Thanks!

**Comment by zroubalik** [comment]
relevant: https://github.com/kedacore/keda/issues/944

**Comment by houstonj1** [comment]
> relevant: #944

Ah, totally missed this one. I'll close this in favor of the discussion happening in #944

**Comment by zroubalik** [comment]
@houstonj1 no worries! feel free to add your opinion on #944
