### ISSUE TITLE
Consider using Renovate instead of Dependabot

### ISSUE THREAD

**Issue by zroubalik** [kedacore/keda#1823]
### Proposal

Dependabot opens a PR for each dependency, it would be better to have all deps grouped and opened as one PR. Seems like Dependabot doesn't have this feature, but Renovate does:
https://github.com/dependabot/dependabot-core/issues/1190

https://github.com/renovatebot/renovate

https://dev.to/omaiboroda/try-to-update-your-dependencies-once-a-month-5dm5

**Comment by tomkerkhove** [comment]
Renovate is great, I use it myself 🙊

**Comment by tomkerkhove** [comment]
https://github.com/kedacore/keda/pull/1824
