### ISSUE TITLE
Integrate CI/CD with GitHub releases

### ISSUE THREAD

**Issue by jeffhollan** [kedacore/keda#185]
Whenever we release a version of the docker container there should be a corresponding GitHub release to track releases and changes.

/cc @ahmelsayed

**Comment by ahmelsayed** [comment]
CI/CD part is mostly done. There are 3 workflows:

* [master build](https://github.com/kedacore/keda/blob/master/.github/workflows/master-build.yml)
* [pull request validation](https://github.com/kedacore/keda/blob/master/.github/workflows/pr-validation.yml)
* [nightly e2e test](https://github.com/kedacore/keda/blob/master/.github/workflows/nightly-e2e.yml)

**Comment by tomkerkhove** [comment]
Awesome - Thanks!

Will it create a GitHub release for official releases as well or not?

**Comment by jeffhollan** [comment]
@ahmelsayed and @anirudhgarg will manage releases going forward.  Much of it is automated, but will still require human aspects for some parts.  No immediate plans to improve from what we have done for 1.0.0 so far.  Closing for now
