### ISSUE TITLE
Not seeing any HPA after deploying scaledobject

### ISSUE THREAD

**Issue by Savitha-Amaldev** [kedacore/keda#1856]
After deploying scaled objects, I'm not able to verify whether it started scaling or not. when I describe the scaled object, I'm not seeing any events triggered. Before I used to see events as scaled object is active or if there is any warning or not How to check whether something is missing in my environment or not. Any help for debugging the scaled objects are greatly appreciated

**Comment by Savitha-Amaldev** [comment]
my scaled object looks like this:

---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: prometheus-keda-scaledobject
  namespace: aa
spec:
  scaleTargetRef:
    name: fastload-lcache-mem-only
  pollingInterval: 60 # Optional. Default: 30 seconds
  # cooldownPeriod: 30 # Optional. Default: 300 seconds
  minReplicaCount: 2 # Optional. Default: 0
  maxReplicaCount: 20 # Optional. Default: 100
  triggers:
    - type: prometheus
      metadata:
       metricName: nginx_ingress_controller_requests
       query: nginx_ingress_controller_requests{job="metrics-ingress",namespace="aa", service="xyz"}
       serverAddress: "http://localhost:9090"
       threshold: "50"

**Comment by tomkerkhove** [comment]
Can you please provide the KEDA logs?

**Comment by tomkerkhove** [comment]
And what is the output of kubectl get scaledobjects?

**Comment by Savitha-Amaldev** [comment]
> Can you please provide the KEDA logs?

I couldn't find much logs regarding this.. I used ">kubectl logs scaledobjects/<scaledobjectname> -n <scaledobject deployed namespace> -c keda-operator and got a one line error which I'm mentioning below
error: no kind "ScaledObject" is registered for version "keda.sh/v1alpha1" in scheme "k8s.io/kubectl/pkg/scheme/scheme.go:28"

**Comment by Savitha-Amaldev** [comment]
> And what is the output of kubectl get scaledobjects?

I can see my scaledobject in the namespace

**Comment by tomkerkhove** [comment]
Our CRD doesn't provide any logs, you need to check the operator of KEDA itself, can you check the logs there and share the output please?

Also, can you run `kubectl get scaledobject` and share the output please?

**Comment by zroubalik** [comment]
And I would add `kubectl get crd | grep keda`, seems like your CRDs are not correctly installed

**Comment by Savitha-Amaldev** [comment]
> Our CRD doesn't provide any logs, you need to check the operator of KEDA itself, can you check the logs there and share the output please?
> 
> Also, can you run `kubectl get scaledobject` and share the output please?
  NAME                                   SCALETARGETKIND      SCALETARGETNAME     MIN   MAX   TRIGGERS     AUTHENTICATION                   READY   ACTIVE   AGE
mssql-constr-hvr-keda-scaledobject                          yzxyzxyzxyzxyzoord     2     20    mssql        keda-trigger-auth-mssql-secret                    26m
mssql-constr-keda-scaledobject                             xyzxyzxyzxyzxyzxyzxyz   2     20    mssql        keda-trigger-auth-mssql-secret                    152m
mssql-keda-scaledobject                                    xyzxyzxyzxyzxyzxyzxyz   2     20    mssql                                                          3h13m
prometheus-httpmet-keda-scaledobject                       xyzxyzxyzxyzxyzxyzxyz   2     20    prometheus                                                     72m
prometheus-keda-scaledobject           apps/v1.Deployment  xyzxyzxyzxyzxyzxyzxyz   2     20    prometheus                                    True    False    19h
  
This is  how it looks.. crds are installed correctly as i can see one hpa created for one scaledobject. But none of the others are getting created

**Comment by tomkerkhove** [comment]
Can you also share the logs of the KEDA operator please?
