### ISSUE TITLE
Replace `golint` linter with `revive`

### ISSUE THREAD

**Issue by zroubalik** [kedacore/keda#1868]
### Proposal

In our linter we are using `golint` plugin which is deprecated, we should replace it with `revive` and fix any potential linter problems in the codebase.

https://github.com/kedacore/keda/blob/d75dbee5b9ab29ddfb26ee972611cd87c5b03f95/.golangci.yml#L20

```
level=warning msg="[runner]  The linter 'golint' is deprecated (since v1.41.0) due to: The repository of the linter has been archived by the owner.  Replaced by revive."
```

### Anything else?

Related: https://github.com/kedacore/keda/issues/1158

**Comment by Abhay2412** [comment]
I could give this a shot if you would like

**Comment by zroubalik** [comment]
> I could give this a shot if you would like

@Abhay2412 sure! that would be great :)

**Comment by Abhay2412** [comment]
Thank you for the opportunity :)
