### ISSUE TITLE
Custom Scaling Policies

### ISSUE THREAD

**Issue by Hassnain-Alvi** [kedacore/keda#1869]
### Proposal

I want to scale my deployment based on metric so using KEDA but should be deployed in a different way. i want to restart all my deployment pods after each up scale / down scale. Reason for this is pod dependency on max replica count

### Use-Case

ave containers running thread of my application acting as a consumer on database and processing records. I need to keep track of replicas and pass it as a parameter to my pods. The pods currently require 2 params to process records to avoid duplication.

>     Replica number
>     Max number of replicas

So pods use JVM modding techniques to fetch unique records from DB so that duplicate records are not processed by 2 pods.

### Anything else?

 am not sure if that sort of functionality is already present or possible with KEDA but i didn't find it so asking here. Is there any way i can extend kubernetes HPA functionality or KEDA to define custom scaling policies ?

**Comment by zroubalik** [comment]
Unfortunately that's not possible with KEDA and I don't think that this is something that's supported by HPA either (but you should double check that).

As a workaround, you can implement an operator, that will be watching the deployments and if the replica count changes, it could kill all relevant pods.

**Comment by tomkerkhove** [comment]
An alternative is triggering a Job to kill all pods with kubectl when the deployment is changing replica counts.

You can rely on the Kubernetes events for that.
