### ISSUE TITLE
Bug in updating a deployment?

### ISSUE THREAD

**Issue by elucidsoft** [kedacore/keda#187]
Note sure if this is me or its a bug but I deployed an HttpFunction. I accidentally had the authLevel set to user so I was getting a 401 error. I updated it to "anonymous" and redeployed, but it did not appear to take affect at all.  Which is odd...

**Comment by elucidsoft** [comment]
Yes so I was able to verify the deployment doesn't work correctly, when I deleted the pod and let Kubernetes automatically recreate it from the ReplicaSet the changes appeared. I think if you do a deployment it should pick up on this automatically no?

**Comment by yaron2** [comment]
This is probably an Azure Functions Core Tools issue and not a KEDA issue.

@ahmelsayed can you assist?

@elucidsoft if you do ```kubectl get pod <id> -o yaml``` do you see the imagePullPolicy?
Unless you see imagePullPolicy: always it means if you push a new version to the same image k8s wont pick up on it. If you use a different image name it should work.

**Comment by elucidsoft** [comment]
Yes, it's set to Always

**Comment by elucidsoft** [comment]
What I did notice though is if you let it scale down to 0, and then hit it has latest version. I mean that is pretty obvious but just thought I would mention it.

**Comment by yaron2** [comment]
Yeah, because the pod gets recreated and pulls latest.

Its an issue with Core Tools, we should probably check if a deployment already exists we call the set image command for the deployment.

**Comment by elucidsoft** [comment]
Yes I agree...

**Comment by ahmelsayed** [comment]
thanks @yaron2, @elucidsoft. I'll take care of it in the core tools.

**Comment by yaron2** [comment]
Closing as a core tools issue.

**Comment by elucidsoft** [comment]
Did you file this over at the core tools repo because I didn't see where
you did that and before it's closed at least that needs to happen.

**Comment by yaron2** [comment]
Yeah just did.

https://github.com/Azure/azure-functions-core-tools/issues/1301
