### ISSUE TITLE
Getting error "pq: parameter "ssl" cannot be changed now " when connecting to postgres using tls

### ISSUE THREAD

**Issue by WhoAteDaCake** [kedacore/keda#1876]
### Report

When using **PostgreSQL** scaler with a `connectionFromEnv` and `?ssl=1` attached to url, the connenction will fail

### Expected Behavior

Connection should succeed

### Actual Behavior

Connection fails with 
> "pq: parameter "ssl" cannot be changed now " when connecting to postgres using tls

### Steps to Reproduce the Problem

1.**PostgreSQL** scaler with a `connectionFromEnv` and `?ssl=1` attached to url

### Logs from KEDA operator

```
2021-06-09T17:04:37.183Z	ERROR	controller	Reconciler error	{"reconcilerGroup": "keda.sh", "reconcilerKind": "ScaledObject", "controller": "scaledobject", "name": "api-group-text-visual-anomaly-detection-scaled", "namespace": "default", "error": "error getting scaler for trigger #0: error establishing postgreSQL connection: pq: parameter \"ssl\" cannot be changed now"}
```

### KEDA Version

2.3.0

### Kubernetes Version

1.19

### Platform

Microsoft Azure

### Scaler Details

PostgreSQL

### Anything else?

Found reference to the same issue here:
https://github.com/uber/cadence/issues/3756

And the merge, which fixed it here:
https://github.com/uber/cadence/pull/3758

**Comment by zroubalik** [comment]
I think that you should configure Promethes auth with these settings, not via url params: https://keda.sh/docs/2.3/scalers/prometheus/#authentication-parameters

**Comment by WhoAteDaCake** [comment]
I'm using https://keda.sh/docs/2.3/scalers/postgresql/ not prometheus?

**Comment by zroubalik** [comment]
Sorry, my mistake. But for postgresql, I can see there is`sslmode` parameter, have you tried that?
