### ISSUE TITLE
Add automated tests for PRs

### ISSUE THREAD

**Issue by jeffhollan** [kedacore/keda#188]
Ideally could validate that the scaling logic is working so when folks open up pull requests it can validate and run through tests

**Comment by ahmelsayed** [comment]
I added E2E tests that run once a day. I had the same basic E2E setup but it got broken by few access changes on azure and it was using bash scripts so it was a bit hard to setup, debug, add to, etc.

The new e2e setup uses typescript and should be a lot simpler to add tests to or debug existing tests. I added a readme here https://github.com/kedacore/keda/tree/master/tests
