### ISSUE TITLE
hpa is not created as part of deployment

### ISSUE THREAD

**Issue by endejoli** [kedacore/keda#1895]
### Report

we have a opensift 4.5 cluster. we installed KEDA through operator
```
$ oc get all -n keda
NAME                                     READY   STATUS    RESTARTS   AGE
pod/keda-olm-operator-77875674d5-mmw2s   1/1     Running   0          9h

NAME                                READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/keda-olm-operator   1/1     1            1           9d

NAME                                           DESIRED   CURRENT   READY   AGE
replicaset.apps/keda-olm-operator-5667fffddc   0         0         0       9d
replicaset.apps/keda-olm-operator-77875674d5   1         1         1       15h
```
we are trying to test mysql scaledobject  using the example mentioned here https://github.com/turbaszek/keda-example/blob/master/keda/mysql-hpa.yaml

Once we perform oc apply -f mysql-hpa.yaml, scaledobject resource gets created fine
```
$ oc get scaledobjects
mysql-scaledobject                     dummy                   4     mysql                                        19m
```
But it doesnt create a hpa resource
```
$oc get hpa
No resources found test namespace.
```
How do we  debug this issue? None of the logs give any clue as well

### Expected Behavior

hpa resource should get created

### Actual Behavior

Np hpa resource got created
```
$oc get hpa
No resources found test namespace.
```

### Steps to Reproduce the Problem

1. oc apply -f https://github.com/turbaszek/keda-example/blob/master/keda/mysql-hpa.yaml
2. oc get hpa
3.

### Logs from KEDA operator

```
{"level":"info","ts":1623888075.4025164,"logger":"controller","msg":"Starting workers","reconcilerGroup":"","reconcilerKind":"Secret","controller":"secret","worker count":1}
{"level":"info","ts":1623888075.4581237,"logger":"controller","msg":"Starting workers","reconcilerGroup":"keda.sh","reconcilerKind":"KedaController","controller":"kedacontroller","worker count":1}
{"level":"info","ts":1623888075.4065857,"logger":"controller","msg":"Starting workers","reconcilerGroup":"","reconcilerKind":"ConfigMap","controller":"configmap","worker count":1}
```

### KEDA Version

2.3.0

### Kubernetes Version

1.19

### Platform

Red Hat OpenShift

### Scaler Details

MySQl

**Comment by zroubalik** [comment]
Please see the `How to install KEDA in the cluster` section in the operator description, it can be seen here as well:
https://operatorhub.io/operator/keda

You need to create `KedaController` CustomResource named `keda` in namespace `keda`. This will trigger the installation of KEDA, which is being handled by the operator (KEDA-OLM-Operator) that you have just installed.
