### ISSUE TITLE
Keda as a generic pull-based autoscaler for K8s and Knative

### ISSUE THREAD

**Issue by bbrowning** [kedacore/keda#19]
I'd love to see Kore become a generic pull-based autoscaler for Kubernetes and Knative. Below are the general high-level things I believe are needed to make that happen:

- [ ] Open source Kore
- [ ] Define an extension or plugin mechanism. If Kore supports various Azure services and Kafka out of the box, how would a user add support for another service? AMQP, other cloud provider services, etc? Where would that code live? Does it all need to live in the Kore repo? How would the person deploying Kore enable or disable specific service support?
- [ ] Where would the Knative PodAutoscaler implementation the delegates to Kore live? Should that part live in Knative itself and just depend on Kore, which keeps Kore from needing to take a dependency on Knative? Or should it live in Kore? Or its own repo, independent of either?
- [ ] Add unit and e2e tests so we have confidence in releases
- [ ] Give Kore the option to watch a single namespace instead of only all namespaces. This is trivial if we move to an operator-sdk style layout, but even with what's here today it's just adding an environment variable and a bit of logic to control which namespaces we watch. I believe this is important because Kore handles `Secret` objects and, at least while it's fairly new, limiting its privileges to reading `Secrets` in a single namespace seems like a good idea.

This issue is to have a conversation about the above and track any other bits of work we need to make it happen.

**Comment by aslom** [comment]
Started exploratory work on it with @zroubalik on it in https://github.com/knative/eventing/issues/2153
