### ISSUE TITLE
RabbitMQ connections not being closed

### ISSUE THREAD

**Issue by maricneven** [kedacore/keda#1912]
### Report

My KEDA function is triggered by messages from a RabbitMQ queue.  When I check RabbitMQ, I am noticing that the number of connections keeps rising.  It seems that each time a message triggers my function, a new connection is opened.  For whatever reason, after the message is processed, it would seem that the connection is not being closed. Over time, this exhausts all the available connections for RabbitMQ, and messages can no longer be processed.  I know that the messages are indeed being processed as I am seeing the output after the work is done.

### Expected Behavior

Connections to RabbitMQ should be closed after messages are processed by my Python KEDA functions.

### Actual Behavior

Connections are staying open to RabbitMQ - over time, the max connection limit is reached (this is the case no matter what the limit is set to).

### Steps to Reproduce the Problem
Names of functions + env variables have been replaced with []

data:
  [env variables]
apiVersion: v1
kind: Secret
metadata:
  name: [function name]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: [function name]
  labels:
    app: [function name]
spec:
  selector:
    matchLabels:
      app: [function name]
  template:
    metadata:
      labels:
        app: [function name]
    spec:
      containers:
      - name: [function name]
        image: [image name]
        env:
        - name: AzureFunctionsJobHost__functions__0
          value: [function name]
        envFrom:
        - secretRef:
            name: [function name]
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
          httpGet:
            path: /
            port: 80
            scheme: HTTP
        startupProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
          httpGet:
            path: /
            port: 80
            scheme: HTTP
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: [function name]
  labels: {}
spec:
  scaleTargetRef:
    name: [function name]
  pollingInterval: 10
  cooldownPeriod: 10
  minReplicaCount: 1
  maxReplicaCount: 3
  triggers:
  - type: rabbitmq
    metadata:
      direction: in
      queueName: [queue-name]
      hostFromEnv: RABBITMQCONNECTION
      queueLength: "5"

### KEDA Version

2.3.0

### Kubernetes Version

1.19

### Platform

Microsoft Azure

### Scaler Details

RabbitMQ

**Comment by zroubalik** [comment]
Have you tried to update to latest KEDA 2.4.0?

**Comment by rychuhardy** [comment]
Upgraded to KEDA 2.4.0

I've beed observing open channels and connections for ~24 hours, but it was not increasing.

So it looks like upgrade solved the issue.

**Comment by arschles** [comment]
@zroubalik @rychuhardy Can this issue be closed then?

**Comment by rychuhardy** [comment]
For me yes, although I did not open it
