### ISSUE TITLE
connectionStringFromSecret

### ISSUE THREAD

**Issue by ianadavies** [kedacore/keda#1913]
### Proposal

Need the ability to set connection string from a source other than the deployment environment variables.

### Use-Case

I am using KEDA with Azure functions (Queue Trigger) + ACI (Virtual Nodes). The problem is that ACI Virtual Nodes do not support ENV variables and these need to be baked into the docker image.

This is means that I cannot use KEDA scaled objects with deployments that target ACI virtual nodes.

NB : The nodes will not start if the ENV variables exist :/

### Anything else?

Nothing else, unless there is something I have missed or there is another way to achieve this ?

**Comment by tomkerkhove** [comment]
>  The problem is that ACI Virtual Nodes do not support ENV variables and these need to be baked into the docker image.

Are you sure about that? As far as I know that is not the case.

**Comment by tomkerkhove** [comment]
Also, what queue are you using? Depending on it, they provide various ways to authenticate.
