### ISSUE TITLE
Support Azure DevOps Server for Azure Pipelines

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda#1919]
### Proposal

Support Azure DevOps Server for Azure Pipelines

### Anything else?

Relates to #1285

**Comment by JorTurFer** [comment]
This PR looks like a good place for refactoring the code and remove duplications related with supporting non-public clouds in other scalers, WDYT @v-shenoy ?

**Comment by v-shenoy** [comment]
> This PR looks like a good place for refactoring the code and remove duplications related with supporting non-public clouds in other scalers, WDYT @v-shenoy ?

Yup, sounds good.

**Comment by v-shenoy** [comment]
I installed my own DevOps server on an Azure VM with Azure DevOps Express following the instructions [here](https://docs.microsoft.com/en-us/azure/devops/server/install/get-started) and [here](https://docs.microsoft.com/en-us/azure/devops/server/install/single-server).

The scaler is able to fetch metrics when provided with the PAT and the appropriate server URL / bindings configured during the setup. No changes need to be done to support them.

@JorTurFer @tomkerkhove 

Just going to send a PR with the refactoring for active directory endpoints, if that is alright?

**Comment by v-shenoy** [comment]
I installed my own DevOps server on an Azure VM with Azure DevOps Express following the instructions [here](https://docs.microsoft.com/en-us/azure/devops/server/install/get-started) and [here](https://docs.microsoft.com/en-us/azure/devops/server/install/single-server).

The scaler is able to fetch metrics when provided with the PAT and the appropriate server URL / bindings configured during the setup. No changes need to be done to support them.

@JorTurFer @tomkerkhove

Just going to send a PR with the refactoring for active directory endpoints, if that is alright?

**Comment by v-shenoy** [comment]
Raised a PR with the refactored changes. As for this issue, I think this should be closed now.
