### ISSUE TITLE
Username used in place of password in IBM MQ scaler

### ISSUE THREAD

**Issue by tdolby-at-uk-ibm-com** [kedacore/keda#1938]
It looks like the username variable "val" is used instead of the password variable "value" in the IBM MQ scaler, which makes authentication fail in many (most?) cases.

https://github.com/kedacore/keda/blob/a84c5cc1534bec5a9bc5e027fcebedd3673ac3d3/pkg/scalers/ibmmq_scaler.go#L140

passwordFromEnv would work as expected.

**Comment by tdolby-at-uk-ibm-com** [comment]
Verified using netcat to dump the actual REST request made by the scaler; can submit a PR if needed.

**Comment by tomkerkhove** [comment]
That would be awesome, thank you!
