### ISSUE TITLE
kubectl get scaledobject only displays one trigger

### ISSUE THREAD

**Issue by amirschw** [kedacore/keda#1943]
### Report

For scaled objects with multiple triggers, `kubectl get scaledobject` only shows the first trigger:

```bash
~ $ k get scaledobject myapp
NAME           SCALETARGETKIND      SCALETARGETNAME   MIN   MAX   TRIGGERS     AUTHENTICATION   READY   ACTIVE   AGE
myapp          apps/v1.Deployment   myapp             1     2     prometheus                    True    True     7d

~ $ k get scaledobject myapp -o jsonpath='{.spec.triggers[*].type}'
prometheus cpu
```

### Expected Behavior

All trigger types should be displayed

### Actual Behavior

Only the first trigger is displayed

### Steps to Reproduce the Problem

1. create a scaled object with two triggers
2. run `kubectl get scaledobject`

### Logs from KEDA operator

N/A

### KEDA Version

2.2.0

### Kubernetes Version

1.19

### Platform

Microsoft Azure

### Scaler Details

any (e.g. prometheus, cpu, memory)

**Comment by amirschw** [comment]
I took a closer look and found it's actually a kubectl issue with CRDs: https://github.com/kubernetes/kubectl/issues/517.
LMK if you want me to close this one or keep it open until it's fixed upstream.

**Comment by tomkerkhove** [comment]
Thanks for checking! It's ok to keep it open.

**Comment by SpiritZhou** [comment]
The CRD spec of scaleobject has added JSONPath to show all triggers. But kubectl still does not support displaying array type of printcolumn. https://github.com/kubernetes-sigs/controller-tools/issues/652

**Comment by zroubalik** [comment]
Yes, that's the problem. Maybe we can workaround this by an additional Status field, that will be basically a string of all triggers.
