### ISSUE TITLE
Getting datatype error though the values passed is of string 

### ISSUE THREAD

**Issue by taragurung** [kedacore/keda#1955]
### Report

Getting the error `spec.triggers.metadata.queueLength in body must be of type string: "integer"` though the values passed is integer string. 

I am trying to create ScaledObject via helm chart and passing the value for queueLength as following:
 **queueLength: "5"** 

### Expected Behavior

successfully created helm release with Triggerauthentication and Scaledobject created with the values passed from values.yaml

### Actual Behavior

successfully creating a helm release with ScaledObject Created. 

### Steps to Reproduce the Problem

1. install keda verion 2.1.0 with helm
2. create a local helm chart 
3. Create a template for TriggerAuthenticaton and ScaledObject.
4. Set values
5. Run local helm `helm upgrade --install keda-scaler .  -f values.yaml `

### Logs from KEDA operator

```
Error: UPGRADE FAILED: failed to create resource: ScaledObject.keda.sh "aws-sqs-queue-scaledobject" is invalid: spec.triggers.metadata.queueLength: Invalid value: "integer": spec.triggers.metadata.queueLength in body must be of type string: "integer"
helm.go:84: [debug] ScaledObject.keda.sh "aws-sqs-queue-scaledobject" is invalid: spec.triggers.metadata.queueLength: Invalid value: "integer": spec.triggers.metadata.queueLength in body must be of type string: "integer"

```

### KEDA Version

2.1.0

### Kubernetes Version

1.20

### Platform

Amazon Web Services

**Comment by endyrocket** [comment]
What was the fix? Facing the same issue

**Comment by endyrocket** [comment]
Fixed by adding quotes in scaledobject value field

**Comment by shulyakav** [comment]
I had a similar issue. 

Was fixed by a change:

**Myvalue: {{ .Values.cpuValue  }}**

to

**Myvalue: {{ .Values.cpuValue | quote }}**
