### ISSUE TITLE
[InfluxDB Scaler] Allow queries that return integers in addition to those that return floats

### ISSUE THREAD

**Issue by philomory** [kedacore/keda#1973]
### Proposal

The InfluxDB scaler should continue to function if the query used returns an integer rather than a float. At the moment, there is an undocumented requirement that queries must return floats.

### Use-Case

I'd like to query values from InfluxDB that happen to be stored as integers (event counters and such) without having to remember to manually convert those values to floats in each Flux query.

### Anything else?

[influxdb_scaler.go lines 173 to 176](https://github.com/kedacore/keda/blob/03d0f98fb4b9c81e04be0dbc1069bb4a3a03f5b5/pkg/scalers/influxdb_scaler.go#L173-L176) contains the following code:

```golang
val, ok := result.Record().Value().(float64)
if !ok {
    return 0, fmt.Errorf("value could not be parsed into a float")
}
```

It seems like adding an additional branch that handles integers wouldn't be a huge burden.

**Comment by zroubalik** [comment]
Seems like a fair requests, I don't think there is something that prevents us in using int there as well. @yquansah wdyt?

@philomory Are you willing to contribute this one?

**Comment by yquansah** [comment]
@zroubalik I mean it eventually does get truncated to an integer https://github.com/kedacore/keda/blob/03d0f98fb4b9c81e04be0dbc1069bb4a3a03f5b5/pkg/scalers/influxdb_scaler.go#L193

but there is some assumptions being made here. Is there a particular error or something you are encountering? @philomory

**Comment by philomory** [comment]
@zroubalik Yes, I think I'd be able to contribute a fix. At the very least, I can give it a shot.

@yquansah Yes, if you start with a query that returns an integer the entire process fails, while logging the error "value could not be parsed into a float". 

For example, if I try to use the following query:

```
from(bucket: "example")
  |> range(start: -5m)
  |> filter(fn: (r) => r._measurement == "job_stats" and r._field == "backlog_size")
  |> last()
```
... this will return the number of jobs in a backlog, which is an integer. Used as-is, this causes the entire thing to fail; if I want it to work, I have to manually convert my data to floats within my query, e.g.:

```
from(bucket: "example")
  |> range(start: -5m)
  |> filter(fn: (r) => r._measurement == "job_stats" and r._field == "backlog_size")
  |> last()
  |> map(fn: (r) => ({r with _value: float(v: r._value)})
```

**Comment by yquansah** [comment]
@philomory Got you. Okay this should be something I can write a fix for

**Comment by zroubalik** [comment]
@yquansah  the PR is already opened, feel free to do a review
https://github.com/kedacore/keda/pull/1977
