### ISSUE TITLE
Kore metrics as custom/external Kubernetes metrics

### ISSUE THREAD

**Issue by markusthoemmes** [kedacore/keda#20]
Kubernetes defines [APIs to get custom/external metrics into the system](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#support-for-metrics-apis). They can also be used to feed the HPA for example.

As Kore progresses, we could think about organizing the code in a way, that makes it straightforward to eventually plug it into the HPA (or other autoscalers). I think these APIs make for a very nice uniform way to provide the metrics Kore needs.

See https://github.com/kubernetes-incubator/custom-metrics-apiserver/blob/master/pkg/provider/interfaces.go#L104-L108 for the interface to implement. This might directly influence #19 as it could be a partial answer as to how the code should be organized.

I'd envision a custom/external metrics adapter per event-source. Kore's own autoscaler would poll these metrics in a fixed interval (as today) for now, to provide the cases Kore need.

**Comment by so0k** [comment]
What's the difference between setting up an external metrics provider like prometheus and using that for HPA 

versus using KEDA? I've been going through concepts and FAQ but can't seem to find an answer to this question

**Comment by tomkerkhove** [comment]
The difference is that Prometheus metrics provider solely covers Prometheus while KEDA allows you to get metrics from more sources.

Does that answer your question?

**Comment by tomkerkhove** [comment]
Added https://github.com/kedacore/keda-docs/issues/119 to clarify this

**Comment by so0k** [comment]
awesome, that helps! I'll put a small comment on that issue
