### ISSUE TITLE
Add ScaledObject shortname to CRD

### ISSUE THREAD

**Issue by lee0c** [kedacore/keda#200]
[CRD example with shortNames field](https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#create-a-customresourcedefinition)

It'd be awesome to see a shorthand for "ScaledObject" - I've been using `sco` in my cluster but I'd like input on what you'd all want to see as a shorthand. I'm happy to put in the PR for it once it's decided as it's a one line change.

**Comment by tomkerkhove** [comment]
I think `sco` & `so` would make sense indeed!

**Comment by tomkerkhove** [comment]
@jeffhollan I would consider this as required for v1.0

**Comment by tomkerkhove** [comment]
I think this one is finished and ready to close

**Comment by yaron2** [comment]
Closed with #211
