### ISSUE TITLE
I am trying to upgrade the keda v 1.4.0 to 2.3.0 after uninstalling keda (1.4.0)

### ISSUE THREAD

**Issue by nidiculageorge** [kedacore/keda#2004]
AKS CLuster : 1.20.7
Keda Version :1.4.0  

helm uninstall -n keda keda
W0803 11:45:45.714229     997 warnings.go:67] apiregistration.k8s.io/v1beta1 APIService is deprecated in v1.19+, unavailable in v1.22+; use apiregistration.k8s.io/v1 APIService
release "keda" uninstalled
nithin@Azure:~$ kubectl delete -f https://raw.githubusercontent.com/kedacore/keda/v1.4.0/deploy/crds/keda.k8s.io_scaledobjects_crd.yaml
Warning: apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
customresourcedefinition.apiextensions.k8s.io "scaledobjects.keda.k8s.io" deleted

Its stuck in deleting state 

The link I followed was https://keda.sh/docs/1.4/deploy/

**Comment by zroubalik** [comment]
Did you removed all deployed ScaledObjects/ScaledJobs as well?

**Comment by nidiculageorge** [comment]
Hi @zroubalik 

The issue has been resolved after deleting the following from the Custom Resource Definitions

![image](https://user-images.githubusercontent.com/43850474/128499034-a4c63dce-8c01-4d97-9ff9-a01bbafd5588.png)

scaledjobs.keda.sh                               
scaledobjects.keda.k8s.io                        
scaledobjects.keda.sh    
triggerauthentications.keda.k8s.io

These needs to be removed from the CRD's
