### ISSUE TITLE
Should Helm chart deploy a service?

### ISSUE THREAD

**Issue by lee0c** [kedacore/keda#201]
Currently, the keda Helm chart deploys a ClusterIP service but I don't believe it's used for anything.

Last I checked the `func kubernetes install` setup for keda does not deploy this ClusterIP, so I'm guessing it's a holdover from the default Helm chart & hasn't been removed.

Also something I'm happy to put a PR in for once there's an answer in place.

**Comment by jeffhollan** [comment]
Good question. 

/cc @Aarthisk @ahmelsayed

**Comment by ahmelsayed** [comment]
I think the ClusterIP service is needed for the custom metrics adapter to work. Kubernetes gets those metrics over http, though @Aarthisk would know more. The core-tools should be [creating the same service](https://github.com/Azure/azure-functions-core-tools/blob/dev/src/Azure.Functions.Cli/StaticResources/keda.yaml#L50-L67) as well.

**Comment by ahmelsayed** [comment]
Closing this issue.
