### ISSUE TITLE
List Keda Helm Chart on hub.helm.sh

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda#203]
List Keda Helm Chart on [hub.helm.sh](https://hub.helm.sh) to make it more discoverable.

**Comment by tomkerkhove** [comment]
I'm happy to pick this up if you want, presuming the Helm chart repo won't change soon?

**Comment by tomkerkhove** [comment]
I'm ready to send a PR to https://github.com/helm/hub if you agree.

I've called it *KEDA Core* repo which is pointing to https://kedacore.azureedge.net/helm.
It lists @ahmelsayed as maintainer which is same as chart but can change it if you want.

Details:
  - See https://github.com/tomkerkhove/hub/blob/keda-helm-repo/repos.yaml#L269
  - See https://github.com/tomkerkhove/hub/blob/keda-helm-repo/config/repo-values.yaml#L108

**Comment by tomkerkhove** [comment]
@jeffhollan I'd consider this important for v1.0

**Comment by tomkerkhove** [comment]
Thoughts anybody? @jeffhollan maybe?

**Comment by jeffhollan** [comment]
Looks good to me. Thanks @tomkerkhove

**Comment by tomkerkhove** [comment]
We are live on hub.helm.sh - https://hub.helm.sh/charts/kedacore/keda-edge
