### ISSUE TITLE
Keda Operator Panics if MetricSpec.TargetSize is 0

### ISSUE THREAD

**Issue by KTAtkinson** [kedacore/keda#2056]
### Report

Keda operator panics when the target size for a metric is 0.

### Expected Behavior

The server shouldn't panic when the scale target size is 0, it should write an error or other information to the logs. In addition, if the metrics server returns an error, the resulting metric spec should probably not be saved.

### Actual Behavior

panic

### Steps to Reproduce the Problem

1. Create an external metrics server in Golang (other languages may work too), provide your server with a dummy implementation for the 'GetMetricSpec` endpoint, this server should return an error
2. Create a Scaled[Object,Job] that uses your scaler.
3. See that the Keda server crashes.

### Logs from KEDA operator

```
runtime error: integer divide by zero
oroutine 286 [running]:
github.com/kedacore/keda/pkg/scaling.devideWithCeil(...)
	/workspace/pkg/scaling/scale_handler.go:279
github.com/kedacore/keda/pkg/scaling.(*scaleHandler).checkScaledJobScalers(0xc0004e8180, 0x24cdfe0, 0xc0007c2cc0, 0xc0006aa550, 0x1, 0x1, 0xc0004596c0, 0x0, 0xc0006ae2e0, 0x3)
	/workspace/pkg/scaling/scale_handler.go:273 +0xa7d
github.com/kedacore/keda/pkg/scaling.(*scaleHandler).checkScalers(0xc0004e8180, 0x24cdfe0, 0xc0007c2cc0, 0x20bae00, 0xc0004596c0, 0xc00074a0b8)
	/workspace/pkg/scaling/scale_handler.go:195 +0x145
github.com/kedacore/keda/pkg/scaling.(*scaleHandler).startScaleLoop(0xc0004e8180, 0x24cdfe0, 0xc0007c2cc0, 0xc00073d2c0, 0x20bae00, 0xc0004596c0, 0xc00074a0b8)
	/workspace/pkg/scaling/scale_handler.go:126 +0x1f8
 created by github.com/kedacore/keda/pkg/scaling.(*scaleHandler).HandleScalableObject
	/workspace/pkg/scaling/scale_handler.go:94 +0x368
```

### KEDA Version

2.0.0-beta

### Kubernetes Version

1.18

### Scaler Details

external

### Anything else?

I ran into this issue while creating a new external scaler that would  only be used for push based scaling. In this case it would be idea if I didn't have to implement the entire interface. This is a more general problem though, as this sort of failure can bring down the entire Keda server and throw it into `CrashLoopBackoff`.

**Comment by zroubalik** [comment]
This has been solved already: https://github.com/kedacore/keda/blob/fe032ccc41f1af1aa4dcdcf4f1d05bba9150fdbf/pkg/scaling/scale_handler.go#L300-L302

Is there a particular reason you are using 2.0.0-beta version? I highly recommend you to update to 2.4.0.
