### ISSUE TITLE
Error in log for unrelated env variable in Metric server

### ISSUE THREAD

**Issue by rangarb885** [kedacore/keda#2059]
### Report

Keda metric server looks at unrelated environment variable on deployment & prints error message on log

### Expected Behavior

Keda metric server should only be interested on the env variables on the deployment which are used by trigger-auth related to that Scaled Object/deployment

### Actual Behavior

Keda metric server looks at unrelated environment variable on deployment & prints error message on log

### Steps to Reproduce the Problem

1. Create a deployment which has env variable say `ABCD`  with value `status.hostIP`
2. Create Scalar (in my case SQS) and corresponding trigger-auth
3. Keda operator will start logging the error while running metric polling each time. 

### Logs from KEDA operator

Keda Metric server log, which prints each time the metric is polled. 

```
I0826 04:32:07.903733       1 scale_resolvers.go:313] keda_metrics_adapter/scalehandler "msg"="cannot resolve env to a value. fieldRef and resourceFieldRef env are skipped" "name"="adapter" "namespace"="sbx" "type"="ScaledObject" "env-var-name"="ABCD"
```

### KEDA Version

2.4.0

### Kubernetes Version

1.21

### Platform

Amazon Web Services

### Scaler Details

SQS

**Comment by zroubalik** [comment]
Are you able to test a Deployment without the potentially problematic ENV variable? `SIGNALFX_AGENT_HOST` ? 

Would you mind pasting (redacted) `envs` section from the Deployment as it is defined, ie. not `describe` output, but `kubectl get -oyaml` ?

Thanks

**Comment by rangarb885** [comment]
Unfortunately i cant remove `SIGNALFX_AGENT_HOST` as it fail the deployment.

Below is the result of `kubectl get deploy adapter -n sbx -o yaml`

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2021-08-26T03:02:40Z"
  generation: 31
  labels:
    app: adapter
  name: adapter
  namespace: sbx
  resourceVersion: "437585"
  uid: 84cdf64a-83ac-4dfc-ab31-6d180ab1916a
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: adapter
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: adapter
    spec:
      automountServiceAccountToken: true
      containers:
      - env:
        - name: SPRING_PROFILES_ACTIVE
          value: sbx
        - name: SPLUNK_ACCESS_TOKEN
          value: <redacted>
        - name: APP_NAME
          value: adapter
        - name: SIGNALFX_AGENT_HOST
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        image: <redacted>.dkr.ecr.us-west-2.amazonaws.com/adapter:sbx-testing-2
        imagePullPolicy: IfNotPresent
        name: adapter
        resources:
          requests:
            cpu: 75m
            memory: 1200Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 65534
        runAsNonRoot: false
      serviceAccount: adapter
      serviceAccountName: adapter
      shareProcessNamespace: false
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-08-26T03:02:40Z"
    lastUpdateTime: "2021-08-26T03:02:55Z"
    message: ReplicaSet "adapter-85bb95ffb6" has successfully
      progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2021-08-26T23:00:59Z"
    lastUpdateTime: "2021-08-26T23:00:59Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 31
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
```

**Comment by zroubalik** [comment]
Okay, I can see the problem. It is a `fieldRef` which is not supported and this env is skipped.

@rangarb885 do you actually see error messages in the Metrics Adapter? Or just a log message? Do you see the the message with default log level setting?

**Comment by rangarb885** [comment]
@zroubalik  :
Log messages seen under `DEBUG` level. I have enabled DEBUG for our monitoring purpose.  
I see this log entry on both `keda-operator` logs as well as `keda-operator-metrics-apiserver` logs.

```
2021-08-31T15:42:39.300Z	DEBUG	scalehandler	cannot resolve env to a value. fieldRef and resourceFieldRef env are skipped	{"type": "ScaledObject", "namespace": "sbx", "name": "adapter", "env-var-name": "SIGNALFX_AGENT_HOST"}
```

**Comment by zroubalik** [comment]
Okay, so this is expected, it is defined to be printed as Debug message.

https://github.com/kedacore/keda/blob/0e4a01f55cec12e65d11041f40f9d98d179ae2e5/pkg/scaling/resolver/scale_resolvers.go#L312-L315

What do you suggest?

**Comment by rangarb885** [comment]
IMO as keda is not going to use `fieldRef` and `resourceFieldRef` , we can safely ignore them from logging as well.
