### ISSUE TITLE
Conflicting Helm Chart naming

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda#206]
I was looking around and noticed that the [Helm docs](https://github.com/kedacore/keda/#install-keda-edge-chart) are referring to the Helm chart as `kedacore/keda-edge` which is also on the Helm Chart repo.

However, in the codebase it is referred to as `keda`.

I'd like to align this, if I may, but was wondering what the expected name would be?

**Comment by zroubalik** [comment]
@tomkerkhove still relevant?

**Comment by tomkerkhove** [comment]
Frankly, I don't recall what this was about.

Did a search for `keda-edge` and nothing showed up so will close.
