### ISSUE TITLE
TriggerAuthentication/Vault: add support for vault namespace

### ISSUE THREAD

**Issue by chapurlatn** [kedacore/keda#2084]
### Proposal

Support TriggerAuthentication for Vault Enterprise. For now, the Vault namespace feature can not be operate by TriggerAuthentication.

In the TriggerAuthentication spec, add an optional "spec.hashiCorpVault.namespace" in order to be compliant with all Vault install (and update the Vault authentication sequence accordingly).

Currently, it's not possible to setup a Vault TriggerAuthentication when using a namespace-based Vault server.
I could be useful to provide, in the spec, an optional "spec.hashiCorpVault.namespace" in order to be compliant with all Vault install.

Notes:
I checked Keda code and the corresponding handler do not implement namespace handling (https://github.com/kedacore/keda/blob/main/pkg/scaling/resolver/hashicorpvault_handler.go).
Here's an example of how to support namespace: https://github.com/hashicorp/vault/blob/main/api/client.go#L486

### Use-Case

This allow to perform Vault authentication on a Vault Enterprise platform organized with isolated namespaces.
This way, any team in some organization can manage its own Keda trigger authentication within its own Vault namespace.

### Anything else?

Useful links:
- [Vault Namespace doc](https://www.vaultproject.io/docs/enterprise/namespaces)
- [Hashicorp Vault Go client example with Vault namespace support](https://github.com/hashicorp/vault/blob/main/api/client.go#L486)
- [Keda Vault handler source](https://github.com/kedacore/keda/blob/main/pkg/scaling/resolver/hashicorpvault_handler.go)

Relates to https://github.com/kedacore/keda/discussions/2080

**Comment by zroubalik** [comment]
fixed in #2085
