### ISSUE TITLE
Provide scaler for ActiveMQ Classic

### ISSUE THREAD

**Issue by melisatanrverdi** [kedacore/keda#2120]
### Proposal

Provide a scaler for ActiveMQ Classic

### Scaler Source

ActiveMQ Classic

### Scaling Mechanics

Scale based on ActiveMQ Classic broker. Contacts ActiveMQ Classic's management endpoint to determine the queue's message count and scale accordingly.

### Authentication Source

Require username and password for authentication.

**Comment by RaulButuc** [comment]
Any chance for supporting ActiveMQ without auth being required? The company set up a staging AMQ which sits in a DMZ and is set up without authentication, as such there is no username or password to pass which results in the ScaledObject failing to become Ready.

**Comment by tomkerkhove** [comment]
That's something we could add - Would you mind opening a feature request and/or contribute it please?

**Comment by RaulButuc** [comment]
@tomkerkhove Sure, will have a look on Monday as I'm off for the weekend.
