### ISSUE TITLE
Keda Non-compliant for pods and containers should only run using approved user and group Ids

### ISSUE THREAD

**Issue by Sac-BRONGA** [kedacore/keda#2139]
### Report

We have enabled Azure Policy for "Kubernetes cluster pods and containers should only run with approved user and group IDs." but we received all the pods in all the containers are Non-Compliant. even we provide all the required parameters.

### Expected Behavior

The Keda Pods in the Cluster need to be Non Compliant. The Keda should run only in the provided user and group ids. 

### Actual Behavior

The Keda should run the provided User and Group Ids. It need to search for the User and Group Ids.

### Steps to Reproduce the Problem

1. Create Policy Kubernetes cluster pods and containers should only run with approved user and group IDs in the Azure Policies.
2. Deploy the AKS Cluster and Pod with Keda Image 
3. and check whether the policy is Non Compliant or Compliant.

### Logs from KEDA operator

```
example
```

### KEDA Version

2.2.0

### Kubernetes Version

1.21

### Platform

Microsoft Azure

**Comment by JorTurFer** [comment]
Hi,
How are you deploying KEDA? I have just tried and it's working, at least in my cluster. Maybe I'm doing something wrong
![image](https://user-images.githubusercontent.com/36899226/136272628-b957a38f-7547-426b-b9da-e4807bb276a8.png)

Basically I deployed the add-on to use Azure Policies and deployed KEDA into the cluster

**Comment by Sac-BRONGA** [comment]
Hi Ferrero,

We are deploying the Container from the below repository using helm chat with version 2.2.2

repository : ghcr.io/kedacore/keda-metrics-apiserver

Thanks,
Santosh C.

From: Jorge Turrado Ferrero ***@***.***>
Sent: Thursday, October 7, 2021 1:18 AM
To: kedacore/keda ***@***.***>
Cc: Santosh C ***@***.***>; Author ***@***.***>
Subject: [External]Re: [kedacore/keda] Keda Non-compliant for pods and containers should only run using approved user and group Ids (#2139)


Hi,
How are you deploying KEDA? I have just tried and it's working, at least in my cluster. Maybe I'm doing something wrong
[image]<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F36899226%2F136272628-b957a38f-7547-426b-b9da-e4807bb276a8.png&data=04%7C01%7CSantosh_C%40gap.com%7C631638078d9347a101b508d989022a22%7C348a129655b6466ea7af4ad1a1b79713%7C1%7C0%7C637691464671128791%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Gj%2BtI2b42R9RD5jt642UXlsbCZPaz3J2wY4EVQCLsgE%3D&reserved=0>

Basically I deployed the add-on to use Azure Policies and deployed KEDA into the cluster

-
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkedacore%2Fkeda%2Fissues%2F2139%23issuecomment-937000513&data=04%7C01%7CSantosh_C%40gap.com%7C631638078d9347a101b508d989022a22%7C348a129655b6466ea7af4ad1a1b79713%7C1%7C0%7C637691464671138746%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=hhQk2xWTccoUuwUN1yre6QLUmWhJexoGSLscV8FSJqw%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAVHBPLQXZN3275MBP74CX6TUFSRV7ANCNFSM5FJCH66A&data=04%7C01%7CSantosh_C%40gap.com%7C631638078d9347a101b508d989022a22%7C348a129655b6466ea7af4ad1a1b79713%7C1%7C0%7C637691464671138746%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=56%2F7GdxKeD%2Bvv0jHsIkSci%2BCv7D276W%2BHQBwPQh3aqM%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7CSantosh_C%40gap.com%7C631638078d9347a101b508d989022a22%7C348a129655b6466ea7af4ad1a1b79713%7C1%7C0%7C637691464671138746%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=CSCRw8caVAr6eT3BgafWVyf5s70MRo0Hayv2ZE7xeJg%3D&reserved=0> or Android<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7CSantosh_C%40gap.com%7C631638078d9347a101b508d989022a22%7C348a129655b6466ea7af4ad1a1b79713%7C1%7C0%7C637691464671148709%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ACDyhswAD5GpTTHhDooh1%2Bhe6jQret2zaaXgHGi6K%2Fg%3D&reserved=0>.

**Comment by Sac-BRONGA** [comment]
We have provided the group ids as.

"ranges": [
                {
                  "min": 1,
                  "max": 65535
                }
              ]

Thanks,
Santosh C.
From: Jorge Turrado Ferrero ***@***.***>
Sent: Thursday, October 7, 2021 1:26 PM
To: kedacore/keda ***@***.***>
Cc: Santosh C ***@***.***>; Author ***@***.***>
Subject: [External]Re: [kedacore/keda] Keda Non-compliant for pods and containers should only run using approved user and group Ids (#2139)


One question (I don't have experience with this). Are valid userid/groupsid needed to be defined or there is a built-in predefined group?
Looking the documentation I can't get this part. I mean, you can define values inside this group, but defaul values are [] in both cases.

-
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkedacore%2Fkeda%2Fissues%2F2139%23issuecomment-937545661&data=04%7C01%7CSantosh_C%40gap.com%7C02f031a1779c4afb892008d98967d99e%7C348a129655b6466ea7af4ad1a1b79713%7C1%7C0%7C637691901393012776%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=pHPFVZjA44MXQnqRQmH56kzt%2BPoZ3%2BkmotXrd5dSX4s%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAVHBPLWQZV7J7ZVZIDHGUMDUFVG7TANCNFSM5FJCH66A&data=04%7C01%7CSantosh_C%40gap.com%7C02f031a1779c4afb892008d98967d99e%7C348a129655b6466ea7af4ad1a1b79713%7C1%7C0%7C637691901393012776%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=88JKbyTUHy6D8OMymrd%2FKJmRdZ0HkAcpl1UUdvb5d40%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7CSantosh_C%40gap.com%7C02f031a1779c4afb892008d98967d99e%7C348a129655b6466ea7af4ad1a1b79713%7C1%7C0%7C637691901393022732%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=1oNrbtWLwChOBo90fvsbIPG5WvzEWaBTDgBNPGlcRFM%3D&reserved=0> or Android<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7CSantosh_C%40gap.com%7C02f031a1779c4afb892008d98967d99e%7C348a129655b6466ea7af4ad1a1b79713%7C1%7C0%7C637691901393022732%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=oGkMaYydAmuldf6B997nxhHPKhSl9SXb%2FQynw3QHgu0%3D&reserved=0>.

**Comment by JorTurFer** [comment]
Hi @Sac-BRONGA ,
I have it working on my cluster
![image](https://user-images.githubusercontent.com/36899226/136814922-6c6e0a9c-732b-4dea-9e07-1f9a5d17011c.png)

I have edited the parameters and these are mine:
![image](https://user-images.githubusercontent.com/36899226/136815152-cad302fb-0684-45aa-a14e-9d937d26bf63.png)

Basically I added the range to all (userids and gropuids). I know that in theory groupids are not important because the dropdown selection is `RunAsAny`  but... I added in any case to be sure xD

**Comment by JorTurFer** [comment]
> we install with Helm

Did you try setting the [securityContext inside helm values](https://github.com/kedacore/charts/blob/master/keda/values.yaml#L93-L99)?

I'm trying it right now to ensure that it works

**Comment by JorTurFer** [comment]
It works @Sac-BRONGA ,
now it's compliant again (thanks @tomkerkhove  for the idea :) )
![image](https://user-images.githubusercontent.com/36899226/137016903-8929be0f-0163-4cf8-b852-d9072d4fc02f.png)

**Comment by tomkerkhove** [comment]
Any update on this @Sac-BRONGA ?
