### ISSUE TITLE
[Samples] .NET Core 3.0 Worker

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda#216]
I'd be happy to contribute a .NET Core 3.0 Worker sample.

My initial thought was to create a Service Bus message pump but I'm open for suggestions.

**Comment by jeffhollan** [comment]
You cool if I assign this to you?

**Comment by tomkerkhove** [comment]
Sure!

**Comment by tomkerkhove** [comment]
Will show up on https://github.com/tomkerkhove/sample-dotnet-queue-worker-servicebus-queue until it's finished

**Comment by tomkerkhove** [comment]
We've been checking out KEDA at Codit and worked on the following sample - https://github.com/tomkerkhove/sample-dotnet-worker-servicebus-queue

We are happy to donate this to https://github.com/kedacore if you are interested.

**Comment by jeffhollan** [comment]
Absolutely.  This looks great

**Comment by tomkerkhove** [comment]
Happy to hear! I suggest that somebody gives it a try as well before giving a sign-off.
Then we can move it to this org.

**Comment by tomkerkhove** [comment]
The sample got donated to https://github.com/kedacore and is available [here](https://github.com/kedacore/sample-dotnet-worker-servicebus-queue).
