### ISSUE TITLE
increase function Timeout

### ISSUE THREAD

**Issue by lferreirad1** [kedacore/keda#218]
how can i´m increase function Timeout more then 5 minutes?

**Comment by yaron2** [comment]
Hi,

This is related to Azure Functions and not KEDA directly.
In any case, an example of how to set the timeout for your function to 10 minutes:

(in ```host.json```):

```
{
  "version": "2.0",
  "functionTimeout": "00:10:00"
}
```

Read more [here](https://docs.microsoft.com/en-us/azure/azure-functions/functions-host-json#functiontimeout).
