### ISSUE TITLE
Improve Redis support

### ISSUE THREAD

**Issue by jerbob92** [kedacore/keda#2182]
### Proposal

The Redis support is a little outdated and does not support the following functionality:

- ACL support, because you can't give it a username
- Sentinel support 

My proposal is to update go-redis v6.15.9 to v8.11.4 to support ACL in Redis 6+ and implement scalers for Redis Sentinel.

### ACL
[Redis added ACL in Redis 6](https://redis.io/topics/acl): to make use of this, the client also needs to support this, which has been added in later versions of go-redis. Updating the client and allowing to pass a username to the scalers will solve this.

### Sentinel
Our cluster uses Redis Sentinel, we use HAProxy now to point to the master server, but it's not perfect. 
go-redis supports Sentinel out of the box so we just need a way to pass metadata/authentication to support it. 

### Anything else?

With this change, total Redis support will come to 6 scalers:

- Redis Lists
- Redis Streams
- Redis Cluster Lists
- Redis Cluster Streams
- Redis Sentinel Lists
- Redis Sentinel Streams

The code is really similar and mostly in the same files. When adding the Sentinel support, I tried to make it as much in line with the current codebase, see #2181, however, this could probably be just 1 scaler right? Difference between the different scalers is minimal and we can easily add metadata to decide whether it's standalone, cluster or sentinel and lists or streams.

**Comment by zroubalik** [comment]
@jerbob92 we can close this one, right?

**Comment by jerbob92** [comment]
@zroubalik Yep :)
