### ISSUE TITLE
GCP Pub/Sub permission denied

### ISSUE THREAD

**Issue by ayushsearce** [kedacore/keda#2208]
### Report

We have used the GCP Pub/Sub trigger and provided the permissions to service account as mentioned in the documentation.
logs provide the error "KEDAScalerFailed 3s (x16 over 7m39s) keda-operator rpc error: code = PermissionDenied desc = Permission monitoring.timeSeries.list denied (or the resource may not exist)."
Even after providing the Owner permissions to the service account it throws same error.
Installed KEDA using "kubectl apply -f https://github.com/kedacore/keda/releases/download/v2.4.0/keda-2.4.0.yaml"
How we can resolve this?

### Expected Behavior

scaledObject must be able to scale the replicas on the basis of pub/sub messages

### Actual Behavior

Getting error 
"KEDAScalerFailed 3s (x16 over 7m39s) keda-operator rpc error: code = PermissionDenied desc = Permission monitoring.timeSeries.list denied (or the resource may not exist)."

### Steps to Reproduce the Problem

1.
2.
3.

### Logs from KEDA operator

```
example
```
KEDAScalerFailed 3s (x16 over 7m39s) keda-operator rpc error: code = PermissionDenied desc = Permission monitoring.timeSeries.list denied (or the resource may not exist)."

### Kubernetes Version

Other

### Platform

Google Cloud

**Comment by tomkerkhove** [comment]
Closing as there hasn't been response in a while, feel free to re-open if still an issue.
