### ISSUE TITLE
[Question] How to modify the CORS

### ISSUE THREAD

**Issue by idanshahar** [kedacore/keda#221]
I want to allow Azure Static Web Page to access to HTTP function that runs on KEDA on AKS.
The local setting is valid for debug mode. Is it possible to allow CORS at this moment?

**Comment by ahmelsayed** [comment]
Nope. The runtime doesn't handle CORS. It's handled either by the cli or the platform. You can open an ask [here](https://github.com/Azure/azure-functions-host) to add CORS support to the runtime itself.
