### ISSUE TITLE
Container registry page for KEDA is 404ing

### ISSUE THREAD

**Issue by arschles** [kedacore/keda#2215]
### Report

When I go to https://github.com/kedacore/keda/pkgs/container/keda, I get a 404 page when I am not logged into GitHub (i.e. in a private browsing window)

### Expected Behavior

The page does not 404

### Actual Behavior

The page 404s. The correct behavior exhibits when I am logged into GitHub

### Steps to Reproduce the Problem

1. Log out of GitHub or enter a private browsing window (i.e. incognito on Chrome)
2. Go to https://github.com/kedacore/keda/pkgs/container/keda
3. Observe that the page 404s

### Logs from KEDA operator

N/A

### KEDA Version

2.4.0

### Anything else?

This issue is not related to the KEDA software itself. Rather, it's related to project infrastructure. Note that the same issue is occurring with the HTTP Addon images: [interceptor](https://github.com/kedacore/http-add-on/pkgs/container/http-add-on-interceptor), [operator](https://github.com/kedacore/http-add-on/pkgs/container/http-add-on-operator) and [scaler](https://github.com/kedacore/http-add-on/pkgs/container/http-add-on-scaler). I suspect these are misconfigured as well, but I don't see anything wrong with the settings - they all are set to public visibility.

**Comment by tomkerkhove** [comment]
It looks like this is no longer the case, can you verify please @arschles?

**Comment by arschles** [comment]
Yup, looks like it's fine now. I checked the `kedacore/keda` package as well as the `http-add-on` interceptor package. Closing
