### ISSUE TITLE
Add e2e test for CPU Scaler

### ISSUE THREAD

**Issue by JorTurFer** [kedacore/keda#2219]
### Proposal

https://github.com/kedacore/keda/tree/main/tests

**Comment by Ritikaa96** [comment]
Hi @JorTurFer Is anyone working on this issue? If not, I'll be happy to take this up.

**Comment by JorTurFer** [comment]
Nobody is working on this AFAIK, so feel free to do it :)
Thanks for it!!

**Comment by Ritikaa96** [comment]
Hi @JorTurFer Added the Cpu test . PTAL
