### ISSUE TITLE
Add e2e test for Memory Scaler

### ISSUE THREAD

**Issue by JorTurFer** [kedacore/keda#2220]
### Proposal

https://github.com/kedacore/keda/tree/main/tests

**Comment by Ritikaa96** [comment]
Hi @JorTurFer Is anyone working on this issue? If not, I'll be happy to take this up.

**Comment by JorTurFer** [comment]
Nobody is working on this AFAIK, so feel free to do it :)
Thanks for it!!

**Comment by Ritikaa96** [comment]
Hi @JorTurFer , the cpu and memory e2e is way too similar to have two different test files, I was wondering if we should merge them and call it cpu-memory.test.ts
What do you think?

**Comment by Ritikaa96** [comment]
Hi @JorTurFer I've raised #2646 for this. PTAL!
