### ISSUE TITLE
RabbitMQ scaler scales on empty queues when using regex

### ISSUE THREAD

**Issue by alegmal** [kedacore/keda#2223]
### Report

When using KEDA 2.4 and rabbitmq scaler with regex it scales deployment as it thinks there are messages when queues are empty. We're using cloudamqp to host our rabbit.

### Expected Behavior

Scale based on operation strategy and number of msgs in queues

### Actual Behavior

Scales even though queues are empty

### Steps to Reproduce the Problem

1. apply keda 2.4 
kubectl apply -f https://github.com/kedacore/keda/releases/download/v2.4.0/keda-2.4.0.yaml

2. apply scaler with useRegex: true, operation: sum and mode: QueueLength

### Logs from KEDA operator

no errors in logs

### KEDA Version

2.4.0

### Kubernetes Version

1.20

### Platform

Google Cloud

### Scaler Details

RabbitMQ

### Anything else?

![Screen Shot 2021-10-28 at 15 34 50](https://user-images.githubusercontent.com/6178232/139256870-351d5eb0-4e64-46a4-b69b-9fb2851f45ea.png)
![Screen Shot 2021-10-28 at 15 34 28](https://user-images.githubusercontent.com/6178232/139256895-a5064281-0a11-4b6f-a57f-bdafa736c74b.png)

![Screen Shot 2021-10-28 at 15 31 49](https://user-images.githubusercontent.com/6178232/139256909-03f140d3-fa73-43d6-a0bf-02c7b0f912b2.png)

**Comment by JorTurFer** [comment]
Hi @alegmal ,
There is a known bug in RabbitMQ using regex in v2.4 (Basically I made a mistake and regex doesn't work at all :( ). The problem is fixed, and the next release will be during November.  
You can try it using main branch or wait until next release :)

**Comment by crisp2u** [comment]
@alegmal https://github.com/kedacore/keda/issues/2054
@JorTurFer which November ? :)

**Comment by JorTurFer** [comment]
hi @crisp2u 
Next release is already planned.  We would like to merge some PRs before it but between this week and the next week the new version should be released :)
You could check if you want the plans and decisions in the [Community Standup notes](https://hackmd.io/@jeffhollan/r127ErYiN?type=view)
