### ISSUE TITLE
Provide support for HTTPS for Selenium Grid scaler

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda#2252]
### Proposal

Provide support for HTTPS for Selenium Grid scaler

**Comment by JorTurFer** [comment]
Is this not already supported? I mean, [we are using the url provided in the trigger](https://github.com/kedacore/keda/blob/main/pkg/scalers/selenium_grid_scaler.go#L164)
```golang
req, err := http.NewRequestWithContext(ctx, "POST", s.metadata.url, bytes.NewBuffer(body))
```

Do you mean adding support to skip certificate validation? (like we are already doing with influx scaler)
