### ISSUE TITLE
Support google pubsub scaling when pubsub is in another google cloud project

### ISSUE THREAD

**Issue by visheyra** [kedacore/keda#2256]
### Proposal

When using keda along the google cloud pubsub scaler I want to be able to define in which google project the stackdriver metrics query should be performed.

### Use-Case

At my company, we have service account defined in google project A and pubsub in project B. And we allow access to pubsubs in project B from the service account in project A.

### Anything else?

The scaler is requesting metrics on stackdriver without specifying any project thus, using the project of the service account, which in my case is not where the pubsubs are defined.

Let me know if I can help more !

**Comment by jmalvarezf-lmes** [comment]
Hi @visheyra,

Today you can do it if you use a credential whose associated project is different.

Hope it helps,

Regards,

Jose Maria.

**Comment by jmalvarezf-lmes** [comment]
Ah, I understood wrong. Sorry for that. I was in the middle of coding something similar and proposing to the keda team as a PR. Hope it will make sense for them.

Regards,

Jose Maria.
