### ISSUE TITLE
Fix for bug #176 (Explicitly setting minReplicas to 0 results in an error) missed "scaleFromZero" function

### ISSUE THREAD

**Issue by genadyk** [kedacore/keda#226]
The default for minReplicas on a ScaledObject is 0. If you explicitly set it to 0 and the deployment is scaled to zero it will never leave that state. 

**if scaledObject.Spec.MinReplicaCount != nil** {
		deployment.Spec.Replicas = scaledObject.Spec.MinReplicaCount
	} else {
		*deployment.Spec.Replicas = 1
	}

the if condition should be :
if scaledObject.Spec.MinReplicaCount != nil && *scaledObject.Spec.MinReplicaCount > 0

**Comment by yaron2** [comment]
That was already fixed with #178.

**Comment by genadyk** [comment]
Please look at https://github.com/kedacore/keda/blob/0feeec05401a95ee36cfa9b28a4184d3ecea0eef/pkg/handler/scale_handler.go#L310

**Comment by yaron2** [comment]
Correct, #178 fix needs to be applied to ```scaleFromZero``` too. I'll submit a fix soon.
