### ISSUE TITLE
Automatically release container image for ARM

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda#2263]
Automatically release container image for ARM.

- CI on `main` branch: https://github.com/kedacore/keda/actions/workflows/main-build.yml
- Do the release as part of https://github.com/kedacore/keda/actions/workflows/release-build.yml

Relates to https://github.com/kedacore/keda/issues/779

**Comment by morganchristiansson** [comment]
No binaries are currently published? Only docker images. https://github.com/kedacore/keda/releases

If so I don't think this task is required/blocker to add ARM support in #779
