### ISSUE TITLE
NATS Authentication Support

### ISSUE THREAD

**Issue by Tharun-Sabbu** [kedacore/keda#2296]
### Proposal

Currently NATS isn't supporting Authentication as per documents https://keda.sh/docs/1.4/scalers/nats-streaming/#authentication-parameters, we would like to see support for TLS Mutual Authentication

**Comment by JorTurFer** [comment]
Hi @Tharun-Sabbu ,
This sounds good, supporting authentication methods is always worth :)
Are you open to contribute with this?

**Comment by Adarsh-verma-14** [comment]
Hi @JorTurFer , @zroubalik , I want to contribute it .
