### ISSUE TITLE
Scalers Should Use Numeric Types for Thresholds and Values

### ISSUE THREAD

**Issue by isugimpy** [kedacore/keda#2299]
### Proposal

It would be nice to have threshold and value fields accept plain numeric or integer values for scaling.  To retain backwards compatibility both strings which parse as numbers and actual numeric types could be allowed, if that's feasible in openAPIv3.

### Use-Case

YAML libraries are well known to cast values to different types based on how they look.  Because of this, even when providing a quoted value to force an integer to be a string (or even with the YAML `!!str` type hint), if a ScaledObject goes through any form of parsing or mutation (a great example being a GitOps workflow tool such as Flux, or passing through Kustomize), the YAML parser sees the value, assumes it should be an integer, and outputs it as one, causing apply failures due to the spec being incorrect.  Allowing plain numeric/integer values would help with this considerably.

Additionally, requiring string types for numeric values is counterintuitive to users, so this would be a win for user experience.

**Comment by JorTurFer** [comment]
Hi,
I think that using other type than string could be complicated because we should unify all the threshold names in order to have only 1 integer field. 
Now we are using `map[string]string` for trigger metadata (including threshold) and that is super flexible, we can reuse the same CRD with the same section for all scalers, and each scaler can use it own values. 
From my pov, this approach allows giving semantic names for each scaler threshold, and that is better than a generic name.

@ahmelsayed @tomkerkhove @zroubalik ?

**Comment by isugimpy** [comment]
I think `map[string]string` would still be viable to use internally, if the object from the CRD would accept either and it could be transformed at runtime to the necessary `string` value.  Looking at a glance, it looks like the `metadata` in the API spec is an `object`, so it should be feasible to do what would amount to the cast at runtime.  I could be wrong, though, I haven't written a CRD before.

**Comment by isugimpy** [comment]
After further thought, I think I have a rough idea on how this could be done.

https://github.com/kedacore/keda/blob/7b9817325fd88f291af6a224899bd385cb86bb3c/config/crd/bases/keda.sh_scaledobjects.yaml#L268-L269

The `metadata` field specifies 
```
additionalProperties:
  type: string
```
which could be changed to
```
additionalProperties:
  oneOf:
    - type: string
    - type: integer
    - type: number
```
And checks/conversions could be put into place on the various scalers for the known fields to type check them and convert as appropriate.  That'd be a lot to touch, but seems like a really good starting point.  A distinct negative is that it'd add a whole lot of necessary code to prevent errors due to things like setting the wrong type of data on a field which MUST be a string, but considering there's a limited field set for each scaler that doesn't seem extremely burdensome to me up front.

An alternative that might be worth considering is making those numeric fields look string-like to YAML by adding non-numeric characters.  Using the CPU scaler as an example, the threshold could be set to `i(50)` to suggest that an integer value of 50% is to be used.  For floats, `d(50.0)` could be used.  I believe this could be done without breaking backwards compatibility by leaving the existing parsing in place and checking the values for this type hinting first, then falling back to the plain ParseInt-style behavior.

I'd be open to trying to write up an implementation for either of these if maintainers would be willing consider acceptance of them, but don't want to start the work until it's clear that something like this could be accepted.

**Comment by JorTurFer** [comment]
Any opinion @kedacore/keda-core-contributors ?

**Comment by isugimpy** [comment]
As a strawman, I opened the PR above with a potential implementation of the alternative I mentioned above.  It seems like this should fairly elegantly solve the problem while completely preserving existing backwards compatibility, and without extensive changes to the codebase.  I'd be glad to go through other references to ParseInt and ParseFloat and replace them with this if the team is willing to accept the change.

**Comment by JorTurFer** [comment]
> After further thought, I think I have a rough idea on how this could be done.
> 
> The `metadata` field specifies
> 
> https://github.com/kedacore/keda/blob/7b9817325fd88f291af6a224899bd385cb86bb3c/config/crd/bases/keda.sh_scaledobjects.yaml#L268-L269
> 
> which could be changed to
> 
> ```
> additionalProperties:
>   oneOf:
>     - type: string
>     - type: integer
>     - type: number
> ```
> 
> And checks/conversions could be put into place on the various scalers for the known fields to type check them and convert as appropriate. That'd be a lot to touch, but seems like a really good starting point. A distinct negative is that it'd add a whole lot of necessary code to prevent errors due to things like setting the wrong type of data on a field which MUST be a string, but considering there's a limited field set for each scaler that doesn't seem extremely burdensome to me up front.
> 
> An alternative that might be worth considering is making those numeric fields look string-like to YAML by adding non-numeric characters. Using the CPU scaler as an example, the threshold could be set to `i(50)` to suggest that an integer value of 50% is to be used. For floats, `d(50.0)` could be used. I believe this could be done without breaking backwards compatibility by leaving the existing parsing in place and checking the values for this type hinting first, then falling back to the plain ParseInt-style behavior.
> 
> I'd be open to trying to write up an implementation for either of these if maintainers would be willing consider acceptance of them, but don't want to start the work until it's clear that something like this could be accepted.

Hi @isugimpy ,
I have tried to support more than one type as `additionalProperties` but I couldn't figure out how to do it with kubebuilder. 
Do you know how we could archive it? I mean, we use kubebuilder for CRD (and other manifests) generation during the build, so kubebuilder has to support it for supporting that feature in KEDA

**Comment by isugimpy** [comment]
I don't actually know offhand.  I haven't had to work significantly with kubebuilder, so I've never had to dig into that.  It likely is possible through some means though.

**Comment by JorTurFer** [comment]
I think that it's not possible right now :(
Let me review your PR in depth, my concern with it is the backward compatibility and I'd like to do some test

**Comment by isugimpy** [comment]
Need to bump this so it stays open.

**Comment by isugimpy** [comment]
Bumping again.  This reminds me that my PR probably needs love.

**Comment by isugimpy** [comment]
Continuing to bump, as the PR needs review and a label.
