### ISSUE TITLE
Is short polling intervals a problem?

### ISSUE THREAD

**Issue by karoldeland** [kedacore/keda#230]
The default polling interval is 30 seconds in scaledobjects. For low latency scenarios, we could update the default value to something shorter. May this setting cause performance problems at scale? With 30 seconds, we have a loooong cold start…

Thanks in advance for guidance.

**Comment by jeffhollan** [comment]
I believe polling interval really only impacts the time-to-activation (scaling from 0 to 1) but once scaled to one it's really up to the HPA to poll the custom metrics.  I'm not really sure if polling interval is still at play for publishing custom metrics though.  So I think the considerations for doing a more aggressive polling interval:
- If you have lots of `ScaledObjects` your KEDA controller will be doing lots of work to poll frequently. This may not be a big deal, but is something to remember all those loops.
- There may be some resource cost for polling.  For example if using something like Azure Queues there is a small charge when you check the queue length.  More or less negligible but at scale can add up

But for most I expect a shorter polling interval would be expected.

/cc @ahmelsayed @Aarthisk to clarify if polling interval impacts the custom metric aspect with HPA or if HPA has it's own algorithm for how often a scalar will return metrics?

**Comment by yaron2** [comment]
HPA is polling KEDA on its own interval set by the Kubernetes api server.

The polling interval will affect activation/deactivation.

**Comment by jeffhollan** [comment]
@anirudhgarg not sure how many FAQs you were thinking of adding but this may be good one 😸 

#170

**Comment by karoldeland** [comment]
Thanks a lot!
