### ISSUE TITLE
Cloudwatch scaler not working when there's no metrics

### ISSUE THREAD

**Issue by prajithp13** [kedacore/keda#2302]
### Report

The aws-cloudwatch metrics is not working as expected. When there's not metrics, the  endpoint /apis/external.metrics.k8s.io/v1beta1/namespaces/<namespace>/<metric_name> gets removed and showing some errors when describing both hpa and scaled object and also the desired value of hpa is not changing back to min.

hpa - warning
```
unable to get external metric <namespace>/<metric name>/&LabelSelector{MatchLabels:map[string]string{scaledobject.keda.sh/name: cleargstbackend-prod-consumer-swf,},MatchExpressions:[]LabelSelectorRequirement{},}: unable to fetch metrics from external metrics API: No matching metrics found for <metric name>
```
scaled object  - warning
``` 
 Warning  KEDAScalerFailed  10s (x3434 over 31h)  keda-operator  metric data not received
```

### Expected Behavior

If there's no metric returned by cloudwatch, then keda should set 0.0 by default.

### Actual Behavior

Currently its showing an error message. 
Warning  KEDAScalerFailed  10s (x3434 over 31h)  keda-operator  metric data not received

### Steps to Reproduce the Problem

1. Setup a cloudwatch scaler
2. stop feeding metrics to cloudwatch

### KEDA Version

2.4.0

### Kubernetes Version

1.19

### Platform

Amazon Web Services

### Scaler Details

aws-cloudwatch

### Anything else?

In k8s-cloudwatch-adapter, if there's no metrics it returns 0. 

https://github.com/amazon-archives/k8s-cloudwatch-adapter/blob/master/pkg/provider/provider_external.go#L38

**Comment by allupaku** [comment]
This pull request should fix this issue https://github.com/kedacore/keda/pull/2345
