### ISSUE TITLE
Find a way to monitor adoption and basic usage

### ISSUE THREAD

**Issue by jeffhollan** [kedacore/keda#231]
Not sure what flavor this will take (docker pulls, optional phone home? Etc) but would be good to have some pipeline to know how many people are using KEDA, and ideally which features, to help us plan and prioritize better. Realize this may not be possible given the open nature but wanted to at least have the conversation

**Comment by tomkerkhove** [comment]
Docker pull sounds feasible indeed, a phone home is more tricky as this can be "an issue" from a security perspective.

If the goal is to prioritize scalers then I think this will grow over time once the community starts to grow.
