### ISSUE TITLE
Support skipping cert validation (for self-signed certificates)

### ISSUE THREAD

**Issue by JorTurFer** [kedacore/keda#2310]
### Proposal

We have several services which could be self-hosted. When a service is self-hosted, the TLS certificate could be self-signed, explicitly in development/staging environments. It'd be nice if KEDA supported those scenarios, skipping the certificate validation.

Right now, KEDA already supports it for influx and selenium-grid using the parameter `unsafeSsl`, we could extend this support to other scalers.

- [x] https://github.com/kedacore/keda/issues/3821

**Comment by mknet3** [comment]
I can do this issue :)

**Comment by JorTurFer** [comment]
I close this as doesn't make sense after the support to custom CAs
