### ISSUE TITLE
Metrics Scaler: Improve Error Handling on not-ok response

### ISSUE THREAD

**Issue by schoki040** [kedacore/keda#2317]
### What's even going on?
The Metrics API Scaler is pretty quit on non-200 API responses. [(See this link for code)](https://github.com/kedacore/keda/blob/cbe929bcff6ee6d036283ad13423d6da083cf7e8/pkg/scalers/metrics_api_scaler.go#L214-L217)

At the moment we are using this for around 2000 scale targets and whenever something on API side goes wrong its a real hassle to even find out what the query was, when this is your response:
```log
2021-11-23T11:59:33.926Z    ERROR    metrics_api_scaler    Error when checking metric value: api returned 403    {"error": "api returned 403"} 
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).isScaledObjectActive
    /workspace/pkg/scaling/scale_handler.go:228
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).checkScalers
    /workspace/pkg/scaling/scale_handler.go:211
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).startScaleLoop
    /workspace/pkg/scaling/scale_handler.go:145
```

### Suggestion
Integrate the requested API endpoint and an optional response body into the scale error to get decent info on why the query didn't go through.

### Possible new log
```log
2021-11-23T11:59:33.926Z    ERROR    metrics_api_scaler    Error when checking metric value for /api/v1/files/on/server: api returned 403    {"error": "403 forbidden - cannot change into directory"} 
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).isScaledObjectActive
    /workspace/pkg/scaling/scale_handler.go:228
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).checkScalers
    /workspace/pkg/scaling/scale_handler.go:211
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).startScaleLoop
    /workspace/pkg/scaling/scale_handler.go:145
```

### Use-Case

* Improve debugging of big scaled systems
* No need to have access to logs of metric endpoint to debug

**Comment by zroubalik** [comment]
This seems like a fair request, are you willing to contribut this?

**Comment by schoki040** [comment]
I'd be happy to contribute, I'll look into the process and will link a PR

**Comment by ahmelsayed** [comment]
Also while you're at it, this defer https://github.com/kedacore/keda/blob/cbe929bcff6ee6d036283ad13423d6da083cf7e8/pkg/scalers/metrics_api_scaler.go#L219 should move above that `if r.StatusCode != http.StatusOK`

**Comment by zroubalik** [comment]
@schoki040 what is the status of this please?

**Comment by schoki040** [comment]
I was not yet able to make any changes on this. This improvement is nonetheless still dear to my heart. Please dont close.

**Comment by Friedrich42** [comment]
Hey. I created PR for this issue. Please review - https://github.com/kedacore/keda/pull/2739
