### ISSUE TITLE
[Scaler] Azure CosmosDB

### ISSUE THREAD

**Issue by jeffhollan** [kedacore/keda#232]
Scale on the Azure CosmosDB change feed.  Would require Go SDK support most likely, or work to make scalers extensible.

**Comment by jeffhollan** [comment]
Chatted with the CosmosDB team.  The Go SDK doesn't currently have support for the change feed, but they are willing to work with us and help write the logic that would be needed to check the leases collection and know how much remaining work is there in a Go variation of the code

**Comment by edrevo** [comment]
@jeffhollan, do you know if there's any update of this? I'd definitely be interested in a CosmosDB change-feed scaler

**Comment by lgmorand** [comment]
same here. customers are looking for it

**Comment by tomkerkhove** [comment]
Paging @jeffhollan  to see if we can implement this.

@lgmorand @edrevo What are the scenarios you are looking at? Just change-feed or scale on other metrics/scenarios as well?

**Comment by edrevo** [comment]
From my side, change feed is enough

**Comment by lgmorand** [comment]
I have two customers with cosmosdb as the output of databricks and functions in AKS to consume them so changefeed should be perfectly fitted

**Comment by tomkerkhove** [comment]
This should be feasible, but we need a Go SDK / REST API interface which is probably not available yet.

@jeffhollan  can you follow-up on this please? An alternative approach is to evaluate an external scaler which handles through .NET Core or so.

**Comment by bsstahl** [comment]
Would it be possible to get an update on this? I know it depends on other work outside of the scope of this project but it is also likely to become a blocking issue for me and my company very soon. Have we gotten an ETA on the Cosmos SDK work or REST API that is blocking this issue? Scaling based on the change feed is all I'd need at this point.

**Comment by tomkerkhove** [comment]
I'll try to get some info

**Comment by abhirockzz** [comment]
It *maybe* possible to implement this using a combination of External Scaler and [Change Feed Estimator](https://docs.microsoft.com/en-us/azure/cosmos-db/how-to-use-change-feed-estimator).

**Comment by tomkerkhove** [comment]
This is coming through an external scaler that you can find here: https://github.com/kedacore/keda-external-scaler-azure-cosmos-db

It is still being developed though.

**Comment by JatinSanghvi** [comment]
The external scaler package is available now: https://github.com/kedacore/keda-external-scaler-azure-cosmos-db/pkgs/container/keda-external-scaler-azure-cosmos-db. The associated README file has the setup instructions.

**Comment by tomkerkhove** [comment]
Closing as we have this through an external scaler: https://github.com/kedacore/external-scaler-azure-cosmos-db
