### ISSUE TITLE
[Scaler] Azure Functions Durable Orchestration and Activity

### ISSUE THREAD

**Issue by jeffhollan** [kedacore/keda#233]
Today I believe this leverages the [Durable Task Framwork](https://github.com/Azure/durabletask) SDK (in .NET) to assess if work is scheduled and how work needs to be done.

**Comment by tomkerkhove** [comment]
This is covered via https://github.com/kedacore/keda-scaler-durable-functions, do you want to keep this one open for another reason @jeffhollan ?

**Comment by tomkerkhove** [comment]
https://github.com/kedacore/keda-scaler-durable-functions is archieved but guidance is to use SQL backend for scaling.
