### ISSUE TITLE
azure pipelines scaler not working, using KEDA V2.4

### ISSUE THREAD

**Issue by SandipGorde-TomTom** [kedacore/keda#2334]
### Discussed in https://github.com/kedacore/keda/discussions/2332

<div type='discussions-op-text'>

<sup>Originally posted by **SandipGorde-TomTom** November 24, 2021</sup>
Hello,

I need a help in finding the exact problem as I do not see any errors or problems while running scaler for azure pipelines. However scaler simply do not work. Below are the more details.

1. Running EKS clsuter
2. deployed KEDA 2.4 version using helm and direct k8s file
3. deployed ado-agent k8s deployment with one agent(pod)
4. deployed scaledobject which deployed hpa 
5. run multiple jobs on the azure pipelines 

Expected behavior: Pipelines agents should scale based on the queue length
Actual behaviors:  pods are not scaling without any error

Using reference guide: https://keda.sh/blog/2021-05-27-azure-pipelines-scaler/

Below is the scaledobject 

`apiVersion: v1
kind: Secret
metadata:
  name: pipeline-auth
data:
  personalAccessToken: <PAT>
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: pipeline-trigger-auth
spec:
  secretTargetRef:
    - parameter: personalAccessToken
      name: pipeline-auth
      key: personalAccessToken
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: azure-pipelines-scaledobject
spec:
  scaleTargetRef:
    name: azdevops-deployment
  minReplicaCount: 1
  maxReplicaCount: 5 
  triggers:
  - type: azure-pipelines
    metadata:
      poolID: "1"
      organizationURLFromEnv: "AZP_URL"
    authenticationRef:
     name: pipeline-trigger-auth`
</div>

**Comment by tomkerkhove** [comment]
Closing as a discussion is already open
