### ISSUE TITLE
Provide more thorough logs for Azure Pipelines scaler

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda#2339]
### Proposal

Provide more thorough logs for Azure Pipelines to provide insights on the configuration and how our integration with Azure Pipelines is.

### Use-Case

Improve the troubleshooting of failures given we are a bit in the dark in a few past reports.

**Comment by tomkerkhove** [comment]
Things it should log if not already, the organization name and pool ID.

#2342 will handle error if pool does not exist

**Comment by JorTurFer** [comment]
I think this is solved since this other is solved (https://github.com/kedacore/keda/issues/2342). 
Now KEDA logs an explicit error in case of not existing poolID or poolName

**Comment by tomkerkhove** [comment]
Ok to close then?
