### ISSUE TITLE
HPA creation should fail or produce useful error logging on bad scaledobject spec

### ISSUE THREAD

**Issue by lee0c** [kedacore/keda#236]
Incorrect ScaledObject specs (such as a connection string value that can't be resolved as in the case of #146) create an HPA that doesn't use external metrics but instead falls back to default CPU metrics, & info-level logs don't reflect an error (just says that an HPA was created). This should at the very least create error logs, and potentially not create an HPA if a useful HPA can't be created.

**Comment by Aarthisk** [comment]
I will take this- I think a testconnection method in the scaler can check that the creds are valid before the HPA gets created so we don't monitor scaled objects with incorrect credentials.

**Comment by lee0c** [comment]
@Aarthisk afaik this is less an issue due to bad credentials, and more an issue with metadata that doesn't parse incorrectly. It happens when the ExternalMetric struct that would be passed to the HPA is poorly formed. I think all that is needed is better errors and error handling in scalers' creation & parseMetadata functions - happy to point out where I've seen this coming from previously (unfortunately don't have the time to just put in the fix for it in the first place).

**Comment by Aarthisk** [comment]
@lee0c Please go ahead and share where you have seen this.

**Comment by lee0c** [comment]
From what I've seen, it comes about when [the scaledObjectMetricSpecs set in the HPA](https://github.com/kedacore/keda/blob/master/pkg/handler/scale_handler.go#L151) are nonexistent, which happens when [no scalers are returned](https://github.com/kedacore/keda/blob/master/pkg/handler/scale_handler.go#L117) due to an error in scaler creation, likely metadata parsing. If scaler creation returns an error it is [logged at debug level](https://github.com/kedacore/keda/blob/master/pkg/handler/scale_handler.go#L498) but otherwise ignored, & there is no check to ensure the scaler list being returned to HPA creation is not empty.

From what I've looked at/worked on the scaler metadata parsing returns errors in the cases it should, so that part *should* be ok but I'm not sure.

**Comment by lee0c** [comment]
I last saw it when I failed to set a queue name in a scaled object spec, but theoretically any failure to include necessary metadata in a scaled object's trigger metadata should do it.

**Comment by Aarthisk** [comment]
Should be fixed in above PR.
