### ISSUE TITLE
Azure Event Hub scaler doesn't log anything if the blob container name is wrong

### ISSUE THREAD

**Issue by jrehnen** [kedacore/keda#2363]
While querying the scaling metric, if the scaler for Azure Event Hub cannot find the blob storage container the error message never gets logged.
Instead, the total amount of events in the hub is used as the value for the metric, whether they have already been handled or not.

This is due to the codeblock starting from the line in this link:
https://github.com/kedacore/keda/blob/7b9817325fd88f291af6a224899bd385cb86bb3c/pkg/scalers/azure_eventhub_scaler.go#L168

Due to this it is currently incredibly difficult to locate an error caused by a wrong blob storage container name.

**Comment by JorTurFer** [comment]
Hi @jrehnen 
Nice catch!, improvements in troubleshooting are always welcomed. 
Thanks for noticing it ❤️ 
are you willing to contribute?

**Comment by tomkerkhove** [comment]
I'm getting somebody to fix this, assigning to myself for now

**Comment by SushmithaVReddy** [comment]
We are looking at this issue

**Comment by tomkerkhove** [comment]
Thank you!
