### ISSUE TITLE
Graphite scaler is returning the earliest datapoint of a query, not the latest.

### ISSUE THREAD

**Issue by bpinske** [kedacore/keda#2366]
### Expected Behavior

Graphite's scaler acts on the most recent data available from a given query.

### Actual Behavior

The scaler will act on the most outdated value returned by a query for a given time range.

### Steps to Reproduce the Problem

1. Define a scaler definition with a QueryTime of 1 hour
2. Observe scaling behaviours act on hour-old data.

### Logs from KEDA operator

```
example
```

### KEDA Version

2.5.0

### Anything else?

Here you can see the graphite server response returns values in order of oldest to latest. With the final element of the response array being the most up-to-date timestamp. Graphite's scaler should be acting on the final element of the response array, not the first.

* https://graphite-api.readthedocs.io/en/latest/api.html#json
* https://github.com/kedacore/keda/blob/main/pkg/scalers/graphite_scaler.go#L197

_No response_

**Comment by zroubalik** [comment]
@bpinske do you think, that there might be some usecase where keeping the current behavior (oldest) makes sense?

**Comment by bpinske** [comment]
It seems very unlikely to me there is any legitimate use in allowing people to intentionally use out of date data. 
Prometheus's scaler does not have any equivalent back-in-time functionality either.
