### ISSUE TITLE
Kafka scaler should concurrently query brokers and partitions for their message offsets

### ISSUE THREAD

**Issue by bpinske** [kedacore/keda#2377]
### Proposal

Currently, the kafka scaler serially queries kafka brokers for partitions one at a time. For very large topics with many hundreds of partitions, this can be quite slow. During this slow query, the controller-manager hpa loop blocks preventing other HPA actions from taking place.

This has previously been optimized with only querying each broker once for the entire list of all partitions held by the broker, but ultimately this process remains serial.

All brokers should be concurrently queried to minimize time to calculate the total number of unprocessed messages in a topic.

### Use-Case

As of now, the kafka scaler is non-performant when multiple kafka-based scaledObjects are querying large topics.

This change would make the kafka scaler usable.

### Anything else?

![image](https://user-images.githubusercontent.com/32846221/144486782-ac2a0a31-d95b-491d-9cc3-8c826f1a0d1a.png)

**Comment by VerstraeteBert** [comment]
Hey @bpinske 

I've tried my [hand at implementing this](https://github.com/VerstraeteBert/keda/commit/e6073130304758ea5f87abf3f72f4f8bccf815eb). Haven't had the chance to properly test this myself, feel free to try it out :-). Note that I'm quite a golang novice still, especially its concurrency patterns.
