### ISSUE TITLE
Unify configuration for logging

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda#238]
As of today, you can configure the logging in the Helm chart via `glogLevel` & `logLevel`.

We should try to unify them to make it easier to configure the runtime.

This was initially found in #222

**Comment by jeffhollan** [comment]
I believe these are two separate values I'm not sure if we should combine but should at least document.  `glogLevel` determines how many of the Kubernetes system logs get surfaced (when we first had KEDA your logs would be muddied with a bunch of "saw create of deployment `foo`" that wasn't really relevant to KEDA.  `logLevel` is about exposing the level of logs from the KEDA controller itself.

**Comment by tomkerkhove** [comment]
If that is the case then I would suggest improving the docs a bit on this as it's not clear, at least to me, what they were for.

Thanks for letting me know!

**Comment by tomkerkhove** [comment]
Actually, #222 is still open so if we could clarify this a bit more then I can update it in the Helm chart already.

**Comment by zroubalik** [comment]
loggin should be already documented
