### ISSUE TITLE
Keda .NEt core and RabbitMQ

### ISSUE THREAD

**Issue by VenkateshSrini** [kedacore/keda#239]
Hi All,

This there a sample application that run on Keda written in .NET core and RabbitMQ.

**Comment by tomkerkhove** [comment]
We don't have one as of today, you can find all samples here: https://github.com/kedacore

That said, we have one for Go but the configuration part is the same.

**Comment by GokGokalp** [comment]
I can prepare a sample for .NET Core and RabbitMQ.

**Comment by VenkateshSrini** [comment]
@GokGokalp ,
Yes that would be of immense help. Also when you are containerizing, please see if it can access a RabbitMQ cluster that runs on the local machine bit not as a separate docker. Also if you can see of this runs on KEDA then it will be a good starting point for us

**Comment by GokGokalp** [comment]
> @GokGokalp ,
> Yes that would be of immense help. Also when you are containerizing, please see if it can access a RabbitMQ cluster that runs on the local machine bit not as a separate docker. Also if you can see of this runs on KEDA then it will be a good starting point for us

I prepared a sample project with RabbitMQ .NET Core client - https://github.com/GokGokalp/sample-netcore-keda-rabbitmq

I also wrote an article about it: https://www.gokhan-gokalp.com/en/kubernetes-based-event-driven-autoscaling-with-keda-rabbitmq-and-net-core/

**Comment by NileshGule** [comment]
@GokGokalp Your example is great. I like the usage of MetroBus package which provides higher level API to interact with RabbitMQ. I built a similar application with .Net Core and RabbitMQ client. The source code is available at https://github.com/NileshGule/pd-tech-fest-2019

**Comment by NileshGule** [comment]
@jeffhollan I would like to add the repo https://github.com/NileshGule/pd-tech-fest-2019 as sample code for .Net Core consumer for RabbitMQ. What are the steps to include this in the list of samples & blog posts?

**Comment by jeffhollan** [comment]
Thanks @NileshGule - this looks great.  One option is we let the repo continue to live where it is today and we link to it in our README and Wiki.  The other is we move the content over to the Kedacore org.  I'm really open to either. I imagine eventually we may move to a single repo called "KEDA Samples" that has samples for lots of stuff, but in the meantime while we still have only a handful of samples I'm ok having a repo for each.

**Comment by NileshGule** [comment]
@jeffhollan Thanks for quick response. Lets keep the repo where it is currently. Please help to add the link to Wiki and README. If you can add me to the contributors list for KEDA, I can do it myself.
I am also working on the Kafka sample with .Net core. Will share the link to that soon.

**Comment by tomkerkhove** [comment]
Closing as we now have a sample listed on https://github.com/kedacore/samples#rabbitmq
