### ISSUE TITLE
Provide scaler for NATS Jetstream

### ISSUE THREAD

**Issue by shaunc** [kedacore/keda#2391]
### Proposal

Currently keda supports NATS streaming. However, [NATS  Streaming has been deprecated in favor of NATS Jetstream](https://docs.nats.io/reference/faq#jetstream-and-nats-streaming). NATS is simpler to run in-cluster than Kafka, and jetstream scales well. I hope that Keda will support it?

### Use-Case

I hope to use in [conjunction with fission](https://github.com/fission/fission/issues/2062)

**Comment by JorTurFer** [comment]
Hi @shaunc 
Thanks for notify this. I think that KEDA should support NATS Jetstream being this the successor of NATS Streaming.
Are you willing to contribute with this?

**Comment by shaunc** [comment]
Thank you, @JorTurFer!

I'm not familiar with the codebase, and have many things to do. That said, getting this working would simplify a number of other things (like having to maintain a Kafka cluster). If you could give some pointers/a checklist, I can investigate, and depending on how much work there is make some contributions if not the full feature.

**Comment by JorTurFer** [comment]
hi @shaunc ,
As I understand this, it's basically another new scaler (because STAN is deprecated but still be there). This means that [this guide](https://github.com/kedacore/keda/blob/main/CREATE-NEW-SCALER.md) could be useful.
Probably the majority of the code will be similar to [already existing STAN scaler](https://github.com/kedacore/keda/blob/main/pkg/scalers/stan_scaler.go), also from unit/e2e tests

**Comment by shaunc** [comment]
Very good! ... (currently very busy :( )....

**Comment by xgenvn** [comment]
@goku321 do you have a plan or task board, and repository to contribute on? I think there are some people having the same interest in this.

**Comment by goku321** [comment]
Hi @xgenvn I didn't plan anything yet. I believe it will be like any other scalers that we already have. I will start on this today/tomorrow and will try to keep you in loop.

**Comment by xgenvn** [comment]
@goku321 I did a check on the scalers of STAN and a bit on the JetStream metrics endpoint. It seems there are many differences with `/jsz` endpoint compared to `/channelsz`. If we can conclude the `IsActive` implementation which currently has `hasPendingMessage`, the implementation should be straight-forward.

**Comment by leopoldodonnell** [comment]
@xgenvn I'm interested in being able to scale using JetStream metrics as well. Is this something that is being considered, if so what is the timeframe?

Re the /jsz endpoint, which specific Nats server issue were you referencing. We might be willing to do some work here.

**Comment by goku321** [comment]
@leopoldodonnell I've started working on the scaler. Will try my best to conclude it in a couple of weeks

**Comment by leopoldodonnell** [comment]
@goku321 No pressure (really) Just checking to see if you were able to make any progress towards a JetStream scaler?

**Comment by goku321** [comment]
@leopoldodonnell @xgenvn Got delayed due to some pre-commit issues

Here's the commit: https://github.com/goku321/keda/commit/126130b9e228cc84576047fcfe03906a3db3ce1d (Didn't test it yet)

I'm not sure how accurate is `getMaxMsgLag`

Would really appreciate your input and help 🙂

**Comment by leopoldodonnell** [comment]
@goku321 I will build it and have a look - its not my top priority, but I'd like to see this working and really appreciate that someone is giving it a try.

**Comment by gcameo** [comment]
Any updates?

**Comment by tomkerkhove** [comment]
Let's see where @goku321 is at and if he wants to contribute it.

**Comment by goku321** [comment]
@gcameo @tomkerkhove I still want to contribute. I had already started with the tests couple of weeks back but a bit caught up with production deployments these days. Will try to wrap up in the coming weekends or so. Appreciate your patience :)

**Comment by JorTurFer** [comment]
hey @goku321 
Any update? we aim to do a release next week

**Comment by goku321** [comment]
Hi @JorTurFer In the process of testing the scaler. Will try to create a PR by today.

**Comment by goku321** [comment]
Hi all. Can anyone from this thread with JetStream experience please review this scaler (https://github.com/kedacore/keda/pull/3468)? Would really appreciate the help :)
