### ISSUE TITLE
Provide workflow to deploy KEDA on various Kubernetes versions

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda#2392]
Provide workflow to deploy KEDA on various Kubernetes versions to ensure we support them correctly.

Relates to https://github.com/kedacore/charts/pull/213#issuecomment-988085409

**Comment by JorTurFer** [comment]
I think this is already solved with [the smoke tests](https://github.com/kedacore/keda/blob/main/.github/workflows/template-versions-smoke-tests.yml) we execute on several k8s versions.
Currently, we execute them on main and every night.
Can I close this @tomkerkhove ?

**Comment by tomkerkhove** [comment]
Let's close this for now indeed
