### ISSUE TITLE
Create OpenAPI3 validation schema for ScaledObject

### ISSUE THREAD

**Issue by ahmelsayed** [kedacore/keda#24]

**Comment by jeffhollan** [comment]
What's the status / urgency of this? Wondering if we should add to the "current" milestone or just leave for now

**Comment by ahmelsayed** [comment]
sorry I know I missed the standup. Is current milestone 2 weeks from now?

It'll let the server validate the scaled object so you can't submit a string for `pollingInterval` or a scaledObject without a deploymentName for example. It would certainly be nice to have.

**Comment by jeffhollan** [comment]
No set timeline but thinking is work that will finish in the next two week. So yeah I guess so. If it’s an item you intend to close in next 2 weeks we can set to that milestone. If further out I’ve been setting to Triaged with a priority tag (what you said above sounds like a strong P1)
