### ISSUE TITLE
Provide scaler for Dynatrace metrics

### ISSUE THREAD

**Issue by davidlm228** [kedacore/keda#2411]
### Proposal

Provide k8s autoscaling based on Dynatrace Metrics

### Scaler Source

Pods

### Scaling Mechanics

https://www.dynatrace.com/support/help/dynatrace-api/environment-api/metric-v2/get-all-metrics

### Authentication Source

https://www.dynatrace.com/support/help/dynatrace-api/basics/dynatrace-api-authentication

**Comment by tomkerkhove** [comment]
Thanks! Are you willing to contribute this?

**Comment by davidlm228** [comment]
Yes

**Comment by tomkerkhove** [comment]
Awesome, thank you @davidlm228!

**Comment by cyrilico** [comment]
@tomkerkhove do you know if there is anyone actively looking at this? might have a go at it if not

**Comment by JorTurFer** [comment]
There isn't anyone working on this, and we can request a dynatrace account for e2e tests, so there isn't any blocker if you are willing to work on this 😄

**Comment by cyrilico** [comment]
@JorTurFer sounds interesting, I'm willing to give it a shot 🙏

**Comment by JorTurFer** [comment]
so, the stage is yours xD

**Comment by cyrilico** [comment]
@JorTurFer I believe I have a proposal nearly ready, how to proceed with regards to that account configuration for e2e tests?

**Comment by JorTurFer** [comment]
We have the account ready, I just need to know which secrets you need and on which envs vars. 
For example, you can see how Datadog e2e test work: https://github.com/kedacore/keda/blob/main/tests/scalers/datadog/datadog_test.go#L252-L254
Once I know the envs that you need, I'll generate the secrets and you can just read them from env vars (they are automatically loaded during CI)

**Comment by cyrilico** [comment]
Thanks @JorTurFer 🙏 I know I need these:
- The host (`DYNATRACE_HOST`), or, in alternative, the environment ID from which the host URL can be built (`DYNATRACE_ENV_ID`)
- A token with `metrics.ingest` scope (`DYNATRACE_METRICS_INGEST_TOKEN`)
- A token with `metrics.read` scope (`DYNATRACE_METRICS_READ_TOKEN`)

If you prefer to merge both scopes into one token (`DYNATRACE_METRICS_TOKEN`), that should work fine as well. I believe this is all, but if there's anything missing I'll let you know eventually

**Comment by JorTurFer** [comment]
I've created them:
- DYNATRACE_HOST: https://IDENTIFIER.apps.dynatrace.com/
- DYNATRACE_METRICS_TOKEN: a token with metric scopes (ingest, read, write)

**Comment by cyrilico** [comment]
Thanks @JorTurFer ; I believe to use the API the host must be in the format `https://<IDENTIFIER>.live.dynatrace.com` (at least that's what I need to use with another installation I have access to), if you could make that small change 🙏

**Comment by JorTurFer** [comment]
> Thanks @JorTurFer ; I believe to use the API the host must be in the format `https://<IDENTIFIER>.live.dynatrace.com` (at least that's what I need to use with another installation I have access to), if you could make that small change 🙏

Do you mean without the ending slash? np, let me remove it xD

**Comment by cyrilico** [comment]
> > Thanks @JorTurFer ; I believe to use the API the host must be in the format `https://<IDENTIFIER>.live.dynatrace.com` (at least that's what I need to use with another installation I have access to), if you could make that small change 🙏
> 
> Do you mean without the ending slash? np, let me remove it xD

No, I mean the subdomain `.live` instead of `.apps` in the API URL
