### ISSUE TITLE
Clarification for deploymentName

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda#242]
I've noticed that `deploymentName` needs to be labeled on the `ScaledObject` as well and I think this is what the following docs are referring to:

> The name of the deployment this scaledObject is for. [...] Make sure to include the deployment name in the label as well, otherwise the metrics provider will not be able to query the metrics for the scaled object and 1-n scale will be broken.

https://github.com/kedacore/keda/wiki/ScaledObject-spec#details

So what I'm understanding from this is that we **have** to include it in the label because otherwise you cannot access the data on the `ScaledObject` itself, is that correct?

In order to clarify this I would suggest the following edit:
```diff
- Make sure to include the deployment name in the label as well, otherwise the metrics provider will not be able to query the metrics for the scaled object and 1-n scale will be broken.
+ Make sure to include the deployment name in the label as well of the ScaledObject, otherwise the metrics provider will not be able to query the metrics for the scaled object and 1-n scale will be broken.
```

Because my initial understanding was that the label had to be on my deployment, not the scaled object and only got it when I saw the following error:

> time="2019-05-31T14:47:44Z" level=info msg="Updated HPA with namespace default and name keda-hpa-order-processor"
> E0531 14:48:42.757909       1 status.go:64] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"Exactly one scaled object should match label deploymentName=order-processor"}

**Comment by ahmelsayed** [comment]
I personally don't like the duplication of the deploymentName in the scaledObject. Since the label is required for HPA to work, I wonder if we can remove it from the scaleTargetRef.

**Comment by tomkerkhove** [comment]
Would be great to remove the duplication idd!

From a user perspective I'd prefer to keep the scaleTargetRef and delete the label, but that is probably not possible given the statement above?

**Comment by Aarthisk** [comment]
Ahmed is right, we need it in the label as the External metrics adapter gets limited information (not the deployment name) and we need a means of finding the scaled object. We can auto populate the label based on the ScaleTargetRef  to avoid user-duplication?

**Comment by jeffhollan** [comment]
Sounds good.  Is there consensus then to remove `scaledObjectRef` and just derive all info from the `deploymentName` label?

**Comment by yaron2** [comment]
No. ScaleObjectRef also contains ```containerName``` which tells you which container in what might be a multi container pod is the one that needs scaling.

**Comment by tomkerkhove** [comment]
I like the idea of sticking with scaledObjectRef and automatically applying the labels ourself. Can we do that?

**Comment by tomkerkhove** [comment]
Relates to https://github.com/kedacore/keda/issues/545 which talks about the removal part.

Closing this one.
