### ISSUE TITLE
Unable to connect to Azure Service Bus namespace via secret

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda#243]
While working on the .NET Core sample for Azure Service Bus I've been struggling to wire up KEDA to my Service Bus Namespace.

When using a `secretKeyRef` ([code](https://github.com/tomkerkhove/sample-dotnet-worker-servicebus-queue/blob/master/deploy/deploy-queue-processor.yaml#L21)) I received the following error:
> time="2019-05-31T14:05:28Z" level=error msg="error error code: 401, Details: claim is empty. TrackingId:a7faaf8c-5665-4aa5-9837-c3e9e299bd50_G11, SystemTracker:keda-sandbox.servicebus.windows.net:orders, Timestamp:2019-05-31T14:05:35"
> time="2019-05-31T14:05:28Z" level=error msg="Error getting scale decision: error code: 401, Details: claim is empty. TrackingId:a7faaf8c-5665-4aa5-9837-c3e9e299bd50_G11, SystemTracker:keda-sandbox.servicebus.windows.net:orders, Timestamp:2019-05-31T14:05:35"

However, it means that somehow it was able to read the secret but not allowed in given it's able to resolve the DNS name.

The secret resolved to the following connection string _(will delete resource when resolved)_:
`Endpoint=sb://keda-sandbox.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=qMCFMXbJeXzjWl5mniXtpXZo0Py6AdpF2L4m8+haapw=`

This works when passed directly as an environment variable.

Am I doing something wrong or is this a bug?

_Full template can be found [here](https://github.com/tomkerkhove/sample-dotnet-worker-servicebus-queue/blob/5487572f7e96cc21f5648c6f8a3df0df843e68d6/deploy/deploy-queue-processor.yaml)_

**Comment by jeffhollan** [comment]
I got this when I used the NAMESPACE key(like you have here). I had to generate a key on the queue directly and use that key.  I opened a bug to track this #215

**Comment by tomkerkhove** [comment]
I'll give that a try but doesn't really explain why it works with a plain text environment variable 🤔

**Comment by jeffhollan** [comment]
References to things like connection strings will check both secrets and environment variables for the target container to resolve the secret. The one that won’t work is putting connection string directly in metadata

**Comment by tomkerkhove** [comment]
> References to things like connection strings will check both secrets and environment variables for the target container to resolve the secret. The one that won’t work is putting connection string directly in metadata

That's right, I was more referring to passing the raw connection string on the environment variable on the container, not ScaledObject configuration.

Anyhow there is too much overlap with #215 so I'll close this one. Thanks.
