### ISSUE TITLE
Google Cloud Pubsub Scaler factoring number of workers into scaling

### ISSUE THREAD

**Issue by TrevinTeacutter** [kedacore/keda#2455]
### Proposal

I would like to see the Pubsub scaler adopt the ability to do one of two things:
* Take the number of workers deployed into account when scaling. [Amazon has a decent article to explain the reasoning](https://docs.aws.amazon.com/autoscaling/ec2/userguide/as-using-sqs-queue.html). This means allowing a target message count per worker.
* The above is really trying to get at the rate of growth within the backlog, scaling up when it is growing, and scaling down when it is shrinking. This also allows you to scale up ahead of time (since it grows a while before it hits a threshold in the case of the acceptable backlog per worker) however the mechanics of this are still a bit hazy to me since the rate of growth (negative or positive) ideally would dictate how fast and/or how much you scale. However, this requires the autoscaler to know the rate of growth during the last scale calculation poll.

All things in consideration, the former seems the easiest to rationalize and work around even if the latter seems like it would have some benefit at some point.

### Use-Case

Right now we are running into a situation where we are consistently flapping due to constantly fluctuating volumes of data. Unfortunately, this causes issues with high cardinality in our Prometheus metrics because pods constantly flap (which in turn creates new time series'). I'd like to see scaling be smoothed between how far it scales up and down. Adjusting the time to scale up and down definitely helps but it seems like any queue-based autoscaling should take into account a target backlog per worker.

### Anything else?

This would apply to more than just Pubsub but I haven't actually looked at any of the other scalers that work on queues to see if this is applicable to more.

**Comment by zroubalik** [comment]
Interesting, are you willing to contribute this?

**Comment by TrevinTeacutter** [comment]
I or somebody from the team I work with can make an attempt at this.
