### ISSUE TITLE
Provide an PredicetKube scaler 

### ISSUE THREAD

**Issue by daniel-yavorovich** [kedacore/keda#2458]
### Proposal

[PredictKube](https://predictkube.com/) is a proactive KEDA scaler made by [Dysnix](http://dysnix.com/) for Kubernetes projects

### Scaler Source

Prometheus + PredictKube AI API

### Scaling Mechanics

It's based on an AI model trained on cloud traffic data: public, business, and custom metrics. It helps to deal with overprovisioning by predicting the traffic trend and timely resource balancing. PredictKube is easy to install in your environment and its AI model demands only 2 weeks data about your traffic to start predicting efficiently.

### Authentication Source

API key

### Anything else?

We'd like to develop this project continuously, and thus, we encourage you to leave us your feedback. We're eager to hear your thoughts about PredictKube and its model efficiency. 

Related PR: https://github.com/kedacore/keda/pull/2418

**Comment by tomkerkhove** [comment]
Relates to #197 & #2401

**Comment by tomkerkhove** [comment]
Can you share some more information related to the billing model & legal implications of PredictKube? For example, will you train the AI model based on the metrics that you use for KEDA?

**Comment by tomkerkhove** [comment]
Also, our [community standup](https://keda.sh/community/) is next week on Tuesday. Would you be able to join it and share more on this scaler?

**Comment by daniel-yavorovich** [comment]
> Can you share some more information related to the billing model & legal implications of PredictKube? For example, will you train the AI model based on the metrics that you use for KEDA?

Hi Tom. Thank you for your questions. Regarding the legal issues of PredictKube, we can assure that:
Any personal data that we are asking for is used only for sending the API key and contacting our representatives to answer the questions about PredictKube. We may ask for the name, email address, company name, phone number—so people choose a way to communicate with us that is convenient for them.
We store log files and collect data about the performance of a PredictKube in a certain environment. But we do not monitor or log data from customer servers when they use PredictKube, as we may collect only statuses and logs of the PredictKube itself. And also we have access to typical web analytics of PredictKube website including the type of browser, access sessions, pages views, IP address, and the page visited before entering our website. 
We track the metrics of KEDA on the basis of a third-party service provider.
We’re sorry for publishing Cookies and Privacy Policies earlier. They’ll be published soon, and I’ll add a link here for everyone to review it.
Here’s an answer about the billing model. Free access to the PredictKube will be available on a permanent basis, and we’ll constantly pay attention to updating and developing this tool. Thus, users will be able to make predictions based on a generic AI model. Later on, we plan to add a Business paid plan for those who want to train their own model on specific data. But this part of the service is only in development for now.

**Comment by daniel-yavorovich** [comment]
> Also, our [community standup](https://keda.sh/community/) is next week on Tuesday. Would you be able to join it and share more on this scaler?

we will be happy to join you, tell you about PredictKube, and answer all your questions!
