### ISSUE TITLE
Support for autoscaling/v2-based HorizontalPodAutoscaler on Kubernetes v1.23+

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda#2462]
### Proposal

HPA has graduated to GA and we should use `autoscaling/v2` for all the HPAs that we create on Kubernetes v1.23+.

https://kubernetes.io/blog/2021/12/07/kubernetes-1-23-release-announcement/#horizontalpodautoscaler-v2-graduates-to-ga

### Use-Case

Provide alignment with Kubernetes upstream.

**Comment by JorTurFer** [comment]
In this case, what approach are we going to follow? Supporting both depending on the cluster?

**Comment by tomkerkhove** [comment]
Based on the Kubernetes version it is installed on I'd try to use the latest

**Comment by tomkerkhove** [comment]
We should plan for this as `autoscaling/v2beta1` for `HorizontalPodAutoscaler` will be removed in Kubernetes 1.25 and `autoscaling/v2beta2` in Kubernetes 1.26.

https://kubernetes.io/blog/2022/04/07/upcoming-changes-in-kubernetes-1-24/#looking-ahead

**Comment by beingashwin** [comment]
Hi,
can someone please point me to a updated helm chart which i can refer to ?
Post upgrading aks to v1.25.6 i am facing issues . Argocd is pointing to use v2 for HPA and i tried that n yet am getting issues probably the syntax of helm chart has changed in some way..using a {if} block in metrics is not supported or changed

**Comment by beingashwin** [comment]
well i jusr want the updated schema...i thought i can get a updated schema for V2

**Comment by JorTurFer** [comment]
> want the updated schema

What do you mean?  autoscaling/v2 schema? I don't get your question, sorry

**Comment by beingashwin** [comment]
yes i mean that ...its probably working now..though the memory is not correctly getting fetched by metrics need to check on that...argocd is syncing every 5 secs due to autoscaling.... thanks anyway

**Comment by JorTurFer** [comment]
> yes i mean that ...its probably working now..though the memory is not correctly getting fetched by metrics need to check on that...argocd is syncing every 5 secs due to autoscaling.... thanks anyway

I still don't get you, sorry. What problem are you seeing? Could you describe it?

**Comment by beingashwin** [comment]
@JorTurFer well sure let me try
So the issue is we have argocd deployed on k8s cluster and when i configure hpa for cpu and memory metrics argocd every 5 sec tries to sync 
only with cpu it seems to work fine as the avg utilisation is well below limit
I am assuming the utilisation is making it constantly sync and doesn't allow enough time for hpa to be in synced status

**Comment by JorTurFer** [comment]
> So the issue is we have argocd deployed on k8s cluster and when i configure hpa for cpu and memory metrics argocd every 5 sec tries to sync

Do you mean an ScaledObject with CPU/Memroy trigger or just an HPA directly?

We also use ArgoCD and I haven't seen this behavior, could you share your ScaledObject to replicate it in my local?

**Comment by beingashwin** [comment]
The argocd version is 2.7 aks is 1.25.6 and i have used the below manifest file

{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: example-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: example-deployment
  minReplicas: 2
  maxReplicas: 5
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
    scaleUp:
      stabilizationWindowSeconds: 300
    {{- if .Values.autoscaling.metricInterval }}
    periodicity:
      intervalSeconds: 600
    {{- end }}
  metrics:
  {{- if .Values.autoscaling.targetCPUUtilizationPercentage }}
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.autoscaling.targetCPUUtilizationPercentage }}
  {{- end }}
  {{- if .Values.autoscaling.targetMemoryUtilizationPercentage }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.autoscaling.targetMemoryUtilizationPercentage }}
  {{- end }}
{{- end }}

and in the values yaml file provided the below value 
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
  metricInterval: 300

**Comment by JorTurFer** [comment]
BTW, what is this for?
![image](https://github.com/kedacore/keda/assets/36899226/b7704a54-7885-4146-83e7-4e35fe895528)

I have checked the HPA spec and I haven't found that poperty xD

**Comment by JorTurFer** [comment]
> periodicity is described as something which makes HPA wait before checking metrics

Do you have any link about that? I thought that the HPA Controller has a fixed period :) 

> did you try on your local with both cpu and memory?

No, we use cpu + prometheus or cpu + nats

**Comment by JorTurFer** [comment]
Hi,
NATS it's a message streaming stuff for queues, my ScaledObjects use CPU and NATS as triggers, so my HPA uses them. I use ArgoCD to deploy the applications and no, I don't see that problem that you are refering. 

If you have autosync every 5 seconds, maybe there is something modifying your workload automatically and ArgoCD is trying to reconcile it but IDK what can be as the only manifest that you have sent is for an HPA and KEDA doesn't accept HPAs (so I'm not sure how is your problem related with this issue or with KEDA, that's the thing that I'm trying to figure out 😄 )

I'd suggest disabling the autosync for a while and check which differences are detected by ArgoCD. I mean, if you don't autosync the `Application` every 5 seconds and there are mismatches between real status and ArgoCD desired status, you will see the differences and then, you will know which resources are triggering the sync all the time

**Comment by beingashwin** [comment]
ok thanks for the hint..have a good day
