### ISSUE TITLE
Stabilize tooling around `protoc-gen-go` 

### ISSUE THREAD

**Issue by zroubalik** [kedacore/keda#2467]
### Discussed in https://github.com/kedacore/keda/discussions/2461

<div type='discussions-op-text'>

<sup>Originally posted by **bretagne-peiqi** January 11, 2022</sup>
Hi， I need to know protoc and protoc-gen-go version for externalscaler pb.go file generation.

I used version 3.19.2 but generated different file </div>

**Comment by JorTurFer** [comment]
I close this because it's already done by https://github.com/kedacore/keda/pull/3618
