### ISSUE TITLE
version 2.5.0,  create hpa v1 version;  expected to create hpa v2betav2 version  

### ISSUE THREAD

**Issue by bretagne-peiqi** [kedacore/keda#2473]
### Expected Behavior

expect to create a hpa " keda-hpa-*** "  with Apiversion: v2betav2 

### Actual Behavior

hpa " keda-hpa-*** "  with Apiversion: v1

### Steps to Reproduce the Problem

1. using ScaleObject： targetRef: deployment 
2.create
3.

### Logs from KEDA operator

```
example
```

### KEDA Version

2.5.0

### Kubernetes Version

1.18

### Platform

Alibaba Cloud

### Scaler Details

promethues

**Comment by tomkerkhove** [comment]
Hi, can you provide some guidance on reproducing this please?

Also, why is this a bug? Because you don't have v1 given you run Kubernetes v1.18? How did you install KEDA?

**Comment by bretagne-peiqi** [comment]
It's alicloud k8s version related, not a bug.

**Comment by tomkerkhove** [comment]
Ok, thanks for letting us know!
