### ISSUE TITLE
Metrics server suddenly stoped getting metrics from rabbitmq

### ISSUE THREAD

**Issue by alexbanditos** [kedacore/keda#2476]
### Report

Without known reason keda metrics server started getting errors  for all auth triggers  -

E0111 20:51:14.833101       1 scale_resolvers.go:164] keda_metrics_adapter/scalehandler "msg"="Error getting triggerAuth" "error"="context canceled" "name"="service-hpa-rmq" "namespace"="default" "type"="ScaledObject" "triggerAuthRef.Name"="prod-something-rmq"
E0111 20:51:14.845428       1 provider.go:124] keda_metrics_adapter/provider "msg"="error getting metric for scaler" "error"="error parsing rabbitmq metadata: no host setting given"  "scaledObject.Name"="service-rmq" "scaledObject.Namespace"="default" "scaler"={}

we are using TriggerAuthentication with vault , no issues with vault cluster
the trigger and the scaledobject are in the same ns

trigger:

apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: prod-something-rmq
spec:
  hashiCorpVault:
    address: https://vault.cluster.com
    authentication: kubernetes
    role: keda-operator
    mount: 'kubernetes/prod-cluster/'
    credential:
      serviceAccount: '/var/run/secrets/kubernetes.io/serviceaccount/token'
    secrets:
    - parameter: host
      key: host
      path: "secrets/data/infra/keda/prod-something-rmq"

Only after I delete the metrics server pod and it recreated scaling started working. 

### Expected Behavior

Metrics server able to monitor rabbitmq queues

### Actual Behavior

keda in not scaling hpa based on rmq

### Steps to Reproduce the Problem

1. create TriggerAuthentication with vault auth (external vault)
2. create scaledobject based on rabbit queue
3. wait for metrics server send errors.

### Logs from KEDA operator

error | Exception (504) Reason: "channel/connection is not open"
-- | --
level | error
logger | rabbitmq_scaler
stacktrace | github.com/kedacore/keda/v2/pkg/scaling/cache.(*ScalersCache).IsScaledObjectActive 	/workspace/pkg/scaling/cache/scalers_cache.go:89 github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).checkScalers 	/workspace/pkg/scaling/scale_handler.go:261 github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).startScaleLoop 	/workspace/pkg/scaling/scale_handler.go:146
ts | 1641934785.0178342
}

### KEDA Version

2.5.0

### Kubernetes Version

1.18

### Platform

Amazon Web Services

### Scaler Details

rabbitmq

**Comment by JorTurFer** [comment]
Hi @alexbanditos 
Could you share more logs please?

**Comment by alexbanditos** [comment]
@JorTurFer
from metrics server:
* HH:mm:ss.SSSSSS       1 provider.go:124] keda_metrics_adapter/provider "msg"="error getting metric for scaler" "error"="error parsing rabbitmq metadata: no host setting given"  "scaledObject.Name"="*" "scaledObject.Namespace"="lusha" "scaler"={}
 1 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"No matching metrics found for *"}: No matching metrics found for *
* HH:mm:ss.SSSSSS       1 scale_resolvers.go:164] keda_metrics_adapter/scalehandler "msg"="Error getting triggerAuth" "error"="context canceled" "name"="*" "namespace"="lusha" "type"="ScaledObject" "triggerAuthRef.Name"="prod-something-rmq"

from keda operator:


{
--
error | Exception (504) Reason: "channel/connection is not open"
level | error
logger | rabbitmq_scaler
stacktrace | github.com/kedacore/keda/v2/pkg/scaling/cache.(*ScalersCache).IsScaledObjectActive 	/workspace/pkg/scaling/cache/scalers_cache.go:89 github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).checkScalers 	/workspace/pkg/scaling/scale_handler.go:261 github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).startScaleLoop 	/workspace/pkg/scaling/scale_handler.go:146
ts | 1641934785.0183375
}



{
--
error | error parsing rabbitmq metadata: no host setting given
level | error
logger | scalehandler
object { |  
apiVersionkeda.sh/v1alpha1kindScaledObjectnamelusha-prospecting-queues-rmqnamespacelusha | apiVersion | keda.sh/v1alpha1 | kind | ScaledObject | name | lusha-prospecting-queues-rmq | namespace | lusha
apiVersion | keda.sh/v1alpha1
kind | ScaledObject
name | lusha-prospecting-queues-rmq
namespace | lusha
}
scalerIndex | 0
stacktrace | github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).getScaledObjectMetricSpecs 	/workspace/controllers/keda/hpa.go:163 github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).newHPAForScaledObject 	/workspace/controllers/keda/hpa.go:63 github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).createAndDeployNewHPA 	/workspace/controllers/keda/hpa.go:46 github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).ensureHPAForScaledObjectExists 	/workspace/controllers/keda/scaledobject_controller.go:360 github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).reconcileScaledObject 	/workspace/controllers/keda/scaledobject_controller.go:228 github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).Reconcile 	/workspace/controllers/keda/scaledobject_controller.go:179 sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile 	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.3/pkg/internal/controller/controller.go:114 sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler 	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.3/pkg/internal/controller/controller.go:311 sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem 	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.3/pkg/internal/controller/controller.go:266 sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2 	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.3/pkg/internal/controller/controller.go:227
trigger | 0
ts | 1641995139.0565894
}

**Comment by JorTurFer** [comment]
I think that there are missing logs :(
Could you collect more logs during the next time that this happens, please? Another thing, please paste them as a code because now they are super difficult for reading

**Comment by zroubalik** [comment]
Might be related to this: https://github.com/kedacore/keda/issues/2415

**Comment by JorTurFer** [comment]
The metrics server logs show one error, I think that not because #2415 is related with the operator
