### ISSUE TITLE
New scaler for KubeMQ 

### ISSUE THREAD

**Issue by TheHunter** [kedacore/keda#2478]
### Proposal

Recently, It was developed a new modern native kubernetes message platform called KubeMQ, a very light and and kubernetes natively oriented.

The idea is to implement a new scaler for this great competitor of rabbitmq, activemq and kafka.

### Scaler Source

I want to scale the number of subscribers ( same implementation of rabbitmq scaler )

### Scaling Mechanics

The scaling mechanics could be based on the number of messages present into "source queues" (similar like rabbitmq mechanics)

### Authentication Source

The authentication could be similar like rabbitmq, so basic credentials on kubemq cluster

### Anything else?

The idea is to have a similar implementation like rabbitmq, so based on the number of messages on queues, scalers could increase the number of deployments / statefulsets / jobs.

**Comment by tomkerkhove** [comment]
KubeMQ - https://kubemq.io/

Good idea, are you up to contributing this scaler? https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#contributing-scalers
