### ISSUE TITLE
AWS DynamoDb scaler

### ISSUE THREAD

**Issue by samueleresca** [kedacore/keda#2482]
### Proposal

Scaler based on the result of a DynamoDB table query.

### Scaler Source

The single numeric result of a DynamoDb query.

### Scaling Mechanics

The scaling mechanics is based on the result of a table query in DynamoDB (similar to what has been done for MongoDB).

### Authentication Source

It can reuse the `identityOwner` and the `TriggerAuthentication`  implemented for the SQS Scaler.

### Anything else?

The idea is similar to the MongoDB scaler. It is possible to reuse the authentication bit already implemented for Amazon SQS.
DynamoDb paginates results over 1MB, see [https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Query.html#Query.Count](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Query.html#Query.Count)

**Comment by tomkerkhove** [comment]
Are you willing to contribute this?

**Comment by samueleresca** [comment]
> Are you willing to contribute this?

Yes, I can have a look 👍🏻
