### ISSUE TITLE
Kafka scaler stops working until pods are restarted

### ISSUE THREAD

**Issue by bilby91** [kedacore/keda#2484]
### Report

We are experiencing an issue with the Kafka-based autoscaler that requires re-creating Keda pods in order to get it fixed. 

The Leda operator metrics pod is throwing the following errors when autoscaling stops working:

```
E0114 20:25:44.258822       1 deleg.go:144] keda_metrics_adapter/kafka_scaler "msg"="" "error"="error finding offset block for topic my-topic and partition 47"
E0114 20:25:44.258835       1 deleg.go:144] keda_metrics_adapter/kafka_scaler "msg"="" "error"="error finding offset block for topic my-topic and partition 49"
E0114 20:25:44.258847       1 deleg.go:144] keda_metrics_adapter/kafka_scaler "msg"="" "error"="error finding offset block for topic my-topic and partition 42"
E0114 20:25:44.258861       1 deleg.go:144] keda_metrics_adapter/kafka_scaler "msg"="" "error"="error finding offset block for topic my-topic and partition 7"
E0114 20:25:44.258874       1 deleg.go:144] keda_metrics_adapter/kafka_scaler "msg"="" "error"="error finding offset block for topic my-topic and partition 21"
```

### Expected Behavior

Kafka-based autoscaling should work correctly without the need of re-creating an pod.

### Actual Behavior

Metrics pod must be re-created in order for autoscaling to continue working.

### Steps to Reproduce the Problem

Unclear

### Logs from KEDA operator

```
E0114 20:25:44.258822       1 deleg.go:144] keda_metrics_adapter/kafka_scaler "msg"="" "error"="error finding offset block for topic my-topic and partition 47"
E0114 20:25:44.258835       1 deleg.go:144] keda_metrics_adapter/kafka_scaler "msg"="" "error"="error finding offset block for topic my-topic and partition 49"
E0114 20:25:44.258847       1 deleg.go:144] keda_metrics_adapter/kafka_scaler "msg"="" "error"="error finding offset block for topic my-topic and partition 42"
E0114 20:25:44.258861       1 deleg.go:144] keda_metrics_adapter/kafka_scaler "msg"="" "error"="error finding offset block for topic my-topic and partition 7"
E0114 20:25:44.258874       1 deleg.go:144] keda_metrics_adapter/kafka_scaler "msg"="" "error"="error finding offset block for topic my-topic and partition 21"
```

### KEDA Version

2.5.0

### Kubernetes Version

1.19

### Platform

Amazon Web Services

### Scaler Details

Kafka

**Comment by JorTurFer** [comment]
Hi, 
Are you using ScaledObjects or ScaledJobs? Could you share more logs please?

**Comment by bilby91** [comment]
@JorTurFer I'll try to capture more logs next time it happens. Other logs didn't look relevant to the problem (from my ignorant perspective) which is why I didn't include them.

We are using `ScaledObject` CRD.

**Comment by JorTurFer** [comment]
is this problem present in v2.4? I don't remember, but I think that v2.5 doesn't introduce any big change in kafka, maybe you could try it to check if the problem it's in the scaler or in the cache system

**Comment by bilby91** [comment]
I'm going to give 2.4 a shot and report back. Thanks @JorTurFer

**Comment by bilby91** [comment]
@JorTurFer I have downgraded to 2.4 in all of our clusters and the issue is no longer happening. After reviewing the diff between 2.5 and 2.4, it seems highly likely that the new cache could be the culprit. The Kafka autoscaler itself looks almost unchanged.

**Comment by zroubalik** [comment]
@bilby91 I think this is related to the caching problem, should be fixed in 2.6.0

**Comment by pchaudhary1** [comment]
Hi @bilby91 
I am on Keda Version 2.6.0 and I see the same error message mentioned above.
Should I downgrade to 2.4.0 to get around this issue?

Regards,
Pankaj

**Comment by zroubalik** [comment]
@pchaudhary1 this should be fixed in 2.6.1. So I rather recomend update over downgrade :)

**Comment by joaoluchetti** [comment]
Hi, 

We are having the exact same issue on Keda 2.7.1, shouldn't this be fixed after 2.6.1?

```
 keda_metrics_adapter/kafka_scaler \"msg\"=\"\" \"error\"=\"error finding offset block for topic com.arquivei.events.app_billing-was-updated and partition 0\"  \n","stream":"stderr","time":"2023-01-06T18:39:28.298335092Z"}
```

**Comment by sinanub18** [comment]
Hi,

I am facing this issue in Keda 2.9.0 as well

**Comment by JorTurFer** [comment]
As this was related with other cause (even if behavior is the same), could you open a new issue to track it? :pray:

**Comment by sinanub18** [comment]
> As this was related with other cause (even if behavior is the same), could you open a new issue to track it? 🙏

New issue created - https://github.com/kedacore/keda/issues/4215
