### ISSUE TITLE
Scaledjob creates double amount of replicas on the first time

### ISSUE THREAD

**Issue by omer2500** [kedacore/keda#2488]
### Report

I have a queue with 42 messages, I configured a scaled job that will consume the messages (42 jobs each with 1 pod in it)

I set the maxReplicaCount to 42 (in my use case it will always be 42)
when I trigger it for the first time keda creates 84 jobs instead of 42
on the second run of such an operation, keda created 42 as expected

im using keda 2.3 (helm chart on eks)

here is my yaml:
```
apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: worker
  namespace: default
spec:
  jobTargetRef:
    parallelism: 1
    completions: 1
    activeDeadlineSeconds: 18000
    backoffLimit: 10
    template:
      metadata:
        annotations:
          cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
      spec:
        containers:
          - name: alaska-worker
            image: ''"
            imagePullPolicy: Always
            resources:
              limits:
                memory: '1Gi'
                cpu: '200m'
              requests:
                memory: '550Mi'
                cpu: '100m'
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 5
  maxReplicaCount: 42
  triggers:
    - type: rabbitmq
      metadata:
        protocol: amqp
        queueName: tasks
        mode: QueueLength
        value: "1"
      authenticationRef:
        name: keda-trigger-auth-rabbitmq-conn
```

### Expected Behavior

keda should respect the maxReplicaCount and create only 42 jobs or less

### Actual Behavior

keda on the first trigger is creating double of the size mentioned on the maxReplicatCount

### Steps to Reproduce the Problem

1. create queue with 42 messages
2. create the scaledJob with my config and run it

### Logs from KEDA operator

```
│ 2022-01-17T10:27:51.608Z    INFO    scaleexecutor    Creating jobs    {"scaledJob.Name": "alaska-worker", "scaledJob.Namespace": "default", "Effective number of max jobs": 42}                                  │
│ 2022-01-17T10:27:51.608Z    INFO    scaleexecutor    Creating jobs    {"scaledJob.Name": "alaska-worker", "scaledJob.Namespace": "default", "Number of jobs": 42}                                                │
│ 2022-01-17T10:27:51.622Z    INFO    scaleexecutor    Creating jobs    {"scaledJob.Name": "alaska-worker", "scaledJob.Namespace": "default", "Effective number of max jobs": 42}                                  │
│ 2022-01-17T10:27:51.622Z    INFO    scaleexecutor    Creating jobs    {"scaledJob.Name": "alaska-worker", "scaledJob.Namespace": "default", "Number of jobs": 42}                                                │
│ 2022-01-17T10:27:54.268Z    INFO    scaleexecutor    Created jobs    {"scaledJob.Name": "alaska-worker", "scaledJob.Namespace": "default", "Number of jobs": 42}                                                 │
│ 2022-01-17T10:27:54.318Z    INFO    scaleexecutor    Created jobs    {"scaledJob.Name": "alaska-worker", "scaledJob.Namespace": "default", "Number of jobs": 42}    
```
see how it is shown twice on the logs?

### KEDA Version

2.3.0

### Kubernetes Version

1.23

### Platform

Amazon Web Services

### Scaler Details

rabbitmq

### Anything else?

I saw this issue:

https://github.com/kedacore/keda/issues/529

but on the keda channel on slack i was asked to open a separate issue for that

Thanks!

**Comment by JorTurFer** [comment]
Is this behaviour still present on KEDA v2.6.1?

**Comment by hschimmel** [comment]
I just experienced this using Keda v2.12.0. It looks to me that this issue has only been closed because it went stale. And a previous issue #529 was also closed. But in this comment https://github.com/kedacore/keda/pull/945#issuecomment-663915914 529 was mentioned as not yet fixed.

**Comment by JorTurFer** [comment]
This issue was closed due to inactivity 2  years ago, could you open another issue to track your case? 🙏
