### ISSUE TITLE
Sample for SQS scaler

### ISSUE THREAD

**Issue by asavaritayal** [kedacore/keda#254]

**Comment by patnaikshekhar** [comment]
Hi @Aarthisk would you be able to assign this issue to me.

**Comment by patnaikshekhar** [comment]
Hi @Aarthisk here is the URL for the SQS [sample](https://github.com/patnaikshekhar/KEDA-AWS-SQS-Python). Could you please review?

**Comment by asavaritayal** [comment]
@asavaritayal to validate the sample.

**Comment by tomkerkhove** [comment]
Any update on this @asavaritayal?

**Comment by tomkerkhove** [comment]
Bump @asavaritayal

**Comment by rushivarun** [comment]
Flask app fails in the container.

> Hi @Aarthisk here is the URL for the SQS [sample](https://github.com/patnaikshekhar/KEDA-AWS-SQS-Python). Could you please review?
