### ISSUE TITLE
Use re-usable workflows for GitHub Actions

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda#2569]
Use re-usable workflows for GitHub Actions to remove the duplication that we have, for example for [doing e2e-tests](https://github.com/kedacore/keda/pull/2568).

**Comment by tomkerkhove** [comment]
This should now be easier to achieve: https://github.blog/changelog/2022-08-22-github-actions-improvements-to-reusable-workflows-2/

**Comment by JorTurFer** [comment]
I'm implementing reusable workflows, thanks for staying tuned to every change on their side @tomkerkhove

**Comment by tomkerkhove** [comment]
Happy to help!
