### ISSUE TITLE
Ability for keda-operator to connect out using proxy server

### ISSUE THREAD

**Issue by wltbenade** [kedacore/keda#2577]
### Proposal

Currently, there doesn't seem to be any mechanism to allow the keda-operator to connect out using a proxy server, rendering it impossible to connect to external services to pull metric data.

I've tried to set HTTP_PROXY, HTTPS_PROXY, as well as their lowercase counterparts, without result.

It would be highly beneficial to have the operator able to connect to external services using either environment variables, or an explicitly defined proxy definition.

### Use-Case

We utilise KEDA's Azure Pipelines scaler in on-prem clusters, which requires all external access to be routed via proxies, including Azure DevOps.

First prize would be to be able to set proxy URL, username, password via environment variables via the helm chart values.

### Anything else?

Golang's http package can read proxy variables from the environment using the http.ProxyFromEnvironment(req) function. I just don't know where it should be implemented to make the most sense.

**Comment by racdev** [comment]
I think all that is required here is to add the following:
`Proxy: http.ProxyFromEnvironment`
 to the Transport definition here: https://github.com/kedacore/keda/blob/main/pkg/util/http.go#L42 i.e.
```
httpClient := &http.Client{
		Timeout: timeout,
		Transport: &http.Transport{
			TLSClientConfig: &tls.Config{InsecureSkipVerify: unsafeSsl},
                        Proxy: http.ProxyFromEnvironment,
		},
	}
```

**Comment by wltbenade** [comment]
Thanks, @racdev. I'm not a developer, so I didn't want to take the chance.

I'll try this locally to see if it works, then submit a PR.

**Comment by anton-dealmeida** [comment]
Thanks @racdev!
