### ISSUE TITLE
Improve e2e tests to always cleanup resources in cluster

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda#2584]
Improve e2e tests to always cleanup resources in cluster, even if it was cancelled.

As per [the docs](https://docs.github.com/en/actions/managing-workflow-runs/canceling-a-workflow#steps-github-takes-to-cancel-a-workflow-run), this should be possible to use a `job` with condition `if: always()`.

This avoids a bad starting point for next test runs if the previous one failed or was cancelled.

**Comment by JorTurFer** [comment]
Maybe we could use a pattern for testing namespaces (now the naming is totally free) and during the test preparation, we can run the deletion to ensure that all resources are cleaned before the start.
WDYT @kedacore/keda-core-contributors  ?

**Comment by tomkerkhove** [comment]
Testing namespaces are good for me, but I'd prefer to clean things up at the end rather than the beginning to follow the boyscout rule - Clean up before you leave

**Comment by JorTurFer** [comment]
Note to my self: review also azure-queue
