### ISSUE TITLE
Authentication fails for Azure Pipelines scaler due to new line characters

### ISSUE THREAD

**Issue by vazkarvishal** [kedacore/keda#2600]
### Report

Trying to use the AzureDevOps pipeline autoscaler and keep getting a 401 with the following error:
```
│   Warning  KEDAScalerFailed         0s (x11 over 8s)  keda-operator  error parsing azure Pipelines metadata: the Azure DevOps REST API returned error. url: https://dev.azure.com/REDACTED/_apis/distributedtask/pools?poolName=keda-ado-agents status: 401 response:    │
```

When triggering the same API call using Postman I am getting a 200.

**UPDATE: 07-02-2022:17:35**

When replacing the ADO token to use `plain-text` instead of secrets, everything seems to work fine. So the issue seems to be in either **TriggerAuthentication** or the way the **ScaledObject** decrypts the secret.

Keda Version: 2.6
Helm Version: 3.8.0

Code

### Expected Behavior

Should work with a 200 as expected.

### Actual Behavior

Fails with a 401. Tried using different Base64 encoding using community responses, but none work. Tried to use version 2.4 to validate if the error was in the latest version, but get the same error.

### Steps to Reproduce the Problem

1. Create the agent using the [documentation here](https://keda.sh/blog/2021-05-27-azure-pipelines-scaler/)
2. Create the Scaled Object
3. Monitor the scaled object (using K9s or a similar tool)

### Logs from KEDA operator

```
│   Warning  KEDAScalerFailed         0s (x11 over 8s)  keda-operator  error parsing azure Pipelines metadata: the Azure DevOps REST API returned error. url: https://dev.azure.com/REDACTED/_apis/distributedtask/pools?poolName=keda-ado-agents status: 401 response:    │
```

### KEDA Version

2.6.0

### Kubernetes Version

1.21

### Platform

Other

### Scaler Details

Azure Pipelines

**Comment by vazkarvishal** [comment]
After further debugging, turns out that the Keda`ScaledObject` or `ScaledJob` does not strip new lines in the AzDo API Token provided. Thus, if the PAT_TOKEN was base64 encrypted using a command-line command like: `echo $PAT_TOKEN | base64` , you end-up with an encrypted token with a new line, which then breaks the authentication (as the Keda module does not handle stripping of new-line chars after decoding).

Thus to resolve this, I had to explicitly use `echo -n ${PAT_TOKEN} | base64` to avoid creating new lines. A useful fix for this maybe to strip new-line characters from the token before being used? As this is very likely to happen and there isin't much help/logs/documentation out there which avoids users from getting caught out by something like this.

**Comment by zroubalik** [comment]
> **RECOMMENDED FIX**
> KEDA Scaled Objects and Jobs to strip new-line characters (if found) from b64 encoded secrets.

@kedacore/keda-maintainers WDYT? Is there a possibility we would like to encode (and keep) the new line character somewhere?

**Comment by tomkerkhove** [comment]
The question is, do we do it everywhere or not? isn't it tricky if we start removing new lines and, for some reason, this is intentional by end-users?

What if we log a warning that it has new lines instead of manipulating the secret? That way it's more discoverable but we don't change things?

Just a thought.

**Comment by zroubalik** [comment]
A warning is a great idea. @vazkarvishal are you willing to contribute this?

**Comment by vazkarvishal** [comment]
> 

Absolutely. What am I expected to do?

**Comment by tomkerkhove** [comment]
Would be nice if the code could check for leading/trailing new lines and log warnings correspondingly.

**Comment by vazkarvishal** [comment]
> 

I am not a proficient go developer, so I would not be the best person to write this I'm afraid 😔

**Comment by tomkerkhove** [comment]
No problem at all!

**Comment by JorTurFer** [comment]
Don't worry, if you want, open a PR and we will help you. If you prefer don't do it, no problem at all.
