### ISSUE TITLE
No way to specify TLS disabled for Kafka scaler

### ISSUE THREAD

**Issue by gunniwho** [kedacore/keda#2608]
### Report

When using the Apache Kafka scaler, you can set the auth parameter `tls` to `enabled` for the underlying kafka client to use tls when connecting to the brokers. There is no way however to set `tls` to anything else to configure tls to be disabled. See [here](https://github.com/kedacore/keda/blob/main/pkg/scalers/kafka_scaler.go#L170-L189). Now I know that the default behavior is that tls is off but the current behavior is counter-intuitive.

### Expected Behavior

`tls: disabled` is not invalid and means the same as not specifying the parameter

### Actual Behavior

The scaler throws an error

### Steps to Reproduce the Problem

1. Create a trigger authentication resource that exposes the tls parameter as "disabled"
2. Create a kafka scaler that references the trigger auth
3. The scaler can't be created because the tls value is invalid

### KEDA Version

2.6.0

### Kubernetes Version

1.20

### Platform

Amazon Web Services

### Scaler Details

Kafka

**Comment by tomkerkhove** [comment]
Thank you for the PR!
