### ISSUE TITLE
Selenium Grid Scaler should consider "maxSession"

### ISSUE THREAD

**Issue by d-patch** [kedacore/keda#2618]
### Proposal

The graphql API of Selenium Grid allows to query the "maxSession" value per grid and/or node:
[https://www.selenium.dev/documentation/grid/advanced_features/graphql_support/#querying-the-number-of-maxsession-and-sessioncount-in-the-grid-](https://www.selenium.dev/documentation/grid/advanced_features/graphql_support/#querying-the-number-of-maxsession-and-sessioncount-in-the-grid-)
That is, if maxSession=5 each node can hold up to 5 concurrent sessions. Therefore, if there are 10 requests in the queue, only 2 nodes are neccessary to fulfill the requirements. Currently, the Selenium Grid Scaler of KEDA will scale up to 10 nodes in this case, ignoring the maxSessions per node.

**Comment by zroubalik** [comment]
Seems reasonable, are you willing to contribute this?

**Comment by d-patch** [comment]
Sorry, but unfortunately I'm merely a user and not a developer.

**Comment by adborroto** [comment]
I can take this one.

**Comment by JorTurFer** [comment]
Thanks a lot! ❤️

**Comment by amit337496** [comment]
@adborroto  Any update on this issue

**Comment by adborroto** [comment]
> @adborroto Any update on this issue

[PR](https://github.com/kedacore/keda/pull/2774) open

**Comment by amit337496** [comment]
@JorTurFer / @adborroto  I see this issue is closed... Is there any version we need to get this

**Comment by JorTurFer** [comment]
Hi @amit337496 
Next release will be during the first half of May. If you need to test this feature, you could use `main` tag, but we don't recommend it for prod environments because `main` is built every commit and could be not stable

**Comment by amit337496** [comment]
@JorTurFer  Thank you.. I am able to see changes in 2.7 version.

How this scale down will happen in this scenario.. If node is still running will it kill that?

**Comment by JorTurFer** [comment]
hi @amit337496 
I'm not sure if I get your question. Do you mean how the scale in will be done?
If that's your question, KEDA doesn't take care about that because it's the HPA Controller who manages it. The HPA kills pods with task in progress, so your job could be interrupted. If you have use cases with long-running tasks or when your system doesn't retry non-acknowledge messages, [you should use ScaledJob instead of ScaledObject](https://keda.sh/docs/2.7/concepts/scaling-jobs/).

**Comment by JorTurFer** [comment]
Did you check ScaledJob? It, s the solution for long term processes
