### ISSUE TITLE
IdleReplicaCount of 1 does not work

### ISSUE THREAD

**Issue by q26646** [kedacore/keda#2619]
### Report

We are unable to use idleReplicantCount attribute in keda scaled objects due to a misleading error:  "error": "IdleReplicaCount=1 must be less or equal to MinReplicaCount=1"

### Expected Behavior

The scaledobject should have 1 replica(idleReplicaCount) when there are no messages and scale up to minreplicaCount as soon as there are messages and after that based on the lag it should go upto maxReplicaCount

### Actual Behavior

We are seeing the error that says:  IdleReplicaCount=1 must be less or equal to MinReplicaCount=1" which does not make sense since it's less than or equal to MinReplicaCount

### Steps to Reproduce the Problem

1. Create a scaled object with the below replica configuration:

```
idleReplicaCount: 1
maxReplicaCount: 2
minReplicaCount: 1
```
2. Watch the keda operator logs to see that it's printing the error that says  IdleReplicaCount=1 must be less or equal to MinReplicaCount=1
3.

### Logs from KEDA operator

```
example
```

### KEDA Version

2.4.0

### Kubernetes Version

1.21

### Platform

Microsoft Azure

### Scaler Details

Kafka

**Comment by zroubalik** [comment]
You don't have to specify `idleReplicaCount` in this scenario, see https://github.com/kedacore/keda/discussions/2610

**Comment by q26646** [comment]
We did try it with minReplicaCount=2 and idleReplicaCount=1. It still gives the same error and it does not scale the target.

**Comment by zroubalik** [comment]
just specify this
```yaml
minReplicaCount: 1
maxReplicaCount: 2
```

and omit `idleReplicaCount` from the configuration completely.

**Comment by q26646** [comment]
Thats what we have as a workaround currently to avoid the error message. However, usecase is to have  1 pod running even when there is no lag, but spin up an additional 2 pods upto a max of 6 pods. Per the documentation, we should be able to use the below. However, it does not work due to the error. May be I need a bit more education on the whole purpose of having idleReplicaCount.
```
idleReplicaCount: 1
minReplicaCount: 2
maxReplicaCount: 6

**Comment by zroubalik** [comment]
`idleReplicaCount` works only for `0` replicas, see the documentation: https://keda.sh/docs/2.6/concepts/scaling-deployments/

Following will scale between 1-6 replicas:
```yaml
minReplicaCount: 1
maxReplicaCount: 6
```

**Comment by q26646** [comment]
thanks
