### ISSUE TITLE
Image releases

### ISSUE THREAD

**Issue by asavaritayal** [kedacore/keda#262]
We need to setup GitHub releases for the KEDA image. There already seems to be a CircleCI setup. We should have a nightly build to update master as well.

**Comment by tomkerkhove** [comment]
And I'd like to add to that that we need to:
- Create a separate image for CI/official release
- Create separate Helm charts for CI/official release

That way we have a **stable & experimental** release stream.

As an example, our [Helm chart](https://hub.helm.sh/charts/kedacore/keda-edge) Helm chart is polluted with all CI/nightly versions while we should have a stable stream.
![image](https://user-images.githubusercontent.com/4345663/62106805-76dcae00-b2a6-11e9-9095-cd258a2f351a.png)

This would be a v1.0 requirement for me @jeffhollan

**Comment by tomkerkhove** [comment]
Happy to help, but only used to use Azure DevOps 😅

**Comment by tomkerkhove** [comment]
This is now done thanks to @ahmelsayed!

Docs are tracked in #439
