### ISSUE TITLE
day-of-week support for cron scaler

### ISSUE THREAD

**Issue by trondhindenes** [kedacore/keda#2626]
### Proposal

We'd like to do `0 9 * * 1-5` to have a scaler perform scale-up on weekdays only. This seems to not work in Keda atm:

```error parsing cron metadata: error parsing start schedule. map[desiredReplicas:3 end:0 17 * * 1-5 start:0 9 * * 1-5 timezone:Europe/Oslo]: range or hyphenated inputs are not allowed```

**Comment by tomkerkhove** [comment]
Fair request - Are you willing to contribute this?

**Comment by trondhindenes** [comment]
I'm not an expert go dev, but I can definetely make an attempt. Will report back here.

**Comment by trondhindenes** [comment]
my bad. This seems to have been fixed as part of https://github.com/kedacore/keda/pull/2038 - I was on an older version. Closing.
