### ISSUE TITLE
Provide scaler for Google cloud storage

### ISSUE THREAD

**Issue by RamCohen** [kedacore/keda#2628]
### Proposal

Scale based on the number of objects in a Google cloud storage bucket

### Scaler Source

Scale based on the number of objects in a bucket

### Scaling Mechanics

Periodically list and count the number of object in the specified google cloud storage bucket.
Use an upper limit on the # of counted items to handle buckets with a very large number of items.

### Authentication Source

See https://pkg.go.dev/cloud.google.com/go#hdr-Authentication_and_Authorization

### Anything else?

SDK: https://pkg.go.dev/cloud.google.com/go/storage

**Comment by tomkerkhove** [comment]
Would be a great addition, thank you!
