### ISSUE TITLE
Allow connection strings to be set via Secret or ConfigMap reference that *is not* referenced from the deployment

### ISSUE THREAD

**Issue by lee0c** [kedacore/keda#263]
Currently, KEDA resolves environment variables by pulling all literals, secretrefs, and configmaprefs from the target deployment's environment variables. KEDA should also be able to take in a secret ref or config map ref without referencing the container's env/envfrom fields at all.

**Comment by lee0c** [comment]
@jeffhollan double checked on this after our conversation yesterday & it looks like this is **not** possible (also not in the docs). KEDA resolves secret refs/config map refs in the container spec, but cannot resolve a secret ref handed to it as far as I can tell.

**Comment by tomkerkhove** [comment]
That is my understanding as well and agree that it would be great to have option to decouple this

**Comment by jeffhollan** [comment]
Ah thank you - I failed to realize that often the secret spec I've been using has been added as config to the deployment.  Yes this is a good feature.

**Comment by jeffhollan** [comment]
@priyaananthasankar was brought up that you may be working on this? Can I assign it to you and you can share details on how you are looking to implement.  @ahmelsayed had a few questions in our standup

**Comment by priyaananthasankar** [comment]
Yes. I am looking into this and will share some details after one week hack.

**Comment by tomkerkhove** [comment]
Let's take this along with the AAD Pod Identity discussion as this is very similar and should be taken along.

**Comment by tomkerkhove** [comment]
This is a good one we should address imo @jeffhollan

**Comment by tomkerkhove** [comment]
Closing as this is possible via TriggerAuthentication
