### ISSUE TITLE
Improve how the Datadog scaler retrieves the Datadog query

### ISSUE THREAD

**Issue by arapulido** [kedacore/keda#2630]
### Proposal

Right now, the Datadog scaler expects a well formed Datadog query in the ScaledObject.

This is OK, but it would be better if it would do the following:

* If the ScaledObject has a "query", then regex that the query is correct before proceeding 
* If the ScaledObject has a "metricName" instead of a query, then build the corresponding query automatically, based on a default aggregator (avg)

### Use-Case

This will make it a lot easier for users to use the Datadog scaler, without having to build the query themselves.

**Comment by arapulido** [comment]
@zroubalik hey! I think this will be a good improvement for the Datadog scaler. Can you assign this issue to me, please? Thanks!

**Comment by zroubalik** [comment]
@arapulido done, the improvement looks great, thanks!

**Comment by arapulido** [comment]
With the changes made for #2771, the way queries get the default rollup and aggregators rely on the Datadog API, simplifying a lot the UX as well. The only thing needed in a query now, apart from a metric, is a scope, which can default to all. I think we can close this issue now, as this is no longer that needed after those changes.
