### ISSUE TITLE
RabbitMQ api hosted in a subpath is truncated  to http://host/api/ when it shouldbe http://host/subpath/api

### ISSUE THREAD

**Issue by ovidiubuligan** [kedacore/keda#2634]
### Report

We are hosting rabbitmq with a subpath due to ingress exposed as a subpath .We do it with the following setting : 
```
  management.path_prefix = /rabbit
```
in bitnami helm chart :  
```yaml
extraConfiguration: |-
  management.path_prefix = /rabbit
```
This causes the api to also be hosted at `http://host/rabbit/api`

**Problem is this resset of Path  `parsedURL.Path = ""` here :** https://github.com/kedacore/keda/blob/v2.6.1/pkg/scalers/rabbitmq_scaler.go#L426 

We are using this configuration in keda `ScaledSecret` : 
```yaml
  triggers:
  - type: rabbitmq
    metadata:
      host: http://user:pass@rabbitmq.rabbitmq.svc.cluster.local:15672/rabbit/
      mode: MessageRate
      protocol: auto
      queueName: My-queue
      value: "1"
      vhostName: /
```

### Expected Behavior

Setting the host path is preserved and not truncated.

### Actual Behavior

rabbitmq http subpath is truncated

### Steps to Reproduce the Problem

1. Install https://bitnami.com/stack/rabbitmq/helm with this configuration
```yaml
extraConfiguration: |-
  management.path_prefix = /rabbit
```
2. configure keda with rabbitmq MessageRate
3.

### Logs from KEDA operator

keda operator logs
```
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).startScaleLoop                                                                                   │
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).startScaleLoop
        /workspace/pkg/scaling/scale_handler.go:149
1.6448533659252813e+09  ERROR   scalehandler    Error getting scale decision    {"scaledobject.Name": "vbc-vbs-scaledobject", "scaledObject.Namespace": "dev", "scaleTarget.Name": "vbc-vbs-contrib", "error": "error inspecting rabbitMQ: error requesting rabbitMQ API status: 404 Not Found, response: {\"error\":\"Object Not Found\",\"reason\":\"Not Found\"}, from: http://user:password@rabbitmq.rabbitmq.svc.cluster.local:15672/api/queues/%!F(MISSING)/VBUS-req-queue"}
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).checkScalers
        /workspace/pkg/scaling/scale_handler.go:278
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).startScaleLoop
        /workspace/pkg/scaling/scale_handler.go:149
1.6448533959287195e+09  ERROR   scalehandler    Error getting scale decision    {"scaledobject.Name": "vbc-vbs-scaledobject", "scaledObject.Namespace": "dev", "scaleTarget.Name": "vbc-vbs-contrib", "error": "error inspecting rabbitMQ: error requesting rabbitMQ API status: 404 Not Found, response: {\"error\":\"Object Not Found\",\"reason\":\"Not Found\"}, from: http://user:password@rabbitmq.rabbitmq.svc.cluster.local:15672/api/queues/%!F(MISSING)/VBUS-req-queue"}
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).checkScalers
        /workspace/pkg/scaling/scale_handler.go:278
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).startScaleLoop
        /workspace/pkg/scaling/scale_handler.go:149
```
keda operator metrics pod logs:
```
E0214 15:44:00.029030       1 provider.go:124] keda_metrics_adapter/provider "msg"="error getting metric for scaler" "error"="error inspecting rabbitMQ: error requesting rabbitMQ API status: 404 Not Found, response: {\"error\":\"Object Not Found\",\"reason\":\"Not Found\"}, from: http://user:password@rabbitmq.rabbitmq.svc.cluster.local:15672/api/queues/%!F(MISSING)/VBUS-req-queue"  "scaledObject.Name"="vbc-vbs-scaledobject" "scaledObject.Namespace"="dev" "scaler"={}
E0214 15:44:00.029088       1 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"no matching metrics found for s0-rabbitmq-vbus-req-queue"}: no matching metrics found for s0-rabbitmq-vbus-req-queue
E0214 15:44:15.052886       1 provider.go:124] keda_metrics_adapter/provider "msg"="error getting metric for scaler" "error"="error inspecting rabbitMQ: error requesting rabbitMQ API status: 404 Not Found, response: {\"error\":\"Object Not Found\",\"reason\":\"Not Found\"}, from: http://user:password@rabbitmq.rabbitmq.svc.cluster.local:15672/api/queues/%!F(MISSING)/VBUS-req-queue"  "scaledObject.Name"="vbc-vbs-scaledobject" "scaledObject.Namespace"="dev" "scaler"={}
E0214 15:44:15.052967       1 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"no matching metrics found for s0-rabbitmq-vbus-req-queue"}: no matching metrics found for s0-rabbitmq-vbus-req-queue
```

ScaledObject k8s event message :
```
error inspecting rabbitMQ: error requesting rabbitMQ API status: 404 Not Found, response: {"error":"Object Not Found","reason":"Not ││  Found"}, from: http://user:password@rabbitmq.rabbitmq.svc.cluster.local:15672/api/queues/%!F(MISSING)/My-queue 
```
From the message we can clearly see that `rabbit` subpath is truncated
### KEDA Version

2.6.1

### Kubernetes Version

1.22

### Platform

Microsoft Azure

### Scaler Details

RabbitMQ

**Comment by rtnpro** [comment]
I am triaging this issue.

**Comment by shcherbak** [comment]
@rtnpro @tomasgiden the error persists

**Comment by rtnpro** [comment]
@shcherbak Thanks for bringing this up.

@tomasgiden @ovidiubuligan I confirm that this issue still persists. I am working on a fix for it. Please reopen this issue.

**Comment by rtnpro** [comment]
Great job on #4584, @AmorBielyi!

I wanted to express my support for the idea of including a separate boolean option to enable a subpath in the host value of the RabbitMQ scaler. However, I believe it might introduce some complexity to the current parsing of the RabbitMQ host path. I'm curious to know how you plan to handle situations where both vhost and subpath are specified in the host URL while allowSubpathsOnHost is set to True. In my recent approach in #4589, I utilized string operations to extract the subpath and vhost from the host path.

I strongly believe that we should carefully consider the developer experience (DX) when configuring the RabbitMQ Scaler and strive to minimize any potential confusion.

In my opinion, we have two possible approaches: either parse the host path URI to retrieve the subpath, vhost, and other necessary details, or alternatively, disallow the specification of vhost in the host path altogether and utilize the vhost scaler metadata instead.

@zroubalik @JorTurFer WDYT?

**Comment by JorTurFer** [comment]
There are already some comments to address in the PR 😄

**Comment by AmorBielyi** [comment]
> There are already some comments to address in the PR 😄

thanks, almost done

**Comment by JorTurFer** [comment]
This isn't stale, just summer break has happended xD
