### ISSUE TITLE
Provide a metric for total amount of ScaledObjects

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda#2637]
### Proposal

Provide a metric for total amount of ScaledObjects so that end-users can visualize it.

### Use-Case

Improve our operational story

**Comment by liangyuanpeng** [comment]
I want to work for it, can you give me some help? Thanks.

Have a question: where is the appropriate place to implement this, is it port of 9022 from keda-operator-metrics-apiserver?

**Comment by zroubalik** [comment]
Yeah, probably yes, given the current implementation. 

Though we should think about this as well: https://github.com/kedacore/keda/issues/1281

**Comment by bamboo12366** [comment]
Can consider adding update hpa error and active polling rate/error rate as well IMHO
As I mention in this issue https://github.com/kedacore/keda/issues/3098, those are both key metrics in my use-case

**Comment by tomkerkhove** [comment]
This is nto really related here but created https://github.com/kedacore/keda/issues/3120

**Comment by v-shenoy** [comment]
Closed in #3719
