### ISSUE TITLE
External scalers receive metric names with internal KEDA core prefix

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda#2640]
### Discussed in https://github.com/kedacore/keda/discussions/2635

<div type='discussions-op-text'>

<sup>Originally posted by **krishna-kariya** February 14, 2022</sup>
Hi, 
I am testing HTTP-triggered Azure Functions on Azure Arc with Keda version 2.5 and 2.6.1. We have created our external HTTP scaler on Keda for autoscaling. 

I am getting the error below in the metrics API server 
`E0207 02:55:09.412436 1 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"No matching metrics found for s0-upstream_rq_total"}: No matching metrics found for s0-upstream_rq_total`.

The hpa shows a similar error: 
`invalid metrics (4 invalid out of 4), first error is: failed to get s0-upstream_rq_active external metric: unable to get external metric k8se-apps/s0-upstream_rq_active/&LabelSelector{MatchLabels:map[string]string{scaledobject.keda.sh/name: myapp,},MatchExpressions:[]LabelSelectorRequirement{},}: unable to fetch metrics from external metrics API: no matching metrics found for s0-upstream_rq_active` 

I see that from Keda v2.5 and later, the external metric names are prefixed with "sX-". Is this a new addition? 
We have created our external HTTP scaler. Do we need to update our external HTTP scaler with these new metric names? 

Any help would be appreciated. Thanks. </div>

## Tasklist

- [ ] Fix in KEDA core to pass correct metric name
- [ ] Provide e2e test(s)

End-users can mitigate this in their external scaler to remove the sX- prefix until we have shipped KEDA v2.6.2 or v2.7.0

**Comment by JorTurFer** [comment]
if nobody tackles this, next week I'll take a look at it

**Comment by tomkerkhove** [comment]
Thank you!

**Comment by v-shenoy** [comment]
Can take a look at this, if noone else is? @JorTurFer

**Comment by tomkerkhove** [comment]
That would be great, thanks @v-shenoy!
