### ISSUE TITLE
KEDA hpa with loganalytics scaler throws error Unable to get external metric after a day of running

### ISSUE THREAD

**Issue by krishnadce** [kedacore/keda#2653]
### Report

Unable to get external metric s0-loganalytics....

The HPA shows the value "Unknown"/3 (Where 3 is my threshold value)

### Expected Behavior

Expectation:

1. Metric should be available.
2. Show the error in the logs if there's some issue.

### Actual Behavior

When the scaler is created, the hpa gets the metric value and displays correctly. And it scales with the rise in the metric value. When we keep this running overnight, by next day, the hpa says "Unknown" for the external metric.
In the HPA Events, it says it tried over 52X in last 2 hrs Unable to Get External Metric s0-loganalytics-...

No ERROR message is found in the KEDA Operator pod log.

When queried with kubectl get --raw https://KUBE-APISERVER-IP:6443/apis/external.metrics.k8s.io/v1beta1/namespaces/keda/s0-azure-log-analytics-...., it throws an error "Unable to get external metric.

### Steps to Reproduce the Problem

1. Create a log analytics scaler and verify the hpa is created
2. Leave the setup overnight 
3. Check the hpa status the next day.

4. Edit the SO by changing some value and the hpa starts showing the metric value.
5. After leaving the setup for overnight, it throws same error in the next morning

### Logs from KEDA operator

```
1.645097356373742e+09   INFO    controller.scaledobject Reconciling ScaledObject    {"reconciler group": "keda.sh", "reconciler kind": "ScaledObject", "name": "kedaloganalytics-abc-scaled-object", "namespace": "keda"}
1.645097356391896e+09   INFO    controller.scaledobject Updated HPA according to ScaledObject       {"reconciler group": "keda.sh", "reconciler kind": "ScaledObject", "name": "kedaloganalytics-abc-scaled-object", "namespace": "keda", "HPA.Namespace": "keda", "HPA.Name": "keda-hpa-kedaloganalytics-abc-scaled-object"}
1.6450973564081438e+09  INFO    controller.scaledobject Reconciling ScaledObject    {"reconciler group": "keda.sh", "reconciler kind": "ScaledObject", "name": "kedaloganalytics-abc-scaled-object", "namespace": "keda"}
1.6450973564290235e+09  INFO    controller.scaledobject Updated HPA according to ScaledObject       {"reconciler group": "keda.sh", "reconciler kind": "ScaledObject", "name": "kedaloganalytics-abc-scaled-object", "namespace": "keda", "HPA.Namespace": "keda", "HPA.Name": "keda-hpa-kedaloganalytics-abc-scaled-object"}
1.645097371936659e+09   INFO    controller.scaledobject Reconciling ScaledObject    {"reconciler group": "keda.sh", "reconciler kind": "ScaledObject", "name": "kedaloganalytics-abc-scaled-object", "namespace": "keda"}
1.6450973719605079e+09  INFO    controller.scaledobject Updated HPA according to ScaledObject       {"reconciler group": "keda.sh", "reconciler kind": "ScaledObject", "name": "kedaloganalytics-abc-scaled-object", "namespace": "keda", "HPA.Namespace": "keda", "HPA.Name": "keda-hpa-kedaloganalytics-abc-scaled-object"}
1.6450973719716609e+09  INFO    controller.scaledobject Reconciling ScaledObject    {"reconciler group": "keda.sh", "reconciler kind": "ScaledObject", "name": "kedaloganalytics-abc-scaled-object", "namespace": "keda"}
1.6450973719895387e+09  INFO    controller.scaledobject Updated HPA according to ScaledObject       {"reconciler group": "keda.sh", "reconciler kind": "ScaledObject", "name": "kedaloganalytics-abc-scaled-object", "namespace": "keda", "HPA.Namespace": "keda", "HPA.Name": "keda-hpa-kedaloganalytics-abc-scaled-object"}
```

### KEDA Version

2.6.0

### Kubernetes Version

1.20

### Platform

Microsoft Azure

### Scaler Details

Azure Log Analytics

### Anything else?

Trigger Authentication: 
```
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: loganalytics-tauth
spec:
  podIdentity:
    provider: azure
```

**Comment by zroubalik** [comment]
See this: https://github.com/kedacore/keda/issues/2647#issuecomment-1041284067

It should help with the problem:) If not please reopen this.
