### ISSUE TITLE
Add Clarifying Documentation for Kafka Samples

### ISSUE THREAD

**Issue by izzymsft** [kedacore/keda#270]
Sometimes, at first glance users have have the impression that the tutorial is intended to scale the kafka brokers as more messages arrive. We need to clarify this in the objective section of the sample tutorial.

The instruction on installing the Kafka cluster via Helm could also be updated to explain the purpose of the different components of the Kafka cluster installed via Helm.

**Comment by izzymsft** [comment]
@jeffhollan @asavaritayal, I have submitted a pull request for this in the other repo.

https://github.com/kedacore/sample-python-kafka-azure-function/pull/2

What is the process for reviewing and merging it into the docs?

**Comment by asavaritayal** [comment]
Adding @anirudhgarg and @priyaananthasankar to review.

**Comment by priyaananthasankar** [comment]
Reviewed and merged PR with README changes: https://github.com/kedacore/sample-python-kafka-azure-function/pull/2

**Comment by tomkerkhove** [comment]
Can we close this one @priyaananthasankar @izzymsft ?

**Comment by izzymsft** [comment]
@tomkerkhove sure we can close it
