### ISSUE TITLE
Separate CRD manifest

### ISSUE THREAD

**Issue by ishioni** [kedacore/keda#2726]
### Proposal

I would like a separate CRD-only yaml to deploy CRDs tak keda uses

### Use-Case

I manage my cluster with flux, using their helmrelease CRDs and kustomize. This works fine but on the condition that CRDs are deployed on a separate step before the actual helm release. This is to combat the fact that helm releases in a kustomization step are run in parallel, and if any of them include keda resources, they will obviously fail until keda itself is installed. 

Installing only the CRDs in a separate step neatly fixes this. Most projects that use CRDs that I've encountered (cert-manager, tigera) offer separate CRD yamls knowing that helm-managed CRDs are iffy

**Comment by tomkerkhove** [comment]
Would you prefer to have them as a YAML file in that case?

**Comment by ishioni** [comment]
Yes, that would be ideal

**Comment by tomkerkhove** [comment]
Any thoughts on this @zroubalik?

**Comment by zroubalik** [comment]
Fine for me, the CRDs are already part of the big `keda-2.X.X.yaml` (eg. https://github.com/kedacore/keda/releases/download/v2.6.1/keda-2.6.1.yaml), we can release just CRDs next to it.

The release is being done here: https://github.com/kedacore/keda/blob/8c857512439cbbbc305f017c21932bde2f59eb2a/.github/workflows/release-build.yml#L57-L60

@ishioni are you willing to contribute this?

**Comment by dmendres** [comment]
We have another use case. We'd like conditional deployment of the KEDA resources from a template (e.g. templates/keda.yaml) but Helm 3.x must process the CRDs in advance. We don't need conditional deployment of the CRDs.
