### ISSUE TITLE
Migrate e2e tests to Go

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda#2737]
Migrate e2e tests to Go instead of typescript to standardize one one language.

We should use a phased approach where we migrate one scaler and run the new approach next to the current one to verify the setup.

New scalers should be in Go and then gradually migrate old tests over. 

- [x] https://github.com/kedacore/keda/issues/3224
- [x] https://github.com/kedacore/keda/issues/3225
- [x] https://github.com/kedacore/keda/issues/3226
- [x] #3173
- [x] https://github.com/kedacore/keda/issues/3227
- [x] #3171
- [x] #3172
- [x] https://github.com/kedacore/keda/issues/3228
- [x] https://github.com/kedacore/keda/issues/3229
- [x] https://github.com/kedacore/keda/issues/3257
- [x] https://github.com/kedacore/keda/issues/3258
- [x] https://github.com/kedacore/keda/issues/3259
- [x] https://github.com/kedacore/keda/issues/3223
- [x] https://github.com/kedacore/keda/issues/3230
- [x] https://github.com/kedacore/keda/issues/3231
- [x] https://github.com/kedacore/keda/issues/3217
- [x] #3169
- [x] https://github.com/kedacore/keda/issues/3232
- [x] https://github.com/kedacore/keda/issues/3233
- [x] #3175
- [x] #3174
- [x] https://github.com/kedacore/keda/issues/3234
- [x] https://github.com/kedacore/keda/issues/3235
- [x] https://github.com/kedacore/keda/issues/3236
- [x] https://github.com/kedacore/keda/issues/3237
- [x] https://github.com/kedacore/keda/issues/3238
- [x] https://github.com/kedacore/keda/issues/3239
- [x] #3170
- [x] https://github.com/kedacore/keda/issues/3240
- [x] https://github.com/kedacore/keda/issues/3241
- [x] https://github.com/kedacore/keda/issues/3242
- [x] https://github.com/kedacore/keda/issues/3243
- [x] https://github.com/kedacore/keda/issues/3244
- [x] https://github.com/kedacore/keda/issues/3245
- [x] #3176
- [x] https://github.com/kedacore/keda/issues/3246
- [x] https://github.com/kedacore/keda/issues/3247
- [x] https://github.com/kedacore/keda/issues/3248
- [x] https://github.com/kedacore/keda/issues/3249
- [x] https://github.com/kedacore/keda/issues/3250
- [x] https://github.com/kedacore/keda/issues/3251
- [x] https://github.com/kedacore/keda/issues/3252
- [x] https://github.com/kedacore/keda/issues/3253
- [x] https://github.com/kedacore/keda/issues/3254
- [x] https://github.com/kedacore/keda/issues/3256
- [x] https://github.com/kedacore/keda/issues/3260
- [ ] https://github.com/kedacore/keda/issues/3435
- [x] #3436

**Comment by tomkerkhove** [comment]
Thoughts @kedacore/keda-core-contributors?

**Comment by JorTurFer** [comment]
There is not an icon to reflect how much I agree this proposal 😁😁

**Comment by v-shenoy** [comment]
Bumping this issue. I think this switch would be highly beneficial and work on it should get started. There's no need for a project that's written entirely in Go, to have its e2e tests written in TypeScript. The more we delay this, the tougher it's going to get with more scalers and their typescript tests being added.

**Comment by tomkerkhove** [comment]
💯, we just need to find somebody who wants to go through it 😅

**Comment by v-shenoy** [comment]
First of all, there's the discussion of which Go testing framework to be used, and with which assertion framework. Currently, there's a bit of inconsistency with some unit tests using `testify/assert`, while some are using another, while some are using manual comparisons with the default testing framework.

Once the decision is finalized, a little bit of work would also be required to bring existing tests to parity. 

As for the e2e tests themselves, we should probably have an umbrella thread for e2e tests similar to the one already existing, and start accepting new tests only in Go.

**Comment by zroubalik** [comment]
@v-shenoy that would be great! Please sync with @JorTurFer.

It doesn't have to be over complex, but we should have some general library with `wait/deploy/watch/log` methods.

**Comment by JorTurFer** [comment]
I did some tries, but nothing really important, if you are willing to contribute with this, I'll not be who blocks you xD
My only concern/request is that please, use a tool/framework that can be debuggable please 🙏 . 
Developing e2e test with npx ava printing logs is a pain

**Comment by v-shenoy** [comment]
I'll send a draft PR with one test tomorrow for reference.

**Comment by tomkerkhove** [comment]
Thanks a ton @v-shenoy!

**Comment by v-shenoy** [comment]
Okay, I created a few. But I now realize that there's too many of them. What's the smoothest way here?

**Comment by v-shenoy** [comment]
> Please don't forget to update the contribution guide as well;

`tests/READM.md` has already been updated with basic guide about tests in `Go`.

**Comment by Ritikaa96** [comment]
Hi @tomkerkhove Seems like the list doesn't have Cron scaler.

**Comment by Ritikaa96** [comment]
Added #3217 for the same if it's alright.

**Comment by tomkerkhove** [comment]
Updated, thanks!

**Comment by tomkerkhove** [comment]
@v-shenoy Were you going to open issues for all of them?

**Comment by v-shenoy** [comment]
@tomkerkhove Could you also pin this issue along with the other one for e2e tests?

**Comment by tomkerkhove** [comment]
> > @v-shenoy Were you going to open issues for all of them?
> 
> I was until I realized there's just way too many. Going forward we can either just use this main thread or create an issue when someone takes up a specific scaler

Unfortunately, we need to have issues for all of them in order to have a representative backlog. I'll create all the missing issues later today.

**Comment by tomkerkhove** [comment]
Done

**Comment by v-shenoy** [comment]
Halfway there, phew!

**Comment by tomkerkhove** [comment]
Nice progress on this!

**Comment by JorTurFer** [comment]
Redis is almost done, I have the PR opened

**Comment by JorTurFer** [comment]
@goku321 , do you know about Redis Stream in general? Could I ask if you could answer [this](https://github.com/kedacore/keda/pull/3415#issuecomment-1193181474)?

**Comment by v-shenoy** [comment]
Took a while, but we got there :)

**Comment by tomkerkhove** [comment]
Congrats and thanks to everyone who has contributed to this! 🎉
