### ISSUE TITLE
Cron Scaler should maintain a original replicas when not reach the time window

### ISSUE THREAD

**Issue by bamboo12366** [kedacore/keda#2769]
### Proposal

when not reaching the time window(startTime<currentTime<endTime), the cron scaler is Inactive, the replicas counts rely on min or idle replicas(depends on two value comparison). 

Can we just maintain a field called originalReplicas or something else in the meta information, to maintain this replicas before the time window, and scaler become active.

### Use-Case

Here is our use case:
We want to scale up the replicas when the time come, in the other time, we should maintain the replicas(define by user) to support normal traffic. And we also have upper logic to own the scalerObject, there are other triggers also includes(like prometheus, utility, redis). 

If we control the replicas in the normal time by using min/idle fields, which will be inconsistent with other trigger logic. 

So if this field can lays in cron's metadata, the workflow of all triggers should be the same.

**Comment by JorTurFer** [comment]
Hi @bamboo12366 
Could be an option just setting another trigger with the opposite cron for the min replicas? I mean, right now cron scaler only works during the activation time, but if you have another cron trigger covering the period when the first cron trigger is not active, you have the same behavior

**Comment by bamboo12366** [comment]
hey @JorTurFer 

Sorry for the late reply.
Sounds tricky but good to me, thank you for the help!

**Comment by zroubalik** [comment]
Q answered
