### ISSUE TITLE
Update all needed scalers to use `int64` instead of `float64`

### ISSUE THREAD

**Issue by JorTurFer** [kedacore/keda#2790]
### Proposal

The HPA doesn't allow the usage of `float64` but there are some scalers where KEDA allows that, and basically KEDA cast those values into `int64`. This could be confusing and there is a risk of losing information like happened to [this user](https://github.com/kedacore/keda/issues/2760#issuecomment-1075102663).

We should review all the scalers and change the to use `int64` values for the threshold and also internally for the returning metrics. This could be not enough because the upstream can still return `float64` (missing information during the cast), so this situation should be explained also in the docs for being clearest as possible. Majority of the cases could be solved multiplying * 100 the value in the query and taking that into account for the threshold.

- [ ] Selenium Grid Scaler (just internal represenation - ie no breaking change)
- [ ] Metrics API Scaler 
- [ ] AWS CloudWatch Scaler
- [ ] Huawei Cloudeye Scaler
- [ ] InfluxDB Scaler
- [ ] OpenStack Metrics Scaler

**Comment by zroubalik** [comment]
Not finished yet, we need to fix the scalers listed in the issue description -> this might be potentially user breaking, since the fields directly (in trigger spec) expects float.

**Comment by JorTurFer** [comment]
I close this because KEDA since now, KEDA supports `mili` units so float64 target values make sense
