### ISSUE TITLE
Add e2e test for Metric API Scaler

### ISSUE THREAD

**Issue by JorTurFer** [kedacore/keda#2791]
Add e2e test for Metric API Scaler

**Comment by adborroto** [comment]
I can take a look at this one.

**Comment by JorTurFer** [comment]
Nice! I wanted to do it but tbh, I don't have enough time.
Do you plan to create any new image for the rest api server? In case of yes, please open a PR in https://github.com/kedacore/test-tools adding the image.

**Comment by adborroto** [comment]
PR open [2893](https://github.com/kedacore/keda/pull/2893)
