### ISSUE TITLE
v2.6.1 release notes contain invalid link

### ISSUE THREAD

**Issue by chalin** [kedacore/keda#2809]
Visit https://github.com/kedacore/keda/releases/tag/v2.6.1 and you'll notice the following issue:

- The link to the docs, https://keda.sh/docs/INSERT-CORRECT-VERSION/deploy/, is invalid.
  This is the [second of the top 404s of the website](https://github.com/kedacore/keda-docs/issues/692).
- The opening text is missing the version (probably because the version is there in the text but contained between angle brackets):
  > We are happy to release KEDA 🎉
  Should read
  > We are happy to release KEDA 2.6.1 🎉

**Comment by zroubalik** [comment]
Fixed, thanks!
