### ISSUE TITLE
v2.6.0 release notes contain invalid link

### ISSUE THREAD

**Issue by chalin** [kedacore/keda#2810]
Visit https://github.com/kedacore/keda/releases/tag/v2.6.0 and you'll notice the following issue:

- The link to the docs, https://keda.sh/docs/INSERT-CORRECT-VERSION/deploy/, is invalid.
  This is the [second of the top 404s of the website](https://github.com/kedacore/keda-docs/issues/692).

**Comment by zroubalik** [comment]
Fixed, thanks!
