### ISSUE TITLE
Support consumer group lag for Redis Streams scaler

### ISSUE THREAD

**Issue by thielepaul** [kedacore/keda#2819]
### Proposal

Currently the Redis Streams scaler only supports the "Pending Entries List" as a metric.
I think it would be more useful to scale based on the lag of a consumer group as described in the Redis docs:

> **lag:** the number of entries in the stream that are still waiting to be delivered to the group’s consumers, or a NULL when that number can’t be determined.
https://redis.io/commands/xinfo-groups/

### Use-Case

My application always reads one messsage from the stream, then acknowledges this message and reads another message. That way the pending count is always <= the number of consumers and, thus, cannot be used as a metric for scaling.

The lag on the other hand will grow, if more messages are written to the stream than the application can consume, so it would be the perfect metric for scaling.

**Comment by zroubalik** [comment]
Will to contribute this?
