### ISSUE TITLE
After update of an AKS cluster, Keda is unable to connect to the Kubernetes API

### ISSUE THREAD

**Issue by Evantage-WS** [kedacore/keda#2838]
### Report

After updating the k8s cluster to a new version (from 1.22.5 to 1.22.6), the keda-metrics pod is unable to connect to the kubernets api. The debug log shows an 

```
I0328 14:44:00.734194       1 main.go:156] keda_metrics_adapter "msg"="KEDA Version: 2.6.1"  
I0328 14:44:00.734467       1 main.go:157] keda_metrics_adapter "msg"="KEDA Commit: efca71d6bc770408468a9e1a4b3984f7136c0967"  
I0328 14:44:00.734553       1 main.go:158] keda_metrics_adapter "msg"="Go Version: go1.17.3"  
I0328 14:44:00.734626       1 main.go:159] keda_metrics_adapter "msg"="Go OS/Arch: linux/amd64"  
I0328 14:44:00.742713       1 with_retry.go:171] Got a Retry-After 1s response for attempt 1 to https://10.0.0.1:443/api?timeout=32s
I0328 14:44:01.745991       1 with_retry.go:171] Got a Retry-After 1s response for attempt 2 to https://10.0.0.1:443/api?timeout=32s
I0328 14:44:02.749603       1 with_retry.go:171] Got a Retry-After 1s response for attempt 3 to https://10.0.0.1:443/api?timeout=32s
I0328 14:44:03.754102       1 with_retry.go:171] Got a Retry-After 1s response for attempt 4 to https://10.0.0.1:443/api?timeout=32s
I0328 14:44:04.757609       1 with_retry.go:171] Got a Retry-After 1s response for attempt 5 to https://10.0.0.1:443/api?timeout=32s
I0328 14:44:05.761270       1 with_retry.go:171] Got a Retry-After 1s response for attempt 6 to https://10.0.0.1:443/api?timeout=32s
I0328 14:44:06.764257       1 with_retry.go:171] Got a Retry-After 1s response for attempt 7 to https://10.0.0.1:443/api?timeout=32s
I0328 14:44:07.767366       1 with_retry.go:171] Got a Retry-After 1s response for attempt 8 to https://10.0.0.1:443/api?timeout=32s
I0328 14:44:08.770036       1 with_retry.go:171] Got a Retry-After 1s response for attempt 9 to https://10.0.0.1:443/api?timeout=32s
I0328 14:44:09.773508       1 with_retry.go:171] Got a Retry-After 1s response for attempt 10 to https://10.0.0.1:443/api?timeout=32s
E0328 14:44:10.776583       1 main.go:100] keda_metrics_adapter "msg"="unable to construct new client" "error"="Get \"https://10.0.0.1:443/api?timeout=32s\": EOF"  
E0328 14:44:10.777143       1 main.go:218] keda_metrics_adapter "msg"="making provider" "error"="unable to construct new client (Get \"https://10.0.0.1:443/api?timeout=32s\": EOF)"  
E0328 14:44:10.777175       1 main.go:177] keda_metrics_adapter "msg"="unable to run external metrics adapter" "error"="unable to construct new client (Get \"https://10.0.0.1:443/api?timeout=32s\": EOF)"
I0328 14:44:56.589822       1 main.go:156] keda_metrics_adapter "msg"="KEDA Version: 2.6.1"  
I0328 14:44:56.589880       1 main.go:157] keda_metrics_adapter "msg"="KEDA Commit: efca71d6bc770408468a9e1a4b3984f7136c0967"  
I0328 14:44:56.589887       1 main.go:158] keda_metrics_adapter "msg"="Go Version: go1.17.3"  
I0328 14:44:56.589892       1 main.go:159] keda_metrics_adapter "msg"="Go OS/Arch: linux/amd64"  
I0328 14:44:56.593960       1 with_retry.go:171] Got a Retry-After 1s response for attempt 1 to https://10.0.0.1:443/api?timeout=32s
I0328 14:44:57.596947       1 with_retry.go:171] Got a Retry-After 1s response for attempt 2 to https://10.0.0.1:443/api?timeout=32s
I0328 14:44:58.600431       1 with_retry.go:171] Got a Retry-After 1s response for attempt 3 to https://10.0.0.1:443/api?timeout=32s
I0328 14:44:59.604105       1 with_retry.go:171] Got a Retry-After 1s response for attempt 4 to https://10.0.0.1:443/api?timeout=32s
```

We also completely removed keda, including crd's and reinstalled keda, but this error remains. It seems that the Keda operator is depended on the metrics pod. 

### Expected Behavior

Able to connect and get Keda up and running

### Actual Behavior

Error in the log, restarting pod(s)

### Steps to Reproduce the Problem

1. Update an AKS cluster
2. Check the pods
3. Check the logs

### Logs from KEDA operator (Debug)

```
1.64847757568208e+09	ERROR	Failed to get API Group-Resources	{"error": "Get \"https://10.0.0.1:443/api?timeout=32s\": EOF"}
sigs.k8s.io/controller-runtime/pkg/cluster.New
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/cluster/cluster.go:160
sigs.k8s.io/controller-runtime/pkg/manager.New
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/manager/manager.go:313
main.main
	/workspace/main.go:86
runtime.main
	/usr/local/go/src/runtime/proc.go:255
1.6484775756822596e+09	ERROR	setup	unable to start manager	{"error": "Get \"https://10.0.0.1:443/api?timeout=32s\": EOF"}
main.main
	/workspace/main.go:96
runtime.main
	/usr/local/go/src/runtime/proc.go:255
```

### KEDA Version

2.6.1

### Kubernetes Version

1.22

### Platform

Microsoft Azure

### Scaler Details

azure-pipelines

**Comment by jeffhollan** [comment]
Can you check and see if another external metrics adapter (or if any external metrics adapter) is installed? `kubectl get apiservice | grep external.metrics` - may be related to the issue that only one can be configured per cluster #470

**Comment by Evantage-WS** [comment]
Hi @jeffhollan,

Thanks, this is the output from the kubectl command, so just one is running:
```
v1beta1.external.metrics.k8s.io        keda/keda-metrics-apiserver   False (MissingEndpoints)   15h
```

That missing endpoint concerns me.

**Comment by SushmithaVReddy** [comment]
Looking in to this.

**Comment by SushmithaVReddy** [comment]
@Evantage-WS 

I tried replicating this issue but failed. Metrics and operator both seem to be healthy. Below is my precise versions info

KEDA Version: 2.7.1
Go Version: go1.17.9
Kubernetes 1.22  {"version": "v1.22.6"}

I understand you've mentioned you've updated aks cluster's version from 1.22.5 to 1.22.6. Does the same issue occur if your cluster is created directly with 1.22.6 version?

**Comment by Evantage-WS** [comment]
I have raised this issue over a month ago, so we removed this cluster and reïnstalled it. From that moment on it is working again. Because of the lack of support on Keda we are considering another solution.

**Comment by tomkerkhove** [comment]
For what it's worth, it's an open source product and this felt through the cracks as we have a lot of request. Feel free to nudge us again in the future.

**Comment by Evantage-WS** [comment]
I really understand this, but it has been 6 weeks between the answers................................

**Comment by tomkerkhove** [comment]
Well it was opened on March 28 and last reply was on 29th, feel free to bump next time because we get a lot of requests and sometimes things fall through the cracks :)

Sorry.

**Comment by tomkerkhove** [comment]
If you are on Azure and want support, you can use the AKS add-on for KEDA: https://docs.microsoft.com/en-us/azure/aks/keda-about

**Comment by rarampasso** [comment]
Hello,

I recently had the same symptom when upgrading to AKS 1.22.6 version.

With that I'm having problems with keda, I'm not able to remove it also due to v1beta1.external.metrics.k8s.io

**Erro.......**

ramps@NT0876526MT1580:~$ helm uninstall keda -n keda
Error: uninstallation completed with 1 error(s): unable to build kubernetes objects for delete: resource mapping not found for name: "v1beta1.external.metrics.k8s.io" namespace: "" from "": no matches for kind "APIService" in version "apiregistration.k8s.io/v1beta1"
ensure CRDs are installed first
ramps@NT0876526MT1580:~$ kubectl get apiservice | grep external.metrics
v1beta1.external.metrics.k8s.io        keda/keda-operator-metrics-apiserver   True        690d

How could I get around this situation without failing to break anything else?

How can I remove keda using helm and try to do a new clean and fresh install?

**Comment by evenh** [comment]
After upgrading from K8s 1.21 to 1.22.11 I observed the following error when trying to run a third-party tool locally (popeye):
> unable to retrieve the complete list of server APIs: external.metrics.k8s.io/v1beta1: the server is currently unable to handle the request

After digging around I came up with the following `NetworkPolicy` which resolved my problem.
```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: keda-metrics-adapter-ingress
  namespace: my-ns
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          control-plane: "true"
          kubernetes.io/metadata.name: kube-system
      podSelector:
        matchLabels:
          component: tunnel
  podSelector:
    matchLabels:
      app.kubernetes.io/component: metrics-adapter
      app.kubernetes.io/name: keda
  policyTypes:
  - Ingress
```

I'm not sure if this helps the issue reported, but I thought I'd share so it might help someone.
