### ISSUE TITLE
Add Azure Data Explorer e2e tests with active directory credentials.

### ISSUE THREAD

**Issue by v-shenoy** [kedacore/keda#2841]
Relates to #2770, [#2882](https://github.com/kedacore/keda/pull/2822).

**Comment by tomkerkhove** [comment]
Make sure to check https://github.com/kedacore/keda/pull/2822#pullrequestreview-925753333 as we need https://github.com/kedacore/keda/pull/2741 instead of #2882

/cc @kedacore/keda-maintainers

**Comment by v-shenoy** [comment]
@tomkerkhove I wasn't planning on enabling the pod identity tests here. Instead of having all e2e tests disabled for Data Explorer, I was going to add a condition to disable only the ones using pod identity (as I can see there is already one using AD credentials). This ensures that we at least have some tests running for Data Explorer that we can check on PRs. The condition can then be removed once #2741 is merged.

**Comment by v-shenoy** [comment]
Should I wait until #2741 is merged before working on this?

**Comment by tomkerkhove** [comment]
> @tomkerkhove I wasn't planning on enabling the pod identity tests here. Instead of having all e2e tests disabled for Data Explorer, I was going to add a condition to disable only the ones using pod identity (as I can see there is already one using AD credentials). This ensures that we at least have some tests running for Data Explorer that we can check on PRs. The condition can then be removed once #2741 is merged.

This sounds like a good plan to me!
