### ISSUE TITLE
Add e2e test for Azure Key Vault

### ISSUE THREAD

**Issue by JorTurFer** [kedacore/keda#2843]
### Proposal

[https://github.com/kedacore/keda/tree/main/tests](https://github.com/kedacore/keda/tree/main/tests?rgh-link-date=2021-10-26T19%3A51%3A53Z)

**Comment by v-shenoy** [comment]
There is already a key vault test that with the azure queue scaler.

**Comment by JorTurFer** [comment]
you're right!
Thanks for the reminder ❤️
