### ISSUE TITLE
Support configurable TLS Version for Metrics Server (Adapter)

### ISSUE THREAD

**Issue by dalgibbard** [kedacore/keda#2850]
### Proposal

Ideally, the Keda Metrics Server should allow for configuring the Min TLS Version, so that users in stricter security environments can override it to be TLS1.3 only.

### Use-Case

The default TLS1.2 implementation in the k8s apiserver includes less secure ciphers, such as 64bit CBC ciphers, 3DES etc.
In our environment, these are unacceptable, and since there's concerns that TLS1.3 everywhere might break things, putting it behind an environment variable allows the best of both worlds.

**Comment by dalgibbard** [comment]
OK I'm an idiot; turns out you can just pass an extra arg of ```--tls-min-version=VersionTLS13``` and this happens. Closing!

**Comment by zroubalik** [comment]
@dalgibbard could you please open documentation PR to explain this setting? I guess it might be beneficial for others as well.
Probably a new section here: https://keda.sh/docs/2.6/operate/cluster/

**Comment by zroubalik** [comment]
Btw is this config really interesting only for Metrics Adapter? What about the KEDA Operator Deployment?

**Comment by dalgibbard** [comment]
> @dalgibbard could you please open documentation PR to explain this setting? I guess it might be beneficial for others as well. Probably a new section here: https://keda.sh/docs/2.6/operate/cluster/

Will look to do this on Monday most likely

**Comment by dalgibbard** [comment]
> Btw is this config really interesting only for Metrics Adapter? What about the KEDA Operator Deployment?

I checked the main Keda deployment, only listens on HTTP 8080 (and internally on 8081 for healthchecks), so TLS doesn't apply there.

**Comment by zroubalik** [comment]
ACK, thanks!

**Comment by zroubalik** [comment]
The documentation is still missing on this.

**Comment by dalgibbard** [comment]
Agreed; I still plan to do this.

**Comment by JorTurFer** [comment]
I close this as it's already supported in v2.10
https://keda.sh/docs/2.10/operate/cluster/#http-tls-min-version

**Comment by rmrfroot** [comment]
> I close this as it's already supported in v2.10 https://keda.sh/docs/2.10/operate/cluster/#http-tls-min-version

Metrics Server doesn't respect the KEDA_HTTP_MIN_TLS_VERSION variable. 
But setting an extra arg --tls-min-version=VersionTLS13 works like a charm.

**Comment by JorTurFer** [comment]
> > I close this as it's already supported in v2.10 [keda.sh/docs/2.10/operate/cluster/#http-tls-min-version](https://keda.sh/docs/2.10/operate/cluster/#http-tls-min-version)
> 
> Metrics Server doesn't respect the KEDA_HTTP_MIN_TLS_VERSION variable. But setting an extra arg --tls-min-version=VersionTLS13 works like a charm.

What KEDA version are you using? This feature has been introduced in KEDA v2.10

**Comment by rmrfroot** [comment]
> > > I close this as it's already supported in v2.10 [keda.sh/docs/2.10/operate/cluster/#http-tls-min-version](https://keda.sh/docs/2.10/operate/cluster/#http-tls-min-version)
> > 
> > 
> > Metrics Server doesn't respect the KEDA_HTTP_MIN_TLS_VERSION variable. But setting an extra arg --tls-min-version=VersionTLS13 works like a charm.
> 
> What KEDA version are you using? This feature has been introduced in KEDA v2.10

appVersion: 2.10.1

**Comment by JorTurFer** [comment]
In that case, I'd say that the env is honored because all the http connections with TLS (where the httpClient can be provided by us, some SDKs don't allow it) use this code:
https://github.com/kedacore/keda/blob/29e14294348e1f10fd316f98c0b0f787041ed4b1/pkg/util/tls_config.go#L89-L108

How have you checked the supported TLS? I'd like to check it to solve it
