### ISSUE TITLE
 The AWS SQS Queue scaler's documentation should be more specific about which SQS actions are required

### ISSUE THREAD

**Issue by AndreyMatveyev** [kedacore/keda#2852]
### Proposal

The AWS SQS Queue scaler's documentation states: "_The user will need access to read properties from the specified AWS SQS queue._"
It would be nice to have the exact list of required SQS actions needed in the AWS policy.

For example:
"_The user will need access to read properties from the specified AWS SQS queue._ The AWS policy must allow action sqs:GetQueueAttributes against the queue subject to the scaler's monitoring."

### Use-Case

Users have to configure the AWS policy, and they need to know the exact list of required SQS actions by the scaler.

### Anything else?

This suggestion applies to the documentation for other scalers that monitor different types of AWS resources.

**Comment by JorTurFer** [comment]
Hi @AndreyMatveyev 
Sorry for the slow response. :( 
Are you willing to contribute with that change? We are not experts on AWS, so if you feel that the documentation is poor and you have an idea about how to solve it, we will be happy if you contribute with it.

The change in this case should be done in the [docs repo](https://github.com/kedacore/keda-docs).
