### ISSUE TITLE
Busy pods got terminated in mid-work in Kubernetes With KEDA v2

### ISSUE THREAD

**Issue by jitendrabehera2** [kedacore/keda#2900]
### Discussed in https://github.com/kedacore/keda/discussions/2899

<div type='discussions-op-text'>

<sup>Originally posted by **jitendrabehera2** April 12, 2022</sup>
Hello Team,
Recently I have done scaling based on an Azure Service Bus Queue then we have identified a serious issue: busy pods got terminated during scale-down. As the number of messages in the queue decreases, the HPA automatically shuts down some of the pods. Since the HPA does not know which pods are currently doing actual work, it terminated pods in mid-work and forced them to restart. Please do help on this.

**Excepted :**
**It Should wait till the process complete, once process completed then it should terminated.**</div>

**Comment by zroubalik** [comment]
Not an issue.
