### ISSUE TITLE
How to handle long running execution when implemented scaling with Keda scaledobject 

### ISSUE THREAD

**Issue by rrathord1885** [kedacore/keda#2901]
### Report

Hi,
I have done scaling on basis of azure service bus queue count with Keda scaled object and its working fine. but how we can handle this scenario.  Imagine a deployment triggers on a azure service bus queue message. Each message takes 30 minutes to process. It’s possible that if many queue messages arrive, KEDA will help drive scaling out to many replicas - let’s say 4. Now the HPA makes a decision to scale down from 4 replicas to 2. There is no way to control which of the 2 replicas get terminated to scale down. That means the HPA may attempt to terminate a replica that is 15 minutes into processing a 30 minutes queue message.
so how we can graceful terminate the pod ?

### Expected Behavior

Message is not processed . because its taking long time .Due to pod is terminated on basis service bus queue count. 

### Actual Behavior

Message should be processed.

### Steps to Reproduce the Problem

Create Keda scaling, deployment will trigger on basis of service bus count
New Replica will be created.
Scale down triggered on basis queue count.
but replicas are still busy . so how we can graceful scale down? 

### Logs from KEDA operator

```
example
```

### Scaler Details

Azure Service bus

**Comment by amirschw** [comment]
This section of the docs addresses the exact same scenario and suggests two ways to handle it: https://keda.sh/docs/latest/concepts/scaling-deployments/#long-running-executions
