### ISSUE TITLE
Kafka Scaler not scaling up

### ISSUE THREAD

**Issue by ajames-branch** [kedacore/keda#2908]
### Report

 I am having trouble with keda kafka scaler (version 1.5)
 
Number of partitions for topic `tetopic` is 64.
`lagThreshold` is set to 3000

lagThreshold: "3000"

`keda-operator` debug log for the topic:
`{"level":"debug","ts":1649873141.4286203,"logger":"kafka_scaler","msg":"Group tetopic-consumer has a lag of 447478 for topic tetopic and partition 0\n"}
{"level":"debug","ts":1649873201.4540296,"logger":"kafka_scaler","msg":"Group tetopic-consumer has a lag of 449053 for topic tetopic and partition 0\n"}
{"level":"debug","ts":1649873261.4787436,"logger":"kafka_scaler","msg":"Group tetopic-consumer has a lag of 450576 for topic tetopic and partition 0\n"}
{"level":"debug","ts":1649873321.5027044,"logger":"kafka_scaler","msg":"Group tetopic-consumer has a lag of 452101 for topic tetopic and partition 0\n"}
{"level":"debug","ts":1649873381.5300736,"logger":"kafka_scaler","msg":"Group tetopic-consumer has a lag of 453588 for topic tetopic and partition 0\n"}
{"level":"debug","ts":1649873441.554117,"logger":"kafka_scaler","msg":"Group tetopic-consumer has a lag of 455040 for topic tetopic and partition 0\n"}`

The kafka offset lag is - 450K+ (as you can see from operator logs). Interestingly only 1 partition is lagging.
We have 63 pods running. The scaler seems stuck at 63 pods, while I expect it to scale upto max (64).

`Name:                                     keda-hpa-te-deploy
Namespace:                                production
Labels:                                   app.kubernetes.io/managed-by=keda-operator
                                          app.kubernetes.io/name=keda-hpa-te-deploy
                                          app.kubernetes.io/part-of=te-deploy-kafka-scaledobject
                                          app.kubernetes.io/version=1.5.0
Annotations:                              <none>
CreationTimestamp:                        Mon, 11 Apr 2022 13:24:53 -0700
Reference:                                Deployment/te-deploy
Metrics:                                  ( current / target )
  "lagThreshold" (target average value):  3047620m / 3k
Min replicas:                             32
Max replicas:                             100
Conditions:
  Type            Status  Reason              Message
  ----            ------  ------              -------
  AbleToScale     True    ReadyForNewScale    recommended size matches current size
  ScalingActive   True    ValidMetricFound    the HPA was able to successfully calculate a replica count from external metric lagThreshold(&LabelSelector{MatchLabels:map[string]string{deploymentName: te-deploy,},MatchExpressions:[],})
  ScalingLimited  False   DesiredWithinRange  the desired count is within the acceptable range
`

  

### Expected Behavior

Expect to scale to max replicas (64)

### Actual Behavior

Scaling stuck at 63 pods

### Steps to Reproduce the Problem

1.
2.
3.

### Logs from KEDA operator

```
{"level":"debug","ts":1649873141.4286203,"logger":"kafka_scaler","msg":"Group tetopic-consumer has a lag of 447478 for topic tetopic and partition 0\n"}
{"level":"debug","ts":1649873201.4540296,"logger":"kafka_scaler","msg":"Group tetopic-consumer has a lag of 449053 for topic tetopic and partition 0\n"}
{"level":"debug","ts":1649873261.4787436,"logger":"kafka_scaler","msg":"Group tetopic-consumer has a lag of 450576 for topic tetopic and partition 0\n"}
{"level":"debug","ts":1649873321.5027044,"logger":"kafka_scaler","msg":"Group tetopic-consumer has a lag of 452101 for topic tetopic and partition 0\n"}
{"level":"debug","ts":1649873381.5300736,"logger":"kafka_scaler","msg":"Group tetopic-consumer has a lag of 453588 for topic tetopic and partition 0\n"}
{"level":"debug","ts":1649873441.554117,"logger":"kafka_scaler","msg":"Group tetopic-consumer has a lag of 455040 for topic tetopic and partition 0\n"}
```

### KEDA Version

1.5.0

### Kubernetes Version

< 1.16

### Platform

Amazon Web Services

### Scaler Details

Kafka

**Comment by ajames-branch** [comment]
![Screen Shot 2022-04-13 at 11 24 18 AM](https://user-images.githubusercontent.com/48938754/163248112-9fb0b04e-c6fa-495a-bce8-0ec7b8db882f.png)

**Comment by ajames-branch** [comment]
![Screen Shot 2022-04-13 at 11 32 52 AM](https://user-images.githubusercontent.com/48938754/163248296-354f1070-d103-4195-ac54-ecb05b043e8f.png)

**Comment by ajames-branch** [comment]
![Screen Shot 2022-04-13 at 11 42 04 AM](https://user-images.githubusercontent.com/48938754/163248491-8f6b63c7-793d-4ca9-b999-ef067b7e9a14.png)

**Comment by ajames-branch** [comment]
Could someone help understand what is happening here?

**Comment by ajames-branch** [comment]
Any help here is much appreciated. Is this a bug in the product?

**Comment by ajames-branch** [comment]
We are planning Keda for our env and this issue is blocking us. Any insight here is appreciated.

**Comment by zroubalik** [comment]
Hi, version 1.5 is pretty old. I'd definitely recommend you to update to latest 2.6.1 as we have done a plenty of improvements in Kafka scaler and KEDA in general.

**Comment by ajames-branch** [comment]
@zroubalik Thank you for the reply. However, this particular cluster is 1.15 K8 version. As per my understanding, latest KEDA version that supports this K8 version is 1.5. So we are stuck with it.

**Comment by zroubalik** [comment]
I see (even though I definitely not recommend you to use that old KEDA or k8s - think of security vulnerabilities), but I am not sure what could be wrong. I know there has been done a bunch of improvements on the lag calculation and offsets, hard to say sorry :(

What you can do is to try to build your KEDA release. But as you can see, the changes in Kafka scaler are quite heavy: https://github.com/kedacore/keda/compare/3692eca90897a5b5a226fbfe2f0ca72fab2be6ff...main#diff-03cf62956adcec86c0717723ab146472f0979221b0e5942a6e5460fa6d5e4f08

**Comment by lsolovey** [comment]
I have a theory on what's going on here. See this line in the HPA status:

`"lagThreshold" (target average value): 3047620m / 3k`

Since your topic has 64 partitions, KEDA metrics server artificially "limits" the lag on your topic at `64*3,000=192,000` to prevent scaling more than 64 replicas and having idle consumers.

Next, HPA looks at lag of 192,000 and calculates current average metric as `192,000 / 63 = 3,047.620`. 
This matches the value in your HPA status.

Next, HPA doesn't start 64th replica because by default it has 10% tolerance to the metric values. So the average metric should be higher than 3,300 to start 64th pod.  

See https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#algorithm-details

> The control plane skips any scaling action if the ratio is sufficiently close to 1.0 (within a globally-configurable tolerance, 0.1 by default).

It's an interesting problem. 

Another side question is - since your lag comes all from single partition, how starting 64th pod would help?
