### ISSUE TITLE
keda-metrics-adapter calling apiserver qps are quite high

### ISSUE THREAD

**Issue by bamboo12366** [kedacore/keda#2914]
### Report

we create arounds 200 scaleObjects in the cluster, the qps from keda-metrics-adapter to apiserver is quite high, which create burden to apiserver

![image](https://user-images.githubusercontent.com/38064424/163704382-0d09bfff-e4c9-4cc5-b5fd-cd5b119d29a4.png)

the code for listing here: https://github.com/kedacore/keda/blob/main/pkg/provider/provider.go#L90

### Expected Behavior

Not calling apiserver so frequently, should be done by reconcile by watching constantly

### Actual Behavior

Calling apiserver every time the metrics request to get the so resource

### Steps to Reproduce the Problem

large amounts of scaleObjectx

### KEDA Version

2.6.1

### Kubernetes Version

1.20

### Platform

Other

### Anything else?

1. maybe we can using the shared informer with scaledObject Controller, when get new so can get directly from informer cache
2. or create a shared cache between controller and provider

if you guys feel ok either way, I can give a try

**Comment by zroubalik** [comment]
Yeah, this is something that needs improvement, @bamboo12366 would be nice if you can try to tackle this. 

FYI there's already controller present in the MetricsAdapter (currently used for metricNames), so you might want to go this direction: https://github.com/kedacore/keda/blob/main/controllers/keda/metrics_adapter_controller.go

**Comment by zroubalik** [comment]
There might be even an easier solution, replace following section:
https://github.com/kedacore/keda/blob/99619e3a8b52dfa3e70a525c94b204dbf9e03028/pkg/provider/provider.go#L84-L95

with 
```go
...
	scaledObject := &kedav1alpha1.ScaledObject{}
	p.client.Get(ctx, namespaceNameParsedFromMetricSelector, scaledObject)
...
```

we should be able to parse ScaledObject.Name from a label `scaledobject.keda.sh/name` that is set on ScaledObject and most likely is part of the `metricSelector`.

It's definitely worth exploring.

**Comment by bamboo12366** [comment]
hey @zroubalik 

can I just using the manager.GetClient() and pass the client to the provider, thus the provider and scaledObject Controller are sharing the same informer cache together

something like 
`	
        mgr, err := ctrl.NewManager(ctrl.GetConfigOrDie(), ctrl.Options{
		Scheme:    scheme,
		Namespace: namespace,
	})
	if err != nil {
		return nil, nil, err
	}
	if err := runScaledObjectController(ctx, mgr, handler, logger, externalMetricsInfo, externalMetricsInfoLock, maxConcurrentReconciles, stopCh); err != nil {
		return nil, nil, err
	}
	
	return kedaprovider.NewProvider(ctx, logger, handler, mgr.GetClient(), namespace, externalMetricsInfo, externalMetricsInfoLock), stopCh, nil
	`

**Comment by zroubalik** [comment]
ScaledObject controller is running in KEDA Operator Pod, Provider in Metrics Server Pod.

**Comment by zroubalik** [comment]
The client for Metrics Server (thus provider) is setup here: https://github.com/kedacore/keda/blob/main/adapter/main.go

I happy to see any improvements on this side.

**Comment by bamboo12366** [comment]
yea, what trouble me is the Metrics Server pare.
I will create a PR work on this

**Comment by bamboo12366** [comment]
@zroubalik master, could you help me review on this https://github.com/kedacore/keda/pull/2922?
