### ISSUE TITLE
KEDA objects won't scale to 0 after live edit

### ISSUE THREAD

**Issue by matanr-orca** [kedacore/keda#2917]
### Report

When I use kubectl edit to edit the replica attribute to 0 it has no effect on the target deployment at all, at any other value it does affect it but if I change it to 0 it just does nothing and keeps the last state of the deployment.
I'm changing those values:
spec:
maxReplicaCount: 10
minReplicaCount: 3

### Expected Behavior

deployment will scale down to 0

### Actual Behavior

deployment keeps the last state

### Steps to Reproduce the Problem

1. deploy a scaled object
2. use kubectl edit to change min and max replica counts to 0

### KEDA Version

2.6.1

### Kubernetes Version

1.20

### Platform

Amazon Web Services

### Scaler Details

cloudwatch

### Anything else?

running on eks

**Comment by zroubalik** [comment]
Not a bug, because the deployment is managed by KEDA. It keeps the replicas on the specified count. If you wish to update replicas, you need to do it via ScaledObject.
