### ISSUE TITLE
Add documentation for aws cloudwatch

### ISSUE THREAD

**Issue by ageekymonk** [kedacore/keda#293]

**Comment by ageekymonk** [comment]
I would like to add the documentation, how do i edit / raise pr for doc ?

**Comment by anirudhgarg** [comment]
Please add the documentation here: https://github.com/kedacore/keda/tree/master/spec and submit a PR. We are requesting all scaler authors to add documentation and spec here instead of the wiki

**Comment by tomkerkhove** [comment]
Done
