### ISSUE TITLE
Add ability to set additional HPA annotations

### ISSUE THREAD

**Issue by dolefirenko** [kedacore/keda#2940]
### Proposal

Add ability to set additional HPA annotations:
I'm trying to provide both solutions: keda autoscaling and kube-downscaler (https://codeberg.org/hjacobs/kube-downscaler)
For kube-downscaler  it's necessary to annotate HPA with corresponding "downtime" annotations. 
So it would be nice to have an ability to provide HPA annotations in horizontalPodAutoscalerConfig

thanks

### Use-Case

make Pod autoscaling more flexible

**Comment by tomkerkhove** [comment]
Adding additional labels to HPA is something that we can support, though.

**Comment by JorTurFer** [comment]
I agree with @tomkerkhove , we can just add support to adding additional annotations, how end users use them is their scope.
Maybe we could add a section in the SO or just pass SO labels to HPA. WDYT?

**Comment by tomkerkhove** [comment]
I think that's fair
