### ISSUE TITLE
Add needed resources in the clusters for e2e test with AAD-Workload-identity

### ISSUE THREAD

**Issue by v-shenoy** [kedacore/keda#2941]
Proposal

Azure AD Workload Identity support is currently in process of being added. With this in mind, we should have e2e tests covering this scenario. Preferably for all Azure scalers, but at least one to ensure that the changes do not break this feature.

Creating this issue for tracking purposes.

Use-Case
Improve the trust in the e2e test because they cover more scenarios

Anything else?
Relates to https://github.com/kedacore/keda/issues/2487, https://github.com/kedacore/keda/pull/2907

**Comment by tomkerkhove** [comment]
Do we need to add anything else?

**Comment by v-shenoy** [comment]
> Do we need to add anything else?

The tests are passing, so we have everything. Let's just keep this open until the main PR is merged.

**Comment by tomkerkhove** [comment]
❤️
