### ISSUE TITLE
[Docs] Video Tutorials for KEDA

### ISSUE THREAD

**Issue by izzymsft** [kedacore/keda#295]
A lot of developers and admins learn faster by watching video tutorials.
We need some guidance videos to demonstrate installation, setup and configuration of scalers.

**Comment by jeffhollan** [comment]
Potentially broken up in to several other items:
 - Overview - why use KEDA
 - How to install and get started 
 - Scaler specific videos

@izzymsft to help. If you want to create a sub issue for any of these or all of these I can assign

**Comment by tomkerkhove** [comment]
We have some stuff in community already but still valuable indeed
