### ISSUE TITLE
Add GCP PubSub Sample to Wiki

### ISSUE THREAD

**Issue by patnaikshekhar** [kedacore/keda#298]
I've added a GCP PubSub sample to the org which needs to be added to the wiki under **Samples and Blog posts**

* [GCP PubSub messages consumed by a Go Container](https://github.com/kedacore/sample-go-gcppubsub)

**Comment by tomkerkhove** [comment]
@jeffhollan 	Can you pick this up or shall we move this to the GitHub repo as well?

**Comment by tomkerkhove** [comment]
@patnaikshekhar can you send a PR to our samples repo, if not done already please?

If we're good to go, I'd like to close this issue.

**Comment by tomkerkhove** [comment]
Closing as we no longer use the wiki
