### ISSUE TITLE
[Docs] No documentation is available for Prometheus trigger

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda#300]
No documentation is available for Prometheus trigger in the [wiki](https://github.com/kedacore/keda/wiki/ScaledObject-spec).

**Comment by tomkerkhove** [comment]
Hi @yaron2, looks like you've contributed this scaler. Would you mind taking this up or don't have the bandwidth?

**Comment by jeffhollan** [comment]
I'll see if I can grab this and do on the docs repo.  Haven't used before but expect I can get to work 🤞

**Comment by tomkerkhove** [comment]
Docs are done - https://keda.sh/scalers/prometheus/
