### ISSUE TITLE
Allow PR authors to run E2E tests.

### ISSUE THREAD

**Issue by v-shenoy** [kedacore/keda#3004]
Right now, only reviewers with write access can trigger e2e tests on a PR.  In many cases, the tests work on the developer's local setup, but fail in the KEDA test environment, which can be a bit confusing to debug. This leads to a constant back and forth of the developer making changes, and then having to ask one of the reviewers to run the tests and wait. It is the case, even if the change is as simple as adding a logging statement. 

I feel like this process is a bit tedious and can be improved. Wanted to bring this up for a discussion and see if it can be changed.

**Comment by tomkerkhove** [comment]
Ha, I'm happy to share that we've already discussed this and we have an improvement coming that would allow more people to trigger e2e tests.

**Comment by JorTurFer** [comment]
I expect to have it ready in the beginning of next week
I have a trip for the rest of the week, sorry

**Comment by v-shenoy** [comment]
@tomkerkhove @JorTurFer Thanks a lot.

And enjoy your trip :)
