### ISSUE TITLE
Pause autoscaling doesn't work from 0->1 or 1->0

### ISSUE THREAD

**Issue by JorTurFer** [kedacore/keda#3009]
### Report

Trying the feature with RabbitMQ Scaler, I tried to pause the scaling setting the annotation `autoscaling.keda.sh/paused-replicas: '0'`.
The workload went to 0 properly but automatically the operator scaled the workload from 0 to 1 (because there were pending messages in the queue).

I have tried setting `autoscaling.keda.sh/paused-replicas: '1'` and the operator scaled to 1 and a few moments after, again to zero (because there wasn't any pending message).

It seems that the operator is not taking into account this annotation during the process to determine if the ScaledObject is active or not.
During the stage 1->N and N->1 works good

### Expected Behavior

Pause the scaling in both stages, 0->1->0 and 1->N->1

### Actual Behavior

The scaling is paused only in 1->N->1

### Steps to Reproduce the Problem

1. Deploy a SO using RabbitMQ trigger scaling from 0 to X
2. Enqueue some messages in the queue
3. Add the annotation `autoscaling.keda.sh/paused-replicas: '0'`

Or

1. Deploy a SO using RabbitMQ trigger scaling from 0 to X
2. Ensure the queue is empty
3. Add the annotation `autoscaling.keda.sh/paused-replicas: '1'`

### Logs from KEDA operator

```
1.6517537492817814e+09	INFO	scaleexecutor	Successfully scaled target to paused replicas count	{"scaledobject.Name": "rabbitmq-consumer", "scaledObject.Namespace": "default", "scaleTarget.Name": "rabbitmq-consumer", "paused replicas": 0}
1.6517537542743633e+09	INFO	scaleexecutor	Successfully updated ScaleTarget	{"scaledobject.Name": "rabbitmq-consumer", "scaledObject.Namespace": "default", "scaleTarget.Name": "rabbitmq-consumer", "Original Replicas Count": 0, "New Replicas Count": 1}

```

```
1.651753834290882e+09	INFO	scaleexecutor	Successfully scaled target to paused replicas count	{"scaledobject.Name": "rabbitmq-consumer", "scaledObject.Namespace": "default", "scaleTarget.Name": "rabbitmq-consumer", "paused replicas": 1}
1.651753859283409e+09	INFO	scaleexecutor	Successfully set ScaleTarget replicas count to ScaledObject minReplicaCount	{"scaledobject.Name": "rabbitmq-consumer", "scaledObject.Namespace": "default", "scaleTarget.Name": "rabbitmq-consumer", "Original Replicas Count": 1, "New Replicas Count": 0}

```

### KEDA Version

2.7.0

### Kubernetes Version

1.23

### Platform

Microsoft Azure

### Scaler Details

RabbitMQ

**Comment by zroubalik** [comment]
CC @aryan9600
