### ISSUE TITLE
[Docs] No documentation is available for AWS Simple Queue Service (SQS) trigger

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda#302]
No documentation is available for AWS Simple Queue Service (SQS) trigger in the [wiki](https://github.com/kedacore/keda/wiki/ScaledObject-spec).

**Comment by tomkerkhove** [comment]
Hi @zach-dunton-sf, looks like you've contributed this scaler. Would you mind taking this up or don't have the bandwidth?

**Comment by zach-dunton-sf** [comment]
Yes, I'll block out an hour this week to add some.

**Comment by tomkerkhove** [comment]
Awesome, thank you!

**Comment by jralph** [comment]
Was just looking for docs on this. Would also be good to know if the scaler can use iam profiles instead of env variables from the container. I believe the aws library checks for this by default, but keda throws an error when the env doesn't exist.

Is this possible? Or should I raise an issue for this?

**Comment by tomkerkhove** [comment]
I'm not sure but I doubt that this works, can you confirm this @zach-dunton-sf 	?

**Comment by zach-dunton-sf** [comment]
It tries to use the default provider chain first, then looks for environment variables. IF you set a role for the keda deployment it should work. I have some work in progress such that you can define the role to be assumed in the CRD.

**Comment by tomkerkhove** [comment]
> I have some work in progress such that you can define the role to be assumed in the CRD.

Can you elaborate on this, please?

Keep in mind that the ScaledObject spec is subject to change (#294) which might impact you or you'd want to provide feedback on it

**Comment by zach-dunton-sf** [comment]
In the AWS SQS Scaler configuration.

https://github.com/kedacore/keda/blob/master/examples/awssqsqueue_scaledobject.yaml#L42

**Comment by jralph** [comment]
Currently it doesn't work as it throws an error if the environment variables aren't found in the deployment.

I use kube2iam to apply instance profiles to containers, so an option for it to use the iam policy found when running on the keda container would be awesome. That way I can give the keda deployment a read only iam policy for sqs.

**Comment by tomkerkhove** [comment]
Can you open a seperate issue please?

Tom Kerkhove
Azure Architect at Codit, Microsoft Azure MVP

________________________________

**Comment by jralph** [comment]
Done, see #316

**Comment by tomkerkhove** [comment]
Docs are available here - https://keda.sh/scalers/aws-sqs/
