### ISSUE TITLE
[Docs] No documentation is available for AWS CloudWatch trigger

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda#303]
No documentation is available for AWS CloudWatch trigger in the [wiki](https://github.com/kedacore/keda/wiki/ScaledObject-spec).

**Comment by tomkerkhove** [comment]
Hi @ageekymonk, looks like you've contributed this scaler. Would you mind taking this up or don't have the bandwidth?

**Comment by ageekymonk** [comment]
I can take it up but i do not have access to wiki.

**Comment by tomkerkhove** [comment]
No problem, I didn't have access as well and just copied it as is.
Feel free to let me know if you have issues.

**Comment by anirudhgarg** [comment]
#293

**Comment by tomkerkhove** [comment]
Done
