### ISSUE TITLE
FailedGetExternalMetric unable to fetch metrics from external metrics API: no matching metrics found (Azure Log Analytics)

### ISSUE THREAD

**Issue by kibnelbachyr** [kedacore/keda#3031]
### Report

I have a scaled object with Azure Log Analytics. The auto-scaling is working and our application can scale based on Azure Log Analytics query result. But, I see a persistent warning inside the events of the HPA : 

`  Warning  FailedGetExternalMetric  3m47s (x333 over 4h3m)  horizontal-pod-autoscaler  unable to get external metric <namespace>/s0-azure-log-analytics-<id>/&LabelSelector{MatchLabels:map[string]string{scaledobject.keda.sh/name: kedaloganalytics-consumer-scaled-object-dev,},MatchExpressions:[]LabelSelectorRequirement{},}: unable to fetch metrics from external metrics API : no matching metrics found for s0-azure-log-analytics-<id>`

Describe of the hpa : 
```
Name:                                                                                    keda-hpa-kedaloganalytics-consumer-scaled-object-dev
Namespace:                                                                               chili-dev
Labels:                                                                                  app.kubernetes.io/managed-by=keda-operator
                                                                                         app.kubernetes.io/name=keda-hpa-kedaloganalytics-consumer-scaled-object-dev
                                                                                         app.kubernetes.io/part-of=kedaloganalytics-consumer-scaled-object-dev
                                                                                         app.kubernetes.io/version=2.7.0
                                                                                         deploymentName=keda-consumer-dev
                                                                                         scaledobject.keda.sh/name=kedaloganalytics-consumer-scaled-object-dev
Annotations:                                                                             <none>
CreationTimestamp:                                                                       Tue, 10 May 2022 14:18:20 +0200
Reference:                                                                               Deployment/chiliservice-dev
Metrics:                                                                                 ( current / target )
  "s0-azure-log-analytics-2c590a65-54c2-45a2-9aaf-b529fa0b4b3d" (target average value):  0 / 1
Min replicas:                                                                            1
Max replicas:                                                                            10
Deployment pods:                                                                         1 current / 1 desired
Conditions:
  Type            Status  Reason                   Message
  ----            ------  ------                   -------
  AbleToScale     True    SucceededGetScale        the HPA controller was able to get the target's current scale
  ScalingActive   False   FailedGetExternalMetric  the HPA was unable to compute the replica count: unable to get external metric chili-dev/s0-azure-log-analytics-2c590a65-54c2-45a2-9aaf-b529fa0b4b3d/&LabelSelector{MatchLabels:map[string]string{scaledobject.keda.sh/name: kedaloganalytics-consumer-scaled-object-dev,},MatchExpressions:[]LabelSelectorRequirement{},}: unable to fetch metrics from external metrics API: no matching metrics found for s0-azure-log-analytics-2c590a65-54c2-45a2-9aaf-b529fa0b4b3d
  ScalingLimited  True    TooFewReplicas           the desired replica count is less than the minimum replica count
Events:
  Type     Reason                   Age                    From                       Message
  ----     ------                   ----                   ----                       -------
  Normal   SuccessfulRescale        54m (x2 over 88m)      horizontal-pod-autoscaler  New size: 1; reason: All metrics below target
  Warning  FailedGetExternalMetric  4m7s (x334 over 4h9m)  horizontal-pod-autoscaler  unable to get external metric chili-dev/s0-azure-log-analytics-2c590a65-54c2-45a2-9aaf-b529fa0b4b3d/&LabelSelector{MatchLabels:map[string]string{scaledobject.keda.sh/name: kedaloganalytics-consumer-scaled-object-dev,},MatchExpressions:[]LabelSelectorRequirement{},}: unable to fetch metrics from external metrics API: no matching metrics found for s0-azure-log-analytics-2c590a65-54c2-45a2-9aaf-b529fa0b4b3d
  ```

Describe of the scaled object:
```
Name:         kedaloganalytics-consumer-scaled-object-dev
Namespace:    chili-dev
Labels:       deploymentName=keda-consumer-dev
              scaledobject.keda.sh/name=kedaloganalytics-consumer-scaled-object-dev
Annotations:  <none>
API Version:  keda.sh/v1alpha1
Kind:         ScaledObject
Metadata:
  Creation Timestamp:  2022-05-10T12:18:18Z
  Finalizers:
    finalizer.keda.sh
  Generation:  3
  Managed Fields:
    API Version:  keda.sh/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
        f:labels:
          .:
          f:deploymentName:
      f:spec:
        .:
        f:cooldownPeriod:
        f:maxReplicaCount:
        f:minReplicaCount:
        f:pollingInterval:
        f:scaleTargetRef:
          .:
          f:name:
        f:triggers:
    Manager:      HashiCorp
    Operation:    Update
    Time:         2022-05-10T12:18:18Z
    API Version:  keda.sh/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          .:
          v:"finalizer.keda.sh":
        f:labels:
          f:scaledobject.keda.sh/name:
      f:status:
        .:
        f:conditions:
        f:externalMetricNames:
        f:lastActiveTime:
        f:originalReplicaCount:
        f:scaleTargetGVKR:
          .:
          f:group:
          f:kind:
          f:resource:
          f:version:
        f:scaleTargetKind:
    Manager:      keda
    Operation:    Update
    Time:         2022-05-10T14:50:59Z
    API Version:  keda.sh/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        f:health:
          .:
          f:s0-azure-log-analytics-2c590a65-54c2-45a2-9aaf-b529fa0b4b3d:
            .:
            f:numberOfFailures:
            f:status:
    Manager:         keda-adapter
    Operation:       Update
    Time:            2022-05-10T14:51:14Z
  Resource Version:  2871768
  UID:               cf548230-b482-4ba6-affa-305c7ed6cf4a
Spec:
  Cooldown Period:    30
  Max Replica Count:  10
  Min Replica Count:  1
  Polling Interval:   30
  Scale Target Ref:
    Name:  chiliservice-dev
  Triggers:
    Authentication Ref:
      Name:  trigger-keda-dev
    Metadata:
      Query:  let tenant = "dev";
AppMetrics
| where TimeGenerated > ago(5m)
| where Name == "OverdueTasks"
| where AppRoleInstance contains tenant
| summarize by OverdueTasks_Sum = Sum

      Threshold:  1
    Type:         azure-log-analytics
Status:
  Conditions:
    Message:  ScaledObject is defined correctly and is ready for scaling
    Reason:   ScaledObjectReady
    Status:   True
    Type:     Ready
    Message:  Scaling is performed because triggers are active
    Reason:   ScalerActive
    Status:   True
    Type:     Active
    Message:  No fallbacks are active on this scaled object
    Reason:   NoFallbackFound
    Status:   False
    Type:     Fallback
  External Metric Names:
    s0-azure-log-analytics-2c590a65-54c2-45a2-9aaf-b529fa0b4b3d
  Health:
    s0-azure-log-analytics-2c590a65-54c2-45a2-9aaf-b529fa0b4b3d:
      Number Of Failures:  0
      Status:              Happy
  Last Active Time:        2022-05-10T16:32:26Z
  Original Replica Count:  2
  Scale Target GVKR:
    Group:            apps
    Kind:             Deployment
    Resource:         deployments
    Version:          v1
  Scale Target Kind:  apps/v1.Deployment
Events:               <none>

``` 

Errors from KEDA operator : 

`1.6521939320277655e+09	ERROR	scalehandler	Error getting scale decision	{"scaledobject.Name": "kedaloganalytics-consumer-scaled-object-dev", "scaledObject.Namespace": "chili-dev", "scaleTarget.Name": "chiliservice-dev", "error": "failed to execute IsActive function. Scaled object: kedaloganalytics-consumer-scaled-object-dev. Namespace: chili-dev. Inner Error: error calling Log Analytics REST api. Inner Error: Post \"https://api.loganalytics.io/v1/workspaces/2c590a65-54c2-45a2-9aaf-b529fa0b4b3d/query\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).checkScalers
	/workspace/pkg/scaling/scale_handler.go:278
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).startScaleLoop
	/workspace/pkg/scaling/scale_handler.go:149`

### Expected Behavior

No failure event on the HPA.

### Actual Behavior

Warning  **FailedGetExternalMetric** 

### Steps to Reproduce the Problem

1. Install KEDA with helm chart on AKS cluster.
2. Configure the scaler following: https://keda.sh/docs/2.7/scalers/azure-log-analytics/ 

### Logs from KEDA operator

```
I0510 12:09:48.928119       1 request.go:665] Waited for 1.045989048s due to client-side throttling, not priority and fairness, request: GET:https://10.2.0.1:443/apis/autoscaling/v1?timeout=32s
1.6521845901325662e+09	INFO	controller-runtime.metrics	Metrics server is starting to listen	{"addr": ":8080"}
1.6521845901359537e+09	INFO	setup	Running on Kubernetes 1.21	{"version": "v1.21.9"}
1.652184590136202e+09	INFO	setup	Starting manager
1.6521845901362207e+09	INFO	setup	KEDA Version: 2.7.0
1.6521845901362245e+09	INFO	setup	Git Commit: 5f8af5cd90805d8b9c5964e1619a8b2bdcec6cfd
1.6521845901362278e+09	INFO	setup	Go Version: go1.17.3
1.652184590136231e+09	INFO	setup	Go OS/Arch: linux/amd64
I0510 12:09:50.136603       1 leaderelection.go:248] attempting to acquire leader lease keda/operator.keda.sh...
1.6521845901368594e+09	INFO	Starting server	{"kind": "health probe", "addr": "[::]:8081"}
1.652184590136948e+09	INFO	Starting server	{"path": "/metrics", "kind": "metrics", "addr": "[::]:8080"}
I0510 12:10:05.290087       1 leaderelection.go:258] successfully acquired lease keda/operator.keda.sh
1.652184605290749e+09	INFO	controller.scaledobject	Starting EventSource	{"reconciler group": "keda.sh", "reconciler kind": "ScaledObject", "source": "kind source: *v1alpha1.ScaledObject"}
1.6521846052907484e+09	INFO	controller.triggerauthentication	Starting EventSource	{"reconciler group": "keda.sh", "reconciler kind": "TriggerAuthentication", "source": "kind source: *v1alpha1.TriggerAuthentication"}
1.6521846052911603e+09	INFO	controller.triggerauthentication	Starting Controller	{"reconciler group": "keda.sh", "reconciler kind": "TriggerAuthentication"}
1.652184605290868e+09	INFO	controller.clustertriggerauthentication	Starting EventSource	{"reconciler group": "keda.sh", "reconciler kind": "ClusterTriggerAuthentication", "source": "kind source: *v1alpha1.ClusterTriggerAuthentication"}
1.6521846052912364e+09	INFO	controller.clustertriggerauthentication	Starting Controller	{"reconciler group": "keda.sh", "reconciler kind": "ClusterTriggerAuthentication"}
1.652184605290804e+09	INFO	controller.scaledjob	Starting EventSource	{"reconciler group": "keda.sh", "reconciler kind": "ScaledJob", "source": "kind source: *v1alpha1.ScaledJob"}
1.6521846052914548e+09	INFO	controller.scaledjob	Starting Controller	{"reconciler group": "keda.sh", "reconciler kind": "ScaledJob"}
1.6521846052910922e+09	INFO	controller.scaledobject	Starting EventSource	{"reconciler group": "keda.sh", "reconciler kind": "ScaledObject", "source": "kind source: *v2beta2.HorizontalPodAutoscaler"}
1.6521846052915452e+09	INFO	controller.scaledobject	Starting Controller	{"reconciler group": "keda.sh", "reconciler kind": "ScaledObject"}
1.6521846053933072e+09	INFO	controller.scaledjob	Starting workers	{"reconciler group": "keda.sh", "reconciler kind": "ScaledJob", "worker count": 1}
1.652184605393311e+09	INFO	controller.triggerauthentication	Starting workers	{"reconciler group": "keda.sh", "reconciler kind": "TriggerAuthentication", "worker count": 1}
1.6521846053933315e+09	INFO	controller.scaledobject	Starting workers	{"reconciler group": "keda.sh", "reconciler kind": "ScaledObject", "worker count": 5}
1.652184605393649e+09	INFO	controller.scaledobject	Reconciling ScaledObject	{"reconciler group": "keda.sh", "reconciler kind": "ScaledObject", "name": "kedaloganalytics-consumer-scaled-object-dev", "namespace": "chili-dev"}
1.6521882252631824e+09	INFO	controller.scaledobject	Reconciling ScaledObject	{"reconciler group": "keda.sh", "reconciler kind": "ScaledObject", "name": "kedaloganalytics-consumer-scaled-object-dev", "namespace": "chili-dev"}
1.6521882548151696e+09	INFO	controller.scaledobject	Reconciling ScaledObject	{"reconciler group": "keda.sh", "reconciler kind": "ScaledObject", "name": "kedaloganalytics-consumer-scaled-object-dev", "namespace": "chili-dev"}
1.6521939020265949e+09	ERROR	scalehandler	Error getting scale decision	{"scaledobject.Name": "kedaloganalytics-consumer-scaled-object-dev", "scaledObject.Namespace": "chili-dev", "scaleTarget.Name": "chiliservice-dev", "error": "failed to execute IsActive function. Scaled object: kedaloganalytics-consumer-scaled-object-dev. Namespace: chili-dev. Inner Error: error calling Log Analytics REST api. Inner Error: Post \"https://api.loganalytics.io/v1/workspaces/2c590a65-54c2-45a2-9aaf-b529fa0b4b3d/query\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).checkScalers
	/workspace/pkg/scaling/scale_handler.go:278
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).startScaleLoop
	/workspace/pkg/scaling/scale_handler.go:149
1.6521939021789622e+09	INFO	controller.scaledobject	Updated HPA according to ScaledObject	{"reconciler group": "keda.sh", "reconciler kind": "ScaledObject", "name": "kedaloganalytics-consumer-scaled-object-dev", "namespace": "chili-dev", "HPA.Namespace": "chili-dev", "HPA.Name": "keda-hpa-kedaloganalytics-consumer-scaled-object-dev"}
1.6521939162685077e+09	INFO	controller.scaledobject	Reconciling ScaledObject	{"reconciler group": "keda.sh", "reconciler kind": "ScaledObject", "name": "kedaloganalytics-consumer-scaled-object-dev", "namespace": "chili-dev"}
1.6521939193038576e+09	INFO	controller.scaledobject	Updated HPA according to ScaledObject	{"reconciler group": "keda.sh", "reconciler kind": "ScaledObject", "name": "kedaloganalytics-consumer-scaled-object-dev", "namespace": "chili-dev", "HPA.Namespace": "chili-dev", "HPA.Name": "keda-hpa-kedaloganalytics-consumer-scaled-object-dev"}
1.652193919318518e+09	INFO	controller.scaledobject	Reconciling ScaledObject	{"reconciler group": "keda.sh", "reconciler kind": "ScaledObject", "name": "kedaloganalytics-consumer-scaled-object-dev", "namespace": "chili-dev"}
1.6521939223443966e+09	INFO	controller.scaledobject	Updated HPA according to ScaledObject	{"reconciler group": "keda.sh", "reconciler kind": "ScaledObject", "name": "kedaloganalytics-consumer-scaled-object-dev", "namespace": "chili-dev", "HPA.Namespace": "chili-dev", "HPA.Name": "keda-hpa-kedaloganalytics-consumer-scaled-object-dev"}
1.6521939320277655e+09	ERROR	scalehandler	Error getting scale decision	{"scaledobject.Name": "kedaloganalytics-consumer-scaled-object-dev", "scaledObject.Namespace": "chili-dev", "scaleTarget.Name": "chiliservice-dev", "error": "failed to execute IsActive function. Scaled object: kedaloganalytics-consumer-scaled-object-dev. Namespace: chili-dev. Inner Error: error calling Log Analytics REST api. Inner Error: Post \"https://api.loganalytics.io/v1/workspaces/2c590a65-54c2-45a2-9aaf-b529fa0b4b3d/query\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).checkScalers
	/workspace/pkg/scaling/scale_handler.go:278
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).startScaleLoop
	/workspace/pkg/scaling/scale_handler.go:149
1.6521939613691688e+09	INFO	controller.scaledobject	Reconciling ScaledObject	{"reconciler group": "keda.sh", "reconciler kind": "ScaledObject", "name": "kedaloganalytics-consumer-scaled-object-dev", "namespace": "chili-dev"}
1.6521939620284812e+09	ERROR	scalehandler	Error getting scale decision	{"scaledobject.Name": "kedaloganalytics-consumer-scaled-object-dev", "scaledObject.Namespace": "chili-dev", "scaleTarget.Name": "chiliservice-dev", "error": "failed to execute IsActive function. Scaled object: kedaloganalytics-consumer-scaled-object-dev. Namespace: chili-dev. Inner Error: error calling Log Analytics REST api. Inner Error: Post \"https://api.loganalytics.io/v1/workspaces/2c590a65-54c2-45a2-9aaf-b529fa0b4b3d/query\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).checkScalers
	/workspace/pkg/scaling/scale_handler.go:278
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).startScaleLoop
	/workspace/pkg/scaling/scale_handler.go:149


```

### KEDA Version

2.7.0

### Kubernetes Version

1.21

### Platform

Microsoft Azure

### Scaler Details

Azure Log Analytics

**Comment by kibnelbachyr** [comment]
I redeployed the keda-operator and keda-operator-metrics-apiserver (v2.7.0) , I don't see this error anymore: `Inner Error: error calling Log Analytics REST api. Inner Error: Post \"https://api.loganalytics.io/v1/workspaces/<id>/query\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"` on the KEDA operator logs. The auto-scaling is working fine based on the Azure Log Analytics query result. But, I still can see the same warnings in HPA events : 

`Warning  FailedComputeMetricsReplicas  51m (x28 over 81m)   horizontal-pod-autoscaler  invalid metrics (1 invalid out of 1), first error is: failed to get s0-azure-log-analytics-<id> external metric: unable to get external metric dev/s0-azure-log-analytics-<id>/&LabelSelector{MatchLabels:map[string]string{scaledobject.keda.sh/name: kedaloganalytics-consumer-scaled-object-dev,},MatchExpressions:[]LabelSelectorRequirement{},}: unable to fetch metrics from external metrics API: no matching metrics found for s0-azure-log-analytics-<id>`

`Warning  FailedGetExternalMetric       92s (x109 over 81m)  horizontal-pod-autoscaler  unable to get external metric dev/s0-azure-log-analytics-<id>/&LabelSelector{MatchLabels:map[string]string{scaledobject.keda.sh/name: kedaloganalytics-consumer-scaled-object-dev,},Mat
chExpressions:[]LabelSelectorRequirement{},}: unable to fetch metrics from external metrics API: no matching metrics found for s0-azure-log-analytics-<id>`

**Comment by kibnelbachyr** [comment]
@tomkerkhove do you have any clue why this is happening?

**Comment by JorTurFer** [comment]
hey @kibnelbachyr 
Sorry due to the slow response, we have been in KubeCon last week. Is your query complex? I mean, maybe Log Analytics need more time than expected to process the query because it's too complex. [Could you try extending the timeout](https://keda.sh/docs/2.7/operate/cluster/#http-timeouts)?

**Comment by kibnelbachyr** [comment]
Hi @JorTurFer, Thank you for your answer! Actually the query is not that complex, it takes less than 1s (avg 500ms) in Azure to be executed. Regarding the http timeout in KEDA, it's configured to '3000s' should it be set to more?  

![Screenshot 2022-05-30 at 08 59 36](https://user-images.githubusercontent.com/31845236/171005244-1478fc3e-8d7e-40bd-a1e4-e4ec78a6b141.png)

**Comment by JorTurFer** [comment]
No, it shouldn't be necessary. Metrics server logs don't say anything else, right?

**Comment by kibnelbachyr** [comment]
I see some errors in the metrics server logs : 

`E0530 16:30:46.758637       1 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"no matching metrics found for s0-azure-log-analytics-<id>"}: no matching metrics found for s0-azure-log-analytics-<id>
I0530 16:30:46.758819       1 trace.go:205] Trace[895562437]: "List" url:/apis/external.metrics.k8s.io/v1beta1/namespaces/xxxx/s0-azure-log-analytics-<id>,user-agent:kube-controller-manager/v1.21.9 (linux/amd64) kubernetes/79b7a58/horizontal-pod-autoscaler,audit-id:ccdbec5f-9e88-457b-9899-9800f80eef66,client:172.31.27.201,accept:application/vnd.kubernetes.protobuf, */*,protocol:HTTP/2.0 (30-May-2022 16:30:46.194) (total time: 564ms):`

In the keda operator logs, I see these errors:

`1.6538370216543596e+09	ERROR	scalehandler	Error getting scale decision	{"scaledobject.Name": "kedaloganalytics-consumer-scaled-object-xxx", "scaledObject.Namespace": "xxxx", "scaleTarget.Name": "chiliservice-xxx", "error": "failed to execute IsActive function. Scaled object: kedaloganalytics-consumer-scaled-object-xxx. Namespace:xxxx. Inner Error: error calling Log Analytics REST api. Inner Error: Post \"https://api.loganalytics.io/v1/workspaces/<id>/query\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).checkScalers
	/workspace/pkg/scaling/scale_handler.go:278
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).startScaleLoop
	/workspace/pkg/scaling/scale_handler.go:149`

**Comment by kibnelbachyr** [comment]
Hi @JorTurFer, did you get a change to check these errors?

**Comment by JorTurFer** [comment]
hi @kibnelbachyr 
I have checked them and I can't find anything (but I'm not an expert in Log Analytics). Maybe @v-shenoy can take a look if he has time

**Comment by v-shenoy** [comment]
I don't think I can take this up for some time.

**Comment by mhoppe-cedar** [comment]
I saw a similar error when my keda metrics server did not have proper IAM permissions associated with it. Went back to check the keda metrics server deployment, the keda operator deployment, the scaledobject, and the keda operator serviceaccount roles/permissions. After ensuring they all agreed and were sufficient, it worked.

**Comment by kibnelbachyr** [comment]
@mhoppe-cedar Thank you for your answer. Could you please elaborate a little bit more? 
I am using a [Service Principal based authentication](https://keda.sh/docs/2.7/scalers/azure-log-analytics/#service-principal-based-authentication ) with "Log Analytics Reader" role over the Log Analytics workspace. The mechanism of scaling based on Log Search metrics in Azure Log Analytics is working but I still can see those errors anyways.

**Comment by mhoppe-cedar** [comment]
> @mhoppe-cedar Thank you for your answer. Could you please elaborate a little bit more? I am using a [Service Principal based authentication](https://keda.sh/docs/2.7/scalers/azure-log-analytics/#service-principal-based-authentication) with "Log Analytics Reader" role over the Log Analytics workspace. The mechanism of scaling based on Log Search metrics in Azure Log Analytics is working but I still can see those errors anyways.

@kibnelbachyr  - I have using the following:
- an IAM role for: keda api metrics server service, keda operator service, the scaledobject, and the keda operator serviceaccount. this is added under the "annotations" section.

- for example, my scaledobject looks a little weird but working:
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: myname
  namespace: mynamespace
  annotations:
    iam.amazonaws.com/role: k8s-keda-dev-role

**Comment by kibnelbachyr** [comment]
@mhoppe-cedar I am using an AKS cluster on Azure which doesn't have AAD/RBAC enabled. I am using a Service Principal to connect KEDA to the Azure Log Analytics scaler following this documentation : https://keda.sh/docs/2.7/scalers/azure-log-analytics/#service-principal-based-authentication 

I confirm again that the auto-scaling is working but I still see those errors when the metric (based on which we scale) is equal to 0.. I changed the time range on my query to Azure Log Analytics to match the frequency of updating the custom metric (10 minutes) and also increased the "pollingInterval" value (to 10mn) in the KEDA scaledobject. For now, I don't see the timeout errors in the KEDA operator logs but I still can see "unable to fetch metrics from external metrics API: no matching metrics found" errors in the HPA events/logs.

**Comment by Anoojak** [comment]
Hi All
Even same issue exist here unable to fetch the external metrics the query which am using is executed on prometheus ui i could see the metrics collected but when i deployed hpa file using the metric query facing issue error is unable to fetch external metrics
 i restarted keda but still the issue is same
keda version installed is 2.7.1
kubernetes version 1.21
![Screenshot_20220914-182745_Gmail](https://user-images.githubusercontent.com/50958509/190160305-8b88c189-dd6a-4763-8510-e6543a7c65a5.jpg)

**Comment by v-shenoy** [comment]
@JorTurFer Could this be a broader issue, rather than something specific `Log Analytics`?

**Comment by Anoojak** [comment]
Hi JorturFer

please find the attached logs from metric server
i checked the query in prometheus UI its executing fine
![20220915_125256](https://user-images.githubusercontent.com/50958509/190345705-9e74b5e0-0fd8-4e29-92cf-d37136890ffa.jpg)

**Comment by zroubalik** [comment]
@JorTurFer might be worth checking this in the Prometheus scaler code, right?

**Comment by JorTurFer** [comment]
the error says `prometheus query %s returned multiple elements`. I guess that the error here is clear, but the docs isn't clear enough, but we could modify the message clarifying the limitation in code too. Maybe something like `prometheus query %s returned multiple elements but only single element is supported`

**Comment by ritesh-agarwal-db** [comment]
I m also getting the same issue. I am just using Cronjob as a trigger so no upstream trigger. Any permanent fix to this issue?

 **_unable to fetch metrics from external metrics API: the server was unable to return a response in the time allotted, but may still be processing the request_**

**Comment by JorTurFer** [comment]
What do you mean with Cronjob as a trigger? Cron Trigger?

I'd suggest creating a new issue to track your case (sharing info such as KEDA version, logs, etc) because this was closed a year ago
