### ISSUE TITLE
KEDA Metrics API Server not honoring Loglevels

### ISSUE THREAD

**Issue by prousso** [kedacore/keda#3053]
### Report

Kede Matrics Api Server is spamming trace logs, even though logging is set to v=0

### Expected Behavior

When setting loglevel to 0, only level 0 and below should be logged
( as per log documentation)

### Actual Behavior

Traces are logged

### Steps to Reproduce the Problem

Start Keda Metrics Server
Let it run for a while
See logs

### Logs from KEDA operator

```
I1123 11:36:52.772270       1 trace.go:205] Trace[1110288377]: "List" url:/apis/external.metrics.k8s.io/v1beta1/namespaces/dd071/http-http---ems-dd071-8080-topic-dd071-hsdg->-pendingmessages,user-agent:kube-c │
│ ontroller-manager/v1.20.9 (linux/amd64) kubernetes/454b5b5/system:serviceaccount:kube-system:horizontal-pod-autoscaler,client:172.31.31.244 (23-Nov-2021 11:36:52.195) (total time: 576ms):                      │
│ Trace[1110288377]: ---"Listing from storage done" 576ms (11:36:00.772)   
```

### KEDA Version

2.7.1

### Kubernetes Version

1.21

### Platform

Google Cloud

### Anything else?

Copy from https://github.com/kedacore/keda/issues/2316

**Comment by tomkerkhove** [comment]
Closing in favor of #2316 who has the initial report.
