### ISSUE TITLE
KEDA operator crashes on nil memory panic if the eventhub connectionstring for Azure Eventhub Scaler contains an invalid character

### ISSUE THREAD

**Issue by christle** [kedacore/keda#3082]
### Report

The Azure Eventhub Scaler creates a storage path with `url.parse()` based on information from an eventhub connection string. If this connection string contains invalid characters like newline, the `url.parse` raise an error. This error is unhandled, so the operator crashes with a panic.

Invalid characters usually appear if the connectionstring contains an incorrect base64 encoding. 

### Expected Behavior

the Azure Eventhub Scaler should log an error message, which contains informations about the incorrect connectionstring

### Actual Behavior

the keda operator get a panic

### Steps to Reproduce the Problem

1.  add an Azure Eventhub scaler
2. add an Azure Eventhub connectionstring with a newline character
3. the keda operator crash with a panic

### KEDA Version

2.7.1

### Scaler Details

Eventhub Scaler

**Comment by v-shenoy** [comment]
Should this be closed after #3080?

**Comment by zroubalik** [comment]
Fixed in #3080
