### ISSUE TITLE
Provide support for preventing interference of autoscaling a single scale target when creating a new ScaledJob/ScaledObject

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda#3083]
### Proposal

We always recommend people to follow this guidance:
- Only have one ScaledJob/ScaledObject with multiple triggers, instead of multiple instances
- Do not mix and match ScaledJob/ScaledObject with your own HPA

However, we don't provide any prevention for this.

KEDA should automatically be rejecting new ScaledObject resources that are created which target a scale target which is already being autoscaled.

This should cover the following scenarios:
- ScaledJob/ScaledObject targeting workload A, but workload A is already scaled by another ScaledJob/ScaledObject
- ScaledJob/ScaledObject targeting workload A, but workload A is already scaled by another Horizontal Pod Autoscaler

### Use-Case

Prevent end-users from having multiple actors scale workloads, either by accident or on purpose, to prevent flapping due to different criteria.

### Anything else?

See https://github.com/kedacore/keda/discussions/3023 for the discussion

**Comment by tomkerkhove** [comment]
Just to be sure; are we effectively checking this today or was it closed by accident? (I think it's fine but just checking)

**Comment by JorTurFer** [comment]
It was closed automatically because the feature is fully implemented.
Feature + Docs + Helm chart changes are merged (helm changes merge closed this)
