### ISSUE TITLE
Provide support for preventing interference of autoscaling a single scale target with arbitrary HPAs

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda#3087]
### Proposal

If somebody creates an HPA while it is already being autoscaled by an ScaledJob/ScaledObject, we should prevent the HPA from being created by using an admission controller that rejects the HPA.

Alternatively, KEDA can just log a warning so that end-users become aware of it but this does not reject HPA resources and might get lost.

### Use-Case

Prevent end-users from having multiple actors scale workloads, either by accident or on purpose, to prevent flapping due to different criteria.

In this scenario, we want to prevent end-users creating arbitrary HPAs when a scale target is already scaled by a ScaledObject/ScaledJob.

**Comment by bamboo12366** [comment]
I urgently need this one, if no one is working on this can I give a try?

**Comment by tomkerkhove** [comment]
That would be nice! But we need to close on the approach first, certainly if we introduce an admission controller we need to see where we will shove it in (core or separate).

Thoughts @kedacore/keda-maintainers?

**Comment by tomkerkhove** [comment]
> It's a really good idea IMO. Maybe not only for preventing HPA in case of already existing SO and also for preventing SO if there is already a HPA or another SO.

Already got you covered with https://github.com/kedacore/keda/issues/3083 ;)

**Comment by tomkerkhove** [comment]
If you create an HPA manually and deploy it, there is no way for KEDA to stop it except without using an admission controller since KEDA doesn't manage the HPAs but Kubernetes vanilla does.

**Comment by zroubalik** [comment]
We would need a separate controller for watching HPAs in the cluster.

**Comment by zroubalik** [comment]
I mean to keep just the SO Status as the base feature and an option to fallback to for people which don't want to (or can't) use admission webhooks.

**Comment by bamboo12366** [comment]
For the base feature one, in the scaleObejct Controller main logic just to check no other hpa existing in the cluster binding with workload, if exist reporting in status and emit an event right?

**Comment by zroubalik** [comment]
Yeah, but please make it configurable, so it is not enabled by default.
