### ISSUE TITLE
add prometheus-metrics for keda-operator

### ISSUE THREAD

**Issue by bamboo12366** [kedacore/keda#3098]
### Proposal

We already using keda in live environment. The metrics is missing for keda-operator is kind of hard for me to debug problem. 
Maybe we should consider to add some metrics for it? Currently we only using the `scaleObject`, not using `triggerAuthentication` and `scaleJob`, what I implement in my environment for SO controller is:
- Total scaleobject per ns
- The rate and error rate to update hpa
- The rate to query the so active

**Comment by tomkerkhove** [comment]
We are already tracking some in https://github.com/kedacore/keda/issues/2638, https://github.com/kedacore/keda/issues/2637 & https://github.com/kedacore/keda/issues/2639.

We are open for contributions on those.

> * The rate and error rate to update hpa
> * The rate to query the so active

Can you elaborate on these metrics and their use-case please?

**Comment by bamboo12366** [comment]
> The rate and error rate to update hpa

our apiserver always keeps in overloaded. The update to hpa sometimes will fail or retry, and hpa resource is key point to me, so I monitor it to check everything goes right

> The rate to query the so active

I got around 1k SO in the cluster. After creating hpa resource, the one of main logic for so controller is keep checking SO, which will cause burden to other service(in our case, prometheus or kv system). It's will be easy for me to adjust the polling interval and timeout setting by monitoring the query rate and error rate for polling active
