### ISSUE TITLE
Provide HTTP scaling sample

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda#311]
Provide HTTP scaling sample which is using Osiris.

Noticed that this scenario is still a bit rough on the edges and not clear how to set this up so we might want to provide some guidance there.

**Comment by jeffhollan** [comment]
@anirudhgarg recently created this blog post https://dev.to/anirudhgarg_99/scale-up-and-down-a-http-triggered-function-app-in-kubernetes-using-keda-4m42

**Comment by tomkerkhove** [comment]
A link to post in samples repo was added
