### ISSUE TITLE
Allow active connections based scaling using KEDA

### ISSUE THREAD

**Issue by kunalchandratre1** [kedacore/keda#3126]
The underlying nodes on Azure support 500K flows. If we translate this into connections; it will be around 2,50,000. If we are using websocket based application with AKS; then this connection limit per node might breach; at the same time CPU and memory may not increase significantly.

Therefore please provide a way to scale nodes/ pods if active number of connections being served by pod/ node reaches to threshold stated in settings.

**Comment by tomkerkhove** [comment]
The ask is to scale based on used connections on nodes so that applications can be scaled out accordingly, if I'm not mistaken @kunalchandratre1?

If so, how would you envision this assuming KEDA does not know how many connections are being used on the nodes?
