### ISSUE TITLE
Redis 7.0 Streams - use Lag instead of pending

### ISSUE THREAD

**Issue by Jouse82** [kedacore/keda#3127]
Existing Redis Streams scaler uses the Xpending which may be completely false information. XPending only shows the number of read but unacked messages and therefore may not reflect the queue status. 

Redis 7.0 has introduced a new metric "Lag", which shows the amount of unread messages for a Stream and Group. 
XINFO _stream_ _group_ 

This should be the made available for the Redis streams scaler to use instead of the Xpending.

**Comment by JorTurFer** [comment]
Hey @Jouse82 
This sounds totally legit. My only concern is if this change can be done keeping the backward compatibility in any way or we will need to create (another) redis scaler 🤔 

BTW, are you willing to contribute with this?

**Comment by tomkerkhove** [comment]
We should have the capability to configure which approach to use given this is only in Redis 7 as well

**Comment by KomTak001** [comment]
> backward compatibility

Prerequisites: The threshold for stream and consumer group is obtained from yaml.

If `XINFO GROUPS [streameName]` has `lag`
```
threashold <= lag
```
Then scale

If there is no `lag`
Get `last-delivered-id` and get the entry list with, count the number,
```
XRANGE [streameName] [last-derivered-id for specific group] + COUNT [threashold]
```
and,
```
[Number] = threashold
```
Then scale

I think this will maintain backward compatibility to some extent, how about this?

**Comment by JorTurFer** [comment]
I'm not an expert on Redis but it sounds good

**Comment by sergio-ferreira-jscrambler** [comment]
> > backward compatibility
> 
> Prerequisites: The threshold for stream and consumer group is obtained from yaml.
> 
> If `XINFO GROUPS [streameName]` has `lag`
> 
> ```
> threashold <= lag
> ```
> 
> Then scale
> 
> If there is no `lag` Get `last-delivered-id` and get the entry list with, count the number,
> 
> ```
> XRANGE [streameName] [last-derivered-id for specific group] + COUNT [threashold]
> ```
> 
> and,
> 
> ```
> [Number] = threashold
> ```
> 
> Then scale
> 
> I think this will maintain backward compatibility to some extent, how about this?

I'm worried of the performance hit this brings with the XRANGE command, which iterates all entries from the `last-delivered-id` to the last entry (+).

My team is using Redis 6 in production and since we don't have the `lag` value directly from Redis, we're using a script which does pretty much the same as your code to get the lag. It iterates with XRANGE since the last-delivered-id to the last message. However, we noticed that under high loads, this iteration will block Redis for a few seconds - we've had test cases where this blocked Redis to up to 15 seconds

**Comment by krishnadurai** [comment]
@JorTurFer can you please check the PR addressing this feature by my colleague @mikelam-us addressing this issue. We are both willing to maintain the Redis implementations:

https://github.com/kedacore/keda/pull/4592

**Comment by zroubalik** [comment]
Thanks @krishnadurai & @mikelam-us !

**Comment by zroubalik** [comment]
Implented in 2.11

**Comment by elpablete** [comment]
Is this available to use on "redis-streams" [docs 2.13](https://keda.sh/docs/2.13/scalers/redis-streams/) ? I only see it in the docs for "redis-cluster-streams" [docs 2.13](https://keda.sh/docs/2.13/scalers/redis-cluster-streams/)

**Comment by JorTurFer** [comment]
Based on e2e tests I'd say that yes and it's not properly updated docs

**Comment by elpablete** [comment]
Can I help updating the docs?

**Comment by JorTurFer** [comment]
Thanks for the proposal! ❤️
I did it yesterday : https://github.com/kedacore/keda-docs/pull/1304
