### ISSUE TITLE
Provide support for container-level metrics in CPU/Memory scaler

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda#3146]
### Proposal

Provide support for container-level metrics in CPU/Memory scaler

### Use-Case

Provide support for container-level metrics in CPU/Memory scaler to scale more granularly.

**Comment by itonyli** [comment]
@tomkerkhove I want to try it, what kind of process do I need?

**Comment by tomkerkhove** [comment]
Do you mean process for contribution or?

**Comment by zroubalik** [comment]
Implemented in KEDA 2.8
