### ISSUE TITLE
Authentication failures for Datadog scaler 

### ISSUE THREAD

**Issue by karolorlamowski** [kedacore/keda#3147]
### Report

Getting 403 error when I try to use Datadog scaler following this steps https://keda.sh/docs/2.7/scalers/datadog/

There is no problems when I try invoke API from local machine via CURL using same apiKey and appToken.

### Expected Behavior

Activation of Keda Datadog scaler

### Actual Behavior

"error": "error establishing Datadog connection: error connecting to Datadog API endpoint: 403 Forbidden"

### Steps to Reproduce the Problem

1. Get your API and APP token from Datadog 
2. Deploy Keda autoscaler on your cluster following docs

### Logs from KEDA operator

```
1.6547744315708387e+09	DEBUG	events	Warning	{"object": {"kind":"ScaledObject","namespace":"b","name":"core-fr-celery-priority-worker","uid":"7cb8bfc9-9c62-419d-8b25-07c2ab670718","apiVersion":"keda.sh/v1alpha1","resourceVersion":"405447786"}, "reason": "KEDAScalerFailed", "message": "error establishing Datadog connection: error connecting to Datadog API endpoint: 403 Forbidden"}
1.6547744315709755e+09	DEBUG	events	Warning	{"object": {"kind":"ScaledObject","namespace":"b","name":"core-fr-celery-priority-worker","uid":"7cb8bfc9-9c62-419d-8b25-07c2ab670718","apiVersion":"keda.sh/v1alpha1","resourceVersion":"405447786"}, "reason": "ScaledObjectCheckFailed", "message": "Failed to ensure HPA is correctly created for ScaledObject"}
1.654774431622108e+09	ERROR	controller.scaledobject	Reconciler error	{"reconciler group": "keda.sh", "reconciler kind": "ScaledObject", "name": "core-fr-celery-priority-worker", "namespace": "b", "error": "error establishing Datadog connection: error connecting to Datadog API endpoint: 403 Forbidden"}
```

### KEDA Version

2.7.1

### Kubernetes Version

1.22

### Platform

Google Cloud

### Scaler Details

Datadog

**Comment by JorTurFer** [comment]
hey
Could you share your scaleobject? (without secrets ofc)
