### ISSUE TITLE
Prometheus scaler unable to recover after missing metric response

### ISSUE THREAD

**Issue by 3schwartz** [kedacore/keda#3152]
### Report

We are using the Prometheus scaler configured like below

```
      - type: prometheus
        metadata:
          serverAddress: http://thanos:9090
          metricName: some-metric-name
          query: 'some metric or vector (0)'
          threshold: '100'
```

Due to high traffic within our cluster requests to Thanos can sometimes take a higher amount of time. I believe a request timeout is happening. What we observe is the HPA reports `<unknown>/100`.

If I delete the HPA, and the ScaledObjects recreates it, it correctly gets the metric. Hence it seems like it isn't able to recover.

We are using multiple triggers however if some of them errors out the others doesn't kick in and the HPA get's into a stalled state.

I can reproduce the problem - logs from Keda when reproduce correctly states that Thanos wasn't available. But it doesn't recover when Thanos get's back up.

```
1.6548664839465003e+09  INFO    controller.scaledobject Reconciling ScaledObject        {"reconciler group": "keda.sh", "reconciler kind": "ScaledObject", "name": "some-name-scale", "namespace": "dev2"}
1.6548664857930536e+09  ERROR   prometheus_scaler       error executing prometheus query        {"error": "prometheus query api returned error. status: 503 response: no healthy upstream"}
github.com/kedacore/keda/v2/pkg/scalers.(*prometheusScaler).IsActive
        /workspace/pkg/scalers/prometheus_scaler.go:135
github.com/kedacore/keda/v2/pkg/scaling/cache.(*ScalersCache).IsScaledObjectActive
        /workspace/pkg/scaling/cache/scalers_cache.go:86
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).checkScalers
        /workspace/pkg/scaling/scale_handler.go:278
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).startScaleLoop
        /workspace/pkg/scaling/scale_handler.go:149
```

### Expected Behavior

I expected the scaler was able to recover and hence the HPA would get out of a `<unknown>/100` state.

### Actual Behavior

The HPA get's into a stalled state of `<unknown>/100` whenever a request fails

### Steps to Reproduce the Problem

1. Create a Prometheus trigger
2. Kill Prometheus
3. Watch HPA get's into state `<unknown>/100` and doesn't recover when Prometheus back up and running

### Logs from KEDA operator

```
1.6548664839465003e+09  INFO    controller.scaledobject Reconciling ScaledObject        {"reconciler group": "keda.sh", "reconciler kind": "ScaledObject", "name": "some-name-scale", "namespace": "dev2"}
1.6548664857930536e+09  ERROR   prometheus_scaler       error executing prometheus query        {"error": "prometheus query api returned error. status: 503 response: no healthy upstream"}
github.com/kedacore/keda/v2/pkg/scalers.(*prometheusScaler).IsActive
        /workspace/pkg/scalers/prometheus_scaler.go:135
github.com/kedacore/keda/v2/pkg/scaling/cache.(*ScalersCache).IsScaledObjectActive
        /workspace/pkg/scaling/cache/scalers_cache.go:86
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).checkScalers
        /workspace/pkg/scaling/scale_handler.go:278
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).startScaleLoop
        /workspace/pkg/scaling/scale_handler.go:149
```

### KEDA Version

2.6.1

### Kubernetes Version

1.21

### Platform

Microsoft Azure

### Scaler Details

Prometheus

**Comment by zroubalik** [comment]
Can you reproduce the same with KEDA 2.7.1?

**Comment by 3schwartz** [comment]
> > Can you reproduce the same with KEDA 2.7.1?
> 
> It works 🎉 Thank you very much.
> 
> Just out of curiosity which PR or issue did the fix?
