### ISSUE TITLE
Ability to control an existing HorizontalPodAutoscaler

### ISSUE THREAD

**Issue by pragmaticivan** [kedacore/keda#3154]
### Proposal

Add the ability to reference an existing Horizontal Pod Autoscaler (HPA) by overwriting or expanding the existing HPA with the new scalers provided in the ScaledObject.

Such a feature would alleviate the need to delete existing HPAs and would support progressive add-ons in existing running applications.

### Use-Case

Application ABC has memory/cpu based HPA already.

ScaledObject would replace that HPA file completely without deleting the existing resource.

**Comment by aviadlevy** [comment]
What is the expected behavior when the ScaledObject is deleted? 
Does the original HPA restored?

**Comment by pragmaticivan** [comment]
@aviadlevy just like it would not delete the Deployment, I think the original HPA should be restored.

**Comment by tomkerkhove** [comment]
What does the HPA have configured that would want you to keep it?

**Comment by pragmaticivan** [comment]
@tomkerkhove Just the take-over control via CD pipeline. If someone already has an HPA, there will be no need to delete that resource and add keda after that. The same applies to just removing the ScaleObject, the existing hpa would take over as a fallback.

**Comment by tomkerkhove** [comment]
So the ask is to not only be able to bring-your-own HPA, but also preserve it after deleting the ScaledObject; is that correct?

**Comment by zroubalik** [comment]
And what if the original HPA is owned by another tool/controller? Then we will have a conflict in ownerRefs. I am not a fan of this proposal TBH.

**Comment by tomkerkhove** [comment]
Yes, I have some doubts as well as there can be decent chunk of implications.

**Comment by pragmaticivan** [comment]
All good on that one :D Was just thinking if there would be a way to easily change things progressively. You have good points.
