### ISSUE TITLE
Migrate e2e test for AWS SQS Queue scaler to Go.

### ISSUE THREAD

**Issue by v-shenoy** [kedacore/keda#3172]
### Proposal

Relates to https://github.com/kedacore/keda/issues/2357, https://github.com/kedacore/keda/issues/2737.

**Comment by aviadlevy** [comment]
Hi,  
I might be interested in working on this issue, but first needs to verify I understand the current behvior

In e2e test you querying an actual SQS queue in AWS? not mock?

**Comment by v-shenoy** [comment]
> Hi, I might be interested in working on this issue, but first needs to verify I understand the current behvior
> 
> In e2e test you querying an actual SQS queue in AWS? not mock?

Yes, all of the e2e tests query actual resources.

**Comment by aviadlevy** [comment]
So I'll start take a look at this test. you can assign this to me 😎

**Comment by v-shenoy** [comment]
Ahaha, I am not in charge here ;) Just helping out.

**Comment by aviadlevy** [comment]
Can't assign myself, so let's wait for KEDA owners

**Comment by JorTurFer** [comment]
hey @aviadlevy 
in fact, we prefer to use real resources for e2e always, where is possible. If e2e test fail and the resources are not deleted, we can delete them manually, going to the cloud provider console to do it 😄
if the test fails without a panic, the resources should be deleted, and even that, after solving the panic, the resources will be deleted (running and failing the test again).

The advantage of using real resources is that we can detect/check real behaviors, mocks usually doesn't support all the scenarios like authentication or pod-identities (we want to cover them also with e2e test).

**Comment by aviadlevy** [comment]
Thanks @JorTurFer for the elaborate explanation
