### ISSUE TITLE
keda operator not closing connections to rabbitmq

### ISSUE THREAD

**Issue by sc-chad** [kedacore/keda#318]
Been playing with the rabbitmq trigger and everything was working well.

Somewhere in the testing keda quit closing connections to one of our clusters.  I've gone as far as deleted all the kubernetes templates of keda, rebuilt the rabbitmq cluster, rebuilt all the templates that were using triggers and it's still causing my rabbitmq cluster to gain connections.

If I delete the keda pods the connection count drops instantly, but I can't see why it's opening new connections to the service without closing them.

Any help would be appreciated, if I can share any other details please let me know!

Example: This cluster is usually around 45 connections.

![Screen Shot 2019-08-02 at 5 03 28 PM](https://user-images.githubusercontent.com/6853614/62398951-33a16a00-b548-11e9-9067-5ed8eef2ec96.png)

We are running on EKS in AWS.
AMI Version: amazon-eks-node-1.13-v20190614 (ami-08c4955bcc43b124e)

**Comment by zodraz** [comment]
This only happens on the sample project provided. Works perfectly on properly producers/consumers.

**Comment by sc-chad** [comment]
Well I may be missing something, but this was happening on our live staging environments.  Can you point me to what I should be using instead?

**Comment by zodraz** [comment]
I can confirm that a properly RabbitMQ producer /consumer frees the connections after the HPA resizes down to the original state. I am using NServiceBus BTW.

And like I said if you tested with the sample project on Keda, it has some bug that the consumers are not scaled down and of course the connections per se on those consumers are not.

Cheers
