### ISSUE TITLE
Add a check to validate the changelog on PRs

### ISSUE THREAD

**Issue by JorTurFer** [kedacore/keda#3190]
### Proposal

Even it's documented the proper way to add entries in the changelog, there are cases where we still approve PRs with the entry unsorted or with other style errors.
It's difficult to review every thing without any error, but maybe we can create a bash script that checks the unreleased section to validate it and append it to pre-commit checks

**Comment by nitishchauhan0022** [comment]
/assing @JorTurFer can you please share the link for 

> Even it's documented the proper way to add entries in the changelog

**Comment by JorTurFer** [comment]
https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#Changelog
