### ISSUE TITLE
Templates name aren't clear in the output in the error log for the latest e2e testing.

### ISSUE THREAD

**Issue by Ritikaa96** [kedacore/keda#3192]
### Report

While doing negative testing on the latest migrated code for the e2e testing, the output for a test with erroneous template was this: 
 
`cannot apply file - error: error parsing /tmp/tempTemplateFile393652011: error converting YAML to JSON: yaml: line 31: could not find expected ':'`

This proves to be confusing in case we have scalers with multiple templates.

### Expected Behavior

The expected behavior was something like this:

`cannot apply file - error: error parsing /tmp/deploymentTemplateFile393652011: error converting YAML to JSON: yaml: line 31: could not find expected ':'`

or as mentioned by @JorTurFer it could also be printing the template itself in the error log.

### Actual Behavior

The error log doesn't provide clarity to which exact template file is causing error and the error is like this:

```	
Error Trace:	helper.go:170
        	            				helper.go:178
        	            				helper.go:209
        	            				cpu_test.go:127
        	Error:      	Received unexpected error:
        	            	error: error parsing /tmp/tempTemplateFile1287392103: error converting YAML to JSON: yaml: line 31: could not find expected ':'
```

### Steps to Reproduce the Problem

1. make an error in templateFile.
2. Run go test on the test file with : `go test -v ./scalers_go/scalerName/scalerName_test.go`
3. find the error in output

### Logs from KEDA operator

None

### KEDA Version

2.7.1

### Kubernetes Version

1.23

### Platform

Any

### Scaler Details

Any

**Comment by Ritikaa96** [comment]
@JorTurFer @zroubalik @arschles WDYT?

**Comment by JorTurFer** [comment]
BTW, are you willing to contribute with this?

**Comment by v-shenoy** [comment]
I think having a template name parameter in the function is not that bad of an idea. I was thinking something like this -
```diff
- func KubectlApplyWithTemplate(t *testing.T, data interface{}, config string) {
+ func KubectlApplyWithTemplate(t *testing.T, data interface{}, templateName, config string) {
	tmpl, err := template.New("kubernetes resource template").Parse(config)
	assert.NoErrorf(t, err, "cannot parse template - %s", err)

-	tempFile, err := ioutil.TempFile("", "tempTemplateFile")
+       tempFile, err := ioutil.TempFile("", templateName)
	assert.NoErrorf(t, err, "cannot create temp file - %s", err)

	defer os.Remove(tempFile.Name())

	err = tmpl.Execute(tempFile, data)
	assert.NoErrorf(t, err, "cannot insert data into template - %s", err)

	_, err = ExecuteCommand(fmt.Sprintf("kubectl apply -f %s", tempFile.Name()))
	assert.NoErrorf(t, err, "cannot apply file - %s", err)

	err = tempFile.Close()
	assert.NoErrorf(t, err, "cannot close temp file - %s", err)
}

- func KubectlApplyMultipleWithTemplate(t *testing.T, data interface{}, configs ...string) {
- for _, config := range configs {
+ func KubectlApplyMultipleWithTemplate(t *testing.T, data interface{}, configs map[string]string) {
+	for name, config := range configs {
		KubectlApplyWithTemplate(t, data, name, config)
	}
}
```

**Comment by Ritikaa96** [comment]
> BTW, are you willing to contribute with this?

hi @JorTurFer , i might have missed the comment here, sure I'd love to work on it. if @v-shenoy don't mind? any suggestion is also appreciated of how we can improve this even more.

**Comment by v-shenoy** [comment]
> > BTW, are you willing to contribute with this?
> 
> hi @JorTurFer , i might have missed the comment here, sure I'd love to work on it. if @v-shenoy don't mind? any suggestion is also appreciated of how we can improve this even more.

Yes, please take it up. I was just adding my thoughts.

**Comment by Ritikaa96** [comment]
Thanks @v-shenoy

**Comment by Ritikaa96** [comment]
Hi @JorTurFer the changes according to what @v-shenoy and I proposed earlier look like [this](https://github.com/kedacore/keda/compare/main...Ritikaa96:template-variable-for-e2e-log)

**Comment by Ritikaa96** [comment]
And there is another simple way to give a hint to the developer about which template file created the error.
We can add tags to the templateFile name itself, as the multipleTemplateFiles are always applied in sequence it's easier.

[Here](https://github.com/kedacore/keda/commit/4d337c250db2c4732b40b87d711047ee10632828) are the changes needed.

**Comment by Ritikaa96** [comment]
Please let me know what you think.

**Comment by v-shenoy** [comment]
The problem I feel with the approach of using an index as the tag is, if you have code like
```go
KubectlApplyMultipleWithTemplate(t, data, []string{secretTemplate, deploymentTemplate})
// some lines of code
// ...
KubectlApplyMultipleWithTemplate(t, data, []string{triggerAuthTemplate, scaledObjectTemplate})
```

Now if there's an error in applying some template the error message might look like
`cannot apply file - error: error parsing /tmp/tempTemplateFile-1#393652011: error converting YAML to JSON: yaml: line 31: could not find expected ':'`

This still doesn't tell you whether the `deploymentTemplate` caused the error or `scaledObjectTemplate` caused the error. You're going to have to check the logs for more context (if there's any) to differentiate.

I would rather have the error message be something like 

`cannot apply file - error: error parsing /tmp/deploymentTemplateFile#393652011: error converting YAML to JSON: yaml: line 31: could not find expected ':'`

**Comment by Ritikaa96** [comment]
> Now if there's an error in applying some template the error message might look like `cannot apply file - error: error parsing /tmp/tempTemplateFile-1#393652011: error converting YAML to JSON: yaml: line 31: could not find expected ':'`
> 
> This still doesn't tell you whether the `deploymentTemplate` caused the error or `scaledObjectTemplate` caused the error. You're going to have to check the logs for more context (if there's any) to differentiate.

Agreed there is not complete clarity. the developer might have to go back to see `tempTemplateFile-1#393652011` and search for the 1st template file as the tag is `1` herethe files are applied as sequence but this method seems to uncertain i agree

**Comment by Ritikaa96** [comment]
@JorTurFer @v-shenoy ,If everyone agrees on the variable approach with exact name of template, then i'll continue doing the required changes in other *_test.go files

**Comment by JorTurFer** [comment]
If you think that it's the best approach, we can give a try. Maybe I'm overthinking and one extra parameters it's not a problem at all, and in case of if it is, we can rethink this in the future.

**Comment by v-shenoy** [comment]
There's one issue that I have noticed cause due to the use of `map` for template names, and config. When multiple templates are applied / deleted, they're done by iterating over the keys of the map. But the order of keys when iterating is not same as the order of dependencies.

As an example, when applying the order should be secret -> deployment -> trigger auth -> scaled object
And the reverse order when deleting.

This causes multiple error messages showing up in the operator logs when testing. If this is a problem in itself or not, is up for question.

What do you think, @JorTurFer?

**Comment by JorTurFer** [comment]
mmm...
It's true that doesn't affect to the test, but it's hard to read the logs when you are troubleshooting... Maybe we can iterate the values in the opposite order in case of deletion. WDYT?

**Comment by v-shenoy** [comment]
This will require changes to the apply / delete multiple method signature, and all the tests that are currently there. We should pick a consistent signature that would not require changes in the future. @JorTurFer @Ritikaa96

**Comment by v-shenoy** [comment]
This is kind of my bad, as I suggested the map approach and forgot about the iteration order.

**Comment by JorTurFer** [comment]
> This is kind of my bad, as I suggested the map approach and forgot about the iteration order.

don't worry, we are iterating to figure out the best solution. You have done an awesome work, really!!
