### ISSUE TITLE
Create a samples GitHub repo

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda#321]
[Jeff suggested](https://github.com/kedacore/keda/issues/239#issuecomment-521448870) before that we might need a dedicated repo for listing all the samples out there - Either part of the org or externally.

This allows folks to just send a PR rather than having to create an issue and ask somebody to list it.

I'm happy to pick this up and create a new repo.

**Comment by anirudhgarg** [comment]
Jeff created this repo and I have trasferred all known samples to a readme in that repo.

**Comment by tomkerkhove** [comment]
That's great!

We've once discussed this during the standup but should we assign owners per sample to know whom to contact?

/cc @jeffhollan
