### ISSUE TITLE
Migrate e2e test for Cron to Go.

### ISSUE THREAD

**Issue by Ritikaa96** [kedacore/keda#3217]
### Proposal

Relates to https://github.com/kedacore/keda/issues/2357, https://github.com/kedacore/keda/issues/2737.

**Comment by Ritikaa96** [comment]
Hi @keda-core-contributors @tomkerkhove. I might as well work on it. Please let me know if we were waiting on something to add it into the migration list.

**Comment by tomkerkhove** [comment]
We're definitely happy to review PRs on this - Thanks!
