### ISSUE TITLE
Migrate e2e test for Cassandra to Go

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda#3231]
### Proposal

Relates to https://github.com/kedacore/keda/issues/2357, https://github.com/kedacore/keda/issues/2737.

**Comment by aviadlevy** [comment]
Unfortunately, I'm having trouble initiating Cassandra in my minikube on my personal laptop.

This is the progress I have so far and it should work, but I wasn't able to verify 1 cycle end to end: https://github.com/aviadlevy/keda/tree/e2e_cassandra 

not sure how to proceed from here.
@zroubalik , do you think I can open a PR and we'll test it there? do you have any other suggestion?

**Comment by zroubalik** [comment]
@aviadlevy sure this, open a PR and we can iterate there, thanks for the work!
