### ISSUE TITLE
Migrate e2e test for InfluxDB  to Go

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda#3237]
### Proposal

Relates to https://github.com/kedacore/keda/issues/2357, https://github.com/kedacore/keda/issues/2737.

**Comment by Ritikaa96** [comment]
Hi @tomkerkhove, I'll take this up if no one's working on it already

**Comment by JorTurFer** [comment]
@Ritikaa96 , are you on this? if not, I'll tackle it

**Comment by Ritikaa96** [comment]
> @Ritikaa96 , are you on this? if not, I'll tackle it

Hey @JorTurFer , Sorry for missing out on your comment, yes im working on this one. if you have already started working you can take it up.

**Comment by JorTurFer** [comment]
Do you think that you could add the activation feature too? We plan to do a release aiming to the end of next week and we'd like to have that feature implemented. If you don't have time, it's not a problem at all, no pressure from our side, we can tackle it before the release if next week you haven't had time 😄

**Comment by Ritikaa96** [comment]
are you talking about this one: https://github.com/kedacore/keda/issues/2800 ? I might need a little reference but I'll definitely try adding this feature. if you have any other references please let me know.

**Comment by JorTurFer** [comment]
hey @Ritikaa96 ,
Sure, these are some samples:
https://github.com/kedacore/keda/pull/3408
https://github.com/kedacore/keda/pull/3405
https://github.com/kedacore/keda/pull/3402

**Comment by JorTurFer** [comment]
Once you have migrated the e2e test, the changes are quite easy :)

**Comment by Ritikaa96** [comment]
> Once you have migrated the e2e test, the changes are quite easy :)

Thanks @JorTurFer , i'm on it.
