### ISSUE TITLE
Migrate e2e test for Kubernetes Workload to Go

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda#3239]
### Proposal

Relates to https://github.com/kedacore/keda/issues/2357, https://github.com/kedacore/keda/issues/2737.

**Comment by Ritikaa96** [comment]
Hi @tomkerkhove I'd like to work on this one if no one's working on it already.

**Comment by Ritikaa96** [comment]
Hi @tomkerkhove I'd like to work on this one if no one's working on it already.

**Comment by tomkerkhove** [comment]
Awesome, thank you @Ritikaa96!
