### ISSUE TITLE
Migrate e2e test for NewRelic to Go

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda#3244]
### Proposal

Relates to https://github.com/kedacore/keda/issues/2357, https://github.com/kedacore/keda/issues/2737.

**Comment by pragmaticivan** [comment]
Can I take this one?

**Comment by ivan-santos-eq** [comment]
Howdy! I made some progress, but have not finished yet. Sorry for the delay (and by commenting with a different account 😂 )

**Comment by pragmaticivan** [comment]
@zroubalik PR opened.
