### ISSUE TITLE
Resources required for e2e tests concerning permission segregation.

### ISSUE THREAD

**Issue by v-shenoy** [kedacore/keda#3262]
Require some new Azure resources for e2e tests -

1. Azure Service Bus instance with connection string in workflow env (AZURE_SERVICE_BUS_CONNECTION_STRING_ALT?)
2. Azure AD Application with client id present in workflow env (AZURE_SP_APP_ID_ALT?). This app should have Azure Service Bus Data Receiver permissions on the above created service bus instance.
3. There is already an Azure AD Application used by the e2e tests. Copy over the federated credentials from the old application to the new application (Note - Do not remove them from the old app, just add them to the new one as well)..

Relates to https://github.com/kedacore/keda/issues/2656, https://github.com/kedacore/keda/pull/3216

**Comment by tomkerkhove** [comment]
I'll pick this up tomorrow!
