### ISSUE TITLE
Support `readOnlyRootFilesystem=true` in KEDA metric adapter

### ISSUE THREAD

**Issue by joebowbeer** [kedacore/keda#3292]
### Proposal

Configure `keda-metrics-apiserver` to run with `readOnlyRootFilesystem=true`, or at least document how to configure this.

See [suggested solution](https://github.com/kedacore/keda/discussions/2880#discussioncomment-2686676) in discussion #2880

Relates to #2938 which [omitted](https://github.com/kedacore/keda/blob/main/config/metrics-server/deployment.yaml#L71-L72) this setting from `keda-metrics-apiserver`

### Use-Case

Enable KEDA to pass security audit.

While `readOnlyRootFilesystem=true` is not required by PSS/restricted, it is a recommended security best practice and may be required by other policies.

**Comment by tomkerkhove** [comment]
I will let @zroubalik determine if we want to do this, because from what I'm seeing on https://github.com/kedacore/keda/discussions/2880 this is something that the end-user has to do and we should provide better docs on.

We cannot run KEDA with full readOnlyRootFilesytem as far as I know.

**Comment by joebowbeer** [comment]
@tomkerkhove in #2880 @zroubalik asked for someone to create a doc PR.

@ygnr was able to [accomplish this](https://github.com/kedacore/keda/discussions/2880#discussioncomment-2686676) by setting mountPath to `/apiserver.local.config/certificates/`

```
--set volumes.metricsApiServer.extraVolumes[0].name=keda-volume
--set volumes.metricsApiServer.extraVolumeMounts[0].name=keda-volume
--set volumes.metricsApiServer.extraVolumeMounts[0].mountPath=/apiserver.local.config/certificates/
```

and then setting readOnlyRootFilesystem to true in the securityContext of metricServer

**Comment by zroubalik** [comment]
Yeah, it is partly covered in FAQ: https://keda.sh/docs/2.7/faq/

Though we can definitely improve it, @joebowbeer mind opening a RP on https://github.com/kedacore/keda-docs with changes that will make it more clear for you?

**Comment by joebowbeer** [comment]
Created PR https://github.com/kedacore/keda-docs/pull/830 to improve FAQ answer
