### ISSUE TITLE
Provide support for explicitly pausing autoscaling of ScaledJobs

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda#3303]
### Proposal

Provide support for explicitly pausing autoscaling of ScaledJobs so that it no longer spins up new jobs.

This should be done by applying the `autoscaling.keda.sh/paused: true` annotation on the ScaledJobs resource.

### Use-Case

Avoid scaling when:
- Cluster is having resource starvation
- Doing maintenance
- ...

### Anything else?

Follow-up for https://github.com/kedacore/keda/issues/944

**Comment by tomkerkhove** [comment]
Thank you @keeganwinchester-shipt!

**Comment by zroubalik** [comment]
`autoscaling.keda.sh/is-paused: true` - I personally don't like the `is-` part of this at all. It gives me an impression that it describes a state rather than setting the action.

I'd use `autoscaling.keda.sh/paused: true` instead

@tomkerkhove @JorTurFer ^^

**Comment by tomkerkhove** [comment]
Fine by me, I thought that was what we agreed on but I'll update the spec

**Comment by JorTurFer** [comment]
I agree

**Comment by tomkerkhove** [comment]
This is being worked on by @flux-benj in https://github.com/kedacore/keda/issues/3303
