### ISSUE TITLE
Change runtime to provide access to deployed TriggerAuthentication CRDs

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda#331]
Change runtime to provide access to deployed TriggerAuthentication CRDs so that scalers can access them for retrieving authentication information.

This allows scalers to just use the parameters rather than having to lookup all the CRDs themselves.

This is a follow-up action for #307

**Comment by tomkerkhove** [comment]
If I remember correctly you were going to work on this @patnaikshekhar, is that correct?

**Comment by patnaikshekhar** [comment]
Yes, @tomkerkhove I'll create a pull request for it this week
