### ISSUE TITLE
Set metric to null if target metric read is missing or scaledObject is removed

### ISSUE THREAD

**Issue by nvtkaszpir** [kedacore/keda#3326]
### Proposal

If scaledObject is removed, then corresponding label is removed from exposed via keda-operator-metrics-apiserver (under metrics: 9022/TCP) which are scraped by Prometheus (via PodMonitor).

### Use-Case

We have a KEDA running and scaling based on metric scraped from service which exposes metric as JSON.

Now because we create/delete scaledObject per namespace and we create/delete namespaces in CI/CD system, then after some time given scaledObjects are experiencing errors of read timeout usually due to service being removed and after a moment the scaledObject is removed (together with the namespace itself).

We scrape KEDA with prometheus so we get metrics per scaledObject, this works fine.
But as a result the objects are added/removed in kubernetes, the metrics or removed objects are not cleared -  they are in KEDA and are still scraped by Prometheus.

So as a result we have let say 20 namespaces but also over 300 metrics per scaledObject labels, from already deleted namespaces.

### Anything else?
This is especially irritating in on-prem setups where KEDA pod can work for weeks without restarts and the number of namespaces/scaledObjects is high due to daily development cycles.

Current workaround for us is to delete keda-operator-metrics-apiserver pod, so that the labels are auto-removed.
This also helps to decrease memory usage of the pod.

KEDA: 2.7.1

**Comment by JorTurFer** [comment]
Hey,
It sounds totally legit. 
Are you willing to contribute it?

**Comment by nvtkaszpir** [comment]
sorry, but no - I have no experience in KEDA source code at all.

**Comment by JorTurFer** [comment]
okey, np at all 😄

**Comment by ShineSmile** [comment]
Sorry, I found that there is no other metrics could be found besides *keda_metrics_adapter_scaler_errors_total*. I have confirmed that there is a ScaledObject working in the cluster. 
![image](https://user-images.githubusercontent.com/8800442/182587598-fc944e5d-75a9-496e-bad1-3177f3bf2a62.png)

Helm Chart version 2.7.2
I think it is caused by there is no error just occurred for exist ScaledObject until now. I may contribute this via weekend.

**Comment by zroubalik** [comment]
@ShineSmile cool thanks, just FYI, we plan to do release next week (Aug 10), so if you happen to fix this before the release, we can include it in.

**Comment by ShineSmile** [comment]
> @ShineSmile cool thanks, just FYI, we plan to do release next week (Aug 10), so if you happen to fix this before the release, we can include it in.


@zroubalik Sorry, I'm afraid I couldn't catch up with it. Please give me one more iteration.

**Comment by JorTurFer** [comment]
I close this because it's inactive
