### ISSUE TITLE
azure pipeline agents don't always remove

### ISSUE THREAD

**Issue by BenH-Puregym** [kedacore/keda#3335]
### Report

i've got scaledjob setup and a placeholder agent in ADO. Sometimes the agents are remove when their job is finished and sometimes they're not. Some agents which don't get removed will have a job lasting 13 minutes and others 1hr so doesn't seem to be consistent.  

### Expected Behavior

the agents should remove each time a job has finished

### Actual Behavior

some do, some don't. leaving the pool with tons of offline agents.

### Steps to Reproduce the Problem

1. setup a pipeline scaledjob with 10/20 containers
2. run a unit test pipeline or similar which has 10 parallel jobs
3. repeat a few times and you will see the agents being left.

### Logs from KEDA operator

```
example
```

### Platform

Microsoft Azure

### Scaler Details

pipeline

**Comment by JorTurFer** [comment]
hey,
Is the agent pod finishing? I mean, KEDA doesn't know if the pod has finished or not its work, KEDA removes the pod/job once it has finished with success or failure, so if your pod is still alive without finishing (like a job should do), KEDA will not remove it

**Comment by BenH-Puregym** [comment]
Hey  @JorTurFer , So the agent is left in an offline state in the ADO agent pool but when you check back in AKS, the pod is no longer there so requires to be manually removed from ADO.

**Comment by JorTurFer** [comment]
Just to clarify it, it's your problem related with agent pods not deleted from the AKS or with orphan agent in Azure DevOps?

**Comment by BenH-Puregym** [comment]
maybe would be best for me to explain the problem again:
job is run on ADO
keda starts jobs and adds pods to the ADO pool
job finishes on ADO
keda deletes the pod and stops the job
agents still exist in ADO pool as offline

**Comment by JorTurFer** [comment]
hey, 
I got it. KEDA doesn't handle ADO at all, the only goal of KEDA is to make the autoscaling dead simple, but not to manage the upstreams. 
I mean, in the same way that you register the agent by yourself in AzDO (it does automatically on pod agent) you should unregister it. My suggestion is to unregister the agent after executing the pipeline, before finishing the job execution.
