### ISSUE TITLE
Allow overriding EndpointUrl for AWS-related scalers

### ISSUE THREAD

**Issue by barndawe** [kedacore/keda#3337]
### Proposal

AWS Go SDK client allows for passing in an EndpointUrl parameter to override the AWS endpoint url (see [Config struct for AWS client](https://docs.aws.amazon.com/sdk-for-go/api/aws/#Config). Currently Keda does not allow for specifying this, e.g. for the SQS scaler, so it is not possible to run Keda against anything but full-fat AWS.

### Use-Case

Adding the ability to override the EndpointUrl would allow Keda to be pointed at a Localstack SQS queue ([https://docs.localstack.cloud/aws/sqs/](https://docs.localstack.cloud/aws/sqs/)).

**Comment by tomkerkhove** [comment]
Makes sense, are you willing to contribute this?

**Comment by aviadlevy** [comment]
> Makes sense, are you willing to contribute this?

I can take a look if the issue reporter don't want to (I think we can give him few more days to respond)

**Comment by yuyuvn** [comment]
@aviadlevy 

did you start to do it? (or still want to do it?)
It was a few months and I don't see any response from reporter...

**Comment by aviadlevy** [comment]
> @aviadlevy 
> 
> did you start to do it? (or still want to do it?)
> It was a few months and I think we don't have any response from reporter...
> I can do it if no one going to do

I didn't start working on that. Feel free to take it
