### ISSUE TITLE
Change Azure Event Hubs trigger to use new authentication approach

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda#334]
The Azure Event Hubs trigger should be changed so that it uses the new authentication approach documented in the [spec](https://github.com/kedacore/keda/blob/master/spec/triggers/README.md#authentication).

This includes:
- Changing the scaler to retrieve the authentication information from the configured [`TriggerAuthentication` CRD](https://github.com/kedacore/keda/blob/master/spec/TriggerAuthentication.md)
- Update the trigger spec to list what parameters should be configured in the [`TriggerAuthentication` CRD](https://github.com/kedacore/keda/blob/master/spec/TriggerAuthentication.md).

The KEDA core runtime provides access to the deployed `TriggerAuthentication` CRDs via #331.

As part of this change, we should support AAD Pod Identity (#161).

This is a follow-up action for #307

**Comment by tomkerkhove** [comment]
@ahmelsayed Did we finish this already? I think so but not sure

**Comment by tomkerkhove** [comment]
What's the status here?

**Comment by tdesmet** [comment]
@tomkerkhove I see you closed this, but I don't see any support for pod identity with event hub in the documentation or the code...

**Comment by tomkerkhove** [comment]
Trigger Authentication is just the decoupling of the scaler and how to authenticate so it was not in scope here but feel free [to suggest it](https://github.com/kedacore/keda/issues/new?labels=needs-discussion%2Cfeature-request&template=Feature_request.md)
