### ISSUE TITLE
Change Azure Storage Queue trigger to use new authentication approach

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda#335]
The Azure Storage Queue trigger should be changed so that it uses the new authentication approach documented in the [spec](https://github.com/kedacore/keda/blob/master/spec/triggers/README.md#authentication).

This includes:
- Changing the scaler to retrieve the authentication information from the configured [`TriggerAuthentication` CRD](https://github.com/kedacore/keda/blob/master/spec/TriggerAuthentication.md)
- Update the trigger spec to list what parameters should be configured in the [`TriggerAuthentication` CRD](https://github.com/kedacore/keda/blob/master/spec/TriggerAuthentication.md).

The KEDA core runtime provides access to the deployed `TriggerAuthentication` CRDs via #331

As part of this change, we should support AAD Pod Identity (#161).

This is a follow-up action for #307

**Comment by ahmelsayed** [comment]
https://github.com/kedacore/keda/pull/380

**Comment by tomkerkhove** [comment]
@ahmelsayed I see that the old approach is still included here:
https://github.com/kedacore/keda/blob/master/spec/triggers/azure-storage-queue.md

Is that for sake of keeping docs for older versions or?

We might want to re-open this one to update the samples:
- https://github.com/kedacore/keda/blob/master/examples/azurequeue_scaledobject_jobs.yaml
- https://github.com/kedacore/keda/blob/master/examples/azurequeue_scaledobject.yaml
