### ISSUE TITLE
Change Azure Service Bus Queue trigger to use new authentication approach

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda#336]
The Azure Service Bus Queue trigger should be changed so that it uses the new authentication approach documented in the [spec](https://github.com/kedacore/keda/blob/master/spec/triggers/README.md#authentication).

This includes:
- Changing the scaler to retrieve the authentication information from the configured [`TriggerAuthentication` CRD](https://github.com/kedacore/keda/blob/master/spec/TriggerAuthentication.md)
- Update the trigger spec to list what parameters should be configured in the [`TriggerAuthentication` CRD](https://github.com/kedacore/keda/blob/master/spec/TriggerAuthentication.md).

The KEDA core runtime provides access to the deployed `TriggerAuthentication` CRDs via #331

As part of this change, we should support AAD Pod Identity (#161).

This is a follow-up action for #307

**Comment by jeffhollan** [comment]
@ahmelsayed or @SatishRanjan was this one you already did? Or are doing?

**Comment by tomkerkhove** [comment]
Reopening for https://github.com/kedacore/keda/pull/450 & https://github.com/kedacore/keda/pull/450

**Comment by jeffhollan** [comment]
Completed, merged in, and documented
