### ISSUE TITLE
Increase limit for scaler metric value

### ISSUE THREAD

**Issue by jrehnen** [kedacore/keda#3364]
### Proposal

Currently, the maximum value of a scaler metric (at least for Azure EventHub) is 6400. If there are more unprocessed events in the hub, the value is capped at 6400 instead. I'd like to have this cap removed or increased.

### Use-Case

While the precise number of unprocessed events becomes irrelevant at higher numbers, it is still very relevant whether it decreases or increases over time.
The screenshot below plots the scaler metric value of a subscriber microservice after I removed its checkpoints.

![grafik](https://user-images.githubusercontent.com/94835791/178924660-0b982318-7ca0-4f47-9dc3-06e240a00801.png)
Up until the number of unprocessed events reduced to below 6400, I was not able to detect any change.

**Comment by JorTurFer** [comment]
I have checked the code and I think KEDA doesn't limit it.
I'd say that it's a limitation of the `Azure EventHub` itself or in the configuration (or maybe the underlying SDK limits it 🤔 ). 
@tomkerkhove ?

**Comment by JorTurFer** [comment]
Do you know if there is any limit @v-shenoy ?

**Comment by JorTurFer** [comment]
@jrehnen , Any update here?
I'll remove the tag and the issue will be closed by inactivity if there isn't any answer
