### ISSUE TITLE
docker logs are going into Datadog as ERROR

### ISSUE THREAD

**Issue by biohazd** [kedacore/keda#3365]
In Datadog the Dcoker logs are showing as ERROR

1.657708213349751e+09	INFO	scaleexecutor	Scaling Jobs	{"scaledJob.Name": "azdevops-scaledjob-build-agents-java", "scaledJob.Namespace": "default", "Number of pending Jobs ": 0}

## Expected Behavior
The logs should show as INFO

## Actual Behavior
Logs are showing as ERROR logs

## Steps to Reproduce the Problem

  1.
  2.
  3.

## Specifications

  - **KEDA Version:** *Please elaborate*
  - **Platform & Version:** *Please elaborate*
  - **Kubernetes Version:** *Please elaborate*
  - **Scaler(s):** *Please elaborate*

**Comment by biohazd** [comment]
I'm not sure if you can fix it on the KEDA side.   Im happy with my solution.

Do the Docker logs goto STDERR or STDOUT ?

**Comment by Wildpipe** [comment]
I'm encountering this issue as well. Do you mind providing the configuration for the GROK parser to fix this @biohazd ?

**Comment by Wildpipe** [comment]
Thank you!

**Comment by Wildpipe** [comment]
I'm also recieving lines like these where Datadog sees them as one unique message per line:

```
github.com/kedacore/keda/v2/pkg/scalers.(*activeMQScaler).IsActive
/workspace/pkg/scalers/activemq_scaler.go:149
github.com/kedacore/keda/v2/pkg/scaling/cache.(*ScalersCache).IsScaledObjectActive
/workspace/pkg/scaling/cache/scalers_cache.go:87
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).checkScalers
/workspace/pkg/scaling/scale_handler.go:278
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).startScaleLoop
/workspace/pkg/scaling/scale_handler.go:149
```

I'm guessing these lines are part of the stacktrace to whatever went wrong and should be submitted as a multiline log to Datadog. I think part of the problem here is that Datadog does not provide an out-of-the-box parser for the keda service as they do to many other services.

**Comment by tomkerkhove** [comment]
@zroubalik We're writing to STDOUT right?

**Comment by zroubalik** [comment]
@tomkerkhove yeah

**Comment by pauliusg** [comment]
> Sure, its not clean, but it works
> 
> GROK rule: `rule1 %{numberExtStr:first}\t%{word:second}\t.*`
> 
> Then a "status remap rule" Set status attribute(s) `second`

I improved GROK rules: 
```
rule1 %{date("yyyy-MM-dd'T'HH:mm:ssZZ"):date}\t%{word:level}\t%{word:codeFile}\t%{regex(".*?"):message}\t%{data::json}\t%{regex(".*?"):stack}
rule2 %{date("yyyy-MM-dd'T'HH:mm:ssZZ"):date}\t%{word:level}\t%{regex(".*?"):message}\t%{data::json}
```
Then:
- added `Date Remapper` on: `date`
- added `Status Remapper` on: `level`
- added `Remapper`: `scaledObject.Namespace -> namespace`
- added `Remapper`: `object.namespace -> namespace`
- added `Remapper`: `object.name -> name`
- added `Remapper`: `scaledobject.Name -> name`
- added `String Builder Processor` on: `message` with value `%{message} - %{name}`
- added `Message Remapper` on: `message`
