### ISSUE TITLE
Migrate from azure-service-bus-go to azservicebus

### ISSUE THREAD

**Issue by amirschw** [kedacore/keda#3394]
### Proposal

The azure-service-bus-go package [was replaced](https://github.com/Azure/azure-service-bus-go#readme)  by the new azservicebus package. It is recommended to migrate to the new package. Migration guide: https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/messaging/azservicebus/migrationguide.md/

### Use-Case

Azure service bus scaler

**Comment by JorTurFer** [comment]
we need to use [golang 1.18](https://github.com/kedacore/keda/issues/3205) before because tnhe new pkg requires 1.18. It's in my radar to update the library once we use go 1.18

**Comment by RamCohen** [comment]
I can do that once it's possible

**Comment by JorTurFer** [comment]
Nice!
Maybe after next release we can take a look. AFAIR, there are problems related with the golint because some chacks are not ported due to a limitation in some libraries

**Comment by amirschw** [comment]
Hey @JorTurFer, are there any other blockers or can this be started now that #3653 is merged?

**Comment by JorTurFer** [comment]
> Hey @JorTurFer, are there any other blockers or can this be started now that #3653 is merged?

It's already done here :smile:
https://github.com/kedacore/keda/pull/3639

**Comment by amirschw** [comment]
Cool! Missed the reference 😀
