### ISSUE TITLE
Change Redis trigger to use new authentication approach

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda#342]
The Redis trigger should be changed so that it uses the new authentication approach documented in the [spec](https://github.com/kedacore/keda/blob/master/spec/triggers/README.md#authentication).

This includes:
- Changing the scaler to retrieve the authentication information from the configured [`TriggerAuthentication` CRD](https://github.com/kedacore/keda/blob/master/spec/TriggerAuthentication.md)
- Update the trigger spec to list what parameters should be configured in the [`TriggerAuthentication` CRD](https://github.com/kedacore/keda/blob/master/spec/TriggerAuthentication.md).

The KEDA core runtime provides access to the deployed `TriggerAuthentication` CRDs via #331

This is a follow-up action for #307

**Comment by balchua** [comment]
Im interested in taking this up, if we have some samples or getting started guide, that will be great.

**Comment by balchua** [comment]
This can now be closed after merging #441 .

**Comment by balchua** [comment]
I think we can close this one.  Tom has aligned the docs already in this merged pr.
https://github.com/kedacore/keda-docs/commit/f37cc0b273e3ae7a45b1f3ca66beaf2baba9f700

**Comment by tomkerkhove** [comment]
You are correct, thanks!
