### ISSUE TITLE
Support Kafka SASL MSK IAM authentication

### ISSUE THREAD

**Issue by pragmaticivan** [kedacore/keda#3431]
### Proposal

MSK (Kafka Managed Services from AWS) supports IAM for authentication via SASL.

ref: https://github.com/segmentio/kafka-go/issues/661

### Use-Case

ServiceAccount should be able to be used for Kafka authentication.

**Comment by tomkerkhove** [comment]
Fair ask! Are you willing to contribute this?

**Comment by pragmaticivan** [comment]
I might be able to help but will take quite some time (Still refreshing my skills with go) 😂 If anyone else has the need for this feature asap.

**Comment by pragmaticivan** [comment]
Should this be closed? 
cc @zroubalik

**Comment by Manicben** [comment]
Understand that the experimental scaler is based on kafka-go and supports MSK IAM via the custom SASL mechanism, but just as an FYI, AWS released an alternative based on SASL-OAUTHBEARER which works with all Go-based Kafka libraries.

Just wanted to highlight this in case it made any difference to the future of the non-experimental and experimental Kafka scalers.

[AWS announcement from Nov 2023](https://aws.amazon.com/blogs/big-data/amazon-msk-iam-authentication-now-supports-all-programming-languages/)
[GH repo](https://github.com/aws/aws-msk-iam-sasl-signer-go) including examples for Sarama

**Comment by JorTurFer** [comment]
@dttung2905 @zroubalik . Wasn't the support to MSK IAM the only reason for the new scaler? I mean, could we unify both into the original one adding support to MSK IAM thanks to this?

**Comment by dttung2905** [comment]
@JorTurFer sorry for the late reply. Its been a busy week for me. Iirc, supporting MSK IAM was a main reason, besides better support and documentation as outlined in https://github.com/kedacore/keda/issues/4692.

What's our policy when it comes to deprecating scaler ? Do we follow N-2 cycle too? I took at look at the doc but its not clear too me on scaler deprecation https://github.com/kedacore/governance/blob/main/DEPRECATIONS.md

**Comment by JorTurFer** [comment]
The first step is to figure out if the experimental scaler brings extra features (not only now but also in the future) or its just for AWS

**Comment by dttung2905** [comment]
> The first step is to figure out if the experimental scaler brings extra features (not only now but also in the future) or its just for AWS
Its a really good point to bring up during our next community meet up! We can discuss more indept there :muscle:
