### ISSUE TITLE
Keda scaler for blob trigger

### ISSUE THREAD

**Issue by ReneeRuth** [kedacore/keda#3433]
Hi,
We have configured a blob trigger which should be trigged when we upload any files to Folder1 or Folder2 (SubFolders).
This is my blob container structure:

ContainerName
   |__ FolderA
            |__ Folder1
                    |__test1.csv
                    |__test2.csv
            |__ Folder 2
                    |__ test.csv 

We were using KEDA scaled object for deployment

apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "test.scaledobjectname" . }}
spec:
  advanced:                                      
    restoreToOriginalReplicaCount: true
  scaleTargetRef:
    name: {{ include "test.name" . }}
  triggers:
  - type: azure-blob
    metadata:
      blobContainerName: {{ .Values.containerName }}
      connectionFromEnv: TestAppConnectionString
      globPattern: "FolderA/Folder1/*.csv"

Keda is not scaling when we upload the files to the sub folders. We also tried with blob prefix and blob delimiter and KEDA is not scaling the pods.
Could someone please help with the trigger metadata values?

**Comment by v-shenoy** [comment]
Could you post logs from the operator pod?

**Comment by ReneeRuth** [comment]
I can see that the installed KEDA Version: 2.4.0. 
How do I upgrade to the latest?

**Comment by v-shenoy** [comment]
The `globPattern` parameter for blob trigger was introduced in KEDA 2.7.

**Comment by ReneeRuth** [comment]
It worked fine after upgrading the version to 2.7.1. Thanks :) 
Is there a more elegant way of upgrading the version to the latest apart from having to run the below uninstall commands?
kubectl delete $(kubectl get scaledobjects,scaledjobs -oname)
helm uninstall keda -n keda

**Comment by v-shenoy** [comment]
I think [helm upgrade](https://helm.sh/docs/helm/helm_upgrade/) should work.
