### ISSUE TITLE
Migrate e2e test for `Value metricType` to Go 

### ISSUE THREAD

**Issue by JorTurFer** [kedacore/keda#3435]
### Proposal

Relates to https://github.com/kedacore/keda/issues/2357, https://github.com/kedacore/keda/issues/2737.

### Anything else?

We should port this test to another simpler upstream to check it as internal feature
https://github.com/kedacore/keda/blob/main/tests/scalers/prometheus-value-metric-type.test.ts

**Comment by zroubalik** [comment]
+1 probably using `Kubernetes Workload Scaler` or some similar, that doesn't require addional service.

The current internal e2e tests should be transfered to this simple scaler as well.
