### ISSUE TITLE
ScaledJob "Target Average Value" prometheus

### ISSUE THREAD

**Issue by rh-voice** [kedacore/keda#3438]
### Discussed in https://github.com/kedacore/keda/discussions/3437

<div type='discussions-op-text'>

<sup>Originally posted by **rh-voice** July 27, 2022</sup>
Hi there,

So I am trying to scale some jobs that run agents for our CI/CD; I can read pipeline demand metrics from prometheus (I have an exporter for that); Now this works fine with ScaledObjects; but I am trying to switch those to jobs.

My question is; what the "Target Average Value" attribute for prometheus ? because Threshold is not working; which is expected; it defines the threshold to start scaling for HPA not for spinning up jobs.</div>

**Comment by JorTurFer** [comment]
Let's talk about this in the discussion
