### ISSUE TITLE
Add README / docs on external scaler

### ISSUE THREAD

**Issue by jeffhollan** [kedacore/keda#345]
So people know when use, how to build, etc.

**Comment by gohar94** [comment]
Any instructions on how to build from source? I want to make some source changes and build again. Any instructions for the recommended process to do this would be really helpful, considering this is an open source project and folks from all around should be encouraged to contribute. :)

**Comment by jeffhollan** [comment]
It's a great callout.  @ahmelsayed @Aarthisk @anirudhgarg would be fantastic in advance of KEDA 1.0 you could help write a contributor guide?  Things like:

1. How to build out KEDA to test locally / with your own bits
1. How to build a scaler (any tips, places to start, general guidance on what it is)
1. How to test your bits before opening a PR
1. Any general guidance on what a PR should or should not contain to make merging easier

Any of you 3 able to help with that?

**Comment by jeffhollan** [comment]
Created a contributor guide, added build steps to README, we have a scaler doc on external, and a sample of an external scaler.  Any objections to closing this?
