### ISSUE TITLE
Change workflows to auto-add issues to GitHub Project because of deprecation

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda#3470]
Change workflows to auto-add issues to GitHub Project

https://www.cloudwithchris.com/blog/github-projects-ga-automation-updates/

**Comment by JorTurFer** [comment]
aren't we using GH projects @tomkerkhove ?

**Comment by tomkerkhove** [comment]
Yes, but we need to update our automation

**Comment by tomkerkhove** [comment]
Completed through https://github.com/kedacore/keda/pull/4245
