### ISSUE TITLE
Error updating scaledObject

### ISSUE THREAD

**Issue by sc-chad** [kedacore/keda#350]
```time="2019-09-13T20:03:51Z" level=error msg="Error updating scaledObject (twitter-worker) status: Operation cannot be fulfilled on scaledobjects.keda.k8s.io \"twitter-worker\": the object has been modified; please apply your changes to the latest version and try again"```

I'm getting these messages on pods even after scaling down to zero.  What changes need to be applied here?

**Comment by sc-chad** [comment]
So this looks like it happens from changing something on the scaledobject.  For example if you change the cooldownperiod or add/remove a label.

Once I manually deleted the scaledobject and recreated the errors went away.

**Comment by anirudhgarg** [comment]
Closing this issue.

**Comment by kentonbmax** [comment]
@anirudhgarg should patching scaledobjects be supported? Currently we use ansible to build and deploy out kubernetes manifests.
