### ISSUE TITLE
CPU/MEM percentage in HPA should be based on limits!

### ISSUE THREAD

**Issue by Hello-Linux** [kedacore/keda#3506]
### Proposal

I think the cpu and mem should base on pod limit not request
like this issue https://github.com/kubernetes/kubernetes/issues/72811

**Comment by zroubalik** [comment]
We rely on the upstream HPA implementation, so this change would need to be driven there.

**Comment by Hello-Linux** [comment]
@zroubalik  The official processing speed is very slow. I feel that keda should implement this function by itself. If you rely on them to solve it, you may have to wait until the earth is extinct!

**Comment by zroubalik** [comment]
This would require us to reimplement the whole autoscaler and I don't feel like that's something we should do at the moment. 

@Hello-Linux if you feel the upstream is slow, then I think that sending a PR with the feature might speed up things a little bit :) I can see this feature as a optional setting on HPA, to not break existing stuff. Are you up to implement that?

**Comment by Hello-Linux** [comment]
@zroubalik  Okay, let me urge the official
