### ISSUE TITLE
Produce reproducible builds

### ISSUE THREAD

**Issue by zroubalik** [kedacore/keda#3509]
### Proposal

Produce reproducible builds - we should be able to rebuild the same binary release everytime.

**Comment by JorTurFer** [comment]
Once we fix this, we need to update best practices[ survey to reflect the status](https://github.com/kedacore/governance/issues/8)
FYI @tomkerkhove

**Comment by JorTurFer** [comment]
Do we want this even it's not mandatory? IMO it's a good improvement
