### ISSUE TITLE
Wrong calculation in selenium_grid_scaler when minReplicaCount defined

### ISSUE THREAD

**Issue by lgklkh** [kedacore/keda#3514]
### Report

You have wrong calculation in selenium_grid_scaler. 
`maxSession` and `NodeCount` are the total aggregated indicators for hub (not only from nodes with expected browserName and browserVersion)
For example I have grid:
2 chrome pods, 2 firefox pods and 2 msedge pods. 
NodeCount = 2 chrome + 2 firefox pods + 2 msedge = 6
I set MaxSession=1 for each pod and got maxSession = NodeCount * 1 = 6

I am trying to start 3 chromes on this grid.
Expected result: We see targets 1500m/1 on hpa and the number of replicas increases.
Actual result: We see targets 500m/1 on hpa. The scaler thinks that only half of the sessions are used.

![image](https://user-images.githubusercontent.com/37677396/183097279-3f79726c-9fd5-4b42-bfca-c8dfc1043aa4.png)

To solve the problem you can use `nodesInfo.nodes.stereotypes` to count the number of specific browsers.

### Expected Behavior

We see targets 1500m/1 on hpa and the number of replicas increases.

### Actual Behavior

We see targets 500m/1 on hpa. The scaler thinks that only half of the sessions are used.

### Steps to Reproduce the Problem

1.Deploy selenium grid https://github.com/SeleniumHQ/docker-selenium/tree/trunk/charts/selenium-grid
2.Deploy scalers for each browser with minReplicaCount=2
3.Create 3 chrome sessions

### Logs from KEDA operator

```
example
```

### KEDA Version

2.7.1

### Platform

Microsoft Azure

### Scaler Details

selenium-grid

**Comment by topikachu** [comment]
@lgklkh 
It's fixed at main branch but not released yet.

@JorTurFer Are you going to release a fix? The latest version has a critical bug which makes selenium_grid_scaler doesn't work as expected.

**Comment by JorTurFer** [comment]
> @JorTurFer Are you going to release a fix? The latest version has a critical bug which makes selenium_grid_scaler doesn't work as expected.

Today we will release v2.8

**Comment by JorTurFer** [comment]
[v2.8 is available 🥳 ](https://github.com/kedacore/keda/releases/tag/v2.8.0)
Please update your KEDA version and try again, as @topikachu said, this issue should be already solved. If you still have the problem, feel free to reopen this.
