### ISSUE TITLE
Provide capability to configure a "cluster name" in KEDA for CloudEvents

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda#3532]
### Proposal

Provide the capability to configure a cluster name through an environment variable on the KEDA operator.

Proposal: `KEDA_CLUSTER_NAME` or  `KEDA_CLOUDEVENTS_CLUSTER_NAME`

### Use-Case

Event Sinks allow KEDA end-users to use events as an extension of KEDA by forwarding them to dedicated workloads. These workloads can be located in the same Kubernetes cluster or outside of the cluster on any runtime.

In such a scenario, it often happens that events are aggregated into a centralized workload across clusters where end-users have to be able to distinguish where events come from to better understand what the impact is.

Because of this reason, every event’s subject must be prefixed with `/{kubernetes-cluster-name}/{namespace}/` where `kubernetes-cluster-name` is an end-user friendly name to help understand where the event comes from.

End-users must be able to optionally configure the cluster name during the installation of KEDA. If it is not configured, then `kubernetes-default` will be used.

### Anything else?

Relates to https://github.com/kedacore/keda/issues/479

**Comment by tomkerkhove** [comment]
Thios is done, I believe. @SpiritZhou can you confirm please? From what I recall this was included + Helm chart was updated to allow to configure this?

**Comment by dezmodue** [comment]
Sorry to comment on an old issue - I cannot find any documentation referencing CLUSTER_NAME or any reference to CLUSTER_NAME in the code that seem related to this issue - was this ever implemented? Could you please point me at the documentation? @tomkerkhove @SpiritZhou
