### ISSUE TITLE
Azure storage account queue scaler should allow users to select peek or approximate method

### ISSUE THREAD

**Issue by wallflower762** [kedacore/keda#3555]
### Proposal

Azure storage account queue scaler supports users defining the "peek" or "approximate" methods for evaluating the queue length.

### Use-Case

Using Azure storage account queues to trigger a mix of short and longer running jobs using the [Azure Functions runtime](https://docs.microsoft.com/en-us/azure/azure-functions/functions-kubernetes-keda).

### Anything else?

I have encountered a problem where KEDA ignores invisible messages (messages currently being processed) when evaluating the queue length for an Azure storage account queue. This gives a few outcomes:
- Fewer pods are scheduled than should be as currently in progress messages are not considered
- KEDA scales in pods more aggressively than it should, resulting in in progress messages being interrupted (most commonly encountered with longer running jobs)

A few issues have been raised in the past:
- [Issue 2385](https://github.com/kedacore/keda/issues/2385)
- [Issue 1615](https://github.com/kedacore/keda/issues/1615)

Scaled jobs have been suggested instead for long running tasks, but this doesn't necessarily solve the issues of:
- Excluding in progress messages from the queue count impacts short running jobs as well, it's just more noticeable on longer running jobs
- Users using the [Azure Functions runtime](https://docs.microsoft.com/en-us/azure/azure-functions/functions-kubernetes-keda) to manage trigger lifecycle and per node scaling. To the best of my knowledge this runtime does not offer "execute one message" processing as required for scaled jobs

Based on the discussion in [Issue 2385](https://github.com/kedacore/keda/issues/2385), it would be good if a user has the option to select the peek method, or approximate method.

As noted on [Issue 2385](https://github.com/kedacore/keda/issues/2385), when using Azure functions on an App Service Plan, you can scale based on storage queue length. The implementation Azure has used for this is approximate message count, and does not offer any other method of scaling based on queue length.

A screenshot from the app service plan scale rules GUI:
![184562934-543e0621-dbf4-4e6b-afd6-9a44a17f0831](https://user-images.githubusercontent.com/81551380/184585182-2f6f2f32-d5c9-4a10-871f-89e8b8f7d68b.png)

**Comment by kranthikumar-kvs-by** [comment]
Can't this issue be resolved by using the accurate strategy for sclaed job configuration?
https://github.com/kedacore/keda/pull/1227

**Comment by wallflower762** [comment]
I believe that feature is for `jobs` rather than `deployments`. Please correct me if I have understood

**Comment by wallflower762** [comment]
Leaving a comment to prevent the issue from being closed as stale. This is still critical to use Azure storage queues effectively.

**Comment by wallflower762** [comment]
Issue has been resolved with the above PR!
