### ISSUE TITLE
Keda stuck in error loop calculating lag from kafka

### ISSUE THREAD

**Issue by amit1-100ms** [kedacore/keda#3558]
### Report

We are using keda with kafka scaler(confluent). At same time in different gke clusters, there was probably a network glitch in keda kafka communication. Then keda-operator pod got stuck in error loop in calculating lag from kafka. Same error log in keda operator logs for 6 hours while other kafka consumers were working fine.

### Expected Behavior

Even if there's an error once, keda should calculate correct lag eventually.

### Actual Behavior

Keda operator stuck in calculating error loop, causing kafka scaler to stop functioning. Severe SEV1 on production.

### Steps to Reproduce the Problem

Keda using kafka autoscaler (confluent). Simulate network glitch.

### KEDA Version

2.7.1

### Kubernetes Version

1.23

### Platform

Google Cloud

### Scaler Details

Kafka

### Anything else?

{
msg:
cluster_name:prod
kubernetes:{
container_name:keda-operator
namespace_name:keda
pod_name:keda-operator-7fdbdfd484-h5fw9
container_image:ghcr.io/kedacore/keda:2.7.1
container_image_id:ghcr.io/kedacore/keda@sha256:<removed>
pod_id:<removed>
pod_ip:<removed>
host:<removed>
labels:{
app:keda-operator
name:keda-operator
pod-template-hash:7fdbdfd484
app_kubernetes_io/component:operator
app_kubernetes_io/instance:keda
app_kubernetes_io/managed-by:Helm
app_kubernetes_io/name:keda-operator
app_kubernetes_io/part-of:keda-operator
app_kubernetes_io/version:2.7.1
helm_sh/chart:keda-2.7.2
}
master_url:<removed>
namespace_id:<removed>
namespace_labels:{
name:keda
kubernetes_io/metadata_name:keda
}
}
stacktrace:github.com/kedacore/keda/v2/pkg/scalers.(*kafkaScaler).getLagForPartition
/workspace/pkg/scalers/kafka_scaler.go:368
github.com/kedacore/keda/v2/pkg/scalers.(*kafkaScaler).IsActive
/workspace/pkg/scalers/kafka_scaler.go:255
github.com/kedacore/keda/v2/pkg/scaling/cache.(*ScalersCache).getScaledJobMetrics
/workspace/pkg/scaling/cache/scalers_cache.go:257
github.com/kedacore/keda/v2/pkg/scaling/cache.(*ScalersCache).IsScaledJobActive
/workspace/pkg/scaling/cache/scalers_cache.go:124
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).checkScalers
/workspace/pkg/scaling/scale_handler.go:286
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).startScaleLoop
/workspace/pkg/scaling/scale_handler.go:149
stream:stderr
level:error
logger:kafka_scaler
time:2022-08-15T18:39:53.42022928Z
error:error finding offset block for topic prod and partition 0
ts:1660588793.420116
docker:{
container_id:<removed>
}
}

**Comment by amit1-100ms** [comment]
can anyone check and comment please?

**Comment by kevinnesta** [comment]
Hey @amit1-100ms ,
I've got the same kind of issue from Azure environment.
We do also suspect issue due to network glitch.

the only workaround we found is to restart the KEDA operator deployment (to start a new pod) then all is fine.

Also really interested in a fix on KEDA side.

**Comment by zroubalik** [comment]
Is anybody able to reproduce the issue?

**Comment by amit1-100ms** [comment]
@zroubalik simulating network error on kafka side should reproduce it once in a while
@kevinnesta we had to deploy custom keda code which throws error on this as a stop gap solution. What fix did you guys do?

**Comment by kevinnesta** [comment]
@amit1-100ms we monitor the KEDA operator service logs to trigger automatic restart ...

**Comment by johnnytardin** [comment]
When we run on instances in aws with better network performance the problem does not occur. Example: m5.8xlarge, c6i.8xlarge.
