### ISSUE TITLE
Support Managed identity auth for Blob Storage checkpointing in Event Hub scaler

### ISSUE THREAD

**Issue by andyatwork** [kedacore/keda#3569]
### Proposal

Accessing the blob storage for Event Hubs requires a connection string to be supplied by means of `triggers.metadata.storageConnectionFromEnv` . azure_eventhub_checkpoint.go could be modified to pass the PodIdentity from EventHubInfo with the required account name and endpoint to enable pod identity based authentication.

Suggest to pass PodIdentity to `ParseAzureStorageBlobConnection` and add fields to `trigger.metadata`:

* StorageAccountName - The name of the account

StorageEndpointSuffix is internally resolved from Azure's environment configuration for the specified cloud.

The fqdn blob storage uri is compiled from `https://{StorageAccountName}.blob.{StorageEndpointSuffix}/` .

### Use-Case

Allowing pod identities to be used consistently across Event Hub and Storage Accounts enables connection string free configurations and eliminates the need to manually manage a connection credential.

### Anything else?

When using the above configuration together with a `triggers.authenticationRef`, the field `storageConnectionFromEnv` is no longer required.

To preserve back-compat, if `storageConnectionFromEnv` is provided, it will force connection string based authN for the blob storage account.

**Comment by andyatwork** [comment]
I'd be happy to contribute this feature to the project.

**Comment by v-shenoy** [comment]
Completed in https://github.com/kedacore/keda/pull/3573.
