### ISSUE TITLE
Mention Azure Event Hub scaler limitations to avoid confusion

### ISSUE THREAD

**Issue by abhirockzz** [kedacore/keda#358]
As mentioned in the sample here https://github.com/kedacore/sample-javascript-eventhub-azure-function, *"As of now, the Event Hub scaler only supports reading from Blob Storage, as well as scaling only Event Hub applications written in C# or created with Azure Functions."* - This should be explicitly called out (probably as a README note in this section https://github.com/kedacore/keda#event-sources-and-scalers ?).

**Comment by tomkerkhove** [comment]
Given KEDA does not care how the app was written I'm more wondering if this is an Azure Function limitation or not? 🤔

Do you know @ahmelsayed?

**Comment by ahmelsayed** [comment]
It's an eventHub checkpoint format limitation. Eventhub checkpoints using storage, the format it uses for checkpointing is different per language. When Azure Functions is processing eventHub, it uses the EventHub C# sdk, which writes check points in C# format. 

When Keda is reading the checkpoint, it's only handling C# format which is [defined here](https://github.com/kedacore/keda/blob/ec7430c63f02f4dd640243ad59b2ab562f20efa6/pkg/scalers/azure_eventhub.go#L21-L28)

**Comment by tomkerkhove** [comment]
Thanks for updating the docs @ahmelsayed ! Think that should be good enough to close the issue
