### ISSUE TITLE
Scaling Custom Resources without HPAs

### ISSUE THREAD

**Issue by cliveseldon** [kedacore/keda#3582]
### Proposal

We would like to use KEDA Scalers to scale a custom resource replica count in cases where the custom resource does not manage any underplying Pods and thus there is no HPA to connect to. In essence, can we switch off the HPA wiring but leave the metrics collection and replica update decisioning?

### Use-Case

Custom resources which manage non-pod internal application components.

**Comment by JorTurFer** [comment]
hey,
Could you explain a bit more about your user case? I can see the goal you are trying to achieve

**Comment by zroubalik** [comment]
I think that it should work this way even now. If your CustomResource correctly implements `/scale` subresource, then the HPA just talks through this interface and the CustomResource does the final decision on how to actually scale.
Can you double check that?

**Comment by cliveseldon** [comment]
> hey, Could you explain a bit more about your user case? I can see the goal you are trying to achieve

We have resources such as machine learning models which we manage ourselves and which do not have a 1-1 mapping to pods. However, we would still like to use KEDA scalers to allow metrics from some source to determine the replica count of the custom resource its just there are no Pods for an HPA to manage.

> I think that it should work this way even now. If your CustomResource correctly implements `/scale` subresource, then the HPA just talks through this interface and the CustomResource does the final decision on how to actually scale. Can you double check that?

From [here](https://github.com/kubernetes/kubernetes/blob/963adda7f9a58e7d8ef803e5052c07e9fc9da207/staging/src/k8s.io/api/autoscaling/v1/types.go#L133-L143) the v1/scale resources monitor Pods as expected. So the HPA would fail if no Pod selector is found.

I assume KEDA sets up the HPA and the decision to scale up/down a certain amount is left to that? So I assume to get what I want KEDA would need to have something similar to an HPA but which is agnostic to the resource type. So not using the   [selector](https://github.com/kubernetes/kubernetes/blob/963adda7f9a58e7d8ef803e5052c07e9fc9da207/staging/src/k8s.io/api/autoscaling/v1/types.go#L137-L142) but doing something else to get current state.

**Comment by zroubalik** [comment]
> > I think that it should work this way even now. If your CustomResource correctly implements `/scale` subresource, then the HPA just talks through this interface and the CustomResource does the final decision on how to actually scale. Can you double check that?
> 
> From [here](https://github.com/kubernetes/kubernetes/blob/963adda7f9a58e7d8ef803e5052c07e9fc9da207/staging/src/k8s.io/api/autoscaling/v1/types.go#L133-L143) the v1/scale resources monitor Pods as expected. So the HPA would fail if no Pod selector is found.
> 

I think that if your CR sets the proper status, then it should be enough and the HPA will not actually monitor Pods.

> I assume KEDA sets up the HPA and the decision to scale up/down a certain amount is left to that? So I assume to get what I want KEDA would need to have something similar to an HPA but which is agnostic to the resource type. So not using the [selector](https://github.com/kubernetes/kubernetes/blob/963adda7f9a58e7d8ef803e5052c07e9fc9da207/staging/src/k8s.io/api/autoscaling/v1/types.go#L137-L142) but doing something else to get current state.

I know I discussed this with someone while ago, but I am not sure what was the final verdict on this 😄  @lionelvillard I know I ask you a couple times about this, can you please confirm? 😅 

@cliveseldon so can you cofirm, that you have actually tried that and HPA complains?
