### ISSUE TITLE
Merge prometheus servers exposed by metrics-server

### ISSUE THREAD

**Issue by JorTurFer** [kedacore/keda#3586]
### Proposal

Right now, metrics server exposes 2 different prometheus servers, the default controller-runtime prometheus server and other with KEDA metrics only, we should merge both and expose only the default.
To avoid breaking changes, we can expose KEDA metrics in both for some versions more and mark it as a deprecated, removing it in the future

**Comment by tomkerkhove** [comment]
I think we might want to make this configurable as well given I'm not sure what Prometheus will do when you scrape the same metric twice. I think it should be OK, but you never know.

That way, if people deliberately choose to merge them then the deprecation log will be gone.

So:
- Default writes to the ones we have today
- Configured to merge, only writes to the 8080 one.

That's how I would do it to avoid breaking things.

**Comment by JorTurFer** [comment]
Okey, seems good to me, we can introduce this as an optional feature now logging the deprecation and drop the old way in 2 versions, aiming to KEDA v2.11. How does it look to you?

**Comment by tomkerkhove** [comment]
If we want to drop it, then we can only do that in KEDA 3.0 as this is a breaking change.
