### ISSUE TITLE
cron scaler metricType shouldn't be configurable

### ISSUE THREAD

**Issue by amirschw** [kedacore/keda#3591]
### Proposal

For the cron trigger to scale to the number specified in `metadata.desiredReplicas`, it must use the `AverageValue` metric type. Otherwise (if `Value` is used), based on the HPA algorithm, it will scale to [currentReplicas * desiredReplicas] instead. Therefore, we should probably disallow changing the metricType for this specific scaler.

### Anything else?

Related to #2309 where we introduced the option to set the metricType.

**Comment by amirschw** [comment]
Will be happy to do it myself if there's no objection

**Comment by JorTurFer** [comment]
Makes sense, excellent catch!

**Comment by tomkerkhove** [comment]
Not sure if we should continue investing in cron-scaler or should start #3566 with this instead

**Comment by amirschw** [comment]
Thanks, I'll wait for the outcome of the discussion there before starting this.
