### ISSUE TITLE
RabbitMQ Scaler doesn't parse vhost correctly if provided in the host url

### ISSUE THREAD

**Issue by JorTurFer** [kedacore/keda#3602]
### Report

After v2.7.0, the vhost it's not correctly parsed from the url

### Expected Behavior

`http://guest:guest@pecan-rabbitmq.default:15672/` should parse the vhost as `/`

### Actual Behavior

`http://guest:guest@pecan-rabbitmq.default:15672/` should parse the vhost as `""`. To parse the vhost has `/` we need to set `http://guest:guest@pecan-rabbitmq.default:15672//`

### Steps to Reproduce the Problem

1.
2.
3.

### Logs from KEDA operator

```
example
```

**Comment by PSKP-95** [comment]
The error looks like this. I think.
![image](https://user-images.githubusercontent.com/35999328/191566225-27f79806-cebf-447c-a0a1-b9cff267a034.png)

**Comment by JorTurFer** [comment]
Do you still have the issue? If you are running with KEDA v2.8.1 (chart v2.8.2) and you still have issues, could you open another  issue to track it?
