### ISSUE TITLE
New scaler: Google Cloud Tasks

### ISSUE THREAD

**Issue by mwarkentin** [kedacore/keda#3613]
### Proposal

I would like to be able to set up autoscaling for Google Cloud Tasks. 

> Cloud Tasks is a fully managed service that allows you to manage the execution, dispatch, and delivery of a large number of distributed tasks. Using Cloud Tasks, you can perform work asynchronously outside of a user or service-to-service request.

### Scaler Source

api/request_count, queue/depth

### Scaling Mechanics

I see this as being similar to the existing RabbitMQ triggers where you could define a request rate trigger to scale up with the number of incoming items, as well as a queue depth trigger in case consumption slows down and you begin to accumulate a backlog.

### Authentication Source

Google Cloud IAM

**Comment by tomkerkhove** [comment]
That's a good idea! Are you willing to contribute it?

**Comment by mwarkentin** [comment]
@tomkerkhove I'm working on a proposal for using KEDA at Sentry - if that goes through and we implement it it may be something I can look at.. don't think I can put in the time if we're not using KEDA yet though. :D

**Comment by tomkerkhove** [comment]
Sounds great though!

**Comment by Shulammite-Aso** [comment]
Hi @tomkerkhove I would like to take this up

**Comment by tomkerkhove** [comment]
Awesome, thank you! Let us know if you need help, you can learn more in our contribution guide.

**Comment by jmalvarezf-lmes** [comment]
Hey @Shulammite-Aso are you already working on this? I also need this and have time to try to do this. Tell me if you are on it not to waste time. Thank you!

**Comment by Shulammite-Aso** [comment]
Hi @jmalvarezf-lmes I started working on this, but I have gotten a bit too busy and can't seem to pay close attention to this for now. If you have the time you can take it up.
