### ISSUE TITLE
Upgrade test cluster to Kubernetes v1.23

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda#3615]
Upgrade test cluster to Kubernetes v1.23 as per our support policy.

**Comment by tomkerkhove** [comment]
@JorTurFer @zroubalik am I OK to start this?

**Comment by JorTurFer** [comment]
Yes, go ahead. Currently, KEDA works perfectly on 1.23 so we can proceed

**Comment by tomkerkhove** [comment]
Done, all nodes run 1.23.8 now
