### ISSUE TITLE
Selenium Grid Scaler | Multiple browser nodes are not scaling parallel

### ISSUE THREAD

**Issue by ChandniSuresh** [kedacore/keda#3620]
### Report

When we run browser nodes separately they are autoscaling as expected. For example, if we run the Firefox test the Firefox nodes are scaling as per the count in the session queue.
But the issue is when we start multiple browser tests eg: Chrome, and Firefox together then at a time only one browser is autoscaling.
The other browser will stay in the queue until all current running browser sessions are finished.
Once all the running sessions are finished the pending browser session will start to autoscale.

The below screenshot shows the chrome sessions are pending in the queue.
![image](https://user-images.githubusercontent.com/50142085/187845857-ad80f279-b2f6-4626-82ed-0eeb1ea08bbe.png)

Keda version : 2.7.2

### Expected Behavior

Both Chrome and FF should autoscale simultaneously as per their session count in the queue.

### Actual Behavior

Only one browser is autoscaling (here FF) at a time, the other one is waiting in the queue

### Steps to Reproduce the Problem

1.
2.
3.

### Logs from KEDA operator

```
example
```

### KEDA Version

Other

### Kubernetes Version

v1.20.15

### Platform

Amazon Web Services

### Scaler Details

selenium-grid

**Comment by Wolfe1** [comment]
@ChandniSuresh Are you positive on your version? Not sure if a version 2.7.2 exists from what I can see but 2.8.0 had a few bug fixes for selenium grid that you should probably check out:

https://github.com/kedacore/keda/releases/tag/v2.8.0

https://github.com/kedacore/keda/issues/2709
https://github.com/kedacore/keda/issues/3061
