### ISSUE TITLE
support multiple cron triggers for multiple schedules with different replicas 

### ISSUE THREAD

**Issue by khateeb15** [kedacore/keda#3646]
### Proposal

to be able to have different cron schedules with different desiredReplicas for the same target without them conflicting with each other, for example, the following code will result in the two scaledObject conflicting, during the operation hours of the first, it will try to scale up to 2, but since it's out of operation hours for the second, it will try to scale to 0, causing the service to spin
```apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: cron-scaledobject-9-5
  namespace: namespace
spec:
  scaleTargetRef:
    name: name
  minReplicaCount: 1
  triggers:
  - type: cron
    metadata:
      timezone: Europe/London
      start: 0 9 * * 1-5
      end: 0 17 * * 1-5
      desiredReplicas: "2"
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: cron-scaledobject-ooh
  namespace: namespace
spec:
  scaleTargetRef:
    name: name
  triggers:
  - type: cron
    metadata:
      timezone: Europe/London
      start: 0 17 * * 1-5
      end: 0 9 * * 1-5
      desiredReplicas: "1"
```

### Use-Case

having multiple cron with different scaling, in the above case, we want 2 replicas during office hours, 1 replica outside office hours, 0 during the weekend.

**Comment by tomkerkhove** [comment]
I would need to check if using multiple crons are supported, but you should only use 1 ScaledObject instead of 2

**Comment by khateeb15** [comment]
so it would be two triggers one ScaledObject?

**Comment by tomkerkhove** [comment]
Yes, but I have not tried that with a cron - @zroubalik @JorTurFer Any concerns here with cron scaler?

**Comment by JorTurFer** [comment]
Hey,
Yes, you can have multiple cron triggers, they will be evaluated as MAX between them, so in case of overlap but that's all. 
You shouldn't have multiple ScaledObject per workload, because that will create multiple HPA per workload and the HPA Controller will scale out/in all the time, 1 ScaledObject per workload, all the triggers you want in that ScaledObject
