### ISSUE TITLE
Support Go checkpoint format for Event Hubs

### ISSUE THREAD

**Issue by abhirockzz** [kedacore/keda#367]
similar to #353

In Go SDK for Event Hubs, `Checkpoint` (https://github.com/Azure/azure-event-hubs-go/blob/master/persist/checkpoint.go) looks like this:

```
Checkpoint struct {
		Offset         string    `json:"offset"`
		SequenceNumber int64     `json:"sequenceNumber"`
		EnqueueTime    time.Time `json:"enqueueTime"`
	}
```

**Comment by ahmelsayed** [comment]
I'd expect this to work since `sequenceNumber` and `offset` are there and they match the C# format (go json is case insensitive)

**Comment by abhirockzz** [comment]
Thanks. I'll give it a try and update this thread
