### ISSUE TITLE
Can provide keda-api as single github project?

### ISSUE THREAD

**Issue by penghuazhou** [kedacore/keda#3671]
### Proposal

I only want use keda api，but I want not use go module witch keda have dependence.

### Use-Case

for example
```
func (r *ScaledObjectReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error) {
	_log := log.FromContext(ctx).WithValues("name", req.Name, "namespace", req.Namespace, "func", "ScaleObject Reconciler")
	// 查询scaleObject
	scaleObject := &kedav1alpha1.ScaledObject{}
```

<img width="1396" alt="image" src="https://user-images.githubusercontent.com/13001038/190360971-4653d5d7-5a96-479f-8579-290838942d7c.png">

I copy keda api to my project，because  I want not use go module witch keda have dependence.
<img width="356" alt="image" src="https://user-images.githubusercontent.com/13001038/190361394-97003e0f-6dc4-49c9-8e8c-eb39d5d4b225.png">

### Anything else?
I think we can provide keda api like kruise api.
<img width="920" alt="image" src="https://user-images.githubusercontent.com/13001038/190363521-3c1bd81a-52f6-4908-b9b3-d823ccdb5944.png">

**Comment by JorTurFer** [comment]
I think that this is overengineering for us atm. WDYT @kedacore/keda-core-contributors ?
