### ISSUE TITLE
KEDA frequent reconciling causing ApiServer LIST verb Saturation

### ISSUE THREAD

**Issue by djsly** [kedacore/keda#3678]
### Report

Keda operator goes into a "restart" loop causing a constant reconciliation loop. Due to the non cache LIST operation the apiserver was not able to answer LIST request for other services as well. 

### Expected Behavior

Keda Operator should use cached List operation and it should also not get into reconciliation loop

### Actual Behavior

Graph showing the apiserver saturation time

<img width="1063" alt="apiserver-list-saturation" src="https://user-images.githubusercontent.com/4981802/191034158-571a2b73-849e-4118-9050-b82c5422287a.png">

### Steps to Reproduce the Problem

1. Hard to tell, it started after Keda Operator lost it's leader election due to a slow ApiServer response : https://github.com/operator-framework/operator-sdk/issues/5186

### Logs from KEDA operator

[keda-pods-apiserver-list-saturation.csv](https://github.com/kedacore/keda/files/9599479/keda-pods-apiserver-list-saturation.csv)

### KEDA Version

2.6.1

### Kubernetes Version

1.23

### Platform

Microsoft Azure

### Scaler Details

Prometheus

### Anything else?

Azure Support: 2209160030000259 for the impact and severity of such a bug

**Comment by zroubalik** [comment]
Hi, this is probably a duplicate of https://github.com/kedacore/keda/issues/2914

This issue has been solved most likely By chance, could you please update KEDA version to the latest one?

**Comment by djsly** [comment]
we certainly can, what do you mean "by chance" ?

**Comment by zroubalik** [comment]
> we certainly can, what do you mean "by chance" ?

the original sentece was missing a `.` hope that it makes sense now ;)
