### ISSUE TITLE
Apache Kafka Scaler: SASL/OAuthbearer Implementation

### ISSUE THREAD

**Issue by DevinGillman** [kedacore/keda#3681]
### Proposal

Add support for Kafka SASL/OAuthbearer authentication.
https://kafka.apache.org/documentation/#security_sasl_oauthbearer

### Use-Case

We often deploy our consumers/producers outside of the Kafka infrastructure. Because of this we are looking for ways to use OAuth Providers like Azure AD or KeyCloak with the Keda Apache Kafka Scalers.

**Comment by JorTurFer** [comment]
Hi,
This proposal is related with adding a new authentication mechanism for Kafka scaler, right?
It sounds totally legit, are you willing to contribute this?

**Comment by DevinGillman** [comment]
Working on the PR now.

**Comment by DevinGillman** [comment]
PR is now open. Let me know if there are any questions or concerns. I've been able to test this with a local Strimzi Minikube cluster using Azure AD. If there are ways to add e2e tests for this please let me know.

All the best,
Devin
