### ISSUE TITLE
Prepare for Hacktoberfest

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda#3686]
As Hacktoberfest registrations are openening, we should prepare by tagging issues with `help-wanted` and `hacktoberfest`.

**Comment by tomkerkhove** [comment]
@JorTurFer @zroubalik I'll go through some of them today but feel free to do the same

**Comment by JorTurFer** [comment]
I'll tag some of them 😋

**Comment by tomkerkhove** [comment]
Done from my end

**Comment by JorTurFer** [comment]
I have reviewed and I don't have any more either
