### ISSUE TITLE
Error deploying keda via Helm

### ISSUE THREAD

**Issue by scotty-c** [kedacore/keda#369]
If you run the standard deployment via Helm 
``` 
helm install kedacore/keda-edge --devel --set logLevel=debug --namespace keda --name keda
```
you get the following error
```
Error: unable to convert to CRD type: unable to convert unstructured object to apiextensions.k8s.io/v1beta1, Kind=CustomResourceDefinition: cannot convert int64 to float64
```

**Comment by tomkerkhove** [comment]
Thanks for reporting @scotty-c!

Would it be possible to get a full error log or some more info please?

@ahmelsayed Would it be possible that this is due to our recent validation/spec changes?
Happy to take a look, but will only be next week I'm afraid.

**Comment by scotty-c** [comment]
@tomkerkhove  That is the only logs I have at the moment, keda wont install on the cluster. You can reproduce the error by just installing the chart with `helm install kedacore/keda-edge --devel --set logLevel=debug --namespace keda --name keda`

**Comment by sebastianspross** [comment]
Same here. Recording to this [stackoverflow question](https://stackoverflow.com/questions/58166426/unable-to-install-keda-on-aks-with-helm) I downloaded the keda chart and changed `"helm.sh/hook": crd-install`  to `"helm.sh/hook": pre-install`

**Comment by jeffhollan** [comment]
Thanks - @ahmelsayed agreed to look into this

**Comment by sbawaska** [comment]
This issue was introduced in helm 2.14: https://github.com/helm/helm/issues/5806

**Comment by ahmelsayed** [comment]
Fixed in https://github.com/kedacore/keda/pull/382
