### ISSUE TITLE
Prometheus custom metrics not queried by KEDA when using push mode

### ISSUE THREAD

**Issue by nelsonpraveen** [kedacore/keda#3696]
### Report

When Prometheus works in push mode (application pushes the metrics to the Prometheus pushgateway), the custom metrics are not appearing in HPA. When using Prometheus pull mode (Prometheus scrapes from application), the custom metrics appear in HPA. 
The metrics are visible when queried from thanos-querier svc which means KEDA has some issue in pulling the metrics.

HPA output:
```
kubectl get hpa -n $ns
NAME                  REFERENCE                                 TARGETS                                            MINPODS   MAXPODS   REPLICAS   AGE
keda-hpa-amms   StatefulSet/cmm34-qa-amms    **0**/350k (avg), 49%/91% + 1 more...   5                5                   5               24h
```

ScaledObject:

```
Spec:
  Advanced:
    Horizontal Pod Autoscaler Config:
      Behavior:
        Scale Down:
          Policies:
            Period Seconds:              15
            Type:                        Percent
            Value:                       100
          Stabilization Window Seconds:  300
    Restore To Original Replica Count:   false
  Cooldown Period:                       300
  Fallback:
    Failure Threshold:  3
    Replicas:           6
  Idle Replica Count:   0
  Max Replica Count:    5
  Min Replica Count:    5
  Polling Interval:     30
  Scale Target Ref:
    API Version:  apps/v1
    Kind:         StatefulSet
    Name:         cmm34-qa-amms
  Triggers:
    Metadata:
      Type:   Utilization
      Value:  91
    Type:     memory
    Metadata:
      Type:   Utilization
      Value:  80
    Type:     cpu
    Authentication Ref:
      Name:  keda-auth-prometheus
    Metadata:
      Auth Modes:      bearer
      Metric Name:     m172c011
      Namespace:       npv-cmm-34
      Query:           sum(avg_over_time(m172c011[5m]))
      Server Address:  https://thanos-querier.openshift-monitoring.svc.cluster.local:9092
      Threshold:       350000
    Type:              prometheus
Status:
  Conditions:
    Message:  ScaledObject is defined correctly and is ready for scaling
    Reason:   ScaledObjectReady
    Status:   True
    Type:     Ready
    Message:  Scaling is performed because triggers are active
    Reason:   ScalerActive
    Status:   True
    Type:     Active
    Message:  No fallbacks are active on this scaled object
    Reason:   NoFallbackFound
    Status:   False
    Type:     Fallback
  External Metric Names:
    s2-prometheus-m172c011
  Health:
    s2-prometheus-m172c011:
      Number Of Failures:  0
      Status:              Happy
  Last Active Time:        2022-09-27T10:12:19Z
  Original Replica Count:  5
  Resource Metric Names:
    memory
    cpu
  Scale Target GVKR:
    Group:            apps
    Kind:             StatefulSet
    Resource:         statefulsets
    Version:          v1
  Scale Target Kind:  apps/v1.StatefulSet
Events:               <none>
```

The metrics are available in the thanos querier and can be viewed using curl.

```
 curl -X GET -kG "https://thanos-querier-openshift-monitoring.apps.cmm34.npvlab.com/api/v1/query?" --data-urlencode "query=sum(avg_over_time(m172c011[5m]))" -H "Authorization: Bearer $TOKEN"

{"status":"success","data":{"resultType":"vector","result":[{"metric":{},"value":[1664273645.048,"568843.5454545454"]}]}}

```

The Prometheus services in the system:

```
[root@npv-cmm-34-oc-client nelson_work]# kubectl get svc -n openshift-monitoring
NAME                            TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                               AGE
alertmanager-main               ClusterIP   172.30.66.232    <none>        9094/TCP,9092/TCP,9097/TCP            124d
alertmanager-operated           ClusterIP   None             <none>        9093/TCP,9094/TCP,9094/UDP            124d
cluster-monitoring-operator     ClusterIP   None             <none>        8443/TCP                              124d
grafana                         ClusterIP   172.30.36.18     <none>        3000/TCP,3002/TCP                     124d
kube-state-metrics              ClusterIP   None             <none>        8443/TCP,9443/TCP                     124d
node-exporter                   ClusterIP   None             <none>        9100/TCP                              124d
openshift-state-metrics         ClusterIP   None             <none>        8443/TCP,9443/TCP                     124d
prometheus-adapter              ClusterIP   172.30.247.196   <none>        443/TCP                               124d
prometheus-k8s                  ClusterIP   172.30.166.129   <none>        9091/TCP,9092/TCP                     124d
prometheus-k8s-thanos-sidecar   ClusterIP   None             <none>        10902/TCP                             124d
prometheus-operated             ClusterIP   None             <none>        9090/TCP,10901/TCP                    124d
prometheus-operator             ClusterIP   None             <none>        8443/TCP,8080/TCP                     124d
prometheus-pushgateway          ClusterIP   172.30.218.87    <none>        9091/TCP                              4d23h
telemeter-client                ClusterIP   None             <none>        8443/TCP                              124d
thanos-querier                  ClusterIP   172.30.60.193    <none>        9091/TCP,9092/TCP,9093/TCP,9094/TCP   124d

```

The cluster is OpenShift and version details are:

```
oc version
Client Version: 4.6.8
Server Version: 4.10.3
Kubernetes Version: v1.23.3+e419edf
```

Note:
As mentioned above, the issue is observed when using push mode in Prometheus. When Prometheus scrapes from application (pull mode), the metrics appear right in the HPA.

### Expected Behavior

The metrics appear in HPA when using push mode in Prometheus for the application custom metrics.

### Actual Behavior

KEDA is unable to fetch metrics from Prometheus thanos querier and hence HPA unable to get any metrics

### Steps to Reproduce the Problem

1. Deploy application with push mode. Metrics are pushed to Prometheus
2. Verify if the metrics are visible in thanos querier
3. KEDA ScaledObject has thanos-querier and port configured correctly but still unable to fetch metrics

### Logs from KEDA operator

```
example
```

### KEDA Version

2.7.1

### Kubernetes Version

1.23

### Platform

Red Hat OpenShift

### Scaler Details

Prometheus

**Comment by zroubalik** [comment]
Hi, could you please put all the referenced yaml objects into code blocks, so it is readable and we can see the intendation? https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#fenced-code-blocks

Also, could you please attach here logs from both KEDA Operator and Metrics Server?

**Comment by nelsonpraveen** [comment]
Changed the indent for yaml definitions. Attached the logs from api-server and operator.

[keda-operator.log](https://github.com/kedacore/keda/files/9658764/keda-operator.log)
[keda-metricsserver.log](https://github.com/kedacore/keda/files/9658769/keda-metricsserver.log)

**Comment by JorTurFer** [comment]
Hey,
I have checked the logs and metrics-server has errors related with timeouts querying the metrics:
```bash
E0927 07:15:38.456111       1 logr.go:279] keda_metrics_adapter/prometheus_scaler "msg"="error executing prometheus query" "error"="Get \"https://thanos-querier.openshift-monitoring.svc.cluster.local:9092/api/v1/query?query=sum%28avg_over_time%28m172c011%5B5m%5D%29%29&time=2022-09-27T07:15:35Z&namespace=npv-cmm-34\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
```

Has KEDA access to the namespace where the prometheus server is? I mean, do you have any firewall/netpol that could block the access? Other possibility is that the query is to heavy to be executed in the default timeout and you [need to extend it](https://keda.sh/docs/2.8/operate/cluster/#http-timeouts)

**Comment by nelsonpraveen** [comment]
As I mentioned in the same OCP cluster, the Prometheus pull mode worked fine. KEDA was able to fetch the metrics from the Prometheus running in the openshift-monitoring namespace.

Only when using the Push mode, (application pushing metrics to prometheus-pushgateway), the HPA does not show any custom metrics.

I can try the timeout option.

**Comment by JorTurFer** [comment]
You are right, KEDA can reach the server :) 
Try with the timeout because usually push mode requires more resources in Prometheus than pull mode because with pull mode, Prometheus is who decides when do the things, if it's overloaded, the scraping job could be executed with delay.
In case of push mode, is your app who decides when push metrics and the amount of them (depending on the sampling).

**Comment by nelsonpraveen** [comment]
I need a bit help on the timeout setting. Where do I set this - export KEDA_HTTP_DEFAULT_TIMEOUT=1000 ?

Is this before deploy of KEDA ? With KEDA already running, can I set this ? If yes, where and how exactly ?

**Comment by JorTurFer** [comment]
You need to add the environment variable to KEDA pods, you can do it modifying manually the deployment, but if you are using helm to deploy KEDA, you can just modify [this value](https://github.com/kedacore/charts/blob/main/keda/values.yaml#L256)
