### ISSUE TITLE
Provide a Loki Scaler

### ISSUE THREAD

**Issue by neelanjan00** [kedacore/keda#3699]
### Proposal

Grafana Loki is an open-source, horizontally scalable, brute-force log aggregation tool inspired by Prometheus. KEDA should provide a Loki scaler to autoscale k8s resources based on quantifiable LogQL (Loki's query language) query results.

### Scaler Source

Loki

### Scaling Mechanics

Scale based on quantifiable LogQL query results i.e. queries that result in a numeric value.

### Authentication Source

Since Loki doesn't define any built-in authentication, basic auth and bearer auth can be used through `TriggerAuthentication`.

**Comment by neelanjan00** [comment]
I would like to be assigned to this issue.

**Comment by tomkerkhove** [comment]
Awesome, thanks! Nice addition.
