### ISSUE TITLE
error installing alongside knative

### ISSUE THREAD

**Issue by sbawaska** [kedacore/keda#371]
I have [knative](https://knative.dev/) installed in my k8s cluster. I then tried to install keda and got the following error:
```
$ helm install kedacore/keda-edge --devel --set logLevel=debug --namespace keda --name keda
Error: release keda failed: clusterrolebindings.rbac.authorization.k8s.io "hpa-controller-custom-metrics" already exists
```
there are at-least a couple of resources that have name conflicts with knative. 
1. clusterrolebinding: hpa-controller-custom-metrics 
1. clusterrole: custom-metrics-server-resources

**Comment by tomkerkhove** [comment]
I can take a look at this if you want @ahmelsayed

**Comment by anirudhgarg** [comment]
That will be great @tomkerkhove. I will assign it to you

**Comment by tomkerkhove** [comment]
`custom-metrics-server-resources` is only used in `KedaScaleController.yaml` which is not shipped as part of our Helm chart.

Did you run it manually yourself or where did you see this pop up?

**Comment by sbawaska** [comment]
I found `custom-metrics-server-resources` while manually applying KedaScaleController.yaml.  I was trying to work around the helm bug https://github.com/kedacore/keda/issues/369

**Comment by sbawaska** [comment]
@tomkerkhove It looks like the ClusterRole `custom-metrics-server-resources` is not used to define any ClusterRoleBindings in the entire github org, so I think can be safely removed.

**Comment by tomkerkhove** [comment]
Do we still maintain the files in `deploy` @ahmelsayed?

I see we've recently changed them but not sure if it's just to keep them up to date or because of the strategy for KEDA.

**Comment by tomkerkhove** [comment]
> Is that file updated in ci? Is this a recommended path?
Not that I'm aware of.

**Comment by sbawaska** [comment]
Since `KedaScaleController.yaml` is advertised as being usable in the README, I submitted another PR: https://github.com/kedacore/keda/pull/388

**Comment by tomkerkhove** [comment]
Thanks man!
