### ISSUE TITLE
Scaling a deployment to Zero by setting MaxReplicaCount to "0" is not supported

### ISSUE THREAD

**Issue by tshaiman** [kedacore/keda#3724]
### Report

- I am trying to set MinReplicaCount = 0 , and MaxReplicaCount =0 which is effectively scale to zero 
- The scenario we try to do is similar to Blue/Green Deployments where we want on some cases to allow Blue deployment be active while the "Green" deployment is idle.
- both deployment read from the same Source ( Azure Service Bus Queue in this case ) but the connector is not the issue here.

we get an error message on the Keda controller saying "Min Replica Count = 1 cannot be below Max Replica Count = 0"
this is incorrect error message since both Min and Max were set to "0" .

### Expected Behavior

 - we expect Keda to allow us to scale to "0" instead of deleting a scaled object and change the K8s deployment to scale 0
 - since K8s deployments support "Scale to zero" - so does keda should

- if the feature 

### Actual Behavior

we are getting error with incorrect information : 

2022-10-04T15:01:08Z    ERROR   Reconciler error        {"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "scaledObject": {"name":"aed","namespace":"vi-be-map-dev9"}, "namespace": "vi-be-map-dev9", "name": "aed", "reconcileID": "3533a506-549e-4536-bbdd-5d5bbd1d331a", "error": "MinReplicaCount=1 must be less than MaxReplicaCount=0"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:273
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:234

- The error reports that our MinReplicaCount= 1 ,where it was actually set to "0"
- There shouldn't be any error since we want this feature to be supported.

### Steps to Reproduce the Problem

1. Create a Scale Object on a Deployment , set min = 0 , max = 0
![image](https://user-images.githubusercontent.com/512709/193860998-5bddf9e8-b74f-42d7-b13f-9727d73e21fb.png)

### Logs from KEDA operator

```
2022-10-04T15:01:08Z    ERROR   Reconciler error        {"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "scaledObject": {"name":"aed","namespace":"vi-be-map-dev9"}, "namespace": "vi-be-map-dev9", "name": "aed", "reconcileID": "3533a506-549e-4536-bbdd-5d5bbd1d331a", "error": "MinReplicaCount=1 must be less than MaxReplicaCount=0"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:273
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:234
```

### KEDA Version

2.8.1

### Kubernetes Version

1.23

### Platform

Microsoft Azure

### Scaler Details

Azure Service Bus

**Comment by JorTurFer** [comment]
hey,
I'd suggest to pause the autoscaling instead of setting min/max to 0. You can pause the autoscaling with the instances you want just adding an annotation, so I guess that having to modify the SO in both cases, using the annotation isn't a problem (and it's already supported)
https://keda.sh/docs/latest/concepts/scaling-deployments/#pause-autoscaling

**Comment by tshaiman** [comment]
@JorTurFer  : absolutely, great suggestion.
in addition don't forget that there is indeed a bug in the error message saying I chose scale =1 , where It wasn't the case

**Comment by tomkerkhove** [comment]
Let's open a dedicated bug for that @tshaiman
