### ISSUE TITLE
Provide stable Helm chart releases

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda#374]
As of today, we generate a new version of the helm chart for every change which results in a lot of new releases:
![image](https://user-images.githubusercontent.com/4345663/66652157-45cd1200-ec35-11e9-8c57-711a3d31ecf5.png)

Given that those are not stable versions, you have to specify the version of the chart you want to install and `helm install kedacore/keda-edge --devel --set logLevel=debug --namespace keda --name keda` no longer works unless `--version` is added.

We might want to see if we can streamline this by pushing a stable version and add previews as we do today, or use a dedicated "experimental" chart for this.

**Comment by jeffhollan** [comment]
@ahmelsayed  do you know if this will be addressed by any of the helm changes you made?

**Comment by ahmelsayed** [comment]
That's part of the change in https://github.com/kedacore/keda/pull/446, though I need to update the README with the stable helm instructions.

**Comment by tomkerkhove** [comment]
Would you mind updating it here instead https://github.com/kedacore/keda-docs/blob/master/content/deploy.md#deploying-with-a-helm-chart?

I'll send a PR to cleanup this repo once migration has been done.

**Comment by tomkerkhove** [comment]
Thanks!

**Comment by ahmelsayed** [comment]
will do.

**Comment by jeffhollan** [comment]
Completed and tracked at https://github.com/kedacore/charts
