### ISSUE TITLE
KEDA operator deployment has error when deployed locally

### ISSUE THREAD

**Issue by aavarghese** [kedacore/keda#3751]
### Report

`make deploy` of `main` branch causing keda-operator deployment to throw error below

```
2022-10-13T20:09:36Z	ERROR	controller-runtime.source	if kind is a CRD, it should be installed before calling Start	{"kind": "HorizontalPodAutoscaler.autoscaling", "error": "no matches for kind \"HorizontalPodAutoscaler\" in version \"autoscaling/v2\""}
sigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start.func1.1
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/source/source.go:139
k8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtectionWithContext
	/go/pkg/mod/k8s.io/apimachinery@v0.24.5/pkg/util/wait/wait.go:233
k8s.io/apimachinery/pkg/util/wait.WaitForWithContext
	/go/pkg/mod/k8s.io/apimachinery@v0.24.5/pkg/util/wait/wait.go:660
k8s.io/apimachinery/pkg/util/wait.poll
	/go/pkg/mod/k8s.io/apimachinery@v0.24.5/pkg/util/wait/wait.go:594
k8s.io/apimachinery/pkg/util/wait.PollImmediateUntilWithContext
	/go/pkg/mod/k8s.io/apimachinery@v0.24.5/pkg/util/wait/wait.go:545
sigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start.func1
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/source/source.go:132
```

### Expected Behavior

No errors in deployment.

### Actual Behavior

Error in keda-operator pod (Error pasted above).

And pods restarting due to it:

```
ansuvarghese$ k get pods -n keda
NAME                                      READY   STATUS    RESTARTS      AGE
keda-metrics-apiserver-76fb58fc74-8k68t   1/1     Running   0             9m27s
keda-operator-7b9d7667fd-x66pm            1/1     Running   1 (96s ago)   3m45s
```

### Steps to Reproduce the Problem

1. `make docker-build`
2. `make publish` (changed ghcr repo to my personal docker hub repo)
3. `VERSION=main make deploy`

### Logs from KEDA operator

```
2022-10-13T20:14:29Z	ERROR	controller-runtime.source	if kind is a CRD, it should be installed before calling Start	{"kind": "HorizontalPodAutoscaler.autoscaling", "error": "no matches for kind \"HorizontalPodAutoscaler\" in version \"autoscaling/v2\""}
sigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start.func1.1
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/source/source.go:139
k8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtectionWithContext
	/go/pkg/mod/k8s.io/apimachinery@v0.24.5/pkg/util/wait/wait.go:233
k8s.io/apimachinery/pkg/util/wait.WaitForWithContext
	/go/pkg/mod/k8s.io/apimachinery@v0.24.5/pkg/util/wait/wait.go:660
k8s.io/apimachinery/pkg/util/wait.poll
	/go/pkg/mod/k8s.io/apimachinery@v0.24.5/pkg/util/wait/wait.go:594
k8s.io/apimachinery/pkg/util/wait.PollImmediateUntilWithContext
	/go/pkg/mod/k8s.io/apimachinery@v0.24.5/pkg/util/wait/wait.go:545
sigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start.func1
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/source/source.go:132
```

### KEDA Version

`main`

### Platform

Red Hat OpenShift

### Scaler Details

Kafka

**Comment by JorTurFer** [comment]
Hey,
What k8s version are you using? It seems that you are using <= v1.22 which currently is not supported because KEDA (in ´main´ tag) is already [using](https://github.com/kedacore/keda/pull/3606) `autoscaling/v2` and that's API was introduced in k8s v1.23. 
[We follow N-2 support policy](https://github.com/kedacore/governance/blob/main/SUPPORT.md#kubernetes-support) and due to `autoscaling/v2beta1` and `autoscaling/v2beta2` deprecation, we migrate KEDA to `autoscaling/v2` which requires k8s v1.23 (N-2)

**Comment by JorTurFer** [comment]
Hi @tvert ,
It looks like microk8s addon is using keda v2.8 or below. For k8s >= 1.25 you should use KEDA v2.9 or above

**Comment by JorTurFer** [comment]
> Thanks for the hint. Do you know if there is a plan for the microk8s addon to be updated to 2.9?

IDK because we don't manage it. Maybe you could ask in their repo

**Comment by tvert** [comment]
I used the documentaion provided by the release notes:
https://keda.sh/docs/2.10/deploy/#yaml

And it works - I was able to deploy my ScaleObject yaml file - no more apiversion issues. Thank you @JorTurFer for the hint.
