### ISSUE TITLE
Add prefix support to Google Cloud Platform Storage scaler

### ISSUE THREAD

**Issue by wrdls** [kedacore/keda#3756]
### Proposal

Add prefix support to Google Cloud Platform Storage scaler.

Similar to `blobPrefix` in [Azure Blob Storage](https://keda.sh/docs/2.8/scalers/azure-storage-blob/).

This value is currently hardcoded to `""` in the code: https://github.com/kedacore/keda/blob/main/pkg/scalers/gcp_storage_scaler.go#L194

### Use-Case

This allows us to only watch part of a bucket.

### Anything else?

I might be able to contribute this myself but I thought I'd already open the issue to see if this is acceptable.

**Comment by zroubalik** [comment]
This is definitely useful improvement, shall I assign the issue to you @wrdls ?

**Comment by JorTurFer** [comment]
Agree, this is a really useful improvement 😄
