### ISSUE TITLE
KEDA Redis Scaler dbIndexFromEnv proposal

### ISSUE THREAD

**Issue by Marcin250** [kedacore/keda#3766]
### Proposal

Providing dbIndex value directly from env as host and port, ex. yaml element `dbIndexFromEnv`

### Use-Case

Now i set host and port in single config file for whole project, but for dbIndex i need to duplicate it in every scaler.

**Comment by JorTurFer** [comment]
This sounds totally legic!
Are you willing to contribute with it?
