### ISSUE TITLE
Stackdriver scalar returns 0 for gauge values of type double

### ISSUE THREAD

**Issue by octothorped** [kedacore/keda#3777]
### Report

When using the GCP Stackdriver scalar to retrieve metrics that have a [value type of double](https://cloud.google.com/monitoring/api/v3/kinds-and-types#value-types) it always returns a value of 0. Since it does not create any errors, it triggers a scale down to zero but can never scale back up.

### Expected Behavior

Since double is a valid metric value type and can still have a similar average target value calculation, we would expect the scalar to retrieve the correct metric value instead of returning 0. If this is expected behavior, maybe we can update the documentation to make it more clear that the only supported value type is int64.

### Actual Behavior

We believe the issue is [here](https://github.com/kedacore/keda/blob/7eab93b9956383c7e358637f9661ef411d37a142/pkg/scalers/stackdriver_client.go#L215) where the getMetrics() function in the client is casting the value to an Int64. In the calling function [here](https://github.com/kedacore/keda/blob/7eab93b9956383c7e358637f9661ef411d37a142/pkg/scalers/gcp_stackdriver_scaler.go#L212) it also attempts to cast the value back to a float64.

### Steps to Reproduce the Problem

1. Create a `ScaledObject` that uses a [Google Cloud Platform stackdriver scalar](https://keda.sh/docs/2.8/scalers/gcp-stackdriver/) with a metric filter of some external metric type. We used `metric.type="external.googleapis.com/prometheus/test_pod_scaling"` for testing purposes.
2. Publish values of 1.0 to the stackdriver metric ensuring the gauge value type is double.
3. Check operator logs and associated HPA to see that the values are always returning 0.

The setup can be verified by:
1. Deleting the metric created above
2. Publish values of 1 to that same metric ensuring the gauge value type is now int64
3. Check operator logs and associated HPA to see that the values retrieved are now 1.

### KEDA Version

2.8.1

### Platform

Google Cloud

**Comment by JorTurFer** [comment]
You are right
Are you willing to contribute with the fix?

**Comment by octothorped** [comment]
@JorTurFer I am willing to help contribute with a fix.
