### ISSUE TITLE
RabbitMQ auth not working when username contains backslash

### ISSUE THREAD

**Issue by mohite-abhi** [kedacore/keda#3781]
### Report

We tried to connect to RabbitMQ in local machine with the following host and it was working fine
```
amqps://<<username>>:<<pwd>>@<<host>>:<<port>>/<<vhost>>
```

But when we were connecting to a remote RabbitMQ Queue with the username that contained '\' to separate domain:
```
amqps://<<domain-name>>\<<username>>:<<pwd>>@<<host>>:<<port>>/<<vhost>>
https://<<domain-name>>\<<username>>:<<pwd>>@<<host>>:<<port>>/<<vhost>>
```

then Keda scaler is displaying queue depth as unknown:
![MicrosoftTeams-image (6)](https://user-images.githubusercontent.com/39857042/198570028-3f7fbdd5-e98c-4fab-a9c0-e79a0af3fe6b.png)

### Expected Behavior

Actual Queue depth should be visible and Keda should scale the pod according to Queue length.

### Actual Behavior

Actual Queue depth is not visible and Keda is not scaling the pods according to Queue length.

### Steps to Reproduce the Problem

1. Use username/password in host when the username contains backslash '\'

### Logs from KEDA operator

```
example
```

**Comment by JorTurFer** [comment]
Hello @mohite-abhi 
Could you share KEDA logs? Have you tried escaping it? `https://<<domain-name>>\\<<username>>:<<pwd>>@<<host>>:<<port>>/<<vhost>>` KEDA should code it as a valid url, but maybe it's parsing the backslash as a command with the first letter from the username

**Comment by mohite-abhi** [comment]
Hello @JorTurFer sorry for the late response

We tried escaping like this ` https://<<domain>>\<<username>>:SAMPLE?^&PASSWORD@<<host>>:5672/<<vhost>>` and the logs we got for the above was


> 2022-11-14T18:18:07+05:30 1.6684300874320738e+09    ERROR    Reconciler error    {"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "scaledObject": {"name":"<<app-name>>","namespace":"<<namespace-name>>"}, "namespace": "<<namespace-name>>", "name": "<<app-name>>", "reconcileID": "<<redoncileID>>", "error": "error parsing rabbitmq metadata: can't parse host to find protocol: parse \"https://<<domain>>\\\\\\\\<<username>>:SAMPLE?^&PASSWORD@<<host>>:5672/<<vhost>>\": invalid port \":SAMPLE\" after host"}

**Comment by JorTurFer** [comment]
mmmm
I think KEDA should support this scenario too. Are you willing to contribute?

**Comment by mohite-abhi** [comment]
Yes! Though I might need some help in setup and finding the code that handles the above configuration.

**Comment by JorTurFer** [comment]
Sure, you can ask us whatever if you are blocked. I'd recommend #keda-dev slack channel for development questions because it's probably faster
BTW, you could find [these docs interesting](https://github.com/kedacore/keda/blob/main/BUILD.md). It's explained how to kick off the project using devcontainers (if you don't use golang in your daily basics, this could help you to create the environment) and how to deploy/debug the operator/metrics server.

**Comment by mohite-abhi** [comment]
> Hello @JorTurFer sorry for the late response
> 
> We tried escaping like this ` https://<<domain>>\<<username>>:SAMPLE?^&PASSWORD@<<host>>:5672/<<vhost>>` and the logs we got for the above was
> 
> > 2022-11-14T18:18:07+05:30 1.6684300874320738e+09    ERROR    Reconciler error    {"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "scaledObject": {"name":"<>","namespace":"<>"}, "namespace": "<>", "name": "<>", "reconcileID": "<>", "error": "error parsing rabbitmq metadata: can't parse host to find protocol: parse "https://<>\\\\<>:SAMPLE?^&PASSWORD@<>:5672/<>": invalid port ":SAMPLE" after host"}

I made a typo here actually we had used `https://<<domain>>\\<<username>>:SAMPLE?^&PASSWORD@<<host>>:5672/<<vhost>>`. Fiddling with the keda source code code, we found out the error was actually due to the special character in the password. 

I think using double backslash should work. 

PS: Just now we have landed into another issue with TLS certificates of rabbitmq, I think will need to open another issue and fix that 😄.

**Comment by JorTurFer** [comment]
>PS: Just now we have landed into another issue with TLS certificates of rabbitmq, I think will need to open another issue and fix that 😄.

Yeah, it's better if you open another issue to track it 😄
