### ISSUE TITLE
'(' is not sanitized from datadog scalar

### ISSUE THREAD

**Issue by tehlers320** [kedacore/keda#3789]
### Report

Not sure if this is a bug or working as intended but having "(" in kubernetes objects doesnt feel right. 

metrics name:

```
s1-datadog-moving_rollup(sum-istio-mesh-request-count
```

### Expected Behavior

metrics name:
```
s1-datadog-moving_rollup-sum-istio-mesh-request-count
```

### Actual Behavior

metrics name:

```
s1-datadog-moving_rollup(sum-istio-mesh-request-count
```

### Steps to Reproduce the Problem

1. use query 
```
moving_rollup(sum:istio.mesh.request.count{}.as_rate().rollup(sum, 30), 120, 'max')
```

### Logs from KEDA operator

```
example
```

### KEDA Version

2.8.1

### Kubernetes Version

1.25

### Platform

Any

### Scaler Details

datadog

### Anything else?

This is probably just a simple update to this function

```
// NormalizeString will replace all slashes, dots, colons and percent signs with dashes
func NormalizeString(s string) string {
	s = strings.ReplaceAll(s, "/", "-")
	s = strings.ReplaceAll(s, ".", "-")
	s = strings.ReplaceAll(s, ":", "-")
	s = strings.ReplaceAll(s, "%", "-")
	return s
}
```

**Comment by JorTurFer** [comment]
Hey,
Thanks for reporting it, one question, does KEDA works properly? I mean, is it just a visual thing, or you are facing with problems with autoscaling? I mean, that function sanitize some characters that produce issues with url formats, but IDK if this is the case

**Comment by tehlers320** [comment]
@JorTurFer sorry i didnt see this, yes it does work perfectly fine. Its just very weird to have '(' in kubernetes object names.

**Comment by zroubalik** [comment]
I agree, that we should sanitize this. @tehlers320 are you up for opening a PR?

**Comment by JorTurFer** [comment]
> I agree, that we should sanitize this. @tehlers320 are you up for opening a PR?

Yeah, +1
