### ISSUE TITLE
Support HTTPS protocol in NATS Scalers

### ISSUE THREAD

**Issue by JorTurFer** [kedacore/keda#3805]
### Proposal

Currently, the scalers have hardcoded the protocol ([1](https://github.com/kedacore/keda/blob/main/pkg/scalers/nats_jetstream_scaler.go#L156) [2](https://github.com/kedacore/keda/blob/main/pkg/scalers/stan_scaler.go#L171)), we should add an option to use https if it's needed

**Comment by mknet3** [comment]
I can do it
