### ISSUE TITLE
Prometheus scaler "disableScaleToZero" attribute

### ISSUE THREAD

**Issue by abhirockzz** [kedacore/keda#381]
The example for [Prometheus ScaledObject](https://github.com/kedacore/keda/blob/master/examples/prometheus_scaledobject.yaml#L19) includes the `disableScaleToZero` attribute. I don't see it being used in the [metadata definition](https://github.com/kedacore/keda/blob/master/pkg/scalers/prometheus.go#L31-L36). Is this valid ?

**Comment by balchua** [comment]
@abhirockzz, you're right.  i dont think its used at all. The sample is obsolete.
Having the minreplicas=1 defined is sufficient.
