### ISSUE TITLE
A kubectl plugin for listing scaling events

### ISSUE THREAD

**Issue by 26tanishabanik** [kedacore/keda#3822]
### Proposal

A simple kubectl plugin which will list the current scaling events under the deployed keda replicas.

Examples:

`kubectl get scaling-events`
```
Output:
NameOfScaler                           Scaling decision
couchdb-scaler                         no of rows greater than threshold
loki-scaler                            metric value greater than a threshold
```
What do you guys think? 
I would be glad to pick this up as soon as this issue receives any positive feedback from the community.

### Use-Case

Show the different scaling events of different scalers listed under the keda operator

**Comment by zroubalik** [comment]
Do you think this use case is worth implementing?

**Comment by 26tanishabanik** [comment]
> Do you think this use case is worth implementing?

I think it is, in context that, suppose I would want to know as an user what scalers are available in my cluster currently, just using `kubectl` only

**Comment by neelanjan00** [comment]
> > Do you think this use case is worth implementing?
> 
> I think it is, in context that, suppose I would want to know as an user what scalers are available in my cluster currently or the scaling events which are driving the auto scalers or scaling different resources, just using `kubectl` only

Since scalers are defined as part of ScaledJobs/ScaledObjects triggers, I think it will be worth it if we can list them, the trigger(s) that they are using, and the parameter config of the triggers.

**Comment by 26tanishabanik** [comment]
> > > Do you think this use case is worth implementing?
> > 
> > 
> > I think it is, in context that, suppose I would want to know as an user what scalers are available in my cluster currently or the scaling events which are driving the auto scalers or scaling different resources, just using `kubectl` only
> 
> Since scalers are defined as part of ScaledJobs/ScaledObjects triggers, I think it will be worth it if we can list them, the trigger(s) that they are using, and the parameter config of the triggers.

Agreed, that way it will be easier to view all the triggers @neelanjan00

**Comment by 26tanishabanik** [comment]
> Well yeah, but it is not so straighforward to query for this info from KEDA. You will need to manage all of that in the plugin seaprately (which si fine for the list of scalers, but might be a painful process when listing config options per scaler (it is a huge number)).

That will also be a long list, true @zroubalik , what do you suggest?

**Comment by neelanjan00** [comment]
> Well yeah, but it is not so straighforward to query for this info from KEDA. You will need to manage all of that in the plugin seaprately (which si fine for the list of scalers, but might be a painful process when listing config options per scaler (it is a huge number)).

That's a valid concern, I think. We can have a verbose flag for listing the config options maybe. Otherwise it might be done on a per ScaledJob/ScaledObject basis rather than for all of them at once.

**Comment by tomkerkhove** [comment]
I think writing them to our SO/SJ resources would be better: https://github.com/kedacore/keda/issues/3764

**Comment by zroubalik** [comment]
> I think writing them to our SO/SJ resources would be better: #3764

I don't think I follow.

**Comment by 26tanishabanik** [comment]
> @26tanishabanik @neelanjan00 scalers are not defined on the ScaledObject/Job level, there are just metadata (`map[string]string`) that needs to be validated for each scaler. So it is not easy (possible) to programatically list all the options.
> 
> For example:
> 
> https://github.com/kedacore/keda/blob/41487693f172b53689e6b29b55185a4e2840233b/pkg/scalers/activemq_scaler.go#L77

Can't we just define a parameter in keda itself to define what the event is, and then fetch it? @zroubalik

**Comment by tomkerkhove** [comment]
> > I think writing them to our SO/SJ resources would be better: #3764
> 
> I don't think I follow.

https://github.com/kedacore/keda/issues/3764#issuecomment-1305301918 should clarify this, but basically give insights to how your SO/SJ is doing and when it has last scaled
