### ISSUE TITLE
Impact of HPAScaleToZero feature in K8s upstream

### ISSUE THREAD

**Issue by shahiddev** [kedacore/keda#383]
Hi All,

It looks like upstream K8s has support for scale to zero (behind a feature gate).
https://github.com/kubernetes/kubernetes/issues/69687

What does that mean for KEDA/Osiris?

**Comment by tomkerkhove** [comment]
This is being discussed in #208 AFAIK

**Comment by shahiddev** [comment]
Thanks @tomkerkhove  - I searched but clearly not well enough! I'll close this
