### ISSUE TITLE
Load testing

### ISSUE THREAD

**Issue by zroubalik** [kedacore/keda#3832]
### Proposal

We should set up some load test, that will stress KEDA and run it regurarly to catch perf regressions.

Steps:
1. Design the test case
2. Implement the test
3. Make it part of CI and set up to run periodically (nightly?)

**Comment by tomkerkhove** [comment]
What is the scope of perf testing, we should define that as well.

For example, we need to perf test metric server, but also our external scaler approach (mainly push)

**Comment by JorTurFer** [comment]
Let me work on this as part of the testing proposal I'm working on to improve trust in KEDA and I'll link this there

**Comment by JorTurFer** [comment]
This is duplicated: https://github.com/kedacore/keda/issues/4411
