### ISSUE TITLE
Allow jobs to last indefinitely (activeDeadlineSeconds)

### ISSUE THREAD

**Issue by benjimin** [kedacore/keda#3836]
### Proposal

Could `ScaledJob` allow jobs to run for arbitrarily long? That is, by permitting the user to leave `activeDeadlineSeconds` unset (and with an update to the docs to mark it as optional) or else by configuring it to zero?

### Use-Case

We have a common pattern whereby a worker process performs the following loop: attempt to retrieve and process a task from a queue (specifically AWS SQS) and terminate if the queue is empty.

When tasks are added to the queue at a fairly sustained rate for an extended period, then some pods will not try to exit for an extended period (because there is consistently still work for them to do). It shouldn't be customary for the controller to prematurely terminate these pods for no reason. Aborting partially-completed tasks will waste compute, may necessitate extra cleanup, and adds noise to the event log.

### Anything else?

If we instead use a `Deployment` (or `ScaledObject`) for this workflow, we have the problem that when the queue becomes empty there is a race between the worker pod terminating itself and the controller scaling the deployment to zero. This typically produces unwanted errors in the kubernetes event stream (e.g. _CrashLoopBackOff_ because the container is exiting unexpectedly to the controller).

At present, KEDA jobs seem to expect that the container will only consume a fixed small number of tasks from the queue before exiting. It seems like this model will cause superfluous overhead (more frequently terminating a pod and scheduling an identical replacement), make it more difficult to monitor the workload resource consumption (e.g. gaps missed by the prometheus metrics scraper become a larger fraction of the total workload), and does not assist transition of workloads to kubernetes (since elsewhere there is no reason to program a worker to quit after n tasks).

We want an arrangement where (as long as the cluster is healthy) the pod is allowed to run until its container terminates naturally, and is only restarted when there is more work in the queue.

**Comment by benjimin** [comment]
I think this field is already optional (the JobTargetRef seems to be implemented as a standard JobSpec) and just ought to be documented more clearly as such (consistent with the other optional parameters).

**Comment by JorTurFer** [comment]
Hello,
There is documented that parameter in keda.sh but probably we should improve how the information is presented there, are you willing to contribute with that?
![image](https://user-images.githubusercontent.com/36899226/201210442-8072407c-cc75-4e4a-8af2-a9dbd9cb7341.png)

One suggestion, I'd use ScaledObject for your use case, I feel that matches better with your requirements. It's true that during the scale in, the HPA controller will remove instances randomly, but you could set a graceful period which is enough to correctly finish your workers. If your worker monitors system signals, you could react to SIGTERM signal and stop the worker loop to not process more messages and once you don't have more messages in progress, just existing with return code 0. The main problem in these cases, is that workers don't respect system signals and continue processing messages even thought they have received a SIGTERM signal, forcing the SIGKILL after the graceful period. Just playing with the graceful period and monitoring the signals, you could achieve the behaviour you want using ScaledObjects.
Disclaimer: I'm assuming you have "short term" messages that you can process in a few seconds, so you don't need to block the container removal for several minutes.

> We want an arrangement where (as long as the cluster is healthy) the pod is allowed to run until its container terminates naturally, and is only restarted when there is more work in the queue.

This is exactly what I described above, but workers should handle terminations properly

**Comment by benjimin** [comment]
I've just contributed https://github.com/kedacore/keda-docs/pull/976 which should resolve this issue, imo.

@JorTurFer the problem with ScaledObject is that it doesn't leave the container to exit naturally.
* It complains and attempts a restart if the container does exit (i.e. when the container finds the queue empty)
