### ISSUE TITLE
Increase unit test coverage in `pkg/util`

### ISSUE THREAD

**Issue by zroubalik** [kedacore/keda#3871]
### Proposal

https://github.com/kedacore/keda/tree/main/pkg/util

1) Following files don't have unit test, we should target in having majority of those covered
- `gvkr.go`
- `http.go`
- `normalize_string.go`
- `tls_config.go`

2) We should inspect the rest of the package and increase test coverage if needed

**Comment by joshi95** [comment]
Hey, I can pick it up.

**Comment by JorTurFer** [comment]
Nice @joshi95 ! Thanks a lot ❤️ , I assign this to you

**Comment by neverbeenthisweeb** [comment]
hi, may i know this issue's progress? perhaps i can help with some files that have not been done

**Comment by JorTurFer** [comment]
AFAIK @joshi95 is doing it
