### ISSUE TITLE
Very mush connection created by keda

### ISSUE THREAD

**Issue by penghuazhou** [kedacore/keda#3874]
### Report

When i have 600 scaledobject, every scaledobject have a prometheus trigger, it have create more than 500 http connection.We can set disableKeepAlives to be false when create client，as hpa only have only little goroutine to get metrics.

<img width="1436" alt="image" src="https://user-images.githubusercontent.com/13001038/202399869-5699a35d-fefe-4b76-a5f1-03f42b964718.png">

### Expected Behavior

<img width="425" alt="image" src="https://user-images.githubusercontent.com/13001038/202400495-c11fbded-3211-4f4b-86a4-78ae2f9c31c7.png">

### Actual Behavior

<img width="550" alt="image" src="https://user-images.githubusercontent.com/13001038/202400288-0ba79956-7d8c-4593-96ff-8e0a8e82999a.png">

### Steps to Reproduce the Problem

1. 600 scaledobject, every scaledobject have a prometheus trigger

### KEDA Version

2.8.1

### Kubernetes Version

1.20.11

**Comment by JorTurFer** [comment]
Hello @penghuazhou 
AFAIK, the HPA Controller soon will work in parallel, but you are right, enforce the keep alive isn't worth and having the option to configure it (enabling or disabling it) could fit better in more scenarios. 
Are you willing to contribute it?
