### ISSUE TITLE
Close is called twice on PushScaler's deletion

### ISSUE THREAD

**Issue by WindNotStop** [kedacore/keda#3881]
### Report

The scaler's close method has already been called once by ScalersCache. PushScaler will call the scaler's close method again.

### Expected Behavior

The scaler's close method is expected to be called once.

### Actual Behavior

The scaler's close method is actually called twice.

### Steps to Reproduce the Problem

1. Delete the PushScaler resource.

### KEDA Version

2.8.0

### Kubernetes Version

1.24

### Platform

Other

**Comment by tomkerkhove** [comment]
Thanks for reporting! Are you willing to propose a fix for this?

**Comment by JorTurFer** [comment]
This is already fixed
