### ISSUE TITLE
Add e2e test for Azure Event Hubs using Workload Identity and Pod Identity

### ISSUE THREAD

**Issue by JorTurFer** [kedacore/keda#3888]
### Proposal

We need to add e2e test coverage for the scenario

**Comment by christle** [comment]
I can do it

**Comment by JorTurFer** [comment]
Awesome!
You could need to open a PR in testing-infrastructure with the role assignment for granting access to managed identity in eh and storage

**Comment by JorTurFer** [comment]
[This is the repo](https://github.com/kedacore/testing-infrastructure). It's done with terraform and I guess that the change is small, you need to pass the manage identity or the map of managed identities to event-hub module and storage account module, and the assign the roles. Currently, Service Bus module already has assigned roles, so you could check how it's done [here](https://github.com/kedacore/testing-infrastructure/blob/main/modules/azure/service-bus/main.tf#L32-L37)

**Comment by JorTurFer** [comment]
I have already created the role assignments, so you don't need to do anything in testing-infrastructure repo, all the changes you need to do are in this repo 😄

**Comment by christle** [comment]
Great, Thank you :)

**Comment by christle** [comment]
I will start with it the next days. I didn't have time over the turn of the year.

**Comment by JorTurFer** [comment]
No rush, when you have time :)

**Comment by JorTurFer** [comment]
Hey @christle ,
Do you have any update about this? I'm adding missing azure e2e test and could add this as part of [my PR](https://github.com/kedacore/keda/pull/4200)

**Comment by JorTurFer** [comment]
Hey @christle 
I have done it as part of my PR for adding the e2e tests on all azure scalers with pod identities. I hope you haven't started it yet :(

**Comment by christle** [comment]
No Problem. It is totally fine for me. I just did some initial setup task regards infrastructure etc last week.  sry for that

**Comment by JorTurFer** [comment]
f**k, sorry :(
