### ISSUE TITLE
RabbitMQ scaler documentation should be more clear abuot vhost

### ISSUE THREAD

**Issue by daniel-habib** [kedacore/keda#389]
RabbitMQ can have many vhosts (each holding many queues)
a user might be permitted to read just some vhosts.
when one tries to use a user that can access just some vhost - one get the following messages:
`error establishing rabbitmq connection: Exception (403) Reason: \"no access to this vhost\""`

using url notation like specified here: https://www.rabbitmq.com/uri-spec.html (e.g. amqp://1.1.11:5672/vhost) - solves this.

it would be helpful to have documentation state that clearly.

**Comment by jeffhollan** [comment]
Thanks @daniel-habib - makes sense

**Comment by zroubalik** [comment]
Probably solved by: https://github.com/kedacore/keda-docs/pull/123
