### ISSUE TITLE
Add e2e test for Azure Blob Storage using Workload Identity and Pod Identity

### ISSUE THREAD

**Issue by JorTurFer** [kedacore/keda#3895]
### Proposal

We need to add e2e test coverage for the scenario

**Comment by mknet3** [comment]
I will manage this

**Comment by JorTurFer** [comment]
@mknet3 , do you have any update? are you still interested on helping with this?

**Comment by JorTurFer** [comment]
Hey @mknet3 
I tackle this as part of https://github.com/kedacore/keda/pull/4200
