### ISSUE TITLE
Stop scaling out new resources if the function isn't successfully processing

### ISSUE THREAD

**Issue by jeffhollan** [kedacore/keda#39]
There are two scenarios we have today where we stop scaling new instances even as the queue length increases:
1. No available partitions.  If you have an event hub with 5 partitions that is growing in event lenghts, we will scale to 5 instances, and then 6.  The 6th one gets scaled out but can't get a lock on a partition so never actually consumes any events.  We never scale to a 7th because we look to see that the 6th isn't execution so stop scaling.
1. A function is misconfigured and never actually is able to start consuming.  Rather than scaling out a broken app, we stop scaling if we see no executions are happening.

In our service we do that by looking at the execution and billing metrics for the instance, and if no billing or execution metrics are emitting we stop scaling more.  

We'd need a similar pattern in Kore so that if the event consumer isn't actually processing new messages, we don't keep scaling.  Both for the "no available partition" scenario or the "my app isn't even working" scenario.  We could also solve each of these in 2 seperate ways (e.g. maybe expose partition info into the scaler?)

**Comment by gabrielSoudry** [comment]
Some news ? The first case "No available partition" is common
