### ISSUE TITLE
Consolidate all exposed Prometheus Metrics in KEDA Operator

### ISSUE THREAD

**Issue by zroubalik** [kedacore/keda#3919]
### Proposal

Currently we are exposing Prometheus Metrics on Scaling and Errors in Metrics adapter:
https://keda.sh/docs/2.8/operate/prometheus/#metrics-adapter

We also expose some metrics in Operator and also there is a new feature to expose additional metrics in Operator:
https://github.com/kedacore/keda/issues/3663

## Old situation
```
### Metrics Server
keda_metrics_adapter_scaler_error_totals 
keda_metrics_adapter_scaled_object_error_totals
keda_metrics_adapter_scaler_errors
keda_metrics_adapter_scaler_metrics_value

### Operator
operator-sdk related metircs
# newly introduced:
keda_operator_resource_totals 
keda_operator_trigger_totals
````

## New situation
Opeator is now the main source of metrics, keeping Metrics Server metrics as Deprecated for a some time, till https://github.com/kedacore/keda/issues/3930 is resolved
**Some metric names were renamed.**
```
### Operator
keda_scaler_error_totals 
keda_scaled_object_error_totals
keda_scaler_errors
keda_scaler_metrics_value
keda_resource_totals 
keda_trigger_totals

operator-sdk related metircs


### Metrics Server -- DEPRECATED!
keda_metrics_adapter_scaler_error_totals 
keda_metrics_adapter_scaled_object_error_totals
keda_metrics_adapter_scaler_errors
keda_metrics_adapter_scaler_metrics_value
```

This will help us in the future with multi-tenant story etc.

Related:
https://github.com/kedacore/keda/issues/3930

**Comment by zroubalik** [comment]
@kedacore/keda-maintainers @v-shenoy PTAL^

**Comment by v-shenoy** [comment]
I agree with this proposal. Having them all in one place makes sense, and the operator feels like the right place. 

Considering the next release is going to be a breaking one anyway with the HPA API versions, might as well get any breaking changes done along with it.

**Comment by tomkerkhove** [comment]
> This will be a breaking change, but I think it is beneficial and we should do this change now. It will help us in the future with multi-tenant story etc.

Sure but it's breaking :) So we can add them on the operator with the new names, but we cannot remove them on the metric server.

**Comment by tomkerkhove** [comment]
> Considering the next release is going to be a breaking one anyway with the HPA API versions, might as well get any other breaking changes done along with it.

I tend to disagree because this is not pushed on us by Kubernetes

**Comment by v-shenoy** [comment]
> > This will be a breaking change, but I think it is beneficial and we should do this change now. It will help us in the future with multi-tenant story etc.
> 
> Sure but it's breaking :) So we can add them on the operator with the new names, but we cannot remove them on the metric server.

Wouldn't renaming the ones on the operator also be breaking? Also, this is obviously a maintainer's call on what breaking changes should / shouldn't be done. So, I leave that to all of you.

**Comment by tomkerkhove** [comment]
Based on this:
> My suggestion is to move all these metrics to Operator and slightly rename them:

It looks like metrics in a new place so we can do anything we want :) But the ones weh ave today must be kept around.

**Comment by zroubalik** [comment]
Honestly it would be hard to keep those on Metrics Server in a sensible way. And especially if we try to tackle the semi-multitenancy.

**Comment by v-shenoy** [comment]
Right, also I forgot the operator currently doesn't expose anything other than the default OperatorSDK stuff.

> Based on this:
> 
> > My suggestion is to move all these metrics to Operator and slightly rename them:
> 
> It looks like metrics in a new place so we can do anything we want :) But the ones we have today must be kept around.

**Comment by zroubalik** [comment]
But this https://github.com/kedacore/keda/pull/3861 is changing the way we are getting metrics (and exposing them as Prom metrics). It is no longer happening on Metrics Server, it is on Operator.

**Comment by JorTurFer** [comment]
The problem is that currently we are goign to break the metrics server metrics because we are going to move the logic to generate them moving the metric querying to the operator. I think that we could reduce the impact if we add the scrapping to the operator as part of helm chart, but the change is there and we need it

**Comment by zroubalik** [comment]
IMHO we are not doing a breaking change per se. We are still exposing the metrics, but only from a different endpoint with a slightly different name. I am okay with doing this, if this change is properly documented.

**Comment by v-shenoy** [comment]
> But this #3861 is changing the way we are getting metrics (and exposing them as Prom metrics). It is no longer happening on Metrics Server, it is on Operator.

So, if I understand this right, basically the operator will be doing all of the heavy lifting going forward. Not just reconciling the CRDs, but also fetching the metrics from the HPA, and caching them. And the metrics server will just query the operator?

**Comment by JorTurFer** [comment]
I think this release as is already "disruptive" due to the support removal is a good release to do it if we document it clearly

**Comment by zroubalik** [comment]
> > But this #3861 is changing the way we are getting metrics (and exposing them as Prom metrics). It is no longer happening on Metrics Server, it is on Operator.
> 
> So, if I understand this right, basically the operator will be doing all of the heavy lifting going forward. Not just reconciling the CRDs, but also fetching the metrics from the HPA, and caching them. And the metrics server will just query the operator?

Yes.

**Comment by tomkerkhove** [comment]
> I think this release as is already "disruptive" due to the support removal is a good release to do it if we document it clearly

That is a different way of breaking given this is because of Kubernetes. Moving things to another endpoint and renaming them is going to break KEDA's operational story which is bad.

This is also not in line with the deprecation policy that we have discussed on https://github.com/kedacore/governance/pull/70.

Active KEDA users will have to manually change to the new endpoint and use the new endpoints which means this is a breaking change.

**Comment by JorTurFer** [comment]
> Active KEDA users will have to manually change to the new endpoint and use the new endpoints which means this is a breaking change.

We could cover this updating the chart, reducing the impact as much as possible. I think that helm is the most used tool for deploying KEDA, so if we do the needed changes there, we can make this change "invisible" to end-users

**Comment by tomkerkhove** [comment]
And yet, not everyone uses Helm so it's a breaking change.

**Comment by zroubalik** [comment]
Well, technically the deprecation policy is not yet valid :)

I really think this change is in users favour, consolidating the metrics in one place is a good thing and really, if we want to have some sort of multitenancy, we would have to do this change anyway. So my call is to do the change now, together with other breaking changes that we are introducing in 2.9.

**Comment by JorTurFer** [comment]
Technically, we are not introducing breaking changes in the operator as those metrics aren't released yet, they are only in main. WDYT if we add an endpoint in the metrics server that request the metrics to operator?
I know this won't scale and won't support multitenant, but in that case, we can enforce the change as this metrics-server endpoint must be deprecated in this version and deprecated features don't receive updates

**Comment by JorTurFer** [comment]
WRT metric names, we can expose both in the operator, the old and new metrics, deprecating the old metric names.

**Comment by zroubalik** [comment]
Are you up for implementing this? :) I was thinking about this originally, but dropped the idea for it being a messy solution.

**Comment by zroubalik** [comment]
And it will block us of introducting the multi tenant solution till we fully drop metrics from metrics server. According to the gov policy in preparation it would mean a year.

**Comment by JorTurFer** [comment]
So basically, we will only expose metrics from the same namespace as metrics server from metrics server endpoint.

**Comment by JorTurFer** [comment]
I'm not proposing the have a multitenant solution exposing the metrics from metrics server at all, my proposal is just, go ahead with new metrics approach and "proxy" the old metric endpoint to the operator **in the same namespace** without multitenant support

**Comment by tomkerkhove** [comment]
For me this is fairly clear on what we should do:
1. Introduce the approach suggested above by @zroubalik as new "ideal" solution
2. Introduce feature flag on metric server to still serve our current metrics (*)
3. Ship with feature flag on by default but officially deprecating it
4. Next KEDA v2.11 has the flag turned off by default

Existing end-users are not broken but are aware things are moving, and they can start migrating. In 2 releases we still give them the option to do so, but give them a nudge to move because it's off by default.

Am I missing something?

(*) Scrape metrics from operator and serve in metric server, we can add a small memcache here to reduce load on operator.

**Comment by JorTurFer** [comment]
> I am not sure if this is a dumb question. But why specifically v2.11?

[In progress deprecation policy](https://github.com/kedacore/governance/pull/70/files) says that deprecated features are removed in 4 releases (1 year), so 2.11 is just half the deprecation time

**Comment by tomkerkhove** [comment]
> For me this is fairly clear on what we should do:
> 
> 1. Introduce the approach suggested above by @zroubalik as new "ideal" solution
> 2. Introduce feature flag on metric server to still serve our current metrics (*)
> 3. Ship with feature flag on by default but officially deprecating it
> 4. Next KEDA v2.11 has the flag turned off by default
> 
> Existing end-users are not broken but are aware things are moving, and they can start migrating. In 2 releases we still give them the option to do so, but give them a nudge to move because it's off by default.
> 
> Am I missing something?
> 
> (*) Scrape metrics from operator and serve in metric server, we can add a small memcache here to reduce load on operator.

Proposal also added to policy: https://github.com/kedacore/governance/pull/70/files#r1034591287

**Comment by zroubalik** [comment]
I have updated the issue description. We will introduce the new metrics and consolide old ones in KEDA Operator, while keeping the old metrics in Metrics Server, which is deprecated option and will be removed in future KEDA releases.

**Comment by tomkerkhove** [comment]
Re-opening as we need to announce deprecation as well

**Comment by tomkerkhove** [comment]
@zroubalik Can you please announce the deprecation as per https://github.com/kedacore/governance/blob/main/DEPRECATIONS.md?

**Comment by tomkerkhove** [comment]
Deprecation issue is https://github.com/kedacore/keda/issues/3972 with conversation on https://github.com/kedacore/keda/discussions/3973
