### ISSUE TITLE
Support for specifying a different managed identities for checkpointing while using the eventhub scaler and adding optional tenantId to the triggerauthspec

### ISSUE THREAD

**Issue by Aashish93-stack** [kedacore/keda#3932]
### Proposal

We are using workload Identity as provider in the triggerauthspec, but the current flow supports using a single managed identity specified in the triggerauthenticationspec for both checkpointing and eventhub. We have a use case where we need to use two different managed identities across different tenants for checkpointing (azure storage) and eventhub to support multi-tenancy

Suggesting the following changes 
- updating the `AuthPodIdentity` to support an optional  tenantId (this will enable multi-tenant support)
- passing in a `checkpointIdentityId` and `checkpointTenantId` in the scaledObject and adding those fields in EventHubInfo 
- add a tenantId parameter to the `NewAzureADWorkloadIdentityTokenProvider` and use that in case it's not empty, otherwise default to the environment set tenant Id

### Use-Case

We have a use case to support muti-tenancy where event-hubs could be in different tenant and Storage Account (checkpointing) could be in a different tenant.

**Comment by Aashish93-stack** [comment]
I'd be happy to contribute this feature to the project.

**Comment by JorTurFer** [comment]
This totally makes sense to me, WDYT @v-shenoy ?

**Comment by v-shenoy** [comment]
@JorTurFer @Aashish93-stack 

I think this is a fair ask. Just have to confirm once that we don't need to make changes to other Azure scalers incorporating this `tenantId` except for changing the common workload identity methods.

I think the parameters should be named something along the lines of `storageIdentityId` or `storageAccountIdentityId`, considering that's how the parameters are named currently (ex - `connectionFromEnv` vs `storageConnectionFromEnv`).

And maybe these should be specifiable through auth params as well?

**Comment by Aashish93-stack** [comment]
Sorry been busy with other commitments, will contribute this feature in March.
