### ISSUE TITLE
Keda failing to fetch stack driver metrics intermittently

### ISSUE THREAD

**Issue by prakharjoshi** [kedacore/keda#3937]
### Report

we are running keda 2.7.1 version and using stack driver scaler to fetch load balancer metrics in GCP. We are getting unknown values in HPA sometimes. 

When we checked the keda metric service logs we are getting this error logs frequently.

```
1 logr.go:279] keda_metrics_adapter/gcp_stackdriver_scaler "msg"="error getting metric value" "error"="could not find stackdriver metric with filter metric.type=\"loadbalancing.googleapis.com/https/backend_request_count\" AND resource.type=\"https_lb_rule\" AND resource.label.backend_target_name=\"<application_name>\""  ```


### Expected Behavior

There should be no unknown values for stack driver metrics intermittently. 

### Actual Behavior

We are getting unknown values at HPA which are created by scaledObjects for stack driver metrics.
<img width="1157" alt="image (12)" src="https://user-images.githubusercontent.com/6854139/204748478-fe9d7d8f-c5bc-4238-934a-cb57771d8a25.png">



### Steps to Reproduce the Problem

1. Create scaled object with gcp-stackdriver scaler.
2. Add Authentication for access stack drivers.
3. HPA created is getting values but intermittently it is showing unknown values for stack driver metrics.


### Logs from KEDA operator

```
1 logr.go:279] keda_metrics_adapter/gcp_stackdriver_scaler "msg"="error getting metric value" "error"="could not find stackdriver metric with filter metric.type=\"loadbalancing.googleapis.com/https/backend_request_count\" AND resource.type=\"https_lb_rule\" AND resource.label.backend_target_name=\"<application_name>\""  
```


### KEDA Version

2.7.1

### Kubernetes Version

< 1.23

### Platform

Google Cloud

### Scaler Details

gcp-stackdriver

### Anything else?

_No response_

**Comment by JorTurFer** [comment]
Hi,
Sorry for the slow response... You should review your configuration, most probably the time window is too small and during that period there isn't any metric, and that's why you see that error, because basically KEDA can't get any metrics with those parameters
