### ISSUE TITLE
Review logger initialization on every scaler

### ISSUE THREAD

**Issue by JorTurFer** [kedacore/keda#3947]
### Report

After the changes in the logging inside scalers, there were 2 scalers which generate panic due to a mistake in the initialization. We should review all the scalers to ensure no more panics are thrown because this release in next release.

- https://github.com/kedacore/keda/issues/3945
- https://github.com/kedacore/keda/issues/3811

**Comment by tomkerkhove** [comment]
Thanks! Let's make sure we have this in the "new scaler" docs as well, if need be.
