### ISSUE TITLE
Improvement: Increase logging V-level in Apache Kafka scaler

### ISSUE THREAD

**Issue by dkv** [kedacore/keda#3948]
### Description:
The Apache Kafka scaler logs stuff at V(1) level in all cases but one, that uses V(0).
V(0) makes it impossible to suppress those logs, and in our case it's *a lot* of logging.

### Proposal:
Log everything in the Apache Kafka scaler with at least V(1)

Tiny change. Change 0 -> 1 in: https://github.com/kedacore/keda/blob/main/pkg/scalers/kafka_scaler.go#L423

**Comment by zroubalik** [comment]
@dkv make sense, mind opening a PR to fix this please?

**Comment by JorTurFer** [comment]
This is already done: https://github.com/kedacore/keda/pull/3953
