### ISSUE TITLE
Example scaling mechanism for known programs

### ISSUE THREAD

**Issue by yuvalweber** [kedacore/keda#3950]
### Proposal

I want to start a new section in the documentation of keda regarding scaling of known programs many users use:
For example programs like: nginx, logstash, prometheus,  argoCD, jenkins workers...

If for example we take nginx then people could provide scaling options like what scaler did they use and which kind of metric they used and why.

To make my question more clearer if I'll take for example I could say that we scale nginx based on number of connections waiting using the prometheus metric: `nginx_ingress_controller_nginx_process_connections{state="waiting"}` because we see that nginx getting slow if there are more than 100 connections waiting with the sum of our cpu and ram.

Then we could gather all the different options and when new users would think for examples to scale their infrastructure they would already have many examples to use.

I want you to help me decide on template for this kind of documentation like what to include (scaler used, scaledObject, metric Used, company name...)

**Comment by JorTurFer** [comment]
Nice! This is an awesome idea ❤ 
Maybe we can create a getting started section in docs, something like a happy path, including the installation and some of these examples. WDYT @kedacore/keda-docs @kedacore/keda-core-contributors

**Comment by zroubalik** [comment]
I like this idea!

**Comment by yuvalweber** [comment]
So lets discuss regarding a template so we can start working on this

**Comment by JorTurFer** [comment]
Any update?

**Comment by yuvalweber** [comment]
Do you want to suggest some kind of template?

**Comment by JorTurFer** [comment]
I think that something like CI/CD workers (Azure DO or any other we can do with current scalers) is something useful. It's the typical event driven workload that every company could have
