### ISSUE TITLE
Setting kube-api-qps and kube-api-burst are not working

### ISSUE THREAD

**Issue by kevinteng525** [kedacore/keda#3952]
### Report

Sets kube-api-qps and kube-api-burst for KEDA adapter will not take effective.

It was set here
```
	cfg, err := config.GetConfig()
	if cfg != nil {
		cfg.QPS = adapterClientRequestQPS
		cfg.Burst = adapterClientRequestBurst
		cfg.DisableCompression = disableCompression
	}
```
However never got used, when new Manager, it will use another config
```
         mgr, err := ctrl.NewManager(ctrl.GetConfigOrDie(), ctrl.Options{
		MetricsBindAddress: metricsBindAddress,
		Scheme:             scheme,
		Namespace:          namespace,
		LeaseDuration:      leaseDuration,
		RenewDeadline:      renewDeadline,
		RetryPeriod:        retryPeriod,
	})
```

### Expected Behavior

Setting kube-api-qps and kube-api-burst should be working

### Actual Behavior

Setting kube-api-qps and kube-api-burst are not working

### Steps to Reproduce the Problem

1. Pass kube-api-qps and kube-api-burst as args, as following
```
- /usr/local/bin/keda-adapter
        - --secure-port=6443
        - --logtostderr=false
        - --log_file=/tmp/apiserver.log
        - --log_dir=/tmp/log
        - --kube-api-qps=70
        - --kube-api-burst=100
```

### Logs from KEDA operator

N/A

### KEDA Version

2.8.1

### Kubernetes Version

1.23

### Platform

Any

**Comment by v-shenoy** [comment]
The `main` branch code is using the correct config.
This feature was added recently, and will be released as part of KEDA v2.9.

**Comment by v-shenoy** [comment]
> The `main` branch code is using the correct config.
> 
> https://github.com/kedacore/keda/blob/af948a5a8f72bb060b1757a3b33c2a3ad4616a52/main.go#L117-L122
> 
> 
> This feature was added recently, and will be released as part of KEDA v2.9.

Ah, I am dumb, you're talking about the metrics server, where I can see it's not being used.
https://github.com/kedacore/keda/blob/af948a5a8f72bb060b1757a3b33c2a3ad4616a52/adapter/main.go#L127

**Comment by zroubalik** [comment]
Good catch, thanks for reporting.

**Comment by zroubalik** [comment]
Relates to https://github.com/kedacore/keda/issues/3730

**Comment by kevinteng525** [comment]
> Relates to #3730

Thanks @zroubalik for the fixing! I was also planning to submit a PR for this:)
