### ISSUE TITLE
Prometheus metrics on KEDA Metric Server are deprecated in favor of Prometheus metrics on KEDA Operator

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda#3972]
Prometheus metrics on KEDA Metric Server are deprecated in favor of Prometheus metrics on KEDA Operator.

This change was done to bring the metrics closer to the operator which is now integrating with 3rd party for improved performance and integration

## Impact
- End-users have to scrape metrics on KEDA operator
- Metric names have been renamed to use `keda_scaler_` prefix instead of `keda_metrics_adapter_`

Change was introduced in https://github.com/kedacore/keda/issues/3919.

## Timeline

- Dec 7th, 2022 - Deprecation
- July, 2023 - Removal in KEDA v2.11

## Learn more

**Docs:** https://keda.sh/docs/latest/operate/prometheus/#keda-operator
**Engineering issue:** https://github.com/kedacore/keda/issues/3930
**Discussion:** https://github.com/kedacore/keda/discussions/3973

**Comment by JorTurFer** [comment]
https://github.com/kedacore/keda/pull/4471
https://github.com/kedacore/charts/pull/432
https://github.com/kedacore/keda-docs/pull/1117

**Comment by tomkerkhove** [comment]
@JorTurFer This is just deprecation notice, please link everything to the engineering issue on https://github.com/kedacore/keda/issues/3930 as we can only close this once it is released.

**Comment by JorTurFer** [comment]
This can be closed, it was released as part of v2.11
