### ISSUE TITLE
Provide ability to control what pods to scale 

### ISSUE THREAD

**Issue by gyuvaraj10** [kedacore/keda#3981]
### Proposal

Provide ability to scale what pods to scale. Example: Scale the pods that were created 5 min ago if pods exist.

### Scaler Source

pods

### Scaling Mechanics

by triggers (Example: Azure Service Bus)

### Authentication Source

any

**Comment by tomkerkhove** [comment]
Unfortunately that's up to the Kubernetes scheduler to decide and KEDA has no control over it.

There might be a control strategy option in HPA that I'm not aware of but I doubt it - @zroubalik ?

**Comment by zroubalik** [comment]
Yeah, this is more responsibility of HPA or more precise: k8s scheduler.

**Comment by tomkerkhove** [comment]
CLosing as this is more for Kubernetes upstream but feel free to re-open if you have concerns.
