### ISSUE TITLE
Add e2e test for Datadog features timeWindowOffset and lastAvailablePointOffset

### ISSUE THREAD

**Issue by dogzzdogzz** [kedacore/keda#3987]
### Proposal

Add e2e test coverage for Datadog features timeWindowOffset and lastAvailablePointOffset

**Comment by JorTurFer** [comment]
hi @dogzzdogzz ,
Are you willing to contribute it?

**Comment by dogzzdogzz** [comment]
Can but quite busy recently, will revisit this issue when I am available.
