### ISSUE TITLE
Azure Pipelines Scaler: Improve error logging using poolID

### ISSUE THREAD

**Issue by JorTurFer** [kedacore/keda#3996]
### Proposal

Currently, in case of any error validating the poolID, the error is hidden:
```go
body, err := getAzurePipelineRequest(ctx, url, metadata, httpClient)
	if err != nil {
		return -1, fmt.Errorf("agent pool with id `%s` not found", poolID)
	}

```
This makes impossible to troubleshoot the reason behind the fails, we should just return the original error

**Comment by dttung2905** [comment]
Hello @JorTurFer, it should be a quick fix, I could help with this :pray:

**Comment by JorTurFer** [comment]
Thanks a lot!
