### ISSUE TITLE
Unable to create NATS streaming scaler

### ISSUE THREAD

**Issue by abhirockzz** [kedacore/keda#400]
Creation of a `ScaledObject` for NATS streaming failed. Here is the error log from KEDA operator `Pod` - `Error getting scalers error getting scaler for trigger #0: no scaler found for type: stan"` - this is merged but not yet released? 

(sorry I am not familiar with the end to end process)

**Comment by abhirockzz** [comment]
cc @balchua - I was writing an example. Everything is ready but unable to install the scaler

**Comment by balchua** [comment]
Using the latest image?  May i know the error you're getting?

**Comment by balchua** [comment]
Im also not sure of the release process but i think there is a `master` tag which was released 4 days ago.  I think this tag is taken from the master branch.

**Comment by abhirockzz** [comment]
@balchua the error message is included in the description

I am simply using `kubectl apply -f https://raw.githubusercontent.com/kedacore/keda/master/deploy/KedaScaleController.yaml` to deploy KEDA ([facing a problem with Helm](#401 )) - the operator `Deployment` does refer to the `latest` tag.

**Comment by balchua** [comment]
That yaml you are using is pointing to the `latest` tag (`image: kedacore/keda:latest`).

Try the master tag `image: kedacore/keda:master`

**Comment by balchua** [comment]
@abhirockzz i confirm that the image `kedacore/keda:master` contains the nats streaming scaler.  I tend do it like this. `helm template --namespace keda -n keda --set image.repository=kedacore/keda --set image.tag=master .  | kubectl apply -f -`

**Comment by abhirockzz** [comment]
@balchua Thanks for confirming. It works for me too - I simply updated the image in the YAML mentioned above. But this should simply work out-of-the-box when KEDA is installed using the steps in README (just like it does for other scalers). I guess it's a matter of time? maybe @ahmelsayed can comment ?

**Comment by balchua** [comment]
Thanks for confirming @Abhirockzz

**Comment by anirudhgarg** [comment]
The old yaml file which you are trying to use no longer works after we merged in the operator sdk integration. We are going to be updating the documentation very soon.
