### ISSUE TITLE
Azure Storage Queue Scaler: should report both visible and invisible message count to compute queue length.

### ISSUE THREAD

**Issue by moria97** [kedacore/keda#4002]
### Report

From [Azure Storage Queue document](https://learn.microsoft.com/en-us/azure/storage/queues/storage-dotnet-how-to-use-queues?tabs=dotnet#use-additional-options-for-dequeuing-messages), queue messages should be set to invisible state when pulled from queue for processing, deleted when processing completes and be visible again when processing fails. So when computing queue length for scaling, it's better to consider both visible and invisible messages like in the [get-queue-length](https://learn.microsoft.com/en-us/azure/storage/queues/storage-dotnet-how-to-use-queues?tabs=dotnet#get-the-queue-length) documentation instead of [counting those visible only](https://github.com/kedacore/keda/blob/f4bee67f5a444338b7c2b93c7b762a27c348867b/pkg/scalers/azure/azure_queue.go#L61).

### Expected Behavior

Use correct queue length to count both visible and invisible messages.

### Actual Behavior

Count only visible messages.

### Steps to Reproduce the Problem

None

### Logs from KEDA operator

```
example
```

### KEDA Version

None

### Kubernetes Version

None

### Platform

None

### Scaler Details

Azure Storage Queue

**Comment by JorTurFer** [comment]
Hi,
It makes sense, but maybe there is any reason behind that behavior. Do you know why we don't call directly to `ApproximateMessagesCount()` @ahmelsayed ?
Maybe you could now the reason too (or not) @v-shenoy

**Comment by JorTurFer** [comment]
Let's wait till @ahmelsayed has time to answer us before continue with the PR

**Comment by JorTurFer** [comment]
@ahmelsayed, do you have more info?

**Comment by jellevankerk** [comment]
@JorTurFer @moria97 I think this fix has introduced a bug for me. It no longer scales down if there are invisible messages in the queue (Which is good). However, it also keeps scaling up on these invisible messages. Was this expected behavior, if yes is there some way to disable this behaviour
