### ISSUE TITLE
couldn't get resource list for external.metrics.k8s.io/v1beta1: Got empty response for: external.metrics.k8s.io/v1beta1

### ISSUE THREAD

**Issue by r0bj** [kedacore/keda#4008]
### Report

After kubectl binary upgrade to v1.26.0, every kubectl command execution generates error message:
```
E1212 15:51:04.666205   20905 memcache.go:255] couldn't get resource list for external.metrics.k8s.io/v1beta1: Got empty response for: external.metrics.k8s.io/v1beta1
```

API service `v1beta1.external.metrics.k8s.io` is a part of keda installation:
```
$ kubectl get apiservices.apiregistration.k8s.io
v1beta1.external.metrics.k8s.io             keda/keda-operator-metrics-apiserver   True        10m
$ k get apiservices.apiregistration.k8s.io v1beta1.external.metrics.k8s.io -o yaml
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: keda-kube-sjc-dev:apiregistration.k8s.io/APIService:keda/v1beta1.external.metrics.k8s.io
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apiregistration.k8s.io/v1","kind":"APIService","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"keda-kube-sjc-dev:apiregistration.k8s.io/APIService:keda/v1beta1.external.metrics.k8s.io"},"labels":{"app.kubernetes.io/component":"operator","app.kubernetes.io/instance":"keda","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"v1beta1.external.metrics.k8s.io","app.kubernetes.io/part-of":"keda-operator","app.kubernetes.io/version":"2.7.1","helm.sh/chart":"keda-2.7.2"},"name":"v1beta1.external.metrics.k8s.io"},"spec":{"group":"external.metrics.k8s.io","groupPriorityMinimum":100,"insecureSkipTLSVerify":true,"service":{"name":"keda-operator-metrics-apiserver","namespace":"keda"},"version":"v1beta1","versionPriority":100}}
  creationTimestamp: "2022-12-12T23:42:02Z"
  labels:
    app.kubernetes.io/component: operator
    app.kubernetes.io/instance: keda
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: v1beta1.external.metrics.k8s.io
    app.kubernetes.io/part-of: keda-operator
    app.kubernetes.io/version: 2.7.1
    helm.sh/chart: keda-2.7.2
  name: v1beta1.external.metrics.k8s.io
  resourceVersion: "1246725484"
  uid: c4258206-7dd3-4a1b-96b8-d8a339d00a5f
spec:
  group: external.metrics.k8s.io
  groupPriorityMinimum: 100
  insecureSkipTLSVerify: true
  service:
    name: keda-operator-metrics-apiserver
    namespace: keda
    port: 443
  version: v1beta1
  versionPriority: 100
status:
  conditions:
  - lastTransitionTime: "2022-12-12T23:42:02Z"
    message: all checks passed
    reason: Passed
    status: "True"
    type: Available
```

Response from keda v1beta1.external.metrics.k8s.io service:
```
$ kubectl get --raw "/apis/external.metrics.k8s.io/v1beta1"
{"kind":"APIResourceList","apiVersion":"v1","groupVersion":"external.metrics.k8s.io/v1beta1","resources":[]}
```

### Expected Behavior

kubectl command execution is not generating error message.

### Actual Behavior

Every kubectl command execution is generating error message:
```
E1212 15:54:39.565250   21101 memcache.go:255] couldn't get resource list for external.metrics.k8s.io/v1beta1: Got empty response for: external.metrics.k8s.io/v1beta1
```

### Steps to Reproduce the Problem

1. Install kubectl binary in version v1.26.0
2. Execute kubectl command on k8s cluster with keda installed

### Logs from KEDA operator

```
example
```

### KEDA Version

2.7.1

### Kubernetes Version

1.25

### Platform

None

**Comment by JorTurFer** [comment]
Hi,
KEDA doesn't support yet k8s 1.26 because it wasn't released before last KEDA release, so we cannot guarantee the compatibility. Just in case, thanks for reporting this, we will investigate

**Comment by JorTurFer** [comment]
Yeah, I have tried with the binary downloaded and I can reproduce it. The problem is that it doesn't make sense and I'll need to debug kubectl xD
In my case, I see the error but it works even the error, is that your case too?

**Comment by r0bj** [comment]
Yes, kubectl seems work fine despite generating error.

**Comment by JorTurFer** [comment]
I can reproduce the issue, I have to figure out how to solve it, but at least I know why it happens, this error is raised when there is any metric exposed by the metrics server, once you deploy a ScaledObject, this error should disappear. Could you check it?

**Comment by r0bj** [comment]
Yes, I can confirm, error message disappears once ScaledObject is present in the cluster.
Knowing that, It kind of make sense, when there is no objects, kubectl complains that "couldn't get resource list for external.metrics.k8s.io/v1beta1" because that list is empty:
```
$ kubectl get --raw "/apis/external.metrics.k8s.io/v1beta1"
{"kind":"APIResourceList","apiVersion":"v1","groupVersion":"external.metrics.k8s.io/v1beta1","resources":[]}
```

**Comment by JorTurFer** [comment]
I'm not sure if this should be de behavior, we are still investigating, but thanks for confirming that it's only without scaled objects

**Comment by JorTurFer** [comment]
Upstream issue: https://github.com/kubernetes-sigs/custom-metrics-apiserver/issues/146

**Comment by JorTurFer** [comment]
This is solved in the upstream so we can expect a fix released soon
