### ISSUE TITLE
Error installing KEDA using Helm chart

### ISSUE THREAD

**Issue by abhirockzz** [kedacore/keda#401]
Steps:

- helm repo add kedacore https://kedacore.azureedge.net/helm
- helm repo update
- helm install kedacore/keda-edge --devel --set logLevel=debug --namespace keda --name keda

Error:

`Error: release keda failed: clusterrolebindings.rbac.authorization.k8s.io "keda-keda-edge" already exists`

**Comment by tomkerkhove** [comment]
Can you provide some information such as chart version please?

**Comment by abhirockzz** [comment]
@tomkerkhove steps are from [the KEDA README](https://github.com/kedacore/keda#deploying-with-a-helm-chart) which does not refer to the chart version

**Comment by ahmelsayed** [comment]
fixed in #402. This should track improving this https://github.com/kedacore/keda/issues/398
