### ISSUE TITLE
Update helm repo for Helm 2.16 and 3.0

### ISSUE THREAD

**Issue by jeffhollan** [kedacore/keda#406]
A few errors reported when trying to use Helm 3 to install (now in RC).  I'm seeing this error:

> helm3 repo add kedacore https://kedacore.azureedge.net/helm
>
> Error: looks like "https://kedacore.azureedge.net/helm" is not a valid chart repository or cannot be reached: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal number into Go struct field ChartVersion.entries.appVersion of type string

I wonder if we should just remove the `appVersion` from our index anyway as it's optional and I'm not sure if it's needed.  I also don't know why helm 3 is complaining as they all look like strings to me, but nonetheless likely need to do some work here to make sure it works.

**Comment by tomkerkhove** [comment]
Have no experience with Helm 3 but could also be based on where it is hosted. For example, I don't know if ACR for example supports Helm 3 yet.

**Comment by bacongobbler** [comment]
a similar issue was reported upstream. https://github.com/helm/helm/issues/6849

Removing the appversion from the index.yaml would help.

**Comment by jeffhollan** [comment]
@ahmelsayed I know there's a ton going on right now but since Helm 3 just went GA today I'm wondering if we may be able to fit this in before KubeCon?

**Comment by jeffhollan** [comment]
Though good news at least is apparently helm 3 won't just auto-upgrade with like `brew install kubernetes-helm` [so that should](https://github.com/Homebrew/homebrew-core/pull/45789) buy us some time too.  I think this could come after 1.0

**Comment by jeffhollan** [comment]
Sorry know I'm spamming this, while it does work on helm 2.15.2, it *does not work* on the latest helm 2.16 release.  So renaming thread and FYI to others, to use helm to install you'll need to use a version < 2.16

**Comment by bacongobbler** [comment]
> Though good news at least is apparently helm 3 won't just auto-upgrade with like `brew install kubernetes-helm` [so that should](https://github.com/Homebrew/homebrew-core/pull/45789) buy us some time too.

https://github.com/Homebrew/homebrew-core/pull/46708
