### ISSUE TITLE
Managed Identity based authentication for the azure-pipelines scaler

### ISSUE THREAD

**Issue by guidooliveira** [kedacore/keda#4072]
### Proposal

Would it be possible to add support or a handler for the scaler to use a managed identity (when running on Azure) to either request a PAT token and use it transparently or to use the Bearer authentication for that. This would make having the PAT token storage(and associated rotation/management) optional, and make the usage a bit more seamless.

### Use-Case

For Self-Hosted agents in AKS for example we need to generate a PAT token and store that (preferably in a secure way) and manage the expiration and possible leakage of the said token. for registering the scaler in the Node Pool.

### Is this a feature you are interested in implementing yourself?

No

**Comment by JorTurFer** [comment]
Hi,
Sadly, it's not possible atm because the Azure Pipelines API doesn't support it, the only authentication method supported is the PAT. Once AzPipelines team release another mechanism, we can include it

**Comment by tomkerkhove** [comment]
> Hi, Sadly, it's not possible atm because the Azure Pipelines API doesn't support it, the only authentication method supported is the PAT. Once AzPipelines team release another mechanism, we can include it

Closing this issue for now because of the above. Feel free to re-open in the future once this is supported.

**Comment by guidooliveira** [comment]
Amazing!

**Comment by davidhoferzeni** [comment]
Awesome, would love to see that feature soon.
Together with federated workload identities (testing that out right now) this would completely remove PATs from our KEDA agent configurations!

**Comment by tomkerkhove** [comment]
@JorTurFer What do you think? Are you still using ADO at Lidl?

**Comment by JorTurFer** [comment]
Yes we do, and we have had a problem with an expired PAT this week xD
I think this feature is really useful and we should add it. In tandem with the support (from MSFT) in the agent side, the Pats can be totally removed.

**Comment by phmcder** [comment]
This looks like it relates to #4853

**Comment by antiphon0** [comment]
+1 to this, just ran into having to replace the PAT by editing the secret in the cluster, which isn't the end of the world - that said, it'd be nice to just not have to worry about it at all.

**Comment by rbnmk** [comment]
+1 For this feature. Would love to get rid of PATs at all ouf our clients for Self Hosted agent scenarios on AKS/Container Apps

**Comment by JorTurFer** [comment]
[This feature has been already merged](https://github.com/kedacore/keda/pull/4867) and shipped as part of v2.13, so I close the issue
