### ISSUE TITLE
Prometheus' metrics in the operator are only exposed when the metrics server requests the metrics

### ISSUE THREAD

**Issue by JorTurFer** [kedacore/keda#4075]
### Report

I have seen that metric `keda_scaler_metrics_value`  is updated when the value is [queried by the ms](https://github.com/kedacore/keda/blob/27e15173dab8f08f41bc5a5d32fed63ecfddab59/pkg/metricsservice/server.go#L45) (and the same for `keda_scaler_error_totals` and `keda_scaled_object_error_totals`), I think that it makes sense to update the metric after `GetMetricsAndActivity`  (inside `GetScaledObjectState`) because it has been read

### KEDA Version

2.9.1

**Comment by zroubalik** [comment]
> Is this related to the fact that apart from Metrics exposed by the Operator SDK, I only see `keda_resource_totals` and `keda_trigger_totals` metrics?
> 
> I was expecting to see `keda_scaler_metrics_value`, `keda_scaler_errors`, `keda_scaler_error_totals` and `keda_scaled_object_error_totals`, even if they were zero.

So you don't see these values once you create a ScaledObject?

**Comment by nunoadrego** [comment]
I was able to see them after following this https://keda.sh/docs/2.9/operate/metrics-server/.

I can now see:
- keda_resource_totals
- keda_scaled_errors
- keda_scaler_errors (don't appear in the [docs](https://keda.sh/docs/2.9/operate/prometheus/) or have a different name)
- keda_scaler_metrics_value
- keda_trigger_totals

Missing:
- keda_scaler_error_totals
- keda_scaled_object_error_totals

The latest official Grafana dashboard depends on some of these metrics.

**Comment by zroubalik** [comment]
So the supported metrics are (for 2.9.1.)

```
keda_scaler_metrics_value
keda_scaler_errors
keda_scaler_error_totals
keda_scaled_object_errors     # due to a bug this is now reported as keda_scaled_errors, has been fixed already
keda_resource_totals
keda_trigger_totals
```

**Comment by nunoadrego** [comment]
Will try it and provide feedback @zroubalik. Thanks!

**Comment by vmm-afonso** [comment]
> Is this related to the fact that apart from Metrics exposed by the Operator SDK, I only see `keda_resource_totals` and `keda_trigger_totals` metrics?
> 
> I was expecting to see `keda_scaler_metrics_value`, `keda_scaler_errors`, `keda_scaler_error_totals` and `keda_scaled_object_error_totals`, even if they were zero.

Not sure if this was supposed to be fixed since I'm rolling with the latest release v.2.9.3 and I am having the same problem. 
<img width="960" alt="Captura de ecrã 2023-02-10 003749" src="https://user-images.githubusercontent.com/115153075/217970880-38f32e93-df5d-4274-bd24-e86cea3254bc.png">
This is what I'm getting


I was trying to get the grafana dashboard to work but as @nunoadrego pointed out, the dashboard depends on some of these metrics. I'm also unable to set some most of the variables for the dashboard apart from the data-source.

Any tips?
