### ISSUE TITLE
Update Grafana Dashboard to use Keda 2.9.x metrics

### ISSUE THREAD

**Issue by defenestration** [kedacore/keda#4076]
### Proposal

Update grafana dashbaord to 2.9 metrics

### Use-Case

I have been enabling metrics on services on my cluster. I updated keda to 2.9.1 and set up to scrape the Operator only, since i saw some deprecation warnings in the latest docs here https://keda.sh/docs/2.9/operate/prometheus/

I loaded up the dashboard linked there as well but seems like it is set up with the deprecated metrics.

Would be cool to get a dashboard set up for the new metrics in keda 2.9!

### Is this a feature you are interested in implementing yourself?

No

**Comment by tomkerkhove** [comment]
Huh, I thought we already changed them to 2.9.

Are you willing to jump in here and help us a bit?

**Comment by defenestration** [comment]
I feel I am not too familiar enough with the metrics or the changes between the versions to tackle this at present unfortunately.

**Comment by nunoadrego** [comment]
I think they were updated here: https://github.com/kedacore/keda/pull/3934

**Comment by JorTurFer** [comment]
Yeah, the dashboard is already using the new metrics.
I close this issue, but feel free to reopen it if you have any thing related
