### ISSUE TITLE
Create a landing page for https://keda.sh

### ISSUE THREAD

**Issue by jeffhollan** [kedacore/keda#408]
We can host, but we'd love to have a page for people to find and learn more about the project / link to the page.

Static hosting on GitHub pages is sweet, whatever

// @tomkerkhove

**Comment by tomkerkhove** [comment]
I'll give Hugo a try, any preference for a theme?
https://themes.gohugo.io/

**Comment by tomkerkhove** [comment]
@jeffhollan feel free to assign it to me.

WIP - https://keda-staging.netlify.com/

**Comment by tomkerkhove** [comment]
We're done and available on https://keda.sh.
