### ISSUE TITLE
Kafka scalers to support multiple topics

### ISSUE THREAD

**Issue by sinanub18** [kedacore/keda#4082]
### Proposal

The kafka scaler is autoscaling based on single topic, but in some of scenarios we have multiple topics for 1 service and instead of adding multiple kafka scaledobject/triggers, the request is to provide support to autoscaling based on multiple topics in one Kafka trigger.
      
- type: kafka
    metadata:
      bootstrapServers: localhost:9092
      consumerGroup: my-group
      eventSources:
        - topic: test-topic-1
           lagThreshold: "50"
       -  topic: test-topic-2       
           lagThreshold: "50"
      
Ref Issue - https://github.com/kedacore/keda/issues/828 

### Use-Case

This will help to reduce extra effort of creating multiple scaledobject.

### Is this a feature you are interested in implementing yourself?

No

**Comment by zroubalik** [comment]
The current implementation doesn't allow this, the preferred solution is to create a separater trigger for each topic. 

There is a proposal to support more flexible Kafka configuration https://github.com/kedacore/keda/issues/2447 you can take a look and contribute :)
