### ISSUE TITLE
Automatically run main/nightly e2e tests on Mariner nodes

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda#4085]
Automatically run main/nightly e2e tests on Mariner nodes to ensure KEDA runs well on it.

## Checklist
- [ ] Introduce new AKS cluster with Mariner nodes (see [infra](https://github.com/kedacore/testing-infrastructure))
- [ ] Ensure that the new cluster oidc is registered in AWS/GCP for pod identity tests
- [ ] Introduce another job in [the template](https://github.com/kedacore/keda/blob/main/.github/workflows/template-main-e2e-test.yml) to check the second cluster in parallel

**Comment by JorTurFer** [comment]
Does this still make sense? The problem with mariner was related with workload identity add-on and not with the distro itself

**Comment by tomkerkhove** [comment]
It still does not hurt though; but not urgent

**Comment by JorTurFer** [comment]
I think that we can close this tbh

**Comment by tomkerkhove** [comment]
Agreed
