### ISSUE TITLE
NATS JetStream scaler assume the cluster runs on kubernetes

### ISSUE THREAD

**Issue by mfadhlika** [kedacore/keda#4101]
### Report

Jetstream scaler assume the cluster run on the kubertenes cluster, which makes the scaler failed to find consumer leader monitoring url if that's not the case.

### Expected Behavior

The scaler get correct leader monitoring node url even if NATS Jetstream cluster is not on kubernetes

### Actual Behavior

The scaler assume first item when node url split by `.` is the node name and always have `<node>.<monitoringURL>` as URL which may not be case when NATS Jetstream run on multiple VMs.

### Steps to Reproduce the Problem

1. Create NATS Jetstream cluster using VMs with load balancer
2.  Use Jetstream scaler as documented
3. Get cluster information 
```
❯ curl -s "http://load-balancer-ip:8222/varz" | jq .cluster
{
  "name": "nats",
  "addr": "172.0.0.2",
  "cluster_port": 4221,
  "auth_timeout": 2,
  "urls": [
    "172.0.0.3:4221", <-- currently 172 considered as node name
    "172.0.0.4:4221"
  ],
  "tls_timeout": 2
}
```

### Logs from KEDA operator

```
Get "http://172.nats.company.internal:8222/jsz?acc=$G&consumers=true&config=true": dial tcp: lookup 172.nats.company.internal on 10.200.0.10:53: no such host
```

### KEDA Version

2.9.1

### Kubernetes Version

1.24

### Platform

Google Cloud

### Scaler Details

NATS Jetstream

**Comment by JorTurFer** [comment]
Interesting.
Are you willing to contribute with the fix? 
Isn't the machine FQDNs enough?

**Comment by zroubalik** [comment]
There's open PR for this already.

**Comment by mfadhlika** [comment]
@zroubalik I opened the PR regarding this https://github.com/kedacore/keda/pull/4102

**Comment by JorTurFer** [comment]
f**k, sorry, I didn't see it, my fault :(

**Comment by rayjanoka** [comment]
this change seems to have broken nats jetstream on my k8s cluster
