### ISSUE TITLE
Elasticsearch scaler: unable to fetch metrics

### ISSUE THREAD

**Issue by cyberjeff-u8t** [kedacore/keda#4103]
### Report

Using elasticsearch scaler is triggering an error: 
Unable to fetch metrics from external metrics API: rpc error: code = Unknown desc = error when getting metric values no matching metrics found.

### Expected Behavior

Expecting to be able to query value from a metric exposed by KEDA Metrics Server.

### Actual Behavior

Error from server: rpc error: code = Unknown desc = error when getting metric values no matching metrics found 

### Steps to Reproduce the Problem

1. Install KEDA of course
helm repo add kedacore https://kedacore.github.io/charts
helm repo update
kubectl create namespace keda
helm install keda kedacore/keda --namespace keda

2. Create a ScaledObject
```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: elasticsearch-scaledobject
  namespace: app
spec:
  scaleTargetRef:
    name: "test-deployment"
  triggers:
    - type: elasticsearch
      metadata:
        addresses: "https://xxxxxx:9200"
        username: "xxxxx"
        password: "xxxxx"
        index: "logs"
        searchTemplateName: "test"
        valueLocation: "hits.total.value"
        targetValue: "1"
        metricType: "Value"
        unsafeSsl: "true"
```

3. Query metrics exposed by KEDA:
`kubectl get --raw "/apis/external.metrics.k8s.io/v1beta1" | jq
{
  "kind": "APIResourceList",
  "apiVersion": "v1",
  "groupVersion": "external.metrics.k8s.io/v1beta1",
  "resources": [
    {
      "name": "s0-elasticsearch-test",
      "singularName": "",
      "namespaced": true,
      "kind": "ExternalMetricValueList",
      "verbs": [
        "get"
      ]
    }
  ]
}`

4. Query value for that metric
`kubectl get --raw "/apis/external.metrics.k8s.io/v1beta1/namespaces/app/s0-elasticsearch-test?labelSelector=scaledobject.keda.sh%2Fname%3Delasticsearch-scaledobject"`
Error from server: rpc error: code = Unknown desc = error when getting metric values no matching metrics found for s0-elasticsearch-test

### Logs from KEDA operator

keda-operator log:
```
2023-01-13T09:41:21Z    DEBUG   scalehandler    Removing entry from ScalersCache        {"key": "scaledobject.app.elasticsearch-scaledobject"}
2023-01-13T09:41:21Z    DEBUG   scalehandler    scaler error encountered, clearing scaler cache
2023-01-13T09:41:34Z    DEBUG   scalehandler    Getting metrics from scaler     {"scaledObject.Namespace": "app", "scaledObject.Name": "elasticsearch-scaledobject", "scaler": "elasticsearchScaler", "metricName": "s0-elasticsearch-test", "metrics": [], "scalerError": "error inspecting elasticsearch: valueLocation must point to value of type number but got: 'Null'"}
2023-01-13T09:41:34Z    ERROR   scalehandler    error getting metric for scaler {"scaledObject.Namespace": "app", "scaledObject.Name": "elasticsearch-scaledobject", "scaler": "elasticsearchScaler", "error": "error inspecting elasticsearch: valueLocation must point to value of type number but got: 'Null'"}
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).GetScaledObjectMetrics
        /workspace/pkg/scaling/scale_handler.go:449
github.com/kedacore/keda/v2/pkg/metricsservice.(*GrpcServer).GetMetrics
        /workspace/pkg/metricsservice/server.go:45
github.com/kedacore/keda/v2/pkg/metricsservice/api._MetricsService_GetMetrics_Handler
        /workspace/pkg/metricsservice/api/metrics_grpc.pb.go:79
google.golang.org/grpc.(*Server).processUnaryRPC
        /workspace/vendor/google.golang.org/grpc/server.go:1340
google.golang.org/grpc.(*Server).handleStream
        /workspace/vendor/google.golang.org/grpc/server.go:1713
google.golang.org/grpc.(*Server).serveStreams.func1.2
        /workspace/vendor/google.golang.org/grpc/server.go:965
2023-01-13T09:41:34Z    DEBUG   scalehandler    Removing entry from ScalersCache        {"key": "scaledobject.app.elasticsearch-scaledobject"}
2023-01-13T09:41:34Z    DEBUG   scalehandler    scaler error encountered, clearing scaler cache
```
keda-operator-metrics-apiserver log:
```
I0113 09:41:03.991667       1 provider.go:86] keda_metrics_adapter/provider "msg"="KEDA Metrics Server received request for external metrics" "metric name"="s0-elasticsearch-test" "metricSelector"="scaledobject.keda.sh/name=elasticsearch-scaledobject" "namespace"="app"
I0113 09:41:04.230146       1 provider.go:104] keda_metrics_adapter/provider "msg"="Receiving metrics" "metrics"=null "scaledObjectName"="elasticsearch-scaledobject" "scaledObjectNamespace"="app"
E0113 09:41:04.230249       1 status.go:71] apiserver received an error that is not an metav1.Status: &status.Error{s:(*status.Status)(0xc00000fa78)}: rpc error: code = Unknown desc = error when getting metric values no matching metrics found for s0-elasticsearch-test

```

### KEDA Version

2.9.1

### Kubernetes Version

1.24

### Platform

Microsoft Azure

### Scaler Details

Elasticsearch

### Anything else?

The elasticsearch search-template is defined and working from curl command.
connectivity with elastic node from keda pod works.

**Comment by cyberjeff-u8t** [comment]
is it linked to #4088 ?

**Comment by zroubalik** [comment]
The error is:
`"error inspecting elasticsearch: valueLocation must point to value of type number but got: 'Null'"`

So you should check that the  GJSON path notation behind `valueLocation` points to number. Based on the error it is not the case.

**Comment by cyberjeff-u8t** [comment]
The GSJON path is the most simple: hits.total.value
The elasticsearch query works from pod which is calling it, it does return a proper json.

**Comment by cyberjeff-u8t** [comment]
I've upgraded to KEDA 2.10.0.
I've followed the documentation: https://keda.sh/docs/2.10/scalers/elasticsearch/
The valueLocation is simple: hits.total.value 

I'm still seeing:

`
E0310 07:56:56.971183       1 status.go:71] apiserver received an error that is not an metav1.Status: &status.Error{s:(*status.Status)(0xc00122c510)}: rpc error: code = Unknown desc = error when getting metric values no matching metrics found for s0-elasticsearch-test

and

2023-03-10T08:10:31Z	ERROR	scale_handler	error getting metric for scaler	{"scaledObject.Namespace": "ingress-nginx", "scaledObject.Name": "elasticsearch-scaledobject", "scaler": "elasticsearchScaler", "error": "error inspecting elasticsearch: valueLocation must point to value of type number but got: 'Null'"}
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).GetScaledObjectMetrics
	/workspace/pkg/scaling/scale_handler.go:485
github.com/kedacore/keda/v2/pkg/metricsservice.(*GrpcServer).GetMetrics
	/workspace/pkg/metricsservice/server.go:48
github.com/kedacore/keda/v2/pkg/metricsservice/api._MetricsService_GetMetrics_Handler
	/workspace/pkg/metricsservice/api/metrics_grpc.pb.go:98
google.golang.org/grpc.(*Server).processUnaryRPC
	/workspace/vendor/google.golang.org/grpc/server.go:1336
google.golang.org/grpc.(*Server).handleStream
	/workspace/vendor/google.golang.org/grpc/server.go:1704
google.golang.org/grpc.(*Server).serveStreams.func1.2
	/workspace/vendor/google.golang.org/grpc/server.go:965
2023-03-10T08:10:40Z	ERROR	scale_handler	error getting scale decision	{"scaledObject.Namespace": "ingress-nginx", "scaledObject.Name": "elasticsearch-scaledobject", "scaler": "elasticsearchScaler", "error": "error inspecting elasticsearch: valueLocation must point to value of type number but got: 'Null'"}
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).getScaledObjectState
	/workspace/pkg/scaling/scale_handler.go:594
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).checkScalers
	/workspace/pkg/scaling/scale_handler.go:228
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).startScaleLoop
	/workspace/pkg/scaling/scale_handler.go:167
`

**Comment by cyberjeff-u8t** [comment]
From kubernetes cluster, when I query:
`curl https://myelastic/myindex/_search/template?pretty -H 'Content-Type: application/json' -d'
{ "id": "test" } `

I got something like:

`{
  "took" : 3,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 8831,
      "relation" : "eq"
    },
    "max_score" : 1.0,
    "hits" : [
      { 
         ..............
`

Is there any way to debug the full http response received by keda pod ?

**Comment by zroubalik** [comment]
@cyberjeff-u8t Sorry I missed this, unfortunately not, you can modify the scaler and add a debug msg here: https://github.com/kedacore/keda/blob/d234876cb4a8f2a5849f62d264afe6c5b06e1dc5/pkg/scalers/elasticsearch_scaler.go#L283-L287

**Comment by masyutka** [comment]
I am having the same issue, is there any workaround?

**Comment by cyberjeff-u8t** [comment]
I didn’t find a way to make it work, there is an issue in the response from
elastic probably…
One way to understand what is happening would be to log the return message
from elastic…

**Comment by cyberjeff-u8t** [comment]
> @cyberjeff-u8t Sorry I missed this, unfortunately not, you can modify the scaler and add a debug msg here:
> 
> https://github.com/kedacore/keda/blob/d234876cb4a8f2a5849f62d264afe6c5b06e1dc5/pkg/scalers/elasticsearch_scaler.go#L283-L287

@zroubalik , would you be able to add a debug log here?

**Comment by zroubalik** [comment]
@cyberjeff-u8t you can add the log message there and build your KEDA image: https://github.com/kedacore/keda/blob/main/BUILD.md#custom-keda-as-an-image

If it proves to be beneficial, then please open a PR that adds a log message here (DEBUG).

**Comment by Adarsh-verma-14** [comment]
Hi @zroubalik , could you open this issue ? I want to contribute in this.

**Comment by gabriel10013** [comment]
Hi,
I'm facing this problem. Do this have any solution?

**Comment by khayong** [comment]
I discovered that the scalar is unable to capture the following error response from ElasticSearch and instead proceeds to parse it.

`[403 Forbidden] {"error":{"root_cause":[{"type":"security_exception","reason":"action...`

So I resolved the issue by fixing the user permissions as indicated in the error message.
