### ISSUE TITLE
External trigger - Istio - KEDA API metrics server Not working

### ISSUE THREAD

**Issue by miaooss** [kedacore/keda#4106]
### Report

Scenario: 

We are using an external trigger for KEDA.
We have Istio installed inside the Cluster.

So KEDA needs Istio in order to communicate with the external trigger.

By injecting the Istio inside KEDA we have an Error from the API service `/apis/external.metrics.k8s.io/v1beta1": remote error: tls: unknown certificate authority.`

Note:
https://keda.sh/docs/2.5/troubleshooting/
The troubleshooting for us does not work since the External Trigger use istio

### Expected Behavior

The API service should be up and running

### Actual Behavior

 API service is returning a tls certificate issue

### Steps to Reproduce the Problem

1. Create namespace with Istio injection
2. Wait for the pods to be ready
3. ApiService will just return an error

Note: if you don't inject Istio at first and the API service is ready, you can inject Istio and everything worked fine.

### Logs from KEDA operator

v1beta1.external.metrics.k8s.io

```
FailedDiscoveryCheck: failing or missing response from https://10.240.0.27:6443/apis/external.metrics.k8s.io/v1beta1: Get "https://10.240.0.27:6443/apis/external.metrics.k8s.io/v1beta1": remote error: tls: unknown certificate authority
```

### KEDA Version

2.5.0

### Kubernetes Version

1.23

### Platform

Microsoft Azure

### Scaler Details

External

### Anything else?

Keda is working fine if we remove istio, wait for the `API service` to be up and running then inject istio and kill the `keda-operator `and  `keda-operator-metrics-apiserver` pods to have istio correctly injected

**Comment by JorTurFer** [comment]
Hi,
The problem with service mesh is that it manages all the traffic, and that's a problem for trusted connections. IDK if istio supports CA Bundle injection, if it does, you should inject the CA Bundle in the apiservice in order to establish a trusted connection between api server and KEDA through istio.
I'm not 100% sure if this will solve the problem, but definitively I guess it doesn't work without this
