### ISSUE TITLE
Kafka scaler - "error creating kafka client: kafka: client has run out of available brokers to talk to: EOF"

### ISSUE THREAD

**Issue by nkfirdigi** [kedacore/keda#4108]
### Discussed in https://github.com/kedacore/keda/discussions/4090

<div type='discussions-op-text'>

<sup>Originally posted by **nkfirdigi** January 11, 2023</sup>
Hi
I'm using kafka scaler
Keda version 2.9.1
using kafka confluent cloud
Getting error "error creating kafka client: kafka: client has run out of available brokers to talk to: EOF" in keda operator
I used various versions  "0.10.x.0" up to "3.3.1", got the same error.
Appreciate any suggestion, 

my kafka scaler:
```
  triggers:
    - type: kafka
      metadata:
        bootstrapServers: pkc-yyyyyy.aws.confluent.cloud:9092
        consumerGroup: typed-consumer      
        topic: keda-test
        lagThreshold: "2"
        activationLagThreshold: "1"
        offsetResetPolicy: "latest"
        scaleToZeroOnInvalidOffset: "true"
        allowIdleConsumers: "true"
        version: "0.10.2.0"
      authenticationRef:
        name: keda-trigger-auth-kafka-credential

```</div>

**Comment by zroubalik** [comment]
Are you able to use sarama client to connect to the Kafka broker from some test app?

Unfortunately sarama client doesn't provide good info on what is broken. You might want to try tweak the sasl/ssl modes. Hard to say what is wrong 🤷‍♂️

**Comment by nkfirdigi** [comment]
@zroubalik 
Tx for the reply
Unfortunately I'm not python guy :) , but will try your suggestion.
Do U know if there is any plan to replace this client library?

**Comment by zroubalik** [comment]
You might want to try this approach: 

https://github.com/kedacore/keda/issues/1241#issuecomment-933773261

I am not aware of any plans with replacing the library, but we are definitely open to contributions :)

**Comment by nkfirdigi** [comment]
@zroubalik 

In the documentation there is a property called "authMod", but in the source code I saw it is called "sasl"
Is this error in the documentation?

**Comment by zroubalik** [comment]
@nkfirdigi where do you see `authMod` in the documentation? https://keda.sh/docs/2.9/scalers/apache-kafka/

**Comment by nkfirdigi** [comment]
@zroubalik 
check here
https://keda.sh/docs/1.4/scalers/apache-kafka/#authentication-parameters


```
Credential based authentication:

authMode - Kafka sasl auth mode. (Values: none, sasl_plaintext, sasl_ssl, sasl_ssl_plain, sasl_scram_sha256, sasl_scram_sha512. Default: none, Optional)
username - (Optional)
password - (Optional)
ca - Certificate authority file for TLS client authentication sasl_ssl. (Optional)
cert - Certificate for client authentication sasl_ssl. (Optional)
key - Key for client authentication with sasl_ssl. Optional)
```
