### ISSUE TITLE
Version compatibility doesn't match the documentation

### ISSUE THREAD

**Issue by ClementGautier** [kedacore/keda#4126]
### Report

During the deployment of the version 2.8.1 of the Helm chart on a v1.17 Kubernetes cluster I got a version validation error. 

### Expected Behavior

I expected the 2.8 version to be compatible with 1.17 as it's stated on this page: https://keda.sh/docs/2.9/operate/cluster/#kubernetes-compatibility

### Actual Behavior

```installation failed: chart requires kubeVersion: >=v1.20.0-0 which is incompatible with Kubernetes v1.17.6```

### Steps to Reproduce the Problem

1. Launch a 1.17 cluster using kind or minikube
2. helm install
3. see the validation error

### Logs from KEDA operator

n/a

### KEDA Version

2.8.1

### Kubernetes Version

< 1.23

### Platform

Any

### Scaler Details

n/a

**Comment by JorTurFer** [comment]
Hey @ClementGautier 
You are right, most probably we changed it by error :( 
We are planing to release an [exceptional KEDA release v2.8.2](https://github.com/kedacore/keda/issues/4132) (v2.8.3 for the chart) soon, we will include this fix too

**Comment by JorTurFer** [comment]
Hi @ClementGautier 
KEDA v2.8.2 has been released, you can use it with the [chart v2.8.3](https://github.com/kedacore/charts/releases/tag/v2.8.3)

**Comment by ClementGautier** [comment]
@JorTurFer : I think you can reopen the issue, the securityContext seccompProfile isn't available on 1.17 (it's a 1.19+ feature). There is a workaround by specifying `--set securityContext.metricServer.seccompProfile=null --set securityContext.operator.seccompProfile=null` to unset the configuration but I think it should be the default behavior.

**Comment by JorTurFer** [comment]
> @JorTurFer : I think you can reopen the issue, the securityContext seccompProfile isn't available on 1.17 (it's a 1.19+ feature). There is a workaround by specifying `--set securityContext.metricServer.seccompProfile=null --set securityContext.operator.seccompProfile=null` to unset the configuration but I think it should be the default behavior.

Yes, we should definitively release another chart version removing those values. I tried to deploy helm chart into old k8s versions but kind raised errors with that old versions (that's why I added only >=1.19)

**Comment by ClementGautier** [comment]
Actually I can't even use the workaround as I'm using a very old version of FluxCD v1 on this cluster that don't allow my to unset a default value 😓. Ping me whenever you release a new 2.8 version with the fix, I'd much appreciate ❤️

**Comment by JorTurFer** [comment]
Hello @ClementGautier 
Could you give a try to v2.8.4? 
https://github.com/kedacore/charts/releases/tag/v2.8.4

**Comment by JorTurFer** [comment]
I close this as solved, feel free to reopen it if the chart doesn't work
