### ISSUE TITLE
Create e2e tests for all exposed Prometheus metrics

### ISSUE THREAD

**Issue by zroubalik** [kedacore/keda#4127]
### Proposal

At the moment KEDA exposes following metrics:

- [x] `keda_scaler_active`
- [x] `keda_scaler_metrics_value`
- [x] `keda_scaler_metrics_latency`
- [ ] `keda_scaler_errors`
- [ ] `keda_scaler_error_totals`
- [ ] `keda_scaled_object_errors`
- [x] `keda_resource_totals`
- [x] `keda_trigger_totals`

We should cover all of these metrics by e2e tests:
 - test that metrics are exposed
 - test that metrics are correctly calculated (ie. we should test that metrics related to errros are correctly incremented in case of an error in a scaler/scaledobject, etc.).

Exisiting Prometheus Metrics e2e tests: https://github.com/kedacore/keda/blob/main/tests/internals/prometheus_metrics/prometheus_metrics_test.go

Docs: https://keda.sh/docs/2.10/operate/prometheus/

**Comment by Parthiba-Hazra** [comment]
hey, is this issue already worked on ? if not then I want to give a try... as I'm new in open source.

**Comment by JorTurFer** [comment]
Hey @Parthiba-Hazra 
There isn't anybody working on this AFAIK, I assign the issue to you 😄 
Thanks for the help!

**Comment by Parthiba-Hazra** [comment]
Hey @JorTurFer thank you for the response .
As a new folk how should I approach this issue, anything that could help me..

**Comment by zroubalik** [comment]
@Parthiba-Hazra there's a doc around e2e tests: https://github.com/kedacore/keda/tree/main/tests#readme

Existing Prometheus metrics related tests are here:
https://github.com/kedacore/keda/blob/main/tests/internals/prometheus_metrics/prometheus_metrics_test.go


In the issue description you can see missing tests, so you need to create test cases for them.

**Comment by Parthiba-Hazra** [comment]
got it 👍

**Comment by Parthiba-Hazra** [comment]
Hey @zroubalik I need some help --
for the **keda_scaler_errors** test case, first I have to apply a **scaled_object** that will cause error with Prometheus , then get the operator metrics and check that keda operator show the errors...
is that right?

**Comment by zroubalik** [comment]
@Parthiba-Hazra yeah, check that Prometheus metrics show the error.

**Comment by Parthiba-Hazra** [comment]
hey @zroubalik I created test cases that asserts that applying wrong scaled object increase the counter-value of **keda_scaler_errors** , **keda_scaler_error_totals** and  **keda_scaled_object_errors** metrics from 0 to any positive number .. is there anything that I should check also ?
