### ISSUE TITLE
I've been having an issue following the sample for Pub/Sub scaling, https://github.com/kedacore/sample-go-gcppubsub, basically once I setup everything and try testing it the scaler goes to one pod but does not go beyond no matter how many messages are sent to the Topic and after a few minutes it goes back to 0, checking the logs it gives me the following error :

### ISSUE THREAD

**Issue by led94** [kedacore/keda#4141]
I've been having an issue following the sample for Pub/Sub scaling, https://github.com/kedacore/sample-go-gcppubsub, basically once I setup everything and try testing it the scaler goes to one pod but does not go beyond no matter how many messages are sent to the Topic and after a few minutes it goes back to 0, checking the logs it gives me the following error :

2022-12-09T03:16:02Z    ERROR   gcp_pub_sub_scaler      error getting Active Status     {"type": "ScaledObject", "namespace": "keda-pubsub-test", "name": "pubsub-scaledobject", "error": "rpc error: code = PermissionDenied desc = Permission monitoring.timeSeries.list denied (or the resource may not exist)."}

I gave the service account the monitoring viewer , the pubsub subscriber and the monitoring timeSeries list roles but no luck. 

Cluster version: 1.21.14-gke.4300
Keda version:  2.8.1

The code I am using is basically the same from the example with just a minor change, I am using mode and value instead of subscriptionsize as recommended.  I found this existing issue, https://github.com/kedacore/keda/issues/2208, but was not really helpful. 

Hope someone can help me sort this out.

_Originally posted by @led94 in https://github.com/kedacore/keda/discussions/4113_

**Comment by JorTurFer** [comment]
Hey, 
Sorry. I missed the discussion but I have just answered there. Let's continue in the discussion to not have 2 threads
