### ISSUE TITLE
KEDA operator pods not deploying on AKS cluster

### ISSUE THREAD

**Issue by vijayakrishnar** [kedacore/keda#4147]
### Report

i have enabled KEDA add-on aks cluster and it says it's enabled but no pods deployed to cluster

### Expected Behavior

when we enable keda it supposed to create 2 pods "keda-operator" but i don't see any pods under kube-system namespace and that's causing autoscaler failing.

commands ran:
az aks update \
  --resource-group myResourceGroup \
  --name myAKSCluster \
  --enable-keda 

az aks show -g "myResourceGroup" --name myAKSCluster --query "workloadAutoScalerProfile.keda.enabled"

it shows "True"

kubectl get pods -n kube-system

here i don't see any keda pods like
keda-operator-********-k5rfv                     1/1     Running   0          43m
keda-operator-metrics-apiserver-*******-sj857   1/1     Running   0          43m

### Actual Behavior

not sure what was the reason to this issue happened.

### Steps to Reproduce the Problem

1. install AKS cluster
2. Run above those commands
3.

### Logs from KEDA operator

```
example
```

### KEDA Version

None

### Kubernetes Version

1.23

### Platform

Microsoft Azure

### Scaler Details

Azure Pipelines

**Comment by zroubalik** [comment]
Hi, sorry to hear this. This should be probably reported on AKS side, as KEDA doesn't maintain the add-on, but the AKS team does. 

@tomkerkhove FYI^

**Comment by JorTurFer** [comment]
Hi,
I don't know how KEDA add-on install keda because we don't maintain it, it's MSFT who does it as its product, but is kube-system the namespace where KEDA installed?

**Comment by tomkerkhove** [comment]
This is not a KEDA issue, please report on https://github.com/azure/aks instead.

**Comment by v-shenoy** [comment]
Hi, we are aware of this issue. A fix has been done and it's rolling out currently.

**Comment by vijayakrishnar** [comment]
@v-shenoy can you please post issue link here from AKS to track the status?
