### ISSUE TITLE
Keda with prometheus external metric having nested query returing value of first part

### ISSUE THREAD

**Issue by riteshkr54** [kedacore/keda#4148]
### Report

I'm trying on run keda with prometheus metrics, scaling the pod targeting the container's cpu usage. (`containerResourceMetric` is not available is eks, and targeting with vanilla hpa is giving wrong values since I have multiple containers in the pod)

This is my hpa yaml 
`triggers:
 - type: prometheus
   metadata:
     serverAddress: http://prometheus-server.monitoring.svc.cluster.local:80
     metricName: container
     query: >
        ((sum(rate(container_cpu_usage_seconds_total{namespace="boutique", container=~".*checkoutservice" }[60s])))/ (sum(kube_pod_container_resource_requests{ namespace="boutique",resource="cpu", container=~".*checkoutservice"}) )*100)
     threshold: "30"`

### Expected Behavior

The above query works in promethues and I'm getting the actual average cpu utilization of all containers in prometheus, and expected the same values in hpa.
Here's the prometheus output
![image](https://user-images.githubusercontent.com/31988503/213683998-c942b0a2-432a-473c-a559-09b6aba2ac80.png)

### Actual Behavior

In for scaling, keda is returing and only first part of the query `sum(rate(container_cpu_usage_seconds_total{namespace="boutique", container=~".*checkoutservice"}[60s]))` and using this value to match the threshold. So instead of using the cpu percent utilization, it is using the total cpu used. 
Here is the total container's cpu usage
![image](https://user-images.githubusercontent.com/31988503/213685295-067da5d7-9d1f-4205-a152-dec0a5a854fe.png)

### Steps to Reproduce the Problem

1. Calculate container's cpu usage from prometheus and use that to scale

### Logs from KEDA operator

Logs of keda scaler object
```
  Scale Target Ref:
    Kind:  Deployment
    Name:  checkoutservice
  Triggers:
    Metadata:
      Metric Name:  container
      Query:        ((sum(rate(container_cpu_usage_seconds_total{namespace="boutique", container=~".*checkoutservice" }[60s])))/ (sum(kube_pod_container_resource_requests{ namespace="boutique",resource="cpu", container=~".*checkoutservice"}) )*100)

      Server Address:  http://prometheus-server.monitoring.svc.cluster.local:80
      Threshold:       30
    Type:              prometheus
```

Logs from keda hpa
``` k describe hpa keda-hpa-checkoutservice
Name:                                                keda-hpa-checkoutservice
Namespace:                                           boutique
Labels:                                              app.kubernetes.io/managed-by=keda-operator
                                                     app.kubernetes.io/name=keda-hpa-checkoutservice
                                                     app.kubernetes.io/part-of=checkoutservice
                                                     app.kubernetes.io/version=2.8.0
                                                     scaledobject.keda.sh/name=checkoutservice
Annotations:                                         <none>
CreationTimestamp:                                   Fri, 20 Jan 2023 15:56:16 +0530
Reference:                                           Deployment/checkoutservice
Metrics:                                             ( current / target )
  "s0-prometheus-container" (target average value):  34889m / 30
Min replicas:                                        1
Max replicas:                                        20
Behavior:
  Scale Up:
    Stabilization Window: 0 seconds
    Select Policy: Max
    Policies:
      - Type: Pods     Value: 4    Period: 15 seconds
      - Type: Percent  Value: 100  Period: 15 seconds
  Scale Down:
    Stabilization Window: 60 seconds
    Select Policy: Max
    Policies:
      - Type: Percent  Value: 50  Period: 120 seconds
Deployment pods:       3 current / 4 desired
Conditions:
  Type            Status  Reason              Message
  ----            ------  ------              -------
  AbleToScale     True    SucceededRescale    the HPA controller was able to update the target scale to 4
  ScalingActive   True    ValidMetricFound    the HPA was able to successfully calculate a replica count from external metric s0-prometheus-container(&LabelSelector{MatchLabels:map[string]string{scaledobject.keda.sh/name: checkoutservice,},MatchExpressions:[]LabelSelectorRequirement{},})
  ScalingLimited  False   DesiredWithinRange  the desired count is within the acceptable range
Events:
  Type    Reason             Age                   From                       Message
  ----    ------             ----                  ----                       -------
  Normal  SuccessfulRescale  42m                   horizontal-pod-autoscaler  New size: 3; reason: external metric s0-prometheus-container(&LabelSelector{MatchLabels:map[string]string{scaledobject.keda.sh/name: checkoutservice,},MatchExpressions:[]LabelSelectorRequirement{},}) above target
  Normal  SuccessfulRescale  41m (x2 over 44m)     horizontal-pod-autoscaler  New size: 2; reason: external metric s0-prometheus-container(&LabelSelector{MatchLabels:map[string]string{scaledobject.keda.sh/name: checkoutservice,},MatchExpressions:[]LabelSelectorRequirement{},}) below target
  Normal  SuccessfulRescale  5m27s (x27 over 60m)  horizontal-pod-autoscaler  New size: 3; reason: external metric s0-prometheus-container(&LabelSelector{MatchLabels:map[string]string{scaledobject.keda.sh/name: checkoutservice,},MatchExpressions:[]LabelSelectorRequirement{},}) below target
  Normal  SuccessfulRescale  4s (x25 over 60m)     horizontal-pod-autoscaler  New size: 4; reason: external metric s0-prometheus-container(&LabelSelector{MatchLabels:map[string]string{scaledobject.keda.sh/name: checkoutservice,},MatchExpressions:[]LabelSelectorRequirement{},}) above target```


### KEDA Version

2.8.0

### Kubernetes Version

< 1.23

### Platform

Amazon Web Services

### Scaler Details

_No response_

### Anything else?

_No response_

**Comment by JorTurFer** [comment]
Hi,
The problem is that you aren't using the same metric type,and you can't use the same because it's reserved for container metrics.
With your query and default metricType used by KEDA (average), your scaling won't work as you expect. With average metric type, the HPA Controller will calculate the average per pod of the value returned by your query. If your prometheus query returns 60, and you have 4 replicas, the calculated value is 15 (60/4). 
If you still want to use Prometheus, you should take this into account in the formula. Why do you think that EKS doesn't support container? Are you running an old k8s version?

**Comment by riteshkr54** [comment]
> 

Hi @JorTurFer 
Thanks for replying. I'll check and verify the metric value with hpa algorithm and get back.

I'm using kubernetes version 1.21 to 1.24 on my clusters. 

Kubernetes [docs ](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#container-resource-metrics )mentions targeting container resource is still part of alpha feature which is not supported by [eks](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#version-deprecation)

**Comment by JorTurFer** [comment]
> > 
> 
> Hi @JorTurFer Thanks for replying. I'll check and verify the metric value with hpa algorithm and get back.
> 
> I'm using kubernetes version 1.21 to 1.24 on my clusters.
> 
> Kubernetes [docs ](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#container-resource-metrics)mentions targeting container resource is still part of alpha feature which is not supported by [eks](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#version-deprecation)

f**k, I didn't know about this limitation, thanks for pointing to the docs 🙇 
It's totally a hack, but maybe you can invert the average in the query, I mean, knowing that the HPA Controller will divide the returned value between the amount of instances, maybe you could multiply the result of the query for the amount of instances (in prometheus).

**Comment by sushama-kothawale** [comment]
Hi @JorTurFer 
I am facing similar problem for container memory utilisation - https://github.com/kedacore/keda/discussions/4157
prom query - avg(floor((container_memory_usage_bytes{pod=~"pythonb-.*",container=~"proxy"} / container_spec_memory_limit_bytes != +Inf)  * 100))
It gives memory utilisation in percentage but keda somehow not gives the exact value. 
About inverting the value, can you share how we can invert the result?
It's executing only half part of the query (avg(container_memory_usage_bytes{pod=~"pythonb-.*",container=~"proxy"} ))

Thanks

**Comment by JorTurFer** [comment]
It extacly the same case

**Comment by sushama-kothawale** [comment]
@JorTurFer About inverting the value, can you share how we can invert the result?

**Comment by JorTurFer** [comment]
> or is this a bug?

this isn't a bug, as I said, it's related with how the HPA controller algorithms work. There are some metric types, and the AverageUtilization metric type is reserved for container metrics. KEDA metrics are external metrics (except CPU/Memory Scalers, which basically generates a "regular" cpu/memory metric), so you will have to consider.

> @riteshkr54 how did you solve this problem?because I see even we use datadog query it returns the same output as prom. This means HPA controller is doing some calculations over here.

I have explained it above, as default you will the API returned value/replica count

**Comment by sushama-kothawale** [comment]
@JorTurFer 
The below query from prometheus returns 
```
(avg((container_memory_usage_bytes{pod=~"dtl-dlm-pythonb-.*",container=~"istio-proxy"} / container_spec_memory_limit_bytes != +Inf)  * 100))* avg(kube_deployment_spec_replicas{deployment=~"dtl-dlm-pythonb",namespace=~"staging"}) 
```
49.427083333333336

While HPA returns below output:
```
"s3-prometheus-container_memory_usage_bytes" (target average value):  49428m / 70
```
How to co-relate both the values? And we have only one replica running for the app. Its not coming in percentage so how will scaling work?

**Comment by JorTurFer** [comment]
> How to co-relate both the values? And we have only one replica running for the app. Its not coming in percentage so how will scaling work?

As I explained above, you are using a different metric type, the percentage is only for AverageUtilization, you shouldn't expect to see a percentage using any other scaler than CPU/Memory.

Prometheus scaler isn't a CPU/Memory scaler, if you want to use the first one as the others, you need to work in the query to get the value you want, assuming that the visualization won't be in percentages.
[In this thread](https://stackoverflow.com/questions/63347233/how-to-get-cpu-and-memory-usage-of-pod-in-percentage-using-promethus), you can see an example about how to calculate the pod cpu utilization percentage from prometheus. Remember also that this prometheus value will be divided between the instance count due to the metric Type, so you should ensure that correct this division in your query

**Comment by sushama-kothawale** [comment]
@JorTurFer I got your point. Prometheus query returns the result in (m) unit  and scaler compares it with targetaveragevalue /threshold as 70 (so what is the unit of this value?)
Below is the scaledobject spec:
```
    - metadata:
        metricName: container_memory_usage_bytes
        query: (avg((container_memory_usage_bytes{pod=~"dtl-dlm-pythonb-.*",container=~"istio-proxy"} / container_spec_memory_limit_bytes != +Inf)  * 100))* avg(kube_deployment_spec_replicas{deployment=~"dtl-dlm-pythonb",namespace=~"staging"})
        serverAddress:<serveraddress>
        threshold: '70'
      type: prometheus
```

As per the link shared by you, prom query is correct for container level metrics, which returns container memory utilisation.
what should be the threshold value? I assume query output and threshold value units should be same so that scaling will work.

**Comment by sushama-kothawale** [comment]
@JorTurFer Actually the query that I am using returns the output in percentage. Then why keda HPA shows it in (m) units? Only one replica is running for the application so there is no meaning of dividing the query op by replicas. 
still I have added multiplication factor in the query.
I will really appreciate if you could help me here.

**Comment by JorTurFer** [comment]
Kubernetes doesn't use float numbers, it multiplies float * 1000 to change the scale to `mili` (`m`), if you see `49428m` it's the integer conversion for `49,428`.
About the percentage symbol, you won't see it never using prometheus scaler because it doesn't use AverageUtilization metrycType, as it's supported only for cpu/memory scaler

**Comment by sushama-kothawale** [comment]
@JorTurFer Then what about the threshhold?
If the averageutilisation is in (m) then what we need to add for threshold? As I see threshold is also float type. It only allows integer/float no. Otherwise it will throw below error:
```
"error": "error parsing prometheus metadata: error parsing threshold: strconv.ParseFloat: parsing \"70000m\": invalid syntax"
```
Please refer below HPA output:
```
Metrics:                                                                ( current / target )
  "s0-prometheus-container_memory_usage_bytes" (target average value):  48496m / 70
```
If I have to scale beyond 70% then what value I need to put in threshold 70 or 70000

**Comment by JorTurFer** [comment]
no, you can work with floats, KEDA supports floats.`m` is only a displaying thing, if your threshold is 70, you have to set 70, if it's 70.5 you have to place 70.5, the m it's just a visualization thing, internally it doesn't add the `m` anywhere, it knows the scale and do the operations considering the scale

**Comment by sushama-kothawale** [comment]
thanks a lot @JorTurFer . It worked now. here is the summary:

- in the prometheus query we need to add multiply factor for the replicacount
- threshold you can keep in percentage value if your query also returns result in percentage i.e. 70
- visualisation - is as explained by @JorTurFer . even if you see (m) unit in the utilisation it internally takes the value as it is from the prom query result.
