### ISSUE TITLE
Scaled object panics in deref of nil target ref

### ISSUE THREAD

**Issue by alan-marcinkowski** [kedacore/keda#4160]
### Report

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x167ddc5]

goroutine 160951 [running]:
github.com/kedacore/keda/v2/pkg/scaling/executor.(*scaleExecutor).RequestScale(0xc00002c780, {0x40bf968, 0xc002df8e80}, 0xc001f3ca00, 0x0, 0x0)
        /workspace/pkg/scaling/executor/scale_scaledobjects.go:45 +0x225
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).checkScalers(0xc000dfefc0, {0x40bf968, 0xc002df8e80}, {0x3873b80?, 0xc001f3ca00?}, {0x40accf8, 0xc004783c18})
        /workspace/pkg/scaling/scale_handler.go:361 +0x559
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).startScaleLoop(0xc000dfefc0, {0x40bf968, 0xc002df8e80}, 0xc002b2b540, {0x3873b80, 0xc001f3ca00}, {0x40accf8, 0xc004783c18})
        /workspace/pkg/scaling/scale_handler.go:162 +0x32a
created by github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).HandleScalableObject
        /workspace/pkg/scaling/scale_handler.go:118 +0x71d

### Expected Behavior

The code should check nil here or further up. My guess is the target ref is in flux (a controller may have torn it down).

### Actual Behavior

The nil GVKR is deref'd to a panic. Controller restarts.

### Steps to Reproduce the Problem

I am not able to reliably reproduce the condition. We do see it quite often but we've also got a lot of controllers tinkering with state.

### Logs from KEDA operator

```
2023-01-26T01:25:16Z    INFO    Reconciling ScaledObject        {"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "ScaledObject": {"name":"assure-anilm-combined","namespace":"assure-anil-dev"}, "namespace": "assure-anil-dev", "name": "assure-anilm-combined", "reconcileID": "e71c917c-a2b0-42e5-a98c-c2845e3b8ed6"}
2023-01-26T01:25:17Z    INFO    Reconciling ScaledObject        {"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "ScaledObject": {"name":"dmacapd-qinyux-capd-combined","namespace":"dmacapd-dev"}, "namespace": "dmacapd-dev", "name": "dmacapd-qinyux-capd-combined", "reconcileID": "03287421-90f0-483e-bce7-f77a28c2c72e"}
2023-01-26T01:25:17Z    INFO    Reconciling ScaledObject        {"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "ScaledObject": {"name":"musesmoke-combined","namespace":"muse-dev"}, "namespace": "muse-dev", "name": "musesmoke-combined", "reconcileID": "8fabfffa-b0f1-4139-a34c-9f2bc5e6f304"}
2023-01-26T01:25:17Z    INFO    Reconciling ScaledObject        {"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "ScaledObject": {"name":"dmacapd-dev-willb-capd-combined","namespace":"dmacapd-dev"}, "namespace": "dmacapd-dev", "name": "dmacapd-dev-willb-capd-combined", "reconcileID": "965c041b-c2cc-46d7-93b1-d7bf3520469d"}
2023-01-26T01:25:17Z    INFO    Reconciling ScaledObject        {"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "ScaledObject": {"name":"dma-qinyux-capd-combined","namespace":"dma-dev"}, "namespace": "dma-dev", "name": "dma-qinyux-capd-combined", "reconcileID": "4f6f9d91-53c6-4c0c-864f-07c4b3b5435e"}
2023-01-26T01:25:21Z    INFO    Reconciling ScaledObject        {"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "ScaledObject": {"name":"enrcdi-dev-clu-clu360-combined","namespace":"enrcdi-dev"}, "namespace": "enrcdi-dev", "name": "enrcdi-dev-clu-clu360-combined", "reconcileID": "0d9bb0c2-42a6-4afe-89e4-d843e507c31b"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x167ddc5]

goroutine 160951 [running]:
github.com/kedacore/keda/v2/pkg/scaling/executor.(*scaleExecutor).RequestScale(0xc00002c780, {0x40bf968, 0xc002df8e80}, 0xc001f3ca00, 0x0, 0x0)
        /workspace/pkg/scaling/executor/scale_scaledobjects.go:45 +0x225
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).checkScalers(0xc000dfefc0, {0x40bf968, 0xc002df8e80}, {0x3873b80?, 0xc001f3ca00?}, {0x40accf8, 0xc004783c18})
        /workspace/pkg/scaling/scale_handler.go:361 +0x559
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).startScaleLoop(0xc000dfefc0, {0x40bf968, 0xc002df8e80}, 0xc002b2b540, {0x3873b80, 0xc001f3ca00}, {0x40accf8, 0xc004783c18})
        /workspace/pkg/scaling/scale_handler.go:162 +0x32a
created by github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).HandleScalableObject
        /workspace/pkg/scaling/scale_handler.go:118 +0x71d

```

### KEDA Version

2.9.2

### Kubernetes Version

1.24

### Platform

Microsoft Azure

### Scaler Details

Prometheus

### Anything else?

Thanks!

**Comment by JorTurFer** [comment]
Hi,
Could you share your ScaledObject please?

**Comment by alan-marcinkowski** [comment]
Well, if it's the last one logged, which I'm not convinced it was, it would be:
```
kubectl get so -n enrcdi-dev -o yaml enrcdi-dev-clu-clu360-combined
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  annotations:
    clu.nuance.com/institution-id: "160"
    clu.nuance.com/institution-name: EnrcdiClu
    clu.nuance.com/product: ENRCDI
    clu.nuance.com/version: 3.11.5
  creationTimestamp: "2022-11-14T19:39:34Z"
  finalizers:
  - finalizer.keda.sh
  generation: 2428
  labels:
    app.kubernetes.io/component: clu360-combined
    app.kubernetes.io/instance: enrcdi-dev-clu-clu360-combined
    app.kubernetes.io/managed-by: tomcat-controller
    app.kubernetes.io/part-of: enrcdi-dev-clu
    clu-clu360.version: 3.11.5
    clu-common.version: 2.49.0-SNAPSHOT
    clu-deploy-database-cassql.version: 4.16.2
    clu.nuance.com/component-role: tomcat
    clu.nuance.com/ingress-cutover: active
    landc-dependencies.version: 5.13.1
    scaledobject.keda.sh/name: enrcdi-dev-clu-clu360-combined
  name: enrcdi-dev-clu-clu360-combined
  namespace: enrcdi-dev
  ownerReferences:
  - apiVersion: clu.nuance.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Institution
    name: enrcdi-dev-clu
    uid: 4b784804-23cb-4445-8cbf-8639080d3beb
  resourceVersion: "340905230"
  uid: 658fbebd-0cd1-4be2-9566-e66294ab377b
spec:
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          policies:
          - periodSeconds: 300
            type: Pods
            value: 2
          selectPolicy: Max
          stabilizationWindowSeconds: 900
        scaleUp:
          policies:
          - periodSeconds: 60
            type: Pods
            value: 2
          selectPolicy: Max
          stabilizationWindowSeconds: 60
  cooldownPeriod: 300
  maxReplicaCount: 15
  minReplicaCount: 2
  pollingInterval: 30
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: enrcdi-dev-clu-clu360-combined
  triggers:
  - metadata:
      metricName: outbound_queue_size_activemq_enrcdi-dev
      query: org_apache_activemq_Broker_QueueSize{app_kubernetes_io_component="activemq",namespace="enrcdi-dev",
        destinationType="Queue", destinationName=~"engineOutbound"}
      serverAddress: http://clu-monitoring-prometheus.clu-monitoring.svc.cluster.local:9090
      threshold: "500"
    metricType: Value
    type: prometheus
  - metadata:
      metricName: memory_pool_used_clu360-combined_enrcdi-dev-clu_enrcdi-dev
      query: avg(jvm_memory_bytes_used{app_kubernetes_io_part_of="enrcdi-dev-clu",app_kubernetes_io_component="clu360-combined",namespace="enrcdi-dev",
        area="heap"}) * 100 / avg(jvm_memory_bytes_max{app_kubernetes_io_part_of="enrcdi-dev-clu",app_kubernetes_io_component="clu360-combined",namespace="enrcdi-dev",
        area="heap"})
      serverAddress: http://clu-monitoring-prometheus.clu-monitoring.svc.cluster.local:9090
      threshold: "75"
    metricType: Value
    type: prometheus
  - metadata:
      metricName: busy_thread_percent_clu360-combined_enrcdi-dev-clu_enrcdi-dev
      query: "avg(\n  avg_over_time(catalina_threadpool_currentthreadsbusy{namespace=\"enrcdi-dev\",app_kubernetes_io_part_of=\"enrcdi-dev-clu\",app_kubernetes_io_component=\"clu360-combined\"}[5m:])
        * 100 \n  / \n  avg_over_time(catalina_threadpool_maxthreads{namespace=\"enrcdi-dev\",app_kubernetes_io_part_of=\"enrcdi-dev-clu\",app_kubernetes_io_component=\"clu360-combined\"}[5m:])\n)\n"
      serverAddress: http://clu-monitoring-prometheus.clu-monitoring.svc.cluster.local:9090
      threshold: "80"
    metricType: Value
    type: prometheus
status:
  conditions:
  - message: ScaledObject is defined correctly and is ready for scaling
    reason: ScaledObjectReady
    status: "True"
    type: Ready
  - message: Scaling is performed because triggers are active
    reason: ScalerActive
    status: "True"
    type: Active
  - message: No fallbacks are active on this scaled object
    reason: NoFallbackFound
    status: "False"
    type: Fallback
  externalMetricNames:
  - s0-prometheus-outbound_queue_size_activemq_enrcdi-dev
  - s1-prometheus-memory_pool_used_clu360-combined_enrcdi-dev-clu_enrcdi-dev
  - s2-prometheus-busy_thread_percent_clu360-combined_enrcdi-dev-clu_enrcdi-dev
  health:
    s0-prometheus-outbound_queue_size_activemq_enrcdi-dev:
      numberOfFailures: 0
      status: Happy
    s1-prometheus-memory_pool_used_clu360-combined_enrcdi-dev-clu_enrcdi-dev:
      numberOfFailures: 0
      status: Happy
    s2-prometheus-busy_thread_percent_clu360-combined_enrcdi-dev-clu_enrcdi-dev:
      numberOfFailures: 0
      status: Happy
  lastActiveTime: "2023-01-26T14:28:29Z"
  originalReplicaCount: 2
  scaleTargetGVKR:
    group: apps
    kind: Deployment
    resource: deployments
    version: v1
  scaleTargetKind: apps/v1.Deployment
```

**Comment by zroubalik** [comment]
I think it is this line, not the GVKR:
https://github.com/kedacore/keda/blob/v2.9.2/pkg/scaling/executor/scale_scaledobjects.go#L45

For some reason the `scaledObject` is `scaledObject.Spec.ScaleTargetRef.Name` is nil there. 

@alan-marcinkowski what do you mean by following line? What do you mean by a lot of controllers?

> We do see it quite often but we've also got a lot of controllers tinkering with state.

**Comment by alan-marcinkowski** [comment]
Yup. Line 45 is the place.

**Comment by alan-marcinkowski** [comment]
Looking through our controller code, I do not see a case where we would not write out that target ref in the SO spec.

**Comment by zroubalik** [comment]
Yeah, I suspect that the ref ScaledObject is nil, would be great if we can investigate that.

**Comment by JorTurFer** [comment]
> I think it is this line, not the GVKR:

It's impossible because we access to the same property a few lines above without any crash for logger labels
https://github.com/kedacore/keda/blob/9bc3f66578a08cdfe084468ea3ef998fa6bf3bb0/pkg/scaling/executor/scale_scaledobjects.go#L37-L45

**Comment by alan-marcinkowski** [comment]
That is the panic stack verbatim. I agree ... something looks out of shape ... but just what ... I'm not sure. Is there possibly another go routine tinkering with the same bits?

**Comment by JorTurFer** [comment]
Shouldn't be other routing doing the same... Are you changing something in the ScaledObject status? I mean, if I'm not wrong, we validate all the user given data, but we don't validate all data from the status, if your controllers changes the status, setting an inconsistent value, it could generate a panic in line 46 because `scaledObject.Status.ScaleTargetGVKR` is directly recovered from the k8s API

**Comment by alan-marcinkowski** [comment]
Nope. We only work on the spec itself in the SO. I don't see any case in the course of updating the SO spec that we would change or remove the target at all. The most we would do is update the scalers ... or delete the SO altogether.

**Comment by JorTurFer** [comment]
I'm going to try what happens when that section is removed from the ScaledObject manifest, just in case

**Comment by alan-marcinkowski** [comment]
It's definitely tagged as required in the coop builder crd generator

**Comment by alan-marcinkowski** [comment]
We have not noticed this particular panic in any of the previous versions and are SO handling code has not changed in some time.

**Comment by alan-marcinkowski** [comment]
Also wanted to ensure you that this is indeed 2.9.2:

     image: ghcr.io/kedacore/keda:2.9.2

**Comment by JorTurFer** [comment]
I have tried every thing I thought to produce a panic and I can't. The only way I have been able to panic has been removing the validation in the CRD and registering a `nil` value for `scaleTargetRef` (not for scaleTargetRef.name, removing name doesn't panic) and the panic has been in other part of the code.
Could you give us any extra info we can use to figure out what's happening?

**Comment by alan-marcinkowski** [comment]
Next time I see it I'll try and track down the last mod made to it. We don't tend to change the SO very much after creation (almost never). Is there a chance that this could happen because we moved from 2.9.1 to 2.9.2?

**Comment by JorTurFer** [comment]
> Next time I see it I'll try and track down the last mod made to it. We don't tend to change the SO very much after creation (almost never). Is there a chance that this could happen because we moved from 2.9.1 to 2.9.2?

Each time when KEDA operator is restarted, it processes all the ScaledObjects and generates its internal cache, so if there was any error, the restart can impact. How often does this panic happen? Does it only happen with 2.9.2 or with any v2.9?

**Comment by JorTurFer** [comment]
I'm reviewing [changes between 2.9.1 and 2.9.2](https://github.com/kedacore/keda/compare/v2.9.1...v2.9.2) and I can't see anything related

**Comment by alan-marcinkowski** [comment]
We didn't notice it with prior versions. We did notice it quite a bit after the upgrade. We're not seeing it as much after a few restarts on the deployments. We were also seeing the metrics api server having some issues at one point too. Thanks!

**Comment by JorTurFer** [comment]
> We were also seeing the metrics api server having some issues at one point too

This is surely because the operator was down. v2.9 introduced big changes in the architecture and now the operator is the point of truth, metrics server requests the metrics to the operator instead of requesting the metrics directly to the upstream. We introduced this change to reduce the places where high permissions are in use

**Comment by zroubalik** [comment]
@alan-marcinkowski do you think you can try to rebuild operator image and insert a few log messages before the failing call, to see what is the problem? (what is nil)

Here is guide: https://github.com/kedacore/keda/blob/main/BUILD.md#custom-keda-as-an-image

**Comment by alan-marcinkowski** [comment]
Hello @zroubalik  ... not sure I'll get the chance to try that out sadly. We're a bit strapped at the moment. To @JorTurFer 's point though, I'm not sure how the logger setup gets past the deref before the panic location. Also, I haven't seen the panic for about 24 hours now.

**Comment by alan-marcinkowski** [comment]
Did see this again on one of our clusters. Only happened once. I didn't catch it live and I don't see anything additional to add sadly.

**Comment by zroubalik** [comment]
@alan-marcinkowski could you please ping me on slack?

Do you think you can try to use `quay.io/zroubalik/keda:nillog` image for KEDA Operator on one of your clusters? Just replace the reference in the `keda` Deployment.

The only thing I did is that I've added a bunch of log messages starting with `WARNING!` before the panic usually happens:

```go
func (e *scaleExecutor) RequestScale(ctx context.Context, scaledObject *kedav1alpha1.ScaledObject, isActive bool, isError bool, name, namespace string) {
	logger := e.logger.WithValues("scaledobject.Name", scaledObject.Name,
		"scaledObject.Namespace", scaledObject.Namespace,
		"scaleTarget.Name", scaledObject.Spec.ScaleTargetRef.Name)

	if scaledObject == nil {
		logger.Info("WARNING! got nil scaledObject", "name", name, "namespace", namespace)
	}
	if scaledObject.Spec.ScaleTargetRef == nil {
		logger.Info("WARNING! got nil scaledObject.Spec.ScaleTargetRef", "name", name, "namespace", namespace)
	}
	if scaledObject.Status.ScaleTargetGVKR == nil {
		logger.Info("WARNING! got nil scaledObject.Status.ScaleTargetGVKR", "name", name, "namespace", namespace)
	}

	// Get the current replica count. As a special case, Deployments and StatefulSets fetch directly from the object so they can use the informer cache
	// to reduce API calls. Everything else uses the scale subresource.
	var currentScale *autoscalingv1.Scale
	var currentReplicas int32
	targetName := scaledObject.Spec.ScaleTargetRef.Name
	targetGVKR := scaledObject.Status.ScaleTargetGVKR
```

**Comment by alan-marcinkowski** [comment]
Running now. I would think you might want those same checked before the logger setup as crazy as that sounds based on the nil panic ... line 45 derefed something the logger already derefed.

**Comment by alan-marcinkowski** [comment]
It has run for over 24 hours without issue. I'll leave it running as long as I can.

**Comment by JorTurFer** [comment]
Any update on this?

**Comment by alan-marcinkowski** [comment]
Just sort of moving on. We see another panic at this point but I didn't bother to report it as we can't reliably reproduce it either.

goroutine 2169 [running]:
runtime.throw({0x395dd78?, 0xc0020e7de8?})
        /usr/local/go/src/runtime/panic.go:992 +0x71 fp=0xc0020e7d90 sp=0xc0020e7d60 pc=0x4384f1
runtime.mapassign_faststr(0x0?, 0x30f04e0?, {0xc003041ed3, 0x9})
        /usr/local/go/src/runtime/map_faststr.go:212 +0x39c fp=0xc0020e7df8 sp=0xc0020e7d90 pc=0x4133dc
reflect.mapassign_faststr(0x32a97a0, 0xc00261f680?, {0xc003041ed3?, 0x396be6d?}, 0x19?)
        /usr/local/go/src/runtime/map.go:1357 +0x28 fp=0xc0020e7e30 sp=0xc0020e7df8 pc=0x4627a8
reflect.Value.SetMapIndex({0x32a97a0?, 0xc002949b28?, 0x1397?}, {0x30f04e0, 0xc00261f6c0, 0x98}, {0x30f04e0, 0xc00261f680, 0x198})
        /usr/local/go/src/reflect/value.go:2232 +0x225 fp=0xc0020e7eb8 sp=0xc0020e7e30 pc=0x49c6c5
sigs.k8s.io/json/internal/golang/encoding/json.(*decodeState).object(0xc001b49110, {0x32a97a0?, 0xc002949b28?, 0x3673940?})
        /workspace/vendor/sigs.k8s.io/json/internal/golang/encoding/json/decode.go:908 +0x1997 fp=0xc0020e81e8 sp=0xc0020e7eb8 pc=0x602037
sigs.k8s.io/json/internal/golang/encoding/json.(*decodeState).value(0xc001b49110, {0x32a97a0?, 0xc002949b28?, 0x8?})
        /workspace/vendor/sigs.k8s.io/json/internal/golang/encoding/json/decode.go:400 +0x45 fp=0xc0020e8258 sp=0xc0020e81e8 pc=0x5ff4e5
sigs.k8s.io/json/internal/golang/encoding/json.(*decodeState).object(0xc001b49110, {0x3673940?, 0xc002949b00?, 0xb?})
        /workspace/vendor/sigs.k8s.io/json/internal/golang/encoding/json/decode.go:866 +0x1267 fp=0xc0020e8588 sp=0xc0020e8258 pc=0x601907
sigs.k8s.io/json/internal/golang/encoding/json.(*decodeState).value(0xc001b49110, {0x3673940?, 0xc002949b00?, 0x1?})
        /workspace/vendor/sigs.k8s.io/json/internal/golang/encoding/json/decode.go:400 +0x45 fp=0xc0020e85f8 sp=0xc0020e8588 pc=0x5ff4e5
sigs.k8s.io/json/internal/golang/encoding/json.(*decodeState).array(0xc001b49110, {0x303bf80?, 0xc0017ee140?, 0x158e?})
        /workspace/vendor/sigs.k8s.io/json/internal/golang/encoding/json/decode.go:595 +0x6e5 fp=0xc0020e86f8 sp=0xc0020e85f8 pc=0x600305
sigs.k8s.io/json/internal/golang/encoding/json.(*decodeState).value(0xc001b49110, {0x303bf80?, 0xc0017ee140?, 0x8?})
        /workspace/vendor/sigs.k8s.io/json/internal/golang/encoding/json/decode.go:390 +0x7e fp=0xc0020e8768 sp=0xc0020e86f8 pc=0x5ff51e
sigs.k8s.io/json/internal/golang/encoding/json.(*decodeState).object(0xc001b49110, {0x3723a20?, 0xc0017ee108?, 0x24d8?})
        /workspace/vendor/sigs.k8s.io/json/internal/golang/encoding/json/decode.go:866 +0x1267 fp=0xc0020e8a98 sp=0xc0020e8768 pc=0x601907
sigs.k8s.io/json/internal/golang/encoding/json.(*decodeState).value(0xc001b49110, {0x3723a20?, 0xc0017ee108?, 0x4?})
        /workspace/vendor/sigs.k8s.io/json/internal/golang/encoding/json/decode.go:400 +0x45 fp=0xc0020e8b08 sp=0xc0020e8a98 pc=0x5ff4e5
sigs.k8s.io/json/internal/golang/encoding/json.(*decodeState).object(0xc001b49110, {0x3873b80?, 0xc0017ee000?, 0x0?})
        /workspace/vendor/sigs.k8s.io/json/internal/golang/encoding/json/decode.go:866 +0x1267 fp=0xc0020e8e38 sp=0xc0020e8b08 pc=0x601907
sigs.k8s.io/json/internal/golang/encoding/json.(*decodeState).value(0xc001b49110, {0x3873b80?, 0xc0017ee000?, 0xd0?})
        /workspace/vendor/sigs.k8s.io/json/internal/golang/encoding/json/decode.go:400 +0x45 fp=0xc0020e8ea8 sp=0xc0020e8e38 pc=0x5ff4e5
sigs.k8s.io/json/internal/golang/encoding/json.(*decodeState).unmarshal(0xc001b49110, {0x3873b80?, 0xc0017ee000?})
        /workspace/vendor/sigs.k8s.io/json/internal/golang/encoding/json/decode.go:187 +0x1de fp=0xc0020e8f20 sp=0xc0020e8ea8 pc=0x5fee5e
sigs.k8s.io/json/internal/golang/encoding/json.Unmarshal({0xc001d27400, 0x1b48, 0x2500}, {0x3873b80, 0xc0017ee000}, {0xc0020e9010, 0x2, 0x7?})
        /workspace/vendor/sigs.k8s.io/json/internal/golang/encoding/json/decode.go:112 +0x159 fp=0xc0020e8f60 sp=0xc0020e8f20 pc=0x5febf9
sigs.k8s.io/json.UnmarshalCaseSensitivePreserveInts(...)
        /workspace/vendor/sigs.k8s.io/json/json.go:62
