### ISSUE TITLE
Add support to add user given CAs to trusted store

### ISSUE THREAD

**Issue by JorTurFer** [kedacore/keda#4168]
### Proposal

There are some cases where a user could want to use TLS with custom CAs in their own services, and KEDA should support an option to add those CAs to trusted store.
As the container is distroless, I'd add it using golang directly

### Is this a feature you are interested in implementing yourself?

Yes

**Comment by JorTurFer** [comment]
I have been thinking about this, and I'm not sure which is the best approach 🤔 
I could read all the CAs for a given folder and stores them globally, but I'm not sure if this could be better as part of TriggerAuthentication (adding a new field), applying them only in SO/SJ where they are attached.  I can see scenarios for both cases. From a security pov, I guess that trusting a CA is an administrator action more than a developer action (because it can be risky), but I'm not sure what is better (maybe both in different PRs).
WDYT @kedacore/keda-core-contributors ?

**Comment by QualoZe0t** [comment]
@JorTurFer Please keep in mind that as a User I can configure the AWS MSK cluster using TLS without ACM private certificate . So there should be option for using tls without specifying custom certificate

**Comment by JorTurFer** [comment]
Hi @QualoZe0t ,
What do you mean? AWS CAs are not trusted, so there are 2 options:
- Registering their CAs in the trusted store (covered by this issue)
- Adding an option to `unsafeSsl` to the kafka scaler (not covered by this issue)

**Comment by QualoZe0t** [comment]
@JorTurFer so once ,,default,, AWS CA certificates will be registered in the trusted store then doesn't matter if  I wll use or not use ACM option will be able to establish connectivity between KEDA and MSK kafka ?

**Comment by JorTurFer** [comment]
I can't guarantee that this is the only problem, but definitively the certificate should be valid or ignorable, otherwise sarama client will raise an error
