### ISSUE TITLE
ScaledObject Status fields are not updated

### ISSUE THREAD

**Issue by zroubalik** [kedacore/keda#417]
ScaledObject Status has `DesiredReplicas` and `CurrentReplicas` fields which are not updated, they are currently set to `0`.

We should fix this or remove this fields from the Status as they are present in HPA.

**Comment by jeffhollan** [comment]
@Aarthisk would be get to get your inputs on this

**Comment by zroubalik** [comment]
@jeffhollan @ahmelsayed @Aarthisk  I forgot to mention this on standup. I think it'd be great to fix this for v1.0, because these fields are showing misleading information for user atm.
At least we could remove those fields from `ScaledObject` and we can reintroduce them later if needed. It is a very simple change and I can send a PR in a few.

**Comment by Aarthisk** [comment]
@zroubalik Yes, I agree. I don't remember if these ever worked or the refactoring changed them. Sure, if you can get to it that will be great. 
@ahmelsayed I believe you might have had these for 0-1 scaling. is it still relevant with the operator sdk?

**Comment by zroubalik** [comment]
@Aarthisk I think it didn't worked even before the refactoring.

**Comment by tomkerkhove** [comment]
Well wouldn't it be nice if they were working rather than deleting them? 🤔

You could say, check the HPA but I think the added value of KEDA is that it obfuscates this from the users.

**Comment by zroubalik** [comment]
@tomkerkhove agree, I just want to remove those fields until we decide what do we want to show in the status, to avoid confusion.

If we want to have those fields in ScaledObject, we will have to periodically read those values from HPA. Question is, whether we want to add this sync from perfomance POV.

**Comment by tomkerkhove** [comment]
> @tomkerkhove agree, I just want to remove those fields until we decide what do we want to show in the status, to avoid confusion.

Sounds good to me.
