### ISSUE TITLE
Release: akin

### ISSUE THREAD

**Issue by AKIN2022** [kedacore/keda#4194]
This issue template is used to track the rollout of a new KEDA version.

For the full release process, we recommend reading [this document](https://github.com/kedacore/keda/blob/main/RELEASE-PROCESS.md).

## Progress

- [ ] Prepare changelog
- [ ] Add the new version to GitHub Bug report template
- [ ] Create KEDA release
- [ ] Publish new documentation version
- [ ] Setup continous container scanning with Snyk
- [ ] Prepare & ship Helm chart
- [ ] Prepare next release
- [ ] Provide update in Slack
- [ ] Tweet about new release

**Comment by JorTurFer** [comment]
I close this issue as we don't plan any release atm
