### ISSUE TITLE
Elasticsearch trigger documentation mistake

### ISSUE THREAD

**Issue by itaybar** [kedacore/keda#4218]
In the elasticsearch trigger documentation there is field called “params” which is actually “parameters”, figured that after diving into the scaler code

**Comment by JorTurFer** [comment]
Hey @itaybar 
Thanks for reporting it!
Are you willing to fix it in docs repo? https://github.com/kedacore/keda-docs
You'd only need to fork the repo an open a PR with the changes in the affected versions

**Comment by itaybar** [comment]
Yeah why not

**Comment by itaybar** [comment]
pr: https://github.com/kedacore/keda-docs/pull/1068

**Comment by tomkerkhove** [comment]
Merged, thank you for the fix!
