### ISSUE TITLE
Document how to contribute a new scaler

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda#422]
Document how to contribute a new scaler so that folks can jump in and help.

This comes from https://github.com/kedacore/keda/wiki/FAQ while migrating to our doc page

**Comment by tomkerkhove** [comment]
@jeffhollan you're mention that you want to work on this, right?

**Comment by jeffhollan** [comment]
I’m happy to but haven’t started yet. Was just what we chatted about yesterday. So saying they need to include unit tests and doc references and update README and include an example. I won’t get to this until next week so if you get the chance before then go for it and we can collaborate on the PR. Let me know

**Comment by tomkerkhove** [comment]
Not perse but *might* see if I have some more time later next week, need to finalize the docs first!

**Comment by eashi** [comment]
I have started with some content before: PR #395 . I guess the PR has the wrong title now; it started with how to run locally but I added a commit that is related to the documentation by mistake, should have been another PR. 

What do you think? I can abandon PR #395 and create another one that fits your vision for the documentation, I am hoping that we don't fit everything in the FAQ.

**Comment by jeffhollan** [comment]
This is awesome.  Almost close-worthy per @eashi great contribution of #443 .  I'll also include some contributor guidance around including docs and such when adding scaler and how to do that.

**Comment by jeffhollan** [comment]
Working on a `CONTRIBUTING.md` file right now that will cover this
