### ISSUE TITLE
`metricName` should be deprecated for Cassandra Scaler

### ISSUE THREAD

**Issue by JorTurFer** [kedacore/keda#4227]
### Proposal

Currently, Cassandra scaler requires a `metricName` which is used only for KEDA internal things (it's not sent to the prom server). 
This requirement isn't necessary since we introduced mechanisms to ensure the unique metrics names inside the ScaledObject and we should make it optional and also deprecate it in favor of self-generated internal name

https://github.com/kedacore/keda/blob/main/pkg/scalers/cassandra_scaler.go#L151-L155

**Comment by yardenshoham** [comment]
I'd like to give it a shot. It'll be my first time to KEDA. I've read `CONTRIBUTING.md`. Could you list some high-level `TODO` list here? What I did so far is adding logging to Cassandra's scaler metadata parsing to print a deprecation message, but I'm not sure I'm on the right track.

```diff
--- a/pkg/scalers/cassandra_scaler.go
+++ b/pkg/scalers/cassandra_scaler.go
@@ -48,7 +48,7 @@ func NewCassandraScaler(config *ScalerConfig) (Scaler, error) {

        logger := InitializeLogger(config, "cassandra_scaler")

-       meta, err := parseCassandraMetadata(config)
+       meta, err := parseCassandraMetadata(config, logger)
        if err != nil {
                return nil, fmt.Errorf("error parsing cassandra metadata: %w", err)
        }
@@ -67,7 +67,7 @@ func NewCassandraScaler(config *ScalerConfig) (Scaler, error) {
 }

 // parseCassandraMetadata parses the metadata and returns a CassandraMetadata or an error if the ScalerConfig is invalid.
-func parseCassandraMetadata(config *ScalerConfig) (*CassandraMetadata, error) {
+func parseCassandraMetadata(config *ScalerConfig, logger logr.Logger) (*CassandraMetadata, error) {
        meta := CassandraMetadata{}

        if val, ok := config.TriggerMetadata["query"]; ok {
@@ -150,6 +150,7 @@ func parseCassandraMetadata(config *ScalerConfig) (*CassandraMetadata, error) {

        if val, ok := config.TriggerMetadata["metricName"]; ok {
                meta.metricName = kedautil.NormalizeString(fmt.Sprintf("cassandra-%s", val))
+               logger.Info("metricName is deprecated and shouldn't be explicitly set in scaler trigger metadata")
        } else {
                meta.metricName = kedautil.NormalizeString(fmt.Sprintf("cassandra-%s", meta.keyspace))
        }
```

**Comment by JorTurFer** [comment]
Yeah, that draft looks nice. The idea is to announce to end-users that the feature will be removed in v2.12 so maybe I'd include that info in the log, but that's all
😊😊

**Comment by yardenshoham** [comment]
Do I need to make any changes to `CHANGELOG.md` or the KEDA docs?

**Comment by JorTurFer** [comment]
I think that we can refer the main issue directly in the changelog to reduce the noise:
https://github.com/kedacore/keda/issues/4220

But yes, the first one who fixes one of the sub issues should update the changelog xD
