### ISSUE TITLE
`metricName` should be deprecated for Couchdb Scaler

### ISSUE THREAD

**Issue by JorTurFer** [kedacore/keda#4228]
### Proposal

Currently, Couchdb scaler requires a `metricName` which is used only for KEDA internal things (it's not sent to the prom server). 
This requirement isn't necessary since we introduced mechanisms to ensure the unique metrics names inside the ScaledObject and we should make it optional and also deprecate it in favor of self-generated internal name

https://github.com/kedacore/keda/blob/main/pkg/scalers/couchdb_scaler.go#L179-L181

**Comment by zroubalik** [comment]
will be handled by https://github.com/kedacore/keda/issues/4220
