### ISSUE TITLE
`metricName` shouldn't be required and should be deprecated for Prometheus Scaler

### ISSUE THREAD

**Issue by JorTurFer** [kedacore/keda#4230]
### Proposal

Currently, Prometheus Scaler requires a `metricName` which is used only for KEDA internal things (it's not sent to the prom server). 
This requirement isn't necessary since we introduced mechanisms to ensure the unique metrics names inside the ScaledObject and we should make it optional and also deprecate it in favor of self-generated internal name

https://github.com/kedacore/keda/blob/main/pkg/scalers/prometheus_scaler.go#L128-L132

**Comment by OsamaNabih** [comment]
Hey there,
I'm new here and think this might be a good issue to start with.
Could you elaborate more on the self-generation of the internal name? Is there code that does already, or will it be implemented in the PR? Does it follow a specific format?

**Comment by JorTurFer** [comment]
Hi,
I'm not totally sure, but I think that there is another PR in progress that includes this

**Comment by OsamaNabih** [comment]
I see.

**Comment by zroubalik** [comment]
will be handled by https://github.com/kedacore/keda/issues/4220
