### ISSUE TITLE
Adding Solr Scaler for KEDA

### ISSUE THREAD

**Issue by ithesadson** [kedacore/keda#4234]
### Proposal

I'd like to contribute to KEDA by adding a scaler for Solr.

### Scaler Source

Solr

### Scaling Mechanics

Scale based on query from Solr

### Authentication Source

Authentication in the form of username and password

### Anything else?

I'd like to create a Solr scaler. I would like to mention what i did before i started creating this scaler:
1. I submitted ad pr fixin a bug in another scaler and it was accepted. (cassandra_scaler)
2. I created a weather scaler to understand how a scaler is created and works.

I am thinking of using this library when creating the scaler: ( https://pkg.go.dev/github.com/vanng822/go-solr/solr)
Is there any problem if i use this library. (last updated 2020)

**Comment by tomkerkhove** [comment]
The last update of the package is a concern though; are there no other Go packages dor this?

**Comment by zroubalik** [comment]
> The last update of the package is a concern though; are there no other Go packages dor this?

I share this concern. Or is there any other way how to communicate with Solr? Some Rest API?

**Comment by ithesadson** [comment]
> > The last update of the package is a concern though; are there no other Go packages dor this?
> 
> I share this concern. Or is there any other way how to communicate with Solr? Some Rest API?

I checked again and I can do it with Rest API. Can you assign me to this?

**Comment by tomkerkhove** [comment]
Certainly - Good alternative!
