### ISSUE TITLE
Keda operator pod getting restarted 

### ISSUE THREAD

**Issue by samjain04** [kedacore/keda#4270]
### Report

KEDA operator pod is getting restarted and we are seeing below error in keda operator pod logs

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x585a40]

goroutine 452 [running]:
github.com/go-logr/logr.Logger.Error({{0x0, 0x0}, 0x0}, {0x3c58f00, 0xc001896a40}, {0x35c9274, 0x14}, {0x0, 0x0, 0x0})
        /go/pkg/mod/github.com/go-logr/logr@v1.2.3/logr.go:279 +0x80
github.com/kedacore/keda/v2/pkg/scalers.(*newrelicScaler).IsActive(0xc000b5fe00, {0x3cae988, 0xc0004f2e80})
        /workspace/pkg/scalers/newrelic_scaler.go:147 +0x7b
github.com/kedacore/keda/v2/pkg/scaling/cache.(*ScalersCache).IsScaledObjectActive(0xc0008a3db0, {0x3cae988, 0xc0004f2e80}, 0xc0015d2600)
        /workspace/pkg/scaling/cache/scalers_cache.go:89 +0xef
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).checkScalers(0xc0006fa0e0, {0x3cae988, 0xc0004f2e80}, {0x34e3ec0, 0xc0015d2600}, {0x3c8b6e8, 0xc000b896e8})
        /workspace/pkg/scaling/scale_handler.go:278 +0x4b2
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).startScaleLoop(0xc0006fa0e0, {0x3cae988, 0xc0004f2e80}, 0xc001a48640, {0x34e3ec0, 0xc0015d2600}, {0x3c8b6e8, 0xc000b896e8})
        /workspace/pkg/scaling/scale_handler.go:149 +0x31c
created by github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).HandleScalableObject
        /workspace/pkg/scaling/scale_handler.go:105 +0x6ef

### Expected Behavior

The Error logged to the console

### Actual Behavior

Keda Crashes with segmentation fault.

### Steps to Reproduce the Problem

1.
2.
3.

### Logs from KEDA operator

```
example
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x585a40]

goroutine 452 [running]:
github.com/go-logr/logr.Logger.Error({{0x0, 0x0}, 0x0}, {0x3c58f00, 0xc001896a40}, {0x35c9274, 0x14}, {0x0, 0x0, 0x0})
        /go/pkg/mod/github.com/go-logr/logr@v1.2.3/logr.go:279 +0x80
github.com/kedacore/keda/v2/pkg/scalers.(*newrelicScaler).IsActive(0xc000b5fe00, {0x3cae988, 0xc0004f2e80})
        /workspace/pkg/scalers/newrelic_scaler.go:147 +0x7b
github.com/kedacore/keda/v2/pkg/scaling/cache.(*ScalersCache).IsScaledObjectActive(0xc0008a3db0, {0x3cae988, 0xc0004f2e80}, 0xc0015d2600)
        /workspace/pkg/scaling/cache/scalers_cache.go:89 +0xef
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).checkScalers(0xc0006fa0e0, {0x3cae988, 0xc0004f2e80}, {0x34e3ec0, 0xc0015d2600}, {0x3c8b6e8, 0xc000b896e8})
        /workspace/pkg/scaling/scale_handler.go:278 +0x4b2
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).startScaleLoop(0xc0006fa0e0, {0x3cae988, 0xc0004f2e80}, 0xc001a48640, {0x34e3ec0, 0xc0015d2600}, {0x3c8b6e8, 0xc000b896e8})
        /workspace/pkg/scaling/scale_handler.go:149 +0x31c
created by github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).HandleScalableObject
        /workspace/pkg/scaling/scale_handler.go:105 +0x6ef

### KEDA Version

2.8.0

### Kubernetes Version

< 1.23

### Platform

Amazon Web Services

### Scaler Details

New-Relic

**Comment by zroubalik** [comment]
Hi, this has been already fixed, please update to 2.9.3 if you have k8s >= 1.23, if not, use KEDA 2.8.2
