### ISSUE TITLE
Redis stream - use streams XLEN instead of XPENDING 

### ISSUE THREAD

**Issue by jkbmdk** [kedacore/keda#4277]
### Proposal

When it comes to using _redis streams_ as a message queue, as php symfony messenger does, declaring the **XPENDING** parameter as a scaler attribute will not be useful in some scenarios, because it usually returns the current number of subscribers. 
The solution I would propose is to make the **redis stream scaler** optionally dependent on the **XLEN** parameter.

### Use-Case

First of all we are using php symfony messenger and redis. The only way to combine those two is by using redis streams. In our case, we publish many messages once a day and much less throughout the day. Our goal is to quickly subscribe messages from the initial feed (say, within a few hours), and then maintain enough subscribers to handle incoming messages.

### Is this a feature you are interested in implementing yourself?

Maybe

**Comment by JorTurFer** [comment]
Hello,
This makes sense totally. Are you willing to contribute?

**Comment by jkbmdk** [comment]
Sure, should the solution be implemented for redis streams scaler as an additional configuration parameter and when it would be set there would be no need to set __pendingEntriesCount__ or __consumerGroup__?

**Comment by JorTurFer** [comment]
I think so, you can make them optional and raise an error in case of they are required and they are missing (and properly document it xD)
