### ISSUE TITLE
Wrong scale number calculation for selenium grid

### ISSUE THREAD

**Issue by Wampirs** [kedacore/keda#4354]
### Report

When client asks more then one session number of scaled nodes will be n-1 and one request will be failed. Bug reproduces at 2.10.0, and not reproduces at 2.9.3

### Expected Behavior

Number of requests == number of new nodes

### Actual Behavior

Number of requests == number of new nodes -1

### Steps to Reproduce the Problem

1.Create a selenium grid deployment
2.Configure selenium grid node for any deployment
3.Configure ScaledObject for selenium grid node using template from Selenium Grid Scaler docs
4. Create few requests to the grid at once

### Logs from KEDA operator

```
example
```

### KEDA Version

2.10.0

### Kubernetes Version

None

### Platform

Other

### Scaler Details

Selenium Grid Scaler

**Comment by emboss64** [comment]
I can confirm I'm experiencing the same behavior:
- Starting point: 0 chrome nodes
- Queue 16 jobs
- Keda scales chrome nodes to 15 and 1 job stays in the queue

**Comment by JorTurFer** [comment]
This calculation is done here: https://github.com/kedacore/keda/blob/main/pkg/scalers/selenium_grid_scaler.go#L225
I guess that the problem cloud be in this calculation

https://github.com/kedacore/keda/blob/1a8ef85c6a08691ce52fa0192d206749e6234d68/pkg/scalers/selenium_grid_scaler.go#L270-L274

Could you review it? 🙏
