### ISSUE TITLE
KEDA Prometheus Scaler mTLS auth through mounted volumes

### ISSUE THREAD

**Issue by wybe-kopersf** [kedacore/keda#4357]
### Proposal

Allow the prometheus scaler to obtain cert, key and ca files from mounted volumes on the KEDA operator to establish mTLS between the KEDA operator and prometheus server.  

### Use-Case

The KEDA Prometheus Scaler supports mTLS between the KEDA operator and the prometheus server. 
The cert, key and ca files can be loaded in through env variables, secrets, vault, azureKeyVault, etc.

For security reasons I can only use cert, key and ca files that are stored in mounted volumes. 
The certs in the mounted volumes will be refreshed periodically by a sidecar. 

Below are the reasons why getting the ca, crt and key files from other sources is not feasible. 
Env variables is not secure.
Kubernetes secrets are not secure as in AWS EKS Kubernetes secrets are stored unencrypted.
Storing the certs in vault would require the setup of cert rotation in vault, which is added complexity. 

### Is this a feature you are interested in implementing yourself?

No

### Anything else?

Curious to hear how others have solved enabling mTLS for prometheus scaler with certificates that require frequent rotation.

**Comment by JorTurFer** [comment]
Hello,
With v2.10 you can mount your own CAs and read them: https://keda.sh/docs/2.10/operate/security/#register-your-own-ca-in-keda-operator-trusted-store
I think that this matches with your use case, am I right?

**Comment by wybe-kopersf** [comment]
Hello,

So I can put the custom ca, cert, and key files in `/custom/ca` folder?
On the documentation page you linked "all components inspect the folder `/certs `", is this not the place I should store the ca, cert and key files?
Regardless of which path the certs are stored in, how do I then point the prometheus scaler to use the credentials in these folders to enable TLS? I havn't been able to find that in the [prometheus scaler documentation](https://keda.sh/docs/2.10/scalers/prometheus/).

**Comment by JorTurFer** [comment]
Hi,
`/certs` folder is for placing KEDA's certificates (they are used for internal communications and for API server communications) and you have to place a single `tls.crt`, `tls.key` and `ca.cert`. These certificates are not added to the HttpClient trusted store and are only added for internal communications clients.

In this case, you want to add some self-signed CAs to the HttpClient trusted store, so you need to place the CAs that you want in the folder `/custom/ca`. KEDA will read all the files inside that folder and add them as a trusted CAs for all the HttpClients which are used to communicate with the upstream. You don't need to refer it anywhere as it's a global feature, we have plans for adding support at scaler level, but atm this parameter is global, so if you place your custom CAs in that folder, they will be trusted automatically. You can enable debug logs in the operator if you want to ensure that they are correctly register, and you will see a message per each found file in the folder

**Comment by JorTurFer** [comment]
Where are your certificates stored? You could use TriggerAuthentication to read them directly from Azure Key Vault or Hashicorp Vault and pass them directly to the scaler

**Comment by wybe-kopersf** [comment]
Services have a sidecar container that pull the certs from an external service and store them in a mounted volume. The certs are rotated frequently for security reasons. 
We don't use Azure Key Vault unfortunately.
We could use vault to store the certs, however then we would have to setup a service that rotates the certs periodically in vault. Since we already have a solution for rotating the certs (the sidecar container and mounted volumes) we opened this feature request to see if TLS could be made possible for the prometheus scaler through mounted volumes.

**Comment by JorTurFer** [comment]
I think that this could be done as an extra source in TriggerAuthentication, something like:

```yaml
file:
  - parameter: scalerParametar
    path: pathToTheFile
```
The problem I can see with this approach is that we should limit the folders where the files can be read to avoid arbitrary reads from system files. 
I guess that we can define a "safe path, create it during the Docker image generation and limit the TriggerAuthentication file support to that path.
WDYT @kedacore/keda-core-contributors ?

In case of agreement, are you willing to contribute with the feature @wybe-kopersf?

**Comment by wybe-kopersf** [comment]
This is exactly what I am looking for. 
I am willing to contribute in case of agreement.

**Comment by tomkerkhove** [comment]
What would be the expectations of the file path? I would rename it to `absolutePath`.

**Comment by JorTurFer** [comment]
My concerts are about security implications more than the spec itself, naming is an implementation detail xD

**Comment by tomkerkhove** [comment]
What concerns do you have?

**Comment by JorTurFer** [comment]
Are we comfortable allowing to read arbitrary paths in the container? Do we think that we should limit the readable folders to some specific path? Etc...

**Comment by JorTurFer** [comment]
Depending on the use case, it could work. The main problem with service mesh is that the api server (in the control plane) isn't inside the mesh, so if you put KEDA inside the service mesh, it becomes unreachable from api server. If there is any way t add KEDA into the mesh for outbounding requests and not for incoming requests it will work.
Other use case is where you only use ScaledJobs, in this case the api server doesn't try to reach KEDA because it reaches KEDA only for HPA (ScaledObject). 
In any case, we don't support KEDA with service meshes because we aren't expert in that kind of networking and there are a lot of things that could fail

**Comment by wybe-kopersf** [comment]
@zroubalik any thoughts on whether the paths the mounted volumes can access should be restricted?
