### ISSUE TITLE
Provide an IM Channel

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda#436]
Provide an IM Channel where a community can grow to talk about things that don't relate to issues/PRs

**Comment by balchua** [comment]
Is the keda channel in kubernetes not the place? But i have to admit its quiet over there.

**Comment by tomkerkhove** [comment]
Frankly, I was not aware of that one. Wouldn't gitter be a better place for this? That's a big Slack to join ??

Tom Kerkhove
Azure Architect at Codit, Microsoft Azure MVP

________________________________

**Comment by balchua** [comment]
True that its a big slack to join, but i guess most kubernauts perhaps are already there. Ive only seen @jeffhollan  and @zroubalik there. 😁

**Comment by tomkerkhove** [comment]
Frankly, I don't really care so if that's good, I'm good😁

We just have to document it then.

**Comment by jeffhollan** [comment]
Will document as part of README refactor

**Comment by tomkerkhove** [comment]
So, what approach do we take here?

Personally still more of a fan for Gitter as the Kube slack is very big imo

**Comment by jeffhollan** [comment]
I added the slack channel info to contributor guide. We can port over to README to but has had some good chatter and I also get push notifications so prefer to stick with it
