### ISSUE TITLE
Usage of Basic Proprietary Commercial License

### ISSUE THREAD

**Issue by Phani2811** [kedacore/keda#4364]
Hi Team,
I have run a blackduck scan for scanning the keda packages to validate if there are any security or licence risks.
As part of this, dependency scan analysis was executed and it has shown a transitive dependency on the component "**bouk/monkey**" (Version: v1.0.1).

This component is mapped to a licence called "Basic Proprietary Commercial License". When i verified the licence info in github, it has shown below content:

**I do not give anyone permissions to use this tool for any purpose. Don't use it.

I’m not interested in changing this license. Please don’t ask.**

Git hub url for reference: https://github.com/bouk/monkey/blob/master/LICENSE.md

Can you please confirm if there is any workaround to use keda packages without using this component so that licence issues are sorted. Thank you!

**Comment by zroubalik** [comment]
@Phani2811 thanks a lot for your message, we need to fix this. Seems like this dependency has been brought by this PR: https://github.com/kedacore/keda/pull/3804

@26tanishabanik FYI^

**Comment by JorTurFer** [comment]
I'm asking in parallel to FOSSA (the tool we use for detecting this issues) about this case because in theory, we don't have any issue but obviously we have it

**Comment by zroubalik** [comment]
I am working on a fix.
