### ISSUE TITLE
KEDA 2.10.1 tracking issue

### ISSUE THREAD

**Issue by zroubalik** [kedacore/keda#4370]
### Proposal

- License problem  https://github.com/kedacore/keda/pull/4366
- AWS scaler fix https://github.com/kedacore/keda/pull/4358
- Welcome message update https://github.com/kedacore/keda/pull/4360
- Deprecation message logger problem https://github.com/kedacore/keda/issues/4368

We should aim to release this hotfix release in the week of March 27-31.

### Is this a feature you are interested in implementing yourself?

Yes

**Comment by tomkerkhove** [comment]
Created https://github.com/kedacore/keda/issues/4374 to use the release template as well
