### ISSUE TITLE
Keda 2.10 Deployment has 3 crash loops before it starts - cannot find ca.cert 

### ISSUE THREAD

**Issue by tshaiman** [kedacore/keda#4388]
### Report

when taking the new Helm chart of Keda ( 2.10) and updating an exiting version the deployment is having hard time to stabilize the deployment. it takes 3 restart attempts before the helm can succeedd.

![image](https://user-images.githubusercontent.com/512709/225957777-7bdd73ac-0ea2-4881-9d5a-d47654260765.png)

![image](https://user-images.githubusercontent.com/512709/225957799-f31545fb-f63e-4f5c-bec6-228c16bcbfd2.png)

(note the restart counter on the containers)

### Expected Behavior

- smooth installation ;-)

### Actual Behavior

- 3 times container restart going into crash loop 

### Steps to Reproduce the Problem

1. install 2.10 on top of 2.9
2. Azure 
3. Workload Identity enabled

### Logs from KEDA operator

```
I0317 16:00:57.413013       1 controller.go:194] keda_metrics_adapter "msg"="Starting Controller" "controller"="scaledobject" "controllerGroup"="keda.sh" "controllerKind"="ScaledObject"
I0317 16:00:57.513125       1 main.go:164] keda_metrics_adapter "msg"="Connecting Metrics Service gRPC client to the server" "address"="keda-operator.keda.svc.cluster.local:9666"
E0317 16:00:57.513192       1 main.go:167] keda_metrics_adapter "msg"="error connecting Metrics Service gRPC client to the server" "error"="open /certs/ca.crt: no such file or directory" "address"="keda-operator.keda.svc.cluster.local:9666"
E0317 16:00:57.513207       1 main.go:282] keda_metrics_adapter "msg"="making provider" "error"="open /certs/ca.crt: no such file or directory"
E0317 16:00:57.513214       1 main.go:236] keda_metrics_adapter "msg"="unable to run external metrics adapter" "error"="open /certs/ca.crt: no such file or directory"

```

### KEDA Version

2.10.0

### Kubernetes Version

1.25

### Platform

Microsoft Azure

### Scaler Details

Azure Service Bus

**Comment by JorTurFer** [comment]
Hi,
How have you installed v2.10? In KEDA v2.10 we introduced certificates for internal communications and it is normal that KEDA operator restarts once because after generating the certificate, the pod is restarted to mount it in the local file system. 
KEDA metrics server and admission webhook pods shouldn't be scheduled until the secret and the certs are ready.

**Comment by JorTurFer** [comment]
TBH, metrics server and webhooks shouldn't have been restarted (I have never seen that behavior) but maybe there is any unexpected case that produces delays in certificate creation and that is the consequence IDK.
If you restart the deployments, you should see that now they don't fail and work in the first time
