### ISSUE TITLE
Define & document versioning/release strategy

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda#439]
Define & document versioning/release strategy which would help new customers guide how to use KEDA and what to expect.

**Comment by jeffhollan** [comment]
Will document as part of README refactor.

**Comment by tomkerkhove** [comment]
This is done so I presume it can be closed?

https://github.com/kedacore/keda/blob/master/RELEASE-PROCESS.MD

**Comment by zroubalik** [comment]
We should have a section on the Release cadence etc, @jeffhollan wdyt?

**Comment by tomkerkhove** [comment]
This is good to go!
