### ISSUE TITLE
Failed to pull image "ghcr.io/kedacore/keda-admission-webhooks:2.10.0"

### ISSUE THREAD

**Issue by billpieper** [kedacore/keda#4406]
### Report

Unable to pull container image for keda:

Failed to pull image "ghcr.io/kedacore/keda-admission-webhooks:2.10.0": rpc error: code = Unknown desc = failed to pull and unpack image "ghcr.io/kedacore/keda-admission-webhooks:2.10.0": failed to copy: httpReadSeeker: failed open: failed to do request: Get "https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:c4f6c218977897acc65c5387159c0d6013a89c2b073b6d7a75adc0dd720c84b8?se=2023-03-24T21%3A05%3A00Z&sig=H48wzNO2TRJSufOZwp8Mw4MLBqFIQ%2FUd%2FAcTnem0Ids%3D&sp=r&spr=https&sr=b&sv=2019-12-12": x509: certificate is valid for *.githubassets.com, githubassets.com, not pkg-containers.githubusercontent.com

This just started occurring in the past 10-20 min or so...

### Expected Behavior

image would be retrieved without issue

### Actual Behavior

image pull is failing

### Steps to Reproduce the Problem

1.
2.
3.

### Logs from KEDA operator

```
example
```

### KEDA Version

2.10.0

### Kubernetes Version

1.25

### Platform

Microsoft Azure

### Scaler Details

Service Bus, CPU

**Comment by tomkerkhove** [comment]
Did you retry the operation?

I tried to reproduce it on my side but it worked:

```
~  docker pull ghcr.io/kedacore/keda-admission-webhooks:2.10.0
2.10.0: Pulling from kedacore/keda-admission-webhooks
383e1c5dd0c1: Pull complete
b87fe015c3b2: Pull complete
Digest: sha256:8c062db679a95626966f29f9ad26c179acea91105b6258da897b5ed930461267
Status: Downloaded newer image for ghcr.io/kedacore/keda-admission-webhooks:2.10.0
ghcr.io/kedacore/keda-admission-webhooks:2.10.0
```

**Comment by tomkerkhove** [comment]
No worries!
