### ISSUE TITLE
KEDA paused autoscaling metrics+logs

### ISSUE THREAD

**Issue by arnoldyahad** [kedacore/keda#4430]
### Proposal

Hey everyone,
In our company we are using a lot the feature of pausing autoscaling.
It would be a great help if we could have metrics on deployments that are currently paused.
(Also if it could be written explicitly in the logs of keda, that can be great as well)

We want metrics about paused deployments because it can help us set relevant alerts to remind developers to remove the annotation, and also it will allow us to quickly see in Grafana what deployments are paused at the moment.

Thanks a lot.

**Comment by JorTurFer** [comment]
hey!
sure, I assign it to you 😄 
Thanks for the help ❤️

**Comment by zroubalik** [comment]
Done
