### ISSUE TITLE
The new version of AKS does not support keda 

### ISSUE THREAD

**Issue by shzshi** [kedacore/keda#4435]
### Report

The new version of AKS does not support keda 

https://github.com/Azure/AKS/releases

The KEDA addon currently supports aks versions 1.23, 1.24 and 1.25. the managed KEDA addon will not be supported on 1.26 GA at launch. If you use the KEDA addon, please do not upgrade to 1.26. If you use auto-upgrade with the rapid channel enabled as well as the KEDA addon, please switch off the rapid channel and update manually.

### Expected Behavior

Keda scaling would be broken

### Actual Behavior

Keda should support to higher version of AKS

### Steps to Reproduce the Problem

1.
2.
3.

### Logs from KEDA operator

```
example
```

### KEDA Version

None

### Kubernetes Version

None

### Platform

None

**Comment by zroubalik** [comment]
This should be reported on AKS side, KEDA is open source project and is not responsible for AKS.

**Comment by tomkerkhove** [comment]
Please report issues on https://github.com/azure/aks
