### ISSUE TITLE
Add Support for Trust Server SSL Certificate (unsafe ssl) for RabbitMQ Scaler

### ISSUE THREAD

**Issue by jade-lucas** [kedacore/keda#4448]
### Proposal

Currently TLS is hardcoded to not allow unsafe ssl. This is not ideal for environments that use VIPs, load balancers, wild carded ssl certs, etc. Purposing to add support for the unsafeSsl option for the RabbitMQ scaler. This would help keep parity with other scalers, stay inline with the documentation (https://keda.sh/docs/2.10/operate/security/), and also keep behavior similar to other RabbitMQ clients SDKs. More specifically support for trusting the server ssl certificate. Other RabbitMQ Client SDKs allow you to require ssl, but also allow you to trust the server ssl certificate or only do CA verify.

![image](https://user-images.githubusercontent.com/14896787/231645080-3e8dfad9-96f5-49b3-8e9d-f24a9a2b722d.png)
![image](https://user-images.githubusercontent.com/14896787/231645545-3ab3205c-5c5e-4a3e-807f-1dd092f15fb1.png)

### Use-Case

Allows us to use keda in our environment. We have a load balancer sitting in front of our RMQ cluster that does ssl pass through. Meaning there is no ssl termination at the load balancer. This means that the host attribute in ssl certs coming back from the cluster don't align the host being called by the client, which fails full ssl verification.

### Is this a feature you are interested in implementing yourself?

No

**Comment by zroubalik** [comment]
@JorTurFer this is the stuff we talked about, right?

**Comment by JorTurFer** [comment]
This is related, yes (it's not the same because I wanted to integrate the CAs, but we can do both at once)
