### ISSUE TITLE
Optionally use avg_rate from rabbitmq metrics and support setting parameters

### ISSUE THREAD

**Issue by laithalissa** [kedacore/keda#4507]
### Proposal

I wish to be able to configure the metrics calculation as supported by the rabbitmq API.

At present the rabbitmq scaler only uses the `rate` field from the API (see [here](https://github.com/kedacore/keda/blob/1d2e7ca860ee6cb23522866ba86579437bde8a0c/pkg/scalers/rabbitmq_scaler.go#LL479C10-L479C10)), which can give spiky results and make scaling flappy.

Rabbitmq supports a [number of options](https://raw.githack.com/rabbitmq/rabbitmq-management/rabbitmq_v3_6_9/priv/www/doc/stats.html) for this api which can assist an operator to generate a more smoothed scale function, for example I could supply `msg_rates_incr` and `msg_rates_age` as in the below sample. Note that the `rate` shows at `0` whereas by tuning the request with these parameters I get an `avg_rate` of `0.8` which is much closer to the value I expect (0.9)

```
http://localhost:15672/api/queues/%2F/myQueue?msg_rates_age=10&msg_rates_incr=1' | jq '.message_stats.publish_details'                                                                                                                                                       

{
  "avg": 38713.36363636364,
  "avg_rate": 0.8,
  "rate": 0,
  "samples": [
  ...
  ]
}

```

### Use-Case

It would help me give a much smoother scaling implementation. At the moment I'm finding that rate fluctuates a lot around the averaged value, and causes overscaling sometimes.

### Is this a feature you are interested in implementing yourself?

No

**Comment by JorTurFer** [comment]
Hi @laithalissa 
This makes sense totally, are you willing to contribute adding the feature?

**Comment by laithalissa** [comment]
I can look into it at some point but I have no bandwidth at the moment. I'll have a go in a few weeks if nobody else has picked it up.

**Comment by laithalissa** [comment]
Backlinking [this discussion](https://github.com/rabbitmq/rabbitmq-server/discussions/8419) as it looks highly relevant

**Comment by laithalissa** [comment]
I'm trying to squeeze in time to work on this. I need to figure out how to test this change but I have a wip here if you want to chime in https://github.com/laithalissa/keda/commit/6a7f1b9bde0032bbe0f527fc8af2eb81c4da4f73

**Comment by laithalissa** [comment]
I could use some advice on [this line](https://github.com/kedacore/keda/blob/784539dddb8e09d8df079e93801ccbfebb3b3060/pkg/scalers/rabbitmq_scaler.go#L588). This activation logic is first introduced in [this PR](https://github.com/kedacore/keda/pull/2831).

Personally, I don't think a `rate` trigger should be affected by the number of messages in the queue, I feel this logic should simply be

```go
isActive = publishRate > s.metadata.activationValue
```

Is there some explanation I'm missing here, like some kind of backwards compatibility?

**Comment by JorTurFer** [comment]
I think that it was done by error IDK when, but I agree that as they (length and rate) are separated options in the scaler, we should use the correct one for activating the scale and not both.

**Comment by laithalissa** [comment]
Incidentally, should it be `>` or `>=`? I would have thought `>=` 🤔

**Comment by JorTurFer** [comment]
It should be `>` because if users don't provided any value for it means that the value is any message in the queue, so we set 0 as default.

`isActive = publishRate > s.metadata.activationValue`  --> as default (s.metadata.activationValue:0) the trigger will be active if the rate isn't just 0

**Comment by rwkarg** [comment]
If you don't look at the message backlog and only the rate, then can you get in a situation where there were a large number of messages added before, but now there are none being published? 

If you don't activate it with 0 publish rate but 100 messages in the queue then those will never be processed?

**Comment by rwkarg** [comment]
In general, I'd consider using publishRate without also having a message queue metric an anti-pattern. If the queue backs up because dependencies are down or there was a temporary burst of publishing but now there isn't then you'll have a large backlog but not a corresponding large set of processors.

**Comment by laithalissa** [comment]
I agree using a rate scaler without a queue scaler is an unusual sounding use case. I personally use my scalers with 2 triggers, one for backlog and one for message rate. 

That being said, I don't think the rate scaling implementation should implicitly make decisions without it being clear it the user, nor should it overload a single variable to mean disparate things.

I think it's very reasonable to make the user responsible for deciding how to scale against a backlog vs an increased rate.

**Comment by JorTurFer** [comment]
I agree with you and having only publish rate without queue length isn't a real world scenario, but IMO the user should be who decides the scaling behavior. 

With the current implementation, if the publishing rate is 0 and there are 1 million messages, the workload will have minReplicaCount even thought the scaler is active, so IMO doesn't make sense. Users should be the owners of the decisions and they should decide the behavior based on queue length. 

KEDA supports multiple triggers, so users can add triggers for both stuff, deciding what happens in each case. IMO we shouldn't have hidden and not documented behaviors but clarifying this in the docs would be also useful.

**Comment by laithalissa** [comment]
I'm very keen to get this change in the next release if possible, please let me know if there's anything I can do to make that happen.

**Comment by rwkarg** [comment]
I’d like to see this change

**Comment by zroubalik** [comment]
> I agree with you and having only publish rate without queue length isn't a real world scenario, but IMO the user should be who decides the scaling behavior.
> 
> With the current implementation, if the publishing rate is 0 and there are 1 million messages, the workload will have minReplicaCount even thought the scaler is active, so IMO doesn't make sense. Users should be the owners of the decisions and they should decide the behavior based on queue length.
> 
> KEDA supports multiple triggers, so users can add triggers for both stuff, deciding what happens in each case. IMO we shouldn't have hidden and not documented behaviors but clarifying this in the docs would be also useful.
> 
> Do you have any other opinion @tomkerkhove @zroubalik ?

I agree on this. Sorry I haven't noticed this issue before.

**Comment by zroubalik** [comment]
@kedacore/keda-maintainers what should we do about this? :)

**Comment by JorTurFer** [comment]
I've checked current logic and I think that we should refactor this in future versions
https://github.com/kedacore/keda/blob/19f14a82319b1b0aa7d524b1474e149a2231f117/pkg/scalers/rabbitmq_scaler.go#L618-L624

I think that if I have chosen a public_rate mode, the scaler has to take into account just the publishing rate. I can use another queue length scaler if I want to take into account the queue length.

My concern is that this is a huge breaking change and we cannot do it just when we want. I think that majority of users using publish rate also use queue length, but that's an assumption

**Comment by rwkarg** [comment]
I'm still not sure why we want the default behavior for publish rate only to be that a burst of messages will spin up processors, then spin them down to zero even if there are still messages in the queue waiting to be processed. I can't think of a use case where that would be desired, let alone think of a reason to make a breaking change from existing behavior to make that the default behavior.

Do we know of a specific use case where there is a desire to use only publish_rate and explicitly want to scale down to zero while there are still messages in the queue? If this is desired behavior in some uncommon cases then I could see allowing that to be configured, but it doesn't seem right to make that the default behavior.

**Comment by zroubalik** [comment]
That's a valid point^. I think the main concern is backwards compatibility - for users that have already configured their setup with the original behavior in mind.
