### ISSUE TITLE
Remove Azure Data Explorer 'metadata.clientSecret'

### ISSUE THREAD

**Issue by JorTurFer** [kedacore/keda#4514]
### Report

We are allowing to provide secrets as plain text in metadata section, we should remove as metadata isn't safe for managing secrets

The message has been added, we should delete it in 2.13
.

**Comment by tomkerkhove** [comment]
Agreed!

**Comment by JorTurFer** [comment]
https://github.com/kedacore/keda/pull/4490

**Comment by tomkerkhove** [comment]
@JorTurFer Can you please add/link the other aspects of our deprecation policy please?

https://github.com/kedacore/keda/discussions/categories/deprecations

https://github.com/kedacore/governance/blob/main/DEPRECATIONS.md#introducing-new-deprecations

**Comment by tomkerkhove** [comment]
> [<img alt="" width="16" height="16" src="https://avatars.githubusercontent.com/u/36899226?v=4&amp;size=48">@JorTurFer](https://github.com/JorTurFer) Can you please add/link the other aspects of our deprecation policy please?
> 
> https://github.com/kedacore/keda/discussions/categories/deprecations
> 
> https://github.com/kedacore/governance/blob/main/DEPRECATIONS.md#introducing-new-deprecations

@JorTurFer This can be closed I think, but did we do this?

**Comment by JorTurFer** [comment]
yeah, this has been already removed as part of https://github.com/kedacore/keda/pull/5038, so I close this
