### ISSUE TITLE
Failing to fetch metrics on GKE

### ISSUE THREAD

**Issue by raghu-manne** [kedacore/keda#4529]
### Report

Setting up KEDA on GKE, scaledObject for GCP Pub Sub not able to scale up the target deployment though there were unacknowledged messages in my PubSub topic.

### Expected Behavior

To scale up the target deployment depending upon the unacknowledged messages.

### Actual Behavior

Seems keda operator scaling down pods to 0 when there are no messages, and scaling to 1 when the pubsub topic receives messages. But when there are more messages it is not able to scale up more.

### Steps to Reproduce the Problem

1. Setting up KEDA on GKE with workload identity
2. Create a sample Pubsub topic, subscription and a sample deployment. Also keda resources scaledobject and triggerauthentication.
3. Publish some messages to created pubsub topic

### Logs from KEDA operator

Logs from keda-operator:
```
 INFO Reconciling ScaledObject {"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "ScaledObject": {"name":"pubsub-test","namespace":"default"}, "namespace": "default", "name": "pubsub-test", "reconcileID": "3c4d66fc-baa9-42eb-aa28-4f7b286e96c6"}
```

Logs from keda-operator-metrics-apiserver:
```
apiserver received an error that is not an metav1.Status: &status.Error{s:(*status.Status)(0xc0002b1b20)}: rpc error: code = Unknown desc = error when getting metric values no matching metrics found for s0-gcp-ps-keda-test-subscription
```
Events from creted HPA:

```
Events:
  Type     Reason                   Age                 From                       Message
  ----     ------                   ----                ----                       -------
  Warning  FailedGetExternalMetric  18m (x11 over 21m)  horizontal-pod-autoscaler  unable to get external metric default/s0-gcp-ps-keda-test-subscription/&LabelSelector{MatchLabels:map[string]string{scaledobject.keda.sh/name: pubsub-test,},MatchExpressions:[]LabelSelectorRequirement{},}: unable to fetch metrics from external metrics API: rpc error: code = Unknown desc = error when getting metric values no matching metrics found for s0-gcp-ps-keda-test-subscription
```

### KEDA Version

2.10.1

### Kubernetes Version

1.25

### Platform

Google Cloud

### Scaler Details

GCP - Pub Sub

**Comment by JorTurFer** [comment]
Hi,
Do you have any kind of network policy in your cluster?
KEDA metrics server shows an error related with not reaching KEDA operator (who has the metric values). How are you installing KEDA?
Could you share operator and metrics server logs?

**Comment by raghu-manne** [comment]
Sorry i missed on this issue until now.
I was testing on a temporary cluster but when i deployed on proper cluster it worked.
I will close this issue.
Thanks!
