### ISSUE TITLE
KEDA Build Tools Not Compiling for s390x

### ISSUE THREAD

**Issue by jried31** [kedacore/keda#4531]
### Report

I'm using an RHEL8 development machine on s390x to compile KEDA from source code, with the objective of deploying it manually onto an IBM Redhat OpenShift cluster as a container. Upon running the make build command, the build-tools module fails with the following error below. Is there any way to assist with compiling the latest version of KEDA on s390x architecture?

 > [internal] load metadata for ghcr.io/kedacore/build-tools:1.19.7:
------
failed to solve with frontend dockerfile.v0: failed to create LLB definition: no match for platform in manifest sha256:485cc0164d93f38b5bea9121e7dcb71d6a588777fe7780250e4eeb96cfef5aed: not found

NOTE: I also ran the option "make docker-build-tools" to build just that module and the Rust python module from build-tools.Dockerfile failed to build successfully. 
      
          =============================DEBUG ASSISTANCE=============================
          If you are seeing a compilation error please try the following steps to
          successfully install bcrypt:
          1) Upgrade to the latest pip and try again. This will fix errors for most
             users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
          2) Ensure you have a recent Rust toolchain installed. bcrypt requires
             rustc >= 1.56.0.
      
          Python: 3.8.10
          platform: Linux-4.18.0-305.el8.s390x-s390x-with-glibc2.29
          pip: n/a
          setuptools: 67.7.2
          setuptools_rust: 1.6.0
          rustc: n/a
          =============================DEBUG ASSISTANCE=============================
      
      error: can't find Rust compiler

### Expected Behavior

Running 'make build' to compile the source code and produce all executable modules that would be wrapped into a docker container, pushed to a Docker repository and deployed in KEDA.

### Actual Behavior

"make build" fails to compile executables.

### Steps to Reproduce the Problem

1. Install RHEL8, protoc and ensure gcc and g++ are installed 
2. Download KEDA and run "make build"
3. Run make "docker-build-tools" also gives error
NOTE: I have run the same commands on KEDA version 2.10 and 2.9. Same error occurs.

### Logs from KEDA operator

```
test -s /home/cloud-user/projects/keda-2.9.3/bin/controller-gen || GOBIN=/home/cloud-user/projects/keda-2.9.3/bin go install sigs.k8s.io/controller-tools/cmd/controller-gen
test -s /home/cloud-user/projects/keda-2.9.3/bin/mockgen || GOBIN=/home/cloud-user/projects/keda-2.9.3/bin go install github.com/golang/mock/mockgen
GOBIN=/home/cloud-user/projects/keda-2.9.3/bin go install google.golang.org/protobuf/cmd/protoc-gen-go
GOBIN=/home/cloud-user/projects/keda-2.9.3/bin go install google.golang.org/grpc/cmd/protoc-gen-go-grpc
PATH="/home/cloud-user/projects/keda-2.9.3/bin:/home/cloud-user/.local/bin:/home/cloud-user/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/data/apache-jmeter-5.4.3/bin:/home/cloud-user/.local/bin" protoc -I vendor --proto_path=hack LiiklusService.proto --go_out=pkg/scalers/liiklus --go-grpc_out=pkg/scalers/liiklus
PATH="/home/cloud-user/projects/keda-2.9.3/bin:/home/cloud-user/.local/bin:/home/cloud-user/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/data/apache-jmeter-5.4.3/bin:/home/cloud-user/.local/bin" protoc -I vendor --proto_path=pkg/scalers/externalscaler externalscaler.proto --go_out=pkg/scalers/externalscaler --go-grpc_out=pkg/scalers/externalscaler
PATH="/home/cloud-user/projects/keda-2.9.3/bin:/home/cloud-user/.local/bin:/home/cloud-user/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/data/apache-jmeter-5.4.3/bin:/home/cloud-user/.local/bin" protoc -I vendor --proto_path=pkg/metricsservice/api metrics.proto --go_out=pkg/metricsservice/api --go-grpc_out=pkg/metricsservice/api
/home/cloud-user/projects/keda-2.9.3/bin/controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."
/usr/lib/golang/src/net/cgo_linux.go:12:8: no such package located
Error: not all generators ran successfully
run `controller-gen object:headerFile=hack/boilerplate.go.txt paths=./... -w` to see all available markers, or `controller-gen object:headerFile=hack/boilerplate.go.txt paths=./... -h` for usage
make: *** [Makefile:127: generate] Error 1
```

### KEDA Version

2.10.0

### Kubernetes Version

None

### Platform

None

**Comment by JorTurFer** [comment]
Hi @jried31 
Sadly, we don't support s390x currently. I don't have any machine that I can use with that architecture to help you but it looks like the problem is related with this line 
`/usr/lib/golang/src/net/cgo_linux.go:12:8: no such package located`
The only option that I can suggest is using an AMD or ARM machine and cross-compile the image using docker buildx to generate the image in s390x. If you use one supported architecture for building any non-supported architecture, you could use all the already existing tooling.

@zroubalik , should we support s390x for OpenShift? Isn't KEDA available as part of OpenShift's OLM Operator (using custom-metrics or something similar)?

**Comment by jried31** [comment]
A preview (pre-alpha i presume) is available for OpenShift on x86 with limited functionality. It is not made available for install on OpenShift s390x architecture. I did manage to cross compile successfully with an x86 machine. An installation via OperatorHub would be ideal so that we're working with the same tested versions of Keda on OpenShift. 

I appreciate the consideration for adding to your roadmap.

**Comment by jried31** [comment]
@jried31 -- I raised the issue is on both sides. --- Yes, regarding your question. How would you like to go about discussing? 

Beyond this error: /usr/lib/golang/src/net/cgo_linux.go:12:8: no such package located
which is a separate issue I recall that the build-tools step fails compiling on s390x.
