### ISSUE TITLE
Rename CRD api version to keda.k8s.io/v1

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda#454]
With v1.0 coming up I was wondering if we should update our API version to `keda.k8s.io/v1` instead of `keda.k8s.io/v1alpha1`

**Comment by jeffhollan** [comment]
@zroubalik and @ahmelsayed mentioned operator SDK may be able to help here with version translations.  @zroubalik mentioned it may make sense to keep as v1alpha1 in case we end up breaking out into jobs / deployments from a single `scaledobjects`.  So may be ok?  

@ahmelsayed will take a look and make the call

**Comment by tomkerkhove** [comment]
Closing as we've shipped v1 and there are no breaking changes to justify this.
