### ISSUE TITLE
FailedGetExternalMetric Warning for selenium KEDA- Unable to get external metric

### ISSUE THREAD

**Issue by DeepKandey** [kedacore/keda#4556]
### Report

selenium keda is unable to get external metric which results in hpa failure

These are my K8s yaml using to scale chrome node on selenium hub on my Windows machine
https://github.com/DeepKandey/POMFramework/tree/master/k8s

![image](https://github.com/kedacore/keda/assets/39937316/a3e5a1ef-6241-4b3f-85ad-7344b936ee8c)

Error Message
unable to get external metric default/s0-seleniumgrid-chrome/&LabelSelector{MatchLabels:map[string]string{scaledobject.keda.sh/name: selenium-chrome-scaledobject,},MatchExpressions:[]LabelSelectorRequirement{},}: unable to fetch metrics from external metrics API: rpc error: code = Unknown desc = error when getting metric values no matching metrics found for s0-seleniumgrid-chrome

### Expected Behavior

It should get the metrics and should autoscale bases on the metricsbased

### Actual Behavior

It does not get the metrics and should autoscale based on the metrics

### Steps to Reproduce the Problem

1. Go to the below GitHub  and apply the manifests for hub and node deployment -> https://github.com/DeepKandey/POMFramework/tree/master/k8s
2.  Hit the command kubectl describe hpa

### Logs from KEDA operator

```
example
```

### KEDA Version

2.10.1

### Kubernetes Version

1.26

### Platform

Other

**Comment by DeepKandey** [comment]
The issue is solved.

**Comment by topcu-muhammet** [comment]
@DeepKandey Hi, how did you solve it? I get the same error.

**Comment by DeepKandey** [comment]
I was passing the wrong selenium hub url. I added the namespace in the url so that keda metric server could access the selenium hub

For example 
Http://Selenium-hub:4444
Http://selenium-hub.default:4444

**Comment by RevealOscar** [comment]
just adding on to this since I had some issues too
```
http://user:pass@service-name.namespace:port
```
