### ISSUE TITLE
Keda and Hashiorp Vault Authtication using serviceAccount as Auth method

### ISSUE THREAD

**Issue by btwseeu78** [kedacore/keda#4602]
### Discussed in https://github.com/kedacore/keda/discussions/4601

<div type='discussions-op-text'>

<sup>Originally posted by **btwseeu78** June  1, 2023</sup>
I am currently Testing Hashicorp Vault authentication for keda, we noticed the way keda uses is it directly uses serviceaccount token for keda for keda operator now i am getting some issues with and definitely need better examples on authentication.

I found the Architecture is quote troublesome.

Since the triggers or all the triggers will use operator service account to communicate that means we need a key than can read creds from all paths , that itself is problematic to have, and also this can not used at all in shared cluster where there are multiple project hosted since it mean violation of policy.

Suggestion would handling it how external secret operator does since its one of the standardized way to pull secret from vault.

Also we need more logs for Auth errors seems very limited.

for now im getting token not found error on my trigger,

also we are seeing this error as well for some reason.
```
2023-06-01T10:13:28Z    INFO    Observed a panic in reconciler: runtime error: invalid memory address or nil pointer dereference                            {"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "ScaledObject": {"name":"kedalab-scaled-vault","namespace":"monitoring"}, "namespace": "monitoring", "name": "kedalab-scaled-vault", "reconcileID": "021a8854-1a92-4b9b-bed5-d08ca2e6a605"}
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x2f61695]
``
</div>

also we are getting errros on vault login with our trigger:

```
ERROR   scale_handler   error authenticate to Vault     {"type": "ScaledObject", "namespace": "monitoring", "name": "kedalab-scaled-vault", "triggerAuthRef.Name": "vault-test", "error": "Error making API request.\n\nNamespace: monitoring\nURL: PUT https://xxxx:8200/v1/auth/xxxxxx/login\nCode: 400. Errors:\n\n* missing client token"}
```

**Comment by tomkerkhove** [comment]
If I get it correctly, this issue is to improve the authentication nstory and how it fetches the information, is that correct?

**Comment by trzejos** [comment]
I think the issue is that the current implementation references a file mounted in the keda operator pod rather than an external service account. [VSO](https://developer.hashicorp.com/vault/docs/platform/k8s/vso) handles this a bit differently by allowing you to reference a service account by name, then impersonating that service account when using the kubernetes auth method.
