### ISSUE TITLE
Authentication: support AWS secret manager

### ISSUE THREAD

**Issue by devopsmash** [kedacore/keda#4628]
### Proposal

add to `TriggerAuthentication` support to "**AWS secret manager**"

### Use-Case

We are using AWS MSK with sasl (user & password) for authentication

Why? Because we are allowing our Dev team in Development environment to access the MSK with public IP.
Therefor, the developer can't use AWS IAM role (we are not providing them aws creds) so we have to use sasl (user & password).

Because of this, we want that `TriggerAuthentication` will support also getting the user & password from the AWS secret manager instead of a k8s `secret` that realy easy to get the creds.

### Is this a feature you are interested in implementing yourself?

No

### Anything else?
It seems that you already support **Hashicorp Vault secret(s)** and **Azure Key Vault secret(s)**.
Support **AWS secret manager** can be very helpful.

more here: https://keda.sh/docs/2.10/concepts/authentication/

**Comment by nitishchauhan0022** [comment]
I would like to work on it, could you please assign this to me @JorTurFer

**Comment by JorTurFer** [comment]
Nice!!! ❤️❤️❤️

**Comment by geoffrey1330** [comment]
Hi @zroubalik could you please assign this task to me as it been stale for a while now.
cc @JorTurFer

**Comment by geoffrey1330** [comment]
Hi @zroubalik could you please assign this task to me as it been stale for a while now.
cc @JorTurFer

**Comment by JorTurFer** [comment]
Sure ! 
❤️
