### ISSUE TITLE
Add a new Prometheus metric to expose build info from Keda

### ISSUE THREAD

**Issue by pedro-stanaka** [kedacore/keda#4647]
### Proposal

A new "info metric" (`keda_build_info`) would be exposed in the Prometheus endpoint with information like:

* Version
* Git Commit
* Go Version
* Go Arch

### Use-Case

This is useful to join with other metrics and see easily which version you are running (specially across different clusters).

### Is this a feature you are interested in implementing yourself?

Yes

**Comment by zroubalik** [comment]
Done
