### ISSUE TITLE
Harden GitHub Runner Spec

### ISSUE THREAD

**Issue by Eldarrin** [kedacore/keda#4651]
### Proposal

Use a GitHub App to provide a more secure access to GitHub for the runners as opposed to a PAT token and gain increased api usage. (15k vs 5k / hour)

### Use-Case

More secure runner integration with github using certs as opposed to keys

### Is this a feature you are interested in implementing yourself?

Yes

**Comment by JorTurFer** [comment]
This'd be an awesome improvement ❤️

**Comment by Eldarrin** [comment]
> This would be an awesome improvement ❤️ We will cut a release in 2 weeks or so, do you think that you will have time? (no rush at all)

No promises, need to fix my video driver on my RHEL box first, lol

**Comment by piroinno** [comment]
I was just thinking about this a few days ago. Looking forward to this!

**Comment by zroubalik** [comment]
> video driver on my RHEL box

Well, this is a combination that one doesn't see every day 😄

**Comment by Eldarrin** [comment]
@JorTurFer Docs, test tool mods and code PR opened. Test tools and app bit needs to be done before running the e2e.

**Comment by piroinno** [comment]
> > This would be an awesome improvement ❤️ We will cut a release in 2 weeks or so, do you think that you will have time? (no rush at all)
> 
> No promises, need to fix my video driver on my RHEL box first, lol

Hows that fix going :-)

**Comment by JorTurFer** [comment]
@Eldarrin , I'll prepare everything later on :)

**Comment by JorTurFer** [comment]
I have done all the steps, let's see if I have done them well 🤞

**Comment by piroinno** [comment]
Looks good. Need an approver?

**Comment by piroinno** [comment]
Thanks all!
