### ISSUE TITLE
Publish KEDA on Operator Hub

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda#469]
Publish KEDA on Operator Hub

https://operatorhub.io/

**Comment by tomkerkhove** [comment]
What's the status here, are we still blocked on something @zroubalik?

**Comment by zroubalik** [comment]
@tomkerkhove I will need to modify https://github.com/kedacore/keda-olm-operator for v1.1 and then will start initiate the publishing process.

**Comment by zroubalik** [comment]
Done https://operatorhub.io/operator/keda
