### ISSUE TITLE
create HPA object which can scale to 0

### ISSUE THREAD

**Issue by chrisliu1995** [kedacore/keda#4697]
### Proposal

Although KEDA support to scale objects' replicas to 0, it is slow to scale down from 1 to 0.

Actually, Kubernetes support the feature-gate `HPAScaleToZero`, which can be used to create a HPA object with 0 min value. That would be more faster.

### Is this a feature you are interested in implementing yourself?

Yes

**Comment by tomkerkhove** [comment]
This is a duplicate of https://github.com/kedacore/keda/issues/208
