### ISSUE TITLE
2.10.1 upgrade - no such host error

### ISSUE THREAD

**Issue by jstefankowski** [kedacore/keda#4699]
### Discussed in https://github.com/kedacore/keda/discussions/4691

<div type='discussions-op-text'>

<sup>Originally posted by **jstefankowski** June 15, 2023</sup>
After upgrading keda from 2.6.1 to 2.10.1 the operator logs the below every minute.  

Err: connection error: desc = "transport: Error while dialing: dial tcp: lookup keda-sa.keda.svc.cluster.local on 10.106.0.2:53: no such host"
I0614 12:09:47.411621       1 client.go:93] keda_metrics_adapter/provider "msg"="Waiting for establishing a gRPC connection to KEDA Metrics Server" 
E0614 12:09:47.426056       1 provider.go:110] keda_metrics_adapter/provider "msg"="timeout" "error"="timeout while waiting to establish gRPC connection to KEDA Metrics Service server" "server"="keda-sa.keda.svc.cluster.local:9666"

Anyone familiar with this error and what may be causing it ?  </div>

**Comment by jstefankowski** [comment]
Update, helm upgrade without custom operator.name didn't help, even with operator service set to default keda-operator still getting the same error in apiserver pod log:

I0616 15:31:39.635099       1 client.go:93] keda_metrics_adapter/provider "msg"="Waiting for establishing a gRPC connection to KEDA Metrics Server" 
E0616 15:32:39.701388       1 provider.go:110] keda_metrics_adapter/provider "msg"="timeout" "error"="timeout while waiting to establish gRPC connection to KEDA Metrics Service server" "server"="keda-operator.keda.svc.cluster.local:9666"

**Comment by JorTurFer** [comment]
Hi,
How are you deploying KEDA? I guess that you are using helm, could you share the parameters?
Do you have any network policy blocking the traffic inside the cluster?

**Comment by jstefankowski** [comment]
Hi @JorTurFer,
yes, KEDA is deployed using helm.  There is no network policy blocking internal traffic.  

Here are helm pararmeters.

helm upgrade keda kedacore/keda --install \
  --version 2.10.1 \
  --namespace keda \
  --wait \
  --timeout 10m0s \
  --set image.keda.repository=acct_removed.dkr.ecr.us-east-2.amazonaws.com/keda \
  --set image.keda.tag=2.10.0 \
  --set image.metricsApiServer.repository=acct_removed.dkr.ecr.us-east-2.amazonaws.com/keda-metrics-apiserver \
  --set metricsServer.useHostNetwork=true \
  --set image.metricsApiServer.tag=2.10.0 \
  --set serviceAccount.name=keda-sa \
  --set serviceAccount.annotations."eks\.amazonaws\.com\/role\-arn"=arn:aws:iam::acct_removed:role/eks-sa-role-keda-us-east-1 \
  --set tolerations[0].operator=Equal,tolerations[0].effect=NoSchedule,tolerations[0].key=apps,tolerations[0].value=corecomponents \
  --set hostNetwork=true

**Comment by JorTurFer** [comment]
I think that this is the problem: `--set hostNetwork=true`
I'm not sure if using the host network, ms can reach the operator. Why do you need it?

**Comment by jstefankowski** [comment]
@JorTurFer  good point !  Setting --useHostNetwork=false and leaving --set hostNetwork=true fixed connection timeout errors.  

Still testing keda scaling.

**Comment by jstefankowski** [comment]
Setting --useHostNetwork to false fixed "no such host' error but now we see another issue where attempts to delete namespaces fail because v1beta1.external.metrics.k8s.io api service is not available and in FailedDiscoveryCheck state.  As per discussion [1231](https://github.com/kedacore/keda/issues/1231) deleting  v1beta1.external.metrics.k8s.io in test cluster immediately resolved namespaces stuck in terminating state and the affected namespaces terminated successfully.

Is this v1beta1.external.metrics.k8s.io api service still required or does removing it affects cpu based autoscaling for example ?
Trying to determine whether it's safe to remove the api server in production.

**Comment by JorTurFer** [comment]
I think that you just need to open the port in the VPC firewall: https://github.com/kedacore/keda/issues/1231#issuecomment-778253193
If you delete `v1beta1.external.metrics.k8s.io`, KEDA won't work, you can use it for CPU/Memory scalers, but that's all. No other scalers will work

**Comment by jstefankowski** [comment]
Curious why is access through firewall to metrics api service target port 6443 required.  I guess because usehostNetwork is now set to false ?

**Comment by JorTurFer** [comment]
It's because as default, KEDA metrics server listens on poor 6443 and usually AWS blocks that port. We have to try yet if we can change the port to not require this whitelist, but if you want you can try out using the port 433 instead of the port 6443 just changing this parameter: https://github.com/kedacore/charts/blob/main/keda/values.yaml#L333

**Comment by jstefankowski** [comment]
Adding --set metricsServer.dnsPolicy=ClusterFirstWithHostNet resolved "no such host" errors and v1beta1.external.metrics.k8s.io apiservice  in DiscoveryFailed state.  Keda is back to normal.

**Comment by zroubalik** [comment]
@jstefankowski are you wiling to contribute this to the Troubleshooting guide please?

https://keda.sh/docs/2.11/troubleshooting/

**Comment by jstefankowski** [comment]
@zroubalik My issue was pretty much the same as Istio issue, last in troubleshooting guide.  I just missed the comment in values.yaml.

# use ClusterFirstWithHostNet if `useHostNetwork: true` https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-dns-policy

**Comment by lukasmrtvy** [comment]
@zroubalik @jstefankowski is right, the FAQ ( https://github.com/kedacore/keda-docs/blob/main/content/troubleshooting/keda-external-metrics-issue.md?plain=1#L41 ) is incorrect in this use case.
