### ISSUE TITLE
Pause trigger evaluation

### ISSUE THREAD

**Issue by megacier** [kedacore/keda#4725]
### Proposal

Currently, the annotation `autoscaling.keda.sh/paused-replicas: "0"` [doc](https://keda.sh/docs/2.7/concepts/scaling-deployments/#pause-autoscaling) can be added to pause the scaling. 

A similar annotation could be added to stop triggers evaluation as well. 
Another option would be to have an annotation that prevents logging on triggers evaluation error.

### Use-Case

1. Maintenance
When doing maintenance on services used as triggers (e.g. Postgres or metric API) Keda logs error even with  `autoscaling.keda.sh/paused-replicas: "0"` annotation

2. Night downscaling
We downscale part of our testing infrastructure at night by setting all replicas to 0 and adding the `autoscaling.keda.sh/paused-replicas: "0"` annotation. However, as our scaledObject trigger is a [metric API kind](https://keda.sh/docs/2.10/scalers/metrics-api/) that targets a service that now points to 0 replicas, Keda logs errors on every evaluation.

### Is this a feature you are interested in implementing yourself?

No

**Comment by zroubalik** [comment]
This has been just implemented all will be present in the 2.11 release:
https://github.com/kedacore/keda/pull/4253
