### ISSUE TITLE
PR e2e test: Validate the regex before building the images

### ISSUE THREAD

**Issue by JorTurFer** [kedacore/keda#4750]
### Proposal

Currently, we build the images and deploy them into the cluster before checking the provided regex, this could deal in a failure 20 minutes later. 
We should check somehow the regex before starting the process to be more efficient and saving resources

### Is this a feature you are interested in implementing yourself?

Yes

**Comment by sbdtu5498** [comment]
Hey, @JorTurFer can you give me a bit more context on what regex is being used for here specifically or would be used for?

**Comment by JorTurFer** [comment]
Hey, sure!
Currently, [we have a mechanism for running e2e tests as part of PRs based on allowed member comments](https://github.com/kedacore/keda/blob/main/.github/workflows/pr-e2e.yml) (`/run-e2e`). As we want to allow not executing the whole tests suite, we use a regex that can be provided with the comment (`/run-e2e REGEX_HERE`).

The problem is that if the regex is wrong and doesn't match with any file, we want that the execution fails because we have introduced something wrong. Where is the problem? When the regex is executed. Basically we build the images, prepare the cluster, deploy pod identities, KEDA, etc, and then we use the regex for getting the test cases. This is slow and could take 20-25 just for failing:
![image](https://github.com/kedacore/keda/assets/36899226/dd995304-e5e2-4bb0-8815-837df5a9c023)

e2e test suite is executed using [this file](https://github.com/kedacore/keda/blob/main/tests/run-all.go) through make (`make e2e-test`). [This is the function that applies the regex](https://github.com/kedacore/keda/blob/main/tests/run-all.go#L145) for filtering files. 

In order so save time and resources building the image and deploying things into the cluster, just for detecting the typo in the regex, I thought to extract that function and run them in the 2nd job of the workflow, before building the image. In case of no matches, raising an error and finishing the execution there, having saved 20 minutes.

Why in the 2nd job and not in the 1st, to save more time and resources? Because as we use a comment trigger, every comment wherever in the repo will trigger the workflow, and this regex validation needs to pull the code (comment trigger doesn't checkout the code) and execute the code. In this 1st job, an arbitrary change in the code could expose sensitive data, as everybody can comment in the repo and this validation needs to checkout the PR code for executing that regex. (we should use the PR branch because in other case, changes in the system can't be tested before going `main`, the only file executed from main should be the workflow yaml)

I know that we can just add a condition in the specific step to not be executed, but the second reason for adding in the 2nd job, is that the second job already has to checkout the code, so in my mind sounds like the better place:
![image](https://github.com/kedacore/keda/assets/36899226/bfe69df2-a84f-4f58-8e04-a40cb9898372)
