### ISSUE TITLE
Keda deployment is failing

### ISSUE THREAD

**Issue by ashishsahuGitHub** [kedacore/keda#4765]
Hi Team,

I am trying to install keda on gcp gke cluster through kubectl command.
**kubectl apply -f https://github.com/kedacore/keda/releases/download/v2.10.1/keda-2.10.1.yaml**

**command output:**
namespace/keda created
customresourcedefinition.apiextensions.k8s.io/clustertriggerauthentications.keda.sh created
customresourcedefinition.apiextensions.k8s.io/scaledjobs.keda.sh created
customresourcedefinition.apiextensions.k8s.io/scaledobjects.keda.sh created
customresourcedefinition.apiextensions.k8s.io/triggerauthentications.keda.sh created
serviceaccount/keda-operator created
role.rbac.authorization.k8s.io/keda-operator created
clusterrole.rbac.authorization.k8s.io/keda-external-metrics-reader created
clusterrole.rbac.authorization.k8s.io/keda-operator created
rolebinding.rbac.authorization.k8s.io/keda-operator created
rolebinding.rbac.authorization.k8s.io/keda-auth-reader created
clusterrolebinding.rbac.authorization.k8s.io/keda-hpa-controller-external-metrics created
clusterrolebinding.rbac.authorization.k8s.io/keda-operator created
clusterrolebinding.rbac.authorization.k8s.io/keda-system-auth-delegator created
service/keda-admission-webhooks created
service/keda-metrics-apiserver created
service/keda-operator created
deployment.apps/keda-admission created
deployment.apps/keda-metrics-apiserver created
deployment.apps/keda-operator created
apiservice.apiregistration.k8s.io/v1beta1.external.metrics.k8s.io created
validatingwebhookconfiguration.admissionregistration.k8s.io/keda-admission created.

while looking at status 
**kubectl get pods -n keda**
NAME                                      READY   STATUS              RESTARTS   AGE
keda-admission-5c8b9dc89f-ncqcm           0/1     ContainerCreating   0          105s
keda-metrics-apiserver-7879d5cf54-vxrpn   0/1     ContainerCreating   0          104s
keda-operator-59ff7c7bbc-66mxd            0/1     ImagePullBackOff    0          103s

Failed to pull image "ghcr.io/kedacore/keda:2.10.1": rpc error: code = Unknown desc = failed to pull and unpack image "ghcr.io/kedacore/keda:2.10.1": failed to resolve reference "ghcr.io/kedacore/keda:2.10.1": failed to do request: Head "[https://ghcr.io/v2/kedacore/keda/manifests/2.10.1":](https://ghcr.io/v2/kedacore/keda/manifests/2.10.1%22:) x509: certificate signed by unknown authority

<html>
<body>
<span><span class="ui-provider fz b c d e f g h i j k l m n o p q r s t u v w x y z ab ac ae af ag ah ai aj ak" dir="ltr">

Unable to attach or mount volumes: unmounted volumes=[certificates], unattached volumes=[certificates kube-api-access-mgctp temp-vol]: timed out waiting for the condition | FailedMount | Jul 3, 2023, 12:14:58 PM | Jul 3, 2023, 12:49:05 PM | 2 |  
-- | -- | -- | -- | -- | --
MountVolume.SetUp failed for volume "certificates" : secret "kedaorg-certs" not found | FailedMount | Jul 3, 2023, 12:12:55 PM | Jul 3, 2023, 12:43:32 PM | 23 |  
Unable to attach or mount volumes: unmounted volumes=[certificates], unattached volumes=[temp-vol certificates kube-api-access-mgctp]: timed out waiting for the condition | FailedMount | Jul 3, 2023, 12:17:12 PM | Jul 3, 2023, 12:35:32 PM | 8 |  
Unable to attach or mount volumes: unmounted volumes=[certificates], unattached volumes=[kube-api-access-mgctp temp-vol certificates]: timed out waiting for the condition | FailedMount | Jul 3, 2023, 12:30:58 PM | Jul 3, 2023, 12:30:58 PM | 1 |  

</span></span>
</body>
</html>

can someone help on this

**Comment by JorTurFer** [comment]
Hi,
Does the issue persist? Do you have any kind of proxy in your side?
`x509: certificate signed by unknown authority` looks like an error in GH or in an intermediate proxy

**Comment by tomkerkhove** [comment]
Also, would you mind trying to use 2.11 please?

**Comment by ashishsahuGitHub** [comment]
Hi @JorTurFer  @tomkerkhove ,
Thanks for your reply.
I've solved it by pushing the keda images in our container registry and giving the path of registry in yaml file.
KEDA deployment was completed.

**Comment by JorTurFer** [comment]
Do you have any kind of proxy in the middle between your clusters and registries? Just to understand what heppened 😄 
Could we close this issue?

**Comment by ashishsahuGitHub** [comment]
Hi @JorTurFer ,
We do have a firewall which didn’t allow to access Internet.
For our cluster and registry we do have access permission, no proxy
