### ISSUE TITLE
Summer Vacation Notice - Extended Response Time

### ISSUE THREAD

**Issue by JorTurFer** [kedacore/keda#4773]
Dear KEDA Community,

We hope this message finds you well and that you're enjoying the ongoing advancements in the KEDA project. As the proud maintainers of the KEDA project, we wanted to inform you about an upcoming change in our availability during the summer months.

During the months of July and August, the KEDA team will be taking some well-deserved summer vacations. As a result, we anticipate that our response time to GitHub issues and requests may be longer than usual. We believe that taking this time off will help us recharge and return with renewed energy and enthusiasm to continue improving the KEDA project.

We want to emphasize that we remain committed to supporting and maintaining the project, and we will make every effort to minimize any disruptions during this period. However, please understand that there might be delays in addressing your GitHub issues, pull requests, and other inquiries.

We kindly request your understanding and patience during this time. We value your contributions and feedback, and we assure you that we will address all outstanding matters as soon as we return from our vacations. We highly encourage you to continue engaging with the KEDA community, as there are many experienced and knowledgeable members who may be able to provide assistance in our absence.

In the meantime, we encourage you to refer to our comprehensive documentation, which covers various aspects of KEDA and may help address any immediate concerns or questions you may have.

We will be posting an official notice in our GitHub repository to remind the community about our upcoming vacation period and extended response time. Additionally, we will update our GitHub templates and provide an estimated timeline for responses to manage expectations effectively.

We sincerely apologize for any inconvenience this may cause and appreciate your understanding. Your continued support and patience mean a lot to us, and we are confident that we will return with even greater enthusiasm to further enhance the KEDA project.

Thank you for being a valued member of the KEDA community!

Warm regards

**Comment by tomkerkhove** [comment]
We will hold our last standup on Tuesday, July 18th before starting summer vacation for the rest of summer.

Standup will re-instate on September 12th, right in time for KEDA 2.12! If you are subscribing to our [Google calendar](https://calendar.google.com/calendar?cid=bjE0bjJtNWM0MHVmam1ob2ExcTgwdXVkOThAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ) than you should already received notifications.
