### ISSUE TITLE
Use KEDA to feed metric info to self-managed HPAs

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda#480]
One thing that KEDA does well is handle the HPA creation based on the metrics that it exposes.

However, some customers still want to write the HPA themselves, but use the metrics from KEDA.

As far as I know, we do not support this because the metrics are only being tracked based on the deployed scaled object.

It would be good if we would provide a middleground where we could measure a given metric (`MetricMeasurement` or so) and consume it via our own HPA.

**Comment by tomkerkhove** [comment]
I see this as KEDA being active in different layers of the Serverless -> PaaS -> IaaS stack.

How it is today we are fairly PaaS based given they just tell us how to scale and we'll handle it for them, while for some they'll want to have the scaling control but just want the metrics.

**Comment by tomkerkhove** [comment]
Thoughts @jeffhollan?

**Comment by zroubalik** [comment]
@tomkerkhove are there any specific requests to support this?

What are the specific features of HPA that customers want to write themselves?

**Comment by tomkerkhove** [comment]
Let's say my team created a scaled object for a Service Bus queue and another team wants to re-use that same metric but they want to write their HPA themselves as they already do that for their other apps. 

Can we do that today? If so, we might want to document that but add a caveat the metric will be gone if the ScaledObject will be removed.

However, this idea might be a bridge too far as you still need to ask KEDA to start monitoring the metric, so that makes less sense - Happy to close in that case.

**Comment by zroubalik** [comment]
I am not very much inclined to this, as we want to manage HPAs from KEDA controller (but this feature would require just a small modification).
I think we can discuss more this if there are more requests on this specific feature.

**Comment by tomkerkhove** [comment]
Sounds good to me, nothing urgent here!
