### ISSUE TITLE
Kafka scaler support SSL and SASL

### ISSUE THREAD

**Issue by jeffhollan** [kedacore/keda#481]
Not quite sure what would be required here but a user wants to use KEDA but has kafka secured with SSL and SASL. I don't know if our scaler would work with this already

**Comment by iyacontrol** [comment]
pr [https://github.com/kedacore/keda/pull/486](url)

**Comment by iyacontrol** [comment]
hi @tomkerkhove @jeffhollan 
at present, sarama package not support sasl_ssl.

**Comment by jeffhollan** [comment]
This is awesome @iyacontrol !  Thank you!

**Comment by jeffhollan** [comment]
Resolved with #486
