### ISSUE TITLE
Readiness/Liveliness Scaler/trigger 

### ISSUE THREAD

**Issue by kennyparsons** [kedacore/keda#4816]
### Scaler Source

Deployment

### Scaling Mechanics

The readiness and liveliness health checks are wildly used and well documented. 
Proposed scaler: 
A readiness probe and/or liveliness probe trigger for the deployment be implemented. When a deployment has no pods available (either from a readiness probe, liveliness probe, or both - depending on how the engineer uses them), KEDA scales the deployment up and down, based on existing scale strategies in use with other scalers and triggers. 

### Authentication Source

NA.

**Comment by tomkerkhove** [comment]
How do you distinguish if a pod has 0 instances through readiness/liveness probes and if it should scale?

I'm not sure if I get the use-case here, sorry

**Comment by tomkerkhove** [comment]
Basically you want to scale based on your downstream dependencies, similar to https://github.com/kedacore/keda/issues/1932?
