### ISSUE TITLE
Provide capability to configure Prometheus API Path

### ISSUE THREAD

**Issue by SubatomicHero** [kedacore/keda#4819]
### Report

The prometheus scaler has a hardcoded api endpoint, `/api/v1/query`. Some hosted prometheus vendors use a different path. E.g. Grafana uses `/api/prom`

### Expected Behavior

A query should be made to `https://grafana-host/api/prom`

### Actual Behavior

A query is being made to `https://grafana-host/api/prom/api/v1/query`

### Steps to Reproduce the Problem

1. Create a prometheus scaler with basic auth
2. Set the `serverAddress` to `https://grafana-host/api/prom`
3. See the errors

### Logs from KEDA operator

```
https://grafana.net/api/prom/api/v1/query?query=%28sum%28irate%28node_cpu_seconds_total%7Bmode%21%3D%22idle%22%2Ccluster%3D%22aks-gameserver-DEV-EUN%22%7D%5B5m%5D%29+%2A+on+%28node%29+group_left%28namespace%29+max+by+%28node%29+%28kube_node_labels%7Blabel_platform_antstream_com_service%3D%22gameservers%22%7D%29%29+%2F+on%28instance%2C+node%29+group_left+sum%28%28irate%28node_cpu_seconds_total%7Bcluster%3D%22aks-gameserver-DEV-EUN%22%7D%5B5m%5D%29+%2A+on+%28node%29+group_left%28namespace%29+max+by+%28node%29+%28kube_node_labels%7Blabel_platform_antstream_com_service%3D%22gameservers%22%7D%29%29%29%29+%2A+100&time=2023-07-24T14:43:05Z\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
```

### KEDA Version

2.11.1

### Kubernetes Version

1.26

### Platform

Microsoft Azure

### Scaler Details

Prometheus

**Comment by zroubalik** [comment]
What is the status on this? I can see the linked PR was closed for unknown reasons.
