### ISSUE TITLE
Add Trigger to stop scaling

### ISSUE THREAD

**Issue by matan-legit** [kedacore/keda#4823]
### Proposal

i want to have a way to provide a trigger that above it's threshold, lets say database cpu utillization scaling will stop

### Use-Case

let's say my pods handle messages from kafka topics, the pods scale up but the DB is a bottleneck, i don't want to scale more pods if the DB cpu util is over 90% even if the queue length is above the threshold

### Is this a feature you are interested in implementing yourself?

Maybe

**Comment by JorTurFer** [comment]
I think that this incoming PR will help: https://github.com/kedacore/keda/pull/4821

**Comment by matan-legit** [comment]
this looks like it may solve my issue :) thanks @JorTurFer

**Comment by tomkerkhove** [comment]
> I think that this incoming PR will help: #4821

It helps but does not solve it imo

I think https://github.com/kedacore/keda/issues/3949 comes close to it
