### ISSUE TITLE
Support GCP secret manager for scaler Trigger Authentication

### ISSUE THREAD

**Issue by neelanjan00** [kedacore/keda#4831]
### Proposal

GCP Secret Manager is a storage system for API keys, passwords, certificates, and other sensitive data. It provides a central place and single source of truth to manage, access, and audit secrets across Google Cloud. KEDA should provide support for using GCP Secret Manager for retrieving secret data to be used for scaler trigger authentication. 

### Use-Case

- To use GCP Secret Manager for retrieving secret data to be used by scaler trigger authentication.

### Is this a feature you are interested in implementing yourself?

Yes

**Comment by JorTurFer** [comment]
Hey @neelanjan00 ,
This is an awesome idea to be aligned with the feature that we already support from Azure . Are you willing to contribute with it?
If yes, remember that for e2e tests, you will have to open a PR also to the testing-infrastructure repo 😄

**Comment by neelanjan00** [comment]
Hi Jorge, I am indeed planning to contribute to the feature. After I raise the PR, I will need slight guidance on how to get started with the E2E tests.

**Comment by JorTurFer** [comment]
> Hi Jorge, I am indeed planning to contribute to the feature. After I raise the PR, I will need slight guidance on how to get started with the E2E tests.

Nice! ❤️ 
Just let us know when you have questions or need help 😄

**Comment by liavst2** [comment]
+1 for this one.
Any update on progress?

**Comment by neelanjan00** [comment]
Hi @liavst2 sorry I had been away on vacation for a while and couldn't close this. @JorTurFer can we merge the PR? We can add unit tests later perhaps since a few other trigger auth providers also lack unit tests.

**Comment by zm-alex** [comment]
Hi @JorTurFer , is there also a similar feature proposal for AWS Secrets Manager?

**Comment by JorTurFer** [comment]
> is there also a similar feature proposal for AWS Secrets Manager?

Yeah, it is indeed: https://github.com/kedacore/keda/pull/5162
