### ISSUE TITLE
Rabbitmq scaler be used with regexes with amqps protocol

### ISSUE THREAD

**Issue by matan-legit** [kedacore/keda#4832]
### Proposal

similar to [743](https://github.com/kedacore/keda/issues/743) i want to be able to use regex on queue names, this was implemented only on http protocol. As Keda doesn't support https in this scaler i can't use this protocol. (this might be another good feature request)

### Use-Case

use regex in queue name with amqps protocol

### Is this a feature you are interested in implementing yourself?

No

**Comment by JorTurFer** [comment]
Hi,
Regex feature can't be ported to AMQP because AMQP doesn't support it. From management pov, amqp is poorer that http.

> As Keda doesn't support https in this scaler

What do you mean? You can just set a URL with HTTPS and it will work if the certificate is valid. In case of self-signed certificates, you still can add them to KEDA's trusted store: https://keda.sh/docs/2.11/operate/security/#register-your-own-ca-in-keda-operator-trusted-store

**Comment by matan-legit** [comment]
@JorTurFer when i put a url with https it didn't work for me but i might've done something wrong
also i saw this pr closed: https://github.com/kedacore/keda/pull/1073

**Comment by JorTurFer** [comment]
Could you share the https ScaledObject that you are using?

**Comment by JorTurFer** [comment]
Here is the problem:
![image](https://github.com/kedacore/keda/assets/36899226/1f916895-fbeb-4778-bf9c-282d2f0c842e)

It seems that AWS doesn't support http protocol and sadly, amqp doesn't support discovery methods (like listing queues). 
I think that at this moment this issue isn't doable :(

**Comment by JorTurFer** [comment]
@coderanger , do you know if amqp has started to support listing? I don't think so, but just asking...

**Comment by JorTurFer** [comment]
Just recapping:
- You have tried using `https://user:password@b-87ds8765-abcd-4123-sdb9-d187172cf294.mq.us-east-1.amazonaws.com:15671/` (with the https and port)
- You have tried using `https://user:password@b-87ds8765-abcd-4123-sdb9-d187172cf294.mq.us-east-1.amazonaws.com/` (with the https and without port)

Could you give another try an share KEDA error on those cases? In my personal experience, I have had issues with some AWS certificates, maybe it's related with that 🤔

**Comment by JorTurFer** [comment]
> another unrelated issue is, when i edit the secret for the connection url i need to redeploy the scaled object for the configuration to apply, it would be nice if it applied automatically.

In theory, the ScaledObject is rebuilt on each error, so the change in secrets should be read once the scaler returns an error. In normal operation we don't watch the secrets because watching all the configuration sources could be a problem to manage them, but it's a good idea. If you open an issue requesting it, we can discuss about the topic 😄

**Comment by matan-legit** [comment]
```
│ 2023-08-01T09:03:32Z    ERROR    scale_handler    error getting scale decision    {"scaledObject.Namespace": "default", "scaledObject.Name": "code-scanners-scaledobject", "scaler": "rabbi │
│ tMQScaler", "error": "error inspecting rabbitMQ: Get \"https://user:password@@b-87ds8765-abcd-4123-sdb9-d187172cf294.mq.us-east-1.amazonaws.com:15671/api/queues/%!F(MISSING)/Legit.Common.Q │
│ ueue.QueueMessage%5B%!B(MISSING)asopdkaposd.Shared.djoaisjdo.asidjiojio%!C(MISSING)+CodeScanners.Shared%!D(MISSING)%!D(MISSING)%!C(MISSING)+Legit.Common_OfflineConsumers\": │
│  context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}                                                                                                               │
│ github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).getScaledObjectState                                                                                                                │
│     /workspace/pkg/scaling/scale_handler.go:588                                                                                                                                             │
│ github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).checkScalers                                                                                                                        │
│     /workspace/pkg/scaling/scale_handler.go:236                                                                                                                                             │
│ github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).startScaleLoop                                                                                                                      │
│     /workspace/pkg/scaling/scale_handler.go:175                                                                                                                                             │
│                                                                                                                                                                                             │
```

**Comment by matan-legit** [comment]
btw @JorTurFer on this error it doesn't seem to be rebuilding the SO i still need to edit something on it for it to be rebuilt after i change the secret

**Comment by matan-legit** [comment]
actually when im doing no port it sends: error inspecting rabbitMQ: error requesting rabbitMQ API status: 404 Not Found

**Comment by matan-legit** [comment]
ok no port config actually worked for me 🥳  i had misconfiguration on the queuename side, looks like regex is also working. 
thanks for all the help @JorTurFer :) closing the issue

**Comment by JorTurFer** [comment]
Nice! Happy to help :)
