### ISSUE TITLE
On-demand skipping ResolveContainerEnv for security consideration

### ISSUE THREAD

**Issue by kangteng525** [kedacore/keda#4837]
### Proposal

KEDA will try to resolve all ENVs from the target deployment, normally in Prod env, it will restrict the KEDA permission by setting `KEDA_RESTRICT_SECRET_ACCESS` to "true" so as not able to get secret from all other namespaces than KEDA itself. 

So it will cause issue if the env has defined `valueFrom` `secretKeyRef`, error message like: 

> error resolving secrets for ScaleTarget: error resolving secret name &SecretKeySelector{LocalObjectReference:LocalObjectReference{Name:es-creds,},Key:user,Optional:nil,} for env ELASTICSEARCH_USER in namespace xxxx

Suggestion:

To alleviate this issue, it would be beneficial to allow users the option to skip ENV resolution from the target deployment on-demand. This would prevent the above-mentioned error from occurring, particularly for users who are not utilizing the "xxxFromEnv" in their Scalers.

This on-demand skipping of ENV resolution would make KEDA more flexible and robust, especially in production environments with restricted permissions.

### Is this a feature you are interested in implementing yourself?

Yes

**Comment by JorTurFer** [comment]
Hello
What KEDA version are you using? I think that [this commit solves the case](https://github.com/kedacore/keda/commit/406c358214529f4009ecfbd10dbbf55f8670db17#diff-8c546d2eb95a297e897b699d6103324875de92d89c7e2519182c011c68317b57) because in case of not being in the allowed namespace, KEDA won't check the secret

**Comment by kangteng525** [comment]
Hello Jorge,

Great, this is exactly what we want, so we will try to upgrade to v2.11.1

Thanks,
Kevin

**Comment by JorTurFer** [comment]
Nice! 
I close the issue because the fix is already released, after testing it, if you still think that it's not solved, just reopen the issue 😄
