### ISSUE TITLE
Standardize prometheus naming convention for keda metrics

### ISSUE THREAD

**Issue by pragmaticivan** [kedacore/keda#4854]
### Proposal

Because of issues with Prometheus remote writers, it's ideal that we follow Prometheus suffix conventions for counters. If not followed strictly, external vendors supporting Prometheus remote writers might receive the metric as a `Gauge` instead.

Context:
* https://prometheus.io/docs/practices/naming/
* https://docs.newrelic.com/docs/infrastructure/prometheus-integrations/install-configure-remote-write/set-your-prometheus-remote-write-integration/#mapping
* https://github.com/prometheus/client_golang/issues/725
* https://github.com/thanos-io/thanos/pull/3992/filesPrometheus

### Use-Case

Vendors such as newrelic can use Prometheus metrics via remote writer properly.

### Is this a feature you are interested in implementing yourself?

Maybe

**Comment by pragmaticivan** [comment]
We might need to deprecate existing metrics and create new ones.

**Comment by pragmaticivan** [comment]
@JorTurFer, if approved, I can probably take this one.

**Comment by JorTurFer** [comment]
WDYT @kedacore/keda-core-contributors ?

**Comment by zroubalik** [comment]
@pragmaticivan could you please write down the list of metrics to be changed. The old and new name. Thanks!

**Comment by pragmaticivan** [comment]
<img width="1497" alt="Screenshot 2023-08-28 at 4 05 10 PM" src="https://github.com/kedacore/keda/assets/301291/dc1cdf1a-f867-4889-85b2-9ddc69180796">
@zroubalik afaik, only the ones marked as red.

Although I was thrown off by the naming of some being gauge instead of histogram.

**Comment by pragmaticivan** [comment]
I also noticed some of the HELP (descriptions) don't match the description in the doc.

**Comment by pragmaticivan** [comment]
Possible steps:

1. Update Description for affected metrics to include a prefix like: `Deprecation Warning - This metric is deprecated and replaced with 'new_metric'`
2. Create new metrics and add increments right below the code for the existing ones.
3. Update docs (include deprecation notice)
4. Update Grafana template

**Comment by tomkerkhove** [comment]
Sounds like good execution steps imo, are you willing to contribute this?

For 2), let's make sure we increment new metrics first though.

**Comment by pragmaticivan** [comment]
Yes, I can take that one.

**Comment by pragmaticivan** [comment]
After taking a deeper look yesterday, `keda_scaler_errors` vs `keda_scaler_errors_total` seems to be the same metric, called in the same place. The only difference is that `keda_scaler_errors` has the `labels` in place, but technically you could use this one with the same intent `(sum)` so I don't think we need the counter for `all` since we already have the other metric.

**Comment by pragmaticivan** [comment]
This issue might be obsolete if this is available: https://github.com/kedacore/keda/pull/4860/files 🎉

**Comment by tomkerkhove** [comment]
Well not really because Prometheus metrics are not being removed; we're adding it next to each other :)

**Comment by JorTurFer** [comment]
This is in progress
