### ISSUE TITLE
Track the impact of HashiCorp license MPL -> BUSL

### ISSUE THREAD

**Issue by JorTurFer** [kedacore/keda#4875]
This issue is for tracking the usage of HashiCorp Go packages and software products in the KEDA project.

xref: https://github.com/cncf/foundation/issues/617

**Comment by JorTurFer** [comment]
we support HashiCorp Vault as secrets source (we just read values from there as a client), due to it, we use these deps:
```
github.com/hashicorp/vault/api
github.com/hashicorp/errwrap v1.1.0 // indirect github.com/hashicorp/go-cleanhttp v0.5.2 // indirect 
github.com/hashicorp/go-hclog v1.3.0 // indirect 
github.com/hashicorp/go-multierror v1.1.1 // indirect 
github.com/hashicorp/go-retryablehttp v0.7.2 // indirect 
github.com/hashicorp/go-rootcerts v1.0.2 // indirect 
github.com/hashicorp/go-secure-stdlib/parseutil v0.1.7 // indirect 
github.com/hashicorp/go-secure-stdlib/strutil v0.1.2 // indirect 
github.com/hashicorp/go-sockaddr v1.0.2 // indirect 
github.com/hashicorp/go-uuid v1.0.3 // indirect 
github.com/hashicorp/hcl v1.0.0 // indirect
```

We also deploy a HashiCorp Vault during e2e test to test the integration (we use helm chart for it). We only use it locally within the testing cluster and we remove it after the e2e test. 

For managing e2e test infrastructure we use terraform as well. We manage the infra from its own repo and terraform is executed via GH Action (using an Azure Blob Storage as backend).

I think that we aren't affected but we should stay tuned about CNCF updates regarding with this topic

**Comment by zroubalik** [comment]
@JorTurFer please update

**Comment by JorTurFer** [comment]
I don't have any update xD

**Comment by JorTurFer** [comment]
Let's keep this opened
