### ISSUE TITLE
KEDA CI is updating the 1.0.0 image

### ISSUE THREAD

**Issue by jeffhollan** [kedacore/keda#489]
Was trying to figure out why I didn't hit this bug before when pinned to 1.0.0 and realized the 1.0.0 image was updated last night.  I suspect it's actually grabbing a mirror of master - which it shouldn't do.  1.0.0 should remain a snapshot of the code as of whenvever last Tuesday was.  New releases should automatically update master.  And then we manually add `1.0.1` or `1.1.0` or whatever.

// cc @ahmelsayed @anirudhgarg @SatishRanjan 

Related to #487

**Comment by tomkerkhove** [comment]
Woops 😅

**Comment by ahmelsayed** [comment]
Yeah.... I wanted to discuss what we want to do there. I was leaning more towards increment the version as Jeff suggested. Didn't expect there will be a break as I was just merging doc PRs.

**Comment by jeffhollan** [comment]
Not a huge deal and easy fix. Yeah we can sort it out next week.

**Comment by iyacontrol** [comment]
hi @jeffhollan @tomkerkhove @ahmelsayed  Why not set up to build a new image only when tagging, then the form of the tag is similar to v1.0.1? master branch can always be in dev and merge stable future.

**Comment by jeffhollan** [comment]
Yes I think that’s what we’re leaning towards. When we tag / release we generate a new tag. When a PR is merged it just automatically updates the “master” tag but no others.
