### ISSUE TITLE
ScaledObject no being cached correctly at all times

### ISSUE THREAD

**Issue by gauron99** [kedacore/keda#4955]
This is a tracking issue of a bug for which a workaround has been implemented in number of places for this time until its resolved globally.

## What happens
ScaledObject is sometimes not cached correctly -> for example the metrics are an empty list or the `.Status.ScaleTargetGVKR` is nil

## Workaround
A workaround has been implemented in a number of places. See below.

- `pkg/scaling/scale_handler.go` in `func (h *scaleHandler) getTrueMetricArray()`
- `pkg/scaling/resolver/scale_resolvers.go` in `func ResolveScaleTargetPodSpec()`

## Other info
initial related issue [link](https://github.com/kedacore/keda/issues/4389) 

/kind bug

**Comment by BehbudSh** [comment]
Any updates on this issue? We are facing a problem with a scaling of the Production instance

**Comment by nrukavkov** [comment]
The same here

**Comment by nuved** [comment]
Hey 
The same here, 
After migrating the k8s cluster from 1.22.6 to 1.23.17 and upgrading keda from 2.8.2 to 2.9.4, we've faced the same issue. 
keda is connecting to rabbitmq cluster and based on the count of messages in the queue, will adjust the HPA. 

I even tried to delete the helm chart of keda and install the keda from scratch but still  I can see the same errors.

**Comment by gauron99** [comment]
@zroubalik ^

**Comment by Woodencarl** [comment]
We are facing the same issue. :(

**Comment by dontbesatisfied** [comment]
I'm facing this issue.
