### ISSUE TITLE
V1.0.0 - ScaledObject isn't removed when helm template is deleted.

### ISSUE THREAD

**Issue by sc-chad** [kedacore/keda#496]
## Expected Behavior
All definitions and objects are removed when the helm template is deleted.

## Actual Behavior
CustomResourceDefinition scaledobjects.keda.k8s.io 
CustomResourceDefinition triggerauthentications.keda.k8s.io

These aren't removed and an error is thrown upon reinstall: ```Error: customresourcedefinitions.apiextensions.k8s.io "scaledobjects.keda.k8s.io" already exists```

## Steps to Reproduce the Problem

  1.  Install keda via helm
  2.  helm delete keda --purge
  3.  Try to reinstall via helm

## Steps to work around

  1. kubectl delete CustomResourceDefinition scaledobjects.keda.k8s.io
  2. kubectl delete CustomResourceDefinition triggerauthentications.keda.k8s.io

## Specifications

  - **Version:** *1.0.0*
  - **Platform:** *Please elaborate*
  - **Scaler(s):** *Please elaborate*

**Comment by ahmelsayed** [comment]
The uninstall steps are documented here https://keda.sh/deploy/#uninstalling-keda 

As far as I know that's the expected flow for helm charts that bring in CRDs based on https://github.com/helm/helm/issues/4489 and https://github.com/helm/helm/issues/4440

**Comment by sc-chad** [comment]
Thanks @ahmelsayed that's good enough for me.  Appreciate the response.
