### ISSUE TITLE
TriggerAuthentication Vault Integration default values

### ISSUE THREAD

**Issue by BojanZelic** [kedacore/keda#4965]
### Proposal

Ability to set default values on a TriggerAuthentication/ClusterTriggerAuthentication resources when authenticating to vault ( this same change could potentially apply to other keyvaults.

### Use-Case

Currently when trying to use TriggerAuthentication, we have to re-declare alot of static values that don't change within the same cluster meaning we have to duplicate configurations when they're mostly the same across triggerauth mechanisms;

Take a look at the vault config section & the current definition:
```
hashiCorpVault:                                     # Optional.
  address: {hashicorp-vault-address}                # Required.
  namespace: {hashicorp-vault-namespace}            # Optional. Default is root namespace. Useful for Vault Enterprise
  authentication: token | kubernetes                # Required.
  role: {hashicorp-vault-role}                      # Optional.
  mount: {hashicorp-vault-mount}                    # Optional.
  credential:                                       # Optional.
    token: {hashicorp-vault-token}                  # Optional.
    serviceAccount: {path-to-service-account-file}  # Optional.
  secrets:                                          # Required.
  - parameter: {scaledObject-parameter-name}        # Required.
    key: {hasicorp-vault-secret-key-name}           # Required.
    path: {hasicorp-vault-secret-path}              # Required.
```

We should be able to set ENV variables in the operator to automatically apply defaults for a significant portion of the above configuration so that the final looks like this:

```
hashiCorpVault:                                     # Optional.
  address: {hashicorp-vault-address}                # Optional. set via ENV: $VAULT_ADDR
  namespace: {hashicorp-vault-namespace}            # Optional. set via ENV: $VAULT_NAMESPACE
  authentication: token | kubernetes                # Optional. set via ENV: $VAULT_AUTH
  role: {hashicorp-vault-role}                      # Optional. set via ENV: $VAULT_ROLE
  mount: {hashicorp-vault-mount}                    # Optional. set via ENV: $VAULT_MOUNT (or $VAULT_PATH)
  credential:                                       # Optional.
    token: {hashicorp-vault-token}                  # Optional. set via ENV: $VAULT_TOKEN
    serviceAccount: {path-to-service-account-file}  # Optional. set via ENV: $VAULT_JWT_PATH
  secrets:                                          # Required.
  - parameter: {scaledObject-parameter-name}        # Required.
    key: {hasicorp-vault-secret-key-name}           # Required.
    path: {hasicorp-vault-secret-path}              # Required.
```

so that when we use it, we only have to define the secrets like:
```
hashiCorpVault:                                     # Optional.
  secrets:                                          # Required.
  - parameter: {scaledObject-parameter-name}        # Required.
    key: {hasicorp-vault-secret-key-name}           # Required.
    path: {hasicorp-vault-secret-path}              # Required.
```

### Is this a feature you are interested in implementing yourself?

Yes

**Comment by tomkerkhove** [comment]
Given the trigger authentication is not scoped to the app workload; where would you expect these environment variables to come from? If you're expecting them to come from the KEDA installation, how would you see this work when somebody wants to use multiple vaults?

**Comment by BojanZelic** [comment]
This is just for setting defaults if not specified; I would expect them to come from the KEDA installation (specifically the operator); Having a cluster talk to multiple vaults isn't a common use-case in my experience; It's usually 1 vault that multiple Kubernetes clusters connect to; or 1 vault for each cluster; Not 1 cluster talking to many vaults.

Either way though that would still be possible, the ENV variables would just be defaults if the override values aren't provided;

ex
```
hashiCorpVault:                                     # Optional.
  address: {hashicorp-vault-address}  # Optional or defaults to ENV: $VAULT_ADDR value on the keda-operator pod
```

There's other projects that have similar functionality:

vault-agent-injector by hashicorp; Injects vault sidecar & init containers into pods and exposes secrets as ENV variables; It allows setting vault configs via annotations per pod, or use defaults in the webhook via ENV variables if not specified; 

* ex: https://github.com/hashicorp/vault-k8s/blob/1b1d69e438d54aa5442782a5ed66751877ca6d03/subcommand/injector/flags.go#L60

vault-secrets-webhook by banzaicloud has the same functionality, set vault defaults via ENV variables, overridable via annotations: 
* ex: https://bank-vaults.dev/docs/mutating-webhook/annotations/

**Comment by tomkerkhove** [comment]
Created https://github.com/kedacore/keda/issues/5233 to consolidate proposals
