### ISSUE TITLE
No matches for kind "HorizontalPodAutoscaler" in version "autoscaling/v2beta2"

### ISSUE THREAD

**Issue by virtual-deepak** [kedacore/keda#4969]
Hi,

I have deployed Azure Kubernetes Service with version 1.26.6. I executed below kubectl apply command -

`kubectl apply -f https://github.com/kedacore/keda/releases/download/v2.8.0/keda-2.8.0.yaml`

After deployment, the keda-operator logs provided with below error - 
_2023-09-13T14:29:43Z    ERROR   controller-runtime.source       if kind is a CRD, it should be installed before calling Start   {"kind": "HorizontalPodAutoscaler.autoscaling", "error": "no matches for kind \"HorizontalPodAutoscaler\" in version \"autoscaling/v2beta2\""}_

As I see in the KEDA [documentation for version 2.8.0](https://keda.sh/docs/2.8/deploy/), I see below note - 
NOTE: KEDA requires Kubernetes cluster version 1.16 and higher

In my case, as mentioned above, I already have 1.26.6 version which is higher than mentioned in the documentation. 
Any reason why must be failing? Appreciate your response on this.

P.S.: This is working Kubernetes Service with version 1.25.6.

Thanks!
Deepak Agarwal

**Comment by tomkerkhove** [comment]
Kubernetes v1.26 is not supported for KEDA v2.8, see [compatibility matrix](https://keda.sh/docs/latest/operate/cluster/#kubernetes-compatibility).
