### ISSUE TITLE
Metadata annotation for the CustomResourceDefinition "scaledjobs.keda.sh" is invalid

### ISSUE THREAD

**Issue by edubois10** [kedacore/keda#4988]
### Report

I want to install Keda in my OpenShift cluster v4.10.
I did the following:
`oc apply -f https://github.com/kedacore/keda/releases/download/v2.11.2/keda-2.11.2.yaml`
And the output was the following:
```
namespace/keda created
...
The CustomResourceDefinition "scaledjobs.keda.sh" is invalid: metadata.annotations: Too long: must have at most 262144 bytes
```

So the CRD is not created. However, If I manually create the object it works...

### Expected Behavior

That the CustomResourceDefinition "scaledjobs.keda.sh" is created

### Actual Behavior

CustomResourceDefinition "scaledjobs.keda.sh" is not created

### Steps to Reproduce the Problem

1. oc apply -f https://github.com/kedacore/keda/releases/download/v2.11.2/keda-2.11.2.yaml

### Logs from KEDA operator

```
example
```

### KEDA Version

None

### Kubernetes Version

None

### Platform

None

**Comment by zroubalik** [comment]
Please follow installation instructions: https://keda.sh/docs/2.11/deploy/#install-2
