### ISSUE TITLE
Remove prometheus dependency when scaling from 0 to min replicas

### ISSUE THREAD

**Issue by Kirill-Garbar** [kedacore/keda#5009]
### Proposal

Currently when we remove annotation `autoscaling.keda.sh/paused-replicas: "0"` from scaledObject and want our deployment to scaleup to minimum replicas from 0, prometheus needs to be up and running. If prometheus is down, then scaling up to min replicas doesn't happen.

Is it possible to scale to minReplicas from 0 anyway even if prometheus is down?

We use Keda 2.9 and prometheus trigger.

### Use-Case

We scale down environments to 0 at night and noticed behaviour that our application can't be scaled up to minReplicas from 0 when prometheus is not available.
We would like to scale up the application to minReplicas even if prometheus is not available.

### Is this a feature you are interested in implementing yourself?

No

**Comment by JorTurFer** [comment]
Hi,
There were some changes in the pause behaviour on v2.11, optimizing how it works. Does this happen on v2.11 too?

**Comment by zroubalik** [comment]
I think the problem is that the Prometheus instance is down - ScaledObject will report failure and won't do any scaling.

**Comment by Kirill-Garbar** [comment]
@JorTurFer I expected something like this, but we could not use newer version because of older k8s version. I will have a look at the changelog at least. 2.11 requires k8s 1.25 and upgrade to 1.25 is pretty hard because of PSP removal.

@zroubalik Yes, it look like this. Keda just doesn't do any scaling but in my opinion it is not necessary to have prometheus up and running to have min replicas of the application after pause.

However maybe it was done by intention and I am missing something.

**Comment by JorTurFer** [comment]
KEDA >= v2.9 works on any k8s >= v1.23. The suggested versions is because we support N-2 versions to reduce the support matrix (otherwise it'd be imposible), but you are safe using KEDA v2.11 (or even tomorrow's release v2.12). 
BTW, I can't guarantee if upgrading will remove prometheus dependency because I don't remember the whole change, but it maybe do it. In any case, although the prometheus isn't required for creating the HPA, it won't work and that's why we don't create the HPA or scale the workload. I'm not sure if we should change that behavior, tbh

**Comment by Kirill-Garbar** [comment]
@JorTurFer Keda v2.11 doesn't work on k8s 1.24, that we have at the moment => I can't easily check the behaviour, but I will try to do it. No problem with this support matrix. I am not blaming or complaining.

I will check the behaviour on Keda v2.11 and come back with the answer.

**Comment by JorTurFer** [comment]
No no, I'm saying that event though the support matrix says that it's not supported, I'm quite sure that it works. The support matrix means the versions that we have tested for a specific KEDA versions, but KEDA can run on other versions if there isn't breaking changes in the APIs, and IIRC, the last breaking change in the API was in k8s v1.23, that's why I said that

**Comment by Kirill-Garbar** [comment]
No, it is explicitly defined that earlier version is not supported: https://github.com/kedacore/charts/blob/v2.10.1/keda/Chart.yaml#L7

**Comment by JorTurFer** [comment]
f**k, that's true...
We reverted that requirement on v2.11: https://github.com/kedacore/charts/blob/v2.11.0/keda/Chart.yaml#L7

**Comment by Kirill-Garbar** [comment]
I checked the behaviour of Keda 2.11.2 - it behaves the same.
So returning to the main question.

I pause autoscaling with the annotation `autoscaling.keda.sh/paused-replicas: "0"` to scaledObject  - Keda scales deployment to zero replicas. After I remove annotation Keda doesn't scale up the deployment, because prometheus is not available (I use only prometheus triggers). In my opinion this behaviour is not normal, because scaling from 0 to minReplicas should not depend on prometheus availability. Keda doesn't need any metrics at this moment. I think that it is true for all scalers.

If this proposal to change the behaviour doesn't contradict the architecture of Keda, it makes sense to implement this change.

What do you think?

I am asking, because if somebody implements the change, opens PR and then gets objections from Keda architects, it would not be nice :) I would like to come to an agreement.

**Comment by JorTurFer** [comment]
I'm not 100% sure about this. From one side, I agree with you in the part of KEDA shouldn't need the upstream available for scaling to minReplicas from paused (I don't see this for all the cases, just from paused).
In the other side, I'm not totally sure about the possible side effects of this change.
@tomkerkhove @zroubalik ? any thought?

**Comment by zroubalik** [comment]
I am not 100% confident as well. There might be side effects, that might not be nice.

@Kirill-Garbar have you tried setting `fallback` insted?
