### ISSUE TITLE
azure pipelines scaler Federated Workload identities

### ISSUE THREAD

**Issue by daandupauinspark** [kedacore/keda#5013]
### Proposal

Add the ability to use Federated Workload identities as an authentication source with the Keda scaler.

### Use-Case

It is possible to create an app registration that has access to your azure devops organization.
This can be used to read out the pipeline job queue.

This would remove the necessity of implementing an PAT token Lifecycle system.

### Is this a feature you are interested in implementing yourself?

No

**Comment by tomkerkhove** [comment]
Is this officially supported through workload identity?

**Comment by JorTurFer** [comment]
> Is this officially supported through workload identity? As far as I know it is not

Yes for the API, it's in public preview AFAIK

**Comment by JorTurFer** [comment]
[This PR](https://github.com/kedacore/keda/pull/4867) is on-going, but we need to prepare the infra for it

**Comment by ezYakaEagle442** [comment]
@tomkerkhove regardinng [https://learn.microsoft.com/en-us/azure/aks/keda-about#add-on-limitations](https://learn.microsoft.com/en-us/azure/aks/keda-about#add-on-limitations) does this mean that the KEDA add-on in AKS  does already supports Entra ID Workload Identity for azure pipelines ?

Entra ID Workload Identity looks not supported yet in ACA : [https://learn.microsoft.com/en-us/azure/container-apps/scale-app?pivots=azure-cli#authentication-1](https://learn.microsoft.com/en-us/azure/container-apps/scale-app?pivots=azure-cli#authentication-1) , sas also [https://github.com/microsoft/azure-container-apps/issues/592](https://github.com/microsoft/azure-container-apps/issues/592)

**Comment by tomkerkhove** [comment]
We don't offer support for AKS/Container Apps, it is best to open issues/support ticket to learn more as we do not maintain that.

**Comment by JorTurFer** [comment]
[This feature has been already merged](https://github.com/kedacore/keda/pull/4867) and shipped as part of v2.13, so I close the issue
