### ISSUE TITLE
Proposal - Move community standup to bi-weekly basis

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda#502]
I'd like to propose to move the community standup to a bi-weekly cadence so that more people can join at the same time as it can now a bit intense.

However, it might just be me but if we do them every 2 weeks then I would be able to join more often.

**Comment by tomkerkhove** [comment]
Thoughts @jeffhollan @ahmelsayed?

**Comment by jeffhollan** [comment]
I’m ok with this. If there are folks from community that have updates or questions I’m more than happy to have more often, but yes potentially moving into next year we could do bi-weekly

/ @anirudhgarg

**Comment by tomkerkhove** [comment]
Any objections on this?

If not, I'll update everything to reflect this and start cycle on 9/01.

**Comment by anirudhgarg** [comment]
No issues. We can come back to weekly if we find that we are not able to cover all issues

**Comment by tomkerkhove** [comment]
👌, I'll make the required changes.

**Comment by tomkerkhove** [comment]
Core: https://github.com/kedacore/keda/pull/513
Docs: https://github.com/kedacore/keda-docs/pull/52
Google Agenda: ✔️

**Comment by zroubalik** [comment]
I don't have any strong objections, but as @anirudhgarg mentioned on the call, KEDA is getting more visibility and more folks are joining, there are topics on each call. We can maybe shorten the call to 30min?

**Comment by tomkerkhove** [comment]
For me the duration is not the problem but finding time to attend them every week in my spare time as it's outside of business hours for me.

Attended a SIG Instrumentation meeting yesterday and they do it only every other week but probably the problem is more me trying to attend every meeting 😅

Happy to abandon the work if need be.

**Comment by tomkerkhove** [comment]
As discussed today, we're going to hold off and see how it goes.
