### ISSUE TITLE
Removing support for Azure AD Pod Identity authentication from KEDA on v2.15

### ISSUE THREAD

**Issue by JorTurFer** [kedacore/keda#5035]
### Proposal

[AAD-Pod-Identity has gone out of support](https://github.com/Azure/aad-pod-identity#-announcement) and it doesn't make sense to maintain that integration if MSFT doesn't do it.

The depreciation message is added by [this PR](https://github.com/kedacore/keda/pull/5036) and we should remove the feature from KEDA v2.15

### Is this a feature you are interested in implementing yourself?

No

**Comment by tomkerkhove** [comment]
Fine by me, but let's make sure we do everything according to https://github.com/kedacore/governance/blob/main/DEPRECATIONS.md#introducing-new-deprecations
