### ISSUE TITLE
Azure Event Hub scaler using Managed Identity

### ISSUE THREAD

**Issue by andreaskasc** [kedacore/keda#5048]
### Proposal

This is more of a question that I couldn't find a clear answer.

I am trying to create a scaling rule based on event hub for my azure container app. Following the [KEDA documentation](https://keda.sh/docs/1.4/scalers/azure-event-hub/) for it, I see that _Authentication Parameters_ are not supported yet. 

Additionally, I see that it is only possible to connect to the event hub and the blob container by connection string. However, I would like to connect from the scaler through a User-Assigned Managed Identity as my container app does.

Is there a way to do it, or it is not supported at all?

### Use-Case

We are using only Managed Identities in our systems for connecting to Azure resources (for both event hub and blob storage) so it would be impossible for us to create a scaler for the container app.

### Is this a feature you are interested in implementing yourself?

No

### Anything else?

I have found [this open issue ](https://github.com/kedacore/keda/issues/3933) which sounds similar (not exactly my case though) but it is mentioned that Workload Identities can be used with Managed Identities. So if there is already a way to work around this please let me know with some example.

**Comment by JorTurFer** [comment]
Hello,
Azure Event Hub already support Managed Identities: https://keda.sh/docs/2.12/scalers/azure-event-hub/
![image](https://github.com/kedacore/keda/assets/36899226/f4f5c14a-1e40-4617-b874-78e75052bbc6)

Honestly, IDK which KEDA version runs on ACA because we aren't related with them, but I guess that it's already supported. In any case, we don't support ACA and you should open a ticket in Azure support. 
@tomkerkhove , could you point @andreaskasc to the correct place?

As this related with ACA and not directly with KEDA (because KEDA already supports it), I close the issue

**Comment by andreaskasc** [comment]
For anyone checking this issue, apparently container apps don't support using managed identities with KEDA scalers. It is supposedly in the roadmap according to this [open issue](https://github.com/microsoft/azure-container-apps/issues/592) but there is no estimation of delivery date yet.

**Comment by JorTurFer** [comment]
Honestly, I have no idea, ACA is a product built on top of KEDA that's all...
The only thing that I can say is that KEDA already supports it, when will ACA support it? You have to ask directly to ACA team or opening a support ticket on their side, there is nothing we can do

**Comment by andreaskasc** [comment]
I get it. My last comment was for people that want to do the same and end up here from a google search, so that they know this is not possible as of now. They can check the linked issue for updates.

**Comment by JorTurFer** [comment]
Sorry, I misunderstood it, today is being a large day :(

**Comment by JorTurFer** [comment]
https://learn.microsoft.com/en-us/azure/container-apps/managed-identity?tabs=portal%2Cdotnet
