### ISSUE TITLE
Split Deployment for Operator and Metrics Apiserver

### ISSUE THREAD

**Issue by zroubalik** [kedacore/keda#505]
We should split Deployment for Operator and Metrics Apiserver. Currently they are both deployed in one Deployment as a Containers.
Splitting into separate Deployment should help us with scaling out KEDA Operator and don't affect Metrics server, because we can not scale metrics server as there could be only one instance in the cluster.

Needed changes:
- ~KEDA deployment files~
- ~Tests configuration~
- ~Installation docs~
- ~HELM chart~

**Comment by tomkerkhove** [comment]
Stumbled upon https://github.com/helm/helm/issues/6361#issuecomment-538220109 yesterday, I presume this change will not fix it directly?

**Comment by zroubalik** [comment]
@tomkerkhove yeah, I don't think so
