### ISSUE TITLE
Hashicorp Vault: Support for writable secret

### ISSUE THREAD

**Issue by loispostula** [kedacore/keda#5067]
### Proposal

Currently the hashicorpvault auth secret only support secret that are retrievable via the vault `Read` API, supports for `Write` API would be useful.

### Use-Case

With this features, using the hashicorp vault secret could be used to generate mTls certificate for authentication.

### Is this a feature you are interested in implementing yourself?

Yes

**Comment by zroubalik** [comment]
Makes sense! Should I assign you to this issue?

**Comment by loispostula** [comment]
Absolutely
