### ISSUE TITLE
Pulsar Scaler OAuth support audience

### ISSUE THREAD

**Issue by qizichao-dm** [kedacore/keda#5069]
### Proposal

Audience could not be specified in current Pulsar Scaler OAuth Config. Though audience is not a part of the OAuth 2.0 spec, it's usually needed and mentioned in [pulsar document](https://pulsar.apache.org/docs/3.1.x/security-oauth2/#authentication-types)

### Use-Case

Use the Pulsar Scaler with a Pulsar instance and OAuth.

### Is this a feature you are interested in implementing yourself?

Yes

**Comment by zroubalik** [comment]
@qizichao-dm seems reasonable, should I assing the issue to you? :)

**Comment by zroubalik** [comment]
@qizichao-dm seems reasonable, should I assing the issue to you? :)

**Comment by qizichao-dm** [comment]
> @qizichao-dm seems reasonable, should I assing the issue to you? :)

Sure. I've made PRs ready for review
