### ISSUE TITLE
keda.k8s.io_scaledobjects_crd.yaml create error in k8s1.11

### ISSUE THREAD

**Issue by iyacontrol** [kedacore/keda#507]
kubectl apply -f https://github.com/kedacore/keda/blob/master/deploy/crds/keda.k8s.io_scaledobjects_crd.yaml

error: error parsing https://github.com/kedacore/keda/blob/master/deploy/crds/keda.k8s.io_scaledobjects_crd.yaml: error converting YAML to JSON: yaml: line 118: mapping values are not allowed in this context

k8s1.11.

**Comment by iyacontrol** [comment]
hi @zroubalik . 
I think you are more familiar with crd, if k8s1.13, no problem. but for k8s1.11 , failure.

**Comment by zroubalik** [comment]
@iyacontrol thanks! I will take a look on that, but it seems like issue with old k8s, so there's a question whether we want to support that version of k8s.

**Comment by tomkerkhove** [comment]
I'm tracking this in https://github.com/kedacore/keda-docs/issues/49 already, we should indeed define a minimum bar to comply with imo.

**Comment by zroubalik** [comment]
closing this in favor of https://github.com/kedacore/keda-docs/issues/49
