### ISSUE TITLE
Scaling Modifiers formula ambiguous behavior 

### ISSUE THREAD

**Issue by danialgood** [kedacore/keda#5074]
### Report

It seems that since `expr.AsFloat64()` is used while compiling the formula, all possible outputs of the formula should be float.

Currently the examples provided in the [documentation](https://keda.sh/docs/2.12/concepts/scaling-deployments/#scaling-modifiers-experimental) regarding ternary conditions are using int values. If having the value always as float is intended (which i guess it is) then doc should be revised to use float values otherwise the code should be changed.

### Expected Behavior

examples provided in the [docs](https://keda.sh/docs/2.12/concepts/scaling-deployments/#scaling-modifiers-experimental) to work

### Actual Behavior

admissions webhook denying validation :

`Error from server (Forbidden): error when creating : admission webhook "vscaledobject.kb.io" denied the request: error validating formula in ScalingModifiers
expected float64, but got interface {}`

### Steps to Reproduce the Problem

1. Add scalingModifiers to ScaledObject specs
2. Add a formula with ternary condition 

### Logs from KEDA operator

```
example
```

### KEDA Version

2.12.0

### Kubernetes Version

1.27

### Platform

Any

**Comment by zroubalik** [comment]
@gauron99 PTAL 🙏

**Comment by gauron99** [comment]
hey @danialgood thanks for letting us know! It looks like this is a mistake on my end. Ive updated the docs [here](https://github.com/kedacore/keda-docs/pull/1245)

**Comment by danialgood** [comment]
Great! I also noticed that [expr documentation under AsFloat64 ](https://expr.medv.io/docs/Configuration#asfloat64) explicitly mentions that:

> If the expression returns integer value, Expr will convert it to float64.

I didn't check out expr source code but might be an issue on their end.

**Comment by gauron99** [comment]
Expr package returns `any` not `int` on  ternary operator therefore its necessary to cast to float before returning in formula. This can be done using the expr package, Ive created a PR in docs [here](https://github.com/kedacore/keda-docs/pull/1246)

**Comment by JorTurFer** [comment]
As the documentation is already fixed, I close the issue
