### ISSUE TITLE
Provide support for rolling secrets

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda#508]
Provide support for rolling secrets so that customers can manage the lifecycle seperately and KEDA handles that accordingly.

**Comment by tomkerkhove** [comment]
I think this will handled via #563 for scalers

**Comment by pragmaticivan** [comment]
This seems to be fixed

**Comment by jeffhollan** [comment]
@pragmaticivan to be clear - you see now with current behavior if you update a K8s secret referenced by a scaledobject it's automatically / instantly being picked up?

**Comment by TimVosch** [comment]
Just walked into a similar issue (though I misspelled my hostname). I can confirm that - atleast - in version 2.12.1, triggerauthentications are updated when a referenced secret is updated.

**Comment by zroubalik** [comment]
@TimVosch thanks for the update!

Resolved.
