### ISSUE TITLE
update scaled object status with error if it's in error state

### ISSUE THREAD

**Issue by ahmelsayed** [kedacore/keda#51]

**Comment by yaron2** [comment]
What constitutes an error state?

**Comment by ahmelsayed** [comment]
The ones I had in mind were:

* Deployment doesn't exist
* trigger connection secret doesn't exist
* bad connection to event sources (invalid connection string, password/username, not found, etc)

I think it'll make debugging issues easier if you can just lookup the status of a ScaledObject that's not behaving as you'd expect instead of going through keda logs.

**Comment by yaron2** [comment]
Yeah that makes sense, however bad connection to event sources is a pretty volatile and changing thing..

**Comment by edganiukov** [comment]
In any case, if keda can't create HPA, it should report status to ScaleObject (prometheus query is invalid, some parameters are invalid, etc)

**Comment by zroubalik** [comment]
This could be reflected in `Status.Conditions`
https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#typical-status-properties

**Comment by zroubalik** [comment]
Fixed by #750
