### ISSUE TITLE
Apiservice isn't always deleted properly

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda#510]
When deleting KEDA it not always deletes everything leaving behind an unavailable API server.

This was also reported by Brendan Burns here: https://github.com/helm/helm/issues/6361#issuecomment-538220109

**Comment by zroubalik** [comment]
This seems like helm issue, shouldn't we move this to the https://github.com/kedacore/charts ?

**Comment by tomkerkhove** [comment]
You are correct, sorry for that! Transferring issue.

**Comment by tomkerkhove** [comment]
And I don't have the required permissions, can you move it maybe @jeffhollan @anirudhgarg?

**Comment by zroubalik** [comment]
I can't move it either, probably @ahmelsayed can do that, as he has ownership on that repo

**Comment by tomkerkhove** [comment]
Did it the manual way then :D
