### ISSUE TITLE
Watch created HPA and TriggerAuthentication resources

### ISSUE THREAD

**Issue by zroubalik** [kedacore/keda#511]
ATM we don't watch `HPA` and `TriggerAuthentication` resources for changes/updates. Controller should watch those resources and reconcile.

**Comment by tomkerkhove** [comment]
Thanks for taking a look at this @zroubalik!

**Comment by zroubalik** [comment]
HPAs should be covered by #581 

We still need to figure out TriggerAuthentication

**Comment by zroubalik** [comment]
As `TriggerAuthentication` object could be shared between  multiple `ScaledObject` reconciling it doesn't make a sense.
