### ISSUE TITLE
Prometheus scaler - context deadline exceeded

### ISSUE THREAD

**Issue by MattMHB** [kedacore/keda#5118]
### Report

keda-operator is unable to get the required metric from prometheus in order to scale pods and an error is logged

Error : ERROR    scalers_cache    error getting scale decision    {"scaledobject.Name": "api", "scaledObject.Namespace": "mcss", "scaleTarget.Name": "api", "error": "Get \"http://prometheus.monitoring.svc.cluster.local:9090/api/v1/query?query=sum%28rate%28http_requests_received_total%7Bapp%3D%22api%22%7D%5B2m%5D%29%29&time=2023-10-23T13:25:52Z\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}

ScaledObject trigger : 

  - type: prometheus
    metadata:
      serverAddress: http://prometheus.monitoring.svc.cluster.local:9090
      metricName: http_requests_received_total
      query: sum(rate(http_requests_received_total{app="api"}[2m]))
      threshold: '10'
      ignoreNullValues: "true"

Note : I can call the URL in the above error via curl from another pod and get the result {"status":"success","data":{"resultType":"vector","result":[{"metric":{},"value":[1698068296.805,"0"]}]}}

I have also increased the value of KEDA_HTTP_DEFAULT_TIMEOUT in keda-operator

        env:
        - name: WATCH_NAMESPACE
        - name: KEDA_HTTP_DEFAULT_TIMEOUT
          value: "10000"

I originally had this error with Keda 2.7.1 and tried updating to Keda 2.9.2 but it didn't help

### Expected Behavior

I expect keda-operator to retrieve the metric from Prometheus

### Actual Behavior

Getting the error specified above

### Steps to Reproduce the Problem

Install Keda and configure a scaler using prometheus metrics

### Logs from KEDA operator

keda-operator-54cbf4f4f5-qn4qx 2023-10-23T13:18:36Z    INFO    controller-runtime.metrics    Metrics server is starting to listen    {"addr": ":8080"}
keda-operator-54cbf4f4f5-qn4qx 2023-10-23T13:18:36Z    INFO    setup    Starting manager
keda-operator-54cbf4f4f5-qn4qx 2023-10-23T13:18:36Z    INFO    setup    KEDA Version: 2.9.2
keda-operator-54cbf4f4f5-qn4qx 2023-10-23T13:18:36Z    INFO    setup    Git Commit: 9bc3f66578a08cdfe084468ea3ef998fa6bf3bb0
keda-operator-54cbf4f4f5-qn4qx 2023-10-23T13:18:36Z    INFO    setup    Go Version: go1.18.8
keda-operator-54cbf4f4f5-qn4qx 2023-10-23T13:18:36Z    INFO    setup    Go OS/Arch: linux/amd64
keda-operator-54cbf4f4f5-qn4qx 2023-10-23T13:18:36Z    INFO    setup    Running on Kubernetes 1.25    {"version": "v1.25.11"}
keda-operator-54cbf4f4f5-qn4qx 2023-10-23T13:18:36Z    INFO    Starting server    {"kind": "health probe", "addr": ":8081"}
keda-operator-54cbf4f4f5-qn4qx 2023-10-23T13:18:36Z    INFO    Starting server    {"path": "/metrics", "kind": "metrics", "addr": ":8080"}
keda-operator-54cbf4f4f5-qn4qx I1023 13:18:36.685055       1 leaderelection.go:248] attempting to acquire leader lease keda/operator.keda.sh...
keda-operator-54cbf4f4f5-qn4qx I1023 13:19:12.345465       1 leaderelection.go:258] successfully acquired lease keda/operator.keda.sh
keda-operator-54cbf4f4f5-qn4qx 2023-10-23T13:19:12Z    INFO    grpc_server    Starting Metrics Service gRPC Server    {"address": ":9666"}
keda-operator-54cbf4f4f5-qn4qx 2023-10-23T13:19:12Z    INFO    Starting EventSource    {"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "source": "kind source: *v1alpha1.ScaledObject"}
keda-operator-54cbf4f4f5-qn4qx 2023-10-23T13:19:12Z    INFO    Starting EventSource    {"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "source": "kind source: *v2.HorizontalPodAutoscaler"}
keda-operator-54cbf4f4f5-qn4qx 2023-10-23T13:19:12Z    INFO    Starting Controller    {"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject"}
keda-operator-54cbf4f4f5-qn4qx 2023-10-23T13:19:12Z    INFO    Starting EventSource    {"controller": "triggerauthentication", "controllerGroup": "keda.sh", "controllerKind": "TriggerAuthentication", "source": "kind source: *v1alpha1.TriggerAuthentication"}
keda-operator-54cbf4f4f5-qn4qx 2023-10-23T13:19:12Z    INFO    Starting Controller    {"controller": "triggerauthentication", "controllerGroup": "keda.sh", "controllerKind": "TriggerAuthentication"}
keda-operator-54cbf4f4f5-qn4qx 2023-10-23T13:19:12Z    INFO    Starting EventSource    {"controller": "clustertriggerauthentication", "controllerGroup": "keda.sh", "controllerKind": "ClusterTriggerAuthentication", "source": "kind source: *v1alpha1.ClusterTriggerAuthentication"}
keda-operator-54cbf4f4f5-qn4qx 2023-10-23T13:19:12Z    INFO    Starting Controller    {"controller": "clustertriggerauthentication", "controllerGroup": "keda.sh", "controllerKind": "ClusterTriggerAuthentication"}
keda-operator-54cbf4f4f5-qn4qx 2023-10-23T13:19:12Z    INFO    Starting EventSource    {"controller": "scaledjob", "controllerGroup": "keda.sh", "controllerKind": "ScaledJob", "source": "kind source: *v1alpha1.ScaledJob"}
keda-operator-54cbf4f4f5-qn4qx 2023-10-23T13:19:12Z    INFO    Starting Controller    {"controller": "scaledjob", "controllerGroup": "keda.sh", "controllerKind": "ScaledJob"}
keda-operator-54cbf4f4f5-qn4qx 2023-10-23T13:19:12Z    INFO    Starting workers    {"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "worker count": 5}
keda-operator-54cbf4f4f5-qn4qx 2023-10-23T13:19:12Z    INFO    Starting workers    {"controller": "scaledjob", "controllerGroup": "keda.sh", "controllerKind": "ScaledJob", "worker count": 1}
keda-operator-54cbf4f4f5-qn4qx 2023-10-23T13:19:12Z    INFO    Reconciling ScaledObject    {"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "ScaledObject": {"name":"api","namespace":"mcss"}, "namespace": "mcss", "name": "api", "reconcileID": "5b6c5159-af05-4979-be00-360a92da5d7e"}
keda-operator-54cbf4f4f5-qn4qx 2023-10-23T13:19:12Z    INFO    Starting workers    {"controller": "triggerauthentication", "controllerGroup": "keda.sh", "controllerKind": "TriggerAuthentication", "worker count": 1}
keda-operator-54cbf4f4f5-qn4qx 2023-10-23T13:19:12Z    INFO    Starting workers    {"controller": "clustertriggerauthentication", "controllerGroup": "keda.sh", "controllerKind": "ClusterTriggerAuthentication", "worker count": 1}
keda-operator-54cbf4f4f5-qn4qx 2023-10-23T13:19:12Z    INFO    cpu_memory_scaler    trigger.metadata.type is deprecated in favor of trigger.metricType    {"type": "ScaledObject", "namespace": "mcss", "name": "api"}
keda-operator-54cbf4f4f5-qn4qx 2023-10-23T13:19:12Z    INFO    Initializing Scaling logic according to ScaledObject Specification    {"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "ScaledObject": {"name":"api","namespace":"mcss"}, "namespace": "mcss", "name": "api", "reconcileID": "5b6c5159-af05-4979-be00-360a92da5d7e"}
Stream closed EOF for keda/keda-operator-54cbf4f4f5-qn4qx (keda-operator)

keda-operator-54cbf4f4f5-qn4qx     /workspace/pkg/scaling/cache/scalers_cache.go:88
keda-operator-54cbf4f4f5-qn4qx github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).GetScaledObjectMetrics
keda-operator-54cbf4f4f5-qn4qx     /workspace/pkg/scaling/scale_handler.go:443
keda-operator-54cbf4f4f5-qn4qx github.com/kedacore/keda/v2/pkg/metricsservice.(*GrpcServer).GetMetrics
keda-operator-54cbf4f4f5-qn4qx     /workspace/pkg/metricsservice/server.go:45
keda-operator-54cbf4f4f5-qn4qx github.com/kedacore/keda/v2/pkg/metricsservice/api._MetricsService_GetMetrics_Handler
keda-operator-54cbf4f4f5-qn4qx     /workspace/pkg/metricsservice/api/metrics_grpc.pb.go:79
keda-operator-54cbf4f4f5-qn4qx google.golang.org/grpc.(*Server).processUnaryRPC
keda-operator-54cbf4f4f5-qn4qx     /workspace/vendor/google.golang.org/grpc/server.go:1340
keda-operator-54cbf4f4f5-qn4qx google.golang.org/grpc.(*Server).handleStream
keda-operator-54cbf4f4f5-qn4qx     /workspace/vendor/google.golang.org/grpc/server.go:1713
keda-operator-54cbf4f4f5-qn4qx google.golang.org/grpc.(*Server).serveStreams.func1.2
keda-operator-54cbf4f4f5-qn4qx     /workspace/vendor/google.golang.org/grpc/server.go:965
keda-operator-54cbf4f4f5-qn4qx 2023-10-23T13:25:36Z    ERROR    scalehandler    error getting metric for scaler    {"scaledObject.Namespace": "mcss", "scaledObject.Name": "api", "scaler": "prometheusScaler", "error": "Get \"http://prometheus.monitoring.svc.cluster.local:9090/api/v1/query?query=sum%28rate%28http_requests_received_total%7Bapp%3D%22api%22%7D%5B2m%5D%29%29&time=2023-10-23T13:25:26Z\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
keda-operator-54cbf4f4f5-qn4qx github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).GetScaledObjectMetrics
keda-operator-54cbf4f4f5-qn4qx     /workspace/pkg/scaling/scale_handler.go:449
keda-operator-54cbf4f4f5-qn4qx github.com/kedacore/keda/v2/pkg/metricsservice.(*GrpcServer).GetMetrics
keda-operator-54cbf4f4f5-qn4qx     /workspace/pkg/metricsservice/server.go:45
keda-operator-54cbf4f4f5-qn4qx github.com/kedacore/keda/v2/pkg/metricsservice/api._MetricsService_GetMetrics_Handler
keda-operator-54cbf4f4f5-qn4qx     /workspace/pkg/metricsservice/api/metrics_grpc.pb.go:79
keda-operator-54cbf4f4f5-qn4qx google.golang.org/grpc.(*Server).processUnaryRPC
keda-operator-54cbf4f4f5-qn4qx     /workspace/vendor/google.golang.org/grpc/server.go:1340
keda-operator-54cbf4f4f5-qn4qx google.golang.org/grpc.(*Server).handleStream
keda-operator-54cbf4f4f5-qn4qx     /workspace/vendor/google.golang.org/grpc/server.go:1713
keda-operator-54cbf4f4f5-qn4qx google.golang.org/grpc.(*Server).serveStreams.func1.2
keda-operator-54cbf4f4f5-qn4qx     /workspace/vendor/google.golang.org/grpc/server.go:965
keda-operator-54cbf4f4f5-qn4qx 2023-10-23T13:25:37Z    INFO    cpu_memory_scaler    trigger.metadata.type is deprecated in favor of trigger.metricType    {"type": "ScaledObject", "namespace": "mcss", "name": "api"}
keda-operator-54cbf4f4f5-qn4qx 2023-10-23T13:25:47Z    ERROR    prometheus_scaler    error executing prometheus query    {"type": "ScaledObject", "namespace": "mcss", "name": "api", "error": "Get \"http://prometheus.monitoring.svc.cluster.local:9090/api/v1/query?query=sum%28rate%28http_requests_received_total%7Bapp%3D%22api%22%7D%5B2m%5D%29%29&time=2023-10-23T13:25:37Z\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}

### KEDA Version

2.9.2

### Kubernetes Version

1.25

### Platform

Microsoft Azure

### Scaler Details

Prometheus

### Anything else?

There should be nothing blocking a pod from calling the prometheus url which is running on the same cluster

**Comment by JorTurFer** [comment]
Hello
If you deploy a pod within KEDA's namespace and do a curl with the query, does it work?
How much time does it need?
