### ISSUE TITLE
Unable to delete the scaled object deployed in Azure AKS and Namespace in terminating state

### ISSUE THREAD

**Issue by nidiculageorge** [kedacore/keda#5136]
### Discussed in https://github.com/kedacore/keda/discussions/5131

<div type='discussions-op-text'>

<sup>Originally posted by **nidiculageorge** October 17, 2023</sup>
### Report

Unable to delete the scaled object deployed in Azure AKS and Namespace in terminating state

![image](https://github.com/kedacore/keda/assets/43850474/9244b07b-ae10-4617-81e8-d8935309c6bb)

### Expected Behavior

As we tried deleting the namespace its in terminating state because of the above scaled object in that namespace

### Actual Behavior

Namesapce should be deleted after the scaled object is deleted

### Steps to Reproduce the Problem

1.
2.
3.

### Logs from KEDA operator

```
example
```

### KEDA Version

2.11.1

### Kubernetes Version

1.25

### Platform

Microsoft Azure

### Anything else?

_No response_</div>

**Comment by JorTurFer** [comment]
I close this as solved, and the thread looks answered in the discussion, If you still need something related with this, just comment it and we can continue
