### ISSUE TITLE
Add pause metric in prometheus for scaledjob

### ISSUE THREAD

**Issue by geoffrey1330** [kedacore/keda#5140]
### Proposal

Currently, Prometheus does not provide a dedicated metric for monitoring the pause and resume events of ScaledJobs in Kubernetes. We propose adding a new metric specifically designed to track the pause and resume actions of ScaledJobs. This metric will offer valuable insights into the scaling behavior and pause-related events, improving observability and facilitating troubleshooting.

### Use-Case

The addition of a pause metric in Prometheus for ScaledJobs will improve monitoring, simplify troubleshooting, and aid optimization efforts. This metric provides insight into pause and resume events, streamlining the identification of issues and enabling data-driven optimizations. It is a valuable feature for those managing ScaledJobs in Kubernetes clusters.

### Is this a feature you are interested in implementing yourself?

Yes

**Comment by geoffrey1330** [comment]
@zroubalik I created a new issue similar to this PR [here](https://github.com/kedacore/keda/pull/5045) but for scaledjob

**Comment by geoffrey1330** [comment]
If this is OK. 
I can proceed working on it

**Comment by geoffrey1330** [comment]
@zroubalik WDYT about the issue?

**Comment by geoffrey1330** [comment]
@zroubalik Does that Imply I can't work on it. as it should be a part of https://github.com/kedacore/keda/pull/4913

**Comment by zroubalik** [comment]
@geoffrey1330 wait till the PR is merged. If it is not covered there, let's proceed here 🙏

**Comment by geoffrey1330** [comment]
@zroubalik Alright I will do that.
In the meantime could you recommend any issue for me to work on.
