### ISSUE TITLE
AWS session token support broken

### ISSUE THREAD

**Issue by JacobHenner** [kedacore/keda#5156]
### Report

Support for AWS session tokens (introduced in #2573) was inadvertently broken in https://github.com/kedacore/keda/commit/1d6d0f100d06e9fdb1e42275fc1e03160af09a72, when `credentials.NewStaticCredentials(metadata.awsAuthorization.awsAccessKeyID, metadata.awsAuthorization.awsSecretAccessKey, metadata.awsAuthorization.awsSessionToken)` was replaced with `credentials.NewStaticCredentials(metadata.awsAuthorization.awsAccessKeyID, metadata.awsAuthorization.awsSecretAccessKey, "")`. This prevents AWS scalers from authenticating to AWS when session tokens are in use.

### Expected Behavior

AWS scalers should function as expected.

### Actual Behavior

KEDA fails with the following event text: `InvalidClientTokenId: The security token included in the request is invalid. status code: 403`

### Steps to Reproduce the Problem

Attempt to use an AWS scaler (e.g. the SQS scaler) with AWS credentials that require session tokens, with the `awsSessionToken` field set as expected.

### KEDA Version

2.10.1

### Kubernetes Version

None

### Platform

Amazon Web Services

### Scaler Details

AWS SQS

**Comment by JacobHenner** [comment]
See https://github.com/kedacore/keda/pull/5155 (draft) for fix.

**Comment by zroubalik** [comment]
Good catch, thanks!
