### ISSUE TITLE
Event Hub scalar expansion to work with Java and C# applications and not just functions

### ISSUE THREAD

**Issue by rasavant-ms** [kedacore/keda#516]
Currently, the Event Hub scalar does not support scaling Java or C# applications running on containers. Only C# and python Azure functions are supported.
I would like to have support for standalone applications using the EventProcessorHost SDK to work with the Event Hubs scalar for KEDA as well.

Tell us more what you'd like to achieve

Event Hubs checkpointing information for the consumed messages is stored in blob store and the format of the blob url for Azure functions is different than when using a .NET or Java application to store checkpointing information. I would like this format of storing checkpoints to be handled in the KEDA code.

- [ ] Java applications should be scaled with KEDA using Event Hubs scalar

**Comment by abhirockzz** [comment]
Raised in #376 as well

**Comment by ahmelsayed** [comment]
Closed in #517
