### ISSUE TITLE
Admissions webhook rejects when helm upgrade done with renamed ScaledObject

### ISSUE THREAD

**Issue by govindbalaji-s** [kedacore/keda#5167]
### Report

Let's say I have a ScaledObject already installed with "name: initial-scaled-object", and it's target is a deployment with name "target-deployment".

Now, if I rename the ScaledObject in my helm charts to "name: renamed-scaled-object", admissions webhook starts failing the helm upgrade with:
```
upgrade.go:367: [debug] warning: Upgrade "<<RELEASE_NAME>>" failed: failed to create resource: admission webhook "vscaledobject.kb.io" denied the request: the workload 'target-deployment' of type 'apps/v1.Deployment' is already managed by the ScaledObject 'initial-scaled-object'
```

### Expected Behavior

Scaled object with "renamed-scaled-object" name gets created, then "initial-scaled-object" gets deleted by helm upgrade.

### Actual Behavior

Creation of "renamed-scaled-object" fails with above error.

### Steps to Reproduce the Problem

1. Install a scaledobject with some name targeting some deployment.
2. Rename the scaledobject in your helm charts and do a helm upgrade.

### KEDA Version

2.11.2

### Kubernetes Version

1.25

### Platform

Amazon Web Services

**Comment by SpiritZhou** [comment]
I think this is the correct behavior because the name is the identifier of the ScaledObject. Automatically replacing the current ScaledObject with another ScaledObject that has a new identifier can be a little tricky.

**Comment by govindbalaji-s** [comment]
What's the right way to rename a ScaledObject when used with helm then?

**Comment by prajithp13** [comment]
We are also encountering a similar issue. In our case, the creation of the ScaledObject is failing because there is already an HPA for a deployment that we are attempting to update, as we are transitioning from native HPA to ScaledObject.
```
helm.go:84: [debug] admission webhook "vscaledobject.kb.io" denied the request: the workload 'app-prod-http' of type 'apps/v1.Deployment' is already managed by the hpa 'app-prod-http'
```

**Comment by lucyeun-alation** [comment]
> We are also encountering a similar issue. In our case, the creation of the ScaledObject is failing because there is already an HPA for a deployment that we are attempting to update, as we are transitioning from native HPA to ScaledObject.
> 
> ```
> helm.go:84: [debug] admission webhook "vscaledobject.kb.io" denied the request: the workload 'app-prod-http' of type 'apps/v1.Deployment' is already managed by the hpa 'app-prod-http'
> ```

For anyone else running into this, [this](https://keda.sh/docs/2.12/concepts/scaling-deployments/#transfer-ownership-of-an-existing-hpa) did the trick for me.

**Comment by shettypriy** [comment]
@lucyeun-alation Could you please let me how exactly did you solve the issue. I did try the solution in the link you mentioned, but it did not work

**Comment by omfurman-ma** [comment]
I managed to make it work using @lucyeun-alation's suggestion - https://keda.sh/docs/2.12/concepts/scaling-deployments/#transfer-ownership-of-an-existing-hpa

```
      annotations:
        scaledobject.keda.sh/transfer-hpa-ownership: "true"
.....
      advanced:
        horizontalPodAutoscalerConfig:
          name: <name-of-existing-hpa>
```
