### ISSUE TITLE
New Relic metric shows incorrect value

### ISSUE THREAD

**Issue by shachar-ash** [kedacore/keda#5202]
### Report

I'm having issues using New Relic queries properly. The current value shown in HPA does not match the response in New Relic. 
The reported value is too high, and the pods are stuck at their maximum capacity.

I went over previous GitHub issues/discussions about the same problem, and unfortunately, the documentation/FAQs didn't help in my case:
https://github.com/kedacore/keda/issues/2740
https://github.com/kedacore/keda/discussions/2451

### Expected Behavior

I expect the behavior to match the query result in New Relic and the HPA to scale my deployment according to the query results.

### Actual Behavior

![image](https://github.com/kedacore/keda/assets/20629609/6b84d45f-5fb0-48f0-a43e-348c07b6725a)

The query I'm running: 
`SELECT rate(count(apm.service.transaction.duration), 1 minute) FROM Metric WHERE appName = 'my-app-name' TIMESERIES`

HPA output:
NAME                             REFERENCE                          TARGETS              MINPODS   MAXPODS   REPLICAS   AGE
keda-my-app   Deployment/my-app   340141296/50 (avg)   1         5         5          3h56m

As you can see from the graph - the value of the NRQL is around 100 - because I'm using the default average behavior it should be ~20 (divided by 5 pods) which is well below the threshold (50).

I still can't figure out where the value of `340141296` came from, but because of this high value, the HPA is always configured for the maximum amount of replicas.

### Steps to Reproduce the Problem

Add a New Relic scaler with a simple APM query for RPM (requests per minute)

### Logs from KEDA operator

```
2023-11-23T19:50:37Z	INFO	Reconciling ScaledObject	{"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "ScaledObject": {"name":"my-app-name","namespace":"default"}, "namespace": "default", "name": "my-app-name", "reconcileID": "2db87bd4-7cb1-4728-ae5f-e753c8131557"}
2023-11-23T19:50:52Z	INFO	Reconciling ScaledObject	{"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "ScaledObject": {"name":"my-app-name","namespace":"default"}, "namespace": "default", "name": "my-app-name", "reconcileID": "d35a43b5-456f-4e8c-9811-eb07ee961220"}
2023-11-23T19:50:52Z	INFO	Reconciling ScaledObject	{"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "ScaledObject": {"name":"my-app-name","namespace":"default"}, "namespace": "default", "name": "my-app-name", "reconcileID": "a511b801-08b4-40a0-84f4-b09ba845b6b7"}
2023-11-23T19:51:09Z	INFO	Reconciling ScaledObject	{"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "ScaledObject": {"name":"my-app-name","namespace":"default"}, "namespace": "default", "name": "my-app-name", "reconcileID": "4059d985-c9d4-45b6-8f0a-1d32464ac682"}
2023-11-23T19:51:25Z	INFO	Reconciling ScaledObject	{"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "ScaledObject": {"name":"my-app-name","namespace":"default"}, "namespace": "default", "name": "my-app-name", "reconcileID": "a274d10e-daa8-4507-9d4f-317b79e55488"}
2023-11-23T19:52:10Z	INFO	Reconciling ScaledObject	{"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "ScaledObject": {"name":"my-app-name","namespace":"default"}, "namespace": "default", "name": "my-app-name", "reconcileID": "36c77231-eb44-4e0a-89cf-1aa049832a43"}
```

Scaled object status:
```
Status:
  Conditions:
    Message:  ScaledObject is defined correctly and is ready for scaling
    Reason:   ScaledObjectReady
    Status:   True
    Type:     Ready
    Message:  Scaling is performed because triggers are active
    Reason:   ScalerActive
    Status:   True
    Type:     Active
    Message:  No fallbacks are active on this scaled object
    Reason:   NoFallbackFound
    Status:   False
    Type:     Fallback
    Status:   Unknown
    Type:     Paused
```

### KEDA Version

2.12.0

### Kubernetes Version

1.27

### Platform

Amazon Web Services

### Scaler Details

New Relic

**Comment by JorTurFer** [comment]
Hello,
Could you share your ScaledObject please?

**Comment by shachar-ash** [comment]
@JorTurFer Sure, here it is: 
```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  annotations:
    meta.helm.sh/release-name: my-app-name
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2023-11-23T19:50:36Z"
  finalizers:
  - finalizer.keda.sh
  generation: 1
  labels:
    app.kubernetes.io/managed-by: Helm
    scaledobject.keda.sh/name: my-app-name
  name: my-app-name
  namespace: default
  resourceVersion: "<VERSION>"
  uid: <UUID>
spec:
  maxReplicaCount: 5
  minReplicaCount: 1
  scaleTargetRef:
    name: my-app-name
  triggers:
  - authenticationRef:
      name: keda-newrelic-integration
    metadata:
      noDataError: "true"
      nrql: SELECT rate(count(apm.service.transaction.duration), 1 minute) FROM Metric
        WHERE appName = 'my-app-name' TIMESERIES
      threshold: "50"
    type: new-relic
status:
  conditions:
  - message: ScaledObject is defined correctly and is ready for scaling
    reason: ScaledObjectReady
    status: "True"
    type: Ready
  - message: Scaling is performed because triggers are active
    reason: ScalerActive
    status: "True"
    type: Active
  - message: No fallbacks are active on this scaled object
    reason: NoFallbackFound
    status: "False"
    type: Fallback
  - status: Unknown
    type: Paused
  externalMetricNames:
  - s0-new-relic
  health:
    s0-new-relic:
      numberOfFailures: 0
      status: Happy
  hpaName: keda-my-app-name
  lastActiveTime: "2023-11-26T17:48:43Z"
  originalReplicaCount: 1
  scaleTargetGVKR:
    group: apps
    kind: Deployment
    resource: deployments
    version: v1
  scaleTargetKind: apps/v1.Deployment
```

**Comment by JorTurFer** [comment]
[Are you scrapping prometheus metrics from KEDA](https://keda.sh/docs/2.12/operate/prometheus/#operator)? There is a metric that can help as it shows the value recovered from KEDA: `keda_scaler_metrics_value`.
Do you see any error event in the HPA or ScaledObject?

**Comment by shachar-ash** [comment]
@JorTurFer I didn't see any error event in HPA/ScaledObject.
I can look into starting scraping Prometheus metrics from KEDA tomorrow, I'll update afterward.
Any other suggestions?

Thanks!

**Comment by shachar-ash** [comment]
@JorTurFer Hey, I added the metrics, and below is the value for `keda_scaler_metrics_value`. It seems like it doesn't get the value I'm getting when I make the same query through the UI.
![Screenshot 2023-11-27 at 10 17 51 AM](https://github.com/kedacore/keda/assets/20629609/5da78930-7549-48d5-bd16-bf2116857355)

**Comment by JorTurFer** [comment]
I'm checking the code and I see this comment `// Only use the first result from the query, as the query should not be multi row`
Is your query a multi row query?
From your original picture I understand that yes 
![image](https://github.com/kedacore/keda/assets/36899226/8375406e-3245-4b29-99d6-c42efb12af1e)

But it's true that I've no idea about NR and also that doesn't mean that it has to fail in this case, just for digging in the issue

**Comment by shachar-ash** [comment]
The query is not multi-row, I tried to add an identical query to the graph previously to see if it makes a difference.
This is how the graph looks right now:
![image](https://github.com/kedacore/keda/assets/20629609/4a083202-88f0-4d5c-bf39-9cb45b366f01)

**Comment by JorTurFer** [comment]
This is really weird. The querying code is quite simple:
https://github.com/kedacore/keda/blob/5397894a42229efcc608311e055d1aa140ae7613/pkg/scalers/newrelic_scaler.go#L154-L171

I don't see where the issue can be as the SDK is just a direct pass through of the provided query. Other upstreams allow more configurations about the time windows and those stuff, but not in NR.
Are you golang developer by chance? I ask to test the query directly from your local using the SDK to directly query NR and try to discover if the value is wrongly recovered by the SDK, if KEDA is doing something wrong, or what's happening

**Comment by shachar-ash** [comment]
I'm not a golang developer but I can try to test it out. 
I tried to change the query to a simple query that selects a static value `SELECT 3 FROM Metric TIMESERIES` - which worked well:
```
keda-hpa-my-app                     Deployment/my-app                              3/50 (avg)        1         5         1          4d2h
```

I then changed the query back to the query I wanted to use and checked the HPA values, it was set to the right value (27), but I checked the status 5 seconds later and it changed back to a huge value which has nothing to do with my query:
```
keda-hpa-my-app                     Deployment/my-app                              27/50 (avg)       1         5         1          4d2h
keda-hpa-my-app                     Deployment/my-app                              425280165/50 (avg)   1         5         4          4d2h
```

I will try to debug it with other queries to see if I can understand what type of queries are experiencing this behavior.

**Comment by JorTurFer** [comment]
let me know if I can help you with something else :( 
I don't see why this can be happening being honest

**Comment by shachar-ash** [comment]
I can confirm that this behavior is consistent with all queries. 
I tested with the query `SELECT 4 FROM Metric TIMESERIES` and changed it to `SELECT 5 FROM Metric TIMESERIES`. 
I kept getting the HPA values each second and this is the result:
![image](https://github.com/kedacore/keda/assets/20629609/9b578f57-32c9-4ee7-bd79-7a362fb8bba5)

It seems like right after I change to a new query it works for a few seconds, and then the value changes to a huge number that has nothing to do with the queries I'm testing.

**Comment by JorTurFer** [comment]
So, maybe KEDA is mixing somehow the time and the value? I mean, if KEDA is returning the epoch time as value, it can justify current scenario (and we have a starting point for the fix)

**Comment by dipeti** [comment]
I am experiencing the exact same behaviour when using a `TIMESERIES` query. Works just fine without `TIMESERIES`, in other words no problem when the response is a single value.

**Comment by JorTurFer** [comment]
Maybe we should clarify this in docs to prevent issues to newcomers. Are you willing to update docs?

**Comment by shachar-ash** [comment]
@JorTurFer We definitely should clarify it in the doc.
Right now, the docs example is using `TIMESERIES`, that's why I added it in the first place, see here: https://keda.sh/docs/2.11/scalers/new-relic/#trigger-specification

I can confirm that omitting the `TIMESERIES` made `keda_scaler_metrics_value` report the right value and it fixed my issue.

**Comment by JorTurFer** [comment]
Could you open a PR updating docs?

**Comment by shachar-ash** [comment]
Done 😄 
https://github.com/kedacore/keda-docs/pull/1267

**Comment by shachar-ash** [comment]
I'm trying to benchmark my service right now, and even though it looks better now - I still see a mismatch between the value of the query I'm using and the `keda_scaler_metrics_value` metric.
![image](https://github.com/kedacore/keda/assets/20629609/a1170540-10a9-4de2-9c86-4de5e933792a)

This mismatch is causing my service to not scale fast enough.
Any ideas about what might be the issue?

**Comment by JorTurFer** [comment]
The only option that comes to my mind is that the chart is with TIMESERIES and with KEDA you don't use it :/ 
Have you printed the query without TIMESERIES?

**Comment by JorTurFer** [comment]
Do you have just a single ScaledObject with a single trigger? How does the query work? I mean, is your query `SELECT latest(keda_scaler_metric_value) ....` filtering somehow other metrics from KEDA? each trigger (from all the ScaledObjects/ScaledJobs) generates its own timeseries splittable by labels

**Comment by JorTurFer** [comment]
I have another question, what does `count` affect in your APM query? (Just to understand how it works), to know the amount of request you are counting the duration traces over the time, right?

**Comment by shachar-ash** [comment]
I have a single ScaledObject with a single trigger as I'm just testing the New Relic scaler functionality right now. 
My query in the last picture I sent was `SELECT count(apm.service.transaction.duration) FROM Metric WHERE appName = 'my-app'`.

In this query - `count` is just counting the number of metrics reported. The original query was `SELECT rate(count(apm.service.transaction.duration), 1 minute) FROM Metric WHERE appName = 'my-app"` which should have given me the amount of requests the app got each minute.

**Comment by JorTurFer** [comment]
it's weird because during the first minutes it looks correct, and suddenly the metric grows a lot :/ 
Would you try the query using the SDK directly? would you be willing to do it? I can prepare a sample project just for pressing F5 using VSC and devcontainers

**Comment by shachar-ash** [comment]
@JorTurFer Sure, I'll need your help to point me in the right direction, but I don't mind testing it out using the SDK 😄

**Comment by shachar-ash** [comment]
@JorTurFer I was able to make the query value align with the `TIMESERIES` query. For some reason when I tested it yesterday, I didn't get the same value when I made the query manually, maybe I had something wrong with the query.

Anyway, I realized that the reason the `TIMESERIES` query gets different values is that it breaks down the query by the minute, which means each dot on the graph is calculated for the previous minute. 

After I added `SINCE 1 MINUTE AGO` to the query, `keda-operator` gets the same value as I'm getting in the query.
I didn't find anything in the NR documentation that states exactly that, but I'll keep looking it up and open a PR to clarify this undocumented behavior.

Hope you enjoy KCD!

**Comment by JorTurFer** [comment]
> I think we can close the issue, I'm not sure if we should adjust the documentation or not, as apparently, this is the expected New Relic behavior.

I think that at least we can add a note on the scaler announcing this for newcomers. Something like:

>NOTE: Default behaviour takes into account [last 30 minutes](https://docs.newrelic.com/docs/apis/rest-api-v2/basic-functions/specify-time-range-v2/) for the query and it can produce unexpected responses. You could be interested on reducing the scope to 1 minute adding `SINCE 1 MINUTE AGO` to the statement

WDYT?
Would you be willing to open a PR to docs repo?

**Comment by zroubalik** [comment]
Yeah, please add this note to the docs, maybe together with an example of the query.

**Comment by shachar-ash** [comment]
I'll open a PR later today with a clarification

**Comment by shachar-ash** [comment]
Created this PR: https://github.com/kedacore/keda-docs/pull/1280
Preview: https://deploy-preview-1280--keda.netlify.app/docs/2.12/scalers/new-relic/

Will appreciate a review 😄 
![image](https://github.com/kedacore/keda/assets/20629609/d6456d0a-7ebd-430f-927f-14b84980c514)

**Comment by JorTurFer** [comment]
Thanks for your patience, your effort and your contribution! :heart:
