### ISSUE TITLE
Setting autoscaling.keda.sh/paused: "false" leads to ScaledObject/Job being paused

### ISSUE THREAD

**Issue by nappelson** [kedacore/keda#5215]
### Report

I noticed that setting 
```
autoscaling.keda.sh/paused: "false"
```
pauses the ScaledObject.

### Expected Behavior

I would expect setting `autoscaling.keda.sh/paused: "false"` to turn off the forced pausing behavior. 

### Actual Behavior

Instead, regardless of what `autoscaling.keda.sh/paused` is set to, the ScaledObject remains in the paused state. To resume the scaling behavior, I removed the annotation.

### Steps to Reproduce the Problem

1. add `autoscaling.keda.sh/paused: "false"` annotation to an existing, running ScaledObject/ScaledJob
2. run `kubectl get ScaledObject` and verify that the object is in the `paused: True` state

### KEDA Version

2.12.0

### Kubernetes Version

1.27

### Platform

Google Cloud

### Scaler Details

Redis

### Anything else?

I just noticed based on the check here - https://github.com/kedacore/keda/blob/25dc205132d1de09a6156b2bc9ce623353b94fdb/controllers/keda/scaledobject_controller.go#L213 that this is expected behavior. Also, in the documentation this looks like expected behavior as the suggested action to resume the scaling is to remove the annotation - https://keda.sh/docs/2.12/concepts/scaling-deployments/#pause-autoscaling

That being said, the use of `true` in the documentation is confusing as it implies that switching to `false` should disable the pausing functionality.

I was going to submit a PR to check the value of the annotation but I'm curious what people think the desired behavior should be.

**Comment by zroubalik** [comment]
@nappelson you are right, `false` should definitely unpause the SO/SJ. A PR with a fix (and test) would be much appreciated 🙏

**Comment by nappelson** [comment]
> @nappelson you are right, `false` should definitely unpause the SO/SJ. A PR with a fix (and test) would be much appreciated 🙏

@zroubalik FWIW, I put up this PR yesterday https://github.com/kedacore/keda-docs/pull/1266. 

I'm curious, do you think we should enforce a valid boolean value for this annotation and show some warning (while pausing the scaler) if it isn't valid boolean?

**Comment by zroubalik** [comment]
I would say, that:
- if the annontation is set (without a value) or set to `true` then pause
- if not set or set to `false` then unpause 

This way we don't break backwards compatibility.

@kedacore/keda-maintainers wdyt?

**Comment by JorTurFer** [comment]
> I would say, that:
> 
> * if the annontation is set (without a value) or set to `true` then pause
> * if not set or set to `false` then unpause
> 
> This way we don't break backwards compatibility.
> 
> @kedacore/keda-maintainers wdyt?

It's okey to me

**Comment by tomkerkhove** [comment]
Sounds good to me. @nappelson Are you willing to contribute this?

**Comment by tomkerkhove** [comment]
> if the annontation is set (without a value) or set to true then pause

Even if it's not `true` it is considered to be pausing it so we should make sure we don't break people (typo or whatever value) or we can block non supported values

**Comment by nappelson** [comment]
> Sounds good to me. @nappelson Are you willing to contribute this?

@tomkerkhove yep I'm happy to put up a PR. May not be able to do it right away (should be by next week though).

@zroubalik 
> I would say, that:
> 
> if the annontation is set (without a value) or set to true then pause
> if not set or set to false then unpause
> This way we don't break backwards compatibility.

Yep this makes sense to me!

**Comment by nappelson** [comment]
Note - I discovered this bug while testing code for this issue https://github.com/kedacore/keda/issues?q=is%3Aissue+is%3Aopen+paused

**Comment by jgtvares** [comment]
I'm also experiencing this!
In my team we mantain a PaaS with 989 apps running today and a lot of them rely on KEDA for CPU and memory scaling.
Is there an ETA for this fix?

**Comment by jgtvares** [comment]
I'm working around this by setting the annotation as `null` when I don't want the `ScaledObject` to be paused.
