### ISSUE TITLE
Pass the detail of which trigger was fired when you have multiple triggers for a scaled job 

### ISSUE THREAD

**Issue by jpspringall** [kedacore/keda#5218]
### Proposal

This relates to:  https://github.com/kedacore/keda/discussions/5206

Essentially update Keda so that it passes through the trigger that caused a ScaledJob To Be Started
Initial thoughts are to set an env variable? 

### Use-Case

My use case is as follows, but could theoretically apply to any type of trigger:

I have multiple SQS triggers all triggering the same Scaled Job, it would be useful to know which trigger initiated the scaled job

### Is this a feature you are interested in implementing yourself?

No

### Anything else?

Only not willing to help, as I would be more of a hinderance than a help, but knowledge of both the internal workings of Kubernetes & GO is virtually non existent :-)

**Comment by zroubalik** [comment]
Thanks for interesting use case @jpspringall, I missed this somehow. 

So your initial idea is to set environment value in the Job? Any alternatives?

**Comment by jpspringall** [comment]
> Thanks for interesting use case @jpspringall, I missed this somehow.
> 
> So your initial idea is to set environment value in the Job? Any alternatives?

Hi @zroubalik, Apologies in the delay response, I've been under the weather for the past few days.

Yeah my original idea was to use an environment variable, but as i said my knowledge of how kubernetes works is virtually non existent, so there may be another way.

That said, I will confess I'm not moving forward with using KEDA, nothing to do with KEDA, just not worthwhile in my case

Cheers

James

**Comment by inha18minseokkim** [comment]
oh, there's closed issue that i looked for.. did this issue solved?
