### ISSUE TITLE
keda Operator pod fails to be created successfully

### ISSUE THREAD

**Issue by datan-ew** [kedacore/keda#5222]
### Report

The keda-operator pod was working fine , there were no changes done but recently the keda operator container pod is in crash loop state.

when checked on the container logs below is the error we found.

INFO	Observed a panic in reconciler: runtime error: invalid memory address or nil pointer dereference	{"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "ScaledObject": {"name":"demo","namespace":"policy"}, "namespace": "policy", "name": "demo", "reconcileID": "74959bc0-9d1e"}
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2f62594]

goroutine 544 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
	/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:119 +0x1fa

![image](https://github.com/kedacore/keda/assets/85990449/f0dd2a31-66f3-4fb5-a90b-d0e59d010f7c)

### Expected Behavior

should work fine with no errors

### Actual Behavior

pasted the error log above

### Steps to Reproduce the Problem

1. There were no changes done , it was working fine on all clusters , only on this cluster we see this error and not sure what is the issue here
2.
3.

### Logs from KEDA operator

```
example
```

### KEDA Version

2.10.1

### Kubernetes Version

1.24

### Platform

Amazon Web Services

**Comment by JorTurFer** [comment]
Could you share the scaledobject "demo" in namespace "policy"? It seems that it's producing a panic (it shouldn't happen)

**Comment by datan-ew** [comment]
> Could you share the scaledobject "demo" in namespace "policy"? It seems that it's producing a panic (it shouldn't happen)

apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  annotations:
    meta.helm.sh/release-name: demo
    meta.helm.sh/release-namespace: policy
  finalizers:
    - finalizer.keda.sh
  generation: 2
  labels:
    app: demo
    app.kubernetes.io/instance: demo
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: demo
    scaledobject.keda.sh/name: demo
  managedFields:
    - apiVersion: keda.sh/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:labels:
            f:scaledobject.keda.sh/name: {}
      manager: keda
      operation: Update
      time: '2023-08-24T17:12:31Z'
    - apiVersion: keda.sh/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:meta.helm.sh/release-name: {}
            f:meta.helm.sh/release-namespace: {}
          f:labels:
            .: {}
            f:app: {}
            f:app.kubernetes.io/instance: {}
            f:app.kubernetes.io/managed-by: {}
            f:app.kubernetes.io/name: {}
            f:datacenter: {}
            f:env: {}
            f:project: {}
        f:spec:
          .: {}
          f:advanced:
            .: {}
            f:horizontalPodAutoscalerConfig:
              .: {}
              f:behavior:
                .: {}
                f:scaleDown:
                  .: {}
                  f:policies: {}
                  f:stabilizationWindowSeconds: {}
          f:maxReplicaCount: {}
          f:minReplicaCount: {}
          f:scaleTargetRef:
            .: {}
            f:name: {}
          f:triggers: {}
      manager: helm
      operation: Update
      time: '2023-11-16T16:49:04Z'
    - apiVersion: keda.sh/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          .: {}
          f:conditions: {}
          f:externalMetricNames: {}
          f:health:
            .: {}
            f:s0-prometheus-demo_req_per_sec:
              .: {}
              f:numberOfFailures: {}
              f:status: {}
            f:s1-prometheus-demo_req_per_sec:
              .: {}
              f:numberOfFailures: {}
              f:status: {}
          f:originalReplicaCount: {}
          f:scaleTargetKind: {}
      manager: keda
      operation: Update
      subresource: status
      time: '2023-11-24T10:58:35Z'
  name: demo
  namespace: policy
  resourceVersion: '131782150'
  uid: 1d90025e
  selfLink: /apis/keda.sh/v1alpha1/namespaces/policy/scaledobjects/demo
status:
  conditions:
    - message: ScaledObject is defined correctly and is ready for scaling
      reason: ScaledObjectReady
      status: 'True'
      type: Ready
    - status: Unknown
      type: Active
    - message: No fallbacks are active on this scaled object
      reason: NoFallbackFound
      status: 'False'
      type: Fallback
  externalMetricNames:
    - s0-prometheus-demo_req_per_sec
    - s1-prometheus-demo_req_per_sec
  health:
    s0-prometheus-demo_req_per_sec:
      numberOfFailures: 0
      status: Happy
    s1-prometheus-demo_req_per_sec:
      numberOfFailures: 0
      status: Happy
  originalReplicaCount: 4
  scaleTargetKind: apps/v1.Deployment
spec:
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          policies:
            - periodSeconds: 15
              type: Percent
              value: 10
            - periodSeconds: 15
              type: Pods
              value: 4
          stabilizationWindowSeconds: 60
  maxReplicaCount: 17
  minReplicaCount: 4
  scaleTargetRef:
    name: demo
  triggers:
    - metadata:
        metricName: demo_req_per_sec
        query: >-
          max_over_time(demo_req_per_sec:api_call_count:rate5m{cluster=~"clustername"}[180m])
        serverAddress: https://abc.com
        threshold: '300'
      type: prometheus
    - metadata:
        metricName: demo_req_per_sec
        query: >-
          max_over_time(demo_req_per_sec:api_call_count:rate5m{cluster=~"clustername"}[180m]
          offset 6d23h)
        serverAddress: https://abc.com
        threshold: '300'
      type: prometheus
