### ISSUE TITLE
Client-side GRPC load balancing

### ISSUE THREAD

**Issue by BojanZelic** [kedacore/keda#5224]
### Proposal

Keda currently uses the `pick_first` load balancing policy for GRPC connections which is the grpc library default. This currently works in most setups because of default coredns configurations. However, if we're not using the default settings, Keda should perform client-side round-robin load balancing for grpc connections aswell.

### Use-Case

Some Kubernetes environments customize the default DNS configurations; For example:
* disabling the [loadbalance](https://coredns.io/plugins/loadbalance/) CoreDNS plugin
* and talking to a headless service

the above changes means DNS requests will always return the results in the same order and won't randomize the ordering, ex with 2 pods:
```
root@app-5877ff4bd9-p27mk:/# dig headless-svc.default.svc.cluster.local +short
10.1.3.215
10.1.3.210
```

In this case, Keda should round-robin load balance grpc connections... otherwise it's always going to talk to the same pod and not send any requests off to the second one; this is a simple [1-line config change built into the grpc library](https://github.com/grpc/grpc-go/blob/v1.61.0-dev/examples/features/load_balancing/client/main.go#L77); and shouldn't affect existing setups.

### Is this a feature you are interested in implementing yourself?

Yes

**Comment by JorTurFer** [comment]
I'd say that this is already done xD
