### ISSUE TITLE
keda should scale from zero when minReplicaCount is set

### ISSUE THREAD

**Issue by ekcasey** [kedacore/keda#523]
`keda` does not respect `scaledobject.spec.minReplicaCount` when the actual deployment has 0 replicas.

## Expected Behavior
If `scaledobject.spec.minReplicaCount` is set to `n`, `keda` should ensuring that the deployment has at least `n` replicas, scaling from 0 if necessary.

## Actual Behavior
If a deployment is has `minReplicaCount` but was initially created with 0 replicas, `minReplicaCount` is not respected and the deployment is not scaled from 0.

## Steps to Reproduce the Problem

  1. create a deployment with zero replicas
  2. create a scaled object for that deployment with `minReplicaCount` equal to 1
  3. observe that the deployment remains at 0 replicas

## Specifications

  - **Version:** v1.0.0 and master
  - **Scaler(s):** all

**Comment by zroubalik** [comment]
thanks @ekcasey good catch, will take a look at this

**Comment by anirudhgarg** [comment]
Looks like this is merged.
