### ISSUE TITLE
Activation value for redis lists scaler is not working as expected

### ISSUE THREAD

**Issue by petr-buchyn** [kedacore/keda#5231]
### Report

I defined `ScaledObject` with a `redis` trigger. I set `activationValue` to 1, and I expect that my deployment will get scaled from 0 to 1 replica when there is at least 1 message in corresponding Redis list. However, it gets scaled when there are 2 or more messages in a queue. In the code of the Redis scaler I found that it is the case, since the condition being used in code is "greater than", not "greater than or equal to". I understand that this condition is valid in case of 0 messages, however it is counter-intuitive in case of any other number of messages. Is this expected behavior, or should I open PR in order to fix this?

### Expected Behavior

I expect that if I set `activationValue` to 1, deployment will get scaled after the queue has 1 message. If that is not expected behavior, I think it should be added to docs.

### Actual Behavior

If I set `activationValue` to 1, deployment does not get scaled until there is 2 or more messages in a queue.

### Steps to Reproduce the Problem

1. Define `ScaledObject` for the deployment that uses Redis lists as queues.
2. Set `activationValue` to 1.
3. Add 1 message to Redis list.
4. See as deployment does not get scaled.
5. Add another message to Redis list.
6. Observe as deployment gets scaled.

### KEDA Version

2.11.2

### Kubernetes Version

1.27

### Platform

Amazon Web Services

### Scaler Details

Redis Lists

**Comment by JorTurFer** [comment]
Hello,
This is the expected behavior and it's how all the scalers work. I think that we should improve the documentation if it's not clear how it works, but I'd not change the code because it's a breaking change.
Are you willing to open a PR to docs? I guess that the correct place for it can be here: https://keda.sh/docs/2.12/concepts/scaling-deployments/#activating-and-scaling-thresholds
