### ISSUE TITLE
Provide capability to get configuration from outside of scaledjob/scaledobject to configure triggers

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda#5233]
### Proposal

Provide capability to get configuration from outside of scaledjob to configure triggers in a consistent manner across scalers.

Open requests: 
- Get from config map: https://github.com/kedacore/keda/issues/5229
- Get from environment variables: https://github.com/kedacore/keda/issues/4965

### Is this a feature you are interested in implementing yourself?

No

**Comment by tomkerkhove** [comment]
^ @arapulido here is what you are looking for, but we probably need a design and samples of what it would look like

**Comment by panditha** [comment]
I am also looking for a global settings (may be a configmap) where we can customise the default values. For example I am looking for setting default polling interval to a value (other than 30 seconds) globally which will be applied on each scalars that don't explicitly define a polling interval. I think this is very common pattern/practice in Kubernetes to have global configmap to customise default settings.

**Comment by aslafy-z** [comment]
Any chance this issue gets reopened?

**Comment by blakestoddard** [comment]
> Is this really a use case?

I rely heavily on the Prometheus scaler, where the serverAddress is an APM workspace that is specific to the cluster. Currently, service owners of workloads in the cluster (many workloads per cluster) must manually find the workspace query address in the AWS Console and set it in their `ScaledObject` triggers, even though the Terraform that creates the APM workspace also creates a ConfigMap in the cluster with the query URL (repeat times hundreds of clusters with the same ConfigMap name in each). This ConfigMap could be referenced in the trigger to reduce cognitive overhead of setting up a ScaledObject trigger by a service team.

The [AMP example in the Prometheus trigger](https://keda.sh/docs/2.16/scalers/prometheus/#example-amazon-managed-service-for-prometheus-amp) docs actually show a model that would work great (configuring region and workspace ID as variables) if you could declare vars via ConfigMap mount on a ScaledObject:
```
metadata:
  awsRegion: {{.AwsRegion}}
  serverAddress: "https://aps-workspaces.{{.AwsRegion}}.amazonaws.com/workspaces/{{.WorkspaceID}}"
```
