### ISSUE TITLE
Documentation seems wrong regarding kubernetes compatibility

### ISSUE THREAD

**Issue by nadavbuc** [kedacore/keda#5252]
### Report

When i've upgraded kubernetes cluster from 1.25 to 1.26 - we noticed a steep increase in Keda Errors
According to the documentation the running version (2.10) should support kubernetes 1.26 - seems like not all scaling triggered correctly as well

All errors were gone when Keda was upgraded to 2.12

### Expected Behavior

Kubernetes upgrade should not have affected Keda
according to the [Compatibility Matrix](https://keda.sh/docs/2.12/operate/cluster/)

### Actual Behavior

Many Keda errors, reported many timeouts in the logs
Not all scaling would trigger

### Steps to Reproduce the Problem

1. Install keda 2.10 on kubernetes 1.25
2. create scaled objects
3. upgrade to 1.26
4. errors 

### KEDA Version

2.10.0

### Kubernetes Version

1.26

### Platform

Amazon Web Services

### Scaler Details

Multiple

### Anything else?

I suggest modifying the compatibility matrix - i don't think 1.10 supports kubernetes 1.26
It does seem like 1.11 changelog mentions support for this version

**Comment by JorTurFer** [comment]
Hello
I can confirm that 2.10 works on 1.26 because we executed smoke tests on it, checking all the k8s integrations. What errors are you seeing? Maybe there is an upgrade issue that we didn't notice, but fresh installations work, 100% sure.
Could you share the logs from KEDA operator and KEDA metrics server?

**Comment by nadavbuc** [comment]
Hey Yes - i just got back to this ticket to update
seems the issue is not with keda but with the chagnes on the native HPA Object
I will close this issue now
