### ISSUE TITLE
Processing of ScaledJobs intermittently halts at random intervals (trigger: Azure Service Bus)

### ISSUE THREAD

**Issue by JitseHijlkema** [kedacore/keda#5283]
### Report

I'm encountering stability issues with KEDA;

Our goal is for KEDA to trigger a job (max one simultaneously) whenever there are one or more messages in the Azure Service Bus queue and consistently process new jobs. While jobs are indeed being processed, the job processing encounters standstill at random moments.

### Expected Behavior

Our objective is to have KEDA initiate a job (max one simultaneously) whenever there are one or more messages in the Azure Service Bus queue and persistently processing new jobs.

### Actual Behavior

Initially, this works as intended, but after several runs, KEDA unexpectedly ceases to initiate new jobs. 
Log entries for polling the ScaledObject also come to a halt. This issue manifests intermittently, occurring either after a few successful job executions or after more than 10 consecutive successful jobs.

During the periods when KEDA stops processing this ScaledJob, I'm unable to identify any errors in the logging, even after raising the logging level to debug. It's noteworthy that other KEDA scaling activities continue to function properly during these instances. 

The KEDA operator seamlessly resumes processing upon restarting the operator or recreating the ScaledJob resource.

### Steps to Reproduce the Problem

Waiting for a couple of jobs to be processed. I observe this mostly happening between 3 and 15 runs.

### Logs from KEDA operator

```
2023-12-12T15:20:44Z    DEBUG   scalemetrics    Checking if ScaleJob Scalers are active {"ScaledJob": "planningcreator-scaledobject", "isActive": true, "maxValue": 1, "MultipleScalersCalculation": ""}
2023-12-12T15:20:44Z    INFO    scaleexecutor   Scaling Jobs    {"scaledJob.Name": "planningcreator-scaledobject", "scaledJob.Namespace": "ns-t-app-inter", "Number of running Jobs": 1}
2023-12-12T15:20:44Z    INFO    scaleexecutor   Scaling Jobs    {"scaledJob.Name": "planningcreator-scaledobject", "scaledJob.Namespace": "ns-t-app-inter", "Number of pending Jobs ": 0}
2023-12-12T15:20:44Z    DEBUG   scaleexecutor   Selecting Scale Strategy        {"scaledJob.Name": "planningcreator-scaledobject", "scaledJob.Namespace": "ns-t-app-inter", "specified": "", "selected": "default"}
2023-12-12T15:20:44Z    DEBUG   scaleexecutor   At least one scaler is active   {"scaledJob.Name": "planningcreator-scaledobject", "scaledJob.Namespace": "ns-t-app-inter"}
2023-12-12T15:20:44Z    INFO    scaleexecutor   Creating jobs   {"scaledJob.Name": "planningcreator-scaledobject", "scaledJob.Namespace": "ns-t-app-inter", "Effective number of max jobs": 0}
2023-12-12T15:20:44Z    INFO    scaleexecutor   Creating jobs   {"scaledJob.Name": "planningcreator-scaledobject", "scaledJob.Namespace": "ns-t-app-inter", "Number of jobs": 0}
2023-12-12T15:20:44Z    INFO    scaleexecutor   Created jobs    {"scaledJob.Name": "planningcreator-scaledobject", "scaledJob.Namespace": "ns-t-app-inter", "Number of jobs": 0}
2023-12-12T15:20:44Z    DEBUG   events  Created 0 jobs  {"type": "Normal", "object": {"kind":"ScaledJob","namespace":"ns-t-app-inter","name":"planningcreator-scaledobject","uid":"37a6e4db-2ad8-4f4e-ac0b-2bf42e6e860d","apiVersion":"keda.sh/v1alpha1","resourceVersion":"120134194"}, "reason": "KEDAJobsCreated"}
[ processing stops ]
```

### KEDA Version

2.11.2

### Kubernetes Version

1.27

### Platform

Microsoft Azure

### Scaler Details

Azure Service Bus

### Anything else?

**ScaledJob:**
```
apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  labels:
    app.kubernetes.io/instance: int-test
  name: int-test-planningcreator-scaledobject
  namespace: ns-t-app-int
spec:
  failedJobsHistoryLimit: 5
  jobTargetRef:
    parallelism: 1
    template:
      metadata:
        annotations:
          dapr.io/app-id: planningcreator
          dapr.io/config: dapr-config
          dapr.io/enabled: 'true'
          dapr.io/env: GOMEMLIMIT=90MiB
          dapr.io/log-as-json: 'true'
          dapr.io/log-level: info
          dapr.io/sidecar-cpu-limit: 300m
          dapr.io/sidecar-cpu-request: 1.5m
          dapr.io/sidecar-memory-limit: 100Mi
          dapr.io/sidecar-memory-request: 50Mi
        labels:
          app: int
          app.kubernetes.io/instance: int-test
          app.kubernetes.io/name: planningcreator
          service: planningcreator
      spec:
        containers:
          - image: >-
              xwemgmtacrshared.azurecr.io/int/intplanningcreator:0.1.0-FixKedaAuthTrigger.1
            imagePullPolicy: IfNotPresent
            name: planningcreator
            ports:
              - containerPort: 8080
                name: http
                protocol: TCP
            resources:
              limits:
                cpu: 1600m
                memory: 10Gi
              requests:
                cpu: 15m
                memory: 10Gi
            securityContext:
              runAsGroup: 2000
              runAsNonRoot: true
              runAsUser: 1000
            volumeMounts:
              - mountPath: /root
                name: int-test-planningcreator-volume-0
                readOnly: true
        restartPolicy: Never
        securityContext: {}
        serviceAccountName: default
        volumes:
          - csi:
              driver: secrets-store.csi.k8s.io
              readOnly: true
              volumeAttributes:
                secretProviderClass: >-
                  int-test-planningcreator-secretproviderclass
            name: int-test-planningcreator-volume-0
  maxReplicaCount: 1
  minReplicaCount: 0
  pollingInterval: 10
  successfulJobsHistoryLimit: 5
  triggers:
    - authenticationRef:
        name: int-test-planningcreator-azure-servicebus-auth
      metadata:
        activationMessageCount: '0'
        messageCount: '1'
        namespace: XXX-WE-T-SVB
        subscriptionName: planningcreator
        topicName: createplanningevent
      type: azure-servicebus
```
**TriggerAuth**
```
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  labels:
    app.kubernetes.io/instance: int-test
  name: int-test-planningcreator-azure-servicebus-auth
  namespace: ns-t-app-int
spec:
  secretTargetRef:
    - key: connection
      name: int-test-planningcreator-servicebus-endpoint
      parameter: connection
```

**Comment by JorTurFer** [comment]
Hello,
What does `processing stops` mean? no more logs? no more logs related? 
Are you scrapping Prometheus metrics generated by KEDA? Which is the value of this metric `keda_internal_scale_loop_latency` in for that ScaledJob?
are there more logs that you can share?

**Comment by JitseHijlkema** [comment]
Hi,

Thanks for your reply.

With 'processing stops' I mean that there are no more new jobs created (with still items in ServiceBus) and no more log entries registered (also no polling logs, current PollingInterval 10s)

As of now, I don't have additional relevant logs to provide. Could you guide me to the location where I can access more logging information?

I'm not scraping KEDA metrics currently, I already planned to integrate this shortly and will subsequently provide the requested data.

**Comment by JorTurFer** [comment]
> As of now, I don't have additional relevant logs to provide. Could you guide me to the location where I can access more logging information?

If the log doesn't print anymore, there isn't any other source for the metrics. Could you upgrade KEDA to v2.12.1? We have fixed a [critical issue](https://github.com/kedacore/keda/issues/5083) that could match with the behavior you are facing in some cases (related with issues starting some scalers and locked cache due to a deadlock). 

If after upgrading to KEDA v2.12.1 the issue persists, we will need the information from the generated prometheus metrics

**Comment by JitseHijlkema** [comment]
I can confirm that it has been stable since the upgrade.
I'm closing this issue. 

Thank you @JorTurFer
