### ISSUE TITLE
Azure event hub with kafka to get unprocessed events.

### ISSUE THREAD

**Issue by gudipudipradeep** [kedacore/keda#5291]
### Proposal

consumer application using <"Confluent.Kafka" Version="2.2.0" /> library for cost reduction and some more reasons from application team.
As devops engineer what other option we have to read unprocessed events. does Apache kafka keda support Azure event hub..?
Please share your thoughts with some sample on it.

### Use-Case

Our consumer application using Confluent.Kafka. to get the unprocessed  event we need the blog with partition file. but  Confluent.Kafka will taken care about the partition and offsets.

does apache kafka keda api support Azure event hub.. if yes please share some guidelines on it

### Is this a feature you are interested in implementing yourself?

No

**Comment by JorTurFer** [comment]
Hello,
I'm not sure because I haven't testes it. I think that it works as Azure EventHub has Kafka API compatibility mode, so it should work. You can give a try and share your experience. You also have a Specific Azure EvenHub scaler if you need it

**Comment by gudipudipradeep** [comment]
@JorTurFer Specific Azure EvenHub scaler is not working because we need partition file in the blob storage. if it work with kafka api no need to maintain partition file in the blob storage.

**Comment by gudipudipradeep** [comment]
```python
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: iothubinternal-eventhub-scaledobject
  namespace: evt
spec:
  scaleTargetRef:
    name: opintel-common-event-listener-iothubinternal-v1
  cooldownPeriod: 300 #Time in seconds after which Pods should be scaled down to minReplicaCount
  pollingInterval: 30 #Time in seconds after which HPA should check for unprocessed event in the Event Hub
  minReplicaCount: 1
  maxReplicaCount: 6
  triggers:
    - type: kafka
      metadata:
        bootstrapServers: devcaidcdeviceeventspipeline.servicebus.windows.net:9093
        eventHubName: opintel-evt-iot-hub #Internal Event Hub of IOTHub 
        consumerGroup: evt
        topic: opintel-evt-iot-hub
        lagThreshold: "10"
        offsetResetPolicy: latest
        tls: enable
        sasl: plaintext
        authenticationRef:
          name: keda-trigger-auth-kafka-credential
---
apiVersion: v1
kind: Secret
metadata:
  name: keda-kafka-secrets
  namespace: default
data:
  authMode: "org.apache.kafka.common.security.plain.PlainLoginModule"
  username: "$ConnectionString"
  password: "password"
---
apiVersion: keda.k8s.io/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-trigger-auth-kafka-credential
  namespace: default
spec:
  secretTargetRef:
  - parameter: authMode
    name: keda-kafka-secrets
    key: authMode
  - parameter: username
    name: keda-kafka-secrets
    key: username
  - parameter: password
    name: keda-kafka-secrets
    key: password
``` 
above steps I have done for kafka with azure event hub. still getting failures.

**Comment by JorTurFer** [comment]
What failures do you have?
Using EventHub Scaler, have you checked the legacy checkpointer (which doesn't use storage) https://keda.sh/docs/2.12/scalers/azure-event-hub/#checkpointing-behaviour?

**Comment by gudipudipradeep** [comment]
![image](https://github.com/kedacore/keda/assets/8638634/d9a0c96f-47d1-4996-86a6-6ca8988aa413)
some time its in Ready state is True or some time its in False fluctuating.

**Comment by gudipudipradeep** [comment]
[keda-operator-7f4cbd5d8b.log](https://github.com/kedacore/keda/files/13700535/keda-operator-7f4cbd5d8b.log)
[keda-operator-67665bbbf5.log](https://github.com/kedacore/keda/files/13700536/keda-operator-67665bbbf5.log)

**Comment by JorTurFer** [comment]
Honestly, I have no idea if Kafka scaler can be used for Azure EventHub...
@v-shenoy @tomkerkhove , do you have any idea?

**Comment by tomkerkhove** [comment]
Yes you can, but I believe it's using the Kafka protocol so not sure what scaler to use to be honest :)

https://learn.microsoft.com/en-us/azure/event-hubs/azure-event-hubs-kafka-overview

**Comment by gudipudipradeep** [comment]
@tomkerkhove As per above documentation I setup the kafka kuda deployment. but not working. shared logs along with deployment file. Please can you help on this.
