### ISSUE TITLE
Keep track of k8s api server usage

### ISSUE THREAD

**Issue by yaron2** [kedacore/keda#53]
This issue is to examine KEDA's CPU and Memory implications in regards to the Kubernetes API server.
This is to ensure that KEDA does not cause over-utilization of the API server, as it communicates in a bi-di manner with the API server (KEDA controller being asked for metrics and looking up Kubernetes objects using the Kubernetes API).

**Comment by tomkerkhove** [comment]
@yaron2 can you provide some info on this issue please?

**Comment by yaron2** [comment]
Updated the description.

**Comment by zroubalik** [comment]
We should set limits on the containers as well.

**Comment by yaron2** [comment]
@zroubalik yes that's a must. a potential memory leak or CPU hog in KEDA should not drain the node running it.

**Comment by tomkerkhove** [comment]
Great, thanks for the update!
