### ISSUE TITLE
Emit Kuberentes Events on major KEDA events

### ISSUE THREAD

**Issue by zroubalik** [kedacore/keda#530]
KEDA controller should emit Kuberentes Events on major events. This is based on #479 

### Use-Cases
- New Trigger Authentication Created
- Deployment Scaled to Zero
- New Scaled Object Created
- Information on scaling action
- Information about new scaled object referencing existing trigger authentication
- ...

**Comment by anirudhgarg** [comment]
Just curious are these just logs or there is something else first class that you are thinking ?

**Comment by tomkerkhove** [comment]
These are events similar which you can process in other applications, for example to extend KEDA, create awareness around scaling patterns (ie post to Slack), react to certain things, etc.

**Comment by anirudhgarg** [comment]
Sorry my question was that what would be the implementation to emit these "events" - would we just need to add the right logs at various places in the code.

**Comment by tomkerkhove** [comment]
That is a good question, I don't know the answer to that or if it's possible.

**Comment by zroubalik** [comment]
@anirudhgarg yes, that should be the case.

**Comment by tomkerkhove** [comment]
This would be a major feature if you ask me!

Can we target 2.0 for this @zroubalik @ahmelsayed @jeffhollan @anirudhgarg ?

**Comment by tomkerkhove** [comment]
Docs: https://github.com/kedacore/keda-docs/pull/361
