### ISSUE TITLE
Keda Kafka lagThreshold error in parsing

### ISSUE THREAD

**Issue by altrack** [kedacore/keda#5354]
### Report

When using a Keda Kafka scaler with `lagThreshold` argument as `1000000` I'm getting the following error:
```
keda-operator  error parsing kafka metadata: error parsing lagThreshold: strconv.ParseInt: parsing "1e+06": invalid 
```
syntax
```__

### Expected Behavior

Should parse numbers correctly.

### Actual Behavior

Not able to parse or parsing as: `1e+06`

### Steps to Reproduce the Problem

1. set lagThreshold as 1000000
2. kubectl  describe scaledobjects.keda.sh <your-topic>


### Logs from KEDA operator

_No response_

### KEDA Version

None

### Kubernetes Version

None

### Platform

Google Cloud

### Scaler Details

Kafka

### Anything else?

If the bug is related to another repo please let me know, I'll move it.

**Comment by dttung2905** [comment]
Hi @altrack seems like the number `1000000` is converted to scientific notation which makes `strconv.ParseInt` throw error. I have a few questions
- Did you wrap the deployment of scaleObject around another helm deployment ? Helm has been (in)famous for that [link](https://helm.sh/docs/chart_best_practices/values/#make-types-clear)
- What is the KEDA version you are using? I'm testing with a latest version of KEDA from main and it works fine. I also added a test case into this and run locally but that new test case also passes :thinking: https://github.com/kedacore/keda/blob/c5fa2ba5c17e72d1412c0d83893aa9206dda70ca/pkg/scalers/apache_kafka_scaler_test.go#L64

**Comment by zroubalik** [comment]
@dttung2905 thanks for the investigation, could you please open a PR with that test case, just to be sure? We should test this for both Kafka scalers (sarama and go based).

**Comment by dttung2905** [comment]
Hello @altrack , did you manage to resolve the issue by following the suggestion above?

**Comment by altrack** [comment]
Hey @dttung2905 , thank you for checking this and writing the test.
Unfortunately, I don't know the answers yet, it will take some time to check this.
I'll try to use a string instead.

**Comment by dttung2905** [comment]
> Hey @dttung2905 , thank you for checking this and writing the test. Unfortunately, I don't know the answers yet, it will take some time to check this. I'll try to use a string instead.

Yes, please use a string instead as it might be converted to scientific notation :sweat_smile: . Do let us know if it works

**Comment by altrack** [comment]
Sorry for the delay.
Yes, converting to string worked as expected.
The issue was caused since in one of the Helm definition I had `lagThreshold: {{ .Values.keda.kafka.lagThreshold | quote }}`, so this caused the conversion.
Thanks for the answers.
