### ISSUE TITLE
unable to configure scaledobject triggers based on cpu or memory 

### ISSUE THREAD

**Issue by Lokeshmaxi** [kedacore/keda#5357]
### Proposal

I have needed cpu and memory based  supported scaledobject triggers , because i have already using kafka triggers, but we need cpu and memory as well , when i tried to add new triggers based on cpu and memory,it is throwing error "* <nil>: Invalid value: "The edited file failed validation": ValidationError(ScaledObject.spec.triggers[0]): unknown field "metricType" in sh.keda.v1alpha1.ScaledObject.spec.triggers", please help me to resolve this.

### Use-Case

I have needed cpu and memory based  supported scaledobject triggers , because i have already using kafka triggers, but we need cpu and memory as well .i have attached screenshot of the trigger spec that i have configured.

### Is this a feature you are interested in implementing yourself?

No

### Anything else?

<img width="1415" alt="image" src="https://github.com/kedacore/keda/assets/91049865/07025743-ae93-49e0-882c-cc0974416380">

**Comment by JorTurFer** [comment]
What KEDA version are you using?

**Comment by Lokeshmaxi** [comment]
Im using version  keda-2.0.0,	image tag:   docker.io/kedacore/keda:2.0.0

**Comment by JorTurFer** [comment]
That version is quite old so I'd suggest upgrading to a recent version, but if you can't or don't want (which is legit), docs are versioned.
Please filter for your current version: https://keda.sh/docs/2.0/scalers/cpu/

In KEDA 2.0.0 the property metricType didn't exist. I close this as solved because there isn't any error

**Comment by keyurbitw** [comment]
Sample CPU Scaler for Keda 2.0.0 : https://keda.sh/docs/2.0/scalers/cpu/
