### ISSUE TITLE
Supporting Kubernetes recommended labels

### ISSUE THREAD

**Issue by Cottonglow** [kedacore/keda#536]
Kubernetes recommends some  [shared labels](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/#labels) to apply to resources to help manage the cluster. Some of the KEDA resources either don't have any labels at all or are a bit lacking, making them harder to manage.

The HPA that is created by KEDA also doesn't have any labels and these labels could help differentiate it from self-managed HPAs.

### Use-Case

These are the labels that Kubernetes recommends to add to the resources:
```yml
app.kubernetes.io/name
app.kubernetes.io/instance
app.kubernetes.io/version
app.kubernetes.io/component
app.kubernetes.io/part-of
app.kubernetes.io/managed-by
```

What are the thoughts on this and/or is this planned for KEDA in the future?

**Comment by tomkerkhove** [comment]
I like the idea! Most of it should be done via our chart/operator but our HPAs should have them as well.

**Comment by Cottonglow** [comment]
I can have a look at adding them, and then we can discuss in the PR what labels/values we want to keep or use.
