### ISSUE TITLE
Datadog trigger is being included into the composite-metric unexpectedly.

### ISSUE THREAD

**Issue by devkoriel** [kedacore/keda#5367]
### Report

I am using scalingModifiers to make composite-metric using metric-api triggers but when I add datadog trigger metric, it's also forced to be included into composite-metric not as I expected.

### Expected Behavior

I expected the new external section to be added in HPA.

### Actual Behavior

I am using scalingModifiers to make composite-metric using metric-api triggers but when I add datadog trigger metric, it's also forced to be included into composite-metric not as I expected.

### Steps to Reproduce the Problem

1. Use composite-metric by adding scalingModifier.
2. Add datadog trigger.
3. It happens.

### Logs from KEDA operator

```
2024-01-12T03:54:29Z	ERROR	scale_handler	error pairing triggers & metrics for compositeScaler	{"scaledObject.Namespace": "engine", "scaledObject.Name": "engine-open-api", "error": "trigger name not given with compositeScaler for metric s4-datadog-sum-kubernetes_state-deployment-replicas_desired"}
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).getScalerState
	/workspace/pkg/scaling/scale_handler.go:744
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).getScaledObjectState
	/workspace/pkg/scaling/scale_handler.go:590
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).checkScalers
	/workspace/pkg/scaling/scale_handler.go:241
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).startScaleLoop
	/workspace/pkg/scaling/scale_handler.go:180
```

### KEDA Version

2.12.1

### Kubernetes Version

1.26

### Platform

Amazon Web Services

### Scaler Details

kubernetes-workload, metrics-api, cpu, datadog

### Anything else?

We are operating k8s using kops on AWS.

**Comment by JorTurFer** [comment]
Hello,
This is done as design, when you work with scaling modifiers, all the triggers are treated as sources for the formula.
I see that you are using CPU trigger too, but it is not supported for composition

**Comment by devkoriel** [comment]
@JorTurFer Thank you for guiding. However, for now, I have to use cron trigger with scalingModifiers. Any workarounds or plans for this feature?

**Comment by JorTurFer** [comment]
I don't think so, because it makes the things quite complex (which metrics, why onyl one formula, etc), but I'd like to know the thoughts from @zroubalik  and @tomkerkhove

**Comment by zroubalik** [comment]
Yeah, I am also inclined towards what @JorTurFer mentioned. The original desing of ScalingModifiers have been done this way. It would be extremely complicated. Just include it into the formula.
