### ISSUE TITLE
`make deploy` shouldn't enable opentelemetry by default

### ISSUE THREAD

**Issue by zroubalik** [kedacore/keda#5375]
### Proposal

`make deploy` is usually used for development purposes of KEDA. With some recent changes, if one run this command, KEDA is configured to enable opentelemery collector.

We should revisit this approach and don't enforce opentelemetry usage. `make deploy` is also used to run e2e tests in our infra - there is enabling the opentelemetry collector expected.
https://github.com/kedacore/keda/blob/5648b5702ae30fa295f231eb1684f2f5f37127f6/tests/utils/setup_test.go#L220

### Is this a feature you are interested in implementing yourself?

Maybe

**Comment by SpiritZhou** [comment]
I think we can add a flag like AZURE_RUN_AAD_POD_IDENTITY_TESTS to enable/disable opentelemetry.
