### ISSUE TITLE
Add new partners to the website / README

### ISSUE THREAD

**Issue by jeffhollan** [kedacore/keda#539]
As KEDA has grown we've had a bunch of great partnership and contribution from the community far outside just the listed sponsors of Red Hat and Microsoft.  More than happy to add logos from other companies that have contributed time into the project (through code or otherwise).  Creating this issue to start to capture nominations or ideas for these.

**Comment by tomkerkhove** [comment]
We are tracking this on https://github.com/kedacore/keda-docs/issues/65 as well.

Ok if we close this one as this is a duplicate? Feels overkill to list them on the repo here, no?

**Comment by zroubalik** [comment]
@tomkerkhove agree, closing this one.
