### ISSUE TITLE
Ability to auto-scale database pods

### ISSUE THREAD

**Issue by imdmahajankanika** [kedacore/keda#5390]
### Proposal

Hello ! I am trying to explore KEDA. I am wondering if I can use KEDA for auto-scaling of two tier application ( application and database) 

I found that with http event based scaling, it is possible to scale up the application pod but is there a way to do the same for database (for ex MySQL) pod also?

I mean if it is possible to scale up a pod only when someone tries to connect to database

### Is this a feature you are interested in implementing yourself?

No

**Comment by tomkerkhove** [comment]
Vertical scaling is tracked in https://github.com/kedacore/keda/issues/1788 and you may be interested in https://github.com/kedacore/keda/issues/5232 as well
