### ISSUE TITLE
Weighted triggers when using multiple triggers for the same scale target

### ISSUE THREAD

**Issue by hitsub2** [kedacore/keda#5395]
### Proposal

Followed the best pratice of "Using multiple triggers for the same scale target", that would be great if weight trigger is supported. With weight trigger, we can set one trigger's activationThreshold to 0 with low priority of weight, and another trigger(based on application qps) has higher activationThreshold and weight.

When the scale from 0, the low priority of weight trigger is activeted and scale up as needed.

### Use-Case

There is a scenario that we want to scale from 0 based the application of qps.When scale to 0, the trigger based on qps or any  other application's internal metrics can not be scaled up.

### Is this a feature you are interested in implementing yourself?

No

### Anything else?

a disccusion related: https://github.com/kedacore/keda/discussions/1840

**Comment by JorTurFer** [comment]
Hello,
I don't see your user case. Currently, if any scaler is active, the workload is scaled from 0, so you could scale to 0 if there isn't any active scaler and scale from 0 if there is any scaler active.
If you need more complexity, you can evaluate scaling modifiers: https://keda.sh/docs/2.13/concepts/scaling-deployments/#scaling-modifiers-experimental
Using it, you could write your own formula to fit your scenario.

Given that, HTTP scaling is quite different and you need to take into account other factors like holding the request for cold starts and so on.
