### ISSUE TITLE
Refactor ScaledObject webhook

### ISSUE THREAD

**Issue by zroubalik** [kedacore/keda#5397]
### Proposal

Minor refactoring, see details in https://github.com/kedacore/keda/pull/5377#discussion_r1455488231

### Is this a feature you are interested in implementing yourself?

No

**Comment by wozniakjan** [comment]
I will have the PR ready as soon as https://github.com/kedacore/keda/pull/5377 closes, keeping the changes locally for now and will rebase right after the merge :)
