### ISSUE TITLE
Use Operator SDK

### ISSUE THREAD

**Issue by yaron2** [kedacore/keda#54]
Waiting for https://github.com/Azure/Kore/pull/47 and https://github.com/Azure/Kore/pull/41.

**Comment by zroubalik** [comment]
Are there any updates on this issue? If not, I can start working on this.

**Comment by jeffhollan** [comment]
@yaron2 any updates here? Do you have a more recent ETA?  @zroubalik has offered to help as well in our weekly stand up

**Comment by zroubalik** [comment]
@jeffhollan this can be closed since the PR is merged. I am not able to close this issue.
