### ISSUE TITLE
Add flag in Adapter and Operator to disable TLS on the GRPC connection

### ISSUE THREAD

**Issue by aliaqel-stripe** [kedacore/keda#5408]
### Proposal

We use Envoy, an internally built CA, and a networking model that does not use standard Kubernetes networking. Therefore, to achieve mTLS between pods, we use Envoy and need to turn off TLS verification in the service code. 

I would like to add a command-line flag to the adapter and operator called `insecure-metrics-service-skip-tls-verify` that when `true`, disables TLS credentials in the GRPC client and server. 

### Use-Case

For users of KEDA where TLS is handled by a proxy, disabling TLS in the GRPC client and server enables GRPC to work over a proxied connection.

### Is this a feature you are interested in implementing yourself?

Yes

**Comment by aliaqel-stripe** [comment]
Found a way to do this without disabling TLS

**Comment by 1it** [comment]
> Found a way to do this without disabling TLS

How did you do that, exactly? 
I'm trying to integrate Keda with Istio Mesh, any tip could be useful (for many people).

**Comment by aliaqel-stripe** [comment]
@1it I actually bypassed the mesh and relied on mTLS within KEDA. I also used [this flag](https://github.com/kedacore/keda/blob/main/cmd/adapter/main.go#L268) that I added to override the GRPC authority header to match the identity I expect to be in the returned certifcate.

Additionally, our Envoy mesh has support for adding an HTTPS endpoint to the client side proxy. I was able to add that for other uses. As istio is based on Envoy, you can look into adding an HTTPS listener, too.
