### ISSUE TITLE
Unable to use RabbitMQ target. Issue parsing RabbitMQ host.

### ISSUE THREAD

**Issue by PixelRobots** [kedacore/keda#542]
When trying to use this with RabbitMQ I am unable to create the HPA. It seems it has issues parsing rabbitmq host. I have tried it as a secret and also hardcoded into the yaml file. Fresh cluster running newest version of Keda.

## Expected Behavior
connect to rabbitMQ cluster and create HPA

## Actual Behavior
Unable to connect to rabbitMQ cluster and unable to create HPA.

## Steps to Reproduce the Problem

  1.RabbitMQ cluster running in AKS
  2. Deployment created that I want to scale.
  3.Apply yaml file to create HPA

## Specifications

  - Kubernetes v1.14.8
  - AKS
  - RabbitMQ

ScalledObject Yaml:

apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: deploymentname
  labels:
    deploymentName: deploymentname
spec:
  scaleTargetRef:
    deploymentName: deploymentname
  pollingInterval: 30   # Optional. Default: 30 seconds
  cooldownPeriod: 300   # Optional. Default: 300 seconds
  minReplicaCount: 1   # Optional. Default: 0
  maxReplicaCount: 10  # Optional. Default: 100
  triggers:
  - type: rabbitmq
    metadata:
      host: 'amqp://user:password@rabbitmq.default.svc.cluster.local:5672/vhost'
      queueName: queuename
      queueLength  : '5'

Error message:
{"level":"error","ts":1579098533.850565,"logger":"controller_scaledobject","msg":"Error getting scalers","Request.Namespace":"default","Request.Name":"libreconverter","error":"error getting scaler for trigger #0: error parsing rabbitmq metadata: no host setting given","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\ngithub.com/kedacore/keda/pkg/controller/scaledobject.(*ReconcileScaledObject).getScaledObjectMetricSpecs\n\tkeda/pkg/controller/scaledobject/scaledobject_controller.go:329\ngithub.com/kedacore/keda/pkg/controller/scaledobject.(*ReconcileScaledObject).newHPAForScaledObject\n\tkeda/pkg/controller/scaledobject/scaledobject_controller.go:296\ngithub.com/kedacore/keda/pkg/controller/scaledobject.(*ReconcileScaledObject).reconcileDeploymentType\n\tkeda/pkg/controller/scaledobject/scaledobject_controller.go:202\ngithub.com/kedacore/keda/pkg/controller/scaledobject.(*ReconcileScaledObject).Reconcile\n\tkeda/pkg/controller/scaledobject/scaledobject_controller.go:146\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.2.2/pkg/internal/controller/controller.go:216\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.2.2/pkg/internal/controller/controller.go:192\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.2.2/pkg/internal/controller/controller.go:171\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190404173353-6a84e37a896d/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190404173353-6a84e37a896d/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190404173353-6a84e37a896d/pkg/util/wait/wait.go:88"}

Thanks

Richard

**Comment by tomkerkhove** [comment]
Good to see the issue was resolved, can we improve the docs around this to help you in the future?

**Comment by justindavies** [comment]
I'd love to know how this was resolved too as I'm getting the same issue with hardcoded and with Secret B64 encoded
