### ISSUE TITLE
Keda prometheus trigger keeps returning empty results though present 

### ISSUE THREAD

**Issue by sreeboppana** [kedacore/keda#5432]
### Report

keda-operator:
           Image:      ghcr.io/kedacore/keda:2.12.0

API Version:  keda.sh/v1alpha1 

PrometheusQuery:         kaka_query{topic="event.x-y.v1"} offset 2m

The prometheus query keeps returning Zero (0) though query is valid and data is present  But a curl returns data fine for the same.
  "s0-prometheus" (target average value):                 0 / 3900m

$ kubectl describe hpa -n <>
```
Metrics:                                                  ( current / target )
  "s0-prometheus" (target average value):                 0 / 3900m
  resource memory on pods  (as a percentage of request):  23% (62131814400m) / 10%
  resource cpu on pods  (as a percentage of request):     6% (19m) / 10%
Min replicas:                                             3
Max replicas:                                             10
Rollout pods:                                             10 current / 10 desired
Conditions:
  Type            Status  Reason            Message
  ----            ------  ------            -------
  AbleToScale     True    ReadyForNewScale  recommended size matches current size
  ScalingActive   True    ValidMetricFound  the HPA was able to successfully calculate a replica count from memory resource utilization (percentage of request)
  ScalingLimited  True    TooManyReplicas   the desired replica count is more than the maximum replica count
Events:           <none>```

$ kubectl describe scaledobject -n <>
```yaml
API Version:  keda.sh/v1alpha1
Kind:         ScaledObject
  Scale Target Ref:
    API Version:  argoproj.io/v1alpha1
    Kind:         Rollout
    Name:         ltb-golang-microservice
  Triggers:
    Metadata:
      Aws Region:          us-east-1
      Identity Owner:      operator
      Ignore Null Values:  true
      Query:               kaka_query{topic="event.x-y.v1"} offset 2m
      Server Address:      ServerAddress 
      Threshold:           3.9
      Unsafe Ssl:          true
    Type:                  prometheus
    Metadata:
      Value:      10
    Metric Type:  Utilization
    Type:         cpu
    Metadata:
      Value:      10
    Metric Type:  Utilization
    Type:         memory
Status:
  Conditions:
    Message:  ScaledObject is defined correctly and is ready for scaling
    Reason:   ScaledObjectReady
    Status:   True
    Type:     Ready
    Message:  Scaling is not performed because triggers are not active
    Reason:   ScalerNotActive
    Status:   False
    Type:     Active
    Message:  No fallbacks are active on this scaled object
    Reason:   NoFallbackFound
    Status:   False
    Type:     Fallback
    Status:   Unknown
    Type:     Paused
```

### Expected Behavior

successful query should return:
value: 4

{"status":"success","data":{"resultType":"vector","result":[{"metric":{"__name__":"kafka_server_received_records","topic":"event.x-y.v1"},"value":[1705616102.962,"4"]}]}}

curl query had returned the above successful result. 
but keda scaled Object keeps reporting zero.

### Actual Behavior

keda-operator:
           Image:      ghcr.io/kedacore/keda:2.12.0

API Version:  keda.sh/v1alpha1 

PrometheusQuery:         kaka_query{topic="event.x-y.v1"} offset 2m

The prometheus query keeps returning Zero (0) though query is valid and data is present  But a curl returns data fine for the same.
  "s0-prometheus" (target average value):                 0 / 3900m

### Steps to Reproduce the Problem

1. do a curl against the prometheus endpoint.

### KEDA Version

2.12.0

### Kubernetes Version

1.25

### Platform

Amazon Web Services

**Comment by JorTurFer** [comment]
Could you share your Scaledobject?

**Comment by anipadak** [comment]
@JorTurFer We currently facing the same issue. all of a sudden Keda prometheus trigger keeps returning empty results. where as cloudwatch specific external triggers are working fine.

**keda version:**  2.11.2

**k8s-version:**  1.27

**Scaledobject:**

`apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: abc-service-scale
  namespace: infrastructure
spec:
  scaleTargetRef:
    kind: Deployment
    name: abc-service
  pollingInterval: 10
  maxReplicaCount: 4
  minReplicaCount: 4
  triggers:
  - type: prometheus
    metadata:
      metricName: http_requests_total
      serverAddress: http://kube-prometheus-prometheus.observability.svc.cluster.local:9090
      query: sum(increase(http_requests_total{pod=~"abc-service-.*"}[2m]))
      threshold: "200"
  - type: memory
    metadata:
      type: Utilization
      value: "50"
  - type: cpu
    metadata:
      type: Utilization
      value: "60"
  advanced:
    restoreToOriginalReplicaCount: true
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 300`

**Comment by sunhubs** [comment]
may I know 

> [@JorTurFer](https://github.com/JorTurFer) We currently facing the same issue. all of a sudden Keda prometheus trigger keeps returning empty results. where as cloudwatch specific external triggers are working fine.
> 
> **keda version:** 2.11.2
> 
> **k8s-version:** 1.27
> 
> **Scaledobject:**
> 
> ```
> apiVersion: keda.sh/v1alpha1
> kind: ScaledObject
> metadata:
>   name: abc-service-scale
>   namespace: infrastructure
> spec:
>   scaleTargetRef:
>     kind: Deployment
>     name: abc-service
>   pollingInterval: 10
>   maxReplicaCount: 4
>   minReplicaCount: 4
>   triggers:
>   - type: prometheus
>     metadata:
>       metricName: http_requests_total
>       serverAddress: http://kube-prometheus-prometheus.observability.svc.cluster.local:9090
>       query: sum(increase(http_requests_total{pod=~"abc-service-.*"}[2m]))
>       threshold: "200"
>   - type: memory
>     metadata:
>       type: Utilization
>       value: "50"
>   - type: cpu
>     metadata:
>       type: Utilization
>       value: "60"
>   advanced:
>     restoreToOriginalReplicaCount: true
>     horizontalPodAutoscalerConfig:
>       behavior:
>         scaleDown:
>           stabilizationWindowSeconds: 300
> ```

may I know how did you solve this finally?
