### ISSUE TITLE
Deployment scaling up to max replicas when trigger metric is null

### ISSUE THREAD

**Issue by betulbeyazoglu** [kedacore/keda#5438]
### Report

If kafka consumer group lag metric is null (when there is no offset, lag or anything for the topic in the consumer group )

- Keda hpa shows very high numbers for lag metric
- Deployments scale up to max replicas 

### Expected Behavior

When the metric for kafka consumer lag is null deployments should have the min replicas

### Actual Behavior

Keda hpa scaled up the deployment to max replicas
When we added a single msg to the topic, the keda hpa started to show correct metric and deployment instantly scaled down to 0

### Steps to Reproduce the Problem

1. Create a scaled object which has kafka trigger pointing a consumer group/topic which it has never had any msg sent to it.
2. Monitor hpa for that scaledobject

### Logs from KEDA operator

```
example
```

### KEDA Version

2.10.1

### Kubernetes Version

1.24

### Platform

Amazon Web Services

### Scaler Details

Kafka

**Comment by JorTurFer** [comment]
I missed somehow this issue :(
sorry for that

Could you share your scaled object? Are you using `fallback`? 
Maybe you can be scaling to 1 consumer per partition if you haven't disabled this:
![image](https://github.com/kedacore/keda/assets/36899226/1adc5f8a-1598-4a3a-9d63-0b5dd2eb80ed)
