### ISSUE TITLE
Add support for InfluxQL

### ISSUE THREAD

**Issue by danielwhatmuff** [kedacore/keda#5445]
### Proposal

The new version of InfluxDB (v3.0/clustered) does not support Flux queries and therefore the existing scaler cannot be used. This proposal related to adding support for scaling based on an InfluxQL query either within the existing Influx scaler by extending it, possibly with an additional parameter e.g. `queryType` or in a new scaler altogether.

### Scaler Source

Influxdb v3.0

### Scaling Mechanics

An InfluxQL query

### Authentication Source

API token

### Anything else?

Would be good to get feedback on the approach and may be able to submit a PR

**Comment by JorTurFer** [comment]
Hey!
This is a great idea! I guess that adding a new parameter to switch between old and new protocols makes sense.
Are you willing to work on this?

**Comment by danielwhatmuff** [comment]
ok great, yes either me or someone on my team can look at this

**Comment by JorTurFer** [comment]
Thanks for the update! ❤️

**Comment by zroubalik** [comment]
@danielwhatmuff great!

**Comment by danielwhatmuff** [comment]
@zroubalik @JorTurFer appreciate any feedback

https://github.com/kedacore/keda-docs/pull/1318
https://github.com/kedacore/keda/pull/5513
