### ISSUE TITLE
Remove `deploymentName` label on every `ScaledObject`

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda#545]
In #504 we've fixed an issue where we correctly log the missing `deploymentName` label on every `ScaledObject`.

However, do we still need the label? If so, what was the reason again?

Ideally, we get rid of this as it's duplicated data from `spec.scaleTargetRef.deploymentName` which is not ideal.

**Comment by tomkerkhove** [comment]
If we cannot remove it, I'll add a section on https://keda.sh/faq for it

**Comment by ppatierno** [comment]
@tomkerkhove to be honest I don't see any reason for leaving that label.
As far as I can see the entire rest of the logic leverages on the `spec.scaleTargetRef`.

**Comment by tomkerkhove** [comment]
Yes, was somewhat the consensus on #242 but added to agenda for standup before we get things going as a final verification.

**Comment by ppatierno** [comment]
So from #242 it seems that we can remove the label as mandatory field to be specified by the user but the operator has to add it for the metrics server.

**Comment by jeffhollan** [comment]
Chatted about this briefly in standup - sounds good. It doesn't sound like there is a downside to doing this

**Comment by tomkerkhove** [comment]
Are you up for it @ppatierno?

**Comment by ppatierno** [comment]
Yes, guys, I will take it over the weekend I guess.
