### ISSUE TITLE
PostreSQL scaler

### ISSUE THREAD

**Issue by dimberman** [kedacore/keda#546]
A clear and concise description of what scaler you'd like to use and how you'd want to use it:

  - **Scaler Source:** 

Scaler source would be a postGRES database

  - **How do you want to scale:** 

When the user creates the scaledObject, they would fill in a "query" parameter that accepts a string. If the string returns an integer, KEDA will autoscale to this integer. If it returns anything else, KEDA will report an error.

  - **Authentication:** 

Users will be able to place a postGRES password into a kubernetes secret for connecting to the database.

**Comment by tomkerkhove** [comment]
Thanks @dimberman!

In terms of authentication, it would be good if it supports trigger authentication so that folks who want to can use env vars as well (although they shouldn't but sometimes have to) so that it aligns with other scalers. But I presume that was your plan?

**Comment by dimberman** [comment]
Hi @tomkerkhove, 

So for the airflow use-case, we would have a unique postgres per-deployment that KEDA would be speaking to, though I can see situations where multiple deployments would want to speak to a single central PG instance.

If I follow the example of the redis_scaler, would that be sufficient?

**Comment by tomkerkhove** [comment]
Code via https://github.com/kedacore/keda/pull/553

Would you be up for documenting the new scaler in https://github.com/kedacore/keda-docs as well please?


> So for the airflow use-case, we would have a unique postgres per-deployment that KEDA would be speaking to, though I can see situations where multiple deployments would want to speak to a single central PG instance.
> 
> If I follow the example of the redis_scaler, would that be sufficient?

A bit late to reply but yes that should help you

**Comment by dimberman** [comment]
@tomkerkhove on it!

**Comment by tomkerkhove** [comment]
Docs are done, thanks!
