### ISSUE TITLE
Kafka ServiceName hard-coded instead of a config metadata item

### ISSUE THREAD

**Issue by hayscoder** [kedacore/keda#5474]
Our enterprise kafka implementation uses a different service name in each environment. Can the ServiceName be a metadata config item like so many of the other items instead of hardcoded?

https://github.com/kedacore/keda/blob/6d326c83df55c383bd572e069bfc104fbdf653c5/pkg/scalers/kafka_scaler.go#L544

**Comment by JorTurFer** [comment]
Hey,
For sure! Are you willing to open a PR with the support for it?

**Comment by hayscoder** [comment]
I asked my coworker if he could help take it on. I believe he raised a pull
request already. I will ask him to post it here for reference.

Thank you.
