### ISSUE TITLE
Unable to get Debug or detailed logging with keda operator logs.

### ISSUE THREAD

**Issue by KasyapG** [kedacore/keda#5475]
### Report

Hi,

We are trying get detailed logging on information like

When did the scaling start.
Pod information
Any specific error details.
However, Keda operator logs just show minimal info logs, we tried various ways mentioned in the blog, https://github.com/kedacore/keda/issues/3655 however all we could see is only info logs.

Could anyone please suggest the correct way or any alternative to get custom logging / debug logging on Keda operator.

Regards,
Kasyap G

### Expected Behavior

Need to show debug logs or verbose information.

### Actual Behavior

Just the plain operator logs are popping up.

### Steps to Reproduce the Problem

1. Steps mentioned in https://github.com/kedacore/keda/issues/3655 are followed.

### Logs from KEDA operator

```
example
```

### KEDA Version

2.9.1

### Kubernetes Version

None

### Platform

None

**Comment by JorTurFer** [comment]
Errors logs are already printed. Debug logs can be enabled as suggested in the link you sent, but errors are already printed. 

> When did the scaling start.

This is already displayed with info level, but only when the scaling is from/to 0 (activation phase). If you need the scaling logs during N->N, you should get the HPA Controller logs from the control plane.

> Pod information

Which kind of information would you expect to see here? Information about how KEDA is working can be scrapped using prometheus metrics: https://keda.sh/docs/2.13/operate/prometheus/

**Comment by KasyapG** [comment]
Hello 

> Errors logs are already printed. Debug logs can be enabled as suggested in the link you sent, but errors are already printed.
> 
> > When did the scaling start.
> 
> This is already displayed with info level, but only when the scaling is from/to 0 (activation phase). If you need the scaling logs during N->N, you should get the HPA Controller logs from the control plane.
> 
> > Pod information
> 
> Which kind of information would you expect to see here? Information about how KEDA is working can be scrapped using prometheus metrics: https://keda.sh/docs/2.13/operate/prometheus/

Thank you for the response, JorTurfer.

In addition to this, if we want to get the information to understand which scaler spun up the new pod. For instance, if we have Http prometheus scaler, CPU and Memory in the same scaledobject in that case how do we know which scaler started the new pod.

Could you please suggest on this?

Regards,
Kasyap G

**Comment by KasyapG** [comment]
@JorTurFer , Could you please help with below.

"Thank you for the response, JorTurfer.

In addition to this, if we want to get the information to understand which scaler spun up the new pod. For instance, if we have Http prometheus scaler, CPU and Memory in the same scaledobject in that case how do we know which scaler started the new pod.

Could you please suggest on this?

Regards,
Kasyap G"

**Comment by JorTurFer** [comment]
> In addition to this, if we want to get the information to understand which scaler spun up the new pod. For instance, if we have Http prometheus scaler, CPU and Memory in the same scaledobject in that case how do we know which scaler started the new pod.

If you need the scaling logs during N->N, you should get the HPA Controller logs from the control plane. Usually HPA Controller emit events related with that, saying which metric has triggered the scaling out, but you have to check them from the control plane
