### ISSUE TITLE
Self-signed cert errors for keda-operator-metrics-apiserver

### ISSUE THREAD

**Issue by yuanmwang-wf** [kedacore/keda#5476]
### Report

We recently upgraded keda in our cluster from 2.9.1 to 2.13 and after the upgrade we noticed sometimes our kubectl commands would have warnings like
```
E0202 10:16:00.734804   60017 memcache.go:287] couldn't get resource list for external.metrics.k8s.io/v1beta1: the server is currently unable to handle the request
E0202 10:16:00.805568   60017 memcache.go:121] couldn't get resource list for external.metrics.k8s.io/v1beta1: the server is currently unable to handle the request
E0202 10:16:00.856950   60017 memcache.go:121] couldn't get resource list for external.metrics.k8s.io/v1beta1: the server is currently unable to handle the request
E0202 10:16:00.909526   60017 memcache.go:121] couldn't get resource list for external.metrics.k8s.io/v1beta1: the server is currently unable to handle the request
```

With debug logging turned on in kubectl, we found it was encountering errors like this
```
I0202 10:18:32.600980   24474 request.go:1188] Response Body: error trying to reach service: tls: failed to verify certificate: x509: certificate is valid for localhost, localhost, not keda-operator-metrics-apiserver.workiva-system.svc
I0202 10:18:32.601463   24474 request.go:1387] body was not decodable (unable to check for Status): yaml: mapping values are not allowed in this context
E0202 10:18:32.601474   24474 memcache.go:121] couldn't get resource list for external.metrics.k8s.io/v1beta1: the server is currently unable to handle the request
```

This is the rendered helm manifest related to that api service (we don't use cert manager so I'm assuming keda used a self-signed cert)
```# Source: k8s-keda/templates/metrics-server/apiservice.yaml
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  labels:
    app.kubernetes.io/name: v1beta1.external.metrics.k8s.io
    helm.sh/chart: k8s-keda-0.1.92
    app.kubernetes.io/component: operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: keda-operator
    app.kubernetes.io/version: 2.13.0
    app.kubernetes.io/instance: k8s-keda
  name: v1beta1.external.metrics.k8s.io
spec:
  service:
    name: keda-operator-metrics-apiserver
    namespace: workiva-system
    port: 443
  group: external.metrics.k8s.io
  version: v1beta1
  groupPriorityMinimum: 100
  versionPriority: 100
```

Looking at the chart at 2.9.1, the API service has this field: `insecureSkipTLSVerify: true`, does 2.13 need to include this field too if it's using a self-signed cert? 

### Expected Behavior

Kubectl shouldn't have warnings about `external.metrics.k8s.io/v1beta1`.

### Actual Behavior

`E0202 10:16:00.734804   60017 memcache.go:287] couldn't get resource list for external.metrics.k8s.io/v1beta1: the server is currently unable to handle the request`

### Steps to Reproduce the Problem

1. Upgrade to keda 2.13
2. Run kubectl get commands
3.

### KEDA Version

2.13.0

### Kubernetes Version

1.24

### Platform

Amazon Web Services

**Comment by JorTurFer** [comment]
Hello,
You can find more info here: https://keda.sh/blog/2023-05-02-certificate-improvements/

We removed the `insecureSkipTLSVerify: true` in favor of managed certificates. There are 3 working ways:
- KEDA manages its own certificate
- cert-manager integration 
- You manage them by your side

For the first option, KEDA operator generates a secret within the namespace where the operator is which contains the TLS certificate generated and managed by KEDA. Once the certificate is ready, it restarts itself and during the next startup it'll patch the apiservice's caBundle with the cert CA.
For the second option, you can use the cert-manager integration using KEDA's chart, which basically will do the same as the 1st option but the cert will be created and managed by cert-manager and it's cert-manager who patches the apiservice.
For the last option, you can mount your own certs but you are the responsible of patching all the resources which require trusting in KEDA (apiservice, webhooks, etc).

Do you see the secret with the certs in the namespace where KEDA is? Do you see any error in KEDA operator logs?
