### ISSUE TITLE
how activate it via http access, e.g. by accessing the fully qualified domain name of k8s?

### ISSUE THREAD

**Issue by xrwang8** [kedacore/keda#5480]
### Proposal

When replicaset is 0, I can access the k8 fully-qualified domain via http, and its de-activation job makes its  replicaset 0 to 1

### Is this a feature you are interested in implementing yourself?

No

**Comment by JorTurFer** [comment]
Hey!
Are you asking about HTTP based autoscaling? If yes, I'd suggest checking this the HTTP Add-on: https://github.com/kedacore/http-add-on

**Comment by xrwang8** [comment]
@JorTurFer  I have a question, if I go to access the service directly through the FQDN of k8's service, http-add-on doesn't seem to take effect, the service can't be activated

**Comment by JorTurFer** [comment]
For example, [this e2e test ](https://github.com/kedacore/http-add-on/blob/main/tests/checks/internal_service/internal_service_test.go)covers that scenario:
`command: ["curl", "-H", "Host: {{.Host}}", "keda-http-add-on-interceptor-proxy.keda:8080"]`

Basically, it calls directly to interceptor service but setting the host header with the value of the workload's k8s service FQDN behind it
