### ISSUE TITLE
app.kubernetes.io/version Label in *-core.yaml Release Asset Should Specify Version

### ISSUE THREAD

**Issue by bdschaap** [kedacore/keda#5484]
### Report

The `app.kubernetes.io/version` label in the keda-*-core.yaml release asset lists `main` rather than the actual version.  This differs from the keda-*.yaml release asset which lists the version.

### Expected Behavior

The version is listed in the label of the keda-*-core.yaml release asset.

### Actual Behavior

`main` is listed as the version.

### Steps to Reproduce the Problem

1. Download keda-*-core.yaml 
2. View the `app.kubernetes.io/version` labels

### Logs from KEDA operator

N/A

### KEDA Version

2.11.2

### Kubernetes Version

1.26

### Platform

Other

### Scaler Details

kafka

**Comment by JorTurFer** [comment]
Hey!
Thanks for reporting! are you willing to draft a PR with the fix?
It should be just adding a line like 
`@sed -i".out" -e 's@version:[ ].*@version: $(VERSION)@g' config/minimal/kustomize-config/metadataLabelTransformer.yaml` during the `release` target (and the changelog record):
https://github.com/kedacore/keda/blob/6d326c83df55c383bd572e069bfc104fbdf653c5/Makefile#L226-L239

**Comment by vinod827** [comment]
Can I pick this up?

**Comment by vinod827** [comment]
Opened the PR# https://github.com/kedacore/keda/pull/5518
