### ISSUE TITLE
UPGRADE FAILED: cannot patch "security-services" with kind ScaledObject: Timeout: request did not complete within requested timeout - context deadline exceeded

### ISSUE THREAD

**Issue by jagtapa** [kedacore/keda#5487]
### Report

we have recently upgraded keda version to 2.12.1.
after successful upgrade , we have modified scaledObject parameters from Application chart 
e.g minReplica value . threshould etc

So During helm upgrade to application we're getting below error

 Error: UPGRADE FAILED: cannot patch "security-services" with kind ScaledObject: Timeout: request did not complete within requested timeout - context deadline exceeded && cannot patch "security-services" with kind ScaledObject: Timeout: request did not complete within requested timeout - context deadline exceeded && cannot patch "config-services" with kind ScaledObject: Timeout: request did not complete within requested timeout - context deadline exceeded && cannot patch "security-services" with kind ScaledObject: Timeout: request did not complete within requested timeout - context deadline exceeded

so Helm upgrade failed and we could see error in keda operator pod logs

`2024-02-06T11:34:09Z	INFO	Initializing Scaling logic according to ScaledObject Specification	{"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "ScaledObject": {"name":"security-services","namespace":"ffs"}, "namespace": "ffs", "name": "security-services", "reconcileID": "6d14dcf1-ac2c-458e-ae91-07b67d6509eb"}
2024-02-06T11:34:09Z	ERROR	scaleexecutor	failed to patch Objects	{"scaledobject.Name": "security-services", "scaledObject.Namespace": "ffs", "scaleTarget.Name": "security-services", "error": "client rate limiter Wait returned an error: context canceled"}
github.com/kedacore/keda/v2/pkg/status.TransformObject
	/workspace/pkg/status/status.go:186
github.com/kedacore/keda/v2/pkg/scaling/executor.(*scaleExecutor).updateLastActiveTime
	/workspace/pkg/scaling/executor/scale_executor.go:81
github.com/kedacore/keda/v2/pkg/scaling/executor.(*scaleExecutor).RequestScale
	/workspace/pkg/scaling/executor/scale_scaledobjects.go:153
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).checkScalers
	/workspace/pkg/scaling/scale_handler.go:247
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).startScaleLoop
	/workspace/pkg/scaling/scale_handler.go:180
2024-02-06T11:34:09Z	ERROR	scaleexecutor	Error updating last active time	{"scaledobject.Name": "security-services", "scaledObject.Namespace": "ffs", "scaleTarget.Name": "security-services", "error": "client rate limiter Wait returned an error: context canceled"}
github.com/kedacore/keda/v2/pkg/scaling/executor.(*scaleExecutor).RequestScale
	/workspace/pkg/scaling/executor/scale_scaledobjects.go:155
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).checkScalers
	/workspace/pkg/scaling/scale_handler.go:247
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).startScaleLoop
	/workspace/pkg/scaling/scale_handler.go:180`

### Expected Behavior

Applicatiion should have upgraded with specified ScaledObject configuration which were going to applied with helm upgrade

### Actual Behavior

Helm upgrade failed with below error

 Error: UPGRADE FAILED: cannot patch "app-gateway" with kind ScaledObject: Timeout: request did not complete within requested timeout - context deadline exceeded && cannot patch "security-services" with kind ScaledObject: Timeout: request did not complete within requested timeout - context deadline exceeded && cannot patch "config-services" with kind ScaledObject: Timeout: request did not complete within requested timeout - context deadline exceeded && cannot patch "security-services" with kind ScaledObject: Timeout: request did not complete within requested timeout - context deadline exceeded

### Steps to Reproduce the Problem

1.modify scaledObject parameter 
2.try to upgrade application chart with modified values
3.Helm upgrade would fail with error given in description

### Logs from KEDA operator

```
2024-02-06T11:34:09Z	INFO	Initializing Scaling logic according to ScaledObject Specification	{"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "ScaledObject": {"name":"security-services","namespace":"ffs"}, "namespace": "ffs", "name": "security-services", "reconcileID": "6d14dcf1-ac2c-458e-ae91-07b67d6509eb"}
2024-02-06T11:34:09Z	ERROR	scaleexecutor	failed to patch Objects	{"scaledobject.Name": "security-services", "scaledObject.Namespace": "ffs", "scaleTarget.Name": "security-services", "error": "client rate limiter Wait returned an error: context canceled"}
github.com/kedacore/keda/v2/pkg/status.TransformObject
	/workspace/pkg/status/status.go:186
github.com/kedacore/keda/v2/pkg/scaling/executor.(*scaleExecutor).updateLastActiveTime
	/workspace/pkg/scaling/executor/scale_executor.go:81
github.com/kedacore/keda/v2/pkg/scaling/executor.(*scaleExecutor).RequestScale
	/workspace/pkg/scaling/executor/scale_scaledobjects.go:153
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).checkScalers
	/workspace/pkg/scaling/scale_handler.go:247
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).startScaleLoop
	/workspace/pkg/scaling/scale_handler.go:180
2024-02-06T11:34:09Z	ERROR	scaleexecutor	Error updating last active time	{"scaledobject.Name": "security-services", "scaledObject.Namespace": "ffs", "scaleTarget.Name": "security-services", "error": "client rate limiter Wait returned an error: context canceled"}
github.com/kedacore/keda/v2/pkg/scaling/executor.(*scaleExecutor).RequestScale
	/workspace/pkg/scaling/executor/scale_scaledobjects.go:155
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).checkScalers
	/workspace/pkg/scaling/scale_handler.go:247
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).startScaleLoop
	/workspace/pkg/scaling/scale_handler.go:180
```

### KEDA Version

2.12.1

### Kubernetes Version

1.27

### Platform

Google Cloud

### Scaler Details

Confluent Kafka

**Comment by JorTurFer** [comment]
Hello
What version did you upgrade from? The message `client rate limiter` looks related with the client limiter. I guess that you have too many resources for current values and you need to increase them.  This can be produced because during the upgrade operation, all the resources have to be upgraded and it can trigger the local rate limit.

If the error persists during the time, it can be produced by a legit increase. In that case, I'd suggest increasing the limits modifying this parameters: https://keda.sh/docs/2.12/operate/cluster/#kubernetes-client-parameters

**Comment by jagtapa** [comment]
old version was 2.8.2, it was upgraded to 2.12.1,  two weeks ago.



if we edit directly single scaleObject using 
'kubectl edit scaleobject ....... -n ....'

then also we have seen such error in keda operator pod.

**Comment by JorTurFer** [comment]
How many resources do you have? (approx) Including all KEDA resources
So, If you just edit a ScaledObject, the error happens, right?

**Comment by jagtapa** [comment]
Yes , we have around 32 scaledObject  , yes if edit a scaledObject or upgrade via helm as well , we can see those errors.
if possible we can have small call to discuss in details and we can show the exact scenario.

**Comment by jagtapa** [comment]
we had also tried with diff application and here more detailed logs 


````
2024-02-06T16:46:47Z	INFO	Initializing Scaling logic according to ScaledObject Specification	{"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "ScaledObject": {"name":"appexample","namespace":"exampleernor"}, "namespace": "exampleernor", "name": "appexample", "reconcileID": "352d92ae-8149-466a-b6da-521b5d7cfcb6"}
2024-02-06T16:46:47Z	ERROR	prometheus_scaler	error executing prometheus query	{"type": "ScaledObject", "namespace": "exampleernor", "name": "appexample", "error": "Get \"http://frontend.management:9090/api/v1/query?query=sum%28rate%28dapr_http_server_request_count%7Bapp_id%3D%22exampleernor%22%2C+cluster%3D%22exampleernor-cluster40%22%2Cpath%3D~%22%2Fv1.0%2Finvoke%2Fexampleernor%2Fmethod%2Finterceptor%2F.%2A%22%7D%5B5s%5D%29%29&time=2024-02-06T16:46:46Z\": context canceled"}
github.com/kedacore/keda/v2/pkg/scalers.(*prometheusScaler).GetMetricsAndActivity
	/workspace/pkg/scalers/prometheus_scaler.go:359
github.com/kedacore/keda/v2/pkg/scaling/cache.(*ScalersCache).GetMetricsAndActivityForScaler
	/workspace/pkg/scaling/cache/scalers_cache.go:129
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).getScalerState
	/workspace/pkg/scaling/scale_handler.go:699
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).getScaledObjectState
	/workspace/pkg/scaling/scale_handler.go:590
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).checkScalers
	/workspace/pkg/scaling/scale_handler.go:241
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).startScaleLoop
	/workspace/pkg/scaling/scale_handler.go:180
2024-02-06T16:46:47Z	ERROR	prometheus_scaler	error executing prometheus query	{"type": "ScaledObject", "namespace": "exampleernor", "name": "appexample", "error": "Get \"http://frontend.management:9090//api/v1/query?query=sum%28rate%28dapr_http_server_request_count%7Bapp_id%3D%22exampleernor%22%2C+cluster%3D%22exampleernor-cluster40%22%2Cpath%3D~%22%2Fv1.0%2Finvoke%2Fexampleernor%2Fmethod%2Finterceptor%2F.%2A%22%7D%5B5s%5D%29%29&time=2024-02-06T16:46:47Z\": context canceled"}
github.com/kedacore/keda/v2/pkg/scalers.(*prometheusScaler).GetMetricsAndActivity
	/workspace/pkg/scalers/prometheus_scaler.go:359
github.com/kedacore/keda/v2/pkg/scaling/cache.(*ScalersCache).GetMetricsAndActivityForScaler
	/workspace/pkg/scaling/cache/scalers_cache.go:139
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).getScalerState
	/workspace/pkg/scaling/scale_handler.go:699
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).getScaledObjectState
	/workspace/pkg/scaling/scale_handler.go:590
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).checkScalers
	/workspace/pkg/scaling/scale_handler.go:241
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).startScaleLoop
	/workspace/pkg/scaling/scale_handler.go:180
2024-02-06T16:46:47Z	ERROR	scale_handler	error getting scale decision	{"scaledObject.Namespace": "exampleernor", "scaledObject.Name": "appexample", "scaler": "prometheusScaler", "error": "Get \"http://frontend.management:9090//api/v1/query?query=sum%28rate%28dapr_http_server_request_count%7Bapp_id%3D%22exampleernor%22%2C+cluster%3D%22exampleernor-cluster40%22%2Cpath%3D~%22%2Fv1.0%2Finvoke%2Fexampleernor%2Fmethod%2Finterceptor%2F.%2A%22%7D%5B5s%5D%29%29&time=2024-02-06T16:46:47Z\": context canceled"}
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).getScalerState
	/workspace/pkg/scaling/scale_handler.go:720
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).getScaledObjectState
	/workspace/pkg/scaling/scale_handler.go:590
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).checkScalers
	/workspace/pkg/scaling/scale_handler.go:241
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).startScaleLoop
	/workspace/pkg/scaling/scale_handler.go:180
2024-02-06T16:46:47Z	ERROR	scaleexecutor	failed to patch Objects	{"scaledobject.Name": "appexample", "scaledObject.Namespace": "exampleernor", "scaleTarget.Name": "appexample", "error": "client rate limiter Wait returned an error: context canceled"}
github.com/kedacore/keda/v2/pkg/status.TransformObject
	/workspace/pkg/status/status.go:186
github.com/kedacore/keda/v2/pkg/scaling/executor.(*scaleExecutor).setCondition
	/workspace/pkg/scaling/executor/scale_executor.go:106
github.com/kedacore/keda/v2/pkg/scaling/executor.(*scaleExecutor).setReadyCondition
	/workspace/pkg/scaling/executor/scale_executor.go:113
github.com/kedacore/keda/v2/pkg/scaling/executor.(*scaleExecutor).RequestScale
	/workspace/pkg/scaling/executor/scale_scaledobjects.go:178
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).checkScalers
	/workspace/pkg/scaling/scale_handler.go:247
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).startScaleLoop
	/workspace/pkg/scaling/scale_handler.go:180
2024-02-06T16:46:47Z	ERROR	scaleexecutor	error setting ready condition	{"scaledobject.Name": "appexample", "scaledObject.Namespace": "exampleernor", "scaleTarget.Name": "appexample", "error": "client rate limiter Wait returned an error: context canceled"}
github.com/kedacore/keda/v2/pkg/scaling/executor.(*scaleExecutor).RequestScale
	/workspace/pkg/scaling/executor/scale_scaledobjects.go:179
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).checkScalers
	/workspace/pkg/scaling/scale_handler.go:247
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).startScaleLoop
	/workspace/pkg/scaling/scale_handler.go:180
2024-02-06T16:46:47Z	INFO	Reconciling ScaledObject	{"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "ScaledObject": {"name":"appexample","namespace":"exampleernor"}, "namespace": "exampleernor", "name": "appexample", "reconcileID": "59a5139e-8360-493a-a4d1-090e9b17b053"}
2024-02-06T16:46:47Z	INFO	scaleexecutor	Successfully set ScaleTarget replicas count to ScaledObject minReplicaCount	{"scaledobject.Name": "appexample", "scaledObject.Namespace": "exampleernor", "scaleTarget.Name": "appexample", "Original Replicas Count": 3, "New Replicas Count": 4}
2024-02-06T16:47:01Z	INFO	Reconciling ScaledObject	{"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "ScaledObject": {"name":"appexample","namespace":"exampleernor"}, "namespace": "exampleernor", "name": "appexample", "reconcileID": "eec2bb9c-2662-470b-ade1-2aaba18a6e3d"}
2024-02-06T16:47:16Z	INFO	Reconciling ScaledObject	{"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "ScaledObject": {"name":"appexample","namespace":"exampleernor"}, "namespace": "exampleernor", "name": "appexample", "reconcileID": "f9175c65-692a-4a34-b5bb-db84acc2148d"}
````

**Comment by sunnybhambhani** [comment]
I think this error is coming because keda is unable to GET the output of the prometheus query within 3 secs (which is the default value).

2024-02-06T16:46:47Z	ERROR	**scale_handler	error getting scale decision**	{"scaledObject.Namespace": "exampleernor", "scaledObject.Name": "appexample", "scaler": "prometheusScaler", "error": "Get \"http://frontend.management:9090//api/v1/query?QUERY_TRIMMED\": **context canceled**"}

And if we increase the value of KEDA_HTTP_DEFAULT_TIMEOUT to lets say 10000millisecs, it might help (updating this will be applicable to all the scalers).

I am not sure but maybe increasing the value of MaxConcurrentReconciles to a bit higher value like 25-30 might help because its default value is 5 and to reconcile during patching might be taking longer time and eventually it might be timing out throwing this error "Request did not complete within requested timeout".

@JorTurFer , I am new to keda but please do correct me if I am wrong. 

Thank you,
Sunny

**Comment by JorTurFer** [comment]
Hello,
If you are facing with frequent timeouts in that scaler, you can increase a bit the timeout, and it will help for sure. In the same way, if you have multiple scalers failing at the same time, all of them will try to be recreated in parallel using MaxConcurrentReconciles.
The problem that I see is that the message says client rate limiting, wich is managed by the parameters I sent: [keda.sh/docs/2.12/operate/cluster/#kubernetes-client-parameters](https://keda.sh/docs/2.12/operate/cluster/#kubernetes-client-parameters)

I see them as different issues, the Prometheus timeout is triggering the API rate limit as KEDA patches the ScaledObjects on each fail. 

BTW, we fixed a memory leak related with prometheus (and other scalers based on http) which happened if the scaler was failing so often. The fix was released as part of v2.13

**Comment by sunnybhambhani** [comment]
Understood. Since it was failing for a single iteration/patch as well that's why it is a bit confusing.

But thanks for the clarification this helps.

Just a small question based on the above example with 32 scaled objects I think the default values should be fine, but could you please suggest what should be the optimum value in this case?

cfg.QPS | 20.0
cfg.Burst | 40

Thank again,
Sunny

**Comment by JorTurFer** [comment]
I'd just try with the double:
cfg.QPS | 40
cfg.Burst | 80

**Comment by sunnybhambhani** [comment]
> I'd just try with the double: cfg.QPS | 40 cfg.Burst | 80

I tried with cfg.QPS | 40 cfg.Burst | 80 values and unfortunately still I am getting the same kind of error.

And just to add in this case I just had 5 scaledobjects

> 2024-02-07T11:33:48Z    ERROR   scaleexecutor   failed to patch Objects {"scaledobject.Name": "app-isvc1", "scaledObject.Namespace": "app1", "scaleTarget.Name": "app-isvc1", "error": "client rate limiter Wait returned an error: context canceled"}
github.com/kedacore/keda/v2/pkg/status.TransformObject
        /workspace/pkg/status/status.go:186
github.com/kedacore/keda/v2/pkg/scaling/executor.(*scaleExecutor).setCondition
        /workspace/pkg/scaling/executor/scale_executor.go:106
github.com/kedacore/keda/v2/pkg/scaling/executor.(*scaleExecutor).setActiveCondition
        /workspace/pkg/scaling/executor/scale_executor.go:120
github.com/kedacore/keda/v2/pkg/scaling/executor.(*scaleExecutor).RequestScale
        /workspace/pkg/scaling/executor/scale_scaledobjects.go:224
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).checkScalers
        /workspace/pkg/scaling/scale_handler.go:247
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).startScaleLoop
        /workspace/pkg/scaling/scale_handler.go:180
2024-02-07T11:33:48Z    ERROR   scaleexecutor   Error setting active condition when triggers are not active     {"scaledobject.Name": "app-isvc1", "scaledObject.Namespace": "app1", "scaleTarget.Name": "app-isvc1", "error": "client rate limiter Wait returned an error: context canceled"}
github.com/kedacore/keda/v2/pkg/scaling/executor.(*scaleExecutor).RequestScale
        /workspace/pkg/scaling/executor/scale_scaledobjects.go:225
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).checkScalers
        /workspace/pkg/scaling/scale_handler.go:247
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).startScaleLoop
        /workspace/pkg/scaling/scale_handler.go:180

Not sure if in case this is something else, btw about the memory leak issue do you think this could be interrelated?

I think no but just wanted to be sure, I believe the memory leak would affect the pod and once the pod has reached its memory threshold it would just restart but the application logic would run fine. Please correct me if I am wrong.

Thank you.

**Comment by JorTurFer** [comment]
That's weird :/
Could you share your scaledobjects? if they are similar, one it's just enough

**Comment by jagtapa** [comment]
please refer below scaledObject yaml file

```apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: app-services
  labels:
    helm.sh/chart: app-1.0.0
    app.kubernetes.io/name: app
    app.kubernetes.io/instance: app
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
spec:
  minReplicaCount: 3
  maxReplicaCount: 500
  pollingInterval: 1 # Optional. Default: 30 seconds
  cooldownPeriod: 300 # Optional. Default: 300 seconds
  scaleTargetRef:
    name: app-services
  advanced:                                          # Optional. Section to specify advanced options
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 300
    restoreToOriginalReplicaCount: false
  triggers:
    - type: prometheus
      metadata:
        serverAddress: http://frontend.management:9090/
        metricName: http_server_requests_seconds_count
        query: sum(rate(http_server_requests_seconds_count{application="app", cluster="dr-cluster",uri=~"/.*"}[5s]))
        threshold: "50"

**Comment by jagtapa** [comment]
@JorTurFer:

Following the suggestion to whitelist port 9443, which was found in this bug report [https://github.com/kedacore/keda/discussions/4660], the helm upgrade command was successful. Previously, it was failing due to a timeout issue. However, despite these adjustments, the expected patching of scaledObjects is not occurring.

We've thoroughly tested all parameters without success. Additionally, we've encountered some unusual behavior in another environment, related to a different application. While the helm upgrade is successful and scaledObjects are patched for individual changes, if there are multiple scaled object changes, it only updates three out of four, with one giving the aforementioned error. Perhaps @sunnybhambhani can provide further insight into this behavior.

However, in our main application cluster, there have been no changes regarding the patching of scaledObjects. Therefore, the current issue remains that scaledObjects are not being updated despite a successful helm upgrade.

_Please note that this environment is a private cluster with very restricted access. It's important to consider this perspective while addressing the issue._

**Comment by zroubalik** [comment]
A few quick observations, the polling interval set to 1 sec is very aggressive given that your Prometheus instance is probably not able to handel that many requests and respond before the timeout.
Are you able to run a quick load test against the Prometheus and try to run similar query, to see if it is able to handle it?

**Comment by jagtapa** [comment]
@zroubalik 

we temporarily increased the poll interval time from 1 second to 10 seconds. This change resulted in the desired scaledObjects being updated in our lower & Higher environments.

Subsequently, we reverted the poll interval back to its original value of 1 second, and since then, everything has been functioning as expected. 

It's worth noting that despite no other changes being made, the behaviour of scaledObjects being updated was observed due to this poll interval adjustment, which may seem somewhat unusual.

The keda-operator is displaying an errors despite this reflection.

**Comment by zroubalik** [comment]
> It's worth noting that despite no other changes being made, the behaviour of scaledObjects being updated was observed due to this poll interval adjustment, which may seem somewhat unusual.
> 
> The keda-operator is displaying an errors despite this reflection.

Hi, sorry I don't follow these two paragraphs, could you please give me more context?

**Comment by JorTurFer** [comment]
> I mean offourse this will take command once existing pod will get terminated by any reason.

Yes, that'll happen but it won't be instantly because the operator relies on leader election API and it'll need some time (10-15) to lease the leader lock

**Comment by JorTurFer** [comment]
But based on the latest comments, I'm not sure that the operator is the problem but the amount of requests against the prometheus server. Having 32 ScaledObjects with 1 second of pollingInterval, you will execute 32  queries per second agains the server. 

The timeout message (not the `client rate limiter`) is thrown because the server isn't responding in time

**Comment by zroubalik** [comment]
> But based on the latest comments, I'm not sure that the operator is the problem but the amount of requests against the prometheus server. Having 32 ScaledObjects with 1 second of pollingInterval, you will execute 32 queries per second agains the server.
> 
> The timeout message (not the `client rate limiter`) is thrown because the server isn't responding in time

that's exactly my thought here

**Comment by JorTurFer** [comment]
I'd not expect that for just 22 ScaledObject you would have needed to tweak the configurations as 22 is a small number, but if they work for you, that's the goal. Probably the short polling interval is making that you need higher valuers because if the Prometheus server is down you will emit more events, so can be normal I guess

**Comment by zroubalik** [comment]
Thanks for sharing, my guess would also be the Prometheus side, 22 ScaledObjects is not a huge number.

**Comment by vaibhavgoel28** [comment]
We have ~ 30 scaledobjects running in our eks cluster, when scaling down, we observed that for one of the applications, the scale-down did not take place for a significant time for the desired pod count even when the metric was under the right threshold!

When keda-operator logs were checked for the same, we identified the error:
`2024-04-26T11:17:33Z	ERROR	scaleexecutor	Error setting active condition when triggers are inactive	{"scaledobject.Name": "<name>", "scaledObject.Namespace": "<namespace>", "scaleTarget.Name": "<name>", "error": "client rate limiter Wait returned an error: context canceled"}`

as part of the suggestions above, we will try to tweak the parameters namely kube-api-qps and kube-api-burst, but there are some concerns, how can we estimate the impact on the API-server when these parameters are tweaked to use a number higher than default (any metric that can help as exposed by keda)? Which metric exposed by keda-operator can account for evaluating the ideal number for the client parameters? 
@JorTurFer @zroubalik

**Comment by JorTurFer** [comment]
>how can we estimate the impact on the API-server when these parameters are tweaked to use a number higher than default (any metric that can help as exposed by keda)?

You can monitor the API server components and measure the impact, KEDA doesn't have information about how the api server performs

> Which metric exposed by keda-operator can account for evaluating the ideal number for the client parameters?

we don't expose any specific metric from KEDA but the operator sdk exposes this metric that can be useful `rest_client_requests_total`. IIRC it's the amount of request against the control plane, so measuring it you could estimate the correct value
