### ISSUE TITLE
[ Azure] [Workload Identity]  / Understanding Keda Controller Identity definintions vrs Workers Trigger Auth Identities 

### ISSUE THREAD

**Issue by tshaiman** [kedacore/keda#5491]
### Report

we have the following scenario :

![image](https://github.com/kedacore/keda/assets/512709/615386a8-9a8e-4303-bd22-adb4fd2790b9)

on Keda NS : 
we deployed the controller with Service Account as we use Azure Workload Identity
Our Managed Identity  client Id for the Federation is "aaa" 

on Worker Ns : 
we have workload pods/deployments that use Workload Identity with Service Account that reference "bbb" 
the Client Id is granted for azure-servicebus-data owner on some service bus
the Scaled object uses Trigger Auth with that "bbb" managed identity.

Error : 
Trigger Auth on the workler namespace ( orange) is complaining that keda namespace does not have permissions for the federation .

Concern : 
it seems Keda control plane MI / Service Account must match the workers Service Account / MI .
if this is the case it seems like duplication of definition : 
on one hand we grant Keda Control plane the access to Azure with Federation 
on the other hand we define triggger authentication with the same MI again . its not like we can use different MI here , so actually it seems like again giving keda , an auth trigger object , but it can only use the one defined in the control plane anhow .

### Expected Behavior

- Can Keda work with multiple Workload identity federation coming from various namespaces ? 
- what is the role of Keda Controller Workload Identity Federation definition , if the scaled object re-defines the Auth Trigger 

### Actual Behavior

- we fail to implement the above scenario 

### Steps to Reproduce the Problem

1.
2.
3.

### Logs from KEDA operator

```
example
```

### KEDA Version

2.12.0

### Kubernetes Version

1.27

### Platform

Microsoft Azure

### Scaler Details

Azure Service Bus

**Comment by JorTurFer** [comment]
I think that your case is like ["Case 2" from auth docs](https://keda.sh/docs/2.13/authentication-providers/azure-ad-workload-identity/#case-2)

**Comment by JorTurFer** [comment]
![image](https://github.com/kedacore/keda/assets/36899226/b0830b9f-7370-4abb-ae45-d7c4b26ee4bd)

**Comment by tshaiman** [comment]
Yes , that seems to be the case . we will add federation to Keda Service account for those identities. thanks !

**Comment by JorTurFer** [comment]
happy to help!
