### ISSUE TITLE
We are looking for customers to be listed as a customer on keda.sh

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda#551]
We are looking for KEDA customers who are interested to be listed as a customer on keda.sh.

If you are, please comment here and provide a logo that we can use.

**Comment by PixelRobots** [comment]
Happy to be added. 

Logo can be found at https://www.cloud-trade.com/wp-content/uploads/2019/04/CloudTradeLOGO.png

Our website is https://www.cloud-trade.com/.

We are using Keda with RabbitMQ.

Thanks

**Comment by tomkerkhove** [comment]
Thanks @PixelRobots! PR is open - https://github.com/kedacore/keda-docs/pull/79

**Comment by tomkerkhove** [comment]
@PixelRobots It's live on keda.sh, thanks!

**Comment by PixelRobots** [comment]
Awesome. Thank you.

**Comment by kellybirr** [comment]
Happy to be added Mivation, Inc ( https://www.mivation.com )

**Comment by turbaszek** [comment]
Not sure if we count as a customer but Apache Airflow is leveraging KEDA in the upcoming official helm chart https://github.com/apache/airflow
https://github.com/apache/airflow/tree/master/chart
