### ISSUE TITLE
Validate fallback configuration during admission process

### ISSUE THREAD

**Issue by JorTurFer** [kedacore/keda#5515]
### Proposal

Currently, `fallback` feature only supports `AverageValue` metrics type and it doesn't support CPU and Memory. 
![image](https://github.com/kedacore/keda/assets/36899226/ade896e6-ea0e-4f8f-9014-7c2aee80dc1e)

To prevent misconfigurations and confusions related with these limitations, we should include a validation for them during the admission process

**Comment by guopeng0** [comment]
Hi @JorTurFer

**Comment by JorTurFer** [comment]
Thanks @guopeng0 ! ❤️
