### ISSUE TITLE
Supporting disabling admission rules based on resource annotation

### ISSUE THREAD

**Issue by JorTurFer** [kedacore/keda#5516]
### Proposal

We are improving to admission coverage to prevent misconfigurations, but this also can block some users in specific scenarios. Maybe we should introduce a system to disable specific rules based on resource annotations, transferring the ownership of which rules has to apply to the users.

I'm thinking about something like:
```
annotations:	
	validations.keda.sh/shared-ownership: false
```
This could disable the check for already managed workload
or 
```
annotations:	
	validations.keda.sh/fallback: false
```

To covert his new validation: https://github.com/kedacore/keda/issues/5515

This could extend users capabilities to exclude (under their own risks) some validations without totally disabling admission validations

**Comment by zroubalik** [comment]
I like it, also an anotation to disable validation for that particular resource.  Related to this, I want to emphasize the need for correct validation and check in the controller for some options, to not depend only on the webhook.

**Comment by JorTurFer** [comment]
>  I want to emphasize the need for correct validation and check in the controller for some options, to not depend only on the webhook

I agree with you, but I won't invest so much effort adding a good information in operator side. I mean, if we can expose useful information in both places it's nice, but it adding extended info in operator side requires a significant effort, I'd not invest on it because there is already and admission validation (for the extended information)

**Comment by zroubalik** [comment]
Yeah, I mean the existing stuff, or a new fundamental features that requires some check to work correctly (a new field on SO/SJ spec or so).
