### ISSUE TITLE
Use of k8s.io namespace for API group in Kubernetes CRDs needs approval

### ISSUE THREAD

**Issue by trisberg** [kedacore/keda#552]
In order to use `k8s.io` namespace in the API group for CRDs KEDA would need to have approval and add an `"api-approved.kubernetes.io"` annotation - see https://github.com/kubernetes/enhancements/pull/1111

One option is to change the API group to use a domain like `keda.sh` that is owned by the project.

## Expected Behavior

KEDA CRDs conform to the [Kubernetes API Review Process](https://github.com/kubernetes/community/blob/master/sig-architecture/api-review-process.md#what-apis-need-to-be-reviewed)

## Actual Behavior

The KEDA CRDs deployed to Kubernetes v1.16.0 and later have the following failed status condition:

```
  - lastTransitionTime: "2020-01-21T15:22:05Z"
    message: protected groups must have approval annotation "api-approved.kubernetes.io",
      see https://github.com/kubernetes/enhancements/pull/1111
    reason: MissingAnnotation
    status: "False"
    type: KubernetesAPIApprovalPolicyConformant
```

## Steps to Reproduce the Problem

  1. Deploy the KEDA CRDs to a Kubernetes v1.16.x cluster
  2. Check the status condition `KubernetesAPIApprovalPolicyConformant` of the CRDs using `kubectl describe crd/scaledobjects.keda.k8s.io` 
  3.

## Specifications

  - **Version:** v1.0
  - **Platform:** Kubernetes v1.16 and later
  - **Scaler(s):**

**Comment by scothis** [comment]
While a breaking change, I'd suggest renaming the api group from `keda.k8s.io` to `keda.sh`

**Comment by tomkerkhove** [comment]
Good point, thanks. We're adding this to our v2.0 release!

**Comment by tomkerkhove** [comment]
I was thinking this through a bit more and what if we:
1. Introduce new CRDs in v1.2 under `keda.sh`
2. Remove current CRD in v2.0

That way we are already moving towards the new approach, but don't have to rush a 2.0 release until we bundle it with more breaking changes.

Would that be ok for you or do you think this should be fixed ASAP?

/cc @jeffhollan @ahmelsayed

**Comment by zroubalik** [comment]
merged into `v2` branch
