### ISSUE TITLE
Prometheus scaler support for non-external metrics

### ISSUE THREAD

**Issue by RRethy** [kedacore/keda#5523]
### Proposal

Right now the Prometheus scaler creates an HPA metric spec with a metric type of `External`. It would be nice to have this potentially be configurable (e.g. `Pods`).

### Use-Case

`External` metrics and other metrics use a different algorithm when calculating available pods. Specifically, [it will just look at the Scale.status.replicas field](https://github.com/kubernetes/kubernetes/blob/5275bb0502a40d6ebc2ad78f7fd3ec6f1dad3788/pkg/controller/podautoscaler/replica_calculator.go#L368), which counts pods by label selector and includes unready and terminating pods.

Other metrics, like `Pods` [use a more sophisticated algorithm](https://github.com/kubernetes/kubernetes/blob/5275bb0502a40d6ebc2ad78f7fd3ec6f1dad3788/pkg/controller/podautoscaler/replica_calculator.go#L178) which would be beneficial for certain prometheus queries, e.g. utilization queries.

### Is this a feature you are interested in implementing yourself?

Maybe

### Anything else?

I'd be open to looking at implementing this, but my timeline would be uncertain.

**Comment by JorTurFer** [comment]
I see the advantage of this, but for achieving it we have to expose also custom metrics and not only external metrics. I'm not sure if it's worth just for a single scaler and I don't see any other use case in the scaler catalog (but I can be missing something).
WDYT @tomkerkhove @zroubalik ?

**Comment by zroubalik** [comment]
I do understand the usecase, but I would be very careful here (introducing the custom metrics endoint). There are another tools that uses this endpoing, KEDA would end up in reserving both external and custom metrics endpoints.
Maybe working upstream to add more flexibility to the external metrics calculation? 🤔
