### ISSUE TITLE
Get rid of `cortexOrgID` within prometheus scaler

### ISSUE THREAD

**Issue by JorTurFer** [kedacore/keda#5538]
### Proposal

We deprecated `cortexOrgID` on v2.10 with the removal scheduled for v2.12 and we missed it. We have to remove it from code and docs

**Comment by MeenuyD** [comment]
Hello @JorTurFer I would like to work on this issue can you please assign it to me.

**Comment by JorTurFer** [comment]
We still need to address this

**Comment by samsond** [comment]
Hi @JorTurFer , can you please assign this issue to me ?

**Comment by dttung2905** [comment]
Hey @JorTurFer let me work on this
