### ISSUE TITLE
Add option databaseIndexFromEnv with Redis trigger

### ISSUE THREAD

**Issue by Lp-Francois** [kedacore/keda#5543]
### Proposal

It seems like all redis connection options can be provided through environment variables but `databaseIndex`

### Use-Case

Select the database index based on the environment variables to be more dynamic than hardcoded

### Is this a feature you are interested in implementing yourself?

Yes

### Anything else?

I don't have much experience with Go but I could contribute if you find this feature useful.

**Comment by JorTurFer** [comment]
I think that this will be useful 💪 

> I don't have much experience with Go but I could contribute if you find this feature useful.

This change should be quite easy. You need to include another condition in these files:
- lists: https://github.com/kedacore/keda/blob/main/pkg/scalers/redis_scaler.go#L290-L297
- streams: https://github.com/kedacore/keda/blob/main/pkg/scalers/redis_streams_scaler.go#L325-L332

We are unifying the scalers parsing and we've created this parsing helper: https://github.com/kedacore/keda/blob/main/pkg/scalers/scaler.go#L242-L288

You can use it giving the desired configurations and it will just do all the boring stuff. Then you can add a test coverage adding the case into the cases array:
- lists: https://github.com/kedacore/keda/blob/main/pkg/scalers/redis_scaler_test.go#L37
- streams: https://github.com/kedacore/keda/blob/main/pkg/scalers/redis_streams_scaler_test.go#L24
