### ISSUE TITLE
MongoDB Scaler - MongoDB Atlas connection string support

### ISSUE THREAD

**Issue by lsteinberg-r7** [kedacore/keda#5544]
### Proposal

In the current implementation (version 2.13.0), If we supply `host` & `port` instead of `connectionString`, it combines them under a hard-coded "mongodb" protocol -

<img width="557" alt="image" src="https://github.com/kedacore/keda/assets/18532875/147ee272-8134-4681-b105-2ef7a54ee37a">

I would like to request a support in MongoDB Atlas connection strings, that are supplied in the form of `mongodb+srv://`

### Use-Case

Connecting to MongoDB Atlas instances.

### Is this a feature you are interested in implementing yourself?

No

**Comment by JorTurFer** [comment]
Hello!
This makes sense totally and IMO we can easily support it just adding another parameter for the protocol, with current value as default.

**Comment by tico88612** [comment]
Hi @JorTurFer,

I am interested in this issue. Can you assign this issue to me?

**Comment by JorTurFer** [comment]
Done! thanks @tico88612 !

**Comment by tico88612** [comment]
Hi @JorTurFer,

I finished this PR. Should I need to edit [keda-docs](https://github.com/kedacore/keda-docs) now? I'm trying to decide which version to edit.

**Comment by JorTurFer** [comment]
> Hi @JorTurFer,
> 
> I finished this PR. Should I need to edit [keda-docs](https://github.com/kedacore/keda-docs) now? I'm trying to decide which version to edit.

yes, you have to modify the file for the next version (v2.14). In this case, this is the file: https://github.com/kedacore/keda-docs/blob/main/content/docs/2.14/scalers/mongodb.md

**Comment by tico88612** [comment]
> > Hi @JorTurFer,
> > I finished this PR. Should I need to edit [keda-docs](https://github.com/kedacore/keda-docs) now? I'm trying to decide which version to edit.
> 
> yes, you have to modify the file for the next version (v2.14). In this case, this is the file: https://github.com/kedacore/keda-docs/blob/main/content/docs/2.14/scalers/mongodb.md

Sure! Up to date.
