### ISSUE TITLE
Fail fast during e2e tests if dependencies aren't ready

### ISSUE THREAD

**Issue by JorTurFer** [kedacore/keda#5547]
### Proposal

There are some cases where a transient error (or not transient) produce failures on e2e tests, for example this execution:  https://github.com/kedacore/keda/actions/runs/8097346980/job/22128480015
 
I've checked the pr-cluster and the kafka cluster creation has failed, but the e2e test ignores this and continues until the timeout although the test could fail in just 3 minutes, producing really long waiting times just for nothing

**Comment by pratyushprakash** [comment]
Can I take a look at this?

**Comment by JorTurFer** [comment]
Hello @pratyushprakash ,
We have addressed this during the last e2e tests review
