### ISSUE TITLE
MinReplicaCount for ScaledObject can't be set to 0

### ISSUE THREAD

**Issue by yorik** [kedacore/keda#5570]
### Report

Keda reports error:
```
MinReplicaCount=1 must be less than MaxReplicaCount=0
```
If MinReplicaCount=0 and MaxReplicaCount=0

### Expected Behavior

No errors reported, the object scaled to 0.

### Actual Behavior

Keda reports error and don't do anything.

### Steps to Reproduce the Problem

1. Create deployment with ScaledObject, set MinReplicaCount=0, MaxReplicaCount=10 and apply.
2. Change MaxReplicaCount to 0 and apply.
3. Check the logs for errors.

### Logs from KEDA operator

```
MinReplicaCount=1 must be less than MaxReplicaCount=0
```

### KEDA Version

2.13.0

### Kubernetes Version

1.29

### Platform

Google Cloud

### Scaler Details

Prometheus

**Comment by yorik** [comment]
Hi @JorTurFer,
there is a huge difference between pausing Keda and setting `MaxReplicaCount` to 0: 
pausing leaves all the running pods running;
setting `MaxReplicaCount` to 0 shuts all the pods down.

In some cases we need to scale the service down completely, currently we have to add pause annotation and run `kubectl scale --replicas=0 deployment ...`. This is inconvenient, requires people to run manual unreviewed commands (there is always chance of a mistake) and leaves records in different places, so it's harder to debug during incidents.

**Comment by JorTurFer** [comment]
Yeah, I totally understand the requirement of scaling to 0 for some reasons, but that's already supported too xD

If you annotate the ScaledObject with `autoscaling.keda.sh/paused: "true"`, you are right and KEDA will lock current instances as the desired instances, leaving all the pods running but, If you annotate the ScaledObject with `autoscaling.keda.sh/paused-replicas: "0"`, KEDA will kill all the pods scaling to 0 the workload instantly and locking the scaling out.

In fact, you can use `autoscaling.keda.sh/paused-replicas: "YOUR_DESIRED_VALUE"` to enforce an arbitrary amount of pods meanwhile the ScaledObject is annotated. Then when you remove the annotation, the scaling will start from where it is on the annotation removal

**Comment by yorik** [comment]
I missed that part somehow, thanks!

We are migrating from https://github.com/jthomperoo/custom-pod-autoscaler and we used to scale down by setting `maxReplicas` to 0.

I still think that setting `MaxReplicaCount` to 0 is simpler for the task, no need to create custom annotations (it's easy to make small mistake in them and spend a lot of time trying to understand what's going on) and we won't need to re-educate people in our company. Also my PR would fix very strange error `MinReplicaCount=1 must be less than MaxReplicaCount=0` for all people trying to set `MaxReplicaCount` to 0. I spend hours debugging what's going on.

**Comment by JorTurFer** [comment]
Yeah, definitivelly, I don't have anything against the PR, I just suggested as an already available option to speed up your processes xD

**Comment by zroubalik** [comment]
`autoscaling.keda.sh/paused-replicas: "0"` solves this, it also removes the HPA. I am not sure we should allow max == 0. Fixint the error would be nice though.

**Comment by yorik** [comment]
Removing HPA is undesired in our case, if HPA would stay in place it will make sure that the deployment will stay scaled down, even if someone scaled it up by mistake.

**Comment by yorik** [comment]
BTW, there are more people expecting this behaviour, see https://github.com/kedacore/keda/issues/3013 and https://github.com/kedacore/keda/discussions/3014.

What would be a downside of supporting it?

**Comment by yorik** [comment]
This issue can be fixed by the https://github.com/kedacore/keda/pull/5571, any reason not to merge it?
