### ISSUE TITLE
Enhance ScaleObject's Scale Up/Down Event with Active Trigger Information

### ISSUE THREAD

**Issue by SpiritZhou** [kedacore/keda#5577]
### Proposal

As more and more users use multiple scalers in KEDA, they want to know which scaler will trigger pods to scale up from zero/idle or scale down to zero/idle. I suggest adding the active trigger name or scaler type in the KEDAScaleTargetActivated/KEDAScaleTargetDeactivated event. This will help users to understand their scale up/down process more clearly and don't need to analyst the scalers' metrics.

### Is this a feature you are interested in implementing yourself?

Yes

**Comment by zroubalik** [comment]
I like this, we can maybe also include this information into the ScaledObjects/ScaledJobs Status?

Also, we should implement this also for ScaledJobs.

**Comment by SpiritZhou** [comment]
> I like this, we can maybe also include this information into the ScaledObjects/ScaledJobs Status?
> 
> Also, we should implement this also for ScaledJobs.

Great idea. I can create another issue about status improvement.
