### ISSUE TITLE
Support for Amazon MQ (ActiveMQ engine)

### ISSUE THREAD

**Issue by jenna-foghorn** [kedacore/keda#5596]
### Proposal

I adore your project, and would love the convenience of using an amazon mq scaler.

### Scaler Source

queue size or average message count

### Scaling Mechanics

Either (depending on which scaler source is utilized):
- targetQueueSize  and activationTargetQueueSize
- messageSize and activationMessageSize

### Authentication Source

amazonmq username, password

### Anything else?

If this is already possible via ActiveMQ scaler, please let me know.  Our Amazon MQ is using the broker engine of `ActiveMQ`.

**Comment by JorTurFer** [comment]
Thanks for the idea! It makes sense totally 😄 
Are you willing to contribute with the feature?

**Comment by jenna-foghorn** [comment]
Yes, I'd be happy to!  Though, I don't know Go, and it looks like that is what you are written in.  Where is a good place to start?

**Comment by JorTurFer** [comment]
I think that these docs can be interesting:
- How to contribute with scalers: https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#contributing-scalers
- How to setup the env, run, debug, etc: https://github.com/kedacore/keda/blob/main/BUILD.md

**Comment by JorTurFer** [comment]
Are you still willing to help with this @jenna-foghorn ?
