### ISSUE TITLE
Prometheus metrics absent on 2.13.1

### ISSUE THREAD

**Issue by josesimon** [kedacore/keda#5599]
### Report

I am not able to configure observability to Keda by using prometheus.

### Expected Behavior

1- According to the docs I should be able to get the following list

![image](https://github.com/kedacore/keda/assets/12864857/d3947327-d65d-4bfd-8a35-6ef231861891)

2- And that the default dashboard is not aligned with the current version and can´t be used  "AS IS"

https://github.com/kedacore/keda/blob/main/config/grafana/keda-dashboard.json

### Actual Behavior

1- I am only able to see the following "keda-*"metrics exposed by the operator
![image](https://github.com/kedacore/keda/assets/12864857/a9d765bb-2ee3-4def-be3f-41c11d672e12)

2- See current rendered dashboard
![image](https://github.com/kedacore/keda/assets/12864857/989fc35c-760c-453c-8257-a35da15d8a1c)

### Steps to Reproduce the Problem

1. Fetch metrics at operator pod port 8080 at /metrics
2. Check grafana dashboard

### Logs from KEDA operator

```
example
```

### KEDA Version

2.13.1

### Kubernetes Version

< 1.26

### Platform

Other

### Scaler Details

CPU Scaled Object

**Comment by JorTurFer** [comment]
Hello,
The Grafana dashboard is en example to generate your own based on it, but it uses some metrics that can be in your cluster or can not be. Why? There are different limitations here that can affect:
- CPU/Memory Scalers doesn't expose the metric from KEDA but from the k8s metrics server, so KEDA cannot expose that information.
- We can't init labeled metrics if we don't have the labels, e.g: we can't init a metric about ScaledObject latencies if there isn't any ScaledObject
- ...
- 
[I've created an issue](https://github.com/kedacore/keda/issues/5609) to improve docs about these limitations as it's something that we cannot solve
