### ISSUE TITLE
Failed to create HTTPScaledObject, stuck in 'PendingCreation' state

### ISSUE THREAD

**Issue by JimmyCater87** [kedacore/keda#5608]
### Report

Failed to create HTTPScaledObject, stuck in 'PendingCreation' state

keda-add-ons-http-external-scaler log:

“{"level":"error","ts":1710299145.4313052,"caller":"scaler/queue_pinger.go:146","msg":"getting request counts","error":"there isn't any valid interceptor endpoint","stacktrace":"main.(*queuePinger).fetchAndSaveCounts\n\tgithub.com/kedacore/http-add-on/scaler/queue_pinger.go:146\nmain.(*queuePinger).start\n\tgithub.com/kedacore/http-add-on/scaler/queue_pinger.go:108\nmain.main.func3\n\tgithub.com/kedacore/http-add-on/scaler/main.go:110\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\tgolang.org/x/sync@v0.6.0/errgroup/errgroup.go:78}"

### Expected Behavior

HTTPScaledObject created successfully (or fails with error)

Observation:

1. Http add-on pods are running
 
keda-add-ons-http-controller-manager 3/3 Running 0 5h35m
keda-add-ons-http-external-scaler 2/2 Running 0 12h
keda-add-ons-http-external-scaler 2/2 Running 0 12h
keda-add-ons-http-external-scaler 2/2 Running 0 12h
keda-add-ons-http-interceptor 2/2 Running 0 12h
keda-add-ons-http-interceptor 2/2 Running 0 12h
keda-add-ons-http-interceptor 2/2 Running 0 12h
keda-admission-webhooks 2/2 Running 1 (5h44m ago) 12h
keda-operator 2/2 Running 1 (5h43m ago) 12h
keda-operator-metrics-apiserver 2/2 Running 1 (5h43m ago) 12h

2. ScaledObject and HPA are created successfully

PS > kubectl get scaledobject -n httpbin
NAME          SCALETARGETKIND      SCALETARGETNAME       MIN   MAX   TRIGGERS        AUTHENTICATION   READY   ACTIVE   FALLBACK   PAUSED    AGE
http-scaler   apps/v1.Deployment   httpbin   0     10    external-push                    True    False    False      Unknown   27h

PS > kubectl get hpa -n httpbin
NAME                   REFERENCE                        TARGETS              MINPODS   MAXPODS   REPLICAS   AGE
keda-hpa-http-scaler   Deployment/httpbin   <unknown>/10 (avg)   1         10        0          27h

### Actual Behavior

1. Followed the GIT Doc to install HTTP add-on in same namespace as Keda
https://github.com/kedacore/http-add-on/blob/main/docs/install.md
Step: helm install http-add-on kedacore/keda-add-ons-http --namespace keda

2. Http add-on is installed and PODs starts without any error
3. Created HTTPScaledObject with following configuration

kind: HTTPScaledObject
apiVersion: http.keda.sh/v1alpha1
metadata:
    name: http-scaler
spec:
    hosts:
    - 'hostPath'
    pathPrefixes:
    - '/prefixPath'
    targetPendingRequests: 100
    scaleTargetRef:
        deployment: httpbin
        service: httpbin
        port: 80
    replicas:
        min: 0
        max: 10
    scaledownPeriod: 300

---

4. Checked HTTPScaledObject scaled status:

status:
  conditions:
  - message: Identified HTTPScaledObject creation signal
    reason: PendingCreation
    status: Unknown
    timestamp: "2024-03-15T03:15:08Z"
    type: Pending

5. Check Keda Operator Logs, keda-add-ons-http-external-scaler, keda-add-ons-http-interceptor

keda-add-ons-http-external-scaler
---

W0315 03:07:34.321874       1 reflector.go:539] k8s.io/client-go@v0.29.0/tools/cache/reflector.go:229: failed to list *v1alpha1.HTTPScaledObject: Get "https://10.2.0.1:443/apis/http.keda.sh/v1alpha1/httpscaledobjects?limit=500&resourceVersion=0": dial tcp 10.2.0.1:443: connect: connection refused

and 

“{"level":"error","ts":1710299145.4313052,"caller":"scaler/queue_pinger.go:146","msg":"getting request counts","error":"there isn't any valid interceptor endpoint","stacktrace":"main.(*queuePinger).fetchAndSaveCounts\n\tgithub.com/kedacore/http-add-on/scaler/queue_pinger.go:146\nmain.(*queuePinger).start\n\tgithub.com/kedacore/http-add-on/scaler/queue_pinger.go:108\nmain.main.func3\n\tgithub.com/kedacore/http-add-on/scaler/main.go:110\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\tgolang.org/x/sync@v0.6.0/errgroup/errgroup.go:78}"

6. validated keda-add-ons-http-interceptor-proxy service, all 3 endpoint (PODs) are running

### Steps to Reproduce the Problem

1. Followed the GIT Doc to install HTTP add-on in same namespace as Keda
https://github.com/kedacore/http-add-on/blob/main/docs/install.md

Step: helm install http-add-on kedacore/keda-add-ons-http --namespace keda

2. Validate PODs status for Keda and HTTP add-on > all Pods are running

keda-add-ons-http-controller-manager 3/3 Running 0 5h35m
keda-add-ons-http-external-scaler 2/2 Running 0 12h
keda-add-ons-http-external-scaler 2/2 Running 0 12h
keda-add-ons-http-external-scaler 2/2 Running 0 12h
keda-add-ons-http-interceptor 2/2 Running 0 12h
keda-add-ons-http-interceptor 2/2 Running 0 12h
keda-add-ons-http-interceptor 2/2 Running 0 12h
keda-admission-webhooks 2/2 Running 1 (5h44m ago) 12h
keda-operator 2/2 Running 1 (5h43m ago) 12h
keda-operator-metrics-apiserver 2/2 Running 1 (5h43m ago) 12h

3. Created 'HTTPScaledObject' scaler configuration

kind: HTTPScaledObject
apiVersion: http.keda.sh/v1alpha1
metadata:
name: http-scaler
spec:
hosts:
- 'host path'
pathPrefixes:
- 'prefix Path'
targetPendingRequests: 10
scaleTargetRef:
deployment: httpbin
service: httpbin
port: 80
replicas:
min: 0
max: 10
scaledownPeriod: 300

4. Checked HTTPScaledObject scaler status:

status:
  conditions:
  - message: Identified HTTPScaledObject creation signal
    reason: PendingCreation
    status: Unknown
    timestamp: "2024-03-15T03:15:08Z"
    type: Pending

### Logs from KEDA operator

```
keda-add-ons-http-external-scaler
---

W0315 03:07:34.321874       1 reflector.go:539] k8s.io/client-go@v0.29.0/tools/cache/reflector.go:229: failed to list *v1alpha1.HTTPScaledObject: Get "https://10.2.0.1:443/apis/http.keda.sh/v1alpha1/httpscaledobjects?limit=500&resourceVersion=0": dial tcp 10.2.0.1:443: connect: connection refused

and 

“{"level":"error","ts":1710299145.4313052,"caller":"scaler/queue_pinger.go:146","msg":"getting request counts","error":"there isn't any valid interceptor endpoint","stacktrace":"main.(*queuePinger).fetchAndSaveCounts\n\tgithub.com/kedacore/http-add-on/scaler/queue_pinger.go:146\nmain.(*queuePinger).start\n\tgithub.com/kedacore/http-add-on/scaler/queue_pinger.go:108\nmain.main.func3\n\tgithub.com/kedacore/http-add-on/scaler/main.go:110\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\tgolang.org/x/sync@v0.6.0/errgroup/errgroup.go:78}"

```

### KEDA Version

2.13.1

### Kubernetes Version

1.27

### Platform

Microsoft Azure

### Scaler Details

http-add-on

### Anything else?

Environment Details:
AKS Cluster 1.27.9
Controller: 
Istio
Application Gateway 
Private Cluster: False
Test Application: Using Insomnia to trigger HTTP request to <applicationURL> 
Ports:
Application Service : 80/Tcp
keda-add-ons-http-interceptor-proxy:  8080/Tcp

**Comment by zroubalik** [comment]
Please, don't open both a discussion and an issue for the same problem, also this issue is about http add on, not core
https://github.com/kedacore/keda/discussions/5607
