### ISSUE TITLE
Document which (observability) metrics are initialized and which not

### ISSUE THREAD

**Issue by JorTurFer** [kedacore/keda#5609]
### Proposal

We expose multiple metrics but not all of them are initialized. They aren't init because it's impossible, e.g: we can't init a metric about ScaledObject latencies if there isn't any ScaledObject. Other case is when users expect information about CPU/Memory (scalers not managed by KEDA metrics server, so we cannot expose some values)

This is something that we know, but we should explain this in docs to make users aware about these limitations

**Comment by pauldotyu** [comment]
Hey @JorTurFer, if you can point me to an area within the code I should be looking at/around, I can help document this.

**Comment by JorTurFer** [comment]
Sorry for the slow response, we were in KubeCon xD
The metric collectors are here: https://github.com/kedacore/keda/tree/main/pkg/metricscollector
I think that the easiest way is starting a fresh KEDA without any CR and checking the metrics exposed. The problem of the "missing" metrics is that we don't start metrics without info. For example, we cannot init `scaler_errors` if there isn't any scaler. (and other like that)

IDK if we could check a way to init them, but I have no idea

**Comment by pauldotyu** [comment]
Thanks @JorTurFer and no worries on the slow response. I saw you and @zroubalik were busy at KubeCon. Great entertaining session BTW!! 

If you can assign this one to me, I'll dig in.

**Comment by pauldotyu** [comment]
@JorTurFer Apologies... I sat on this for far too long. I did some quick testing on this and saw that only the `keda_build_info` metric gets emitted without any scalers deployed. Added a note to the doc on in the keda-docs repo. So, if you think this will be sufficient, then I can go ahead and submit this PR. https://github.com/kedacore/keda-docs/pull/1425

**Comment by JorTurFer** [comment]
Yeah, if `keda_build_info` it's the only one, keeping it clearly documented it's nice and enough :)

**Comment by pauldotyu** [comment]
Sounds good. The PR should be ready for review. https://github.com/kedacore/keda-docs/pull/1425
