### ISSUE TITLE
Colocating metrics provider along with the operator causes HPA delays if not configured properly

### ISSUE THREAD

**Issue by bharathguvvala** [kedacore/keda#5624]
### Report

At our organization (Flipkart), we manage large k8s clusters where atleast 300 scaledobjects are present. Lately when we onboarded a bunch of new workloads to be managed by scaledobjects we saw substantial degradation to the HPA functionality where scaling events weren't happening inline with changes to corresponding compute metrics. 

A bit of a background here --  recently we upgraded k8s from 1.22.x to 1.25.x and keda from 2.2.x to 2.10.x in order to migrate to HPA v2 as well as move to a newer keda to bring in all the goodness of an upgrade. Post this upgrade everything was fine and the scaledobject count at a cluster level is around 200+ . As mentioned above, when we onboarded a bunch of new scaledobjects (50+ in count) we started seeing substantial degradation to the autoscaling pipeline which impacted all the workloads since they were not scaled out/down in time. Based on our observations it took >10mins in general.

Upon troubleshooting and profiling a bunch of components such as controller manager, k8s metrics server, keda metrics adapter and operator, we saw that the external metrics served by the keda metrics adapter was latent and the p99 latencies were around ~5s. Following our investigation after profiling and code walkthrough we realized that the metrics scraping model has changed in one of the recent releases of keda where the metrics are fetched from the operator (via grpc client) as opposed to the earlier design where the metrics are fetched from the metrics adapter. We saw that in this flow, there are calls being made to the K8s API server to update a certain fallback health status of the scaledobjects. These calls were getting rate limited at the client side causing higher read latencies for the external metrics API. We realized that the k8s clients used by the reconciliation controllers and the metrics scraper are same and come under the default rate limits. Upon increasing these rate limits from the default (20 QPS and 30 burst) the issue is resolved.

While we weren't aware of this design change which sort of merged the scraping component into the operator, we were confused as to why there are k8s API update calls being made as part of the metrics read path. We feel a couple of changes can be made to make keda users aware of deploying and supporting large scale clusters:

1. Update the health status calls only for scaledobjects which have [fallback behaviour](https://keda.sh/docs/2.13/concepts/scaling-deployments/#fallback) defined. In our case there was no fallback defined but still the status update calls were happening which led to this issue.
2. Now that, since k8s client used by reconciliation controllers and scraper components is same, both these flows are sort of coupled without isolation where one flow can swarm and get other flows to get rate limited (client side). Either separate the flows to use different clients or [document and highlight the fact](https://keda.sh/docs/2.13/operate/cluster/#kubernetes-client-parameters) so that users are aware and can configure the ratelimits accordingly in the keda operator.

### Expected Behavior

1.  Perform the health status update calls only for scaledobjects which have [fallback behaviour](https://keda.sh/docs/2.13/concepts/scaling-deployments/#fallback) defined since that status information is useful only for fallback workflow. In our case there was no fallback defined but still the status update calls were happening which led to this issue.
2. Now that, since k8s client used by reconciliation controllers and scraper components is same, both these flows are sort of coupled without isolation where one flow can swarm and get other flows to get rate limited (client side). Either separate the flows to use different clients or [document and highlight the fact](https://keda.sh/docs/2.13/operate/cluster/#kubernetes-client-parameters) so that users are aware and can configure the ratelimits accordingly in the keda operator

### Actual Behavior

Delays in HPA pipelines

### Steps to Reproduce the Problem

Deploy with default configuration and create 300+ scaledobjects.

### KEDA Version

2.10.1

### Kubernetes Version

< 1.26

### Platform

Other

**Comment by bharathguvvala** [comment]
Happy to participate in the discussion and contribute to code/documentation.

**Comment by bharathguvvala** [comment]
@JorTurFer Whichever scaledobjects have not been configured with the fallback option , isn't it better to skip [updating the fallback health status](https://github.com/kedacore/keda/blob/3bf515188196e4e1ed18c195a5c9b18a3680fe00/pkg/fallback/fallback.go#L115) for every metrics read call, which would avoid redundant API calls to the K8s API Server? Instead this condition can be updated from the controller during scaledobject reconciliations? Also means that the fallback health stats are only updated for scaledobjects where the fallback is enabled and for the rest there are defaulted during the time of the scaledobject reconciliation.

**Comment by bharathguvvala** [comment]
Regarding the documentation, I'll raise a PR in the next the couple of days which provides guidance to setup and configure KEDA on large clusters -- with high number of deployments.

**Comment by JorTurFer** [comment]
> @JorTurFer Whichever scaledobjects have not been configured with the fallback option , isn't it better to skip [updating the fallback health status](https://github.com/kedacore/keda/blob/3bf515188196e4e1ed18c195a5c9b18a3680fe00/pkg/fallback/fallback.go#L115) for every metrics read call, which would avoid redundant API calls to the K8s API Server? Instead this condition can be updated from the controller during scaledobject reconciliations? Also means that the fallback health stats are only updated for scaledobjects where the fallback is enabled and for the rest there are defaulted during the time of the scaledobject reconciliation.

Your point it's interesting, it's true that updating the fallback all the time if the feature is disabled doesn't make sense. Checking the code, I have noticed that we can be updating the value although there isn't any change.

Checking the [fallback logic](https://github.com/kedacore/keda/blob/main/pkg/fallback/fallback.go), we are callign to `updateStatus`, and there, we don't check if the status has really changed before patching the resource:
https://github.com/kedacore/keda/blob/f2d86a887d03454adaa6b91be7dcbfa264422b43/pkg/fallback/fallback.go#L115-L129

I think that we can improve that logic to reduce the calls to the API server. @zroubalik @dttung2905 @wozniakjan WDYT?

**Comment by wozniakjan** [comment]
> Checking the fallback logic, we are callign to updateStatus, and there, we don't check if the status has really changed before patching

That is a pretty good optimization, especially given there is already `DeepCopy` available https://github.com/kedacore/keda/blob/f2d86a887d03454adaa6b91be7dcbfa264422b43/pkg/fallback/fallback.go#L116
and the check could be as simple as `!reflect.DeepEqual()`

**Comment by bharathguvvala** [comment]
@wozniakjan @JorTurFer I have made a change to disable health status updates if the fallback for the scaledobject is not configured. I will go ahead with adding the tests if this change is okayed in terms of the intent. We could do additional logic to avoid redundant updates where a fallback is configured in a scaledobject , on top of this.

**Comment by bharathguvvala** [comment]
@JorTurFer @wozniakjan Taking a step back, I was thinking if this information around the error count needs to be updated back to the scaledobject status. Since this is transient information used to implement some sort of circuit breaking isn't it appropriate to keep this information inside the operator (in memory) and only update the condition whenever it flips? 

I presume this information is updated in the status only to make it persistent and survive across multiple operator restarts but it's also expensive considering that an update is performed in the read path of the GetMetrics and can potentially affect the GetMetrics latencies which in turn can affect the autoscaler SLOs. If the same error count information can be reconstructed from scratch based on the new set of errors then why not avoid persistenting it?

**Comment by JorTurFer** [comment]
> If the same error count information can be reconstructed from scratch based on the new set of errors then why not avoid persistenting it?

What do you mean? how would you reconstruct it? It's an interesting point
