### ISSUE TITLE
KEDA Operator Not Exposing kube_horizontalpodautoscaler_status_current_replicas Metric

### ISSUE THREAD

**Issue by Ravikapadne** [kedacore/keda#5655]
### Report

Hi Team,

I've encountered this while using the KEDA operator in our Kubernetes environment. It appears that the KEDA operator is not exposing the `kube_horizontalpodautoscaler_status_current_replicas` metric. This omission is impacting the functionality of our Grafana dashboards.

KEDA Dashboard: https://github.com/kedacore/keda/blob/main/config/grafana/keda-dashboard.json

<img width="1100" alt="Screenshot 2024-04-02 at 12 58 03 PM" src="https://github.com/kedacore/keda/assets/60135296/d45393aa-32c7-4bdf-99a9-6a1b157bfd8c">

<img width="1437" alt="Screenshot 2024-04-02 at 12 57 40 PM" src="https://github.com/kedacore/keda/assets/60135296/d74d4766-f0b0-464f-8825-26046fd8e0cc">

### Expected Behavior

The `kube_horizontalpodautoscaler_status_current_replicas` metric should be available and exposed by the KEDA operator, allowing external systems like Grafana to access and display this data

### Actual Behavior

kube_horizontalpodautoscaler_status_current_replicas` metric is not being exposed by the KEDA operator, resulting in missing data

### Steps to Reproduce the Problem

1. Fetch metrics at operator pod port 8080 at /metrics
2. Check grafana dashboard
 

### Logs from KEDA operator

```
example
```

### KEDA Version

2.12.0

### Kubernetes Version

1.27

### Platform

None

### Scaler Details

AWS SQS

**Comment by jereques** [comment]
@Ravikapadne As per my understanding, the metric `kube_horizontalpodautoscaler_status_current_replicas` is provided by the kube-state-metrics project and not directly by KEDA. To confirm, could you please verify if kube-state-metrics is deployed in your Kubernetes environment?

You can find more information about the metric in the kube-state-metrics documentation: [horizontalpodautoscaler-metrics.md](https://github.com/kubernetes/kube-state-metrics/blob/main/docs/horizontalpodautoscaler-metrics.md)

**Comment by zroubalik** [comment]
@jereques is right in this

**Comment by Ravikapadne** [comment]
Thanks @jereques
