### ISSUE TITLE
Restart of keda-operator causes ScaledJob object to be updated

### ISSUE THREAD

**Issue by chinmaygopal** [kedacore/keda#5656]
### Report

Restart/Recreation of keda-operator causes ScaledJob object to be updated, which leads to Jobs being rolled out as per the RolloutStrategy.

### Expected Behavior

Restart/Recreation of the keda-operator should not update the ScaledJob object

### Actual Behavior

Restart/Recreation of the keda-operator somehow update the ScaledJob object leading to Jobs being rolled out as per the RolloutStrategy.

### Steps to Reproduce the Problem

1. Kill the keda-operator (with replicas >1).
2. Wait for the keda-operator to be recreated.
3. In the Kubernetes events for the ScaledJob object, around the time the keda-operator was restarted the following events can be seen: 
  i. KEDAJobsCreated
  ii. KEDAScalersStarted

### KEDA Version

2.13.1

### Kubernetes Version

1.27

### Platform

Microsoft Azure

### Anything else?

This could also be the expected behavior of the keda-operator. However I do not understand why any changes the to keda-operator should affect the ScaledJob object.

**Comment by JorTurFer** [comment]
Hello,
This is weird and it shouldn't happen. Are you willing to take a look and open a PR with the fix?
