### ISSUE TITLE
Install fails on OpenShift 4.2

### ISSUE THREAD

**Issue by maltron** [kedacore/keda#566]
I tried to install KEDA on OpenShift 4.2 by running the following command:

# func kubernetes install --keda --namespace keda
customresourcedefinition.apiextensions.k8s.io/scaledobjects.keda.k8s.io created
serviceaccount/keda created
clusterrolebinding.rbac.authorization.k8s.io/keda created
clusterrolebinding.rbac.authorization.k8s.io/keda-hpa-role-binding created
service/keda created
deployment.apps/keda created
apiservice.apiregistration.k8s.io/v1beta1.custom.metrics.k8s.io created
apiservice.apiregistration.k8s.io/v1beta1.external.metrics.k8s.io created

However, the KEDA pod keeps crashing
# oc get events -w
https://pastebin.com/xkzMHgc5

By investigating what is going on inside the KEDA pod, I've got the following:

# oc logs keda-59748d7c48-6qx4r -n keda
unknown flag: --log-level
Usage of /usr/local/bin/keda:
      --kubeconfig string                Paths to a kubeconfig. Only required if out-of-cluster.
      --master --kubeconfig              (Deprecated: switch to --kubeconfig) The address of the Kubernetes API server. Overrides any value in kubeconfig. Only required if out-of-cluster.
      --zap-devel                        Enable zap development mode (changes defaults to console encoder, debug log level, and disables sampling)
      --zap-encoder encoder              Zap log encoding ('json' or 'console')
      --zap-level level                  Zap log level (one of 'debug', 'info', 'error' or any integer value > 0) (default info)
      --zap-sample sample                Enable zap log sampling. Sampling will be disabled for integer log levels > 1
      --zap-time-encoding timeEncoding   Sets the zap time format ('epoch', 'millis', 'nano', or 'iso8601') (default )
unknown flag: --log-level

The current func version I am using is:
# func version
3.0.2009

Please advise

**Comment by anirudhgarg** [comment]
How did you install KEDA ? Currently there is a bug in using Core Tools to install KEDA.

**Comment by maltron** [comment]
> How did you install KEDA ? Currently there is a bug in using Core Tools to install KEDA.
I was using the "func" command from Azure functions by running:
# func kubernetes install --keda --namespace keda

Eventually, I've realized I was using a newer (and maybe unstable version). The whole issue was gone when I downgrade to a older (and more stable version): 2.7.2100

Thanks for your help
