### ISSUE TITLE
Add Prometheus metrics related to ScaledObject readiness

### ISSUE THREAD

**Issue by hy00nc** [kedacore/keda#5663]
### Proposal

It'd be good to add a new Prometheus metrics in KEDA operator to monitor ScaledObject readiness, for example `keda_scaled_object_ready` similar to `keda_scaled_object_paused`.

### Use-Case

This will help us monitor the correctness and readiness of the ScaledObject in the cluster.

### Is this a feature you are interested in implementing yourself?

No

### Anything else?

I'm requesting this because `keda_scaled_object_errors` doesn't seem to cover some scaled object errors.
To be specific, when we use Prometheus scaler in the ScaledObject, if we have wrong server address and fail to create the Scaler, `keda_scaled_object_errors` value does not go up. I needed to have some other metrics to catch this kind of situation.

**Comment by JorTurFer** [comment]
Hello,
Would fixing `keda_scaled_object_errors ` be enough? I think that if there is an error we should report it and this is just a bug

**Comment by hy00nc** [comment]
Hello @JorTurFer, thank you for the reply. If that's the case, fixing the bug works for me.

**Comment by JorTurFer** [comment]
I'm checking and I can reproduce the issue, `keda_scaled_object_errors` doesn't report the value in that case, but in the meantime I can suggest to use `keda_scaler_errors` as it reports the value correctly. e.g:
```
keda_scaler_errors{metric="s0-prometheus",namespace="prometheus-test-ns",scaledObject="prometheus-test-so",scaler="prometheusScaler",triggerIndex="0",type="scaledobject"} 6
```

**Comment by hy00nc** [comment]
Thanks a lot! 👍
