### ISSUE TITLE
ERROR   scale_handler   error getting scale decision    {"scaledObject.Namespace": "elasticsearch", "scaledObject.Name": "dp-search-cluster-es-data-node", "scaler": "prometheusScaler", "error": "prometheus query api returned error. status: 403 response: {\"message\":\"Credential should be scoped to a valid region.

### ISSUE THREAD

**Issue by rameshbabu009** [kedacore/keda#5665]
### Proposal

Getting this error.

### Scaler Source

Elasticsearch pods

### Scaling Mechanics

Using Keda with Prometheus

### Authentication Source

Sigv4

**Comment by JorTurFer** [comment]
Hello,
I'm missing something, you said that you're using elaticsearch scaler, but the logs is related with Prometheus scaler. Could you give use some context about your case? What KEDA version you're using, what triggers you're using and how you're authenticating them, etc.
