### ISSUE TITLE
Quickstart on OCP4: using the Kafka bootstrap service instead of the headless one

### ISSUE THREAD

**Issue by ppatierno** [kedacore/keda#567]
In the Quickstart about using KEDA on OCP4, the example in the wiki mentions the following change for the `brokerList`:

```yaml
"brokerList": "my-cluster-kafka-brokers.openshift-operators:9092",
```

Actually, the `-brokers` service is a headless one meant to be used for supporting Statefulset and internal communication. Even if it's working fine, the `-bootstrap` service should be used to connect external applications to Kafka deployed via Strimzi.
I cannot propose a PR because it's on the Wiki but I would suggest to change the example using:

```yaml
"brokerList": "my-cluster-kafka-bootstrap.openshift-operators:9092",
```
As a side question ... why not moving the example as a markdown out of the Wiki? It's simpler for allowing the community to interact and proposing changes and suggestions via PRs.

/cc @markusthoemmes

**Comment by tomkerkhove** [comment]
We certainly should do this, looks like we forgot to move this out of the wiki during our migration to Markdown.

You can now find it here and I've made your suggested change:
https://github.com/kedacore/sample-azure-functions-on-ocp4

**Comment by ppatierno** [comment]
Thanks Tom, I think it makes more sense and is useful for the community.
