### ISSUE TITLE
TriggerAuthentication's `aws` provider does not seem to work with CRD based ScaledObjects

### ISSUE THREAD

**Issue by congiv** [kedacore/keda#5691]
### Report

I am trying to use AWS IRSA to set up auth for an AWS SQS based Scaler using the role of the workload, not the keda-operator. It seems like that should be possible using [TriggerAuthentication's `podIdentity.provider=aws`](https://keda.sh/docs/2.13/concepts/authentication/#aws-pod-identity-webhook-for-aws), and configuring one of `roleArn` or `identityOwner=workload`. This works as expected with ScaledJob and with ScaledObjects that refer to a Deployment. However, when I make the ScaledObject's `scaleTargetRef` use a CRD, such as [argo-rollout's Rollout](https://argo-rollouts.readthedocs.io/en/stable/features/specification/), it no longer assumes the role of the workload. 

I don't see any logs that suggest that the keda-operator even attempted to assume out from the operator's role to the role of the workload. A workaround would be to add the required AWS permissions to the keda-operator's role. However, on a cluster where that keda-operator is serving many different tenants, the role would become bloated and/or overly permissive.

### Expected Behavior

keda-operator should be able to assume an arbitrary AWS IAM role to support CRD `scaleTargetRef`s  from ScaledObject using TriggerAuthentication's `podIdentity.provider=aws` and at least one of:
- `podIdentity.roleArn=arn:aws:iam::*******:role/my-workload-role`
- `podIdentity.identityOwner=workload`

### Actual Behavior

keda-operator does not appear to try to assume the role of the workload, resulting in an error that it doesn't have SQS permissions, see below logs. 

### Steps to Reproduce the Problem

1. Create an AWS EKS Cluster, and [enable its AWS IAM OIDC Provider for IRSA](https://docs.aws.amazon.com/eks/latest/userguide/enable-iam-roles-for-service-accounts.html).
2. Create an AWS SQS Queue
3. Create 2 AWS IAM Roles, one for the keda-operator and one for the workload.
    - keda-operator role trust policy
         ```json
         {
             "Version": "2012-10-17",
             "Statement": [
                 {
                     "Effect": "Allow",
                     "Principal": {
                         "Federated": "arn:aws:iam::*****:oidc-provider/oidc.eks.us-east-1.amazonaws.com/id/******"
                     },
                     "Action": "sts:AssumeRoleWithWebIdentity",
                     "Condition": {
                         "StringLike": {
                             "oidc.eks.us-east-1.amazonaws.com/id/******:sub": "system:serviceaccount:keda:keda-operator"
                         }
                     }
                 }
             ]
         }
         ```
    - keda-operator role resource policy (it should not need any resource policies as all it should do is AssumeRole to a role within the same account, which is granted by the trust of the workload role. In the use-cases with Deployment or ScaledJob that work correctly, I do not need this policy)
        ```json
        {
            "Version": "2012-10-17",
            "Statement": [
                {
                    "Sid": "sqs",
                    "Effect": "Allow",
                    "Action": [
                        "sts:AssumeRole",
                        "sts:TagSession"
                    ],
                    "Resource": [
                        "$ARN_OF_YOUR_WORKLOAD_ROLE"
                    ]
                }
            ]
        }
         ```      
    - my-workload role trust policy:
         ```json
         {
             "Version": "2012-10-17",
             "Statement": [
                {
                    "Effect": "Allow",
                    "Principal": {
                        "AWS": "$ARN_OF_ABOVE_KEDA_OPERATOR_ROLE"
                    },
                    "Action": [
                        "sts:AssumeRole",
                        "sts:TagSession"
                    ]
                }
             ]
         }
         ```
     - my-workload resource policy:
        ```json
        {
            "Version": "2012-10-17",
            "Statement": [
                {
                    "Sid": "sqs",
                    "Effect": "Allow",
                    "Action": [
                        "sqs:*"
                    ],
                    "Resource": [
                        "$ARN_OF_YOUR_SQS_QUEUE"
                    ]
                }
            ]
        }
         ```
     
4. Install [Argo Rollouts](https://argo-rollouts.readthedocs.io/en/stable/installation/) and KEDA, be sure the annotate the ServiceAccount of the keda-operator `eks.amazonaws.com/role-arn=$ARN_OF_KEDA_OPERATOR_ROLE` to complete the IRSA setup.
5. Create a ScaledObject using an SQS Scaler that refers to a Rollout and uses a TriggerAuthentication:
    - with a roleArn:
       ```yaml
        ---
        apiVersion: keda.sh/v1alpha1
        kind: TriggerAuthentication
        metadata:
          name: my-workload
          namespace: my-workload
        spec:
          podIdentity:
            provider: aws
            roleArn: $ARN_OF_WORKLOAD_ROLE

       ```
    - OR with workload:
       ```yaml
        ---
        apiVersion: keda.sh/v1alpha1
        kind: TriggerAuthentication
        metadata:
          name: my-workload
          namespace: my-workload
        spec:
          podIdentity:
            provider: aws
            identityOwner: workload
       ```

### Logs from KEDA operator 

```
2024-04-15T13:14:04Z	INFO	Initializing Scaling logic according to ScaledObject Specification	{"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "ScaledObject": {"name":"my-workload","namespace":"my-workload"}, "namespace": "my-workload", "name": "my-workload", "reconcileID": "*********"}
2024-04-15T13:14:04Z	INFO	Reconciling ScaledObject	{"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "ScaledObject": {"name":"my-workload","namespace":"my-workload"}, "namespace": "my-workload", "name": "my-workload", "reconcileID": "*********"}
2024-04-15T13:14:04Z	INFO	Detected resource targeted for scaling	{"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "ScaledObject": {"name":"my-workload","namespace":"my-workload"}, "namespace": "my-workload", "name": "my-workload", "reconcileID": "*********", "resource": "argoproj.io/v1alpha1.Rollout", "name": "my-workload"}
2024-04-15T13:14:04Z	ERROR	aws_sqs_queue_scaler	Error getting queue length	{"type": "ScaledObject", "namespace": "my-workload", "name": "my-workload", "error": "operation error SQS: GetQueueAttributes, https response error StatusCode: 403, RequestID: ************, api error AccessDenied: User: arn:aws:sts::****************:assumed-role/keda-operator/********** is not authorized to perform: sqs:getqueueattributes on resource: arn:aws:sqs:us-east-1:****************:my-workload-queue because no identity-based policy allows the sqs:getqueueattributes action"}
github.com/kedacore/keda/v2/pkg/scalers.(*awsSqsQueueScaler).GetMetricsAndActivity
	/workspace/pkg/scalers/aws_sqs_queue_scaler.go:225
github.com/kedacore/keda/v2/pkg/scaling/cache.(*ScalersCache).GetMetricsAndActivityForScaler
	/workspace/pkg/scaling/cache/scalers_cache.go:130
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).getScalerState
	/workspace/pkg/scaling/scale_handler.go:743
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).getScaledObjectState.func1
	/workspace/pkg/scaling/scale_handler.go:628
```

You can see from above that keda-operator expects it's own role to have permissions to interact with the SQS Queue. 

### KEDA Version

2.13.1

### Kubernetes Version

1.28

### Platform

Amazon Web Services

### Scaler Details

AWS SQS

**Comment by m3talstorm** [comment]
Also seeing this, same setup

**Comment by matthew-collins-dailypay** [comment]
@congiv I'm running into this as well - did you manage to find a fix or workaround?

**Comment by congiv** [comment]
@matthew-collins-dailypay I couldn't find a workaround that would use the workload's role. I haven't seen whether this is fixed in a newer KEDA release, but the only workaround I found in this version was adding the permissions to the operator's role.

**Comment by matthew-collins-dailypay** [comment]
@congiv - Appreciate you replying! Turns out Keda's auth logic seems to break on `rollouts` which use `workloadRef`. I've managed to work around this bug by inlining our templates rather than referencing an existing deployment.

Not sure if it's the same root cause as your problem, but wanted to post here for others benefit.

**Comment by aarsic95** [comment]
@matthew-collins-dailypay thank you very much. This made it work for us!
