### ISSUE TITLE
KEDA Autoscaling for selenium grid || FailedGetExternalMetric  the HPA was unable to compute the replica count || unable to get external metric prod/s0-seleniumgrid-MicrosoftEdge

### ISSUE THREAD

**Issue by vinuvk11** [kedacore/keda#5694]
### Discussed in https://github.com/kedacore/keda/discussions/5682

<div type='discussions-op-text'>

<sup>Originally posted by **vinuvk11** April 11, 2024</sup>
 kubectl get hpa -n prod
NAME                          REFERENCE            TARGETS             MINPODS   MAXPODS   REPLICAS   AGE
keda-hpa-selenium-grid-edge   Deployment/browser   <unknown>/1 (avg)   5         50        5          44h

kubectl describe hpa keda-hpa-selenium-grid-edge -n prod

Metrics:                                                   ( current / target )
  "s0-seleniumgrid-MicrosoftEdge" (target average value):  <unknown> / 1
Min replicas:                                              5
Max replicas:                                              50
Deployment pods:                                           5 current / 0 desired
Conditions:
  Type           Status  Reason                   Message
  ----           ------  ------                   -------
  AbleToScale    True    SucceededGetScale        the HPA controller was able to get the target's current scale
  ScalingActive  False   FailedGetExternalMetric  the HPA was unable to compute the replica count: unable to get external metric prod/s0-seleniumgrid-MicrosoftEdge/&LabelSelector{MatchLabels:map[string]string{scaledobject.keda.sh/name: selenium-grid-edge,},MatchExpressions:[]LabelSelectorRequirement{},}: unable to fetch metrics from external metrics API: the server is currently unable to handle the request (get s0-seleniumgrid-MicrosoftEdge.external.metrics.k8s.io)
Events:
  Type     Reason                   Age                    From                       Message
  ----     ------                   ----                   ----                       -------
  Warning  FailedGetExternalMetric  112s (x5094 over 21h)  horizontal-pod-autoscaler  unable to get external metric prod/s0-seleniumgrid-MicrosoftEdge/&LabelSelector{MatchLabels:map[string]string{scaledobject.keda.sh/name: selenium-grid-edge,},MatchExpressions:[]LabelSelectorRequirement{},}: unable to fetch metrics from external metrics API: the server is currently unable to handle the request (get s0-seleniumgrid-MicrosoftEdge.external.metrics.k8s.io)

Error is unable to auto scale the selenium grid browser sessions

#$ cat keda_selenium.yaml
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: selenium-grid-edge
  namespace: prod
  labels:
    deploymentName: browser
spec:
  minReplicaCount: 5
  maxReplicaCount: 50
  pollingInterval: 3
  cooldownPeriod:  30
  scaleTargetRef:
    name: browser
  triggers:
    - type: selenium-grid
      metadata:
        url: 'http://selenium-hub.prod:4444/graphql'
        browserName: 'MicrosoftEdge'
        unsafeSsl: 'true'
        sessionBrowserName: 'msedge'
        #maxQueuedSessions: '5'

</div>

Issues like unable to get response while get external metrics 

kubectl get --raw "/apis/external.metrics.k8s.io/v1beta1"
Error from server (ServiceUnavailable): the server is currently unable to handle the request

<img width="579" alt="image" src="https://github.com/kedacore/keda/assets/165902584/6bab5d69-d327-4238-a16c-4cfa49e270ae">

**Comment by vinuvk11** [comment]
HPA targets are shown unknown
![image](https://github.com/kedacore/keda/assets/165902584/9872791e-bfbb-4e5b-ae7c-d1b287b4e058)

while describing the HPA "scalingActive is false" and thrwon with error

![image](https://github.com/kedacore/keda/assets/165902584/8c3dd756-f866-41ac-b6cd-ccf52838d567)

**Comment by katukna** [comment]
Hi @vinuvk11 ... Were you able to resolve your issue?

**Comment by vinuvk11** [comment]
NO havent able to resolve the issue in on-premises, tried on cloud instances and got successful scaling via KEDA
