### ISSUE TITLE
MySQL Scaler

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda#571]
A clear and concise description of what scaler you'd like to use and how you'd want to use it:

  - **Scaler Source:** MySQL Scaler

**Comment by tomkerkhove** [comment]
This is being worked on by @nuclearpinguin here: https://github.com/kedacore/keda/pull/564

**Comment by nuclearpinguin** [comment]
@tomkerkhove I've updated the docs, can you please take another look? ;)
