### ISSUE TITLE
Threshold for scaling out and Threshold for scaling in

### ISSUE THREAD

**Issue by Leonardo-Ferreira** [kedacore/keda#5713]
### Proposal

There should be a threshold for scaling out, and another for scaling in.

### Use-Case

This way you can implement something like "If there are more than 1000 messages queued, scale OUT another pod. If there are more than 20 but less than 1000 messages, don't do anything. If there are less than 20, scale IN one pod"...

or perhaps "If each of my pods are dealing with more than 100 req/s, scale out. If they are handling between 20 and 99 don't change, if they each and all of them are handling less than 20 req/s scale in by 1"

### Is this a feature you are interested in implementing yourself?

Maybe

**Comment by Leonardo-Ferreira** [comment]
Any feedback, anyone?

**Comment by zroubalik** [comment]
Hi, thanks for the proposal, I do understand the reasoning, unfortunately it is very hard to achieve as the scaling itself is driven by HPA and it doesn't support such behaviour. Do you have any specific ideas how to do that?

**Comment by Leonardo-Ferreira** [comment]
hey @zroubalik, I opened this one: https://github.com/kubernetes/autoscaler/issues/6990
