### ISSUE TITLE
Filter Grafana Dashboard Metric Values Based on ScaledObject, scaler and namespace

### ISSUE THREAD

**Issue by B4llouk** [kedacore/keda#5714]
### Proposal

On the Grafana dashboard, `metric ` variable is not filtered on other variables like `ScaledObject `, `scaler `and `namespace`. 
This creates combinations in the Grafana dashboard that make no sense.  In the `Scaler Metric Value` panel for example. 

### Current Behavior

When using the Grafana dashboard with KEDA, I select the variables such as:
- scaler A
- scaledObject B
- namespace C

However, the subsequent `metric ` variables that appear are not automatically filtered to correspond with these selections. This requires manual verification to ensure that the metrics displayed are relevant to the chosen `scaler `, `scaledObject` and `namespace`. 

### Expected Behavior
I would like the Grafana dashboard to automatically filter metric variables based on the previously selected variables like scaler, scaledObject and namespace. This enhancement would ensure that the metrics displayed are directly relevant to my selections. 

### Is this a feature you are interested in implementing yourself?

Yes

**Comment by tomkerkhove** [comment]
Good idea, feel free to open a PR!

**Comment by zroubalik** [comment]
any update here?
