### ISSUE TITLE
 Feature Request: Support Array of App Names or Labels in scaleTargetRef

### ISSUE THREAD

**Issue by ucguy4u** [kedacore/keda#5717]
### Proposal

KEDA currently supports scaling individual deployments using the scaleTargetRef field within a ScaledObject. This feature request proposes an enhancement to allow scaleTargetRef to accept an array of application names or a label selector. This will enable a single ScaledObject to scale multiple deployments, which is particularly useful for microservices that need to be scaled in tandem based on common metrics.

### Use-Case

This feature would be beneficial in scenarios where multiple services, possibly forming a logical group, need to scale up or down together in response to shared workloads or events. For instance, in microservices architectures, different services that handle parts of the same transaction might need to be scaled simultaneously to maintain consistent performance.

An example use case is a microservices-based e-commerce application where the catalog service, the shopping cart service, and the order processing service may need to scale up during high traffic events like sales or promotions.

### Is this a feature you are interested in implementing yourself?

No

### Anything else?

Implementing this feature would reduce the overhead of managing multiple ScaledObject resources for operators and could improve the efficiency of using KEDA in larger-scale environments. It also aligns with the cloud-native principles of automation and scalability.

**Comment by zroubalik** [comment]
Hi thanks for the input, we have discussed this issue a few times and we decided to keep the current behavior. There are some downsides (managing multiple HPAs, how to deal with fallback, etc).
