### ISSUE TITLE
Suggested improvements for Grafana dashboard's panels titles and legend format 

### ISSUE THREAD

**Issue by B4llouk** [kedacore/keda#5718]
### Proposal

- In the panel `Current/max replicas (time based)` we are showing HPA metrics, same as the panel `Changes in replicas`. I think we should be more explicit about it in the panel title. 
- In   `Changes in replicas` panel, `legendFormat `is set to `"."` and should be more insightful, my suggestion: `"legendFormat": "scaling status",
`

### Use-Case

- Panel titles for `Current/max replicas (time based)` and `Changes in replicas` would be more insightful. 
- Legend in `Changes in replicas` panel would be more insightful 

### Is this a feature you are interested in implementing yourself?

Yes

**Comment by tomkerkhove** [comment]
Are you willing to contribute those changes?

**Comment by zroubalik** [comment]
any update here?
