### ISSUE TITLE
Proposal - Run E2E tests in CI

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda#572]
We currently have nightly E2E tests which take 4 minutes.

I was wondering if there is a particular reason why we don't run them in every CI per PR? Can't hurt I think?

**Comment by zroubalik** [comment]
Currently it takes 13-14mins as we keep adding more scalers to E2E tests, but I think that it is still feasible to run them during each PR.

But the main issue is, that the tests are runing on shared kubernetes instance. So in case there are 2 opened PRs in approx the same time, the test will interfere.

**Comment by ahmelsayed** [comment]
They run on every merge to master as well. We will need to only trigger them manually for external contributions since it'll be deploying code to the test cluster. However, the point @zroubalik brought up about shared cluster stands, but at least the manual triggering can be coordinated.
