### ISSUE TITLE
Metrics Server: `klogr.New` is deprecated use `textlogger.NewLogger` instead

### ISSUE THREAD

**Issue by zroubalik** [kedacore/keda#5732]
### Proposal

https://github.com/kedacore/keda/blob/9a00d1e7c3fd1d5acc4c736f2ff9f943d6aa1c2b/cmd/adapter/main.go#L58

```
cmd/adapter/main.go:58:14: SA1019: klogr.New is deprecated: this uses a custom, out-dated output format. Use textlogger.NewLogger instead. (staticcheck)
var logger = klogr.New().WithName("keda_metrics_adapter")
```

Let's migrate to the new interface, there might be some changes in the config/parameters etc.

It might also help with issues like: https://github.com/kedacore/keda/issues/5139

### Is this a feature you are interested in implementing yourself?

Maybe

**Comment by JorTurFer** [comment]
I think that it's a good moment to unify all the loggers across components, operator uses zap IIRC, maybe can give a try but I think that custom-metrics-apiserver can be the blocker here

**Comment by guopeng0** [comment]
Hi @zroubalik , I would like to work on this issue can you please assign it to me.

**Comment by zroubalik** [comment]
@guopeng0 thanks!
