### ISSUE TITLE
Errors while doing a build - Did not find /usr/local/bin/user_setup

### ISSUE THREAD

**Issue by anirudhgarg** [kedacore/keda#575]
Keda build fails. Not sure if I need to do something more before I do a "make build"

Step 4/7 : COPY build/bin /usr/local/bin
 ---> Using cache
 ---> d5ae5e8ce607

Step 5/7 : RUN /usr/local/bin/user_setup &&     mkdir /apiserver.local.config &&     chmod 777 /apiserver.local.config &&     chmod +x ${OPERATOR}
 ---> Running in a758878e121b
/bin/sh: /usr/local/bin/user_setup: /bin/sh^M: bad interpreter: No such file or directory

**Comment by zroubalik** [comment]
@anirudhgarg I am not able to reproduce that. Haven't you deleted any files/folders in `build` directory?

Please attach full log

**Comment by anirudhgarg** [comment]
Attached full log, No I didn't delete anything AFAIK. I am using the devcontainer with VSCode.

I have attached the full log

root@ac1a99bf335c:/workspaces/keda# make build
GO111MODULE=on CGO_ENABLED=0 GOOS=linux GOARCH=amd64 operator-sdk generate k8s
INFO[0000] Running deepcopy code-generation for Custom Resource group versions: [keda:[v1alpha1], ] 
INFO[0008] Code-generation complete.                    
GO111MODULE=on CGO_ENABLED=0 GOOS=linux GOARCH=amd64 operator-sdk generate openapi
INFO[0000] Running OpenAPI code-generation for Custom Resource group versions: [keda:[v1alpha1], ] 
INFO[0011] Created deploy/crds/keda.k8s.io_scaledobjects_crd.yaml 
INFO[0012] Created deploy/crds/keda.k8s.io_triggerauthentications_crd.yaml 
INFO[0012] Code-generation complete.                    
GO111MODULE=on CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build \
        -ldflags "-X=main.GitCommit=81977bf2cb5d4cc386d606a65ad3f08bbbb40f7e" \
        -o build/_output/bin/keda-adapter \
        cmd/adapter/main.go
docker build -f build/Dockerfile.adapter -t docker.io/kedacore/keda-metrics-adapter:master .
Sending build context to Docker daemon  69.98MB
Step 1/7 : FROM registry.access.redhat.com/ubi8/ubi-minimal:latest
 ---> d17cc1f9d041
Step 2/7 : ENV OPERATOR=/usr/local/bin/keda-adapter     USER_UID=1001     USER_NAME=keda
 ---> Using cache
 ---> af138c3234b3
Step 3/7 : COPY build/_output/bin/keda-adapter ${OPERATOR}
 ---> Using cache
 ---> cff5100e8a61
Step 4/7 : COPY build/bin /usr/local/bin
 ---> Using cache
 ---> d5ae5e8ce607
Step 5/7 : RUN /usr/local/bin/user_setup &&     mkdir /apiserver.local.config &&     chmod 777 /apiserver.local.config &&     chmod +x ${OPERATOR}
 ---> Running in 7ea3a3393f02
/bin/sh: /usr/local/bin/user_setup: /bin/sh^M: bad interpreter: No such file or directory
The command '/bin/sh -c /usr/local/bin/user_setup &&     mkdir /apiserver.local.config &&     chmod 777 /apiserver.local.config &&     chmod +x ${OPERATOR}' returned a non-zero code: 126
Makefile:68: recipe for target 'build-adapter' failed
make: *** [build-adapter] Error 126
root@ac1a99bf335c:/workspaces/keda#

**Comment by zroubalik** [comment]
`/bin/sh^M: bad interpreter: No such file or directory` 
`^M` is carriage return character, so looks like the script is not correctly interpreted. Probably combination of Windows and the devcontainer? I don't use either, so can't help with that :(

**Comment by anirudhgarg** [comment]
yes that was it !  I used a utility dos2unix to convert the line endings of all the files in the build folder and it worked. Thanks for your help !
