### ISSUE TITLE
Local build, deployment and testing of KEDA is not a smooth experience

### ISSUE THREAD

**Issue by rasavant-ms** [kedacore/keda#576]
## Expected Behavior
Documents for locally building, deploying and testing KEDA would be easy to follow and give smooth developer experience

## Actual Behavior
* Documents missing pre-requisites
Eg. It would be nice to know the expected GOLang version, HELM version, etc.
* Documents missing details for different operating systems.
Eg. Command `helm install . --set image.keda=kedacore/keda:$IMAGE_TAG,image.metricsAdapter=kedacore/keda-metrics-adapter:$IMAGE_TAG,image.pullPolicy=IfNotPresent` does not work for Windows commandline.
* Documents missing instructions to delete local KEDA deployment
Eg. `helm uninstall <name>`

## Steps to Reproduce the Problem

  1. Follow local build and deployment instructions on Github page - https://github.com/kedacore/keda#building-locally-directly
https://github.com/kedacore/keda#deploying-custom-keda

## Specifications

  - **Version:** N/A
  - **Platform:** Windows 10.0.18363 N/A Build 18363
  - **Scaler(s):** N/A

**Comment by jeffhollan** [comment]
Thanks @rasavant-ms for raising.  Tagging @melmaliacone as well only because I know they are working on some improvements to some of the local instructions and may be relevant for some of those PRs.

**Comment by anirudhgarg** [comment]
Also @rasavant-ms since you have just gone through it - would really appreciate it if you can submit any PR's to improve this.

**Comment by rasavant-ms** [comment]
@melmaliacone helped me with my local deployment issues and said they are working on the PR. Would be happy to help out!

**Comment by zroubalik** [comment]
This instructions should help with local development: https://github.com/kedacore/keda/pull/583

**Comment by zroubalik** [comment]
I supposed this is solved already
