### ISSUE TITLE
Version 2.14 - MongoDB Atlas scheme

### ISSUE THREAD

**Issue by lsteinberg-r7** [kedacore/keda#5760]
### Report

I'm trying to use the latest version's feature of MongoDB Atlas scheme support (mongodb+srv), and getting conflicting requirements -

Keda scale-handler requires a port to be given, otherwise it's failing with:
`failed to parsing mongoDB metadata, because of missing required field in scaler config: no port given`

But if I'm supplying a port, MongoDB driver itself is failing with the following message:
`URI with srv must not include a port number`
which comes from this piece of code - https://github.com/kedacore/keda/blob/c55e306af94bf41d69c4f3d43744398fa07a358e/vendor/go.mongodb.org/mongo-driver/x/mongo/driver/topology/topology.go#L390-L403

### Expected Behavior

Scaler defined with the `+srv` scheme should not require a port number.

### Actual Behavior

Scaler defined with the `+srv` scheme requires a port number, even though it conflicts with the driver's requirements.

### Steps to Reproduce the Problem

1. Define a real Atlas host
2. Define a scaler that uses the host, with a port number
3. See the error event in the scaler definition in k8s.

### Logs from KEDA operator

```
example
```

### KEDA Version

2.14.0

### Kubernetes Version

None

### Platform

Google Cloud

### Scaler Details

MongoDB

**Comment by JorTurFer** [comment]
Nice catch! Are you willing to open a PR with the fix?

**Comment by JorTurFer** [comment]
no worries! Let's see if anyone wants to help here, I'd say that it should be easy

**Comment by Rishikesh01** [comment]
Hi @JorTurFer  I was able to replicate OP error in `mongo_scaler_test.go`, after doing the following changes as shown in pic.  
![image](https://github.com/kedacore/keda/assets/53863619/25198b9f-7d1c-45d9-937e-c3f54e4fc601)

**Comment by Rishikesh01** [comment]
Have opened an pr: https://github.com/kedacore/keda/pull/5773 please take a look when you have time :)
