### ISSUE TITLE
Expose new HPA config around scaling behavior in ScaledObject

### ISSUE THREAD

**Issue by jeffhollan** [kedacore/keda#578]
As of `1.17` the HPA has a few options to control scaling behavior as documented here

https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#support-for-configurable-scaling-behavior

Would be good to expose these and configurable values in the `ScaledObject`

**Comment by jeffhollan** [comment]
Some discussion here https://kubernetes.slack.com/archives/CKZJ36A5D/p1580157353072300

**Comment by nuclearpinguin** [comment]
I think we will have to wait for [1.18](https://github.com/kubernetes/api/blob/924612ff3bca0e127b87d7c9ba26abf3c20e0f47/autoscaling/v2beta2/types.go#L80) as it seems that [1.17](https://github.com/kubernetes/api/blob/4ed536977f46736ee9334e6e29097551f17e8211/autoscaling/v2beta2/types.go#L74) doesn't support behavior definitions.

**Comment by zroubalik** [comment]
This issue is being tracked in https://github.com/kedacore/keda/issues/802
