### ISSUE TITLE
Dynamic Pod Scaling Based on Request Count

### ISSUE THREAD

**Issue by Ravikapadne** [kedacore/keda#5786]
### Proposal

Hi Team,

I am reaching out to discuss a potential enhancement to the KEDA autoscaling capabilities that could greatly benefit users who need more dynamic scaling options based on specific metrics, such as request counts

Background:
Our team is currently leveraging KEDA to autoscale our Kubernetes deployments. We've found KEDA to be incredibly useful for managing our resources efficiently. However, we've encountered a scenario where we need to scale our pods more dynamically based on the number of requests our service receives

Requirement:
We are looking for a way to scale our pods based on the total request count. Specifically, we would like to automatically scale the number of pods in direct proportion to the request count. For example:
- If the request count increases to 10,000, we would like to scale to 10 pods.
- If the request count reaches 20,000, we would like to scale to 20 pods, and so on.

This approach would allow us to handle spikes in traffic more efficiently and ensure that our services remain responsive under varying loads

Thanks,
Ravindra Kapadne

### Is this a feature you are interested in implementing yourself?

No

**Comment by JorTurFer** [comment]
Hello,
Do you mean that you want to scale based on HTTP traffic? You can currently do it using an indirect measure (for example, scrapping the ingress metrics using prometheus and prometheus scaler). 
If you want something more powerful, you can take a look to the [HTTP add-on](https://github.com/kedacore/http-add-on), but it's still on beta
