### ISSUE TITLE
 Report the use of components with vulnerabilities in keda

### ISSUE THREAD

**Issue by HouqiyuA** [kedacore/keda#5790]
### Report

Dear Team Members:
Greetings! Our team is very interested in your project. we performed source code perspective security analysis (SCA) and vulnerability library association analysis on this project and found that components with vulnerabilities are still being used into this project.We would like to report this issue to you,so that you can fix and improve it accordingly. I add the details in json file below. Please confirm whether this problem really exists and confirm with us. Looking forward to hearing from you and discussing more details with us, thank you very much for your time and attention.

Note: Each "affect_components" field in the report represents the vulnerable component introduced by this project. The other is the vulnerability information associated with it.

Qiyu Hou

[keda-main_report.json](https://github.com/kedacore/keda/files/15260047/keda-main_report.json)

### Expected Behavior

None

### Actual Behavior

None

### Steps to Reproduce the Problem

1.
2.
3.

### Logs from KEDA operator

```
example
```

### KEDA Version

None

### Kubernetes Version

None

### Platform

None

**Comment by zroubalik** [comment]
Hi, thanks for reporting, are you willing to open a fix for these?
