### ISSUE TITLE
Getting " no matches for kind "TriggerAuthentication" in version "keda.k8s.io/v1alpha1" ensure CRDs are installed first" while spplying scaledobject for Keda

### ISSUE THREAD

**Issue by KasyapG** [kedacore/keda#5791]
### Report

We are trying apply a scaledobject for scaling based on HTTP requests (using Azure managed prometheus). While doing kubectl apply -f <scaledobject.yaml> getting the below mentioned error.

 "resource mapping not found for name: "azure-managed-prometheus-trigger-auth" namespace: "60486a51-7039-4f45-b1be-a0069c86f864" from "test-sample-keda-hpa-azm-prom.yaml": no matches for kind "TriggerAuthentication" in version "keda.k8s.io/v1alpha1"
ensure CRDs are installed first
resource mapping not found for name: "azure-managed-prometheus-scaler" namespace: "60486a51-7039-4f45-b1be-a0069c86f864" from "test-sample-keda-hpa-azm-prom.yaml": no matches for kind "ScaledObject" in version "keda.k08s.io/v1alpha1"
ensure CRDs are installed first"

Could you please let me know what is being missed here.

Regards,
Kasyap G

### Expected Behavior

Scaledobject should be applied without any error.

### Actual Behavior

Getting the error mentioned above.

### Steps to Reproduce the Problem

1. Running Kubectl apply -f <> command.

### Logs from KEDA operator

![image](https://github.com/kedacore/keda/assets/88187095/a57d8414-e559-44e0-a9b1-32873d5a373c)

### KEDA Version

2.11.0

### Kubernetes Version

1.27

### Platform

Microsoft Azure

### Scaler Details

Prometheus

**Comment by JorTurFer** [comment]
Hello,
Could you share the output of this command? 
```
kubectl get crd | grep keda
```

**Comment by revoltez** [comment]
@KasyapG  Had the same issue and i Fixed it by changin the `apiVersion` from `keda.k8s.io/v1alpha1` to `keda.sh/v1alpha1` 
@JorTurFer  I think the documentation should be updated as its using the wrong apiVersion [here](https://keda.sh/docs/1.4/scalers/redis-lists/#example)

**Comment by JorTurFer** [comment]
Thanks for the comment @revoltez , that docs are correct indeed as the page is for v1.4 (so old), if you go to v2.X the API will be the new one

**Comment by revoltez** [comment]
@JorTurFer Ah yeah that's true, i think it would be great if you make it sticky banner for old APIs maybe!
