### ISSUE TITLE
leaderelection.go:320] error retrieving resource lock keda/operator.keda.sh: invalid character ', after object key

### ISSUE THREAD

**Issue by AShengQiang** [kedacore/keda#5793]
### Expected Behavior

created scaledobject, then create hpa。

### Actual Behavior

created scaledobject, hpa not create。

### Steps to Reproduce the Problem

1.POST https://4ddf94a9-57a3-11ee-b348-0255ac1000b2.cce.cn-east-204-dev.myhuaweicloud.com/(11.108.28.110):443/apis/keda.sh/v1alpha1/namespaces/ns-cce-codehub-advanced-szv-g-az2/scaledobjects
2.2024-03-14 10:27:00.629 [vert.x-eventloop-thread-1] INFO HttpTaskHelper[395] - HTTP Response: 201 Created\r\n{"apiVersion":"keda.sh/v1alpha1","kind":"ScaledObject","metadata":{"creationTimestamp":"2024-03-14T02:27:00Z","generation":1,"managedFields":[{"apiVersion":"keda.sh/v1alpha1","fieldsType":"FieldsV1","fieldsV1":{"f:spec":{".":{},"f:advanced":{".":{},"f:horizontalPodAutoscalerConfig":{".":{},"f:behavior":{".":{},"f:scaleUp":{".":{},"f:policies":{},"f:selectPolicy":{},"f:stabilizationWindowSeconds":{}}}},"f:restoreToOriginalReplicaCount":{}},"f:cooldownPeriod":{},"f:maxReplicaCount":{},"f:minReplicaCount":{},"f:pollingInterval":{},"f:scaleTargetRef":{".":{},"f:name":{}},"f:triggers":{}}},"manager":"cfe-apiserver","operation":"Update","time":"2024-03-14T02:27:00Z"}],"name":"edge","namespace":"ns-cce-codehub-advanced-szv-g-az2","resourceVersion":"123442902","uid":"f3926d09-e388-4043-aced-4d59808607f9"},"spec":{"advanced":{"horizontalPodAutoscalerConfig":{"behavior":{"scaleUp":{"policies":[{"periodSeconds":15,"type":"Percent","value":100},{"periodSeconds":15,"type":"Pods","value":2}],"selectPolicy":"Max","stabilizationWindowSeconds":0}}},"restoreToOriginalReplicaCount":true},"cooldownPeriod":300,"maxReplicaCount":2,"minReplicaCount":1,"pollingInterval":30,"scaleTargetRef":{"name":"codehubedge-advanced-szv-g-regular-az2"},"triggers":[{"metadata":{"type":"Utilization","value":"4"},"name":"cpu","type":"cpu"},{"metadata":{"type":"Utilization","value":"4"},"name":"memory","type":"memory"}]}}\n

### Logs from KEDA operator

```
keda version：2.0.0
```
![image](https://github.com/kedacore/keda/assets/59719534/5cba0375-f82e-4966-b669-0ed8d432b2a1)

### KEDA Version

< 2.10.0

### Kubernetes Version

None

### Platform

None

**Comment by JorTurFer** [comment]
Hello,
What KEDA version are you using?

**Comment by AShengQiang** [comment]
keda 2.0.0

**Comment by AShengQiang** [comment]
> Hello, What KEDA version are you using?

keda 2.0.0

**Comment by zroubalik** [comment]
this is way to old, unsupported version, please update to newer one.
