### ISSUE TITLE
After completing a task, the Pod consistently enters the CrashLoopBackOff state repeatedly with the same Pod.

### ISSUE THREAD

**Issue by abhishek96negi** [kedacore/keda#5798]
### Report

<img width="1037" alt="image" src="https://github.com/kedacore/keda/assets/64316612/671b9990-7f5c-4507-b1a9-2f0c81551932">

### Expected Behavior

Pod should be terminated after completed the task

### Actual Behavior

POD restart again and again

### Steps to Reproduce the Problem

1. use RaabitMQ scalers KEDA

### Logs from KEDA operator

```
example
```

### KEDA Version

2.14.0

### Kubernetes Version

1.29

### Platform

Google Cloud

### Scaler Details

Rabbitmq

**Comment by zroubalik** [comment]
this is more likely not related to KEDA but to the workload itselft. KEDA doesn't manage this part of the workload's lifecycle
