### ISSUE TITLE
Upgrade KEDA to use Debian 12 Distroless

### ISSUE THREAD

**Issue by jhawkins1** [kedacore/keda#5800]
### Proposal

Since Debian 12 Distroless is available, as well as, the latest releases of Kubernetes and many of the Kubernetes related projects have moved to Debian 12, we would request that KEDA move to Debian 12 Distroless.   The other benefit of moving to Debian 12 is there is a population of current and future Operating Systems Vulnerabilities (CVEs) that Debian is not addressing in Debian 11 but only Debian 12.  

### Use-Case

Alignment of OS to other Kubernetes related Projects.  Reduces fan-out of multiple OSes or different versions of OSes across components.  Potential benefits as to being able to obtain OS patches for vulnerabilities where Debian has decided only to fix in latest LTS release.

### Is this a feature you are interested in implementing yourself?

No

**Comment by kady1711** [comment]
Following up on the proposal for migrating KEDA to Debian 12 Distroless. This move is crucial for ensuring KEDA aligns with the broader Kubernetes ecosystem, which has largely transitioned to Debian 12. Additionally, the migration to Debian 12 Distroless would address the concern of operating system vulnerabilities (CVEs) that Debian has chosen not to fix in Debian 11 but only in Debian 12.

The benefits of this migration include improved alignment with Kubernetes-related projects, reduced complexity in managing multiple OS versions, and enhanced security through access to OS patches for vulnerabilities addressed exclusively in the latest LTS release.

Could you please provide an update on the status of this proposal? Specifically, it would be helpful to know if there is a **targeted release date or version number** by which this migration is expected to be completed.

This information is vital for our planning and ensures that we can maintain a secure and consistent environment across our deployments.

**Comment by zroubalik** [comment]
This proposal is soon, are you willing to contribute this?
