### ISSUE TITLE
Add support for access token authentication to an Azure Postgres Flexible Server - Postgres scaler

### ISSUE THREAD

**Issue by Ferdinanddb** [kedacore/keda#5823]
### Proposal

The Postgres scaler only supports basic authentication through username and password, but it is now possible to authenticate to a Postgres server hosted in the cloud by using "access token".

The purpose of this issue is to add support to enable access token authentication within the Postgres scaler by extending it, possibly with additional parameters.

### Use-Case

In Azure, a managed identity does not have a password associated to it, but can obtain short-lived credentials (called access tokens) to connect to certain resources. It is possible for [an Azure managed identity to connect to an Azure Postgres Flexible server](https://learn.microsoft.com/en-us/azure/postgresql/flexible-server/how-to-connect-with-managed-identity).

### Is this a feature you are interested in implementing yourself?

Yes

### Anything else?

 I created this PR: https://github.com/kedacore/keda/pull/5589. I tested it in my own Azure subscription to see if it works with my own use case (related to Apache Airflow) and it worked.

**Comment by Ferdinanddb** [comment]
The doc of this new feature has been updated via [this PR in keda-docs](https://github.com/kedacore/keda-docs/pull/1437).

Thank you very much for your help on this @JorTurFer, much appreciated!

**Comment by JorTurFer** [comment]
You're welcome :)
Thanks for this nice improvement! We will cut a release during the week, so you can expect it soon :)
