### ISSUE TITLE
Unable to scale with AmbiguousSelector message when there are multiple HPA

### ISSUE THREAD

**Issue by KasyapG** [kedacore/keda#5825]
### Report

- We have two HPA (1. KEDA-Kafka scaler 2. Native HPA) which were working as expeccted and scaling applications based on metrics. 
- we recently got upgraded to kubernetes 1.27.7 version and now see scaling is not happening and the HPA description shows ScalingActive as False and throws message "pods by selector rtf.mulesoft.com/id=d20e76b6-02af-48ea-b9d1-d62ad3b020e6 are controlled by multiple HPAs: [namespace/keda-hpa-att-perf-msgrtr-e namespace/att-perf-msgrtr-e".
- keda is on 2.11 and compatibility matrix shows this compatible with 1.27.7.
- Just to add we are having seperately scalers to avoid single point of failure for Keda not working as expected scenarios.

![image](https://github.com/kedacore/keda/assets/88187095/eacc44ab-6594-4d3b-80ed-3ea27f1bc003)

![image](https://github.com/kedacore/keda/assets/88187095/344a73cc-49c6-439e-b327-cbe83e4d6adc)

### Expected Behavior

Scaling should work as expected when there HPA and Keda Kafka separately as well.

### Actual Behavior

Not scaling and thew description shows below error.

![image](https://github.com/kedacore/keda/assets/88187095/d8e309fa-903c-4ff0-9e98-4ee0d88d60b3)

### Steps to Reproduce the Problem

1. Implement Keda and apply a Kafka trigger scaledobject.
2. Then apply a HPA with CPU and Memory trigger seperately.

### Logs from KEDA operator

```
example
```

### KEDA Version

2.11.0

### Kubernetes Version

1.27

### Platform

Microsoft Azure

### Scaler Details

Kafka

**Comment by JorTurFer** [comment]
Hello,
I'd say that you upgrade k8s from 1.25 or below to 1.27. Am I right?
The error and message that you are facing with isn't from KEDA but from Kubernetes directly:
- PR: https://github.com/kubernetes/kubernetes/pull/112011
- Commit: https://github.com/kubernetes/kubernetes/commit/caddfdd0407d32c68176b52d05f3b65a8dd79f04

They introduced a check to validate that a workload is managed by a single HPA based on pod labels/selectors. There isn't anything that we can do. The only thing that I can do is suggesting reviewing your pod labels to avoid conflicts with selectors
