### ISSUE TITLE
github-runner support for GitHub Runner Groups

### ISSUE THREAD

**Issue by rdvansloten** [kedacore/keda#5853]
### Proposal

My organization is using Runner Groups to filter GitHub workflow jobs/tasks into different private runners, but by default only a preset list of repos or ent/org is supported, where KEDA will trigger on all jobs pending for the entire org. I haven't found a way to scope it to a specific Runner Group. I am not sure if the base URL "api.github.com" can be adjusted to include a path/arg as a workaround, but I couldn't find much about what precise call KEDA does to what/where.

### Use-Case

We're intending to use this in conjunction with Azure's Container Apps Jobs (A few Kubernetes jobs in a trench coat):
https://learn.microsoft.com/en-us/azure/container-apps/tutorial-ci-cd-runners-jobs?tabs=bash&pivots=container-apps-jobs-self-hosted-ci-cd-azure-pipelines

So the flow without being to scope to Runner Groups would be:
GitHub Job pending -> KEDA in all my environments respond to org-wide Job pending -> all Container App Jobs in all my environments go +1

Desired outcome:
GitHub Job pending for RunnerGroupABC -> KEDA in environment ABC responds to Job pending -> Container App Job in environment ABC goes +1

### Is this a feature you are interested in implementing yourself?

No

**Comment by KoblerS** [comment]
wouldn't it work if you use labels for label your workflow runsOn?

```yaml
runs-on:
  group: org/my-group
  labels: [ self-hosted, my-group]
```
