### ISSUE TITLE
Add custom name to Prometheus triggers to make the scaling dimensions clearer

### ISSUE THREAD

**Issue by AlonGluz** [kedacore/keda#5874]
### Proposal

When creating several Prometheus triggers, the dashboard becomes a bit cluttered, and the Promql labels for the metrics are a concatenation of the trigger  and the type which is less ideal.

### Use-Case

Make Keda Grafana dashboard clearer and provide more trust in the tool

### Is this a feature you are interested in implementing yourself?

Maybe

**Comment by zroubalik** [comment]
You can add a custom name to a trigger: https://keda.sh/docs/2.14/concepts/scaling-deployments/#triggers
