### ISSUE TITLE
'commonLabels' is deprecated.

### ISSUE THREAD

**Issue by therealdwright** [kedacore/keda#5887]
### Report

'commonLabels' is deprecated. Kustomizations should use 'labels' instead.

### Expected Behavior

When running `kustomize build .` on a modern version there is no deprecation warning.

### Actual Behavior

There is a deprecation warning:
```
# Warning: 'commonLabels' is deprecated. Please use 'labels' instead. Run 'kustomize edit fix' to update your Kustomization automatically.
```

### Steps to Reproduce the Problem

1. `cd config/default`
2. `kustomize build .` using kustomize 5.x

### Logs from KEDA operator

N/A

### KEDA Version

2.14.0

### Kubernetes Version

1.27

### Platform

Amazon Web Services

**Comment by ayushrakesh** [comment]
Hey @therealdwright, is this issue solved? I am interested to work.

**Comment by therealdwright** [comment]
Yes I already made a PR.
