### ISSUE TITLE
HPA warning - selector is required (ScaledObject with cron trigger)

### ISSUE THREAD

**Issue by gerbil** [kedacore/keda#5898]
Non-stop warnings in namespace events:
![image](https://github.com/kedacore/charts/assets/455953/b5162f35-5078-47d4-a4dc-a6188998d5c3)

## Expected Behavior
No warnings or errors after ScaledObject creation

## Actual Behavior
Namespace event/warning -> selector is required (Reason: SelectorRequired)

```yaml
kind: Event
apiVersion: v1
metadata:
  name: keda-hpa-backend.17da56bd723508de
  namespace: ivp-test
  uid: c7a39d49-7904-494d-b379-c05e3d6bad31
  resourceVersion: '23791866'
  creationTimestamp: '2024-06-19T07:19:39Z'
  managedFields:
    - manager: kube-controller-manager
      operation: Update
      apiVersion: v1
      time: '2024-06-19T07:34:40Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:count: {}
        f:firstTimestamp: {}
        f:involvedObject: {}
        f:lastTimestamp: {}
        f:message: {}
        f:reason: {}
        f:reportingComponent: {}
        f:source:
          f:component: {}
        f:type: {}
involvedObject:
  kind: HorizontalPodAutoscaler
  namespace: ivp-test
  name: keda-hpa-backend
  uid: 87f0527b-7e4d-4633-96c8-a3a3a3ed28dd
  apiVersion: autoscaling/v2
  resourceVersion: '23784754'
reason: SelectorRequired
message: selector is required
source:
  component: horizontal-pod-autoscaler
firstTimestamp: '2024-06-19T07:19:39Z'
lastTimestamp: '2024-06-19T07:34:40Z'
count: 61
type: Warning
eventTime: null
reportingComponent: horizontal-pod-autoscaler
reportingInstance: ''
```

HPA spec part
```json
...
"spec": {
        "maxReplicas": 100,
        "metrics": [
            {
                "external": {
                    "metric": {
                        "name": "s0-cron-Europe-Riga-10xx1-5923xx5",
                        "selector": {
                            "matchLabels": {
                                "scaledobject.keda.sh/name": "backend"
                            }
                        }
                    },
                    "target": {
                        "averageValue": "1",
                        "type": "AverageValue"
                    }
                },
                "type": "External"
            }
        ],
        "minReplicas": 3,
        "scaleTargetRef": {
            "apiVersion": "deployment.xxx.com/v1alpha1",
            "kind": "ApplicationDeployment",
            "name": "backend"
        }
    },
...
```

ScaledObject 
```yaml
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  labels:
    scaledobject.keda.sh/name: backend  
  name: backend
  namespace: ivp-test
status:  
  externalMetricNames:
    - s0-cron-Europe-Riga-10xx1-5923xx5
  hpaName: keda-hpa-backend
  originalReplicaCount: 3
  scaleTargetGVKR:
    group: deployment.xxx.com
    kind: ApplicationDeployment
    resource: applicationdeployments
    version: v1alpha1
  scaleTargetKind: deployment.xxx.com/v1alpha1.ApplicationDeployment
spec:
  cooldownPeriod: 30
  idleReplicaCount: 0
  minReplicaCount: 3
  scaleTargetRef:
    apiVersion: deployment.xxx.com/v1alpha1
    kind: ApplicationDeployment
    name: backend
  triggers:
    - metadata:
        desiredReplicas: '3'
        end: 59 23 * * 5
        start: 1 0 * * 1
        timezone: Europe/Riga
      name: backend
      type: cron
```

## Steps to Reproduce the Problem

  1. ScaledObject with cron trigger
  2. Observe an events in the namespace
 

## Specifications

  - **KEDA Version:** *2.14.0*
  - **Platform & Version:** *Azure AKS 1.28.9*
  - **Kubernetes Version:** *1.28.9*
  - **Scaler(s):** *Cron*

**Comment by tomkerkhove** [comment]
@JorTurFer @zroubalik any idea?

@gerbil can you try leaving out `name: backend` in your scaledobject to see if it is related to custom naming please?

**Comment by gerbil** [comment]
@tomkerkhove  the same for `name: tmp`
![image](https://github.com/kedacore/keda/assets/455953/780d2a7a-ab12-40c2-bab2-2e4865ad941b)

**Comment by JorTurFer** [comment]
One question, does your workload have any label? I'd say that the error comes due to missing labels on the workload. If the workload doesn't have labels, the selector will be empty

**Comment by gerbil** [comment]
Could you please elaborate a bit more on what exactly does this error means? I can clearly see matchLabel selectors on HPA in `spec.external.metrics` Or am i looking into wrong field/object? Custom resources controlled by scaleTargetRef inside ScaledObject **does not** contain any labels indeed.

**Comment by gerbil** [comment]
I've managed to fix this by adding [CRD subresource reconcile logic](https://medium.com/@thescott111/autoscaling-kubernetes-custom-resource-using-the-hpa-957d00bb7993) into custom operator to have valid `scale` and `status` subresources; Now when i got `/scale` output with correct `status.selector` field i can see that HPA can observe current/desired state of the CRD owned objects.

**Comment by zroubalik** [comment]
> I've managed to fix this by adding [CRD subresource reconcile logic](https://medium.com/@thescott111/autoscaling-kubernetes-custom-resource-using-the-hpa-957d00bb7993) into custom operator to have valid `scale` and `status` subresources; Now when i got `/scale` output with correct `status.selector` field i can see that HPA can observe current/desired state of the CRD owned objects.

yeah, that's the problem, `/scale` needs to be implemented correctly (incl status), HPA controller checks that
