### ISSUE TITLE
Pass Metadata from ScaledJob Template to ChildJob Template Metadata

### ISSUE THREAD

**Issue by SpiritZhou** [kedacore/keda#5908]
### Proposal

We encountered a situation where we set up annotations in the template metadata of ScaledJob, but the pod generated by ScaledJob had empty metadata. The annotation that pod needed was not passed through. 

I suggest adding the `// +kubebuilder:pruning:PreserveUnknownFields` flag in JobTargetRef so that the scaledjob crd will keep properties to ensure that the metadata is passed through.

### Is this a feature you are interested in implementing yourself?

Yes

**Comment by zroubalik** [comment]
Makes sense, good catch!

**Comment by tomkerkhove** [comment]
@SpiritZhou Can you work on this when you have some time?

**Comment by SpiritZhou** [comment]
Yes. I am working on this. I found another option: add `crd:generateEmbeddedObjectMeta=true` in Makefile to generate Metadata properties.
