### ISSUE TITLE
Not able to install keda  helm charts using terraform

### ISSUE THREAD

**Issue by subbu-prasant-sage** [kedacore/keda#5918]
resource "helm_release" "kedas" {
  name             = "keda"
  repository = "[https://kedacore.github.io/charts"](https://kedacore.github.io/charts%22)
  chart            = "keda"
  version          = "2.14.2"
  namespace        = "keda"
  create_namespace = true
  
}

Error ---->

helm_release.kedas: Creating...
╷
│ Error: could not download chart: Chart.yaml file is missing
│ 
│   with helm_release.kedas,
│   on keda.tf line 22, in resource "helm_release" "kedas":
│   22: resource "helm_release" "kedas" {
│ 
╵

**Comment by Mohan0607** [comment]
I am also facing the same issue, please give any solution for this one
