### ISSUE TITLE
Custom HPA metric names

### ISSUE THREAD

**Issue by pznamensky** [kedacore/keda#5925]
### Proposal

Currently, KEDA creates HPA with [auto-generated metric names](https://github.com/kedacore/keda/issues/4220) (i.e `s0-prometheus`).
Though we can customise a trigger name via `trigger.name`, metric name cannot be changed.
Usually that's not a problem, but in our case it's a bit confusing.
We usually use multiple triggers for our apps.
To understand what causes scaling up, we used to plot these two prometheus metrics from hpa:
- `kube_horizontalpodautoscaler_status_target_metric`
- `kube_horizontalpodautoscaler_spec_target_metric`

or target & hpa spec values.

This is a convenient method to understand what's going on with HPA and what hpa.spec.metrics should be tuned.
However, as hpa.spec.metrics from KEDA are auto-generated, it's not as straightforward anymore.

Fortunately, KEDA has `keda_scaler_metrics_value` that shows the current value of a metric in a trigger.
As we can specify `trigger.name`, we could use this metric, but there is no corresponding `keda_scaler_metrics_target` to compare with.

So, from my perspective, there could be two possible solutions on how to add more visibility:
- add the ability to somehow customise hpa.spec.metrics names (i.e. by adding a custom prefix or postfix to it, or use `trigger.name` as prefix/postfix)
- add prometheus metric `keda_scaler_metrics_target` to get be able to compare it with `keda_scaler_metrics_value`

How does that sound to you?

### Is this a feature you are interested in implementing yourself?

No

**Comment by guicholeo** [comment]
I'm also interested in this. We would want the metric name in the HPA for Prometheus to pick up.

**Comment by pznamensky** [comment]
It seems we need to create a new issue, as stale bot already closed this one.
