### ISSUE TITLE
Enable Kafka Trigger scalar to work with Event Hubs w/Kafka endpoint

### ISSUE THREAD

**Issue by rasavant-ms** [kedacore/keda#594]
Enable Kafka Trigger scalar to work with Event Hubs w/Kafka endpoint.
Currently, the authentication options supported for Kafka trigger do not support this.

### Use-Case

This will enable using the Kafka trigger scalar to work with Event Hubs as well.

### Specification

- [ ] Enable SASL_SSL Plain mechanism authentication with the Kafka trigger Scalar

**Comment by tomkerkhove** [comment]
Re-opening since the docs have not been updated, can you send a PR to https://github.com/kedacore/keda-docs please?

**Comment by rasavant-ms** [comment]
Added PR for docs on Kafka Trigger scalar - https://github.com/kedacore/keda-docs/pull/78
