### ISSUE TITLE
Keda operator gives error "Webhook not found. Unable to update certificate." after disabling admission webhook

### ISSUE THREAD

**Issue by sinanub18** [kedacore/keda#5963]
### Report

We deployed keda 2.13.0 after disabling admission webhook but we are constantly getting below error of unable to update certificate. Is disabling admission webhook disbales cert updation / rotation for metric server and keda-operator as well??

### Expected Behavior

Keda operator should able to rotate / update certificate for keda-operator, keda-metricserver and **ignore webhook service.**

### Actual Behavior

keda-operator throwing error "Webhook not found. Unable to update certificate."

### Steps to Reproduce the Problem

1. Disable admission webhook
2. Deploy keda operator and keda-metric service with keda managed cert

### Logs from KEDA operator

```
{"level":"error","ts":"2024-07-15T08:03:38Z","logger":"cert-rotation","msg":"Webhook not found. Unable to update certificate.","name":"keda-admission","gvk":"admissionregistration.k8s.io/v1, Kind=ValidatingWebhookConfiguration","error":"ValidatingWebhookConfiguration.admissionregistration.k8s.io \"keda-admission\" not found","stacktrace":"github.com/open-policy-agent/cert-controller/pkg/rotator.(*ReconcileWH).ensureCerts\n\t/workspace/vendor/github.com/open-policy-agent/cert-controller/pkg/rotator/rotator.go:816\ngithub.com/open-policy-agent/cert-controller/pkg/rotator.(*ReconcileWH).Reconcile\n\t/workspace/vendor/github.com/open-policy-agent/cert-controller/pkg/rotator/rotator.go:785\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:119\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:316\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:227"}
```

### KEDA Version

2.13.0

### Kubernetes Version

None

### Platform

None

**Comment by lzianekhodja-aneo** [comment]
We have exactly the same configurations and error with Keda version 2.15.2.

**Comment by sinanub18** [comment]
Hi, We have again observed this issue, is it fixed in any version?
@JorTurFer

**Comment by JorTurFer** [comment]
Could you create another issue to track your case and fulfil with fresh info? This issue was closed by inactivity > 1 years ago
