### ISSUE TITLE
Visual Studio Code Dev Container fails build

### ISSUE THREAD

**Issue by Cottonglow** [kedacore/keda#604]
The dev container in visual studio code fails to build the project with the latest from master.

## Expected Behavior
Succeeds build.

## Actual Behavior
The following error appears:
```bash
root@ea9dfb9a7c2f:/workspaces/keda# make build
GOROOT is not defined
Makefile:61: recipe for target 'checkenv' failed
make: *** [checkenv] Error 1
```

## Steps to Reproduce the Problem

  1. Pull the latest from master
  2. Using Visual Studio Code, open project as a remote container
  3. Run `make build`

## Specifications

  - **KEDA Version:** master
  - **Platform & Version:** Running this on Windows 10

**Comment by Cottonglow** [comment]
### Workaround
Current workaround just to get it working again for those who have this problem. **Not** proposing this as a solution.

Comment out or remove the following lines of code:
```Makefile
.PHONY: checkenv
checkenv:
ifndef GOROOT
	@echo "GOROOT is not defined"
	@exit 1
endif
```
Update line 66 from:
```Makefile
build: checkenv build-adapter build-controller
```
to 
```Makefile
build: build-adapter build-controller
```

**Comment by tomkerkhove** [comment]
Pulling in @ppatierno who made the change, can you elaborate on how to optimize this?

**Comment by ppatierno** [comment]
@tomkerkhove I am not a Go expert (yet :-)) but my question would be how it worked without setting the `GOROOT` env var? Can the other checks if their `GOROOT` is set? In my case without it the local build fails. What's different from the dev container build?

**Comment by ppatierno** [comment]
Something interesting here https://github.com/operator-framework/operator-sdk/issues/2288

**Comment by ppatierno** [comment]
@Cottonglow if others are not facing my issue with GOROOT I would suggest you can open a PR to revert my change because it is stopping dev container build right now. I will figure out more on it.

**Comment by ppatierno** [comment]
I thought more about it. Because it can be anyway a problem as it happened to me, what do you think to leave the `checkenv` target there (which could be anyway useful in the future) but providing a warning error instead of exiting if `GOROOT` is missing? @zroubalik @Cottonglow @tomkerkhove wdyt?

**Comment by zroubalik** [comment]
@ppatierno I like the warning approach!
