### ISSUE TITLE
ScaledObject template metadata does not get applied

### ISSUE THREAD

**Issue by unzld** [kedacore/keda#6046]
Metadata from spec.jobTargetRef.template.metadata does not get applied to ScaledObject pods.

Not sure how the charts here are generated, but it could be a bug for KEDA itself. I saw [this issue](https://github.com/kedacore/keda/issues/1311) and maybe the patch is no longer being applied? Checking the CRD for scaledjob, x-kubernetes-preserve-unknown-fields is no longer present. The patch itself in [https://github.com/kedacore/keda/blob/v2.14.0/config/crd/patches/scaledjob_patch.yaml](https://github.com/kedacore/keda/blob/v2.14.0/config/crd/patches/scaledjob_patch.yaml) is still present though.

For the meantime I downgraded to v2.13 since it's still working there.

## Expected Behavior
Metadata should be present in the ScaledObject's pods

## Actual Behavior
Pods are missing the metadata defined in the ScaledObject

## Steps to Reproduce the Problem

  1. Install 2.14.0 chart
  2. Add a ScaledJob, insert a test label in spec.jobTargetRef.template.metadata
  3. Resulting pods will not have the test label

## Specifications

  - **KEDA Version:** 2.14.0

**Comment by JorTurFer** [comment]
This was solved in v2.15 -> https://github.com/kedacore/keda/blob/v2.15.0/config/crd/patches/scaledjob_patch.yaml
