### ISSUE TITLE
Problem enumeration

### ISSUE THREAD

**Issue by LY-today** [kedacore/keda#6061]
### Proposal

1. when I only configure cron,The test is like this. When I manually modify replicas during non-cron periods, it will eventually become minReplicaCount, which is not very friendly to the business. is there any way to allow the business to still have the right to make decisions in this situation?
2. keda-metrics-apiserver Is remote-adapter to prometheus-adapter currently supported? Because there are some stock metrics on it. Please refer to：https://github.com/gocrane/crane/blob/main/docs/tutorials/effective-hpa-with-prometheus-adapter.md3
3.  autoscaling.keda.sh/paused-replicas Automatic scaling was not restored after test deletion in 1.8.2

### Is this a feature you are interested in implementing yourself?

Maybe

**Comment by JorTurFer** [comment]
Hello

> 1. when I only configure cron,The test is like this. When I manually modify replicas during non-cron periods, it will eventually become minReplicaCount, which is not very friendly to the business. is there any way to allow the business to still have the right to make decisions in this situation?

Any kind of manual modification will be reverted automatically always. KEDA (and the HPA controller) is scaling the workload and it doesn't know if you have manually modified them. To achieve this, you should pause the autoscaling setting the desired replicas

> 2. keda-metrics-apiserver Is remote-adapter to prometheus-adapter currently supported? Because there are some stock metrics on it. Please refer to：[gocrane/crane@main/docs/tutorials/effective-hpa-with-prometheus-adapter.md](https://github.com/gocrane/crane/blob/main/docs/tutorials/effective-hpa-with-prometheus-adapter.md?rgh-link-date=2024-08-12T02%3A51%3A25Z)

No, KEDA doesn't support it. I'd suggest asking to crane team to support KEDA too

>3. autoscaling.keda.sh/paused-replicas Automatic scaling was not restored after test deletion in 1.8.2

https://github.com/kedacore/keda/issues/6062

I close this as not planned as the only thing left has its own issue
