### ISSUE TITLE
Breaking change in KEDA 2.14.3 for AADPODIdentity Authentication with podIdentity.activeDirectory.identity

### ISSUE THREAD

**Issue by aamarnath12** [kedacore/keda#6075]
### Report

After upgrading to KEDA version 2.14.3, if you are using aadpodIdentity set up during Helm deployment with property  podIdentity.activeDirectory.identity={your-label-name}, an error is encountered when the service is trying to scale with error "IdentityID of PodIdentity should not be empty"
Docs used for Reference: https://keda.sh/docs/2.14/authentication-providers/azure-ad-pod-identity/
Similiar bug reported: https://github.com/kedacore/keda/issues/5109 

### Expected Behavior

The service should scale as expected with aadpodidentity 

### Actual Behavior

the service does not scale with error 
"IdentityID of PodIdentity should not be empty"

### Steps to Reproduce the Problem

1. Upgrade to AKS version 1.28.12
2. Upgrade to KEDA 2.14.3
3. Look into keda operator logs for this error "IdentityID of PodIdentity should not be empty"

### Logs from KEDA operator

```
example
```
2024-08-13T20:50:44Z    INFO    scale_handler   WARNING: Azure AD Pod Identity has been archived (
https://github.com/Azure/aad-pod-identity#-announcement)
and will be removed from KEDA on v2.15       {"type": "ScaledObject", "namespace": "default", "name": "service-worker"}
2024-08-13T20:50:44Z    ERROR   scale_handler   error resolving auth params     {"type": "ScaledObject", "namespace": "default", "name": "service-worker", "triggerIndex": 2, "error": "IdentityID of PodIdentity should not be empty"}
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).buildScalers
        /workspace/pkg/scaling/scalers_builder.go:99

### KEDA Version

2.14.1

### Kubernetes Version

1.28

### Platform

Microsoft Azure

**Comment by gustavoaca1997** [comment]
I am having the same issue.
