### ISSUE TITLE
Metrics API scaler doesn't parse Prometheus metric with multiple labels

### ISSUE THREAD

**Issue by JorTurFer** [kedacore/keda#6077]
### Report

Metrics API Scaler supports reading values in Prometheus format. The problem is that the Prometheus metric parse is just a strings comparison. This works for metrics without labels or just with a single label, but metrics with 2 or more labels are incorrectly parsed, having more fields than the expected amount of fields:

![image](https://github.com/user-attachments/assets/35378d01-c893-4e75-97d1-b6409124883d)

We should parse the Prometheus metrics and then compare the labels to avoid weird behaviors and the requirement of weird escape of the strings

### Expected Behavior

Metrics API scaler supports any Prometheus metrics

### Actual Behavior

It only supports metrics without labels or with a single label

### Steps to Reproduce the Problem

This can be reproduced just updating the unit test `TestGetValueFromResponse` to include a Prometheus response with a metric that has at least 2 labels. e.g:

```golang
inputPrometheus := []byte(`# HELP backend_queue_size Total number of items
# TYPE backend_queue_size counter
backend_queue_size{queueName="zero"} 0
backend_queue_size{queueName="one"} 1
backend_queue_size{queueName="cache_enabled", instance="qa-khoffman-develop"} 3`)
```

**Comment by abbi-gaurav** [comment]
Hi,
Could someone please share details in which KEDA version it would be available?

Thanks,
Gaurav

**Comment by JorTurFer** [comment]
> Could someone please share details in which KEDA version it would be available?

v2.16
