### ISSUE TITLE
From brokerList to bootstrapServers in the Kafka scaler trigger

### ISSUE THREAD

**Issue by ppatierno** [kedacore/keda#608]
Hi all, 
I can see from Git history that the `brokerList` was `brokers` in the Kafka scaler time ago.
What I would like to propose is changing it again to `bootstrapServers` which is the most common and recognized way to specify "bootstrap" servers on the first connection from a Kafka client.
Actually, it's really a "bootstrap" servers list because it doesn't need to contain ALL the brokers in the cluster but one or more from which the client gets metadata so that can connect to right brokers later (so it's for bootstrapping...).
The "brokerList" name could drive in the wrong direction with the meaning that you need to put ALL the brokers there, which is not true. This name is still used in the Kafka upstream project for the kafka-console-producer tool but it's going to be changed in order to align with the kafka-console-consumer which uses a "--bootstrap-servers" parameter instead.
Said that, how do you approach when changing something in the CRDs?
As far as I can see, triggers metadata is just a map so there is no validation at CRD level / API server level but just inside the scaler when it gets the metadata.
In this case, do you agree if I propose to change this trigger field in `bootstrapServers`?

**Comment by zroubalik** [comment]
Your proposal makes sense. My only concern is, that this could be potentionaly a breaking change.

We could support both ways for some time and mark `brokerList` as deprecated, (we could print warning if user uses this property).

We are planning to release v2.0 with some breaking changes in ScaledObject CRD so that could be a right time of getting rid of `brokerList`.

**Comment by ppatierno** [comment]
Yes, for this reason, I was asking how you are approaching changes like this in CRDs.
I will open a PR supporting both of them for a marking `brokerList` as deprecated for the time being.
On 2.0 release we'll get rid of it.

**Comment by tomkerkhove** [comment]
Reopening for docs https://github.com/kedacore/keda-docs/pull/81

**Comment by ppatierno** [comment]
Closing because the related KEDA docs PR was merged.
