### ISSUE TITLE
Allow to scale differently sized browser nodes on selenium-grid scaler

### ISSUE THREAD

**Issue by rubroboletus** [kedacore/keda#6080]
### Proposal

Currently the selenium-grid scaler needs exactly same sizing for every browser node with any browser / platform combination. We are in situation, where windows browser nodes are static and linux browser nodes are scaled by KEDA. Size of our Windows nodes is 4 browser slots / node with two browsers on each. But we wanna to scale linux nodes with just one slot and one browser per pod. In current situation it does not work well, because KEDA supposes, that all browser nodes are same size. We like to have ability to set browser node size for browser / platform combination and be able to read this size from grid, when at least one node of such combination is up.

### Is this a feature you are interested in implementing yourself?

Yes

**Comment by zroubalik** [comment]
Sounds reasonable :)
