### ISSUE TITLE
KEDA cannot parse PEM certificate from Azure Container Apps secrets when using GitHub Runner scaler

### ISSUE THREAD

**Issue by krukowskid** [kedacore/keda#6083]
### Report

I am trying to setup KEDA GitHub runner scaler in Azure Container Apps, using GitHub Actions .PEM certificate passed as secret. Unfortunately the only option is to pass .pem content as one liner. I've double-checked the pem and secret itself. The runner container is able to use same secret to register in GitHub.

I've tried multiple formats of one-liner pem - just copy pasted, without spaces, with `/n`

### Expected Behavior

KEDA should connect to GitHub with .pem and scale runners

### Actual Behavior

KEDA cannot parse the certificate

### Steps to Reproduce the Problem

1. Use azure container apps
2. Setup KEDA GitHub scaler options
3. Set the `authenticationRef` key as `appKey` and value as reference to secret with `.pem` content

### Logs from KEDA operator

```
error creating GitHub App client: could not parse private key: invalid key: Key must be a PEM encoded PKCS1 or PKCS8 key
```

### KEDA Version

2.14.0

### Kubernetes Version

None

### Platform

Microsoft Azure

### Scaler Details

GitHub Runner

**Comment by JorTurFer** [comment]
Hello,
We don't have any relation with Azure Container Apps, this is the Open Source project and ACA is a Microsoft product. You have to ask directly to ACA team -> https://github.com/microsoft/azure-container-apps/issues
FYI @pauldotyu

**Comment by krukowskid** [comment]
@JorTurFer I believe that this is not ACA specific error.

**Comment by JorTurFer** [comment]
Although it can be KEDA's error by the message, it can be an implementation error in the ACA product passing any value. Microsoft sells KEDA as a product and offers support for it. If you face with the same error using your own KEDA installation, please send the KEDA operator logs, the ScaledObject/ScaledJob and KEDA version and we will be more than happy trying to help
