### ISSUE TITLE
unable to fetch metrics from external metrics 

### ISSUE THREAD

**Issue by yaronworldwide** [kedacore/keda#609]
We are currently trying to integrate Keda on existing projects in order to scale up/down (from and to 0) pods according to number of messages in pubsub .
The following metrics are already in use in our GCP-Projects :

**v1beta1.custom.metrics.k8s.io          monitoring/prom-adapter-1030759040                  True        28d
v1beta1.extensions                     Local                                               True        53d
v1beta1.external.metrics.k8s.io        custom-metrics/custom-metrics-stackdriver-adapter   True        53d
v1beta1.metrics.k8s.io                 kube-system/metrics-server                          True        53d**

We would like to figure out a way to integrate keda (despite existing metrics) and the existing issue https://github.com/kedacore/keda/issues/20 

In order to do so we  have removed external.metrics.k8s.io from our keda project 

[Uploading keda.zip…]()
[Uploading keda-scaledobject.zip…]()

_while executing **kubectl describe hpa keda-hpa-xdr-st-3008200-pipeline -n xdr-st** the following error appears:
ch metrics from external metrics API: the server could not find the descriptor for metric gcppubsubsubscriptionsize: googleapi: Error 404: Could not find descriptor for metric 'gcppubsubsubscriptionsize'., notFound
  Warning  FailedComputeMetricsReplicas  9s (x4 over 54s)  horizontal-pod-autoscaler  failed to get GCPPubSubSubscriptionSize external metric: unable to get external metric xdr-st/GCPPubSubSubscriptionSize/&LabelSelector{MatchLabels:map[string]string{deploymentName: xdr-st-3008200-pipeline,},MatchExpressions:[],}: unable to fetch metrics from external metrics API: the server could not find the descriptor for metric gcppubsubsubscriptionsize: googleapi: Error 404: Could not find descriptor for metric 'gcppubsubsubscriptionsize'., notFound_

I would like to know if is possible to integrate keda with our current setup ?
Moreover we need keda to perform scale up / down based on 2 metrics and folloowing bug is currently preventing us to do so - https://github.com/kedacore/keda/issues/550
Any estimation on how/when we would be able to integrate multiple metrics to Keda ?

**Comment by yaronworldwide** [comment]
Issue was caused because google_credentials were not from secret

**Comment by zroubalik** [comment]
@yaronworldwide sorry for reaching to you that late. Could you please confirm to me, that you were able to run KEDA with your own metrics-adapter?

**Comment by yaronworldwide** [comment]
@zroubalik I was able to run Keda using existing metrics-adapter (external.metrics.k8s.io) by removing yaml files which were creating keda-metrics (such as metrics-api_service.yaml ...)
Would you like me to share my setup ?

**Comment by zroubalik** [comment]
@yaronworldwide that would be great once you have a time :) just out of curiosity

**Comment by yaronworldwide** [comment]
@zroubali <https://github.com/zroubalik>k in order to deploy Keda in our
environment we are running Helm from Terraform thus implying
some of the parameters to be passed from terraform to Helm .
Moreover a dependency was created in order to ensure keda is first
installed then keda-scaledobject

resource "kubernetes_namespace" "keda" {
  count = "${var.enable_keda ? 1 : 0}"
  metadata {
    name = "keda"
  }
}

resource "helm_release" "keda" {
  count = "${var.enable_keda ? 1 : 0}"
  name = "keda"
  namespace = "${kubernetes_namespace.keda.metadata.0.name}"
  chart = "/xdr/terraform/tf/modules/xdr_pods/helm/keda"

}

resource "helm_release" "keda-scaledobject" {
  count = "${var.enable_keda ? 1 : 0}"
  depends_on = ["helm_release.keda"]
  name = "keda-scaledobject"
  namespace = "${kubernetes_namespace.keda.metadata.0.name}"
  chart = "/xdr/terraform/tf/modules/xdr_pods/helm/keda-scaledobject"

  set_string {
    name = "lcaasId"
    value = "${var.lcaas}"
  }
}

**Comment by zroubalik** [comment]
@yaronworldwide thanks! I think you should be able to attach the zip files directly to the comment on this issue. see: https://help.github.com/en/github/managing-your-work-on-github/file-attachments-on-issues-and-pull-requests

**Comment by yaronworldwide** [comment]
@zroubalik exactly what I have tried to do but it was stuck at uploading because of corporate firewall

[keda-scaledobject.zip](https://github.com/kedacore/keda/files/4165417/keda-scaledobject.zip)
[keda.zip](https://github.com/kedacore/keda/files/4165418/keda.zip)

Let me know if additional information is required

**Comment by zroubalik** [comment]
@yaronworldwide thanks!
