### ISSUE TITLE
Add support for a trigger based on a queue in an ActiveMQ Artemis cluster 

### ISSUE THREAD

**Issue by lavifb** [kedacore/keda#6106]
### Proposal

As detailed here: https://github.com/artemiscloud/activemq-artemis-operator/issues/892
The ActiveMQ Artemis management endpoint that KEDA uses works alright for 1 instance but fails for a cluster. The issue is that each artemis node only returns its local queue length (not the queue for the entire cluster). Unfortunately, they do not provide an endpoint for returning the queue length for the entire cluster.

Could we add a configuration where we provide multiple target hosts and the the queue lengths get aggregated together to get the total queue length?

### Use-Case

Allowing proper scaling based on ActiveMQ Artemis queues in a cluster configuration.

### Is this a feature you are interested in implementing yourself?

No

**Comment by rickbrouwer** [comment]
Is maybe [scaling modifiers](https://keda.sh/docs/2.15/concepts/scaling-deployments/#scaling-modifiers) what will work for you ?

**Comment by lavifb** [comment]
ah yeah, that looks like it would work
