### ISSUE TITLE
Invalid CRD for ScaledJobs when loading from release artifacts

### ISSUE THREAD

**Issue by builtroller** [kedacore/keda#6107]
### Report

When I try to load CRDs using the release artifacts, `scaledjobs.keda.sh` fails.

### Expected Behavior

`scaledjobs.keda.sh` CRD loads.

### Actual Behavior

CRD is not loaded because the `metadata.annotations` are too long.

```sh
$ kubectl apply -f https://github.com/kedacore/keda/releases/download/v2.15.1/keda-2.15.1-crds.yaml

customresourcedefinition.apiextensions.k8s.io/cloudeventsources.eventing.keda.sh created
customresourcedefinition.apiextensions.k8s.io/clustertriggerauthentications.keda.sh created
customresourcedefinition.apiextensions.k8s.io/scaledobjects.keda.sh created
customresourcedefinition.apiextensions.k8s.io/triggerauthentications.keda.sh created
The CustomResourceDefinition "scaledjobs.keda.sh" is invalid: metadata.annotations: Too long: must have at most 262144 bytes
```

### Steps to Reproduce the Problem

1. Run `kubectl apply` against the keda CRDs manifest from the release artifacts
```sh
kubectl apply -f https://github.com/kedacore/keda/releases/download/v2.15.1/keda-2.15.1-crds.yaml
```

### KEDA Version

2.15.1

### Kubernetes Version

1.28

### Platform

Amazon Web Services

**Comment by JorTurFer** [comment]
That issue is because you have to include `--server-side` because the CRD is too big. It's explained here: https://keda.sh/docs/2.15/deploy/#yaml
![image](https://github.com/user-attachments/assets/f09ce699-5473-4397-8afe-56f3ff1227aa)
