### ISSUE TITLE
Targeted Pod Removal During Scaling Down

### ISSUE THREAD

**Issue by milad2golnia** [kedacore/keda#6124]
### Proposal

I’m looking for a way to determine which pod to remove when scaling down. Assume we have three pods: A, B, and C. I want to scale down by specifically removing pod B. Does KEDA provide an option for this?

### Use-Case

This is highly useful in many scenarios. I think the [pod-deletion-cost issue](https://github.com/kedacore/keda/issues/3680) is related to this feature, and with it, we could handle pod-deletion-cost programmatically. It also seems that the [Scaling down logic discussion](https://github.com/kedacore/keda/discussions/3551) is requesting this feature, but the author forgot to submit a feature request.

In general, this is useful when we want to remove idle pods rather than a random pod.

### Is this a feature you are interested in implementing yourself?

No

**Comment by JorTurFer** [comment]
Hello,
Sadly KEDA doesn't provide any option to handle this as we rely on the HPA controller and it's the HPA controller the responsible of handling the scaling on k8s side
