### ISSUE TITLE
False Alarm @ v2.15.0

### ISSUE THREAD

**Issue by lsteinberg-r7** [kedacore/keda#6125]
### Report

In the scaled job description (for triggers redis / mongodb and probably more) I'm seeing this log - 

<img width="1645" alt="image" src="https://github.com/user-attachments/assets/6195a6c6-8847-4958-bfb2-fe5d73da3585">

Even though scaler is built and jobs are starting correctly.
My hunch is that it happens when more than one scaler is defined in the same deployment.
Probably not urgent but should be checked.

### Expected Behavior

No warnings in scaler description if it's built correctly.

### Actual Behavior

Warning logs are present.

### Steps to Reproduce the Problem

1. Try to define two redis scalers in same deployment
2. Deploy
3. Check scaler events (k9s > `:scaledjobs` > scaler description)

### Logs from KEDA operator

<img width="1645" alt="image" src="https://github.com/user-attachments/assets/0944fcd9-9182-4f54-879a-af3b5b506832">

### KEDA Version

2.15.0

### Kubernetes Version

1.28

### Platform

Google Cloud

### Scaler Details

Redis

**Comment by JorTurFer** [comment]
Hello
Could you share KEDA operator logs?

**Comment by lsteinberg-r7** [comment]
> Hello Could you share KEDA operator logs?

No valuable logs to share as far as I can see

**Comment by JorTurFer** [comment]
any idea @kedacore/keda-core-contributors ?

**Comment by zroubalik** [comment]
Thanks for reporting, we are aware of this problem. It is related to the caching problem, we discussed on the last community call, related to this:
https://github.com/kedacore/keda/issues/5926
https://github.com/kedacore/keda/issues/6176

In this specific usecase we KEDA was able to recover, you can ignore these warnings. We are working towards finding a proper solution.
