### ISSUE TITLE
KEDA Validation should prevent the creation of a ScaledObject with duplicate value for spec.advanced.horizontalPodAutoscalerConfig.name

### ISSUE THREAD

**Issue by asobti** [kedacore/keda#6130]
### Proposal

KEDA's validating admission webhook should prevent the creation of a ScaledObject if another ScaledObject already exists in the namespace with the same value for `spec.advanced.horizontalPodAutoscalerConfig.name`.

If more than 1 ScaledObject exists with the same value for `spec.advanced.horizontalPodAutoscalerConfig.name`, KEDA operator keeps updating the underlying HPA object continuously.

### Is this a feature you are interested in implementing yourself?

No

**Comment by zroubalik** [comment]
Reasonable idea
