### ISSUE TITLE
bad queue length strconv.ParseInt call

### ISSUE THREAD

**Issue by jonsmeep** [kedacore/keda#6178]
Current code reads:
`metricValue, err := strconv.ParseInt(output.Attributes[string(awsSqsQueueMetric)], 10, 32)`

that 32 ought to be a 64.

https://github.com/kedacore/keda/blob/4444aca424ce12a0e711da9ac106c2c8e829d0c9/pkg/scalers/aws_sqs_queue_scaler.go#L248

**Comment by JorTurFer** [comment]
Hello
Which is the issue with using int32 here? Are you using a number over int32 max value?
