### ISSUE TITLE
Keda Metrics not showing in Prometheus

### ISSUE THREAD

**Issue by wamak9** [kedacore/keda#6237]
### Report

We were trying to use the metrics listed here : https://keda.sh/docs/2.15/integrations/prometheus/
But none of them are available on Prometheus.

### Expected Behavior

once keda is installed, prometheus should be able to pick up the metrics from keda.
A mentioned here: https://keda.sh/docs/2.15/integrations/prometheus/

### Actual Behavior

When I look at the metrics being scrapped, I only see few metrics but nothing for `keda_scaler_`
<img width="700" alt="Screenshot 2024-09-11 at 5 21 43 PM" src="https://github.com/user-attachments/assets/c3c032ba-780d-4027-b6f7-750d36add59b">

<img width="928" alt="Screenshot 2024-09-11 at 5 33 03 PM" src="https://github.com/user-attachments/assets/5e78fd4f-cc9d-4d9d-9153-c1c71857c98c">

## Steps to Reproduce the Problem

  1. Install keda
``` 
helm --upgrade install keda kedacore/keda \
  --version 2.15.1 \
  --namespace keda \
  --set operator.replicaCount=2 \
  --set prometheus.metricServer.enabled=true \
  --set prometheus.webhooks.enabled=true \
  --set profiling.metricsServer.enabled=true \
  --timeout 5m

```

  2. Navigate to Prometheus (We are not using Prometheus Operator)
  3. Type in `Keda_`, it should be able to list the metrics with `keda_scaler`

Prometheus Version running `prometheus-v2.49.1`

### Logs from KEDA operator

```
example
```

### KEDA Version

2.15.1

### Kubernetes Version

1.28

### Platform

Microsoft Azure

### Scaler Details

Auto Scaler object for Pods on K8s

### Anything else?

Tried multiple versions of Prometheus enabled metrics flag.
Seems like I am still unable to see the metrics.

**Comment by SpiritZhou** [comment]
"It seems that Prometheus hasn't been enabled for the operator, which provides major metrics such as the scaledobject's metric。Try to add prometheus.operator.enabled = true
