### ISSUE TITLE
Introducing Scaling by Step in Advanced Settings

### ISSUE THREAD

**Issue by SpiritZhou** [kedacore/keda#6248]
### Proposal

Although there is a scaling modifier that can implement the scaling by step feature, it is still not very convenient for users. It would be more user-friendly to have a direct setting in the ScaledObject. Therefore, we propose introducing a new setting called "scalingSteps" in the advanced settings. 

```
advanced:
  scalingSteps:
     stepReplicaCount: 3
     nextStepInterval: 2
```

```
status:
  nextStepCountdown: 5
```

"stepReplicaCount" would represent the maximum replica count for each scaling step, and "nextStepInterval" would specify the number of “pollintervals” that must pass before scaling to the next step. The maxReplicaCount would be updated according to the increasing step value, and the nextStepCountdown status would also be introduced to calculate the number of steps.

### Is this a feature you are interested in implementing yourself?

Yes

**Comment by JorTurFer** [comment]
Currently we support configuring the HPA behaviour -> https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#configurable-scaling-behavior

This can be achieve configuring the `advanced. horizontalPodAutoscalerConfig ` section of the ScaledObject to pass the values to the underlaying HPA -> https://keda.sh/docs/2.15/reference/scaledobject-spec/#horizontalpodautoscalerconfig

Could this be enough?
