### ISSUE TITLE
issues with graphite trigger

### ISSUE THREAD

**Issue by mahmed15-09** [kedacore/keda#6319]
### Report

Hi i have started using keda with graphite server to scale up our cicd system. i see that the values we get from graphite are not correct.

i get the following values via graphite:

[
  {
    "target": "starting builds",
    "tags": {
      "name": "sumSeries(stats.gauges.zuul.executor.*.starting_builds)",
      "aggregatedBy": "sum"
    },
    "datapoints": [
      [14, 1730991300],
      [11, 1730991360],
      [18, 1730991420],
      [39, 1730991480],
      [9, 1730991540]
    ]
  }
]

and In K8s HPA i get the following result:

Metrics:                                 ( current / target )
  "s3-graphite" (target average value):  1389m / 2
  
1389 actually means 0.1389.  
I don't see such value any where in the graph as well.   

I am using the same query in keda that i used to curl the datapoints above. 

### Expected Behavior

Metrics:                                 ( current / target )
  "s3-graphite" (target average value):  1389m / 2
  
I expected the above 1389m value to be 13890m or maybe some value near the above data points

### Actual Behavior

Actual Behavior:
Metrics:                                 ( current / target )
  "s3-graphite" (target average value):  1389m / 2

### Steps to Reproduce the Problem

1.Its basically the same for any graphite usecase. The value is wrong
2.
3.

### Logs from KEDA operator

```
example
```

### KEDA Version

2.13.1

### Kubernetes Version

1.29

### Platform

None

### Scaler Details

Graphite

### Anything else?

I am using keda chart version 2.13.2 which was not specified in the above list

**Comment by JorTurFer** [comment]
Hello
`1389m` means `1.389`. This can be totally normal as the default metric type is average so the value that you see in the HPA is the result of calculating the average. 
In this case, `1389m` could be shown because you have 25 in your graphite scaler and there are 18 instances (25/18=1389m).

**Comment by mahmed15-09** [comment]
I understand . I have verified that this is indeed the case.
