### ISSUE TITLE
Missing metric keda_scaled_object_paused after keda-operator restart

### ISSUE THREAD

**Issue by aguerra** [kedacore/keda#6321]
### Report

Keda-operator reports the metric keda_scaled_object_paused as 1 for a paused scaled object. After restarting or replacing the keda-operator pod the metric is missing.

### Expected Behavior

The reconciliation should be able to detect the paused scaled object and set the corresponding metric  keda_scaled_object_paused to 1.

### Actual Behavior

The metric keda_scaled_object_paused is missing.

### Steps to Reproduce the Problem

1. Pause a scaled object and confirm that the metric keda_scaled_object_paused{scaledObject="my-scaled-object"}  is present and equals 1.
2. Restart or replace the keda-operator pod.
3. The metric keda_scaled_object_paused{scaledObject="my-scaled-object"} is missing.

### Logs from KEDA operator

```
example
```

### KEDA Version

2.15.1

### Kubernetes Version

1.30

### Platform

Amazon Web Services

### Scaler Details

CPU

**Comment by JorTurFer** [comment]
Thanks for reporting! I've reproduced the issue and the PR with the fix is already opened 😄
