### ISSUE TITLE
NATS JetStream TLS Authentication Support

### ISSUE THREAD

**Issue by giedriusl** [kedacore/keda#6347]
### Proposal

TLS authentication support was introduced in the NATS Streaming scaler with issue [2296](https://github.com/kedacore/keda/issues/2296). According to the [documentation of NATS Jetstream scaler](https://keda.sh/docs/2.16/scalers/nats-jetstream/), no parameters support TLS authentication.

### Is this a feature you are interested in implementing yourself?

Maybe

**Comment by edwin-Marrima** [comment]
Hi @JorTurFer, I'd like to work on this one

**Comment by JorTurFer** [comment]
Hello,
The support for TLS authentication was added to NATS Streaming (STAN) and not to NATS JetStream. They are different scalers, but let's take this issue as a feature request to support TLS auth also for JetStream.

Are you willing to add the support @edwin-Marrima ?

**Comment by edwin-Marrima** [comment]
Yes, sure @JorTurFer

**Comment by edwin-Marrima** [comment]
Hi @JorTurFer 
Both NATS JetStream and NATS stream scalers interact with the NATS monitoring endpoint. According to NATS documentation, they do not support any form of authentication or authorization

> nats-server does not have authentication/authorization for the monitoring endpoint. When you plan to open your nats-server to the internet make sure to not expose the monitoring port as well. By default, monitoring binds to every interface 0.0.0.0 so consider setting monitoring to localhost or have appropriate firewall rules.

**Comment by JorTurFer** [comment]
Nice research! I think that we can close this issue now. thanks 🙇

**Comment by dockercaptain** [comment]
but we dont auth for monitoring. what we want is simple token based login setup for keda, and it's not working.
