### ISSUE TITLE
Unable to scale azure function using KEDA on azure kubernetes cluster

### ISSUE THREAD

**Issue by Priyam1464** [kedacore/keda#635]
I am following this link https://dev.to/anirudhgarg_99/scale-up-and-down-a-http-triggered-function-app-in-kubernetes-using-keda-4m42 to  scale http triggered azure function using keda and prometheus. The azure function is not scaling at all. When I am running the command   kubectl -n ingress-nginx describe horizontalpodautoscaler.autoscaling/keda-hpa-function-senderten-http to describe the hpa then

## Expected Behavior
Scaling active should come out true

## Actual Behavior
Scaling active comes false and the error is unable to get external metric access frequency/ingress-nginx.

## Steps to Reproduce the Problem
Run the command
  1.kubectl -n ingress-nginx describe horizontalpodautoscaler.autoscaling/keda-hpa-function-senderten-http 
 
![hpaerror](https://user-images.githubusercontent.com/20543398/74758323-3160ec00-529d-11ea-9a1e-e14c19c805ca.PNG)

**Comment by tomkerkhove** [comment]
Hi, thanks for the report.

Can you provide the system information from the template please?

> - **KEDA Version:** *Please elaborate*
>   - **Platform & Version:** *Please elaborate*
>   - **Kubernetes Version:** *Please elaborate*
>   - **Scaler(s):** *Please elaborate*

Also, how did you install your function? We've had an issue recently (https://github.com/kedacore/keda/issues/628) due to Azure Function tooling and logged https://github.com/Azure/azure-functions-core-tools/issues/1822 for it.

**Comment by ahmelsayed** [comment]
Closing this issue as it's most likely an azure functions tooling issue. /cc @SatishRanjan
