### ISSUE TITLE
`InitialCooldownPeriod` should be `*int32` not `int32`

### ISSUE THREAD

**Issue by zroubalik** [kedacore/keda#6423]
### Report

`InitialCooldownPeriod` introduced in https://github.com/kedacore/keda/pull/5478 should be pointer, to be aligned with the `cooldownPeriod` paramter. Also this field is marked as `optional` thus another point for pointers.

Another problem with #5478 is that `zz_generated.deepcopy.go` been regerenerated with this PR, so `InitialCooldownPeriod` is completely missing there: https://github.com/kedacore/keda/blob/27c99dc20a18f85295ef2b32f33534d7545cdd33/apis/keda/v1alpha1/zz_generated.deepcopy.go#L916-L965 hasn't 

### Expected Behavior

`InitialCooldownPeriod` should be `*int32`

### Actual Behavior

`InitialCooldownPeriod`is `int32`

### Steps to Reproduce the Problem

1. consume API

### KEDA Version

2.14.0

### Kubernetes Version

None

### Platform

None

**Comment by black-snow** [comment]
This is listed as a "breaking" change in the [2.17.0](https://github.com/kedacore/keda/releases/tag/v2.17.0) release - how is it breaking and what to do about it?

This doesn't seem to be a breaking change for an "end user", is it?

**Comment by jflambert** [comment]
> This is listed as a "breaking" change in the [2.17.0](https://github.com/kedacore/keda/releases/tag/v2.17.0) release - how is it breaking and what to do about it?
> 
> This doesn't seem to be a breaking change for an "end user", is it?

Would have been really awesome to have an answer to this question by now. @JorTurFer any comments?

**Comment by JorTurFer** [comment]
I guess that from KEDA user pov it's not
