### ISSUE TITLE
Extend Redis scaler to scale on age of oldest message in a queue

### ISSUE THREAD

**Issue by turbaszek** [kedacore/keda#647]
A clear and concise description of what scaler you'd like to use and how you'd want to use it:

  - **Scaler Source:**
Redis queue.
  - **How do you want to scale:**
Users can configure the scaler to scale up when the age of the oldest message in a queue exceeds a threshold defined in seconds. In other words, this scaler should assure that queued-to-execute time is below some value (until we reach max no. of pods).
  - **Authentication:**
Same as now.

**Comment by nuclearpinguin** [comment]
I am happy to work on it. Any thoughts @tomkerkhove @dimberman ?

**Comment by tomkerkhove** [comment]
Maybe good to add this to the standup agenda first to discuss?

For example, will this always be the case or is the configuration option for that field optional?

**Comment by jeffhollan** [comment]
I think this makes sense.  @nuclearpinguin we can discuss in our community call in a few minutes but the one thing I'd be interested in is how the `ScaledObject` looks in this mode, and how a someone opts-into this behavior rather than the current "queue size" one.  But I like the idea.

**Comment by nuclearpinguin** [comment]
@jeffhollan sorry I couldn't join the call this week. My general idea was to have one RedisScaler where user can define one of the two targets:
- queue length (already implemented)
- max message age

Both should be mutually exclusive thus a good note docs is a must.

**Comment by turbaszek** [comment]
Unfortunately it seems that both Redis and RabbitMQ don’t have information on the age of a message. Without that it will be hard to implement this scaler in universal and reliable way.
