### ISSUE TITLE
Provide artwork for KEDA logo in PNG & SVG

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda#650]
Provide artwork for KEDA logo in PNG & SVG as we'll need this for https://github.com/cncf/artwork once https://github.com/cncf/toc/issues/335 gets merged.

**Comment by jeffhollan** [comment]
Do we need assets we don't already have in the repo?

**Comment by tomkerkhove** [comment]
Ideally we have SVG as well

**Comment by jeffhollan** [comment]
I see. I'm pretty sure we have one I just didn't upload it.  Let me check

**Comment by tomkerkhove** [comment]
That would be great but it's not urgent!

**Comment by tomkerkhove** [comment]
@sjwaight any update on the logo with lightning bolt?

(follow-up of #665)

**Comment by sjwaight** [comment]
Having some challenges with production because the logo artwork we have doesn't have the circle with dots. Please let me know if this is a blocker for anything so I can prioritise.

**Comment by tomkerkhove** [comment]
You can find the artwork with the circle and docs on https://github.com/cncf/artwork/tree/master/projects/keda/icon

But no worries, this is not urgent!

**Comment by tomkerkhove** [comment]
Let me know if we can help you out and if you need anything else @sjwaight!

Just checking in, no pressure here!

**Comment by sjwaight** [comment]
Our resident designer has been on leave for a few weeks so there hasn't been any movement on this - I have followed up here and will do so again. Taking a while but still not closed off. Thanks for the reminder :)

**Comment by tomkerkhove** [comment]
We are working on design for our merch (#997) and will see if we can squeeze it in in time.

Thanks for the update!
