### ISSUE TITLE
keda-metrics-apiserver should restart/error when it receives HTTP 403 responses

### ISSUE THREAD

**Issue by lenardchristopher** [kedacore/keda#654]
## Expected Behavior
If the keda-metrics-apiserver receives a HTTP 403 status, it restarts or the Pod shows a status that alerts administrators that something is wrong.

## Actual Behavior
keda-metrics-apiserver keeps running and only shows 403 responses in logs.

## Steps to Reproduce the Problem

  1. Install Keda on a cluster without RBAC enabled or restrict RBAC policies to force 403 errors.
  2. Look at keda-metrics-apiserver logs and see 403 errors.
  3. Observe the keda-metrics-apiserver running with no restarts or abnormal pod status

## Specifications

  - **KEDA Version:** 1.2
  - **Platform & Version:** Azure Linux
  - **Kubernetes Version:** 1.14.8
  - **Scaler(s):** Azure Event Hub

**Comment by vineetsharma883** [comment]
hey is this solved ?
