### ISSUE TITLE
Prometheus scaler throws an error when a query returns empty

### ISSUE THREAD

**Issue by jeffhollan** [kedacore/keda#657]
When using prometheus to do something like scale an HTTP workload, if the requests are `nil` for that period of time the scaler throws an error every time it polls:

> {"level":"error","ts":1583710650.0702486,"logger":"prometheus_scaler","msg":"error executing prometheus query","error":"Prometheus query sum(rate(nginx_ingress_controller_requests{service=\"java-azure-function-http\"}[5s])) returned empty","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\ngithub.com/kedacore/keda/pkg/scalers.(*prometheusScaler).IsActive\n\tkeda/pkg/scalers/prometheus.go:101\ngithub.com/kedacore/keda/pkg/handler.(*ScaleHandler).handleScaleDeployment\n\tkeda/pkg/handler/scale_loop.go:119\ngithub.com/kedacore/keda/pkg/handler.(*ScaleHandler).handleScale\n\tkeda/pkg/handler/scale_loop.go:45\ngithub.com/kedacore/keda/pkg/handler.(*ScaleHandler).HandleScaleLoop\n\tkeda/pkg/handler/scale_loop.go:28"}

Would be good to have the scaler handle an `empty` query as a `0`

**Comment by droessmj** [comment]
are you just looking for this line to be a `0,nil` return instead of it's current case or is there a complexity I'm missing? 

https://github.com/kedacore/keda/blob/3692eca90897a5b5a226fbfe2f0ca72fab2be6ff/pkg/scalers/prometheus.go#L149
