### ISSUE TITLE
Move to Apache v2.0 License

### ISSUE THREAD

**Issue by caniszczyk** [kedacore/keda#658]
Since KEDA is becoming a CNCF Sandbox project, it will have to adhere to the CNCF IP Policy:
https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy

Apache v2.0 License + DCO is the easiest and lowest path forward imho.

**Comment by tomkerkhove** [comment]
License has been changed, feel free to do a sanity check @caniszczyk.

Once approved, I'll make same changes to other repos in our org (other than samples, if ok)

**Comment by caniszczyk** [comment]
LGTM thanks, please enforce across all other repos

**Comment by tomkerkhove** [comment]
I'll reopen it to keep track of it!

**Comment by nuclearpinguin** [comment]
@tomkerkhove maybe we should add a pre-commit check to assert licenses are present? That's what we do in Airflow. It's always good to automate boring stuff :)

**Comment by zroubalik** [comment]
@nuclearpinguin the pre-commit check is supposed to check that the licence is not removed in that particullar commit? Or what is the specific usecase?

**Comment by nuclearpinguin** [comment]
@zroubalik it checks if license is present, if not it adds the missing license. In the end, the developer doesn't have to care about the license as long as the pre-commit is installed :)

**Comment by zroubalik** [comment]
@nuclearpinguin gotcha! PR is a great idea

**Comment by tomkerkhove** [comment]
You are more talking about license mentioned in all source code files rather than the repo license itself, right?

@caniszczyk Do we have to add licenses to all source code files? If not, I'd say we are good without to reduce the "noise".

**Comment by nuclearpinguin** [comment]
> You are more talking about license mentioned in all source code files rather than the repo license itself, right?

Yup (edit in my last comment). I do not know if CNCF requires them. If not, no need for such automation.

**Comment by caniszczyk** [comment]
https://github.com/cncf/foundation/blob/master/copyright-notices.md

**Comment by tomkerkhove** [comment]
Based on that I think we are good with only DCO & our updated license.

Closing.
