### ISSUE TITLE
Update README to mention CNCF + remove partnership references

### ISSUE THREAD

**Issue by caniszczyk** [kedacore/keda#678]
We should update the website + README to ensure it complies with:
https://github.com/cncf/foundation/blob/master/website-guidelines.md

**Comment by tomkerkhove** [comment]
PTAL @caniszczyk

**Comment by caniszczyk** [comment]
@tomkerkhove LGTM, you may want to link to devstats now: https://keda.devstats.cncf.io/

Also I'd list the logos in alphabetical order, other than that LGTM
