### ISSUE TITLE
the version of operator-sdk  is wrong in go.sum

### ISSUE THREAD

**Issue by iyacontrol** [kedacore/keda#681]
github.com/operator-framework/operator-sdk v0.0.0-00010101000000-000000000000

so if i import keda in my promgram, go mod can not find operator-sdk.

**Comment by zroubalik** [comment]
Could you please be more specific? Are you trying to build keda locally? There is [replace](https://github.com/kedacore/keda/blob/3692eca90897a5b5a226fbfe2f0ca72fab2be6ff/go.mod#L35) with the specific version in go.mod.

**Comment by iyacontrol** [comment]
not build keda loally, i create kedav1alpha1.ScaledObject in my program with code

**Comment by zroubalik** [comment]
@iyacontrol do you still hit this issue?

**Comment by iyacontrol** [comment]
@zroubalik yes. i still hit this issue,

**Comment by zroubalik** [comment]
I will need to know more details in order to help you or you can send a PR with a fix that helped you.

**Comment by iyacontrol** [comment]
@zroubalik  this issue  can close, i work well now.

**Comment by RiRa12621** [comment]
Would be nice to share how you solved your issue though @iyacontrol
