### ISSUE TITLE
Remove Microsoft CLA and bot

### ISSUE THREAD

**Issue by zroubalik** [kedacore/keda#685]
I think that we should remove the [section](https://github.com/kedacore/keda#contributing) on Microsoft CLA and the bot validating PRs.

Same section is here as well: https://github.com/kedacore/keda/blob/master/CONTRIBUTING.md

**Comment by caniszczyk** [comment]
+1 we should also install the DCO bot https://probot.github.io/apps/dco/

**Comment by caniszczyk** [comment]
this should be done ASAP and along with dropping the MS CLA

**Comment by caniszczyk** [comment]
I installed it now, feel free to tweak but it should be part of every repo: https://github.com/organizations/kedacore/settings/installations/7359869

**Comment by zroubalik** [comment]
@caniszczyk thanks, seems like I don't have enough permissions to see the link and tweak the setttings.

**Comment by zroubalik** [comment]
Same section is in here as well:
https://github.com/kedacore/keda/blob/master/CONTRIBUTING.md

@caniszczyk is there any recommendation on Contributing from CNCF side? Anything that we can put in that section to comply with CNCF standarts.

**Comment by tomkerkhove** [comment]
Paging @jeffhollan since I can't do this as well!

**Comment by caniszczyk** [comment]
for CONTRIBUTING.md examples, you can see a fancy one from Envoy https://github.com/envoyproxy/envoy/blob/master/CONTRIBUTING.md

**Comment by tomkerkhove** [comment]
Ok if I assign this one to you @zroubalik as it looks like you'll pickup the contributing file?

I'll include @jeffhollan for the DCO app as well.

**Comment by tomkerkhove** [comment]
Re-opening until app is installed

**Comment by zroubalik** [comment]
@tomkerkhove if I am not mistaken, DCO app is already installed, but we need to remove the microsoft cla bot.

**Comment by tomkerkhove** [comment]
@zroubalik is it installed on all repos?

We'll need @jeffhollan to remove the Microsoft CLA bot as I'm nto an owner

**Comment by caniszczyk** [comment]
DCO is installed on all repos

**Comment by flecno** [comment]
I have contributed the first time today and it was really easy and  straightforward to use DCO. I think it is a really nice integration! :+1:

**Comment by jeffhollan** [comment]
Made request to open at microsoft to remove the CLA bot. Should be done within 24 hours. If it takes too long I can always just remove access from the org, but suspect should go through w/out issue

**Comment by tomkerkhove** [comment]
It's still here (at least on docs), how do we remove it @jeffhollan ?

**Comment by jeffhollan** [comment]
I just found the confirmation from a few weeks ago that it has been removed from the org. Is it still popping in? Or do we just see it still has permissions? I'll just remove it from the org so should solve all

**Comment by jeffhollan** [comment]
Ok, the deed is done. The CLA bot should be completely gone

**Comment by tomkerkhove** [comment]
Great, thanks! Will re-open if it shows back up!
