### ISSUE TITLE
autoscale based on multiple kafka topics

### ISSUE THREAD

**Issue by AmithGanesh** [kedacore/keda#687]
Do we have a way to autoscale a single deployment based on multiple kafka topics?

**Comment by tomkerkhove** [comment]
I think this relates to #476

**Comment by tomkerkhove** [comment]
But for now, I think your best bet is to create multiple scaled objects

**Comment by AmithGanesh** [comment]
Even if we have multiple scaled objects, if lag is present on one topic and not on the other topic, how will it affect the deployment as its trying to autoscale the same deployment.

**Comment by tomkerkhove** [comment]
It depends what your scaling scenario is - If it's an AND then you cannot do this today, I think. If it's an OR approach, multiple triggers will help you

**Comment by AmithGanesh** [comment]
Cool. thanks!

**Comment by tomkerkhove** [comment]
My pleasure!
