### ISSUE TITLE
Azure Managed Identity support

### ISSUE THREAD

**Issue by droessmj** [kedacore/keda#697]
### Use-Case

Instead of storing connection strings as secrets in Kubernetes, leverage AAD Pod Identity to connect to Azure hosted resources (Service Bus, Event Hub, etc.). 

I realize that this is a solution for a specific provider instead of being provider agnostic. Perhaps it could be an add-on of sorts? 

This feature would put my particular organization over a significant hurdle, as we're avoiding static connectionstrings wherever possible in favor of Managed Identities and RBAC permissions. Historically, we've been terrible at rotating static keys on any recurring basis.

**Comment by tomkerkhove** [comment]
We already support Managed Identity, see https://keda.sh/concepts/authentication/#azure-pod-identity

Does that help you further?

**Comment by droessmj** [comment]
Thanks for the quick reply, Tom. That helps!
