### ISSUE TITLE
apiextensions.k8s.io/v1beta1 deprecation in 1.16

### ISSUE THREAD

**Issue by alegmal** [kedacore/keda#701]
Currently KEDA uses apiextensions.k8s.io/v1beta1 in CustomResourceDefinition.

apiextensions.k8s.io/v1beta1 is going to be deprecated in favor of apiextensions.k8s.io/v1 in 1.16 according to this resource:
https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/

we are planing to migrate and wanted to check if support for v1 is planned.

**Comment by tomkerkhove** [comment]
We should certainly move to `apiextensions.k8s.io/v1` but that will most probably be for 2.0.

Thoughts @ahmelsayed @zroubalik?

**Comment by tomkerkhove** [comment]
Which version *removes* `apiextensions.k8s.io/v1beta1` @Cerberussian, do you know?

For now it's deprecated but it's still around so we have time (which doesn't mean we should wait) but just to know how soon it will go away, 3 versions?

**Comment by zroubalik** [comment]
If `apiextensions.k8s.io/v1beta1` is going to be present in a next few releases, we don't need to rush and could keep this for 2.0, to be consistent.

If we change it to `v1` now, we will drop support on kubernetes < 1.16.0, we can currently run KEDA on > 1.13, so it could affect users with older versions.

**Comment by tomkerkhove** [comment]
Agreed, v2.0 sounds good to me

**Comment by zroubalik** [comment]
As discussed on https://github.com/kedacore/keda/issues/1160, I think that we can safely require k8s v1.16+ for KEDA. That means that we can move to `apiextensions.k8s.io/v1`.

Any objections?

**Comment by tomkerkhove** [comment]
Looks like that was released only on September 18, 2019; but makes sense to me. Maybe we can discuss tomorrow in standup?
