### ISSUE TITLE
Consolidate `apiHost` & `host` for RabbitMQ scaler

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda#711]
Consolidate `apiHost` & `host` for RabbitMQ scaler.

Seperation was introduced via #700

**Comment by turbaszek** [comment]
Do I correctly understand that providing `host` means that the scaler will use AMQP protocol and providing `apiHost` means using HTTP? If that's true should we consolidate those two params into a single `host` argument and add `protocol` param?

**Comment by tomkerkhove** [comment]
Yes, that's the goal indeed so that it provides a more consistent experience. Are you willing to contribute this?

**Comment by turbaszek** [comment]
I can take a look at this one as it would be wise to do this before 2.0. Are we ok with making this a breaking change?

**Comment by zroubalik** [comment]
That's great, a breaking change is fine for me. (before 2.0 of course 😄)

**Comment by tomkerkhove** [comment]
Re-opening for docs

**Comment by turbaszek** [comment]
@tomkerkhove should we close it as https://github.com/kedacore/keda-docs/pull/253 was merged?

**Comment by tomkerkhove** [comment]
Yes, sorry!
