### ISSUE TITLE
HPA: move from autoscaling v2beta1 to v2beta2

### ISSUE THREAD

**Issue by zroubalik** [kedacore/keda#721]
We are using `v2beta1` for our HPAs and scaling, we should consider moving to `v2beta2`. It shouldn't be a big change and cause any negative impact on KEDA functionality. 

There are minor changes in the newer version of k8s autoscaling api, so we need to change our code appropriately.

https://stupefied-goodall-e282f7.netlify.com/contributors/design-proposals/autoscaling/hpa-v2/

**Comment by tomkerkhove** [comment]
Sounds good to me!

**Comment by ahmelsayed** [comment]
merged to v2 branch
