### ISSUE TITLE
Consideration for Maintainership for Daniel Imberman

### ISSUE THREAD

**Issue by dimberman** [kedacore/keda#724]
Hello KEDA community!

Since joining this project, I've become really passionate about seeing KEDA become the de-facto autoscaler for all k8s services. If there is interest, I would love to be considered for a maintainership so I can help merge PRs, promote KEDA to the community, and just generally help any way I can :).

Thank you for your consideration!

**Comment by tomkerkhove** [comment]
Thanks @dimberman! Jeff will PR an update to our governance to list onboarding new members as we are checking what that would look like and what the max number of maintainers is that we want.

Stay tuned!

**Comment by dimberman** [comment]
Thank you Tom!

**Comment by tomkerkhove** [comment]
Just dropping a note that we have not forgotten about this but just a bit delayed due to current world scenario.

Will keep you posted and sorry for the delay!

**Comment by dimberman** [comment]
No worries at all :). It's a crazy time

**Comment by turbaszek** [comment]
@tomkerkhove any update? I'm also considering volunteering to be a maintainer so just checking 😄

**Comment by tomkerkhove** [comment]
I'll post an update this week!

**Comment by tomkerkhove** [comment]
Feel free to open a dedicated issue for you if you are interested @turbaszek to follow the process.

**Comment by tomkerkhove** [comment]
_First things first, sorry for the delay!_

Around April, @jeffhollan reached out to Daniel to let him know we are currently not planning on increasing our amount of maintainers but if there are long-term contributions we might consider changing our current maintainers board.

Given we haven't seen any contributions lately we will close this but feel free to re-open if you want to be reconsidered.
