### ISSUE TITLE
keda operator does not find my connection string

### ISSUE THREAD

**Issue by lgmorand** [kedacore/keda#729]
I'm using KEDA with a servicebus with a minimal setup, but when I push a scaleobject, the operator tells me that connection string is missing. So no HPA is created and of course no scaling. I really don't know what I'm missing

> {"level":"error","ts":1585898856.2814944,"logger":"controller-runtime.controller","msg":"Reconciler error","controller":"scaledobject-controller","request":"keda/azure-servicebus-queue-scaledobject","error":"error getting scaler for trigger #0: error parsing azure service bus metadata: no connection setting given",

I tried different format, with or without the entityPath and I don't understand Go very well but I should only get the error message if the connectionstring is empty...which is not

> apiVersion: keda.k8s.io/v1alpha1
> kind: ScaledObject
> metadata:
>   name: azure-servicebus-queue-scaledobject
>   labels:
>     deploymentName: my-deploy
> spec:
>   scaleTargetRef:
>     deploymentName: my-deploy
>   pollingInterval: 5
>   minReplicaCount: 2   
>   maxReplicaCount: 10  
>   triggers:
>   - type: azure-servicebus
>     metadata:
>       queueName: keda
>       connection: Endpoint=sb://test-keda.servicebus.windows.net/;SharedAccessKeyName=reader;SharedAccessKey=BLABLABLA;EntityPath=keda
>       queueLength: "5"

Any idea of what I am missing ? Thanks

**Comment by tomkerkhove** [comment]
AFAIK you cannot pass a raw connection string and have to point to a secret or environment value.

**Comment by tomkerkhove** [comment]
In your scenario I'd recommend using TriggerAuthentication with a secret, for example: https://github.com/kedacore/sample-dotnet-worker-servicebus-queue/blob/master/deploy/deploy-autoscaling.yaml

Unless you already have the information on the container and it has the same permissions, but I tend to seperate that responsibility.

**Comment by lgmorand** [comment]
I understand !!! but seriously, that's not obvious in the documentation
https://keda.sh/docs/scalers/azure-service-bus/

> Authentication Parameters

You can authenticate by using pod identity or connection string authentication.

> Connection String Authentication:
>     connection - Connection string for Azure Service Bus Namespace
