### ISSUE TITLE
Provide installation YAML in the release

### ISSUE THREAD

**Issue by ppatierno** [kedacore/keda#739]
There are different ways to install KEDA and using the YAML files is one of them.
The only problem with this way is the need for cloning the entire repo in order to have the `deploy` folder. I suggest building a zip/tar.gz file with the content of the `deploy` folder as part of the release process. In this way, when a new release is created on GitHub, it's possible to attach such a file providing to the user the YAML files with the release directly.
What do you think? Is it something you could be interested in?

**Comment by ppatierno** [comment]
I provided #740 as suggestion.

**Comment by tomkerkhove** [comment]
So the benefit is that you can download a ZIP rather than having to clone the repo, is that what you want to do?

**Comment by ppatierno** [comment]
Yes exactly. I think that for people who wants to just install and use KEDA but not developing it, it's useless cloning the entire repo of they want to use YAMLs and not Helm. We find it pretty useful for more people on the Strimzi project as well.

**Comment by tomkerkhove** [comment]
I didn't know a lot of folks were still doing kubectl deployments but sounds reasonable

**Comment by ppatierno** [comment]
Well I can say that from my Strimzi experience but I don't know if it's the same for KEDA.

**Comment by ppatierno** [comment]
@tomkerkhove Anyway, in order to use the Helm way you have to know about Helm. If you want to use the Operator Hub way you have to have OpenShift with Operator Hub or installing the OLM by yourself. The faster way to start is using YAMLs which needs zero overhead and knowledge but cloning the repo is not the better way. This is the rationale behind this proposal.

**Comment by zroubalik** [comment]
@ppatierno good idea, I agree with this. thank!

**Comment by tomkerkhove** [comment]
This is done.
