### ISSUE TITLE
KEDA 1.4.0 release is missing zip and tar.gz files

### ISSUE THREAD

**Issue by ppatierno** [kedacore/keda#760]
As per #739 , now when you build a new release, a zip and tar.gz files are created with all the needed YAMLs which can be used for installation without forcing people to use Helm, OLM or cloning the entire repo. 
These files should be uploaded in the "Assets" section of the release and they are missing in the latest 1.4.0 release.
After this, we can also merge the related documentation PR https://github.com/kedacore/keda-docs/pull/143

**Comment by ppatierno** [comment]
@SatishRanjan I see that you did the release, maybe you can upload this files? or @tomkerkhove @zroubalik ? Thanks!

**Comment by tomkerkhove** [comment]
I'm looking those up but can't find them as output of the release (sorry for my ignorance).

Can you point me out where they should be so that I can upload them please?

**Comment by ppatierno** [comment]
When you do a make release you should find them in the root of the repo at the end of the make.

**Comment by tomkerkhove** [comment]
I'll see if I can get it to work somewhere in next few days but should try to automate this more.

**Comment by tomkerkhove** [comment]
Will add https://github.com/actions/upload-release-asset to our release flow.

**Comment by ppatierno** [comment]
I don't think it's possibile to automate files upload to a github release.

**Comment by tomkerkhove** [comment]
Everything is possible. That GitHub action does it for example.

Will send a PR later next week.

**Comment by ppatierno** [comment]
That's cool, never used it!

**Comment by ppatierno** [comment]
when you do it, remember to merge https://github.com/kedacore/keda-docs/pull/143 thanks!

**Comment by marchmallow** [comment]
Regarding artifact upload it can also be easily done with Travis for example https://docs.travis-ci.com/user/deployment/releases/

**Comment by tomkerkhove** [comment]
Let's be pragmatic - @ppatierno can you download v1.4 release source code and generate the files and upload them here, I will attach them then.

I'm new to Make and don't want to be the blocker.

**Comment by ppatierno** [comment]
Here they are! 
[keda-1.4.0.tar.gz](https://github.com/kedacore/keda/files/4499102/keda-1.4.0.tar.gz)
[keda-1.4.0.zip](https://github.com/kedacore/keda/files/4499103/keda-1.4.0.zip)

**Comment by tomkerkhove** [comment]
Uploaded.

**Comment by ppatierno** [comment]
@tomkerkhove I see you renamed them in `kafka-deployment-$VERSION` which is not the actual name that the Makefile generates; it's just `kafka-$VERSION` so exactly the files names I uploaded in this issue. I am fine to have `deployment` in the name if you like it, but tbh I don't think it's necessary. Btw if you want it I could open a PR for changing the Makefile in order to generate the packages with the names you are using. What do you prefer?

**Comment by tomkerkhove** [comment]
I'll change it as part of the automation.

Reason why it's renamed is because people who haven't read that doc page will expect KEDA source, not deployment YAMLs :)

**Comment by ppatierno** [comment]
But source code packages are actually name "Souce code" in the assets.
Is it really need adding the renaming to the automation? Imho it's simpler just generating the final name as part of the "making" process and the automation has just to upload the files.
Changing "stuff/names" on fly during automation could drive just to not understand better the flow sometimes.

**Comment by ppatierno** [comment]
@tomkerkhove it's just a matter of changing here 
https://github.com/kedacore/keda/blob/master/Makefile#L77
a PR for this should take something like 5 minutes? :-)

**Comment by tomkerkhove** [comment]
I was going to do both improvements in one PR but if you can't wait be my guest, but don't think there is a rush :)



> But source code packages are actually name "Souce code" in the assets.

Sure but `keda-v1.4` is still to vague; certainly if you're not a GitHub expert.

**Comment by zroubalik** [comment]
I agree with @ppatierno, I'd name it `keda-$VERSION`, because this files will install you KEDA.

**Comment by tomkerkhove** [comment]
Updated.
