### ISSUE TITLE
RabbitMQ HTTP API - Unable to provide default VHost value

### ISSUE THREAD

**Issue by quoimec** [kedacore/keda#768]
When setting up RabbitMQ, the default name that is created for a VHost is / (very weird I know). Normally, to use the HTTP API with this VHost, you can provide an encoded slash like %2f which allows you to access the VHost specific parts of the API. The changes introduced in [Issue 700](https://github.com/kedacore/keda/pull/700) that allowed access to the HTTP API over AMPQ, work when a named VHost is provided but when using either a /, %2f or nothing to represent the default VHost, the scaled object will not work and will be stuck at 0.

I don't know a lick of Go but I've dug through the code and I think some part of the URL parser that is being employed is stripping out the / value as the name of the VHost. 

## Expected Behavior
To be able to pass the default VHost name and have the deployment scale up and down.

## Actual Behavior
The deployment immediately scales down to 0 and is unable to poll the API correctly.

## Steps to Reproduce the Problem

  1. Provide an apiHost value of http://un:pw@host:port/, http://un:pw@host:port/%2f or http://un:pw@host:port//

**Comment by tomkerkhove** [comment]
This shoulds like a regression bug, right?

We'll have a look at this, sorry about that!

**Comment by zroubalik** [comment]
@holyketzer do you think you could take a look on this?

**Comment by holyketzer** [comment]
ok

**Comment by holyketzer** [comment]
Hey guys, yes it didn't support empty vhost. 
I opened a PR with a fix. I tested it in our environment. Now it support all kinds of empty vhosts like: 

- http://un:pw@host:port/
- http://un:pw@host:port/%2f 
- http://un:pw@host:port//
