### ISSUE TITLE
Implement ScaledJob functionality for v2

### ISSUE THREAD

**Issue by zroubalik** [kedacore/keda#789]
Implement ScaledJob fucntionality for v2 as was discussed in https://github.com/kedacore/keda/issues/653

We should take into account requirements specific for scaling a Job and design `ScaledJob` CRD appropriately.

**TODO**
- Currently there's only a [stub](https://github.com/kedacore/keda/blob/v2/pkg/apis/keda/v1alpha1/scaledjob_types.go) of the `ScaledJob` type which should be polished/improved and implement `ScaledJob Controller` [functionality](https://github.com/kedacore/keda/tree/v2/pkg/controller/scaledjob) 
- There are several issues opened for Job scaling, they should be taken into a consideration when implementing `ScaledJob`: https://github.com/kedacore/keda/issues?q=is%3Aissue+is%3Aopen+job
- Document Spec and behavior: https://github.com/kedacore/keda-docs/issues/163

**Comment by jeffhollan** [comment]
Let me chat with the CSE team that helped with this in v1 and has some customers using to see if they can help

**Comment by jeffhollan** [comment]
Chatted with CSE - they are finishing some hi-pri covid-19 projects so unable to jump in right now.  Working with @anirudhgarg  and @dimberman to see if we can have one of them help fund

**Comment by anirudhgarg** [comment]
Assigning to @TsuyoshiUshio to start having a look at this.

**Comment by TsuyoshiUshio** [comment]
I think I've done. the main part and big issues. I'll fix issue one by one.

**Comment by tomkerkhove** [comment]
It looks like we are missing migration docs as well or is it just me? https://keda.sh/docs/2.0/migration/#scaling-of-jobs
