### ISSUE TITLE
Blank vhost for Rabbitmq Scaler apiHost is erroring out when making api calls

### ISSUE THREAD

**Issue by mpduarte** [kedacore/keda#790]
Blank vhost for Rabbitmq Scaler apiHost is erroring out when making api calls to the queue.

## Expected Behavior
With no vhost specified the api call to RabbitMQ should look like this:
http://guest:guest@rabbitmq:15672/api/queues/%2F/queuename

## Actual Behavior
With no vhost specified the api call to RabbitMQ looks like this:
http://guest:guest@rabbitmq:15672/api/queues/api//queuename

Debug log from Controller:
{"level":"debug","ts":"2020-04-29T00:15:39.676Z","logger":"scalehandler","msg":"Error getting scale decision","ScaledObject.Namespace":"cust0-herald-test","ScaledObject.Name":"celery-scaledobject","ScaledObject.ScaleType":"deployment","Error":"error inspecting rabbitMQ: error requesting rabbitMQ API status: 404 Not Found, response: {\"error\":\"Object Not Found\",\"reason\":\"Not Found\"}, from: http://guest:guest@rabbitmq.cust0-herald-test.svc.cluster.local:15672/api/queues/api//celery"}

## Steps to Reproduce the Problem

  1. Don't specify a vhost in the apiHost setting
  2. Deploy scaledobject without vhost specified

## Specifications

  - KEDA Version: v1.4.1
  - Kubernetes Version: v1.14.8
  - Scaler(s): RabbitMQ

**Comment by tomkerkhove** [comment]
So you're saying that the fix for https://github.com/kedacore/keda/issues/768 is not working out?

**Comment by zroubalik** [comment]
@tbickford @holyketzer seems like RabitMQ scaler needs more love 😄

**Comment by holyketzer** [comment]
@mpduarte which value you provide in `apiHost` ?

1. `http://guest:guest@rabbitmq:15672/`
2. `http://guest:guest@rabbitmq:15672//`
3. `http://guest:guest@rabbitmq:15672/%2F`
They all should work.

One case I'm not sure is `http://guest:guest@rabbitmq:15672`, let me check

**Comment by holyketzer** [comment]
Yes case without trailing slash wasn't covered. @mpduarte you can just add trailing slash to your `apiHost`

**Comment by mpduarte** [comment]
I had a trailing slash, the issue is I had is I specified /api/ at the end, for some reason I thought it was required, once I removed it, everything started working great. appreciate the quick responses!
