### ISSUE TITLE
eventhub scaler not working on new hubs where no storage checkpoint is initialized

### ISSUE THREAD

**Issue by christle** [kedacore/keda#797]
We configure our eventhub scaledObject with a minimum value of 0. When we create new hubs and start messaging, no function is scaling up. The reason is, there is initially no checkpoint until the first function is started.

so we have to delete the scaledObject after deployment and scale manually to 1 to initialize the storage checkpoint. 

## Expected Behavior
When a new hub is created and messages are available, then the eventhub scaler should react with a suitable metric.

## Actual Behavior
the eventhub scaler returns no metric when noch storage checkpoint is available. 

## Steps to Reproduce the Problem

  1. create a new hub and send messages to it
  2. deploy a function with a scaledObject with a min instance value to zero
  3. no function is scaling up, even if messages exists
  4. delete the scaledObject and scale to 1 manually
  5. redeploy the scaledObject and all works normally

## Specifications

  - **KEDA Version: 1.4
  - **Kubernetes Version:** 1.15.7
  - **Scaler(s):** eventhub-scaler

**Comment by tomkerkhove** [comment]
Good point, thanks for reporting and opening a PR!
