### ISSUE TITLE
Deploy FOSSA license scanning

### ISSUE THREAD

**Issue by caniszczyk** [kedacore/keda#808]
We should enable license scanning on this repo:
https://github.com/fossas/fossa-cli

Ihor will take care of this

**Comment by idvoretskyi** [comment]
cc

**Comment by idvoretskyi** [comment]
Added via https://github.com/kedacore/keda/pull/860

**Comment by zroubalik** [comment]
The FOSSA check doesn't work on PRs: https://github.com/kedacore/keda/pull/765#issuecomment-640862523

**Comment by idvoretskyi** [comment]
@zroubalik I'll check it out, thanks for the heads up.

**Comment by idvoretskyi** [comment]
@zroubalik an update on this - I'm already in touch with the FOSSA support team on finding the best possible solution. As of now, the most valid solution would be using the push-only token embedded into the workflow file directly (https://docs.fossa.com/docs/api-reference#push-only-api-token), but I'd like to discover if there are any alternative ways.

**Comment by zroubalik** [comment]
@idvoretskyi thanks for the update!

**Comment by idvoretskyi** [comment]
We've scheduled a call with FOSSA support on Wednesday to discuss the possible solutions, will keep this issue updated on the progress.

**Comment by zroubalik** [comment]
@idvoretskyi any update on this please?

**Comment by idvoretskyi** [comment]
@zroubalik still no major updates, we're speaking with GitHub on this now.

**Comment by zroubalik** [comment]
@idvoretskyi any news? I am planning to disable FOSSA check on PRs if we are not able to solve this in the near future.
Thanks!

**Comment by tomkerkhove** [comment]
I was thinking the same actually 😅

**Comment by idvoretskyi** [comment]
@zroubalik I have a solution to try, let me check and I'll get back to you.
