### ISSUE TITLE
Blob azure function trigger is not able to create hpa and not worki g in keda

### ISSUE THREAD

**Issue by jainshikha** [kedacore/keda#809]
Created new blob trigger azure function tring to deploy in keda... Not working not creating hpa from keda
Using 1.4.1version of keda

**Comment by balchua** [comment]
For a start, will it be possible to include in this issue the `ScaledObject`

**Comment by jainshikha** [comment]
https://github.com/jainshikha/azure-func-blob-trigger-KEDA/tree/feature/120021
in the deploy. yml ScaledObject is already present
please have a look into the deply.yml and docker file

**Comment by zroubalik** [comment]
Could you post KEDA operator logs?

**Comment by jainshikha** [comment]
attaching the logs, after reinstalling KEDA the HPA created but its runing with 1 pod always.
can you please let me know the reason behind it. or what i am doing wrong 


![image](https://user-images.githubusercontent.com/20218527/81841840-a6745280-9568-11ea-9059-3105ca371f47.png)

**Comment by zroubalik** [comment]
There's probably something broken in your KEDA deployment.

could you please post logs from:
- KEDA Operator 
` kubectl logs <KEDA_OPERATOR_POD> -n keda`
- KEDA Metrics server
` kubectl logs <KEDA_METRICS_ADAPTER> -n keda`

(you can find the correct names for KEDA pods by running: `kubectl get pods -n keda`)

**Comment by jainshikha** [comment]
log from  
kubectl logs **keda-operator-577b5f5cdf-mczjv -n keda**

{
	"level": "error",
	"ts": 1589447440.5995634,
	"logger": "scalehandler",
	"msg": "Error getting triggerAuth",
	"ScaledObject.Namespace": "default",
	"ScaledObject.Name": "uts-reporter",
	"ScaledObject.ScaleType": "deployment",
	"triggerAuthRef.Name": "usageblob",
	"error": "TriggerAuthentication.keda.k8s.io \"usageblob\" not found",
	"stacktrace": "github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\ngithub.com/kedacore/keda/pkg/handler.(*ScaleHandler).parseAuthRef\n\tkeda/pkg/handler/scale_handler.go:294\ngithub.com/kedacore/keda/pkg/handler.(*ScaleHandler).parseDeploymentAuthRef\n\tkeda/pkg/handler/scale_deployments.go:149\ngithub.com/kedacore/keda/pkg/handler.(*ScaleHandler).GetDeploymentScalers\n\tkeda/pkg/handler/scale_handler.go:216\ngithub.com/kedacore/keda/pkg/handler.(*ScaleHandler).handleScaleDeployment\n\tkeda/pkg/handler/scale_loop.go:105\ngithub.com/kedacore/keda/pkg/handler.(*ScaleHandler).handleScale\n\tkeda/pkg/handler/scale_loop.go:45\ngithub.com/kedacore/keda/pkg/handler.(*ScaleHandler).HandleScaleLoop\n\tkeda/pkg/handler/scale_loop.go:28"
}

log form **kubectl logs keda-metrics-apiserver-7494ff668c-j28qb -n keda**

Trace[173003298]: [1.235048979s] [1.234998679s] Listing from storage done
I0514 07:07:54.151107       1 trace.go:116] Trace[822128053]: "List /apis/external.metrics.k8s.io/v1beta1/namespaces/default/blobcount" (started: 2020-05-14 07:07:53.44746
5967 +0000 UTC m=+84109.615475039) (total time: 703.624341ms):
Trace[822128053]: [703.56614ms] [703.489139ms] Listing from storage done
I0514 07:09:12.810427       1 trace.go:116] Trace[1240076502]: "List /apis/external.metrics.k8s.io/v1beta1/namespaces/default/blobcount" (started: 2020-05-14 07:09:10.5029
71261 +0000 UTC m=+84186.670980333) (total time: 2.307438991s):
Trace[1240076502]: [2.307393691s] [2.306814985s] Listing from storage done
I0514 07:09:39.461746       1 trace.go:116] Trace[281846414]: "List /apis/external.metrics.k8s.io/v1beta1/namespaces/default/blobcount" (started: 2020-05-14 07:09:38.69611
3387 +0000 UTC m=+84214.864122459) (total time: 765.614865ms):
Trace[281846414]: [765.570464ms] [765.525164ms] Listing from storage done
I0514 07:24:47.159953       1 trace.go:116] Trace[1723531795]: "List /apis/external.metrics.k8s.io/v1beta1/namespaces/default/blobcount" (started: 2020-05-14 07:24:44.8494
72711 +0000 UTC m=+85121.017481783) (total time: 2.310463276s):
Trace[1723531795]: [2.310418075s] [2.310351274s] Listing from storage done
I0514 07:25:03.209842       1 trace.go:116] Trace[657951405]: "List /apis/external.metrics.k8s.io/v1beta1/namespaces/default/blobcount" (started: 2020-05-14 07:25:02.66014
2523 +0000 UTC m=+85138.828151595) (total time: 549.682867ms):
Trace[657951405]: [549.626666ms] [549.580065ms] Listing from storage done
E0514 08:01:17.648182       1 provider.go:126] keda_metrics_adapter/provider "msg"="Cannot get list of ScaledObjects" "error"="etcdserver: request timed out"  "WatchedName
space"=""
E0514 08:01:17.649273       1 provider.go:126] keda_metrics_adapter/provider "msg"="Cannot get list of ScaledObjects" "error"="etcdserver: request timed out"  "WatchedName
space"=""
E0514 08:01:17.650333       1 provider.go:126] keda_metrics_adapter/provider "msg"="Cannot get list of ScaledObjects" "error"="etcdserver: request timed out"  "WatchedName
space"=""
E0514 08:01:17.651424       1 provider.go:126] keda_metrics_adapter/provider "msg"="Cannot get list of ScaledObjects" "error"="etcdserver: request timed out"  "WatchedName
space"=""
E0514 08:01:17.652500       1 provider.go:126] keda_metrics_adapter/provider "msg"="Cannot get list of ScaledObjects" "error"="etcdserver: request timed out"  "WatchedName
space"=""
I0514 08:15:09.617705       1 trace.go:116] Trace[1312770588]: "List /apis/external.metrics.k8s.io/v1beta1/namespaces/default/blobcount" (started: 2020-05-14 08:15:08.9183
81694 +0000 UTC m=+88145.086390766) (total time: 699.305561ms):
Trace[1312770588]: [699.26006ms] [699.220459ms] Listing from storage done
I0514 08:53:15.404842       1 trace.go:116] Trace[1373104207]: "List /apis/external.metrics.k8s.io/v1beta1/namespaces/default/blobcount" (started: 2020-05-14 08:53:14.7114
8669 +0000 UTC m=+90430.879495862) (total time: 693.337651ms):
Trace[1373104207]: [693.29195ms] [693.23785ms] Listing from storage done

**Comment by zroubalik** [comment]
Do you have `usageblob TriggerAuthentication` deployed in the `default` namespace?

**Comment by jainshikha** [comment]
no i dont have any TriggerAuthentication in my default namespace.
but tried to add it ,that leads to more broken KEDA , now m unable to create HPA also
Added following :

```
apiVersion: keda.k8s.io/v1alpha1
kind: TriggerAuthentication
metadata:
  name: reporter
spec:
  podIdentity:
    provider: azure
```
could you share the full sample yml file to deploy azure blob trigger func app in KEDA that i can compare with my existing one. and make it work

**Comment by tomkerkhove** [comment]
For full function guidance I'd recommend going to an Azure function repo; we are independent of that.

I see you've enabled pod identity but this assumes all the right AD permissions are set, did you do that? If not, best to use a secret if you want to cut out that potential issue.

**Comment by jainshikha** [comment]
Hi,
after doing the changes carefull m able to scale the pods with no errors, but the problem is pod are not getting scale down 
refering :
https://techcommunity.microsoft.com/t5/azure-developer-community-blog/keda-and-aks-experiments/ba-p/1162632
found this 
**`"Note that if the handler does not delete the incoming blob, the HPA will never scale down"`**


how can i scale it down ?? i can't delete the data from blob. we need to use the data further.

**Comment by tomkerkhove** [comment]
Then you'll have to move the blob - KEDA cannot make the decision when to scale down because we don't know what your business logic looks like...

What would you expect it to behave then?

**Comment by jainshikha** [comment]
expecting the behave like queue after read is complete/ successful it should scale down.
business logic is like we are sending some files in blob storage which will trigger blob function to reading those file and trigger some http call.
using KEDA :
to scale if no of files are more then after read is complete

**Comment by tomkerkhove** [comment]
The difference between blobs & queue is that when a message is gone from the queue we can see that, but if you don't delete blobs we don't have a way to know you are done with it - What if you failed to process the blob?

That's why we assume you will either move or delete the blob.

> Hence why we have the notice in our docs - https://keda.sh/docs/1.4/scalers/azure-storage-blob/

**Comment by jainshikha** [comment]
after running the blob 
following is the output :
```
info: Function.azure-blob.User[0]
      Python blob trigger function processed blob 
      Name: iot-billing-storage-usage-bucket-rc/strawberry-cherry-blackberry-fruits.jpg
      Blob Size: 227612 bytes
info: Function.azure-blob[0]
      Executed 'Functions.azure-blob' **(Succeeded, Id=95e5f95d-cdb1-4749-abdc-36d9e7029637)**
info: Function.azure-blob[0]
```

can't we use ### (Succeeded, Id=95e5f95d-cdb1-4749-abdc-36d9e7029637) to monitor HPA?

**Comment by tomkerkhove** [comment]
This is application specific so we can't rely on that as we run any kind of workloads, not just Azure Functions.

Sorry man! I think you'll need to move your blobs.. Or do you have another idea @zroubalik @jeffhollan ?

**Comment by jainshikha** [comment]
will soft delete work in that case ?

**Comment by tomkerkhove** [comment]
What I recommend doing is using 2 containers:
- Landing zone for new blobs - You process them and then move to second container.

As an alternative we might be able to use the tags on blobs but don't think we have access to those, right @ahmelsayed ?

**Comment by jainshikha** [comment]
@tomkerkhove  I can try to move to the new blob,  how much it will cost me for move  to 2nd container l!!! If tags can be use as alternative can you suggest me how I can use the tags  @ahmelsayed

**Comment by jainshikha** [comment]
for now i have moved the blobs but please let me know if any other workaround available. 
& the when **_maxReplicaCount_** can be increase for more then 10
closing the issue 
thanks for the support.

**Comment by tomkerkhove** [comment]
Huh, so you are saying more than 10 instances doesn't work?
