### ISSUE TITLE
Cron Scaler to Scale the deployments as per a particular cron schedule.

### ISSUE THREAD

**Issue by ckuduvalli** [kedacore/keda#812]
A clear and concise description of what scaler you'd like to use and how you'd want to use it:

Cron scaler is being developed in order to scale the deployments based on a particular time schedule. Whenever the currentTimestamp is inbetween a start and endTime, we say the scaler is active and inactive in all other times.

  - **Scaler Source:** Deployment replicas from the k8s deployment in the namespace itself.
  - **How do you want to scale:** The cron scaler will scale the pods to the desiredReplicas when the scaler is active. By Active, I mean the timestamp should be between the start and end time specified in the metadata. All the other times, the replicas will be equal to the minReplicaCount
  - **Authentication:** None

**Comment by ckuduvalli** [comment]
By scaler source, I understand something like kafka topic, rabbitmq etc. Please correct me if I am wrong.

**Comment by zroubalik** [comment]
@ckuduvalli yeah scaler source, is the source of the events, as you mentioned eg. kafka topic..)
In this case, I suppose the source would be the cron implementation itself?

There's community call this Thursday https://keda.sh/community/, you can join and we can discuss it.

**Comment by ckuduvalli** [comment]
@zroubalik I have a question regarding my scaler. I implemented a cron scaler. What I am observing is that keda passes the metric to scale up to some value x, but HPA is scaling to some value less than x due to CPU utilization taking over. Is there a way I can have my scaler override the HPA?

**Comment by ckuduvalli** [comment]
> @ckuduvalli yeah scaler source, is the source of the events, as you mentioned eg. kafka topic..)
> In this case, I suppose the source would be the cron implementation itself?
> 
> There's community call this Thursday https://keda.sh/community/, you can join and we can discuss it.

Sure.. I will join the call on Thursday

**Comment by balchua** [comment]
This is interesting and at the same time it doesn't need hpa to determine how many to scale to. Similar to `ScaledJob`.

**Comment by ckuduvalli** [comment]
> This is interesting and at the same time it doesn't need hpa to determine how many to scale to. Similar to `ScaledJob`.

This happened due to my misunderstanding of the metric. Will discuss over the call today.

**Comment by ckuduvalli** [comment]
And I could not add the agenda for cron scaler in the hackmd

**Comment by tomkerkhove** [comment]
Good idea for a scaler if you ask me!
