### ISSUE TITLE
Expose KEDA Metrics Api Server Prometheus Metrics 

### ISSUE THREAD

**Issue by tbickford** [kedacore/keda#823]
It would be nice if the Metrics API Server also exposed Prometheus Metrics similar to how the KEDA Operator does. 
 
### Use-Case

There are really two use cases for exposing some metrics:

1) Debugging or viewing what the actual metric value is. The HPA only provides the average value of the metric.  It would be useful to see the actual value of the metric when determining how the HPA is computing the target average.

2) Error Monitoring/Reporting without using logs. When there are issues getting the external metric it would be good to see if this is occurring and how many times this has happened.

### Specification

Possible metrics - 

- `keda_metrics_apiserver_external_metric{scaledObjectNamespace="prom-test",scaledObjectName="prom-scaled-object",name="prometheus"} 10`

- `keda_metrics_apiserver_external_metric_error_count{scaledObjectNamespace="prom-test",scaledObjectName="prom-scaled-object",name="prometheus"} 2`

- `keda_metrics_apiserver_total_error_count 2`

**Comment by tomkerkhove** [comment]
In terms of general metrics we can use existing exporters to get CPU, et all so we can skip those, right?

**Comment by tbickford** [comment]
@tomkerkhove Good question. I believe those could be skipped as Resource-based metrics can be scraped through other means (ie cAdvisor).

**Comment by zroubalik** [comment]
@ckuduvalli FYI as you were interested in Scaling related Prometheus metrics. Take a look on the draft as well

**Comment by tomkerkhove** [comment]
We can close this one I think, right?

**Comment by zroubalik** [comment]
Fixed in #889
