### ISSUE TITLE
Apache Pulsar Scaler

### ISSUE THREAD

**Issue by vishal-biyani** [kedacore/keda#853]
This is a request for an Apache Pulsar (https://github.com/apache/pulsar) scalar so that Keda users can integrate with Pulsar.

**Comment by tomkerkhove** [comment]
Great idea!

Are you open to contributing this @vishal-biyani ?

**Comment by vishal-biyani** [comment]
Hi, @tomkerkhove I would love to contribute but the next 3 weeks is tough based on my schedule. I will update here when I plan to start this one. In meantime are there any good pointers I should look at apart from existing Scalar implementations?

**Comment by tomkerkhove** [comment]
No worries at all, take your time!

We are always happy to help on the Kubernetes Slack or you can follow this doc: https://github.com/kedacore/keda/blob/master/CREATE-NEW-SCALER.md

**Comment by liangyuanpeng** [comment]
Actually, I am working for Pulsar Scaler. Even before I didn’t notice this issue.

**Comment by tomkerkhove** [comment]
Well if you want to pick it up @liangyuanpeng, just let me know!

**Comment by liangyuanpeng** [comment]
@tomkerkhove  Yes,I am interested in this. Keda and Pulsar are both amazing things , Thank you for your reply!

**Comment by liangyuanpeng** [comment]
You may want to take a look at this blog before Pulsar scaler is finished. [Creating an External Scaler for KEDA](https://medium.com/@krvarma/creating-an-external-scaler-for-keda-31b314b5c4a3)

**Comment by krvarma** [comment]
@tomkerkhove @liangyuanpeng @vishal-biyani I have created an external scaler for KEDA. It can be easily converted to a built-in scaler. Take a look at this https://medium.com/@krvarma/creating-an-external-scaler-for-keda-31b314b5c4a3. Let me know I can work on the conversion and send a PR.

**Comment by tomkerkhove** [comment]
I'm happy with however contributes it so I'll leave it up to you folks to discuss who does what!

**Comment by krvarma** [comment]
@liangyuanpeng @vishal-biyani What you think?

**Comment by vishal-biyani** [comment]
@krvarma I am not working on this ATM so I will leave it to you and @liangyuanpeng

**Comment by turbaszek** [comment]
Hi @krvarma @vishal-biyani @liangyuanpeng any update on this issue? I would love to see Pulsar scaler :)

**Comment by krvarma** [comment]
@turbaszek Since its been long time with no reply from @liangyuanpeng I think it is OK to proceed. I am working on the it and hopefully finish it by couple of weeks. I will keep posing updates.

@tomkerkhove @vishal-biyani

**Comment by tomkerkhove** [comment]
Awesome, thanks!

**Comment by mmussett** [comment]
Any update on this? If not started can I pick this up?

**Comment by tomkerkhove** [comment]
As far as I know, this has not been picked up, thanks for grabbing this one!

**Comment by vivekpd15** [comment]
Do we have a timeline on when this will get merged? We heavily rely on Pulsar and this feature would be of great help.

**Comment by tomkerkhove** [comment]
The PR is still open since it was not ready yet but I've pinged the contributor on #1666

**Comment by vivekpd15** [comment]
Thank you @tomkerkhove.
