### ISSUE TITLE
Outdated Operator SDK version causing bugs

### ISSUE THREAD

**Issue by hmoravec** [kedacore/keda#870]
Currently Operator SDK in version 0.11 [is used](https://github.com/kedacore/keda/blob/3692eca90897a5b5a226fbfe2f0ca72fab2be6ff/go.mod#L35). The latest version [is 0.18](https://github.com/operator-framework/operator-sdk/releases). There have been solved many bugs in meantime, e.g. [not releasing leader lock](https://github.com/operator-framework/operator-sdk/issues/1874#issuecomment-546480687) when the pod with operator is evicted which [was solved in v0.13](https://github.com/operator-framework/operator-sdk/pull/2210#issuecomment-564622818). The latest Operator SDK version should be used.

## Specifications

  - **KEDA Version:** 1.4.1

**Comment by zroubalik** [comment]
We will update Operator SDK version in upcoming KEDA v2. There are multiple dependencies between the components (eg. k8s.io in Metrics server & Operator SDK) which make the update non trivial, so will stay with 0.11 for KEDA v1.

**Comment by hmoravec** [comment]
I see. And when is KEDA v2 planned to be released?

**Comment by zroubalik** [comment]
The (optimistic) plan is to release v2 in a month.

**Comment by zroubalik** [comment]
Fixed in v2
