### ISSUE TITLE
Kafka Scaler e2e tests

### ISSUE THREAD

**Issue by zroubalik** [kedacore/keda#884]
### Use-Case

Implement Kafka Scaler e2e tests the same way there are tests for the other scalers:
https://github.com/kedacore/keda/tree/master/tests

Use Strimzi.io to deploy Kafka on k8s cluster

**Comment by tbickford** [comment]
Hi @zroubalik . Question on this - are there particular reasons to use Strimzi.io's Kafka Operator for this instead of a trimmed down deployment of Kafka (Kafka and Zookeeper)?

**Comment by zroubalik** [comment]
Hi @tbickford no, I just thought that Strimzi could simplify the deployment (it's just a matter of applying a bunch of CRs and Kafka + Kafka topic is up and ready) and would be nice to consume another CNCF project. Do you have any major concerns or objections?

**Comment by tbickford** [comment]
Strimzi looks super cool. One of the concerns I have is an added layer of complexity in debugging the tests or the setup for the tests. If the CRD's are cleaned up in tests, is there a possibility of running into issues with the finalizer? Another concern was that state/PV's were necessary but I see that it supports ephemeral setups which is good. I guess a larger question somewhat related to this would be if the e2e tests should use an ephemeral cluster (correct me if I am wrong but I don't believe the "test" cluster is created and destroyed on each workflow run)?

**Comment by zroubalik** [comment]
I think that we don't have to be afraid of issues with finalizer, if we do the clean up properly (and in the correct order). For me the idea is, that Kafka is going to be installed and uninstalled before/after each test run. And Strimzi is just an Operator, so the added complexity is not that big.

Ephemeral clusters would be awesome from my POV, but as you said - currently we have a long instance. Though I haven't seen any major stability problems or flaky tests so far 🤞 
In case there are going to be this kind of problems, we will have to deal with it for sure!
