### ISSUE TITLE
Behaviour on non active scaling triggers

### ISSUE THREAD

**Issue by nirroz93** [kedacore/keda#886]
Current behaviour is is that when the metric is not available ("unkown") keda scales the deployment to minimum. It will be nice to configure what to do with this case: Not scale at all (leave the previous number of pods), scale to a configurable number of pods or to minumum.

EDIT: Not sure whether this is the isActive (I checked it on 0 min so I got to it but it seems that isActive is to scale form 0 or not). Anyway, keda scales my deployment to zero when metrics are unavailable (checked by changing the promtheus address to wrong address) 

### Use-Case
Option to deal with disaster of Prometheus (or other scalers sources) falling/not responding. 
### Specification

- Option to configure static number of pods (different from minimum) when metrics source is unavailable (trigger is inactive)
- Option to disable the scaling when trigger is inactive (leave the number of pods as it was when it was last active)

**Comment by zroubalik** [comment]
Interesting idea. As you proposed this would require to change the logic of `isActive` and introducing additional logic. 
My concern is, that I am not sure that for all scalers we can distinguish between "unknown" and "not active" state. But I am not sure about this.

**Comment by zroubalik** [comment]
This seems like the same request, am I right? https://github.com/kedacore/keda/issues/965

**Comment by nirroz93** [comment]
Yes, #965 seems like the same problem
