### ISSUE TITLE
Add labels to scaled pods

### ISSUE THREAD

**Issue by raulsh** [kedacore/keda#887]
Add labels to scaled pods when deployment scaled up.

### Use-Case

We need labels to add restrictions or actions based on labels. For example: add pods to specific node group or infrastructure. In my case i'm using Amazon EKS, so I can schedule pods on Fargate infrastructure based on a specific label.  So I can scheduled additional pods on different node group or infrastructure if I need.

### Specification

- [ ] Add custom labels to scaled pods when deployment scaled up

**Comment by zroubalik** [comment]
You can define that in your Deployment under `spec.template.metadata.labels`, there's no need for KEDA to do that.

**Comment by zroubalik** [comment]
Please reopen if you need to.
