### ISSUE TITLE
Issue with api-resources and custom.metrics.k8s.io

### ISSUE THREAD

**Issue by jeffhollan** [kedacore/keda#90]
After deploying via the current `master` branch deploy, things seem to setup ok but when I run `kubectl api-resources` I get the following:

> error: unable to retrieve the complete list of server APIs: custom.metrics.k8s.io/v1beta1: the server could not find the requested resource

Tried on a fresh install and same thing. 

> Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-03-01T23:34:27Z", GoVersion:"go1.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.9", GitCommit:"16236ce91790d4c75b79f6ce96841db1c843e7d2", GitTreeState:"clean", BuildDate:"2019-03-25T06:30:48Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}

**Comment by lee0c** [comment]
@Aarthisk @jeffhollan Is keda actually serving custom metrics? If not, should the custom metrics api be registered if KEDA isn't providing anything there & doesn't intend to?

**Comment by tomkerkhove** [comment]
My bet would be yes given it needs to give input to the HPA, but that's a guess

**Comment by lee0c** [comment]
@tomkerkhove AFAIK keda is only serving external metrics, not custom (there are two separate metric apis for adapters to use).

**Comment by aminebizid** [comment]
Ok for you if I PR to remove the custom metrics?

**Comment by yaron2** [comment]
> Ok for you if I PR to remove the custom metrics?

Not yet please.
@Aarthisk did you get to test KEDA without custom metrics?

**Comment by aminebizid** [comment]
> > Ok for you if I PR to remove the custom metrics?
> 
> Not yet please.
> @Aarthisk did you get to test KEDA without custom metrics?

Keda works great even without custom metrics.

**Comment by Aarthisk** [comment]
https://github.com/kedacore/keda/commit/0cf7c442e780a2d1366ed01991fc4ec0f77dd62b
