### ISSUE TITLE
Provide Azure Key Vault support in TriggerAuthentication

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda#900]
Provide Azure Key Vault support in TriggerAuthentication to pull secrets from.

**Comment by alexandery** [comment]
+1 on this.

**Comment by SebastianSchuetze** [comment]
How would the general approach be? I am a bit confused on how I would need to start on it if I wanted to contribute.

**Comment by tomkerkhove** [comment]
We provide a contribution guide on https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md but I'd ask @zroubalik @ahmelsayed @JorTurFer for more in-depth guidance.

We should, however, document how to add a new authentication source.

**Comment by tomkerkhove** [comment]
This should directly talk to Azure Key Vault as [Azure Key Vault Provider for Secrets Store CSI Driver](https://azure.github.io/secrets-store-csi-driver-provider-azure/) is another scenario to cover that should already work today.

**Comment by SebastianSchuetze** [comment]
still want this feature and I think it should come!

**Comment by tomkerkhove** [comment]
We are happy to review PRs ;)

**Comment by SebastianSchuetze** [comment]
I know. just wanted to keep this open for now 😜

**Comment by v-shenoy** [comment]
I plan on taking this up. @tomkerkhove

**Comment by tomkerkhove** [comment]
Thank you!

**Comment by v-shenoy** [comment]
Got a bit busy with some other work, working on this. Commenting so that the issue doesn't get marked as stale.

**Comment by tomkerkhove** [comment]
No worries, issue won't get stale and take your time - Thanks for the update!

**Comment by v-shenoy** [comment]
Could somebody provide me some more resources I could read up on for adding authentication sources? @tomkerkhove

**Comment by tomkerkhove** [comment]
We don't have any docs on adding auth providers I think, but we should add this.

Or am I mistaken @JorTurFer  @zroubalik ?

**Comment by zroubalik** [comment]
Nope, it's in the code though 😅
