### ISSUE TITLE
Git Repo for e2e source code and container images

### ISSUE THREAD

**Issue by tbickford** [kedacore/keda#930]
It would be nice to have a repo under KEDA that had the corresponding code used in the e2e tests and would also allow the ability to publish container images to the KEDA org

### Use-Case

The objective of this is to move the code and corresponding container images used in e2e tests under KEDA so it is not susceptible to external change.

### Specification

- Create a repository under KEDA for e2e test code
- Allow publication (tagging and pushing) of the built container images to the Docker KEDA repo

**Comment by tomkerkhove** [comment]
I'll get this going! Can you add links for your images to get an idea what they look like?

Once things are set you can then donate if you want!

**Comment by tbickford** [comment]
Great. Thanks @tomkerkhove. I would be more than happy to move anything I have put together into the repo. Some of the existing references:

- https://github.com/kedacore/keda/blob/1374c52bf77bf5c7e21d62ceca2e999e352844ee/tests/scalers/prometheus.test.ts#L140
- https://github.com/kedacore/keda/blob/1374c52bf77bf5c7e21d62ceca2e999e352844ee/tests/scalers/artemis-helpers.ts#L240
- https://github.com/kedacore/keda/blob/1374c52bf77bf5c7e21d62ceca2e999e352844ee/tests/scalers/rabbitmq-helpers.ts#L74
- https://github.com/kedacore/keda/blob/1374c52bf77bf5c7e21d62ceca2e999e352844ee/tests/scalers/redis-streams.test.ts#L236

I am also currently working on submitting a PR for an e2e of the MySQL scaler which will use a custom image (code base). 


-

**Comment by tomkerkhove** [comment]
Perfect! We are good to go and can use - https://github.com/kedacore/test-tools.

Let's open issues there and move things over!

**Comment by tomkerkhove** [comment]
Ok to close or do we need to follow-up on something?
