### ISSUE TITLE
KEDA images built by GitHub Action Release Process are incorrect

### ISSUE THREAD

**Issue by zroubalik** [kedacore/keda#933]
Images produced by GitHub Action Release Process were missing tzdata package,  there should be non-empty directory `/usr/share/zoneinfo` present in the resulting image. This should be installed during docker build: https://github.com/kedacore/keda/blob/1374c52bf77bf5c7e21d62ceca2e999e352844ee/build/bin/user_setup#L13

**Output from the [GitHub Action - Publish Step](https://github.com/kedacore/keda/runs/846083693?check_suite_focus=true):**
```bash
...
microdnf install tzdata-2020a 
 
(microdnf:11): librhsm-WARNING **: 15:00:42.752: Found 0 entitlement certificates 
 
(microdnf:11): librhsm-WARNING **: 15:00:42.755: Found 0 entitlement certificates 
 
(microdnf:11): libdnf-WARNING **: 15:00:42.756: Loading “/etc/dnf/dnf.conf”: IniParser: Can’t open file 
Downloading metadata... 
Downloading metadata... 
Downloading metadata... 
Nothing to do.
...
```

**Expected output from 'make publish':**
```bash
...
microdnf install tzdata-2020a
(process:11): librhsm-WARNING **: 13:28:38.911: Found 0 entitlement certificates
(process:11): librhsm-WARNING **: 13:28:38.914: Found 0 entitlement certificates
Downloading metadata...
Downloading metadata...
Package                    Repository       Size
Upgrading:                                      
 tzdata-2020a-1.el8.noarch ubi-8-baseos 480.3 kB
Transaction Summary:
 Installing:        0 packages
 Reinstalling:      0 packages
 Upgrading:         1 packages
 Removing:          0 packages
 Downgrading:       0 packages
Downloading packages...
Running transaction test...
Updating: tzdata;2020a-1.el8;noarch;ubi-8-baseos
Cleanup: tzdata;2019b-1.el8;noarch;installed
Complete.
...
```

  - **KEDA Version:** 1.5.0

**Comment by zroubalik** [comment]
The same applies to `kedacore/keda:master` or `kedacore/keda-metrics-adapter` images, they are produced by GH Action and are incorrect as well.

**Comment by tomkerkhove** [comment]
So the local file will be what's causing this then? 🤔

**Comment by Diddaa** [comment]
any methods to solve this problem?

**Comment by zroubalik** [comment]
We have changed the build process for v2, so we don't this problem anything.

We can close this one now.
