### ISSUE TITLE
Add e2e test for Cron scaler

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda#935]
Provide end-to-end tests for Cron scaler to ensure everything still works.

https://github.com/kedacore/keda/tree/main/tests

**Comment by tomkerkhove** [comment]
Happy to have @ckuduvalli picking this up as per https://github.com/kedacore/keda/issues/932#issuecomment-658001607

**Comment by JorTurFer** [comment]
I will take a look to this the next week

**Comment by zroubalik** [comment]
Thanks a lot @JorTurFer

**Comment by ckuduvalli** [comment]
I had the test ready
test/scalers/cron.test.ts

import * as fs from 'fs'
import * as sh from 'shelljs'
import * as tmp from 'tmp'
import test from 'ava'

const testNamespace = 'nginx-test'

test.before('Create a deployment', t => {
    sh.config.silent = true
    const tmpFile = tmp.fileSync()
    fs.writeFileSync(tmpFile.name, deployYaml)
    sh.exec(`kubectl create namespace ${testNamespace}`)
    const deployment = sh.exec(`kubectl apply -f ${tmpFile.name}
--namespace ${testNamespace}`).code
    sh.exec('sleep 30s')
    const replicaCount = sh.exec(
        `kubectl get deployment.apps/nginx-deployment-basic --namespace
${testNamespace} -o jsonpath="{.spec.replicas}"`
    ).stdout
    t.is(replicaCount, '2', 'Creating a deployment should work')
})

test.serial('Deployment should have 2 replicas on start', t => {
    sh.exec('sleep 20s')
    const replicaCount = sh.exec(
        `kubectl get deployment.apps/nginx-deployment-basic --namespace
${testNamespace} -o jsonpath="{.spec.replicas}"`
    ).stdout
    t.is(replicaCount, '2', 'replica count should start out as 2')
})

test.serial(`Deployment should scale to 4 (the max) within the start and
end time and then back to 1 (minReplicaCount)`, t => {
    t.is(
        '2',
        sh.exec(
            `kubectl get deployment.apps/nginx-deployment-basic --namespace
${testNamespace} -o jsonpath="{.status.readyReplicas}"`
        ).stdout,
        'There should be 2 replicas for the test-app deployment'
    )

    let options = {
        timeZone: 'Etc/UTC',
        year: 'numeric',
        month: 'numeric',
        day: 'numeric',
        hour: 'numeric',
        minute: 'numeric',
        second: 'numeric',
    }
    const formatter = new Intl.DateTimeFormat([], options)
    const currentDate = new Date(formatter.format(new Date()))

    if(currentDate.getMinutes() >= 54 && currentDate.getMinutes() <= 57) {
        // keda based deployment should start scaling up with http requests
issued
        let replicaCount = '0'
        for (let i = 0; i < 15 && replicaCount !== '4'; i++) {
            replicaCount = sh.exec(
                `kubectl get deployment.apps/nginx-deployment-basic
--namespace ${testNamespace} -o jsonpath="{.spec.replicas}"`
            ).stdout
            if (replicaCount !== '4') {
                sh.exec('sleep 5s')
            }
        }


        t.is('4', replicaCount, 'Desired Replica count should be 4')

        for (let i = 0; i < 60 && replicaCount !== '0'; i++) {
            replicaCount = sh.exec(
                `kubectl get deployment.apps/nginx-deployment-basic
--namespace ${testNamespace} -o jsonpath="{.spec.replicas}"`
            ).stdout
            if (replicaCount !== '1') {
                sh.exec('sleep 10s')
            }
        }

        t.is('1', replicaCount, 'Replica count should be 1 after 5 minutes')
    } else {
        const replicaCount = sh.exec(
            `kubectl get deployment.apps/nginx-deployment-basic --namespace
${testNamespace} -o jsonpath="{.spec.replicas}"`
        ).stdout
        t.is('2', replicaCount, 'Replica count should remain at 2 since
cron scaler has not been triggered')
    }
})

test.after.always.cb('clean up deployment', t => {
    sh.exec(`kubectl delete namespace ${testNamespace}`)
    t.end()
})

const deployYaml = `apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-basic
  namespace: nginx-test
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.17.9
        securityContext:
          runAsUser: 0
        ports:
        - containerPort: 80
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: cron-scaledobject
  namespace: nginx-test
spec:
  scaleTargetRef:
    deploymentName: nginx-deployment-basic
  cooldownPeriod: 60
  pollingInterval: 30
  minReplicaCount: 1
  maxReplicaCount: 100
  triggers:
  - type: cron
    metadata:
      timezone: Etc/UTC
      start: 15 * * * *
      end: 18 * * * *
      desiredReplicas: "4"`

**Comment by ckuduvalli** [comment]
However, I am unable to run it since other azure related tests will fail

**Comment by zroubalik** [comment]
@ckuduvalli so you can temporary disable other tests and run just this one. And then you can open a PR.

**Comment by JorTurFer** [comment]
you can run also this test alone.
If you go inside the tests folder and run `npx ava scalers/yourfile.ts` it will execute only your file
