### ISSUE TITLE
[v2] Improve log output

### ISSUE THREAD

**Issue by TsuyoshiUshio** [kedacore/keda#952]
### Use-Case

When we have several scale object, it is very hard to identify the which is which. This is an example with Azure Storage Queue and RabbitMQ on the same keda. 

![image](https://user-images.githubusercontent.com/1390976/88602534-d7243e00-d027-11ea-9de5-ea16c2126345.png)

### Specification

Probably, we can add scaleObject name or scaler name might help.

**Comment by zroubalik** [comment]
Fixed by #1019
