### ISSUE TITLE
Add custom labels to HPA

### ISSUE THREAD

**Issue by bryanhorstmann** [kedacore/keda#954]
We would like to add custom labels to the HPA created by the ScaledObject. 

### Use-Case

Have consistent labelling across all Kubernetes resources allowing us to attribute resources to teams or create a logical link to services. We rely on these consistent labels for monitoring and reporting.

Currently, I am using `kubectl label hpa` to add these labels.

### Specification

You could duplicate the labels on the ScaledObject. You could read the labels from an annotation on the ScaledObject.

**Comment by tomkerkhove** [comment]
I think we already support it or at least it's coming for v2, can you confirm @ahmelsayed @zroubalik ?

**Comment by bryanhorstmann** [comment]
I had a look in the v2 branch, and couldn't see anything. The labels are defined here: https://github.com/kedacore/keda/blob/v2/pkg/controller/scaledobject/hpa.go#L66-L71

This would be great news if it is coming in v2.

**Comment by zroubalik** [comment]
@bryanhorstmann makes sense. Duplicating the labels sounds like an ideal solution.

**Comment by zroubalik** [comment]
Solved by #989
