### ISSUE TITLE
Visibility by dashboard or prometheus exporter

### ISSUE THREAD

**Issue by nisan270390** [kedacore/keda#958]
At the moment the [dashboard Github repository](https://github.com/kedacore/dashboard) is no longer managed and does not work and we need to have the ability to view details of our Keda deployments such as replicas count, scaling decision events etc.
The solution could be around building a dashboard or prometheus exporter.

**Comment by tomkerkhove** [comment]
We are adding more information to our CRDs and will provide extensibility through Kubernetes events and optionally cloud events. Would that help?

In terms of replica count you can just check the current deployments but I presume you want this all visually displayed?

**Comment by nisan270390** [comment]
I think what's most important to me is visually displayed the external metrics value over time, at the moment I can only see the current value. Another metric that is very important is for each scale object count the amount of reconcile failures.

**Comment by tbickford** [comment]
@nisan270390 Is this PR https://github.com/kedacore/keda/pull/889 similar to what you are looking for?

**Comment by nisan270390** [comment]
@tbickford Exactly what I'm looking for, thank you so much! I'll keep track of your PR
