### ISSUE TITLE
Security changes to our community standup due to Zoom policy

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda#963]
> Important Notice: To enhance the security of single-seat Pro accounts, starting April 5th, meeting passwords and Waiting Rooms will be turned on by default. As the meeting host, there are some steps you may need to take to familiarize yourself with these changes and ensure that your attendees can join your upcoming meetings seamlessly. Please read this article for step-by-step instructions.

Related to this we'll need to enable either passcode or waiting room for our standup

**Comment by tomkerkhove** [comment]
To be discussed during standup.

**Comment by tomkerkhove** [comment]
We'll use password and @jeffhollan will update docs

**Comment by zroubalik** [comment]
We should update the calendar invite then as well.

**Comment by tomkerkhove** [comment]
Jup it's on my radar as well!

**Comment by tomkerkhove** [comment]
@jeffhollan Heads-up, it's almost September!
