### ISSUE TITLE
Migrate to the new Kubebuilder based Operator SDK framework

### ISSUE THREAD

**Issue by zroubalik** [kedacore/keda#969]
From v0.19 Operator SDK project was merged with Kubebuilder, this results in a new project layout (ie. KEDA code layout at build stuff).

We should migrate to the new project structure for v2.

https://sdk.operatorframework.io/docs/golang/quickstart/

**Comment by tomkerkhove** [comment]
Notes from standup yesterday:

> - We are using Operator SDK which is being merged with Kubebuilder, we should check if we can migrate
> - Has no functionality changes but just reshuffling of the code
> - No objections, will be done for 2.0 stable release

**Comment by zroubalik** [comment]
Fixed by #1007
