### ISSUE TITLE
Postgres Scaler compatibility with Jobs

### ISSUE THREAD

**Issue by nbhargava** [kedacore/keda#974]
The Postgres scaler should be usable when trying to scale Jobs.

### Use-Case

It would be great if KEDA could support using Postgres as a queue to spin off new Jobs. In cases where the queue represents long-lived tasks that need to be completed, Jobs may be better suited than scaling up a deployment.

### Specification

The main issue is that `postgreSQLScaler.GetMetrics` reports the `pgMetricName` as the metric name rather than the inputted `metricName`. Following the example of `gcp_pub_sub_scaler.go`, it seems like this might be fixable (and consistent with other scalers) by calculating the metric value from the Postgres query but relaying the metric as whatever was specified in the system.

I'm happy to take a stab at a PR on this.

**Comment by zroubalik** [comment]
@nbhargava good catch! Could you please open a PR with a fix against v2 branch? https://github.com/kedacore/keda/tree/v2

I was quickly looking at other scalers and the same problem is with RabbitMQ and Cron scalers, could you please include this in the PR as well? And check other scalers that I haven't overlooked anything?

Thanks

**Comment by nbhargava** [comment]
Resolved by #984
