### ISSUE TITLE
resolve dns in scaler correctly using ScaledObject namespace rather than keda-operator namespace

### ISSUE THREAD

**Issue by yifan** [kedacore/keda#978]
In ScaledObject we specify dns for hosts of many services, KAFKA, REDIS or RabbitMQ. It is right to assume those dns are being resolved in the same namespace as ScaledObject, not from the namespace of keda-operator.

### Use-Case
I have a set of deployments and ScaledObjects for these deployments. Also I have a redis server. I can deploy all these resources in namespace. I would then deploy exactly the same deployments, redis and ScaledObjects in a different namespace if I need to.

### Specification

- [ ] Scaler should resolve dns/host/address in ScaledObject namespace

**Comment by tomkerkhove** [comment]
Closing in favor of #977 for now
