### ISSUE TITLE
support AAD Pod Identity authentication for azure event hubs

### ISSUE THREAD

**Issue by tdesmet** [kedacore/keda#994]
Blob storage, service bus and storage queue triggers have support for AAD Pod identity authentication. It would be nice to also have this for azure event hubs so we can configure authentication the same way.

### Specification

- [ ] support AAD Pod Identity for authentication on azure event hubs trigger

**Comment by jeffhollan** [comment]
Adding a note here for any coming at it from a good first issue.  I expect what would be required here is:
- follow the same pattern that service bus does (should be a similar Go SDK I imagine) and have the EventHub scaler support an option where podIdentity is passed in https://github.com/kedacore/keda/blob/v2/pkg/scalers/azure_servicebus_scaler.go

**Comment by eashi** [comment]
Anyone working on this one? Maybe I can pick it up if not.

**Comment by zroubalik** [comment]
@eashi I am not aware of that. That would be really awesome if tou could contribute this 🎉

**Comment by eashi** [comment]
On which branch should I do this this btw? I have been working on `master`, but I haven't gone too deep  yet and I can back track if necessary.

**Comment by zroubalik** [comment]
@eashi `v2` please 🙂

**Comment by eashi** [comment]
This is done in [PR 1306](https://github.com/kedacore/keda/pull/1305).
