### ISSUE TITLE
Provide merch for people to buy

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda#997]
Provide merch for people to buy

**Comment by turbaszek** [comment]
Not sure if as CNCF project you have already a place for merch. If not then you may consider
https://www.redbubble.com/people/comdev/shop

That's "official" place for Apache merch 😉

**Comment by tomkerkhove** [comment]
Already have something in the works but thanks for the tip!

**Comment by tomkerkhove** [comment]
Mockups are in the works.

**Comment by turbaszek** [comment]
> Mockups are in the works.

Nice <3

**Comment by tomkerkhove** [comment]
New mockups with the updated logo are in the works

**Comment by tomkerkhove** [comment]
This will most likely be it!
![KEDA-tee-options-v5](https://user-images.githubusercontent.com/4345663/97196109-5f8fb780-17ac-11eb-8ee4-40fe6c0dea76.png)

**Comment by tomkerkhove** [comment]
Happy to share that you can now buy merch on https://bit.ly/keda-merch, but we are looking into providing a nice DNS entry on keda.sh to make it easier to share once @jeffhollan is back from holiday.

**Comment by tomkerkhove** [comment]
You can now buy merch on merch.keda.sh
